### ISSUE TITLE
asyncUI returns Unit, and not a future

### ISSUE THREAD

**Issue by ilya-g** [Kotlin/kotlinx.coroutines#1]
This looks similar to `async void` methods in C#. Generally it's a [discouraged practice](https://msdn.microsoft.com/en-us/magazine/jj991977.aspx) with some exceptions.

I suggest to make it return at least `CompletableFuture<Unit>`

**Comment by elizarov** [comment]
There is no more asyncUI. There's is a choice of `future`, `launch`, and `defer` primitives now.
