### ISSUE TITLE
aAccept() accepts only one connection

### ISSUE THREAD

**Issue by ermine** [Kotlin/kotlinx.coroutines#10]
Does the test unit in AsyncIOTest.kt accept second connection? I cannot guess how to write async accepts in coroutine style properly.

**Comment by elizarov** [comment]
I've added a sample echo server that accepts multiple connections: https://github.com/Kotlin/kotlinx.coroutines/blob/master/kotlinx-coroutines-nio/src/test/kotlin/examples/echo-example.kt

**Comment by elifarley** [comment]
This link doesn't exist anymore...

**Comment by elizarov** [comment]
Moved to: https://github.com/Kotlin/kotlinx.coroutines/blob/master/integration/kotlinx-coroutines-nio/src/test/kotlin/examples/echo-example.kt
