### ISSUE TITLE
consumeEach called twice

### ISSUE THREAD

**Issue by snazhmudinov** [Kotlin/kotlinx.coroutines#1013]
I'm having an issue with consumeEach being called twice.

I have the following code in my view model, which updates the status of the task in Room DAO:

`
val statusActor = actor<Pair<Long, Boolean>> {
        consumeEach {
            launch(context = Dispatchers.IO) {
                val (taskId, taskStatus) = it
                Log.d("TasksViewModel", "$taskStatus")
                tasksRepository.setTaskStatus(taskId, taskStatus)
            }
        }
    }
`
Before I was using the Flowable to handle the stream of events, now I decided to try channels. 

I'm calling it in my activity, every time when the checkbox is tapped (checked/unchecked):

`tasksViewModel.statusActor.offer(Pair(event.taskId, event.status))`

It all seems to work fine, but as my log message says, consumeEach is called twice, with identical boolean values. 

Any ideas what's the flaw here? Or maybe I'm using the actor (and the underlying channel) wrong.

Thanks in advance.

**Comment by elizarov** [comment]
Can you, please, provide some bigger, self-contained example that show the problem.

**Comment by snazhmudinov** [comment]
@elizarov sorry that was my binding bug, issue within the android code. Fixed (and consumeEach behaves properly), going close this one.
