### ISSUE TITLE
[Enhancement]  add `CoroutineScope.asScheduler` and  `CoroutineDispatcher.asScheduler` to kotlinx-coroutines-rx2

### ISSUE THREAD

**Issue by Guang1234567** [Kotlin/kotlinx.coroutines#1024]
Hello dev:

Could you add `CoroutineScope.asScheduler` and  `CoroutineDispatcher.asScheduler` function that
let using coroutine in rxjava is possible.  Thx.

>[kotlinx-coroutines-rx2](https://github.com/Kotlin/kotlinx.coroutines/tree/master/reactive/kotlinx-coroutines-rx2) is only support using rxjava in coroutine now.

**Comment by JakeWharton** [comment]
Dupe of #968?

**Comment by Guang1234567** [comment]
@JakeWharton 

Yes, #968 already has a demo that implement `CoroutineDispatcher.asScheduler`, nice!

but `CoroutineScope.asScheduler` ?

**Comment by qwwdfsad** [comment]
>CoroutineScope.asScheduler

Do you mean just a shorthand for extracting dispatcher from a scope and calling `asScheduler` or a more complex semantics?

**Comment by Guang1234567** [comment]
@qwwdfsad 
more complex semantics.  see #968

**Comment by qwwdfsad** [comment]
Ok, let's keep track there, will close this as duplicate
