### ISSUE TITLE
Investigate possibility to integrate debug module with BlockHound

### ISSUE THREAD

**Issue by qwwdfsad** [Kotlin/kotlinx.coroutines#1031]
https://github.com/reactor/BlockHound/blob/master/docs/custom_integrations.md

We should investigate whether we can opt-in for block hound by default without explicit user actions (besides enabling debugger) or a least to provide a simple switch "detect blocking calls" in the debugger.

**Comment by bsideup** [comment]
FYI this is how Reactor itself now integrates with BlockHound:
https://github.com/reactor/reactor-core/blob/4faaa6e6ebe7671064c89f50a9cbc0495480b219/reactor-core/src/main/java/reactor/core/scheduler/ReactorBlockHoundIntegration.java

(There is no code for Reactor 3.3.x in the BlockHound itself, and reactor-core controls how it should be integrated)

**Comment by elizarov** [comment]
@bsideup Thanks. We'll get back to it after the `Flow` release.

**Comment by bsideup** [comment]
FYI BlockHound 1.0.0.RELEASE is out (on Maven Central):
https://github.com/reactor/BlockHound/releases/tag/1.0.0.RELEASE

**Comment by bsideup** [comment]
I just merged the support for dynamic predicates that should unblock Kotlin from progressing.
It will be released soon, and meanwhile you can try it from our SNAPSHOTs repository (`https://repo.spring.io/snapshot/`, version `1.0.1.BUILD-SNAPSHOT`)

I will appreciate if you give it a try before the release and let us know if there is anything else that blocks you from progressing.
Thanks!
