### ISSUE TITLE
TestMainDispatcher is not set as main dispatcher when Unit Tests are run from gradle

### ISSUE THREAD

**Issue by rafoufoun** [Kotlin/kotlinx.coroutines#1033]
Hello,

I've created a [small project](https://github.com/rafoufoun/coroutineUnitTest) to demonstrate a issue I'm having running Unit Test from gradle. 

I have purposely left only the relevant file to understand and replicate the issue, this Android project can't run on a device.

Here is a description of the issue : 

I have a class that create a coroutine with `launch` inside a scope where the dispatcher is `Dispatcher.Main` : [link here](https://github.com/rafoufoun/coroutineUnitTest/blob/8aef0b418da6be5ae1feefd1fff04a0827d7bf17/app/src/main/java/com/coroutine/timertest/SessionViewModel.kt#L34)
For testing purpose, I've added the dependency to `kotlinx-coroutines-test` and I've set a single thread context inside the unit test file [(`SessionViewModelTest` line 29)](https://github.com/rafoufoun/coroutineUnitTest/blob/8aef0b418da6be5ae1feefd1fff04a0827d7bf17/app/src/test/java/com/coroutine/timertest/SessionViewModelTest.kt#L29).

When I start the unit test file from Android Studio, clicking the 'play' button at the class level, everything runs fine, all the tests pass. 
When I launch a `./gradlew test` from the terminal, the tests fail with this exception : 
```
java.lang.IllegalArgumentException: TestMainDispatcher is not set as main dispatcher, have Main[missing, cause=java.lang.AbstractMethodError: kotlinx.coroutines.android.AndroidDispatcherFactory.hintOnError()Ljava/lang/String;] instead.
	at kotlinx.coroutines.test.TestDispatchers.setMain(TestDispatchers.kt:22)
	at com.rafoufoun.timertest.SessionViewModelTest$Companion.beforeAll(SessionViewModelTest.kt:32)
	at com.rafoufoun.timertest.SessionViewModelTest.beforeAll(SessionViewModelTest.kt)
```

It seems that the ServiceLoader is not properly overwritting `Dispatcher.Main` with a `TestMainDispatcher` when running the tests from gradle.

**Edit** : I've tested this sample on JUnit4 and JUnit5. The issue is the same for both. Sample project uses JUnit5

**Comment by qwwdfsad** [comment]
Hi, it is because you are using inconsistent versions of the integration libraries:
You have `kotlinx-coroutines-core:1.1.1`, `kotlinx-coroutines-test:1.1.1`, but `kotlinx-coroutines-android:1.0.0` (`AbstractMethodError` and `NoClassDefFoundError` usually indicate some binary inconsistency).

Please update `kotlinx-coroutines-android` to `1.1.1` and it will fix your problem.

**Comment by rafoufoun** [comment]
Hi, 

That is a rookie mistake, I didn't pay attention to that. 
Thanks for the quick reply
