### ISSUE TITLE
coroutineScope function causing indefinite suspension in producer

### ISSUE THREAD

**Issue by Evyy** [Kotlin/kotlinx.coroutines#1037]
I looked through the issues but I could not find something related, although perhaps I missed something.

for some reason, using `coroutineScope { ... }` is causing the producer to suspend indefinitely.

from my interpretation of the `coroutineScope` function docs

> The provided scope inherits its [coroutineContext][CoroutineScope.coroutineContext] from the outer scope, but overrides context's [Job].

both of the tests below should be using the same context / dispatcher, but one works as expected, and one suspends indefinitely (on the producer `send` call). 

Maybe I have misunderstood something about how `coroutineScope` works.

I have included the full test that I was using. Any help would be appreciated.

kotlin version: `1.3.21`
coroutines version: `1.1.1`

```kt
import com.google.common.truth.Truth.assertThat
import kotlinx.coroutines.CoroutineScope
import kotlinx.coroutines.ExperimentalCoroutinesApi
import kotlinx.coroutines.GlobalScope
import kotlinx.coroutines.ObsoleteCoroutinesApi
import kotlinx.coroutines.channels.ReceiveChannel
import kotlinx.coroutines.channels.consumeEach
import kotlinx.coroutines.channels.produce
import kotlinx.coroutines.coroutineScope
import kotlinx.coroutines.delay
import kotlinx.coroutines.launch
import kotlinx.coroutines.runBlocking
import kotlinx.coroutines.withTimeout
import org.spekframework.spek2.Spek
import org.spekframework.spek2.style.specification.describe

@UseExperimental(ExperimentalCoroutinesApi::class, ObsoleteCoroutinesApi::class)
class ScopeTest : Spek({

    suspend fun <T> ReceiveChannel<T>.consumeToList(): List<T> = mutableListOf<T>().apply {
        consumeEach { add(it) }
    }

    fun produceInts(count: Int, scope: CoroutineScope): ReceiveChannel<Int> = scope.produce {
        (1..count).forEach {
            delay(50)
            println("sending: $it")
            send(it)
        }
    }

    describe("ScopeTest") {
        it("runs and completes") {
            println("start")
            val intsToProduce = 12

            val workingJob = GlobalScope.launch {
                val intChannel = produceInts(intsToProduce, this@launch)
                val intList = intChannel.consumeToList()
                assertThat(intList).hasSize(intsToProduce)
            }

            runBlocking {
                println("wait for workingJob to complete")
                withTimeout(5000) { workingJob.join() }
            }

            val brokenJob = GlobalScope.launch {
                // produceInts will suspend indefinitely on first send
                val intChannel = coroutineScope { produceInts(intsToProduce, this@coroutineScope) }
                val intList = intChannel.consumeToList()
                assertThat(intList).hasSize(intsToProduce)
            }

            runBlocking {
                println("wait for brokenJob to complete")
                withTimeout(5000) { brokenJob.join() } // timeout will fail
            }
        }
    }
})
```

**Comment by qwwdfsad** [comment]
Take a look at another line in `coroutineScope` KDoc:

>This function returns as soon as given block and all its children coroutines are completed.

So in your example `coroutineScope { produceInts(intsToProduce, this@coroutineScope) }` does not complete until `produceInts` is not completed. But `produceInts` can only be completed when someone consumes the channel (or if the channel is created with sufficient `capacity`).
In your tests you are trying to consume channel in the same coroutine after `coroutineScope` block, thus creating an impossible condition: `coroutineScope` is waiting to be consumed, but channel consumer waits for `coroutineScope` to complete.

Does it help your problem?

**Comment by Evyy** [comment]
@qwwdfsad Thank you so much. Very helpful. Don't know how I missed that.

I appreciate the help!

Closing as solved
