### ISSUE TITLE
CoroutineScope.launch() causing ANR

### ISSUE THREAD

**Issue by jeffdgr8** [Kotlin/kotlinx.coroutines#1038]
**Kotlin v1.3.21**
**Coroutines v1.1.1**

Running our app on a Nexus 6, the device consistently receives an ANR with the following stack trace:

```
kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.tryForbidTermination (CoroutineScheduler.kt:668)
kotlinx.coroutines.scheduling.CoroutineScheduler.tryUnpark (CoroutineScheduler.kt:446)
kotlinx.coroutines.scheduling.CoroutineScheduler.requestCpuWorker (CoroutineScheduler.kt:384)
kotlinx.coroutines.scheduling.CoroutineScheduler.dispatch (CoroutineScheduler.kt:353)
kotlinx.coroutines.scheduling.CoroutineScheduler.dispatch$default (CoroutineScheduler.kt:341)
kotlinx.coroutines.scheduling.ExperimentalCoroutineDispatcher.dispatch (Dispatcher.kt:61)
kotlinx.coroutines.DispatchedKt.resumeCancellable (Dispatched.kt:376)
kotlinx.coroutines.intrinsics.CancellableKt.startCoroutineCancellable (Cancellable.kt:25)
kotlinx.coroutines.CoroutineStart.invoke (CoroutineStart.kt:109)
kotlinx.coroutines.AbstractCoroutine.start (AbstractCoroutine.kt:160)
kotlinx.coroutines.BuildersKt__Builders_commonKt.launch (Builders.common.kt:54)
kotlinx.coroutines.BuildersKt.launch (Unknown Source:1)
kotlinx.coroutines.BuildersKt__Builders_commonKt.launch$default (Builders.common.kt:47)
kotlinx.coroutines.BuildersKt.launch$default (Unknown Source:1)
...
```

The code in our app this stems from is just launching a coroutine on the default dispatcher:

```
private val job = SupervisorJob()
override val coroutineContext: CoroutineContext
    get() = Dispatchers.Main + job
...
fun updateList(...) {
    ...
    launch(Dispatchers.Default) { // <-- this is where the ANR stems from
        ...
    }
}
...
```

Why would this function be so long-running, causing an ANR?

**Comment by qwwdfsad** [comment]
This is interesting.
While this call-chain (dispatch -> requestCpuWorker -> tryUnpark) can spin for a while with unlucky timing, it can't block the thread for a whole five seconds to cause ANR.

It may be a bug, but not something that can be easily fixed and/or understood without a reproducer.
Could you please elaborate on the following questions?

>Running our app on a Nexus 6, the device consistently receives an ANR

Is it reproducible locally during development or even on emulator? How often? Does it happen on application startup or in random moments of time? Is it possible to print `Dispatchers.Default.toString()` during ANR?

Are you using `Dispatchers.IO`?

Is it posiible to localize this issue? E.g. to make a sample application that hangs as well?

**Comment by jeffdgr8** [comment]
This was experienced by one of our backend devs running our Android app on his personal Nexus 6. We have another Nexus 6 test device I could use to test further and attempt to localize the issue. I added code to log `Dispatchers.Default.toString()`, as well as the other dispatchers when an ANR is detected. I'll check further reports for this info.

It was consistently reproducible during app startup on his Nexus 6. It was reported about a dozen times in the ANR detection reporting I have setup. One other report caught it long-running while in the `tryUnpark()` method. Eventually I asked him to wait when the ANR dialog popped up and the app did eventually start.

As I am looking closer at each of the stack traces that were reported, there are slight differences from where they stem from in our code, or even some that stem directly from the system event loop. Many of these places are executed during app startup, although they can also be executed when data changes afterwards. At least one of the stack traces stems from a location in the app that is not present at app startup, so app startup is not a requirement. Some of the stack traces stem from code that does use `Disaptchers.IO`. Others are using `Dispatchers.Default`.

These are the other specific stack traces reported, besides the one above:

This one was reported 4 times:
```
kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.tryForbidTermination (CoroutineScheduler.kt:668)
kotlinx.coroutines.scheduling.CoroutineScheduler.tryUnpark (CoroutineScheduler.kt:446)
kotlinx.coroutines.scheduling.CoroutineScheduler.requestCpuWorker (CoroutineScheduler.kt:384)
kotlinx.coroutines.scheduling.CoroutineScheduler.dispatch (CoroutineScheduler.kt:353)
kotlinx.coroutines.scheduling.CoroutineScheduler.dispatch$default (CoroutineScheduler.kt:341)
kotlinx.coroutines.scheduling.ExperimentalCoroutineDispatcher.dispatch (Dispatcher.kt:61)
kotlinx.coroutines.DispatchedContinuation.resumeWith (Dispatched.kt:104)
kotlinx.coroutines.ResumeModeKt.resumeUninterceptedMode (ResumeMode.kt:43)
kotlinx.coroutines.internal.ScopeCoroutine.onCompletionInternal$kotlinx_coroutines_core (Scopes.kt:28)
kotlinx.coroutines.DispatchedCoroutine.onCompletionInternal$kotlinx_coroutines_core (Builders.common.kt:225)
kotlinx.coroutines.JobSupport.completeStateFinalization (JobSupport.kt:305)
kotlinx.coroutines.JobSupport.tryFinalizeSimpleState (JobSupport.kt:264)
kotlinx.coroutines.JobSupport.tryMakeCompleting (JobSupport.kt:762)
kotlinx.coroutines.JobSupport.makeCompletingOnce$kotlinx_coroutines_core (JobSupport.kt:742)
kotlinx.coroutines.AbstractCoroutine.resumeWith (AbstractCoroutine.kt:117)
kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith (ContinuationImpl.kt:45)
kotlinx.coroutines.DispatchedTask.run (Dispatched.kt:233)
android.os.Handler.handleCallback (Handler.java:751)
android.os.Handler.dispatchMessage (Handler.java:95)
android.os.Looper.loop (Looper.java:154)
android.app.ActivityThread.main (ActivityThread.java:6119)
java.lang.reflect.Method.invoke (Method.java)
com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run (ZygoteInit.java:886)
com.android.internal.os.ZygoteInit.main (ZygoteInit.java:776)
```

This one is not during app startup and was reported once:
```
kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.tryForbidTermination (CoroutineScheduler.kt:668)
kotlinx.coroutines.scheduling.CoroutineScheduler.tryUnpark (CoroutineScheduler.kt:446)
kotlinx.coroutines.scheduling.CoroutineScheduler.requestCpuWorker (CoroutineScheduler.kt:384)
kotlinx.coroutines.scheduling.CoroutineScheduler.dispatch (CoroutineScheduler.kt:353)
kotlinx.coroutines.scheduling.ExperimentalCoroutineDispatcher.dispatchWithContext$kotlinx_coroutines_core (Dispatcher.kt:106)
kotlinx.coroutines.scheduling.LimitingDispatcher.dispatch (Dispatcher.kt:158)
kotlinx.coroutines.scheduling.LimitingDispatcher.dispatch (Dispatcher.kt:148)
kotlinx.coroutines.DispatchedKt.resumeCancellable (Dispatched.kt:376)
kotlinx.coroutines.intrinsics.CancellableKt.startCoroutineCancellable (Cancellable.kt:25)
kotlinx.coroutines.CoroutineStart.invoke (CoroutineStart.kt:109)
kotlinx.coroutines.AbstractCoroutine.start (AbstractCoroutine.kt:160)
kotlinx.coroutines.BuildersKt__Builders_commonKt.launch (Builders.common.kt:54)
kotlinx.coroutines.BuildersKt.launch (Unknown Source:1)
kotlinx.coroutines.BuildersKt__Builders_commonKt.launch$default (Builders.common.kt:47)
kotlinx.coroutines.BuildersKt.launch$default (Unknown Source:1)
```
which stems from this code:
```
private val job = SupervisorJob()
override val coroutineContext: CoroutineContext
    get() = Dispatchers.IO + job
...
private fun loadForm() {
    launch { // <-- this is where the ANR stems from
        ...
    }
}
```

This one was reported once:
```
kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.tryForbidTermination (CoroutineScheduler.kt:668)
kotlinx.coroutines.scheduling.CoroutineScheduler.tryUnpark (CoroutineScheduler.kt:446)
kotlinx.coroutines.scheduling.CoroutineScheduler.requestCpuWorker (CoroutineScheduler.kt:384)
kotlinx.coroutines.scheduling.CoroutineScheduler.dispatch (CoroutineScheduler.kt:353)
kotlinx.coroutines.scheduling.ExperimentalCoroutineDispatcher.dispatchWithContext$kotlinx_coroutines_core (Dispatcher.kt:106)
kotlinx.coroutines.scheduling.LimitingDispatcher.dispatch (Dispatcher.kt:158)
kotlinx.coroutines.scheduling.LimitingDispatcher.dispatch (Dispatcher.kt:148)
kotlinx.coroutines.DispatchedKt.resumeCancellable (Dispatched.kt:376)
kotlinx.coroutines.intrinsics.CancellableKt.startCoroutineCancellable (Cancellable.kt:25)
kotlinx.coroutines.CoroutineStart.invoke (CoroutineStart.kt:109)
kotlinx.coroutines.AbstractCoroutine.start (AbstractCoroutine.kt:160)
kotlinx.coroutines.BuildersKt__Builders_commonKt.async (Builders.common.kt:88)
kotlinx.coroutines.BuildersKt.async (Unknown Source:1)
kotlinx.coroutines.BuildersKt__Builders_commonKt.async$default (Builders.common.kt:81)
kotlinx.coroutines.BuildersKt.async$default (Unknown Source:1)
```
which stems from this code (this is using the same coroutine scope as the original stack trace above):
```
private val job = SupervisorJob()
override val coroutineContext: CoroutineContext
    get() = Dispatchers.Main + job
...
fun bindItem(...) {
    ...
    runCatching {
        async(Dispatchers.IO) { // <-- this is where the ANR stems from
            ...
        }
    }
}
```

The original stack trace above occurred 6 times.

**Comment by jeffdgr8** [comment]
@qwwdfsad has this been looked into at all? We continue to experience a high number of ANRs tied specifically to both `CoroutineScheduler$Worker.tryForbidTermination()` and `CoroutineScheduler.tryUnpark()` being long-running. I have hundreds of stack traces from ANR reports within both of these methods, spanning devices new and old from multiple manufacturers and Android versions. 70% of the reports are from `CoroutineScheduler$Worker.tryForbidTermination()`, while 30% are from `CoroutineScheduler.tryUnpark()`.

I'm not sure the `question` tag fits this issue best. There seems to be a bug causing this code to be long-running. Our app is using the latest 1.3.2 version of coroutines and 1.3.50 version of Kotlin.

Please let me know what I can do to assistant in debugging and resolving this issue.

**Comment by jeffdgr8** [comment]
@qwwdfsad by the way, I did add log statements to print out the dispatchers as you asked.

> Is it possible to print `Dispatchers.Default.toString()` during ANR?

But the output is entirely uninformative. I don't know if this is because it's in a production build, or possibly because the logging is within a Java class and not Kotlin. But this is the output:

```
Dispatchers.Default = DefaultDispatcher
Dispatchers.IO = LimitingDispatcher@be6175[dispatcher = DefaultDispatcher]
Dispatchers.Main = Main
Dispatchers.Unconfined = Unconfined
```

**Comment by qwwdfsad** [comment]
@jeffdgr8 yes, I am working on it in `scheduler-changes` branch, 1.3.3 will have a dispatcher that should have fewer unparks

**Comment by jeffdgr8** [comment]
@qwwdfsad great! Thank you for the update. Looking forward to this release. Thank you for your work on this.

**Comment by qwwdfsad** [comment]
It is likely to be fixed in 1.3.3.
Please upgrade and see if the issue still reproduces, feel free to re-open it if it does

**Comment by jeffdgr8** [comment]
@qwwdfsad thanks! I'll add it to our update going out today and monitor.

**Comment by jeffdgr8** [comment]
@qwwdfsad We haven't received any of these ANRs since the version we updated to 1.3.3. Great work and thanks for fixing this!

**Comment by qwwdfsad** [comment]
Good to know, thanks!
