### ISSUE TITLE
runBlocking in Android/iOS common test

### ISSUE THREAD

**Issue by nicktodd12** [Kotlin/kotlinx.coroutines#1039]
Currently trying to write tests for common code used by an Android and iOS app.  I currently have a test which looks something like this:

    @Test
    fun testRsvpAndAnalytics() =  runBlocking {
        val eventModel = EventModel()
        eventModel.toggleRsvp(true)
        assertTrue { analyticsApiMock.logCalled }
    }

 and I need to call a coroutine which looks like the following in order to do my test:

    fun toggleRsvp(rsvp: Boolean) = launch {
        //do some stuff
    }

unfortunately I can't get this to work since runBlocking is not found regardless of which coroutines library I try to add.  Is there a way to use runBlocking in this scenario or to get a test like this working correctly in some other way for an Android and iOS project?  Thanks for the help.

**Comment by qwwdfsad** [comment]
> Is there a way to use runBlocking in this scenario or to get a test like this working correctly in some other way for an Android and iOS project?

Yes. Define `expect fun runBlocking ...` in your common source sets with actual implementations that delegate to `runBlocking` from kx.coroutines.

Common `runBlocking` is not present in `kotlinx.coroutines` because it cannot be reasonably implemented in JS

**Comment by nicktodd12** [comment]
Thanks, just wanted to confirm it was required since I only saw this question in reference to Java and JS projects.  I wasn't sure if mobile projects were the same.

**Comment by nicktodd12** [comment]
@qwwdfsad 

I tried this approach and the code inside of the coroutine still is being ignored, even when debugging.  I attempted to follow along with the examples related to JVM and JS.  In my common test I have:

    expect fun <T> runTest(block: suspend () -> T)

In both my Android test and iOS tests I have:

    actual fun <T> runTest(block: suspend () -> T) { runBlocking { block() } }

and I use this in my test

    @Test
    fun testRsvpAndAnalytics() = runTest {
        val eventModel = EventModel()
        eventModel.toggleRsvp(true)
        assertTrue { analyticsApiMock.logCalled }
    }

Not sure what I'm missing.

**Comment by qwwdfsad** [comment]
What does "code inside of the coroutine still is being ignored" mean? 
What have you seen in the debugger? Did it step into `runBlocking`? Does basic `runTest {  println("foo") }` print something?

Sorry, but I can't help you with a description "something does not work".

I can't point to a specific problem if you will provide a **self-contained** reproducer though

**Comment by nicktodd12** [comment]
I apologize for the vagueness of the question.  I wasn't sure if there was something obviously wrong with my implementations of runTest.  What I meant was that the test executes correctly but fails during my assert statement.  

All the lines inside of runTest are called; however, if I put any breakpoints inside of launch, none of those are hit during debugging.  This is the same behavior I was having before adding runBlocking or runTest.

**Comment by gildor** [comment]
@nicktodd12 It's hard to tell why your assert failed because you didn't show any examples what this code does, looks like that you do something asynchronous under the hood, so your `logCalled` is not triggered yet, but it's just a guess, also I believe this problem is not related to your original question about runBlocking in common code
