### ISSUE TITLE
Exception Constructor parameters getting mixed up in tryCopyException when thrown from rxJava Single

### ISSUE THREAD

**Issue by rpmoore** [Kotlin/kotlinx.coroutines#1040]
I have some code that after upgrading to v1.1.1 started to have some weird behaviors.  I tracked it town to what I believe to be some assumptions made in the `tryCopyException` method in `ExceptionsConstructor.kt`

To explain more what exactly I'm seeing, I have an exception:

```kotlin
class IndexException(val name: String, t: Throwable? = null) :
    RuntimeException("Index $name does not exist", t)
```

If that exception happens to be thrown from inside of an `rxJava Single`, with an `await()` inside of a coroutineContext (we're migrating some code away from rxJava to coroutines), the exception will end up not being the same when thrown from the `await()`

For example:
```kotlin
import io.reactivex.Single
import kotlinx.coroutines.runBlocking
import kotlinx.coroutines.rx2.await
import org.assertj.core.api.Assertions.assertThat
import org.assertj.core.api.Assertions.catchThrowableOfType
import org.junit.Test

class IndexException(val name: String, t: Throwable? = null) :
    RuntimeException("Index $name does not exist", t)
class Exception_Testing{

    @Test
    fun test() {
        val error = catchThrowableOfType({
            runBlocking {
                Single.error<IndexException>(IndexException("indexName", Exception())).await()
            }
        }, IndexException::class.java)

        assertThat(error.name).isEqualTo("indexName") // this fails in my setup
    }
}
```

I'm using rxJava version 2.2.7, Kotlin 1.3.21, Coroutine 1.1.1

To get around this for now I've introduced an inline class to introduce a new type for the `indexName`.

This worked in v1.0.1 and I confirmed that the new behavior starts in 1.1.0

**Comment by qwwdfsad** [comment]
Hi, this is [stacktrace recovery](https://github.com/Kotlin/kotlinx.coroutines/blob/develop/docs/debugging.md#stacktrace-recovery) that is enabled by default in unit tests.
To workaround it, you can explicitly disable stacktrace recovery.

Your particular problem is fixed in 4ba30cdd0c8b24fe620d9c5500deeda6fbe62049 (in not-yet released 1.2.0)
