### ISSUE TITLE
Extend channel API to have parity with FluxSink

### ISSUE THREAD

**Issue by qwwdfsad** [Kotlin/kotlinx.coroutines#1042]
When integrating with blocking API, channel and `offer` or its variants are used (see also #974). Semantically, it is very similar to [`FluxSink`](https://projectreactor.io/docs/core/release/api/reactor/core/publisher/FluxSink.html).

Moreover, in cold streams prototype channels [are used](https://github.com/qwwdfsad/FlowPlayground/blob/master/src/main/kotlin/examples/FlowFromCallback.kt#L22) to connect with callback-based API.

But at least one important method is missing: [`isCancelled`](https://projectreactor.io/docs/core/release/api/reactor/core/publisher/FluxSink.html#isCancelled--).
A good example of why it is needed can be found [here](https://www.tikalk.com/posts/2017/12/11/reactive-made-simple/). Additionally, we may want to include an actual exception.

**Comment by elizarov** [comment]
This is also related to #974. There needs to be a way to `offer` without exception on a closed channel.

**Comment by qwwdfsad** [comment]
Fixed with `channelFlow`
