### ISSUE TITLE
Async isn't working in some overrided methods

### ISSUE THREAD

**Issue by anonym24** [Kotlin/kotlinx.coroutines#1052]
E.g. async block is never called in the next example:

             object: Animation.AnimationListener {
                override fun onAnimationRepeat(animation: Animation?) {  }

                override fun onAnimationEnd(animation: Animation?) {
                    launch {
                        delay(25)
                        Log.i(TAG, "onAnimationEnd kotlinx.coroutines")
                        // is never called
                    }

                    App.handler.postDelayed(Runnable {
                        Log.i(TAG, "onAnimationEnd handler of main loop")
                        // works fine
                    }, 25)
                }

                override fun onAnimationStart(animation: Animation?) { }
            }

I use Android + kotlinx.coroutines

`class MainActivity : AppCompatActivity(), CoroutineScope,`

```
private val parentJob = Job()

override val coroutineContext: CoroutineContext
get() = Dispatchers.Main + parentJob
```

`ext.kotlin_version = '1.3.21'`

    implementation "org.jetbrains.kotlin:kotlin-stdlib-jdk8:$kotlin_version"
    implementation 'org.jetbrains.kotlinx:kotlinx-coroutines-core:1.1.0'
    implementation 'org.jetbrains.kotlinx:kotlinx-coroutines-android:1.1.0'

**Comment by qwwdfsad** [comment]
Hi, it is not clear without a reproducer what exactly is not working as expected.
E.g. when `onAnimationEnd` is called and in which activity, etc.
Could you please provide a self-contained reproducer which exposes the issue?

**Comment by anonym24** [comment]
I'll just make an simple app project later

**Comment by qwwdfsad** [comment]
Closing as outdated
