### ISSUE TITLE
Dead link to CoroutineScope factory in CoroutineScope documentation

### ISSUE THREAD

**Issue by baltiyskiy** [Kotlin/kotlinx.coroutines#1062]
CoroutineScope documentation (https://kotlin.github.io/kotlinx.coroutines/kotlinx-coroutines-core/kotlinx.coroutines/-coroutine-scope/index.html) has a dead link for CoroutineScope factory function: https://kotlin.github.io/kotlinx.coroutines/kotlinx-coroutines-core/kotlinx.coroutines/-coroutine-scope/index.md

**Comment by elizarov** [comment]
Unfortunately, it is a limitation in Dokka. See https://youtrack.jetbrains.com/issue/KT-19765

**Comment by qwwdfsad** [comment]
The issue in Dokka is still here, but we do no longer have a deadlink
