### ISSUE TITLE
Delay bug using Dispatchers.Main coroutine inside runBlocking

### ISSUE THREAD

**Issue by darek607** [Kotlin/kotlinx.coroutines#1066]
I'm experimenting with Robolectric Unit tests on Android and noticed a strange behavior.  See complete example: "task 2" is not printed. 

- When I remove delay(100) it works. 
- When I change dispatcher to Default or Global it works 

```
@RunWith(RobolectricTestRunner::class)
@Config(manifest = Config.NONE)
class TestSample {

    @Test
    fun testMainDispatcher() {
        val job = Job()
        val scope = CoroutineScope(Dispatchers.Main + job)

        runBlocking {
            scope.launch {
                println("task 1")
            }
            scope.launch {
                delay(100)
                println("task 2") //not reached
            }
            delay(3000) //wait for all results
        }
    }
}
```

**Comment by qwwdfsad** [comment]
It is because `delay` on Android uses `postDelayed` and Robolectric does not compute it by default.
You can use `ShadowLooper.runUiThreadTasksIncludingDelayedTasks();` to make your example work.

**Comment by darek607** [comment]
You are probably right, but `ShadowLooper.runUiThreadTasksIncludingDelayedTasks();` didn't help.

**Comment by qwwdfsad** [comment]
It works on Robolectric `4.0-alpha-3`: https://screencast.com/t/EghferuPHF
There are other approaches as well: https://stackoverflow.com/questions/24642049/android-testing-handler-postdelayed

Unfortunately, I cannot help any further without a self-contained reproducer.

**Comment by darek607** [comment]
Ok, it's actually working. I put `runUiThreadTasksIncludingDelayedTasks` in wrong place. Thank you very much for help!

**Comment by charlesng** [comment]
I got the same issues when I have the tests share for both unit test and instrument test in robolectric. I solved it by injecting Dispatcher and override the main Dispatcher in rule. It makes the test more clean. Hope can help some people like me.
