### ISSUE TITLE
Is this safe to store Continuation objects

### ISSUE THREAD

**Issue by Coneys** [Kotlin/kotlinx.coroutines#1067]
Hello! Is this possible to store continuations in some list? I mean, is this safe?

Let's say I have suspend function, which will wait for some listener and then return boolean:

```
suspend fun requestSomething(requestTag: String): Boolean {

        return suspendCoroutine {

            object : SomeListener() {
                override fun onReady(boolean: Boolean) {
                    it.resume(boolean)
                }
            }
        }
    }
```

But when a few requests with the same tag are added, I don't want to create new Listeners, just have one SomeListener for one tag, and store continuations to resume them later.

It works for me, but I wanted to be sure that this is safe, and I don't break some internal coroutine contract.

**Comment by SeekDaSky** [comment]
Storing Continuations is safe, simply make sure not to resume them multiple times or it will throw

**Comment by qwwdfsad** [comment]
Yes, it is safe as long as you resume each individual continuation once.

**Comment by qwwdfsad** [comment]
I am closing this one.
Feel free to reopen if you still have any questions
