### ISSUE TITLE
Unresolved reference on sample from website

### ISSUE THREAD

**Issue by bernaferrari** [Kotlin/kotlinx.coroutines#1071]
This:
```kotlin
val activity = Activity()
activity.doSomething() // run test function
println("Launched coroutines")
delay(500L) // delay for half a second
println("Destroying activity!")
activity.destroy() // cancels all coroutines
delay(1000) // visually confirm that they don't work
```
causes:
`Unresolved reference. None of the following candidates is applicable because of receiver type mismatch: public fun CoroutineContext.cancel(): Unit defined in kotlinx.coroutines @Deprecated @ObsoleteCoroutinesApi public fun CoroutineContext.cancel(cause: Throwable? = ...): Boolean defined in kotlinx.coroutines
`
here: https://kotlinlang.org/docs/reference/coroutines/coroutine-context-and-dispatchers.html

**Comment by qwwdfsad** [comment]
cc @AlexanderPrendota

**Comment by qwwdfsad** [comment]
Fixed, thanks for reporting!
