### ISSUE TITLE
JavaFX Toolkit init problem (NoClassDefFoundError)

### ISSUE THREAD

**Issue by rjhdby** [Kotlin/kotlinx.coroutines#108]
Trying run [simple JavaFX application](https://github.com/Kotlin/kotlinx.coroutines/blob/master/ui/kotlinx-coroutines-javafx/src/test/kotlin/guide/example-ui-basic-03.kt) with coroutines but it's fail to run at line `    val job = launch(UI) { // launch coroutine in UI context`

> Exception in Application start method
> Exception in thread "main" java.lang.RuntimeException: Exception in Application start method
> 	at com.sun.javafx.application.LauncherImpl.launchApplication1(LauncherImpl.java:917)
> 	at com.sun.javafx.application.LauncherImpl.lambda$launchApplication$155(LauncherImpl.java:182)
> 	at java.lang.Thread.run(Thread.java:745)
> Caused by: java.lang.NoClassDefFoundError: kotlin/coroutines/experimental/CoroutineContext$Element$DefaultImpls
> 	at kotlinx.coroutines.experimental.Job$DefaultImpls.fold(Job.kt)
> 	at kotlinx.coroutines.experimental.JobSupport.fold(Job.kt:378)
> 	at kotlin.coroutines.experimental.CoroutineContextImplKt.plusImpl(CoroutineContextImpl.kt:119)
> 	at kotlin.coroutines.experimental.CoroutineContextImplKt.access$plusImpl(CoroutineContextImpl.kt:1)
> 	at kotlin.coroutines.experimental.AbstractCoroutineContextElement.plus(CoroutineContextImpl.kt:34)
> 	at kotlinx.coroutines.experimental.AbstractCoroutine.<init>(AbstractCoroutine.kt:35)
> 	at kotlinx.coroutines.experimental.StandaloneCoroutine.<init>(Builders.kt:158)
> 	at kotlinx.coroutines.experimental.BuildersKt.launch(Builders.kt:60)
> 	at kotlinx.coroutines.experimental.BuildersKt.launch$default(Builders.kt:54)
> 	at guide.ui.basic.example03.ExampleAppKt.setup(ExampleApp.kt:66)
> 	at guide.ui.basic.example03.ExampleApp.start(ExampleApp.kt:61)
> 	at com.sun.javafx.application.LauncherImpl.lambda$launchApplication1$162(LauncherImpl.java:863)
> 	at com.sun.javafx.application.PlatformImpl.lambda$runAndWait$175(PlatformImpl.java:326)
> 	at com.sun.javafx.application.PlatformImpl.lambda$null$173(PlatformImpl.java:295)
> 	at java.security.AccessController.doPrivileged(Native Method)
> 	at com.sun.javafx.application.PlatformImpl.lambda$runLater$174(PlatformImpl.java:294)
> 	at com.sun.glass.ui.InvokeLaterDispatcher$Future.run(InvokeLaterDispatcher.java:95)
> 	at com.sun.glass.ui.win.WinApplication._runLoop(Native Method)
> 	at com.sun.glass.ui.win.WinApplication.lambda$null$148(WinApplication.java:191)
> 	... 1 more
> Caused by: java.lang.ClassNotFoundException: kotlin.coroutines.experimental.CoroutineContext$Element$DefaultImpls
> 	at java.net.URLClassLoader.findClass(URLClassLoader.java:381)
> 	at java.lang.ClassLoader.loadClass(ClassLoader.java:424)
> 	at sun.misc.Launcher$AppClassLoader.loadClass(Launcher.java:331)
> 	at java.lang.ClassLoader.loadClass(ClassLoader.java:357)
> 	... 20 more

Use `kotlinx-coroutines-core-0.18` and `kotlinx-coroutines-javafx-0.18`

**Comment by elizarov** [comment]
Thanks for report. `JavaFx` worked only inside JavaFx app. Fixed in `develop` branch by initializing JavaFx toolkit on the first use of `JavaFx` dispatcher.

**Comment by elizarov** [comment]
Released in version 0.19
