### ISSUE TITLE
ReceiveChannel.consumeEach { … } replacement?

### ISSUE THREAD

**Issue by LouisCAD** [Kotlin/kotlinx.coroutines#1080]
In 1.2.0-alpha2, after `Flow` initial release, the much useful `consumeEach` function is still annotated with `@ObsoleteCoroutinesApi` and referencing the issue #254, without indications on its replacement.

Is `consumeEach` here to stay, is there a replacement that is already here, or is a replacement planned (or in the works)?

**Comment by elizarov** [comment]
There is no decision yet. Thanks for raising this issue.

**Comment by qwwdfsad** [comment]
Decisions:
- Promote `consumeEach` on `ReceiveChannel` to experimental API along with #167 
- Deprecate `consumeEach` on Rx-like primitives and provide `collect` replacement instead
- Deprecate `consumeEach` along with `BroadcastChannel` when replacement (#1082) is here
