### ISSUE TITLE
in android DialogFragment synthetic cannot find View

### ISSUE THREAD

**Issue by yaosongqwe** [Kotlin/kotlinx.coroutines#109]
in android DialogFragment synthetic cannot find View
logger tell me that's a null pointer

**Comment by yaosongqwe** [comment]
Maybe I send the wrong place, but I didn't find 'kotlinx. android. synthetic' corresponding lot projects

**Comment by yole** [comment]
This is indeed the wrong place. Please ask a question on the [forums](https://discuss.kotlinlang.org/).
