### ISSUE TITLE
coroutines not work well with SurfaceView case

### ISSUE THREAD

**Issue by leagmain** [Kotlin/kotlinx.coroutines#1093]
Recently, I create a SurfaceView and a Render class, render class is extends from CoroutineScope, and it's very simple, let me show you the show method below.
```
fun start() {
  if (isRendering.compareAndSet(false, true)) {
    launch {
      while(isRendering.get()) {
        // rendering stuff, lock and unlock
      }
    }
  }
}
```
This seems normally, but, it will make UI stuck, but not ANR. I user profile tool from android studio to check the CPU time of the thread, UI will wait for the ReentrantLock on SurfaceView and Coroutine also try to lock and unlock, this is for sure I was do the right stop in onSurfaceDestroy() method.

Which made me wired is that, after I change the launch to `thread {}`, it works fine. I really don't understand, I would be very happy if some one can explain this to me :)

One more thing, you will not see the stuck obviously in debug mode, but if you run the release build, WOW, stucks in fragment transition.......

**Comment by elizarov** [comment]
I looks like your `start` function just blocks thread thread it is invoked from, so it prevents any other useful work from being done there. So, you either need to do `thread {}` or launch a coroutine in background thread. Can you please clarify how that's related to `CoroutineScope` implementation?
