### ISSUE TITLE
SuspendCancellableCoroutine issue

### ISSUE THREAD

**Issue by halimpuckjava** [Kotlin/kotlinx.coroutines#1098]
hi

```
suspend fun ServerSocket.listening() = suspendCancellableCoroutine<Socket> {
    it.resume(accept())
    it.invokeOnCancellation { println("coroutine is canceling...."); close() }
}

fun main() = runBlocking {
    val job = launch {
        val server = ServerSocket(3000)
        server.listening()
    }
    delay(3000)
    job.cancel()
}
```

i expected after 3 sec coroutine is cancelled and throws an cancellationexception and server is close but not think happen and server still running after 3 sec

**Comment by elizarov** [comment]
`accept` if a blocking function. You cannot cancel it this way. Cancellation in coroutines in cooperative as explained here: https://kotlinlang.org/docs/reference/coroutines/cancellation-and-timeouts.html

Does it help?

**Comment by halimpuckjava** [comment]
thanks
```
val job = launch {
        val server = ServerSocket(3000)
        //server.listening()
        while(isActive) {
            server.accept()
        }
    }
```

does't work !!

**Comment by elizarov** [comment]
Yes. `accept()` is a blocking method and it does not support cancellation.

**Comment by halimpuckjava** [comment]
1.  any idea to fix that with coroutines ?? 
2.  how about use cases of suspendCancellableCoroutine

**Comment by streetsofboston** [comment]
@halimpuckjava 
What about something like this:
```
val SocketException.socketHasBeenClosed : Boolean get() = TODO()

suspend fun ServerSocket.listening() = suspendCancellableCoroutine<Socket> {
    it.invokeOnCancellation { try { close() } catch (e: Throwable){} }
    thread {
        try {
            it.resume(accept())
        } catch (e: SocketException) {
            if (e.socketHasBeenClosed) {
                it.cancel()
            }
            else {
                it.resumeWithException(e)
            }
        }
    }
}
```

**Comment by elizarov** [comment]
If you want to make a non-blocking use of `accept` you don't need to create a thread yourself, just do this:

```
withContext(Dispatchers.IO) {
    socket.accept()
}
```

This way the caller is not going to be blocked. However, it will not be cancellable. Indeed, you can make it "cancellable" by closing socket on cancelled. There is not way to abort `accept()`, yet keep the socket open. You need asynchronous API (like `java.nio`) for that.

**Comment by halimpuckjava** [comment]
thanks,
