### ISSUE TITLE
[Request] Netty/Undertow async http example

### ISSUE THREAD

**Issue by danneu** [Kotlin/kotlinx.coroutines#11]
I've been playing with async/await and studying the examples out of curiosity, but I'm having trouble making the leap to interop with existing frameworks.

I think a great addition to this repo would be a hello world demonstration of an async http handler that makes a fake database call `val user = await(db.getUser())` to generate some toy html `<!doctype html><div>hello ${user.name}</div>` and then does the async write to the response.

A basic example with Netty or Undertow would help illuminate interop, the necessary boilerplate, and what the end result abstraction could look like.

**Comment by danneu** [comment]
Actually, kind of a dumb request.

**Comment by christophsturm** [comment]
why do you think its a dumb request?
