### ISSUE TITLE
production use

### ISSUE THREAD

**Issue by Jaware** [Kotlin/kotlinx.coroutines#110]
can coroutines be used in production? when will the realease version be published?

**Comment by elizarov** [comment]
Coroutines can and should be used in production. They are **released** as a part of the Kotlin 1.1 and come with 100% backwards compatibility guarantees. 
* You get more details on this presentation slide: https://www.slideshare.net/elizarov/introduction-to-kotlin-coroutines/33
* Full video is here: https://vimeo.com/221264980

The "experimental" status of coroutines simply means that we are actively gathering feedback and will tweak design at some later point, while still supporting the original coroutines release in the "experimental" packages. You can get more details on our reasoning in this lengthly explanation by Andrey Breslav in the forum post: 
https://discuss.kotlinlang.org/t/experimental-status-of-coroutines-in-1-1-and-related-compatibility-concerns/2236

I'm keeping this issue open as a reminder to update the corresponding the kotlinlang doc site pages with more details.

**Comment by Jaware** [comment]
thanks，i  have already used it,spring web flux+kotlin coroutines are very awesome

**Comment by elizarov** [comment]
There is an expanded answer on this question on stackoverflow now: https://stackoverflow.com/questions/46240236/can-experimental-kotlin-coroutines-be-used-in-production/46240340
