### ISSUE TITLE
The result of running example-context-11.kt (Thread-local data) on playground differs from what is stated in the tutorial

### ISSUE THREAD

**Issue by mTwTm** [Kotlin/kotlinx.coroutines#1100]
In the [tutorial](https://kotlinlang.org/docs/reference/coroutines/coroutine-context-and-dispatchers.html#thread-local-data), it says:
```
Pre-main, current thread: Thread[main @coroutine#1,5,main], thread local value: 'main'
Launch start, current thread: Thread[DefaultDispatcher-worker-1 @coroutine#2,5,main], thread local value: 'launch'
After yield, current thread: Thread[DefaultDispatcher-worker-2 @coroutine#2,5,main], thread local value: 'launch'
Post-main, current thread: Thread[main @coroutine#1,5,main], thread local value: 'main'
```
is expected.
But running [this](https://github.com/kotlin/kotlinx.coroutines/blob/master/kotlinx-coroutines-core/jvm/test/guide/example-context-11.kt) I've received:
```
Pre-main, current thread: Thread[main @coroutine#1,5,main], thread local value: 'main'
Launch start, current thread: Thread[DefaultDispatcher-worker-2 @coroutine#2,5,main], thread local value: 'launch'
After yield, current thread: Thread[DefaultDispatcher-worker-2 @coroutine#2,5,main], thread local value: 'launch'
Post-main, current thread: Thread[main @coroutine#1,5,main], thread local value: 'main'
```
When executing the code, the worker before and after yield are the same.

**Comment by qwwdfsad** [comment]
Default dispatcher has no guarantees on a particular thread where execution happens.
This is similar to a Java `Executor`: when you invoke `execute(Runnable {})` you have no guarantees on what particular thread of the executor you task will be scheduled.

`ThreadLocal.asContext` does not provide guarantees on threads as well, it only guarantees that coroutine is able to read its value via original thread local. How exactly does it happen is an implementation detail.

Does it answer your question?

**Comment by mTwTm** [comment]
Thanks for the detailed answer! I think that makes sense but my concern is more about if the thread that `@coroutine#2,5,main` is run on never changed then it is also not illustrating what is covered in that part of tutorial: how threadlocal keeps even when a coroutine have switched to another thread. Will it make more sense to change from
```
val job = launch(Dispatchers.Default + threadLocal.asContextElement(value = "launch")) {
    println("Launch start, current thread: ${Thread.currentThread()}, thread local value: '${threadLocal.get()}'")
    yield()
```
to
```
val job = launch(Dispatchers.Unconfined + threadLocal.asContextElement(value = "launch")) {
    println("Launch start, current thread: ${Thread.currentThread()}, thread local value: '${threadLocal.get()}'")
    delay(100)
```
?

Which outputs:
```
Pre-main, current thread: Thread[main @coroutine#1,5,main], thread local value: 'main'
Launch start, current thread: Thread[main @coroutine#2,5,main], thread local value: 'launch'
After yield, current thread: Thread[kotlinx.coroutines.DefaultExecutor @coroutine#2,5,main], thread local value: 'launch'
Post-main, current thread: Thread[main @coroutine#1,5,main], thread local value: 'main'
```
that has a guaranteed thread change?

**Comment by qwwdfsad** [comment]
This may be a good idea, I will play with it a bit and probably fix the sample.
Thanks for spotting it!
