### ISSUE TITLE
Can't use `1.2.0` without GRADLE_METADATA

### ISSUE THREAD

**Issue by soywiz** [Kotlin/kotlinx.coroutines#1105]
I used to use `1.1.1` without GRADLE_METADATA, by manually including the targets like this:
https://github.com/korlibs/korio/blob/846eee4e199b57933b2b0bb2576e9e8382e750d8/korio/build.gradle#L14

I have updated the artifact names to match the new ones, and intellij is able to find them, but when compiling the compiler can't find the symbols in the kotlinx.coroutines library:
https://travis-ci.org/korlibs/korio/jobs/520054747#L541

https://travis-ci.org/korlibs/korio/jobs/520814024

Adding `enableFeaturePreview('GRADLE_METADATA')` to my settings.gradle fixes the issue, but then I would have to do it in all the projects.
In my case it only happens when I include `kotlinx.coroutines`, when I include other libraries I have that do not include GRADLE_METADATA, it can find all the symbols without issues.
Not sure if it is related to Kotlin/Native, if it is the case I can report it there.

**Comment by elizarov** [comment]
Hm... K/N was not supposed to to work without enabled metadata before that, too. I'm really surprised that you've somehow managed to do with previous version. In general, usage of K/N requires the use of gradle metadata feature.

**Comment by elizarov** [comment]
I've added the corresponding configuration notes to readme: https://github.com/Kotlin/kotlinx.coroutines#native
Does it help?

**Comment by soywiz** [comment]
Please, keep this open. I guess I will have time to try this weekend.

I have a special requirement others might not have since I'm using a the jvm variant of a multiplatform library as a gradle plugin dependency.

IIRC I had two main issues when I tried. By then `kotlinx.coroutines` was published using the metadata 0.3 and also it was compiled with Kotlin 1.3.x so it was using the new coroutines. But the gradle version supporting 0.3 included Kotlin 1.2.x.

I was able to circumvent that issue by doing a lot of tricks and generating a single jar as dependency, and using a separate class loader, but was super tricky and since some classes were already loaded from Kotlin 1.2.x it ended failing.
So I ended not using metadata and using a higher version of gradle already including Kotlin 1.3.x.

The other problem I had is that when tried to import the jvm variant of a mpp including android from a jvm-only gradle module, gradle was super confused when using metadata and I was not able to specify the variant. I tried several tricks to overcome this but was not able to find a solution except not using the metadata. I did not report this since the metadata was not 1.0 yet, and I was not sure how would evolve the mpp dependencies.

I can try again with metadata 1.0 and the latest version of gradle and see if I have that problem again and if it keeps being confused.

It takes me almost half a day to compile all my libraries together, so I will try this weekend if I find the time.

Please, keep this issue open and I will place here the results once I try, and if required I will report it somewhere else if can't use the jvm variant of a mpp as dependency of a gradle plugin.

**Comment by qwwdfsad** [comment]
Closing as outdated
