### ISSUE TITLE
Create Maven BOM for kotlinx coroutines

### ISSUE THREAD

**Issue by elizarov** [Kotlin/kotlinx.coroutines#1110]
See original discussion https://youtrack.jetbrains.com/issue/KT-30042

**Comment by sdeleuze** [comment]
To be valid from a Spring Boot perspective, kotlinx coroutines BOM should not specify versions for artifact already managed by other BOMs (like Kotlin one).

**Comment by elizarov** [comment]
Can it _reference_ Kotlin BOM with some specific version? It it should not reference Kotlin BOM at all?

**Comment by snicoll** [comment]
It should not reference it at all. If you do you tie one coroutine version to one kotlin version. If that was true, then why would you want two separate boms? Thanks!

**Comment by sdeleuze** [comment]
Hey, we really need this Coroutines BOm to move forward, could you please plan it for next 1.3 milestone?

**Comment by qwwdfsad** [comment]
Fixed in 1.3.0-RC
