### ISSUE TITLE
Missing documentation for io module

### ISSUE THREAD

**Issue by oliverdain** [Kotlin/kotlinx.coroutines#1111]
The main README lists the various coroutines modules (e.g. core, reactive, etc.) but it does not list `io`. However, there *is* an `io` module and it is referenced in other places (e.g. https://github.com/Kotlin/kotlinx-io says, "Best with kotlinx.coroutines-io" but that link lands on the README here which doesn't document the `io` module. Would be nice to include a note and some docs about it - had me confused for a bit.

**Comment by oliverdain** [comment]
I did notice that there isn't any code here for things like `ByteReadChannel` but there is a Maven package at `org.jetbrains.kotlinx:kotlinx-coroutines-io-jvm` and it is mentioned in a CHANGES.md so I'm a bit confused.

**Comment by elizarov** [comment]
It used to be `kotlinx-coroutines-io` module here, but it was moved to `kotlinx-io` project.
