### ISSUE TITLE
Publish to Maven Central

### ISSUE THREAD

**Issue by elizarov** [Kotlin/kotlinx.coroutines#112]
By  @vietj

> I’ve mentioned here a few weeks ago that the having the coroutine jars in jcenter exclusively was a problem
> for local development I’ve added jcenter repository to my pom.xml using a profile trick
> however the CI we are currently running with does not seem to take up the jcenter repository
> is that so much a problem to publish these jars in central ? (which is a pretty common thing)

**Comment by jmfayard** [comment]
I guess that would also solve my problem of not being able to read the kotlinx.coroutines docs inside [Dash](https://kapeli.com/dash)
![image](https://user-images.githubusercontent.com/459464/30422072-1925332c-993f-11e7-8aed-226dfadf6356.png)

**Comment by elizarov** [comment]
Next release will be pushed to Maven Central. There is already an alpha version pushed as a test.

**Comment by vietj** [comment]
@elizarov do you know when is the next release ? we are planning a Vert.x 3.5.0 release early october and it would be great if we could depend on this non alpha version :-)

**Comment by elizarov** [comment]
We are tentatively planning release at the end of September.

**Comment by elizarov** [comment]
Released in version 0.19
