### ISSUE TITLE
Coroutines Cancellation with java IO blocking 

### ISSUE THREAD

**Issue by halimpuckjava** [Kotlin/kotlinx.coroutines#1126]
hi

the most java IO methods is blocking (inputstream or network, .....) so the cancellation is not allow here but how about coroutine to resolve or improve this IO blocking to support cancellation in future ??

**Comment by elizarov** [comment]
Blocking methods in Java are not cancellable. You can use non-blocking IO libraries for scalability and cancellability.

**Comment by halimpuckjava** [comment]
thanks.
