### ISSUE TITLE
kotlinx.coroutines.CoroutineScope service file seems misplaced

### ISSUE THREAD

**Issue by pull-vert** [Kotlin/kotlinx.coroutines#1131]
I was trying to compile a pure JVM (no Android) project using Jdk12 configured for using Jigsaw JDK9+ module.

I have this error
`java.lang.module.FindException: Unable to derive module descriptor for ...\kotlinx-coroutines-core-1.2.0.jar
Caused by: java.lang.module.InvalidModuleDescriptorException: Provider class kotlinx.coroutines.android.EmptyCoroutineScopeImpl1 not in module`

This is what I see in my project's **External librairies** in intelliJ
![image](https://user-images.githubusercontent.com/5107035/56508684-36da9200-6525-11e9-869e-cd45e0c00adf.png)

Following resources seems misplaced in kotlinx-coroutines-core > jvm > resources
![image](https://user-images.githubusercontent.com/5107035/56508965-047d6480-6526-11e9-9303-d88a94fd4195.png)

Shouldn't these progard and services folders be somewhere in kotlinx-coroutines-android resources instead of kotlinx-coroutines-core ?

**Comment by elizarov** [comment]
That seems like a bug. This file should not be there at all.
