### ISSUE TITLE
Basic usage of Flow on Android

### ISSUE THREAD

**Issue by gabrielhuff** [Kotlin/kotlinx.coroutines#1140]
This post is 100% subjective, so I apologise in advance. It can serve as user feedback though.

Say I have a `ticTac()` function that returns a `Flow` that alternates between the strings `"TIC"` and `"TAC"` every second. A possible implementation:

```kotlin
private fun ticTac(): Flow<String> = flow {
  var isTic = false
  while (true) {
    emit(if (isTic) "TIC" else "TAC")
    delay(1000)
    isTic = !isTic
  }
}
```

Suppose that I want to implement a simple screen on Android that renders the emitted text:

![tictac](https://user-images.githubusercontent.com/19377340/56681898-a8077a00-66ca-11e9-8a14-96484267ab9f.gif)

With the current state of the `Flow` API, I'd do something like this:

```kotlin
class MainActivity : AppCompatActivity(), CoroutineScope by CoroutineScope(Dispatchers.Main) {

  override fun onCreate(state: Bundle?) {
    super.onCreate(state)
    val textView = TextView(this).apply { gravity = Gravity.CENTER }
    setContentView(textView)
    launch {
      ticTac().collect { textView.text = it }
    }
  }

  override fun onDestroy() {
    super.onDestroy()
    cancel()
  }
}
```

This works fine. However, there's something that is bugging me as a user of the API (so, the subjective part): consuming `Flow`s currently **feels** a little bit cumbersome when comparing to RxJava, specifically because of the need to enclose the call to `collect` on a `launch` block.

Considering this snippet, if we had 4 more `Flow`s to collect we would have to add **4 x 3 = 12 lines of code**. In contrast, subscribing to 4 different RxJava's `Observable`s would take **4 additional lines**.

Moreover, with RxJava it is possible to define extension functions such as:

```kotlin
// Usage: textView.setText(textObservable)
fun TextView.setText(text: Observable<String>): Disposable
```

The `Flow` equivalent would be:

```kotlin
// Usage:
// launch {
//   textView.setText(coroutineScope, textFlow)
// }
suspend fun TextView.setText(scope: CoroutineScope, text: Flow<String>)
```

The RxJava version feels more readable, not only because of the single line but also because of the fact that the `Flow` version requires a `CoroutineScope` (and we have to choose between `TextView` and `CoroutineScope` to be the extension receiver). Kind of the same reason that makes the [`Channel` operators](https://kotlin.github.io/kotlinx.coroutines/kotlinx-coroutines-core/kotlinx.coroutines.channels/map.html) relatively verbose.

I really like how minimalistic the `Flow` API is when comparing to `Observable`s (also the fact that it's an interface rather than a class). Also, although RxJava has more operators, `Flow` is more scalable because of extensions functions. However, it currently feels like the consumption part is not scaling well because of the existing coroutine scope mechanism.

**Comment by elizarov** [comment]
We plan to introduce an operator that combines `launch` and `collect`.

**Comment by gabrielhuff** [comment]
Cool! But would it be an extension of `Flow` or `CoroutineScope`?

**Comment by elizarov** [comment]
Most likely `flow.xxxIn(scope) {  ... }` where `xxx` and some other design details (like error-handling) is TBD

**Comment by gabrielhuff** [comment]
Alright, thanks for the info
