### ISSUE TITLE
Coroutines for Android allows operating UI on worker threads

### ISSUE THREAD

**Issue by ywwynm** [Kotlin/kotlinx.coroutines#1143]
I'm trying kotlinx.coroutines for Android (version: 1.2.0). Here is a simple test code block:

```
GlobalScope.launch {
  Logger.i("${Thread.currentThread()}, ${Looper.myLooper() == Looper.getMainLooper()}")
  text_view.text = "test"
}
```

The printed log is:

```
Thread[DefaultDispatcher-worker-2,5,main], false
```

As the log shows, we are not on the Android main thread, i.e UI thread. However, the code above won't throw an exception after we set text to `text_view` on this worker thread, and "test" is set to `text_view` correctly. What's the reason?

**Update 1:**

Adding `delay(10000L)` before` setText()` will cause the exception while shorter time (like 1000L in my test for a debug run with cold startup) won't. So it seems like an Android issue. But still that question, what's the reason?

**Comment by elizarov** [comment]
This has nothing to do with coroutines. If a specific Android API like `TextView.setText` does not throw exception when called from the wrong thread, there is nothing we can do about it. I have no idea what's the reason. You should ask it in Android-specific place.
