### ISSUE TITLE
launch(CommonPool){ ... }.join() not resuming?

### ISSUE THREAD

**Issue by akarnokd** [Kotlin/kotlinx.coroutines#115]
I'm trying to create a couple of interop functions for RxJava 2 and run into an odd situation.

The operator in question is a [transform](https://github.com/akarnokd/akarnokd-misc-kotlin/blob/master/src/main/kotlin/hu/akarnokd/kotlin/RxJavaCoroutineInterop.kt#L39) that takes an upstream item and allows a function to publish as many items as it wants while the infrastructure will suspend its emission in case of a backpressure. It seems to work with synchronous coroutine but the following sequence often doesn't resume after the `join()`:

```kotlin
Flowable.range(0, 10).transform<Int, Int>({ t ->
        println("$t - before sync")
        onNext(t)
        println("$t - after sync")
        launch(CommonPool) {
            println("${t + 1} - sleep async")
            delay(100)
            println("${t + 1} - before async")
            onNext(t + 1)
            println("${t + 1} - after async ")
        }
        .join()
        println("$t - transformed sync")
})
.test()
.awaitDone(5, TimeUnit.SECONDS)
.assertResult(0, 1, 1, 2, 2, 3, 3, 4, 4, 5, 5, 6, 6, 7, 7, 8, 8, 9, 9, 10)
```

```
0 - before sync
0 - after sync
1 - sleep async
1 - before async
1 - after async 
```

Removing `delay` hangs after a couple of items (newlines added for better readability):

```
0 - before sync
0 - after sync
1 - sleep async
1 - before async
1 - after async 
0 - transformed sync

1 - before sync
1 - after sync
2 - sleep async
2 - before async
2 - after async 
1 - transformed sync

2 - before sync
2 - after sync
3 - sleep async
3 - before async
3 - after async 
```

However, if I place a breakpoint on `join` or `println` after and step through slowly, the test succeeds. The `test()` consumes in an unbounded manner so none of the `onNext` suspends.

Any tips on what could be wrong?

**Comment by elizarov** [comment]
"it works when I step through slowly" is a telltale sigh that something is wrong with respect to concurrency & synchronization, e.g. a coroutine resume is getting lost somewhere. I frankly spent quite a lot of time myself debugging primitives to `publish` reactive streams with coroutine code due to these issues, before they started to work under all kinds of load. 

I've just cursory looked at `transform` source and one thing stands out as suspicious. When you use `launch` in `onXXX` function implementations there is no guarantee whatsoever that they are going to be executed in the same order as the original `onXXX` invocations.

**Comment by akarnokd** [comment]
Thanks. Here is a minimal standalone example that exhibits the same problem:

```Kotlin
object CoroutineForkJoin {
    @JvmStatic
    fun main(args: Array<String>) {

        launch(Unconfined) {
            val ctx = coroutineContext
            handler = { c ->
                launch(ctx) {
                    println(c)

                    launch(CommonPool) {
                        delay(1)
                        println("$c - after")
                    }
                            .join()
                    println("$c - done")
                    request()
                }
            }


            request()
        }

        Thread.sleep(10000)
    }

    val req = AtomicLong()
    var n = 0
    var handler: ((Int) -> Unit)? = null

    fun request() {
        if (req.getAndIncrement() == 0L) {
            do {
                handler?.invoke(n++)
            } while (req.decrementAndGet() != 0L)
        }
    }
}
```

If the inner `launch` uses `Unconfined` as well, the code doesn't hang. Are `coroutineContext` supposed to be reusable like this?

**Comment by elizarov** [comment]
There is a bug in `DefaultExecutor` in `kotlinx.coroutines` that causes the "fresh" `delay` to fail. Fixing now.

**Comment by akarnokd** [comment]
It still hangs after a couple of items if I remove `delay`.

```
0
0 - after
0 - done
1
1 - after
1 - done
2
2 - after
```

**Comment by elizarov** [comment]
Yes. The bug is elsewhere. Meanwhile, you can replace `launch(CommonPool) { ... }.join()` with `run(CommonPool) {...}` since it has the effect (and the bug still reproduces with a replacement)

**Comment by elizarov** [comment]
I've figured out what is happening. 

Here is the deal:
1. The first coroutine is `launch(Unconfined) { ... }`
2. The first coroutine does not do anything of significance inside of it. In fact it does not even do a single suspending operation, so, conceptually, the whole outer `launch(Unfonfined) {...}` block can be removed...
3. However, the _coroutineContext_ of the outer coroutine is used to launch _children_ coroutines. 
4. The outer coroutine completes almost immediately, since it does not invoke any suspending functions (it just assigns `handler` and invokes `request` which loops for a while and quits).
5. When the outer coroutine completes it cancels all the children, thus they stop executing too and do not produce any more action.

We definitely need way more diagnostics to troubleshoot cases like this...

**Comment by elizarov** [comment]
It is going to behave the way you wanted (I think) if you just remove the outer `launch(Unconfined) { ... }` block and replace `ctx` with `Unconfined`.

Also, the idiomatic way to write it in Kotlin is without the outer `object`. Just put it into `CoroutineForkJoin.kt` file on the top level. One less level of indentation and no need for `@JvmStatic` just like Kotlin designers intended:

```
fun main(args: Array<String>) {
    handler = { c ->
        launch(Unconfined) {
            println(c)
            run(CommonPool) {
                delay(1)
                println("$c - after")
            }
            println("$c - done")
            request()
        }
    }
    request()
    Thread.sleep(10000)
}

val req = AtomicLong()
var n = 0
var handler: ((Int) -> Unit)? = null

fun request() {
    if (req.getAndIncrement() == 0L) {
        do {
            handler?.invoke(n++)
        } while (req.decrementAndGet() != 0L)
    }
}
```

(it works both with and without `delay`)

**Comment by akarnokd** [comment]
In the original RxJava interop case, I launched the outer so I can gain the context[Job] object to link up with Subscription.cancel so all child tasks should be cancellable transitively in my understanding. Maybe leaving out the outer context is still workable. I'll try your suggestion.

**Comment by akarnokd** [comment]
Yes, it works now:

```kotlin
class Transform<T, R>(private val source: Flowable<T>, 
        private val transformer: suspend SuspendEmitter<R>.(T) -> Unit) : Flowable<R>() {
    override fun subscribeActual(s: Subscriber<in R>) {
        val parent = ProduceWithResource(s)
        s.onSubscribe(parent)
        val ctx = newCoroutineContext(Unconfined)
        source.subscribe(object: FlowableSubscriber<T> {

            var upstream : Subscription? = null

            val wip = AtomicInteger()
            var error: Throwable? = null

            override fun onSubscribe(s: Subscription) {
                upstream = s
                parent.setResource(s)
                s.request(1)
            }

            override fun onNext(t: T) {
                launch(ctx) {
                    parent.setJob(coroutineContext[Job])
                    wip.getAndIncrement()

                    transformer(parent, t)

                    if (wip.decrementAndGet() == 0) {
                        upstream!!.request(1)
                    } else {
                        val ex = error;
                        if (ex == null) {
                            s.onComplete()
                        } else {
                            s.onError(ex)
                        }
                        parent.cancel()
                    }
                }
            }

            override fun onError(t: Throwable) {
                error = t
                if (wip.getAndIncrement() == 0) {
                    s.onError(t)
                    parent.cancel()
                }
            }

            override fun onComplete() {
                if (wip.getAndIncrement() == 0) {
                    s.onComplete()
                    parent.cancel()
                }
            }
        })
    }
}
```

What remains is the question if the original example reproducing my original problem is something that is supposed to work or is something to be avoided entirely by the programmer?

**Comment by elizarov** [comment]
I've lost a bit what was "the original example". The second message in this thread with "a minimal standalone example that exhibits the same problem" works as it is designed to work, as the termination of the outer (parent) coroutine cancels all the children.

However, the problem that I see with this parent/child/cancellation design in `kotlinx.coroutines` library is that it is very hard to trouble-shoot and that parent-child relationship is somewhat implicit. 

Yes, I can see the capture of the parent context with `val ctx = coroutineContext` in the code, but it does not immediately brings my attention to the fact that `launch(ctx)` is going to launch a child coroutine. I see two (non mutually exclusive) potential ways to solve or alleviate this problem:

1. We can make child creation more explicit. For example, we can choose to ignore the job from the parent context and require an explicit `parent=xxx` parameter in coroutine builders (`launch`/`async`/etc) for cases where you want to launch a children coroutine.

2. We can make debugging parent-child and coroutine/start/stop scenarios easier. I'm thinking about "verbose" mode (something like `-Dkotlinx.coroutines.debug=verbose`) that would turn on logging of all coroutine start/stop events, thus making it easier to troubleshoot when something goes wrong.

**Comment by akarnokd** [comment]
I don't know. Certainly when considering interop with non-coroutine based non-blocking code, falling out of a context for any reason may end up with the same issues I had.

**Comment by akarnokd** [comment]
Thanks for the responses. I think I have all the answers to get my code working.

**Comment by elizarov** [comment]
FYI, I'm working on the solution that I've laid out is separate issue #125 in a separate branch. TL;DR parent coroutines will always wait for their children to complete. Under this change of parent-child rules your original code works just can you expected. There are no surprises in its behaviour.
