### ISSUE TITLE
Proguard warning about kotlinx.atomicfu.AtomicBoolean

### ISSUE THREAD

**Issue by neugartf** [Kotlin/kotlinx.coroutines#1155]
Might be related to #1116.
Coroutines v1.2.1, ProGuard v.6.0.3

I'm getting `Warning: kotlinx.coroutines.flow.FlowKt__MergeKt: can't find referenced class kotlinx.atomicfu.AtomicBoolean` when building the app.

**Comment by qwwdfsad** [comment]
Please ignore this warning.
I've verified separately, these symbols are left by atomicfu on unused code paths. I will file a separate issue in atomicfu for that

**Comment by utkarshGithub** [comment]
cannot build my release apk , please help

**Comment by qwwdfsad** [comment]
>cannot build my release apk , please help

You can use `dontwarn` directive for atomicfu to workaround this issue

**Comment by steve-the-edwards** [comment]
I am still getting this Gradle Plugin error:

kotlinx.atomicfu.AtomicFU: can't find referenced method 'void setInterceptor(kotlinx.atomicfu.AtomicOperationInterceptor)' in program class kotlinx.atomicfu.InterceptorKt

This is while using kotlinx-coroutines-core and kotlinx-coroutines-android in both shared Kotlin library included as .aar and in application project itself.

I tried explicit includes like the following:

implementation "org.jetbrains.kotlinx:kotlinx-serialization-runtime:$serialization_version"
    implementation "org.jetbrains.kotlinx:atomicfu:0.12.4"
    implementation "org.jetbrains.kotlinx:atomicfu-common:0.12.4"
    implementation "org.jetbrains.kotlinx:kotlinx-coroutines-core:1.2.1"
    implementation 'org.jetbrains.kotlinx:kotlinx-coroutines-android:1.2.1'
Still no luck

**Comment by elizarov** [comment]
The fix is in `develop` branch but not released yet.

**Comment by calvarez-ov** [comment]
More specifically, the rule to get past this is:
`-dontwarn kotlinx.atomicfu.AtomicBoolean`
