### ISSUE TITLE
Android art Warning

### ISSUE THREAD

**Issue by iNoles** [Kotlin/kotlinx.coroutines#116]
W/art: This dex file is invalid and will be rejected in the future. Error is: Constructor 33657(Lkotlinx/coroutines/experimental/channels/ConflatedBroadcastChannel;.<clinit>) is not flagged correctly wrt/ static.

I am only getting this in Android Emulator's logcat.

**Comment by elizarov** [comment]
Thanks a lot for report. Fixed in `develop` branch (will be part of the next release).

**Comment by elizarov** [comment]
Released in version 0.19
