### ISSUE TITLE
Make ChannelIterator.next non-suspending

### ISSUE THREAD

**Issue by qwwdfsad** [Kotlin/kotlinx.coroutines#1162]
State machine allocation in `ChannelIterator.next` is, in fact, unnecessary as `hasNext` suspends and consumes an element from the channel anyway. Suspension in `next` was introduced to have shortcuts for operators like `first` that do not call `hasNext` at all.
The key point here is to make a binary compatible change

**Comment by fvasco** [comment]
Hi @qwwdfsad,
maybe you have to update the [documentation](https://kotlin.github.io/kotlinx.coroutines/kotlinx-coroutines-core/kotlinx.coroutines.channels/-channel-iterator/next.html), also.
There is no mention to the `hasNext` method there, so the follow _ugly_ example is licit :

```kotlin
fun main() = runBlocking {
    val channel = produce {
        repeat(3) {
            send(it)
            delay(10)
        }
    }
    val iterator = channel.iterator()
    repeat(3) {
        val i = iterator.next()
        println(i)
    }
}
```

**Comment by elizarov** [comment]
@fvasco Good catch. Docs will have to be updated, too.
