### ISSUE TITLE
Invalid documentation for kotlin-coroutines-test TestCoroutineDispatcher

### ISSUE THREAD

**Issue by szymonkozak** [Kotlin/kotlinx.coroutines#1163]
In documentation example for kotlin-coroutines-test about `TestCoroutineDispatcher` there is `testScope` property which doesn't exist.

https://github.com/Kotlin/kotlinx.coroutines/blame/master/kotlinx-coroutines-test/README.md#L343

Also, in text
> Since TestCoroutineDispatcher is stateful in order to keep track of executing coroutines, it is important to ensure that cleanupTestCoroutines is called after every test case.

link to `cleanupTestCoroutines` function is invalid. (https://kotlin.github.io/kotlinx.coroutines/kotlinx-coroutines-test/kotlinx.coroutines.test/-test-coroutine-dispatcher/cleanup-test-coroutines.html)

**Comment by elizarov** [comment]
Good catch. Thanks.
