### ISSUE TITLE
Function reference support for Flow.collect

### ISSUE THREAD

**Issue by ZakTaccardi** [Kotlin/kotlinx.coroutines#1167]
With `ReceiveChannel`, I could do:

```kotlin
repository.states() // returns a `ReceiveChannel`
  .consumeEach(ui::render)
```

But with `Flow`, the following fails to compile

```kotlin
repository.states() // returns a `Flow`
  .collect(ui::render) // Type mismatch
```
Instead, I have to do:

```kotlin
repository.states() // returns a `Flow`
  .collect { state -> ui.render(state) }
```

It would be nice to be able to use the function reference when collecting

**Comment by elizarov** [comment]
Are you sure it does not work? Can you give a self-contained example, please.

**Comment by qwwdfsad** [comment]
Reproducer:
```
public fun channel(): ReceiveChannel<Int> = TODO()
public fun flow(): Flow<Int> = TODO()
public fun render(i: Int) = Unit

@Test
fun foo() = runBlocking {
    channel().consumeEach(::render)
     flow().collect(::render)
}
```

This is a Kotlin issue, please track it under https://youtrack.jetbrains.com/issue/KT-30991
`consumeEach` works because it is an inline extension
