### ISSUE TITLE
Channel produce needs coroutine scope to be created. Is there a better way to do it?

### ISSUE THREAD

**Issue by svkaka** [Kotlin/kotlinx.coroutines#1171]
So I have this

MainActivity.kt

    fun loadData() {
        textView.text = "LOADING"
        launch {
            repository.loadData(this).consumeEach { loaded ->
                withContext(Dispatchers.Main) {
                    logd("Presenting: ${loaded.size}, $loaded")
                    textView.text = loaded.joinToString { "$it\n" }
                }
            }
        }
    }

Repository.kt

    class Repository(
          private val local: Local = Local(),
          private val remote: Remote = Remote()
    ) {
    suspend fun loadData(scope: CoroutineScope): ReceiveChannel<List<String>> {
        return scope.produce(capacity = 2) {
            launch {
                val localData = local.loadData()
                send(localData)
            }
            launch {
                val remoteData = remote.loadData()
                send(remoteData)
            }
            invokeOnClose {
                logd("Closing channel")
            }
        }
    }

Local.kt

    override val data: MutableList<String> = mutableListOf("L1", "L2", "L3", "L4", "L5")

    override suspend fun loadData(): List<String> {
        logd("Loading local started")
        val wait = Random.nextLong(500)
        delay(wait)
        logd("Local loading took $wait")
        logd("Loading local finished: ${data.size}, $data")
        return data
    }

Remote.kt

    override val data: MutableList<String> = mutableListOf("R1", "R2", "R3", "R4", "R5")

    override suspend fun loadData(): List<String> {
        logd("Loading remote started")
        val wait = Random.nextLong(1000)
        delay(wait)
        logd("Remote loading took $wait")
        logd("Loading remote finished: ${data.size}, $data")
        return data
    }

As you can see I need to pass `coroutineScope` as param of function in order to create a `ReceiveChannel` using produce extension function. Is there a way to avoid passing scope as param (it doesn't look very nice)?

I tried creating `coroutineScope{....} `inside `Repository#loadData()` and 
I learned that creates a new scope and because of that `ReceiveChannel` doesn't work as expected (It emits all values after completion rather than emitting one at a time)

**Comment by fvasco** [comment]
@svkaka 

>  Is there a way to avoid passing scope as param (it doesn't look very nice)?

    with(repository) {
        loadData().consumeEach { loaded ->
        }
    }


    suspend fun CoroutineScope.loadData()  { ... }

**Comment by svkaka** [comment]
> @svkaka
> 
> > Is there a way to avoid passing scope as param (it doesn't look very nice)?
> 
> ```
> with(repository) {
>     loadData().consumeEach { loaded ->
>     }
> }
> 
> 
> suspend fun CoroutineScope.loadData()  { ... }
> ```
@fvasco
What if my `loadData()` is function in `Repository` class. How do I create extension function respecting this?

**Comment by fvasco** [comment]
@svkaka 

> What if my loadData() is function in Repository class.

Yea, try to replace the `Repository`'s `loadData` and invoke that method using `with` ;)
See the example.

**Comment by svkaka** [comment]
@fvasco didn't know I can do that. 
What about this warning?

> Ambiguous coroutineContext due to CoroutineScope receiver of suspend function
> Inspection info: This inspection reports calls & accesses of CoroutineScope extensions or members inside suspend functions with CoroutineScope receiver. Both suspend functions and CoroutineScope members & extensions have access to coroutineContext. When some function is simultaneously suspend and has CoroutineScope receiver, it has ambiguous access to CoroutineContext: first via kotlin.coroutines.coroutineContext and second via CoroutineScope.coroutineContext, and two these contexts are different in general case. So when we call some CoroutineScope extension or access coroutineContext from such a function, it's unclear which from these two context do we have in mind. Normal ways to fix this are to wrap suspicious call inside coroutineScope { ... } or to get rid of CoroutineScope function receiver.

**Comment by elizarov** [comment]
There is no reason to make `loadData` a `suspend` function is all it does is using `produce`. See, `produce` itself is not a suspending function and it should not be one, because it returns quickly. 

Does it help?

**Comment by svkaka** [comment]
hey @elizarov , @fvasco sorry for the late response. 
Yes, thanks for pointing that out.

Even though now I can use
```
with(repository) {
    loadData().consumeEach { loaded ->
    }
}
```
I am still not very happy with how it looks like but I don't think there can be done anything about it as I need that scope. So I believe we can close this one. 

Although it would be nice (in this case) if marking function `suspend` would attach it to coroutine scope. Basically, Compiler would do the same thing as this `fun CoroutineScope.loadData()  { ... }`
Meaning I could have access to functions like `launch` or `produce` without passing scope explicitly or using the extension function. The compiler would do that for me.
