### ISSUE TITLE
Fast path for Flow.drop if count is 0

### ISSUE THREAD

**Issue by fvasco** [Kotlin/kotlinx.coroutines#1173]
It is possible to avoid the new `Flow` if `count == 0`.

**Comment by qwwdfsad** [comment]
It is indeed possible, but I am not sure it is worth it, it insignificantly speedups only a pretty uncommon code-path, but (insignificantly) slows down a common code-path with the cost of an additional code.

**Comment by fvasco** [comment]
@qwwdfsad 

```kotlin
public fun <T> Flow<T>.drop(count: Int): Flow<T> {
    if (count <= 0) {
        if (count == 0) return this
        throw IllegalArgumentException("Drop count should be non-negative, but had $count")
    }
    return flow {
        var skipped = 0
        collect { value ->
            if (skipped == count) emit(value)
            else skipped++
        }
    }
}
```

**Comment by JakeWharton** [comment]
Do you have a case where this optimization would yield significant improvements? It seems so rare and have so little impact to be not worth the effort.

**Comment by fvasco** [comment]
The above proposal contains two **minor** enhancements, however I am not interested to engage long JMH sessions to promote this code review, nor to discuss about it without a real goal.

**Comment by fvasco** [comment]
I made some JMH test (for personal purpose).
I simply tested the code: `runBlocking { flow.drop(count).count() }`

The "lib" results are obtained with 1.2.2 version, "drop0" with custom one.
I think it is possible to made a better test, but unfortunately I don't know how enhance this version, yet (any suggestion is appreciated).

```test
Benchmark          (n)   Mode  Cnt        Score       Error  Units
MyBenchmark.drop0    0  thrpt   25  2062154,981 ± 29787,324  ops/s
MyBenchmark.drop0    1  thrpt   25  1552429,847 ± 16863,859  ops/s
MyBenchmark.lib      0  thrpt   25  1477075,982 ± 99268,332  ops/s
MyBenchmark.lib      1  thrpt   25  1678574,332 ± 25815,640  ops/s
```
