### ISSUE TITLE
Flow.take does not accept 0

### ISSUE THREAD

**Issue by fvasco** [Kotlin/kotlinx.coroutines#1174]
`Flow.take(0)` should be an empty `Flow`, in the documentation:

https://github.com/Kotlin/kotlinx.coroutines/blob/d0f62295031d684ae4525b8f1d01e782cf47c8c4/kotlinx-coroutines-core/common/src/flow/operators/Limit.kt#L49

But

https://github.com/Kotlin/kotlinx.coroutines/blob/d0f62295031d684ae4525b8f1d01e782cf47c8c4/kotlinx-coroutines-core/common/src/flow/operators/Limit.kt#L53

**Comment by PaulWoitaschek** [comment]
Makes sense to me. The code could use an early return here:

```kotlin
require(count >= 0) { "Requested element count $count should be positive" }
if(count==0) return emptyFlow()
```

**Comment by qwwdfsad** [comment]
Thanks, I will fix the docs.

The problem with this fast-path is that one may expect that even for `take(0)` an original flow is started (=> start side-effects are observable), but with this change `take(n)` unexpectedly starts to behave differently in the terms of the **source flow** side-effects depending on the `n` value. 
But other users may expect that flow is **not** started if `n == 0` :)

I'd rather prohibit zero at all unless there is a serious demand on it.
