### ISSUE TITLE
docs: runBlocking not available in Kotlin/JS

### ISSUE THREAD

**Issue by webleaf** [Kotlin/kotlinx.coroutines#1180]
![Снимок экрана 2019-05-07 в 14 35 43](https://user-images.githubusercontent.com/1824308/57296339-784a7000-70d5-11e9-8657-dca8ec696896.png)

https://github.com/Kotlin/kotlinx.coroutines/blob/master/kotlinx-coroutines-core/README.md

**Comment by qwwdfsad** [comment]
Was fixed at some point
