### ISSUE TITLE
Work with ThreadLocal-sensitive Components

### ISSUE THREAD

**Issue by ian4hu** [Kotlin/kotlinx.coroutines#119]
Many application trace framework use `ThreadLocal` to store the call context of a application, like the [SLF4j MDC](https://logback.qos.ch/manual/mdc.html), [CAT ](https://github.com/dianping/cat), and other distributed trace system(which use thread local for trace the context in some async situation).

But the coroutine will be dispatched to a unspecified thread to execute, how can i make the tracing work?

**Comment by elizarov** [comment]
Coroutine's analog to `ThreadLocal` is `CoroutineContext`. 

To interoperate with ThradLocal-using libraries you need to implement a custom `ContinuationInterceptor` that supports framework-specific thread-locals. Here is an example. Assume that use some framework that relies on a specific `ThreadLocal` to store some application-specific data (`MyData` in this example):

```
val myThreadLocal = ThreadLocal<MyData>()
```

To use it with coroutines, you'll need to implement a context that keeps the current value of `MyData` and puts it the corresponding ThreadLocal every time the coroutine is resumed on a thread. The code should look like this:

```
class MyContext(
    private var myData: MyData,
    private val dispatcher: CoroutineDispatcher
) : AbstractCoroutineContextElement(ContinuationInterceptor), ContinuationInterceptor {
    override fun <T> interceptContinuation(continuation: Continuation<T>): Continuation<T> =
        dispatcher.interceptContinuation(Wrapper(continuation))

    inner class Wrapper<T>(private val continuation: Continuation<T>): Continuation<T> {
        private inline fun wrap(block: () -> Unit) {
            try {
                myThreadLocal.set(myData)
                block()
            } finally {
                myData = myThreadLocal.get()
            }
        }

        override val context: CoroutineContext get() = continuation.context
        override fun resume(value: T) = wrap { continuation.resume(value) }
        override fun resumeWithException(exception: Throwable) = wrap { continuation.resumeWithException(exception) }
    }
}
```

To use it in your coroutines, you wrap the dispatcher that you want to use with `MyContext` and give it the initial value of your data. This value will be put into the thread-local on the thread where the coroutine is resumed.  

```
launch(MyContext(MyData(), CommonPool)) {
    // do something...
}
```

The implementation above would also track any changes to the thread-local that was done and store it in this context, so this way multiple invocation can share "thread-local" data via context.

I do think we need a ready-to-use implementation for SLF4j in the `integration` directory of `kotlinx.coroutines` project (`kotlinx-coroutines-slf4j`). You are welcome to [contribute it](https://github.com/Kotlin/kotlinx.coroutines/tree/master/integration#contributing).

**Comment by elizarov** [comment]
I've reposted this Q&A to StackOverflow: https://stackoverflow.com/questions/46227462/how-to-use-code-that-relies-on-threadlocal-with-kotlin-coroutines/46227463
Closing this issue.

**Comment by elizarov** [comment]
We should really have it out-of-the box in a separate integration module.

**Comment by oshai** [comment]
@elizarov - I will try to contribute it.

**Comment by elizarov** [comment]
The problem with "wrapping dispatcher" approach that I've provided in SO Q&A is that this "wrapped dispatcher" would get lost if dispatcher gets replaced. Consider, the proposed SLF4J MDC context from #403, for example. If you do 

```
launch (MDCContext(DefaultDispatcher)) { 
    foo()
}
```

But then in `foo()` you'll need to switch to `UI` context:

```
suspend fun foo() {
    withContext(UI) { 
        // MDCContext is lost here.
    }
}
```

I'm implementing an alternative approach, where you can implement and register a special extension point called `CoroutineContextThreadLocal` like this:

```
// declare custom coroutine context element
class MyElement : AbstractCoroutineContextElement(Key) {
    companion object Key : CoroutineContext.Key<MyElement>
    // some state is kept here
}

// declare thread local variable
private val myThreadLocal = ThreadLocal<MyElement?>()

// declare extension point implementation
class MyCoroutineContextThreadLocal : CoroutineContextThreadLocal {
    // this is invoked before coroutine is resumed on current thread
    override fun updateThreadContext(context: CoroutineContext) {
        myThreadLocal.set(context[MyElement])
    }

    // this is invoked after coroutine has suspended on current thrad
    override fun restoreThreadContext(context: CoroutineContext) {
        myThreadLocal.set(null)
    }
}
```

Now, `MyCoroutineContextThreadLocal` fully qualified class named shall be registered via `META-INF/services/kotlinx.coroutines.experimental.CoroutineContextThreadLocal` file.

**Comment by elizarov** [comment]
The downside of the API that is currently proposed in PR #454 is that its overhead for each coroutine suspend/resume is `O(N*K)`, where `K` is the number of registered `CoroutineContextThreadLocal` extension points and `N` is the size of the coroutine context (number of elements in its). I'm thinking about an alternative approach where the overhead is going to be `O(N)`. This will require that each extension point advertises the key of the context element it is bound to and the context is going to be scanned just once on each suspend/resume, only invoking extension points with the corresponding elements in the context.

**Comment by elizarov** [comment]
API in PR #454 now looks like this. In your to use it you have to define your own context element that implements `ThreadContextElement` interface like this: 

```
// declare thread local variable holding MyData
private val myThreadLocal = ThreadLocal<MyData?>()

// declare context element holding MyData
class MyElement(val data: MyData) : ThreadContextElement<MyData?> {
    // declare companion object for a key of this element in coroutine context
    companion object Key : CoroutineContext.Key<MyElement>

    // provide the key of the corresponding context element
    override val key: CoroutineContext.Key<MyElement>
        get() = Key

    // this is invoked before coroutine is resumed on current thread
    override fun updateThreadContext(context: CoroutineContext): MyData? {
        val oldState = myThreadLocal.get()
        myThreadLocal.set(data)
        return oldState
    }

    // this is invoked after coroutine has suspended on current thread
    override fun restoreThreadContext(context: CoroutineContext, oldState: MyData?) {
        myThreadLocal.set(oldState)
    }
}
```

The implementation is quite efficient now. Its cost is `O(N)`, where `N` is the size of the context (number of elements in the context). When a coroutine is resumed on a thread its context is scanned for elements that implement `ThreadContextElement` and they are given change to update the context of the thread.

**Comment by stangls** [comment]
For my projects, I used to do write a simple `CoroutineLocal` implementation to handle these cases.

Let's for the sake of an example say: We want to have block-style db-connections. But only one connection per coroutine.

```kotlin
class MyDatabaseAccess {

   val connection = CoroutineLocal<Connection>()               // <-- matter of interest

    // block-style db-connection
   suspend fun <T> connected( block: suspend (Connection) -> T ): T {
        var con : Connection? = connection.get()               // <-- matter of interest
        val newConnection = (con==null || con.isClosed)
        if (newConnection) {
            con = TODO( "create connection" )
            connection.set(con)                                // <-- matter of interest
        }
        val ret = block(con)
        if(newConnection) {
            con.close()
            connection.set(null)                               // <-- matter of interest
        }
        return ret
   }

}
```

And the `CoroutineLocal` implementation is simply a garbage-collected storage for each context.
```kotlin
class CoroutineLocal<T> {

    val values = WeakHashMap<CoroutineContext,T>()

    suspend fun get(): T? =
        values[coroutineContext]

    suspend fun set(value: T?) {
        if (value==null)
            values.remove(coroutineContext)
        else
            values[coroutineContext] = value
    }

}
```

**Comment by varantes** [comment]
Using  LazyTraceAsyncTaskExecutor(...).as CoroutineDispatcher as follows:

```
        @Service
        @Profile("fake")
        class QualityServiceFake(private val beanFactory: BeanFactory) : IQualityService {
        
        private val log = LoggerFactory.getLogger(javaClass)

            override fun aMethod() {
                log.info("Entrou no rebuild")
    
                val myDispatcher = LazyTraceAsyncTaskExecutor(beanFactory, SimpleAsyncTaskExecutor()).asCoroutineDispatcher()
    
                runBlocking(myDispatcher + CoroutineName("reb")) {
                    log.info("Entrou no runBlocking")
                    log.info("Entrou no coroutineScope. Executando em paralelo 3 processos assíncronos")
                    repeat(3) {
                        launch {
                            log.info("Entrou no async. Executando Thread.sleep de 3 seg")
                            Thread.sleep(3_000)
                            log.info("Retornou do delay")
                        }
                    }
                }
                TODO("rebuild not implemented. Apenas testando Sleuth com kotlin coroutines.")
            }
        }
```
