### ISSUE TITLE
Completion listener from Play Services integration can leak

### ISSUE THREAD

**Issue by LouisCAD** [Kotlin/kotlinx.coroutines#1197]
The two lines of code shown below highlight the problem well:
`suspendCancellableCoroutine` is used, but the wrapped callback (lambda passed to `addOnCompleteListener`)  stays registered and still references the continuation after cancellation, on which it can illegally call ` resume` (which crashes the app).
https://github.com/Kotlin/kotlinx.coroutines/blob/7af7ede7a06ae1a644c17dbb2ca12172af316ec7/integration/kotlinx-coroutines-play-services/src/Tasks.kt#L96-L97

Unfortunately, the [Google Tasks API](https://developers.google.com/android/reference/com/google/android/gms/tasks/Task) doesn't provide a way to remove the listener manually, so a workaround is needed to ignore post-cancellation completion without crashing, or make it no longer cancellable using `suspendCoroutine` (which can be a bummer considering cancellation ability can often be relied on).

The simplest workaround is to wrap `resume` call with `runCatching`, or surround it with `try`/`catch`, ignoring `IlegalStateException`s.

I can make a PR once a decision is taken.

**Comment by LouisCAD** [comment]
Digging through the API reference, I noticed that there's now [a way to listen to cancellation](https://developers.google.com/android/reference/com/google/android/gms/tasks/Task#addOnCanceledListener(com.google.android.gms.tasks.OnCanceledListener)), although, there's seemingly still no way to initiate it.

**Comment by LouisCAD** [comment]
Probably related to this issue: https://github.com/Kotlin/kotlinx.coroutines/issues/48

**Comment by LouisCAD** [comment]
Here's the version I currently use to avoid the crashes that could happen:
```kotlin
import com.google.android.gms.tasks.Task
import kotlinx.coroutines.CancellationException
import kotlinx.coroutines.suspendCancellableCoroutine
import kotlin.coroutines.resume
import kotlin.coroutines.resumeWithException

suspend fun <R> Task<R>.await(): R {
    if (isComplete) {
        val e = exception
        when {
            e != null -> throw e
            isCanceled -> throw CancellationException("Task $this was cancelled normally.")
            else -> @Suppress("UNCHECKED_CAST") return result as R
        }
    }
    return suspendCancellableCoroutine { c ->
        addOnCompleteListener { task: Task<R> ->
            try {
                val e = task.exception
                when {
                    e != null -> c.resumeWithException(e)
                    task.isCanceled -> c.cancel()
                    else -> @Suppress("UNCHECKED_CAST") c.resume(task.result as R)
                }
            } catch (ignored: IllegalStateException) {
                // Continuation has been cancelled, or completion callback has been invoked repeatedly.
            }
        }
    }
}
```

**Comment by qwwdfsad** [comment]
>That fixes previous usage of suspendCancellableCoroutine that would lead to
crashes if cancelled and then the addOnCompleteListener callback was invoked.

This is not the case. `CancellableContinuation` is designed to avoid this exact situation (a race between cancellation and `resume`) and ignores the first `resume` after cancellation.
The only way to trigger `ISE` is to invoke `resume` *twice* which should not happen for `OnCompleteListener`.

Could you please provide a reproducer? We should understand the problem before fixing it

**Comment by qwwdfsad** [comment]
Any update on that?

**Comment by LouisCAD** [comment]
I saw a [report of someone in Kotlin's Slack](https://kotlinlang.slack.com/archives/C1CFAFJSK/p1558003709029300) telling a Firebase library (based on the Play Services Tasks API) called the lambda passed to `addOnSuccessListener` twice. The actual implementation of the `Task` abstract class is obscure (the code is not open source, plus anyone could extend it), so technically, it is possible to have it called more than once, and if the `await` extension is used, there's no way to catch the `IllegalStateException` thrown.

I first thought it was related to cancellation, hence my comment, but it seems it's not the case, so can be the callback actually called twice.

**Comment by qwwdfsad** [comment]
The issue should be reported and fixed at Firebase side.
I don't think that it is a good idea to fix an issue without understanding why (or **if**) it happens and without at least some reproducer

**Comment by qwwdfsad** [comment]
Closing as "not applicable"
