### ISSUE TITLE
About execution order

### ISSUE THREAD

**Issue by l42111996** [Kotlin/kotlinx.coroutines#120]
if I use newSingleThreadContext, all the task execution order is fifo?How does the task execution order be implemented?

**Comment by elizarov** [comment]
`newSingleThreadContext` resumes scheduled continuation in FIFO order. It is implemented using FIFO queue. In fact, the current implementation (as of version `0.18`) creates the thread pool executor using [`Executors.newScheduledThreadPool`](https://docs.oracle.com/javase/8/docs/api/java/util/concurrent/Executors.html#newFixedThreadPool-int-)

**Comment by l42111996** [comment]
Thank you for your answer
