### ISSUE TITLE
Add extension functions for modifying a List<DelayController>

### ISSUE THREAD

**Issue by objcode** [Kotlin/kotlinx.coroutines#1203]
Add extension functions for modifying multiple DelayController at once.

Use case: This is useful for advanced testing situations where the interaction of multiple controllers is being tested.

In addition, a lot of early users of the library have shared that they are making multiple TestCoroutineDispatcher instances in a test (i.e. IO, Default, and Main). While the recommended style is to use one TestCoroutineDispatcher unless explicitly testing dispatcher interactions, the ergonomics will be better when tests are written in this style with aggregate extensions.

Depends on idle implementation in https://github.com/Kotlin/kotlinx.coroutines/issues/1202 to allow advanceUntilIdle to be implemented.

**Comment by elizarov** [comment]
We'll need some motivational code example / use-case to get started here.

**Comment by objcode** [comment]
Agreed - I'm not actually sure this one needs to be part of the library since the use case for advancing time in multiple TCD is unclear.

One option is to ensure the idle implementation in https://github.com/Kotlin/kotlinx.coroutines/issues/1202 also allows for a developer to create their own versions. Right now it's not possible to create "correct" aggregate `advanceTime*` implementations using the interface of `DelayController` since there is no way to figure out which dispatcher has the "shortest pending delay."

I'd like to leave this ticket open until 1202 is resolved and see if anyone has a more concrete use case.
