### ISSUE TITLE
coroutines-reactor: subscriberContext not available in suspended functions

### ISSUE THREAD

**Issue by FrontierPsychiatrist** [Kotlin/kotlinx.coroutines#1212]
When using the `mono` coroutine and `awaitSingle` for the subscriber context in the suspended function it seems the subscriber context is not "propagated".

This example prints `Context0{}` when `Context1{foo=bar}` is expected.

Using reactor 3.3.0.M1, kotlin-coroutines 1.2.1

```kotlin
import kotlinx.coroutines.CoroutineScope
import kotlinx.coroutines.Dispatchers
import kotlinx.coroutines.reactive.awaitSingle
import kotlinx.coroutines.reactor.mono
import reactor.core.publisher.Mono
import reactor.util.context.Context

suspend fun test() {
    val ctx = Mono.subscriberContext().awaitSingle()
    println(ctx)
}

fun main() {
    CoroutineScope(Dispatchers.Unconfined).mono {
        test()
    }.subscriberContext(Context.of("foo", "bar"))
            .block()
}
```

I tried to understand the code to see where this is coming from but sadly couldn't understand it. The `sink` in `Mono.defer` has the subscriber context correctly available, this I saw while debugging.

**Comment by qwwdfsad** [comment]
This is the expected behaviour.
You have two **independent** monos: one created with `CoroutineScope(Dispatchers.Unconfined).mono` and another one created and immediately subscribed with `Mono.subscriberContext().awaitSingle()`. They have nothing in common and thus one context is not propagated to another one.

**Comment by FrontierPsychiatrist** [comment]
Ok, that makes sense. Thanks for the information, I'll follow that ticket then!
