### ISSUE TITLE
Wrong Flow.switchMap { }.take() behaviour 

### ISSUE THREAD

**Issue by igordmn** [Kotlin/kotlinx.coroutines#1218]
Kotlin 1.3.31, kotlinx.coroutines 1.2.1

This code:
```kotlin
runBlocking {
  println(
    flowOf(1, 2, 3, 4, 5)
      .switchMap { x -> flow { emit(x) } }
      .take(1)
      .toList()
  )
}
```
prints wrong result: [1, 2, 3, 4, 5].

It should prints [1].

**Comment by qwwdfsad** [comment]
Thanks for reporting this.
It is pretty similar to #1128
