### ISSUE TITLE
MainDispatcher.immediate does not always dispatch coroutine on Main thread?

### ISSUE THREAD

**Issue by ZakTaccardi** [Kotlin/kotlinx.coroutines#1219]
Per this documentation:

>  If it is known that updateUiElement can be invoked both from the Main thread and from other threads,  `immediate` dispatcher is used as a performance optimization to avoid unnecessary dispatch. 

This seems to indicate that usage of `Dispatchers.Main.immediate` could possibly execute `updateUiElement` on a different thread than the main thread. Is this correct?

From: 

https://github.com/Kotlin/kotlinx.coroutines/blob/86559c6f0972552b8dcc03d3d7e48577091d4914/ui/kotlinx-coroutines-android/src/HandlerDispatcher.kt#L33-L40

**Comment by qwwdfsad** [comment]
It is not correct, it's improper documentation. Will fix in develop
