### ISSUE TITLE
[Flow] combineLatest with custom transformer (e.g. not map transformer)

### ISSUE THREAD

**Issue by hrach** [Kotlin/kotlinx.coroutines#1224]
I miss `combineLatest()` which transformer behaves more like [Flow<E>.transform](https://kotlin.github.io/kotlinx.coroutines/kotlinx-coroutines-core/kotlinx.coroutines.flow/transform.html) than [Flow<E>.map](https://kotlin.github.io/kotlinx.coroutines/kotlinx-coroutines-core/kotlinx.coroutines.flow/map.html).

My usecase: I ('d like to) combine multiple flows and emit loading & success state between suspensions in trasformer:

```kotlin
val filter = ConflatedBroadcastChannel<Filter>()
val search = ConflatedBroadcastChannel<String>()

filter.asFlow().combineLatest(search.asFlow()) { f, s ->
    emit(LoadingResource())
   
    val data = fetchData(f, s) // suspending function
    emit(SuccessResource(data))
}
```

I may rewrite it to do a transformation to `Pair`, however it seems quite unnecessary and personally I have use cases for 4 flows (E.g. I would have to create a data class each time).

I could try to prepare a PR.

(Also, I would do this myself but the building-blocks of combineLatest are internal. :X)

**Comment by qwwdfsad** [comment]
Thanks for the issue! Your report along with the provided example was very useful for designing current and upcoming operators.
