### ISSUE TITLE
Kotlin/Native runBlocking & delay cause high CPU usage

### ISSUE THREAD

**Issue by thowimmer** [Kotlin/kotlinx.coroutines#1225]
Hi all,

I just started a very simple hello world console application with Kotlin/Native for a linuxX64 target.
I want to increment a counter and print it every two seconds to the command line:
```kotlin
fun main() = runBlocking {
    var i = 0
    while(isActive){
        println("Hello Kotlin/Native COROUTINE #${++i}")
        delay(2000)
    }
}
```

When I run the binary on a the target host I encounter that CPU usage increases by 25% (one core being totally occupied). So it seems this is blocking the thread totally.

When I replace the `delay(...)` suspend function with a `platform.posix.sleep(2)` there is no noticeable CPU usage increase (0%).

here my _build.gradle.kts_:
```gradle
plugins {
    kotlin("multiplatform") version "1.3.30"
}

repositories {
    mavenCentral()
}


kotlin {
    linuxX64("native") {
        binaries {
            executable()
        }
    }

    sourceSets {
        val nativeMain by getting {
            dependencies {
                implementation("org.jetbrains.kotlinx:kotlinx-coroutines-core-native:1.2.1")
            }
        }

    }
}

tasks.withType<Wrapper> {
  gradleVersion = "5.3.1"
  distributionType = Wrapper.DistributionType.ALL
}
```

Is this a known issue ? or is just me being new to Kotlin/Native and coroutines... (bear with me if that's the case)

Many thanks for your support and the great efforts you put into bringing Kotlin coroutines to every platform !

Best regards,
Thomas

**Comment by qwwdfsad** [comment]
It's a known issue waiting for someone to report it :)

**Comment by thowimmer** [comment]
Good to hear that :smiley:. Looking forward to this issue being fixed.

For those who are looking for a temporary workaround for Koltin/Native & Multiplatform projects targeting POSIX compliant targets:

expected declaration in common/platform indipendent code
```kotlin
expect suspend fun delayOnPlatform(timeMillis: Long)
```

```kotlin
actual suspend fun delayOnPlatform(timeMillis: Long) {
    usleep(timeMillis.convert<__useconds_t>() * 1000U)
}
```
