### ISSUE TITLE
Android cant update ui but have log

### ISSUE THREAD

**Issue by prprDog** [Kotlin/kotlinx.coroutines#1230]
```
//in repo
fun queryUserList() = runBlocking {
        source.loadingState.value = LoadingState.LOADING
        source.resultList.value = withContext(Dispatchers.IO) {
            delay(3000)
            MainResult(dao.queryUser())
        }
        source.loadingState.value = LoadingState.LOADED
    }
```

```
//in activity
mainModel.loadingState.observe(this@MainActivity, Observer {
            if (it == LoadingState.LOADING){
                tv_loading.text = "loading"
                Log.i("bbbb", "loading")
            }else if (it == LoadingState.LOADED){
                tv_loading.text = "loaded"
                Log.i("bbbb", "loaded")
            }
        })
```

I want to change the text with TextView before or after load.
But there is a problem.Before load, the ui cant change,but have log.Only after load,the ui can change.
whether someone can tell me why and how to solve it.

**Comment by objcode** [comment]
This code appears to block the main thread during the query by using `runBlocking`. Even though the query will run on another thread, the `withContext(Dispatchers.IO)` will block the main thread until the result is ready due to `runBlocking`.

You should change `queryUserList` to a suspend function

```
suspend fun queryUserList() {
...
}
```

then call it from a coroutine started on an appropriate scope from https://developer.android.com/topic/libraries/architecture/coroutines

**Comment by prprDog** [comment]
> This code appears to block the main thread during the query by using `runBlocking`. Even though the query will run on another thread, the `withContext(Dispatchers.IO)` will block the main thread until the result is ready due to `runBlocking`.
> 
> You should change `queryUserList` to a suspend function
> 
> ```
> suspend fun queryUserList() {
> ...
> }
> ```
> 
> then call it from a coroutine started on an appropriate scope from https://developer.android.com/topic/libraries/architecture/coroutines

Thank you for your help. Now I use liveData{} block to update ui and query data. But I found a problem when using liveData{}.
I try build a LiveData with enum type just like this:
```
enum class LoadingState{
    LOADING,LOADED
}

private var liveData: LiveData<LoadingState> = liveData {
        emit(LoadingState.LOADING)
    }

In Activity:
liveData.observe(this, Observer {
            Log.i("test", "abc")
        })
```
The observer cant receive events when I build a LiveData with enum type.

**Comment by prprDog** [comment]
Oh I have found my problem.  the livedata block will create a new Livedata object,  if we rebuild a new one, the observer could not detect the change, if I want to change the value in runtime, I should use lifecycleScope.launch block or viewModelScope.launch block, thank you again
