### ISSUE TITLE
Comparison of performance between Thread and coroutines

### ISSUE THREAD

**Issue by xqzc000** [Kotlin/kotlinx.coroutines#1246]
HI, I read some introductions about coroutines, but I still cannot tell what's better than Thread or when to use  coroutines are more helper.
Can anyone tell me? thanks!

**Comment by fvasco** [comment]
Hi @xqzc000 
I strongly suggest you to read the [offcial documentation](https://kotlinlang.org/docs/reference/coroutines/basics.html#coroutines-are-light-weight) at least once.
Moreover this isn't a library issue, so I encourage you to consider other [Kotlin resource](https://kotlinlang.org/community/#kotlin-online-resources), like Kotlin Forum.
