### ISSUE TITLE
Provide a `collectIndexed` terminal operator

### ISSUE THREAD

**Issue by jcornaz** [Kotlin/kotlinx.coroutines#1247]
Hi, 

Like with collections and sequences we occasionally need to iterate and maintain an index like this:

```kotlin
var index = 0
values.collect {
  // do something with the value, knowing its index.
  ++index
}
```

Since `forEachIndexed` already exists for `Iterable` and `Sequence` and `consumeEachIndexed` exists for `ReceiveChannel` it would seem natural to me that flows provide a `collectIndexed` terminal operator.

**Comment by fvasco** [comment]
Hi @jcornaz 
what do you think about something like `fun <T> Flow<T>.toIndexed(): Flow<IndexedValue<T>>`?

**Comment by jcornaz** [comment]
Hi @fvasco 

>  what do you think about something like fun <T> Flow<T>.toIndexed(): Flow<IndexedValue<T>>?

Why not. except I'd call it `withIndex()` for consistency with the collection API.

But I think I prefer `collectIndexed`. I find it more natural to find, and it does not need to wrap each value (which may create unnecessary GC pressure when dealing with a lot of values).

**Comment by fvasco** [comment]
@jcornaz 
> I'd call it withIndex()

I agree.

> it does not need to wrap each value 

In escape analisys we hope

**Comment by elizarov** [comment]
@jcornaz When you say "we occasionally need" can you provide a slightly more concrete example where this might be needed when you work with flows, please. E.g. if you had recently run into this need in your project, you can explain what was the problem you were solving.

**Comment by jcornaz** [comment]
>can you provide a slightly more concrete example where this might be needed when you work with flows, please.

Last time I felt the need for it, it was to monitor progress. Here is how it'd look like:

```kotlin
lines.collectIndexed { index, line ->
  // process the line
  println("${index + 1} lines processed")
}
```
