### ISSUE TITLE
Can I use kotlinx.coroutines with Firebase Realtime Database Normal or only with Firestore?

### ISSUE THREAD

**Issue by neuberfran** [Kotlin/kotlinx.coroutines#1248]
Hi,

https://github.com/Kotlin/kotlinx.coroutines/issues/62

**_about this link above, I have the question of my topic._**

### **Another brief question:**

I need to check if a variable coming from the firebase changes while I'm inside a while/loop in kotlin.

_**What is the best way to do this, using kotlinx.coroutines?**_

**Comment by elizarov** [comment]
Sorry, but I don't think it is the right place to ask this question.
