### ISSUE TITLE
Coroutine Scope may remains Running after Exception

### ISSUE THREAD

**Issue by amanyi** [Kotlin/kotlinx.coroutines#1249]
```
suspend fun processReferences(refs: List<Reference>) =
    coroutineScope{
        for(ref in refs){
            val location = ref.resolveLocation()
            launch{
                val content = downloadContent(location)
                processContent(ref, content)
            }
        }
    }
```

in the above code (from Kotlin Conference 2018) if we get an exception from one of launched coroutines all child coroutines will be cancel and coroutineScope will not return or throw exception until all child coroutines are canceled. But cancellation is cooperative and if downloadContent do not check for cancellation it will run to end and it is both waste of time and resources (coroutineScope have to wait for all downloadContent to complete because they do not check for cancellation).

But in old fashion if we use thread instead of coroutines it is only a waste of resources and exception will soon propagate and it will not waste time!

Will be there any solution for coroutineScope to say just kill child coroutines and do not wait for cancellation to complete?

**Comment by elizarov** [comment]
Cancellation is cooperations and there is no way to "just kill child coroutines". In the above code `downloadContent` should be checking for cancellation in a cooperative way. I hope this helps.
