### ISSUE TITLE
Lots of calls to Thread.setNativeName from coroutine lib code seem to slow down execution

### ISSUE THREAD

**Issue by antoinebaudoux** [Kotlin/kotlinx.coroutines#1252]
Hello, 

I'm profiling a test that takes 47s to execute, of which 6.5 seconds seem to be spent calling Thread.setNativeName() from coroutine lib code : 
<img width="1426" alt="Screenshot 2019-06-05 at 16 00 18" src="https://user-images.githubusercontent.com/5154448/58962459-7bf01600-87ab-11e9-923d-d3fd06d51d6d.png">

As you can see from the screenshot above, the calls are coming from either 
`kotlinx.coroutines.CoroutineId.updateThreadContext(CoroutineContext)`
or
`kotlinx.coroutines.CoroutineId.updateThreadContext(CoroutineContext)`

Is this "normal"? Maybe my code is switching context too much? (1821325 times).

I'm on MacOs 10.14.4/jdk 1.8.0_111

Thanks for you feedback

**Comment by qwwdfsad** [comment]
Hi, 

Yes, this is normal. This is a feature that is enabled only in [debug mode](https://github.com/Kotlin/kotlinx.coroutines/blob/master/docs/debugging.md) to improve the debugging experience: currently executing coroutine name (or id) is reflected in the thread name.

Is it a real issue for you? Potentially, we could provide a debug mode (~stacktrace recovery) that does not update thread name, but only if it is really justified

**Comment by antoinebaudoux** [comment]
Hi, 

Okay, this is not a problem at all, it's rather a nice feature :)
Sorry for not knowing about this develop mode.

Thanks for your quick reply
