### ISSUE TITLE
Unit Tests & withContext()

### ISSUE THREAD

**Issue by milosmns** [Kotlin/kotlinx.coroutines#1254]
**Question**

Is there a way to control the `Default` dispatcher in Unit tests? Here's an example:

```kotlin
// let's imagine that this function is in the presenter layer,
// and that presenter is implementing a coroutine scope,
// and running launched coroutines in on the main dispatcher

override fun startLooping() {
    val errorHandler = CoroutineExceptionHandler { _, error ->
      view.unblockUser()
      view.showError(error.localizedMessage)
    }

    launch {
      view.blockUser("Looping now...")
      val elapsed = withContext(Dispatchers.Default + errorHandler) { repo.loopFor(loopTime) }
      view.unblockUser()
      view.showDurationMillis(elapsed)
    }
  }
```

It's a simple example, user is blocked for a while, and then unblocked when the task finishes.

I intentionally didn't use `delay()` because it's misleading and most of the time it's not something that would happen in production code, so I use this `loopFor(seconds: Int)` function that basically spins in a `while` loop until the given time elapses.

The problem that I have is: in tests, it seems like this `withContext(...)` call is actually offloading tasks to the `Default` dispatcher (Q: expected?) and thus making my tests multi-threaded -- which is not what I want. I've overridden the Main dispatcher using the `kotlin-coroutines-test` library, but this seems to be working only for `Main` (Q: expected?).

I'm not really sure if it's the code or it's my understanding of how this works under the hood, but something's wrong. So to repeat the question

```
Is there a way to control the Default dispatcher in Unit tests?
```

Appreciate the help.

**Comment by zach-klippenstein** [comment]
> I've overridden the Main dispatcher using the kotlin-coroutines-test library, but this seems to be working only for Main (Q: expected?).

Yes, overriding the Main dispatcher only overrides the Main dispatcher, not any other dispatcher.

> it seems like this withContext(...) call is actually offloading tasks to the Default dispatcher (Q: expected?)

Yes, because you've hard-coded that dispatcher. This is a classic use case for dependency injection: have your presenter take the dispatcher to run this `withContext` block on as a constructor parameter and pass that to `withContext` instead of passing `Default` directly. Then in your unit test you can pass a test context in.

Also, I don't think you need the `CoroutineExceptionHandler`, you can just use a regular try/catch.

```kotlin
class YourPresenter(private val backgroundDispatcher: CoroutineDispatcher) {
  override fun startLooping() {
    launch {
      view.blockUser("Looping now...")
      try {
        val elapsed = withContext(backgroundDispatcher) { repo.loopFor(loopTime) }
        view.unblockUser()
        view.showDurationMillis(elapsed)
      } catch (e: Throwable) {
        view.unblockUser()
        view.showError(error.localizedMessage)
      }
    }
  }
}
```

**Comment by milosmns** [comment]
@zach-klippenstein Awesome, thank you!
