### ISSUE TITLE
In Rx2 interop, coroutine for single should be started Lazy

### ISSUE THREAD

**Issue by AAverin** [Kotlin/kotlinx.coroutines#1256]
```
fun asSingle() {
            println("outside")
            return async {
                println("inside")
            }.asSingle(CommonPool)
}
```
Having code above, once could wrongly assume that code "inside" will only be executed when resulting Single is subscribed on.
The actual result is output of both "outside" and "inside" when that function is called.
I was explained that this happens because `async` executed eager by default.

It would work as one could expect if we
```
fun asSingle() {
            println("outside")
            return async(start = CoroutineStart.LAZY) {
                println("inside")
            }.asSingle(CommonPool)
}
```

Fix would probably by to change in RxSingle.kt file line
```
 coroutine.start(CoroutineStart.DEFAULT, coroutine, block)
```
to
```
 coroutine.start(CoroutineStart.LAZY, coroutine, block)
```

**Comment by elizarov** [comment]
It has nothing to do wtih `asSingle`. It is just how `async { ... }` works. Check it out:
https://kotlin.github.io/kotlinx.coroutines/kotlinx-coroutines-core/kotlinx.coroutines/async.html
Does it help?

**Comment by AAverin** [comment]
@elizarov I understand that `async {}` has a different behaviour, but conversion goes from `async` into `Single`, and behaviour of Single is to execute it's code when it's being subscribed on, not when the function to generate the Single is invoked.
With the current implementation, all conversions from coroutine into rxJava Single will end up being executed at the moment of invocation, not at the moment of subscription, which completely breaks reactive pattern and introduces lots of bugs into the project.

**Comment by fvasco** [comment]
Should `rxSingle` cover your use case?

> all conversions from coroutine into rxJava Single 

Did you mean `conversions from Deferred`?

**Comment by AAverin** [comment]
@fvasco Sorry for not being crystal-clear.
Yes, conversions from Deferred to Single. As I wrote above, it's known from RxJava that Observables and Singles start their execution at the moment of subscription, not at the moment of invocation of the method, that returns an Observable/Single.

Single, created with rxSingle from the coroutines converter library executes at the moment of invocation due to `async {}` being eagerly executed by default, which contradicts RxJava specification.

**Comment by elizarov** [comment]
By the time you apply conversion operator, async had already started coroutine. There is nothing conversion operator can do to prevent that.
