### ISSUE TITLE
Why the RxJava 1.x and 2.x Modules

### ISSUE THREAD

**Issue by AdamsGi** [Kotlin/kotlinx.coroutines#126]
The "Guide to reactive streams with coroutines" at (https://github.com/Kotlin/kotlinx.coroutines/blob/master/reactive/coroutines-guide-reactive.md) nicely presents the "Publish" func that creates cold reactive [Publisher]
 (https://github.com/Kotlin/kotlinx.coroutines/blob/master/reactive/kotlinx-coroutines-reactive/src/main/kotlin/kotlinx/coroutines/experimental/reactive/Publish.kt). More importantly, the guide also illustrates how to write operators as extensions to Publisher.

Based on the guide, it appears that adding dependencies to RxJava, either 1.x or 2.x, should be discouraged if the developer opt-in the coroutines. This is because with the "Publish" func that creates cold reactive Publisher, all that RxJava can additionally bring in are the operators. However, as the guid already illustrated, operators can be written simply and completely with coroutines, bring in the heavy dependencies incurred by RxJava does not make sense.

Actually, RxJava devs also suggest that "provide higher order functions can be elegant, ..., if the JVM supported extension methods" (see "Cons of Exposing Reactive Stream APIs instead of RxJava" at https://github.com/ReactiveX/RxJava/wiki/Reactive-Streams), which is exactly the case of Kotlin (well, to be precise, extension is supported by the Kotlin lang not JVM).

Hence the question herein: when we can easily extend Publisher with operators like flatMap, merge, filter, take, zip and the many others, why bother creating the kotlinx-coroutines-rx1 and kotlinx-coroutines-rx2 modules? Instead, create and invest in a kotlinx-coroutines-reactive-operators module, does it make more sense?

**Comment by elizarov** [comment]
These module are provided for _interoperability_, so that if you have a project based on either Rx 1.x or 2.x you can start getting advantage of Kotlin coroutines.

**Comment by AdamsGi** [comment]
@elizarov 
Thanks for your comments. But I don't quite get it. Here is what my understanding of interoperability with Rx library, either 1.x or 2.x.

Take Rx 2.x as example, it has Flowable.fromPublisher(), Single.fromPublisher(), Completable.fromPublisher(), Maybe.fromCompletable(), etc. Since "Publish" can create Publisher, all the functionality in kotlinx-coroutines-rx2 module appear to be redundant. As long as dev holds a Publisher, the Publisher already empowers the dev to full interoperability with Rx 2.x. Precisely, it means every and all operators that Rx 2.x provides are available to the dev.

If this view of interoperability make sense to you, getting advantage of Kotlin Coroutines really would come from the **operators natively implemented by kotlinx-coroutines**. The advantages can be multi-fold: more performant(?), more readable, 0 extra dependency (reduced app size, methods count).

Thanks for reading and please let me know your thoughts.

**Comment by elizarov** [comment]
Why would we need to reimplement Rx? I don't get it. It is a nice library that does what it is supposed to be very well. If you use it in your project and happy with it, there is no reason to replace it. All we provide are some small convenience methods to enable integration. For example, you are using Rx 2 and you want to have an Rx2 Flowable that emits a number sequence with some complex delay between emmittion (you have some complex code in mind). You can easily write that with `kotlinx-coroutines-rx2` module, way easier than writing customer operations in Rx directly:

```
rxFlowable { 
    repeat(nTimes) { i ->
        delay(someComplexFormula(i))
        send(i)
    }
}
```

That's all. What's wrong with that?

**Comment by AdamsGi** [comment]
@elizarov 
I think your code just shows why it's necessary to re-implement the operators using coroutines! Here are the reasons:

Reason 1: there are common operators, e.g. map, filter, takeN, that are better from a common library and not necessarily every project in the world re-implement these operators again and again.
Reason 2: the common library can serve as patten and best practice in implementing operators using coroutines. This leads to below Reason 3.
Reason 3: there may be project-only complex operator that is not available in the common operator library, but project dev can leverage the best practice and hopefully implement said complex operator by themselves in a more foolproof approach.

That's why I feel the kotlinx-coroutines-reactive-operators would be of interest to the Coroutines + Reactive community! How do you like?

**Comment by elizarov** [comment]
I am definitely open to accept contributions, but I don't see enough motivation to do it myself. For one thing, Rx is already written and it is written well. Rewriting Rx operators in Kotlin coroutines will definitely result in shorter source code, but it will not result in a better performance. If somebody already went through all the pains of manually writing and optimizing implementation of various Rx operations, then we should just use it. 

Rewriting Rx operators via Kotlin coroutines is like rewriting hand-crafted assembly code into C++. Why do if it works? 

The advantage of coroutines is that if you need some project-specific operator in your code, then you don't have to go though all those pains. You just write it with a few lines of code.

**Comment by AdamsGi** [comment]
@elizarov Thanks for sharing your thoughts!  Your example of "rewriting hand-crafted assembly code into C++" is convincing. Here is my takeaway: _reuse the Rx_ (and probably also RxJava2Extensions that @akarnokd works on), and, only for the rare case, _create project-specific operator using coroutines_.

BTW, absolutely agreeable that Rx is written very well!!
