### ISSUE TITLE
coroutineScope block the current thread

### ISSUE THREAD

**Issue by archerLj** [Kotlin/kotlinx.coroutines#1268]
I find `The main difference between runBlocking and coroutineScope is that the latter does not block the current thread while waiting for all children to complete.` at [kotlin basics](https://kotlinlang.org/docs/reference/coroutines/basics.html).

but the result seems that coroutineScope block the current thread when execute the following example code:

```
fun main() = runBlocking { // this: CoroutineScope
    launch { 
        delay(200L)
        println("Task from runBlocking")
    }
    
    coroutineScope { // Creates a coroutine scope
        launch {
            delay(500L) 
            println("Task from nested launch")
        }
    
        delay(100L)
        println("Task from coroutine scope") // This line will be printed before the nested launch
    }
    
    println("Coroutine scope is over") // This line is not printed until the nested launch completes
}
```

execute result is:
```
Task from coroutine scope
Task from runBlocking
Task from nested launch
Coroutine scope is over
```

Why `println("Coroutine scope is over") ` is called always last? if `coroutineScope` does not block the current thread.

**Comment by fvasco** [comment]
`coroutineScope` is a suspending function, it does not block the thread but suspends "`this: CoroutineScope`" coroutine.

> This function returns as soon as the given block and all its children coroutines are completed

See [coroutineScope](https://kotlin.github.io/kotlinx.coroutines/kotlinx-coroutines-core/kotlinx.coroutines/coroutine-scope.html)

**Comment by circusmagnus** [comment]
To put it simply: 
'''coroutineScope {}'''
just suspends its parent coroutine and does not block a thread. However its parent coroutine is runBlocking, which, being suspended by coroutineScope, truly blocks a thread.

Use '''launch{}''' as a parent coroutine and you will see no thread blocking.

**Comment by archerLj** [comment]
Thanks for your answer @fvasco @circusmagnus , and now i understand. That example code really confused me😊.  Following example help me understand better:

```
fun main() {
    runBlocking {
                Log.i("CoroutineDemo", "before delay in coroutine")
                delay(500L)
                Log.i("CoroutineDemo", "after delay in coroutine")
            }

    Log.i("CoroutineDemo", "out coroutine")
}
```

and 

```
fun main() {
        GlobalScope.launch(start = CoroutineStart.UNDISPATCHED) {
            coroutineScope {
                Log.i("CoroutineDemo", "before delay in coroutine")
                delay(500L)
                Log.i("CoroutineDemo", "after delay in coroutine")
            }
        }

        Log.i("CoroutineDemo", "out coroutine")
}
```
