### ISSUE TITLE
JVM options in Android Studio

### ISSUE THREAD

**Issue by archerLj** [Kotlin/kotlinx.coroutines#1271]
I'm learning to debug coroutines. I know there's JVM Options in IDEA configurations. But i can't find this options in Android Studio. Does it impossible in Android Studio?

**Comment by qwwdfsad** [comment]
I am not aware of such option in AS (though it doesn't mean it doesn't exist), but you can invoke 
`System.setProperty("kotlinx.coroutines.debug", "on")` in `onCreate` before using coroutines

**Comment by elizarov** [comment]
With R8 you can add the following configuration to your `proguard-rules.pro` file to statically enable debug:

```
-assumevalues class kotlinx.coroutines.DebugKt {
    static boolean DEBUG return true;
}
```

**Comment by archerLj** [comment]
@qwwdfsad @elizarov  Thanks, it works for me.
