### ISSUE TITLE
Unhelpful error message when crashing due to not including kotlinx-coroutines-android for Dispatchers.Main

### ISSUE THREAD

**Issue by chethaase** [Kotlin/kotlinx.coroutines#1272]
I was hitting a crash in my app with a simple coroutine, where the error message was a one-liner saying that the process had exited.
After playing around with the details of the coroutines, I finally got a more helpful message that Dispatchers.Main could not be used unless I included kotlinx-coroutines-android in my build.gradle file.

This was the root problem, and adding that dependency fixed it.
But the reason I'm reporting the problem is that for someone new to coroutines on Android, it's not obvious that this dependency is necessary (since base coroutines doesn't require it, and there's no build-time error). Then the crash message you get is nonexistent, so it takes a long time to figure out the root cause.

I've reproduced the issue in a very simple Android Studio project. It's mostly the situation I was seeing, although the error message is slightly different:
I/app_process: System.exit called, status: 0

To repro:
- Create a new Android Studio project (blank activity). I was using 3.5 beta 1
- add kotlinx-coroutines-core to build.gradle (I was using version 1.1.1)
- Modify the code in MainActivity.java to this:

    override fun onCreate(savedInstanceState: Bundle?) {
        super.onCreate(savedInstanceState)
        setContentView(R.layout.activity_main)

        GlobalScope.launch {
            println("onCreate: starting offThread")
            offThreadFunction()
            println("onCreate: Done with offThread")
        }
    }

    suspend fun offThreadFunction() {
        println("offThreadFunction begin")
        delay(1000L)
        withContext(Dispatchers.Main) {
            println("offThreadFunction-Main begin")
            delay(1000L)
            println("offThreadFunction-Main end")
        }
        println("offThreadFunction end")
    }

- Build/run and it should crash reliably with a similar error.

Suggested fix: Ideally, the system would detect that the correct module is not installed whenever it's going to use the Dispatchers.Main functionality and will spit out some stack trace or appropriate error that helps debug the situation.

**Comment by elizarov** [comment]
Hm... Can you attach some more details on your crash? What exception was in the logs when it crashed?

**Comment by chethaase** [comment]
There was no exception, that's why I'm filing the bug. One of the errors I saw is in the description above:
I/app_process: System.exit called, status: 0

**Comment by elizarov** [comment]
That seems to be a bug in some of the beta tool chain you are using. We don't call System.exit. We throw an exception.

**Comment by chethaase** [comment]
Interesting. I just tried this on AndroidStudio 3.3 and got the exception you're talking about:
2019-06-18 06:33:22.478 14490-14518/? E/AndroidRuntime: FATAL EXCEPTION: DefaultDispatcher-worker-2
    Process: com.android.coroutinescrash33, PID: 14490
    java.lang.IllegalStateException: Module with the Main dispatcher is missing. Add dependency providing the Main dispatcher, e.g. 'kotlinx-coroutines-android'
        at kotlinx.coroutines.internal.MissingMainCoroutineDispatcher.missing(MainDispatchers.kt:73)
        at kotlinx.coroutines.internal.MissingMainCoroutineDispatcher.isDispatchNeeded(MainDispatchers.kt:54)
...

(which is exactly what I was hoping to get originally)

I'll file this with the Studio team, maybe something changed in the tool chain as of 3.5 beta.

**Comment by elizarov** [comment]
Thanks a lot!
