### ISSUE TITLE
Reactive guide: comments after code blocks out of sync with code

### ISSUE THREAD

**Issue by Inego** [Kotlin/kotlinx.coroutines#1274]
https://github.com/Kotlin/kotlinx.coroutines/blob/master/reactive/coroutines-guide-reactive.md

1. In the "Take until" section, the comment after the code block mentions the `use` function:

> This code is using whileSelect as a nicer shortcut to `while(select{...}) {}` loop and Kotlin's `use` expression to close the channels on exit, which unsubscribes from the corresponding publishers.

But `use` here was refactored with `consume` back in January 2018.

2. In "Merge", there is the following comment:

> Notice, the use of `coroutineContext` in the invocation of `launch` coroutine builder.

`coroutineContext` is not passed to the invocation of `launch` (was refactored in September 2018).

**Comment by elizarov** [comment]
Good catch.
