### ISSUE TITLE
Confusing or incorrect error handling for Channel's produce method

### ISSUE THREAD

**Issue by lkjh654** [Kotlin/kotlinx.coroutines#1276]
According to the documentation [produce.html](https://kotlin.github.io/kotlinx.coroutines/kotlinx-coroutines-core/kotlinx.coroutines.channels/produce.html) and [exception-handling.html](https://kotlinlang.org/docs/reference/coroutines/exception-handling.html):

> Uncaught exceptions in this coroutine close the channel with this exception as a cause and the resulting channel becomes failed, so that any attempt to receive from such a channel throws exception.

> Coroutine builders come in two flavors: propagating exceptions automatically (launch and actor) or exposing them to users (async and produce). The former treat exceptions as unhandled, similar to Java's Thread.uncaughtExceptionHandler, while **the latter are relying on the user to consume the final exception, for example via await or receive** (produce and receive are covered later in Channels section).

After consulting such documentation I would assume that the following code should work properly and the exception should be caught only in the catch block 

```
import kotlinx.coroutines.*
import kotlinx.coroutines.channels.*

fun main() {
    GlobalScope.launch {
            val channel = produce<String> {
                throw IllegalStateException()
            }
            try {
                channel.receive()
            } catch (t: Throwable) {
                println("Error caught")
            }
        }
    Thread.sleep(2000L)
}
```

However it doesn't the `t: Throwable` is caught indeed:
```
Error caught
```

but the application is crashing as well:
```
Exception in thread "DefaultDispatcher-worker-1 @coroutine#1" java.lang.IllegalStateException
	at FileKt$main$1$channel$1.invokeSuspend(File.kt:7)
	at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:33)
	at kotlinx.coroutines.DispatchedTask.run(Dispatched.kt:238)
	at kotlinx.coroutines.scheduling.CoroutineScheduler.runSafely(CoroutineScheduler.kt:594)
	at kotlinx.coroutines.scheduling.CoroutineScheduler.access$runSafely(CoroutineScheduler.kt:60)
	at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.run(CoroutineScheduler.kt:742)
```

**Comment by fvasco** [comment]
The application does not crash, it only prints the error.

`GlobalScope.launch` terminate with an error, due structured concurrency: `produce` is a child of `GlobalScope.launch`.

To change this behaviour you have to run `produce` in a different scope, ie: `val channel = GlobalScope.produce<String>`
