### ISSUE TITLE
about kotlinx-coroutines-quasar

### ISSUE THREAD

**Issue by l42111996** [Kotlin/kotlinx.coroutines#128]
Most of our company is the development of java, only I use kotlin, I would like to use kotlinx.coroutines in our project, in addition to kotlinx-coroutines-quasar, there are other solutions? What is the stability of kotlinx-coroutines-quasar? Can I use the production environment? Use kotlinx-coroutines-quasar need javaagent?Thank you

**Comment by elizarov** [comment]
You can use Kotlin coroutines with Java without Quasar. You can wrap all your suspending functions into `CompletableFuture` using `kotlinx-coroutines-jdk8` module or into Guava's `ListenableFuture` via `kotlinx-coroutines-guava` (if you use Guava in your codebase). This way Kotlin code can be written with coroutines, while you Java code can continue to use Java-specific approach to asynchronous programming (futures).

The Quasar integration module is provided for cases where you already use Quasar in your company and want to start leveraging Kotlin coroutines. If you did not have the need to use Quasar before Kotlin, then Kotlin is not right reason to start using it. You should refer to Quasar documentation for details on how and when it can be used.
