### ISSUE TITLE
NoClassDefFoundError: kotlinx/coroutines/debug/internal/DebugProbesImpl

### ISSUE THREAD

**Issue by nbransby** [Kotlin/kotlinx.coroutines#1284]
I'm getting this after calling `DebugProbes.install()` in an intellij plugin which im running using the `gradle-intellij-plugin` gradle task `runIde`

It happens on the first usage of coroutines after the `DebugProbes.install()` call.

In my gradle file I have:
```
    implementation 'org.jetbrains.kotlinx:kotlinx-coroutines-debug:1.3.0-M1
```

Full trace is
```
java.lang.NoClassDefFoundError: kotlinx/coroutines/debug/internal/DebugProbesImpl
	at kotlin.coroutines.jvm.internal.DebugProbesKt.probeCoroutineCreated(DebugProbes.kt:130)
	at kotlin.coroutines.intrinsics.IntrinsicsKt__IntrinsicsJvmKt.createCoroutineUnintercepted(IntrinsicsJvm.kt:116)
	at kotlinx.coroutines.intrinsics.CancellableKt.startCoroutineCancellable(Cancellable.kt:25)
	at kotlinx.coroutines.CoroutineStart.invoke(CoroutineStart.kt:109)
	at kotlinx.coroutines.AbstractCoroutine.start(AbstractCoroutine.kt:154)
	at kotlinx.coroutines.BuildersKt__Builders_commonKt.launch(Builders.common.kt:54)
	at kotlinx.coroutines.BuildersKt.launch(Unknown Source)
	at kotlinx.coroutines.BuildersKt__Builders_commonKt.launch$default(Builders.common.kt:47)
	at kotlinx.coroutines.BuildersKt.launch$default(Unknown Source)
```

**Comment by nbransby** [comment]
Any ideas on this one? Really need this to work

**Comment by nbransby** [comment]
@qwwdfsad Can you help with this?

**Comment by qwwdfsad** [comment]
I have not enough context to help you. I am familiar neither with `gradle-intellij-plugin` nor with how are you using it alongside with coroutines. 

Wild guess:
If you are able to successfully invoke `DebugProbes.install`, but then you receive `NoClassDefFoundError: kotlinx/coroutines/debug/internal/DebugProbesImpl`, it may be a classloader issue. `DebugProbes.install()` redefines `kotlin.coroutines.jvm.internal.DebugProbesKt`  in the context of its own classloader, but `DebugProbesImpl ` can be loaded by a different classloader. Make sure that classloader of `DebugProbesImpl` is the same as `kotlin.coroutines.jvm.internal.DebugProbesKt`

**Comment by nbransby** [comment]
I suspect it could be to do with this then: http://www.jetbrains.org/intellij/sdk/docs/basics/plugin_structure/plugin_class_loaders.html

**Comment by qwwdfsad** [comment]
At first glance, you just could try to load (or just invoke `DebugProbes.install`) `DebugProbes` from the target class-loader.
If it is not possible for some reason, please explain it in details and then we can work on the proper solution (probably passing the right classloader to `install`)

**Comment by nbransby** [comment]
My issue was due my plugin using the platform provided version of kotlin and coroutines instead of shipping with its own version, when I shipped kotlinx-coroutines-debug in my plugin its using a different classloader. 

Solution was to ship all the kotlin libs in the plugin.
