### ISSUE TITLE
JVM Method Annotations on `suspend` lambdas don't apply

### ISSUE THREAD

**Issue by jeffalder** [Kotlin/kotlinx.coroutines#1289]
Kotlin/JVM: 1.3.40, targeting Java 8
Coroutines core: 1.2.1

I'm trying to annotate the `invokeSuspend` method on the inner class created by a lambda using an annotation that is targeted to a method. The method annotation doesn't get applied.

AnnotationsSuspendLambda.kt:
```
@file:Suppress("unused", "UNUSED_VARIABLE")

import kotlinx.coroutines.CoroutineScope


class AnnotationsSuspendLambda {
    fun foo() {
        val bar1: CoroutineScope.() -> Unit = @MyMethodAnnotation {
            println("hello")
        }
        val bar2: suspend CoroutineScope.() -> Unit = @MyMethodAnnotation {
            println("hello")
        }
        val bar3: CoroutineScope.() -> Unit = @MyMethodKotlinAnnotation {
            println("hello")
        }
        val bar4: suspend CoroutineScope.() -> Unit = @MyMethodKotlinAnnotation {
            println("hello")
        }
    }
}
```

MyMethodAnnotation.java:
```
import java.lang.annotation.ElementType;
import java.lang.annotation.Retention;
import java.lang.annotation.RetentionPolicy;
import java.lang.annotation.Target;

@Target({ElementType.METHOD})
@Retention(RetentionPolicy.RUNTIME)
public @interface MyMethodAnnotation {

}
```

MyMethodKotlinAnnotation.kt:
```
import kotlin.annotation.AnnotationTarget.FUNCTION

@Target(FUNCTION)
@Retention(AnnotationRetention.RUNTIME)
annotation class MyMethodKotlinAnnotation {
}
```

**Expected**: 
1. The decompiler shows that the annotation is applied to `bar1`, `bar2`, `bar3`, and `bar4` *OR*
2. A compiler warning is emitted that the annotation will be lost.

**Actual**: It appears via decompiler that the annotation is applied to `bar1` and `bar3` but _not_ `bar2` or `bar4` - the lambdas with the `suspend` keyword.

**Comment by jeffalder** [comment]
See repo, which has a test that fails on `bar2` and `bar4`.

**Comment by elizarov** [comment]
That would be an issue for Kotlin compiler. See http://kotl.in/issue
However, when you submit this issue to the Kotlin compiler please do include a use-case, that is explain why would you need to have those annotations retained, how would you plan to retrieve them, and would you want to use them.

**Comment by jeffalder** [comment]
@elizarov - Thanks, should we close this issue?

**Comment by elizarov** [comment]
Yes. It would be great if you leave a link to the created compiler issue just in case.

**Comment by jeffalder** [comment]
Converted to compiler issue: https://youtrack.jetbrains.com/issue/KT-32208?project=kt
