### ISSUE TITLE
ERROR: tried to execute code in unprepared class 'Lkotlin/coroutines/jvm/internal/DebugMetadataKt

### ISSUE THREAD

**Issue by tomashanley-toast** [Kotlin/kotlinx.coroutines#1293]
Hi,

I get an app crash on Android 4.4.2 a second or so after hitting a breakpoint in a function called from a coroutine. Note this doesn't happen on Android version 7.1.1.

```
06-25 10:18:28.320 13303-13496/com.mypackage E/dalvikvm: ERROR: tried to execute code in unprepared class 'Lkotlin/coroutines/jvm/internal/DebugMetadataKt;' (3)
06-25 10:18:28.320 13303-13496/com.mypackage I/dalvikvm: "DefaultDispatcher-worker-4 @coroutine#8" daemon prio=5 tid=74 RUNNABLE
06-25 10:18:28.320 13303-13496/com.mypackage I/dalvikvm:   | group="main" sCount=0 dsCount=0 obj=0x4234b780 self=0x7de55458
06-25 10:18:28.320 13303-13496/com.mypackage I/dalvikvm:   | sysTid=13496 nice=0 sched=0/0 cgrp=apps handle=2112182448
06-25 10:18:28.320 13303-13496/com.mypackage I/dalvikvm:   | state=R schedstat=( 0 0 0 ) utm=98 stm=90 core=1
06-25 10:18:28.320 13303-13496/com.mypackage I/dalvikvm:     at kotlin.coroutines.jvm.internal.DebugMetadataKt.getStackTraceElement(DebugMetadata.kt:-1)
06-25 10:18:28.320 13303-13496/com.mypackage I/dalvikvm:     at com.mypackage.MyClassImpl.myMethod(MyClass.kt:-1)
```

I have coroutines debug mode enabled programatically:
`System.setProperty("kotlinx.coroutines.debug", isDebugBuild ? "on" : "off");`

I don't have any watch expressions set up, as per [this stackoverflow question](https://stackoverflow.com/questions/10722462/adding-a-breakpoint-in-eclipse-causes-dalvik-to-crash).

I've also tried adding `-keep @interface kotlin.coroutines.jvm.internal.DebugMetadata { *; }` to my proguard file as per #858

Android version: 4.4.2
Kotlin Version : 1.3.40
Coroutines Version:  1.2.2

**Comment by qwwdfsad** [comment]
It looks like a ProGuard issue. Could you please report that to [Google bug tracker](https://issuetracker.google.com/issues/new)?

Also, please try to follow [these recommendations](https://github.com/Kotlin/kotlinx.coroutines/issues/1035#issuecomment-505834864) to disable aggressive ProGuard optimizations that may cause your issue

**Comment by mice777** [comment]
Same for me, but it's in debug version of app, so without ProGuard.
It's on emulator of Android 4.3.
```
: ERROR: tried to execute code in unprepared class 'Lkotlin/coroutines/jvm/internal/DebugMetadataKt;' (3)
: "main" prio=5 tid=1 RUNNABLE
:   | group="main" sCount=0 dsCount=0 obj=0xafa624b0 self=0xb79801c0
:   | sysTid=2472 nice=0 sched=0/0 cgrp=[fopen-error:2] handle=-1217212384
:   | state=R schedstat=( 0 0 0 ) utm=876 stm=209 core=0
:     at kotlin.coroutines.jvm.internal.DebugMetadataKt.getStackTraceElement(DebugMetadata.kt:-1)
:     at com.lonelycatgames.Xplore.context.ContextPageId3Tags$TagItemAlbumArt.createItem(ContextPageId3Tags.kt:-1)
:     at com.lonelycatgames.Xplore.context.ContextPageId3Tags$onStartVisible$1.invokeSuspend(ContextPageId3Tags.kt:399)
:     at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:33)
:     at kotlinx.coroutines.DispatchedTask.run(Dispatched.kt:238)
:     at android.os.Handler.handleCallback(Handler.java:730)
:     at android.os.Handler.dispatchMessage(Handler.java:92)
:     at android.os.Looper.loop(Looper.java:137)
:     at android.app.ActivityThread.main(ActivityThread.java:5103)
:     at java.lang.reflect.Method.invokeNative(Native Method)
:     at java.lang.reflect.Method.invoke(Method.java:525)
:     at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:737)
:     at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:553)
:     at dalvik.system.NativeStart.main(Native Method)
```

**Comment by adryx86** [comment]
Same for me debugging my app.. i'm working with real device using a 4.x android version and i'm not able to debug my code.. any idea ?

**Comment by adryx86** [comment]
I tried with another device using Android 5.1 version and the debug works perfectly.. it seems something related to the Android version 4.

**Comment by qwwdfsad** [comment]
Have you tried to follow the [recommendations](https://github.com/Kotlin/kotlinx.coroutines/issues/1035#issuecomment-505834864) and fallback to conservative optimizations?

**Comment by adryx86** [comment]
I tried but the program crash.. I found that running the code without the degugger it doesn't crash.
Maybe this is something related to the IDEA debugger ?

**Comment by qwwdfsad** [comment]
If you are trying to debug an application in the emulator, then it's Android toolchain issue.
If the crash occurs during debugging of a regular unit test without running a virtual device, then yes, it's likely to be an IDEA/AS debugger issue.

**Comment by e5l** [comment]
Same for kotlinconf-app debug a new coroutines:
```
E/dalvikvm: ERROR: tried to execute code in unprepared class 'Lkotlin/coroutines/jvm/internal/DebugMetadataKt;' (3)
I/dalvikvm: "main" prio=5 tid=1 RUNNABLE
      | group="main" sCount=0 dsCount=0 obj=0x9e6e2450 self=0xb823d4e0
      | sysTid=8319 nice=0 sched=0/0 cgrp=[fopen-error:2] handle=-1216367552
      | schedstat=( 0 0 0 ) utm=134 stm=11 core=3
        at kotlin.coroutines.jvm.internal.DebugMetadataKt.getStackTraceElement(DebugMetadata.kt:-1)
        at org.jetbrains.kotlinconf.ui.SpeakersViewModel$1.invoke(Speakers.kt:-1)
        ...
E/dalvikvm: VM aborting
A/libc: Fatal signal 11 (SIGSEGV) at 0xdeadd00d (code=1), thread 8319 (ains.kotlinconf)

```

**Comment by qwwdfsad** [comment]
I can tag Google folks here and ask them privately to take a look at the issue, but then I need a self-contained reproducer that I can run and reproduce the issue

**Comment by rgdzh1** [comment]
When I start an IntentService to perform a time-consuming operation, the code in withContext is not executed, but is skipped.
```kotlin
class PhoneInfoService : IntentService("XXX") {
    GlobalScope.launch {
            withContext(Dispatchers.IO) {
                 // Time-consuming operation
            }
    }
}
```
During the debugging process, the log printed is as follows:
```xml
09-01 12:22:34.680 22217-22437/com.xxx.xxx E/dalvikvm: ERROR: tried to execute code in unprepared class 'Lkotlin/coroutines/jvm/internal/DebugMetadataKt;' (3)
09-01 12:22:34.680 22217-22437/com.xxx.xxx E/dalvikvm: VM aborting
09-01 12:22:34.680 22217-22437/com.xxx.xxx A/libc: Fatal signal 6 (SIGABRT) at 0x000056c9 (code=-6), thread 22437 (DefaultDispatch)
09-01 12:22:34.680 22217-22437/com.xxx.xxx A/libc: Unable to open connection to debuggerd: Connection refused
```
The test machine model is Honor 6 Plus
System version: Android 4.4.2

**Comment by Giszmo** [comment]
I'm experiencing this issue, too. Doesn't look fixed and looks very reproducible.
