### ISSUE TITLE
Flow or BroadcastChannel

### ISSUE THREAD

**Issue by sheychen290** [Kotlin/kotlinx.coroutines#1294]
I'm trying to implement a multi room chat with Ktor and coroutines.

The basic idea is every one send in a global "Bus" and each client listen filtered bus by room or other.

And I don't get the difference between Flow and BroadcastChannel for this use.

**Comment by elizarov** [comment]
Flows are conceptually and usually"cold". They typically don't have any state when they have no subscribers. An event bus is more directly modelled by a hot entity like a broadcast channel.
