### ISSUE TITLE
how to run this code with jvm option?

### ISSUE THREAD

**Issue by shaomaicheng** [Kotlin/kotlinx.coroutines#130]
in Readme file about debug coroutines, i have a ask, how i run the koltin code with -Dkotlinx.coroutines.debug JVM option? i google it but donot search any result

**Comment by elizarov** [comment]
How do you normally run your Kotlin code? Command line? IDE?

**Comment by shaomaicheng** [comment]
IDE, do I need to use command line?

**Comment by elizarov** [comment]
You don't have to use command line. So do you run your code from IntelliJ IDEA?

**Comment by shaomaicheng** [comment]
yes, i run my code from IDEA, but i do not know how to set jvm options

**Comment by elizarov** [comment]
I you need to edit the corresponding Run configuration. See here: https://www.jetbrains.com/help/idea/run-debug-configurations.html
"VM Options" are there.

**Comment by shaomaicheng** [comment]
thanks~
