### ISSUE TITLE
Inconsistent behaviour GlobalScope.flux and flow/channelFlow with NonCancellable context.

### ISSUE THREAD

**Issue by gmarchelos** [Kotlin/kotlinx.coroutines#1301]
Reproducing inconsistent behaviour between flux and flow.
In flow case I see message "cancel2" in console but in flux case looks like `send` method is blocked and "cancel2" message is not produced.

It works very inconsistently in different scenarios, for example: 
1. Removing GlobalScope from flux 
2. Removing withContext(NonCancellable) from flux body and collect body
3. Replacing GlobalScope.flux with Flux.generate or Flux.create and adding withContext(NonCancellable) inside collect 
4. Adding backpressure operators like onBackpressureBuffer or publishOn to flux and buffer to flow.
5. Different behaviour for CancellationException in collect block.

Can you please investigate flux and flow behaviour with backpressure operators and withContext(NonCancellable) in different situations like inside collect, inside flux/flow, inside operators.

```kotlin
import kotlinx.coroutines.*
import kotlinx.coroutines.flow.*
import kotlinx.coroutines.flow.collect
import kotlinx.coroutines.reactive.collect
import kotlinx.coroutines.reactor.flux

fun main(): Unit {
    runBlocking(Dispatchers.Default) {
        val j = launch {
            try {
                GlobalScope.flux {
                //channelFlow {
                    try {
                        var i = 0
                        while (true) {
                            println("fluxActive: $isActive")

                            withContext(NonCancellable) {
                                delay(400)
                                println("send $i")
                                send(i++)
                            }
                            println("end while")
                        }
                    } catch (e: Exception) {
                        println("cancel2 ${e.message}")
                    }
                }
                    .collect {
                        withContext(NonCancellable) {
                            delay(1000)
                            println("Received: $it")
                        }
                        if (!isActive) throw CancellationException()
                    }

                println("all completed ok")
            } catch (e: CancellationException) {
                println("cancel")
            }
        }

        launch {
            delay(2000)
            j.cancelAndJoin()
        }

        delay(10000000)
    }
}
```

**Comment by qwwdfsad** [comment]
Could you please point a specific sample where code behave inconsistently, though it is expected (and why it is expected) to behave identically?

>It works very inconsistently in different scenarios, for example:
>Removing GlobalScope from flux

Well, yes, because it is a semantic change. This code **should** behave differently.

>Removing withContext(NonCancellable) from flux body and collect body

Again, a semantic change. This code **should** behave differently.

Additionally, it is not guaranteed that flux and flow should behave identically and have matching operators. `Flow` is indeed very similar to `Flux`, but not identical.

**Comment by gmarchelos** [comment]
I noticed that it works inconsistently in scenarios when I add backpressure operators to flux with NonCancellable in collect.
Flow works as expected for me but flux can't cancel itself in specified timespan and continue processing events.
Not sure why it can't cancel itself properly, perhaps, it is reactor library specifics.
Closing the issue for now.

**Comment by gmarchelos** [comment]
Reproducible flux code for reference:

```kotlin
val counter = AtomicLong(0)

val x = launch {
    GlobalScope.flux {
        var i = 0
        while (true) {
            try {
                send(i++)
            } catch (e: Exception) {
                println("in inner loop ${e.message}")
                throw e
            }
        }
    }.onBackpressureBuffer(Int.MAX_VALUE).collect {
        withContext(NonCancellable) {
            delay(1000)
            counter.addAndGet(it.toLong())
        }
    }
}

launch {
    delay(3000)
    x.cancelAndJoin()
}

delay(100000000)
```
