### ISSUE TITLE
delay(MAX_VALUE) breaks with non-monothonic clocks

### ISSUE THREAD

**Issue by elizarov** [Kotlin/kotlinx.coroutines#1312]
There's an circumstantial evidence that some systems may have non-monotonic implementation of `System.nanoTime()`. In this case the current implementation for `delay(Long.MAX_VALUE)` corrupts internal scheduling data structures and causes further delays to behave erratically.

**Comment by qwwdfsad** [comment]
https://kotlinlang.slack.com/archives/C1CFAFJSK/p1560718294297500
https://gist.github.com/MrPowerGamerBR/81da0b372584729fe5735a91a207edf2
