### ISSUE TITLE
CoroutineContext.plus() behaves counterintuitively

### ISSUE THREAD

**Issue by yorickhenning** [Kotlin/kotlinx.coroutines#1314]
The plus symbol [means addition](https://en.wikipedia.org/wiki/Plus_and_minus_signs#Plus_sign), by convention.

`CoroutineContext + CoroutineContext` is definitely _not_ addition. It's not commutative! `contextA + contextB` is not the same as `contextB + contextA`.

The only built-in I'm aware of that performs a similar operation to this function on immutable maps is Haskell's [`Map.union()`](https://hackage.haskell.org/package/containers-0.4.0.0/docs/Data-Map.html#g:8). That's a _left-biased_ map union, while `CoroutineContext.plus(CoroutineContext)` is (as far as I can tell) a _right-biased_ map union. Haskell's `Map.union()` doesn't use the + symbol to mean this.

[CoroutineScope.plus()](https://kotlin.github.io/kotlinx.coroutines/kotlinx-coroutines-core/kotlinx.coroutines/plus.html) also exists.

`scope + context` means `CoroutineScope(scope.coroutineContext + otherContext)`. Given the precedent of `CoroutineContext.plus(CoroutineContext)`, I'd assume `CoroutineContext.plus(CoroutineScope)` means `CoroutineScope(otherContext + scope.context)`, but it doesn't. That operator doesn't exist, so at least trying to use + commutatively won't compile.

It took me quite a while to figure out how my contexts overlaid using `plus()`. In hindsight, I should have stuck with nested/chained `withContext`s.

Here's what I've figured out.

These two expressions are equivalent:

```kt
  fun contexts(c: CoroutineContext, d: CoroutineContext) {
    CoroutineScope(c).launch {
      withContext(this.coroutineContext + d) {}
    }
    CoroutineScope(c).launch {
      withContext(d) {}
    }
  }
```

These two _aren't_:

```kt
  fun contexts(c: CoroutineContext, d: CoroutineContext) {
    CoroutineScope(c).launch {
      withContext(d + this.coroutineContext) {}
    }
    CoroutineScope(c).launch {
      withContext(d) {}
    }
  }
```

These two expressions are equivalent. The first one is somewhat intuitive (barring the map-union bit), because block scoping is just block scoping:

```kt

  fun contextsEnn(c: CoroutineContext, d: CoroutineContext, e: CoroutineContext) {
    CoroutineScope(c).launch {
      withContext(d) {
        withContext(e) {}
      }
    }
    CoroutineScope(c).launch {
      withContext(d + e) {}
    }
```

This expression doesn't compile:

```kt
 fun contexts(c: CoroutineContext, d: CoroutineContext) {
    CoroutineScope(c).launch {
      withContext(d + this) {}
    }
  }
```

And for obtuseness bonus points, `CoroutineScope.sum()` means these two expressions are equivalent (I think!):

```kt
  fun contexts(c: CoroutineContext, d: CoroutineContext) {
    CoroutineScope(c).launch {
      withContext(d) {}
    }
    CoroutineScope(c).launch {
      (this + d).launch {}
    }
  }
```

The documentation for `withContext()` [points to CoroutineContext.plus()](https://github.com/Kotlin/kotlinx.coroutines/blob/master/kotlinx-coroutines-core/common/src/Builders.common.kt#L136) for its semantics.

I argue that only `withContext()` should be available, and + should be deprecated and ultimately removed.

Trying to figure out what + will do is a bit too mind-bending. As defined, I don't think the operators are appropriately using the + symbol. What terseness + buys Context propagation is outweighed by breaking readers' intuition about what a + does, let alone what these + expressions actually mean.

`CoroutineContext` is a constructor argument to `CoroutineScope`. The innocent-looking sum expression `scope + someContext` is loaded with the meaning "copy-construct-left-operand-using-right-operand-as-right-operand-in-right-biased-map-union-with-previous-constructor-call's-operand". That's not terribly readable. It's a footgun.

I won't start in on multi-operand associativity. :)

**Comment by qwwdfsad** [comment]
It's not the first time someone argues about `+` operator :)

>The plus symbol means addition, by convention.

Yes, in mathematics, not in general-purpose programming languages. In some languages, one cannot override `+`, but Kotlin is not one of them.

>CoroutineContext + CoroutineContext is definitely not addition. It's not commutative! contextA + contextB is not the same as contextB + contextA.

Well, `String` concatenation is also not addition and definitely is not commutative. Map and list concatenations are neither. What should we do here to keep Kotlin concise (that's why `+` overload exists in the first place), but also consistent and mathematically pure? One could go by Scala way and use `++` for collections (but not for String :)), but this ship has sailed.

>The only built-in I'm aware of that performs a similar operation to this function on immutable maps s ...

Map concatenation in both `Kotlin` and `kotlinx.immutable`, `++` operator in Scala (consistent with `++` for lists), for example. Generally speaking, it is a shorthand for `foldLeft`.


About your general concerns regarding context `+` operator. Semantically, `CoroutineContext` is an immutable map with a very specialized API shape. It has the `+` operator for the same reasons as regular `Map` and it is expected to have it. Please note, that this decision is not about someone's personal preferences, but rather about **being consistent** with the language. Such behaviour can be unexpected for people from Haskell, but once you are in the Kotlin ecosystem, you *expect* something that looks like a map to have `+` operator.
The good example of such consistency is coding convention. If you have a company-wide code style, you stick to it, even if you don't like some of its parts. And ignoring that convention eventually will do more harm for the whole team than benefits for the sake of "right" coding style.


>scope + context means CoroutineScope(scope.coroutineContext + otherContext). Given the precedent of CoroutineContext.plus(CoroutineContext), I'd assume CoroutineContext.plus(CoroutineScope) means CoroutineScope(otherContext + scope.context), but it doesn't. 

This was done deliberately. Once having a `scope`, you may want to augment it. Using `uiScope + myThreadLocal` makes sense, while `myThreadLocal + uiScope` is not (especially taking into account right-bias). But usages of this overload is not so common, maybe we should deprecate it.


>I argue that only withContext() should be available, and + should be deprecated and ultimately removed.

`withContext` is not identical to `+` operator, neither semantically, nor by performance characteristics.
For example:
```
CoroutineScope(c + NonCancellable).launch { ... }.cancelAndJoin()
CoroutineScope(c).launch { withContext(NonCancellable) { ...  } }.cancelAndJoin()
``` 
these lines are not identical.


>I won't start in on multi-operand associativity. :)

`+` operator is associative.

> ` withContext(this.coroutineContext + d) {}`

Note that `this.coroutineContext` is always present explicitly and is not required.
`withContext(d)` and `withContext(this.coroutineContext + d)` are literally the same.

**Comment by yorickhenning** [comment]
> `+` operator is a very popular and controversial topic :)

A good indication that it's too clever by half...

> > The plus symbol means addition, by convention.
> 
> Yes, in mathematics, not in general-purpose programming languages.

Many useful languages don't support overloading, precisely to avoid counterintuitive definitions, and operator-precedence weirdness. [Of those languages that do support overloads](https://en.wikipedia.org/wiki/Operator_overloading#Criticisms), they generally don't ship + operators that are not well-defined in mathematics in the standard library. That creeps in with downstream libraries and careless client code programmers. :)

> In some languages, one cannot override `+`, but Kotlin is not one of them.

On the face of it, it doesn't follow that overriding `+` is a good idea.

> > CoroutineContext + CoroutineContext is definitely not addition. It's not commutative! contextA + contextB is not the same as contextB + contextA.
> 
> Well, `String` concatenation is also not addition and definitely is not commutative. Map and list concatenations are neither. 

Strings and Lists are both ordered. Using + for concatenation isn't the clearest, but it's common. Java and Python are popular, and both commit that crime. Defining + for collections that aren't ordered is a different kettle of fish, and not common. [Even operator-happy Python hasn't crossed that bridge, though it seems they're thinking about it](https://www.python.org/dev/peps/pep-0584/).

> What should we do here to keep Kotlin concise (that's why `+` overload exists in the first place), but also consistent and mathematically pure?

Define a two-operand static function or one-operand member function with a short name, something like `foldLeft`?

Sometimes, things are more readable with more characters and well-known invocation semantics. For a counterxample: regular expressions.

> One could go by Scala way and use `++` for collections (but not for String :)), but this ship has sailed.
> 
> > The only built-in I'm aware of that performs a similar operation to this function on immutable maps s ...
> 
> Map concatenation in both `Kotlin` and `kotlinx.immutable`, `++` operator in Scala (consistent with `++` for lists), for example. Generally speaking, it is a shorthand for `foldLeft`.
> About your general concerns regarding context `+` operator. Semantically, `CoroutineContext` is an immutable map with a very specialized API shape. It has the `+` operator for the same reasons as regular `Map` and it is expected to have it. Please note, that this decision is not about someone's personal preferences, but rather about **being consistent** with the language. Such behaviour can be unexpected for people from Haskell, but once you are in the Kotlin ecosystem, you _expect_ something that looks like a map to have `+` operator.
> The good example of such consistency is coding convention. If you have a company-wide code style, you stick to it, even if you don't like some of its parts. And ignoring that convention eventually will do more harm for the whole team than benefits for the sake of "right" coding style.

I was unaware of that. Something I'll run into in the depot and get annoyed at sooner or later. :)

If `CoroutineContext + CoroutineContext` weren't following an SDK precedent, I'd be more inclined to die on this hill. I buy the argument for consistency with Kotlin's Map.

Given consistency with Map is a goal, why not construct `CoroutineContext` from a `Map` or type it as a `Map<>`, instead of defining a weaker sorta-mappish type? That'd permit callers to use Map functions to clearly express whatever complicated Context change they mean. Use `Map<Key<*>, CoroutineContext.Element>` instead of the `CoroutineContext`, or at least implement that type to make it explicit how it behaves.

Right now, `CoroutineContext` is, in a comment, not its type, an "indexed set". It doesn't type itself as a `Map<>`, but what's the possible definition of a `CoroutineContext` that _doesn't_ have map semantics? Would that `CoroutineContext` make any sense summed with any other `CoroutineContext`?

> > scope + context means CoroutineScope(scope.coroutineContext + otherContext). Given the precedent of CoroutineContext.plus(CoroutineContext), I'd assume CoroutineContext.plus(CoroutineScope) means CoroutineScope(otherContext + scope.context), but it doesn't.
> 
> This was done deliberately. Once having a `scope`, you may want to augment it. Using `uiScope + myThreadLocal` makes sense, while `myThreadLocal + uiScope` does not (especially taking into account right-bias). But usages of this overload is not really widespread, so maybe we should deprecate it.

I think that's a very good idea. I buy the consistency argument for a Map-like object, but + copy construction with the plus applying to the constructor parameter is a bridge too far in pursuit of terseness.

I've heard plus copy construction is a bit of a bugbear using Boost in copy-free high-performance C++, because Boost frequently uses + for copy construction. Terseness at the cost of performance.

> > I argue that only withContext() should be available, and + should be deprecated and ultimately removed.
> 
> `withContext` is not identical to `+` operator, neither semantically, nor by performance characteristics.

Agreed. Then I don't think supporting the sometimes-less-performant path is necessarily desirable. That'd mean no `withContext()`?

> For example:
> 
> ```
> CoroutineScope(c + NonCancellable).launch { ... }.cancelAndJoin()
> CoroutineScope(c).launch { withContext(NonCancellable) { ...  } }.cancelAndJoin()
> ```
> 
> these lines are not identical.

Meaning one creates two nested scopes before executing the task block, and one creates a single scope with its Context pre-joined before executing the task block?

They're semantically the same from the perspective of the block being executed, hopefully...

> > I won't start in on multi-operand associativity. :)
> 
> `+` operator is associative.

I wouldn't have guessed. Is that documented?

> > ` withContext(this.coroutineContext + d) {}`
> 
> Note that `this.coroutineContext` is always present explicitly and is not required.
> `withContext(d)` and `withContext(this.coroutineContext + d)` are identical as documentation states:
> 
> > The resulting context for the [block] is derived by merging the current [coroutineContext] with the
> > specified [context] using `coroutineContext + context` (see [CoroutineContext.plus]).

**Comment by elizarov** [comment]
> Given consistency with Map is a goal, why not construct `CoroutineContext` from a `Map` or type it as a `Map<>`, instead of defining a weaker sorta-mappish type? That'd permit callers to use Map functions to clearly express whatever complicated Context change they mean. Use `Map<Key<*>, CoroutineContext.Element>` instead of the `CoroutineContext`, or at least implement that type to make it explicit how it behaves.

`Map` is pretty heavy-weight interface to implement, with lots of methods and implicit expectations (like an implicit expectation of `O(1)` time for `size()`), too heavy for something as ubiquitous as the `CoroutineContext` is supposed to be. We can provide `CoroutineContext.asMap()` extension to get a map _view_ of it, but we don't really have any real-life use-cases that would benefit from being able to use all the power of `Map` extensions on a `CoroutineContext`.

> > + operator is associative.

> I wouldn't have guessed. Is that documented?

Its associativity immediately follows from its documented definition.

**Comment by elizarov** [comment]
Hopefully, we've answered all the questions here. Closing this issue.
