### ISSUE TITLE
SupervisorJob handles Exceptions in an unexpected way (?)

### ISSUE THREAD

**Issue by streetsofboston** [Kotlin/kotlinx.coroutines#1317]
Say we have this code:
```
val cehParent = CoroutineExceptionHandler { c, e ->
    println("Parent Handled Crash $e")
}

val cehChild = CoroutineExceptionHandler { c, e ->
    println("Child Handled Crash $e")
}

fun main() {
    val scope = CoroutineScope(Dispatchers.IO + Job())

    val child1 = scope.launch(cehParent) {
        println("Launched Child 1")

        delay(500)
        val result = try { five() } catch (e: Throwable) { -1 }

        delay(500)
        println("Child 1 is still running with result $result")
    }

    val child2 = scope.launch {
        println("Launched Child 2")

        delay(1500)
        println("Child 2 is still running")
    }

    Thread.sleep(2000)
}
```
and we'll implement the function `five()` in various ways:

**1. The function just inherits the coroutine-scope:**
```
suspend fun five(): Int = coroutineScope {
    val grandChild1_1 = launch {
        delay(100)
        throw SillyException()
    }
    val grandChild1_2 = async {
        delay(500)
        5
    }
    grandChild1_2.await()
}
```
This prints out:
> Launched Child 1
> Launched Child 2
> Child 1 is still running with result -1
> Child 2 is still running

And this makes sense, the printed out logs are what I expect. The `grandChild1_1` coroutine finishes with an exception, causing `five()` to throw that exception, which is then caught by `child1`'s code; the result is`-1`.

**2. The function inherits the supervisor-scope:**
This now uses a `SupervisorJob` instead of a `Job`.
```
suspend fun five(): Int = supervisorScope {
    val grandChild1_1 = launch {
        delay(100)
        throw SillyException()
    }
    val grandChild1_2 = async {
        delay(500)
        5
    }
    grandChild1_2.await()
}
```
This prints out:

> Launched Child 1
> Launched Child 2
> **Parent Handled Crash io.intrepid.coroutines_playground.SillyException: Silly**
> Child 2 is still running
> Child 1 is still running with result **5**

The function `five()` no longer throws an exception and `child1`'s code just receives is result `5`. This is because the `grandChild1_1` coroutine finishes with an exception, but its parent runs in a `SupervisorJob`, which then does **not** finish (with an exception) and its sibling `grandChild1_2` keeps running and finally returns 5, that is returned by `five()`. All good so far.

**However, I did not expect the `cehParent` to handle the exception**. The `Parent Handled Crash io.intrepid.coroutines_playground.SillyException: Silly` is printed out 
I thought that since the `SupervisorJob` of the `supervisorScope` 'eats' its child's exception and just makes `five()` return `5` and lets the program go its merry way.

All the more, because of this modified example below:

**3. The function inherits the supervisor-scope and installs CoroutineExceptionHandler:**
See the installation of the other CoroutineExceptionHandler called `cehChild`. 
```
suspend fun five(): Int = supervisorScope {
    val grandChild1_1 = launch(cehChild) {
        delay(100)
        throw SillyException()
    }
    val grandChild1_2 = async {
        delay(500)
        5
    }
    grandChild1_2.await()
}
```
Now this printed out.

> Launched Child 1
> Launched Child 2
> **Child** Handled Crash io.intrepid.coroutines_playground.SillyException: Silly
> Child 2 is still running
> Child 1 is still running with result 5

The printing out of the `5` result is still expected.

But I don't understand the `Child Handled Crash io.intrepid.coroutines_playground.SillyException: Silly` log... 
In example **2.**, the `cehParent` handled it. In this example `cehChild` handles it. This is unexpected.

I thought only the handler of the **top-most** scoped `launch`-coroutine can install an effective CoroutineExceptionHandler. 

If the `supervisorScope` of the `five()` function prevents the exception from bubbling up to its parent, then example **2.** should have shown an error/crash log because `cehChild` was not installed there. 

**My question is:**
_How are exceptions handled when dealing with `SupervisorJob`s?_ 
Some things are not behaving as expected (as I understand them).

**Comment by streetsofboston** [comment]
From the documentation here: https://kotlin.github.io/kotlinx.coroutines/kotlinx-coroutines-core/kotlinx.coroutines/-supervisor-job.html

I read this:
> A failure of a child job that was created using launch can be handled via CoroutineExceptionHandler in the context.

That would mean that scenario (3.) shows an expected behavior because the `cehChild` is invoked, correct?

However, is it correct that `cehParent` is invoked in scenario (2.)? 

Is this a documentation issue or a bug in how exceptions are handled in a SupervisorScope?

**Comment by elizarov** [comment]
All the coroutines in your code inherit `CoroutineExceptionHandler`.  Now, you start your coroutine with `launch` which propagates the exception to parent (when possible) or delivers it to the exception handler. With `supervisorScope` there is no propagation, so a crashed `launch` coroutine delivers its uncaught exception to the inherited `CoroutineExceptionHandler`.

**Comment by streetsofboston** [comment]
Thank you, @elizarov!

The *inheritance* of the `CoroutineExceptionHandler` is the part that I didn't realize. This explains what my code examples show.
