### ISSUE TITLE
New operator: RepeatWhen

### ISSUE THREAD

**Issue by PaulWoitaschek** [Kotlin/kotlinx.coroutines#1318]
I am missing `Flow.repeatWhen`.

My application is structured in a way that I expose a single state to the view called `ViewState`.
This state is wrapped in a `LoadingState` which is a sealed class and it can contain
```kotlin
object Error : LoadingState()
object Loading : LoadingState()
data class Content<T>(content : T) : LoadingState()
```
So my views consume a `Flow<LoadingState<ViewState>>`.
This flow never throws exceptions. On `LoadingState.Error` I show a retry button in my UI which should call the flow again.

My naive implementation is currently written like this:

```kotlin
fun <T> Flow<T>.repeatWhenEmits(repeat: Flow<*>): Flow<T> {
  return flow {
    collect { emit(it) }
    repeat.collect {
      collect { emit(it) }
    }
  }
}
```

**Comment by linean** [comment]
I've added PR with repeatWhen operator:
https://github.com/Kotlin/kotlinx.coroutines/pull/1848/files

**Comment by elizarov** [comment]
So, given:

```
val repeatButton: Flow<Unit> // button clicks
fun viewState(): Flow<LoadingState<ViewState>> // never ending
```

You need to restart `viewState()` every time button is clicked. Do I get the problem correctly?

Have you considered this solution:

```
repeatButton.flatMapLatest { viewState() }
```
