### ISSUE TITLE
Flow.asPublisher() gets stuck in case of infinite Flows

### ISSUE THREAD

**Issue by budaimartin** [Kotlin/kotlinx.coroutines#1324]
I was trying to create a streaming endpoint in my Spring Boot app with an infinite flow, but when converting `Flow` to `Flux` using `asPublisher()` it gets stuck, most probably due to eager evaluation.

Please see this repo for a brief example: https://github.com/budaimartin/kotlin-infinite-flow-demo

**Comment by gmarchelos** [comment]
@budaimartin , not a kotlin coroutines' issue. 
I am reproducing the same behaviour with Flux.
```ok().body(Flux.interval(Duration.ofSeconds(1)).doOnNext { println("1") })```
please submit this issue to spring project.

fyi @qwwdfsad

**Comment by budaimartin** [comment]
@gmarchelos Thanks for the answer and sorry for the confusion! This issue came up during a migration project from Java+Flux to Kotlin+Flow, that's why I thought this was a Kotlin coroutines issue.

Just for your information: I managed to solve the issue now by adding `.contentType(MediaType.APPLICATION_STREAM_JSON)` before `body`. Still, I don't think if this is the expected behavior, so I will submit the issue to Spring.
