### ISSUE TITLE
Stacktrace recovery doesn't work for suspend main

### ISSUE THREAD

**Issue by opensource21** [Kotlin/kotlinx.coroutines#1328]
I took the example https://raw.githubusercontent.com/Kotlin/kotlinx.coroutines/master/kotlinx-coroutines-debug/test/RecoveryExample.kt and add at line 16 a `println("${Thread.currentThread().name}")`, so I get
```
package example

import kotlinx.coroutines.CoroutineName
import kotlinx.coroutines.CoroutineScope
import kotlinx.coroutines.Dispatchers
import kotlinx.coroutines.async

object PublicApiImplementation : CoroutineScope by CoroutineScope(CoroutineName("Example")) {

    private fun doWork(): Int {
        error("Internal invariant failed")
    }

    private fun asynchronousWork(): Int {
        println("${Thread.currentThread().name}")
        return doWork() + 1
    }

    public suspend fun awaitAsynchronousWorkInMainThread() {
        val task = async(Dispatchers.Default) {
            asynchronousWork()
        }

        task.await()
    }
}

suspend fun main() {
    // Try to switch debug mode on and off to see the difference
    PublicApiImplementation.awaitAsynchronousWorkInMainThread()
}
```
I run it with 

1. -ea
2. -Dkotlinx.coroutines.debug -Dkotlinx.coroutines.stacktrace.recovery=true
3. -Dkotlinx.coroutines.debug

I never get an recovered stacktrace. How ever I got
`DefaultDispatcher-worker-1 @Example#1`
so `-Dkotlinx.coroutines.debug` seems to work.

What does I'm missing?
Here my version
kotlin 1.3.41 
coroutines.version 1.2.2

**Comment by qwwdfsad** [comment]
Thanks for the report!
It appears like a missing recovery in one of the `await` branches, will investigate further

**Comment by opensource21** [comment]
@qwwdfsad do you know a version where it works. Would be nice to see this feature in action.

**Comment by opensource21** [comment]
I looked in org/jetbrains/kotlinx/kotlinx-coroutines-core/1.2.2/kotlinx-coroutines-core-1.2.2-sources.jar!/commonMain/JobSupport.kt:1131. It seems that the state Empty{Active} isn't the expected one.

**Comment by qwwdfsad** [comment]
@opensource21 it works in the latest version except for your particular case (with suspending `await`).
I will fix your problem in `1.3.0`

**Comment by qwwdfsad** [comment]
As a workaround, you can use `fun main() = runBlocking { ... }` instead of `suspend fun main()`

**Comment by opensource21** [comment]
If you clone https://gitlab.com/ppiag/zulipbot, rename application.properties.sample to application.properties and replace `zulip.url=https://####.zulipchat.com` with `zulip.url=https://www.zulipchat.com` and start BotRunner , I guess you have a different situation with ktor and it doesn't work. Unfortunately it's not so easy to debug :-(

Any idea when 1.3 will be released or a beta for a test?
