### ISSUE TITLE
Exception cause is changed when using `Deferred.await()`

### ISSUE THREAD

**Issue by xa17d** [Kotlin/kotlinx.coroutines#1336]
Hey, I have an issue with exceptions thrown within `async {...}`. When an exception is thrown within `async`, and I use `Deferred.await()` to get the exception, the exception's `cause` is not correct anymore.
Let me explain it with an example:

```
import kotlinx.coroutines.async
import kotlinx.coroutines.runBlocking
import org.junit.Test

class AsyncExceptionIssue {
    /**
     * This test shows the expected behavior, without using coroutines.
     * This test passes.
     */
    @Test
    fun `Exception including cause is as thrown`() {
        try {
            throw IllegalArgumentException(
                "Level1",
                IndexOutOfBoundsException("Level2")
            )
        } catch (e: Exception) {
            assert(e::class == IllegalArgumentException::class)
            assert(e.cause!!::class == IndexOutOfBoundsException::class)
        }
    }

    /**
     * This test does the same again, but throws the exception inside an `async {...}` block.
     * When using `await()` the exception's cause is not the same as the one thrown.
     * This test fails, but it should pass IMO.
     */
    @Test
    fun `Exception including causes are as thrown with async`() = runBlocking {
        val result = async {
            throw IllegalArgumentException(
                "Level1",
                IndexOutOfBoundsException("Level2")
            )
        }

        try {
            result.await()
        } catch (e: Exception) {
            assert(e::class == IllegalArgumentException::class)
            assert(e.cause!!::class == IndexOutOfBoundsException::class)
            // The second assert fails because `e` isn't the same as in the test above anymore.
            //
            // What is expected:
            //   IllegalArgumentException: Level1
            //   Caused by: IndexOutOfBoundsException: Level2
            //
            // How `e` actually looks like:
            //   IllegalArgumentException: Level1
            //   Caused by: IllegalArgumentException: Level1
            //   Caused by: IndexOutOfBoundsException: Level2
            //
            // It looks like the thrown exception is wrapped again in a `IllegalArgumentException`
            // with the same `message`.
        }
    }
}
```

Not that the types of the Exceptions don't matter. I just used them, because they are available in the _stdlib_. If I use `CustomException` instead of `IllegalArgumentException`, then `e` looks like this:
```
CustomException: Level1
Caused by: CustomException: Level1
Caused by: IndexOutOfBoundsException: Level2
```

Is this expected behavior or is this a bug?

I found the issue in `org.jetbrains.kotlinx:kotlinx-coroutines-core:1.1.1`/`org.jetbrains.kotlin:kotlin-stdlib:1.3.21`, but can still reproduce it on `org.jetbrains.kotlinx:kotlinx-coroutines-core:1.3.0-M2`/`org.jetbrains.kotlin:kotlin-stdlib:1.3.40`

Thank you!
And keep up the awesome work!

**Comment by qwwdfsad** [comment]
This is intended behaviour for unit tests called [stacktrace recovery](https://github.com/Kotlin/kotlinx.coroutines/blob/master/docs/debugging.md#stacktrace-recovery) to expose "asynchronous" stacktraces through coroutine boundaries. It generally simplifies debugging and stacktrace analysis to answer the question "where this exception came from and where it was handled", but with a cost of additional `cause` indirection.
You can disable this feature by a corresponding system property.

Thank you for your kind words!

**Comment by xa17d** [comment]
Thank you for the fast response. I wasn't aware that _stacktrace recovery_ has this  additional `cause` indirection. I close the issue.
