### ISSUE TITLE
Rename `run`

### ISSUE THREAD

**Issue by elizarov** [Kotlin/kotlinx.coroutines#134]
There is a confusion between `kotlinx.coroutines.experimental.run` and `kotlin.run` functions from stdlib. We should rename the former. A better name is TBD.

**Comment by deviant-studio** [comment]
`await`
`fetch`
`asyncAwait`

**Comment by fvasco** [comment]
I consier `runOn(context)` (or `runIn(context)`) more appropriate (https://discuss.kotlinlang.org/t/calling-suspending-function-from-regular-function/3670/9)

**Comment by cypressious** [comment]
`suspending`
`withContext`
`runSuspending`

**Comment by DmitriyZaitsev** [comment]
That's the issue I was going to open for several weeks!
I consider three options:
* `runOn` - because takes a coroutine context and calls a block of code with it
* `runSuspending` - because it suspends until given block completes
* `runAsync` - because not blocking and often used within other coroutines as a replacement for async/await

**Comment by bj0** [comment]
My vote is for `await`, because it is effectively doing the same thing (awaiting a result).  It also better matches other languages, so would be less mental work for those who go between languages.

**Comment by elizarov** [comment]
Some comments. `await` is off the table, because we have reserved it to mean "wait for some kind of future" and reusing it for `run` is a bad idea (there is no future and no concurrency there). `asyncAwait` might be used since `run(ctx) { smth }`  is roughly equivalent to `async(ctx) { smth }.await()`.

I personally prefer, though, `runXX` variations. However, I would refrain from `runAsync`, since for many people "async" is connected to "concurrent", but there is nothing concurrent going on when you switch the context with `run` (on the contrary, it all remain pretty sequential).

**Comment by DmitriyZaitsev** [comment]
One more option is `call`. Because it returns a result similar to `Callable#call()` and unlike `runWhatever` which is talkative but long, this name is short.

**Comment by elizarov** [comment]
We seem to be unable to find any short names that are unambiguois and convey what is happening. The current contenders are:
* `runIn`, which reads nicely as `runIn(UI) { ... }` and is consisent with `stdlib.run` in other respects. It looks worse when used as `runIn(NonCancellable) { ... }`, but we can attempt to fix the later by somehow renaming `NonCancellable` or just providing a specialized `withoutCancellation { ... }` for it.

* `withContext`, which reads nicely as both `withContext(UI) { ... }` and `withContext(NonCancellable) { ... }`, it is consistent with `stdlib.with` in other respects, and it consistent with how `withTimeout(time) { ... }` is named, which works overally quite well. The only downside is that it is longer, but you can also consider this to be an upside, since it is top-level function that is not used very often.

**Comment by fvasco** [comment]
`withContext(coroutineContext)` looks clear.

`withoutCancellation` doesn't seem much clear.

**Comment by EddieRingle** [comment]
Well, `go` might be a fun choice.

**Comment by XinyueZ** [comment]
withContext

**Comment by elizarov** [comment]
I've used `go` in the original example for the [design document](https://github.com/Kotlin/kotlin-coroutines/blob/master/kotlin-coroutines-informal.md), but that implementation was behaving more like `launch`, since that is what it does in Go language. Using `go` or `run` with be very confusing for developers with golang experience.

**Comment by EddieRingle** [comment]
> I've used go in the original example for the design document, but that implementation was behaving more like launch, since that is what it does in Go language. Using go or run with be very confusing for developers with golang experience.

That's fair. It was mostly a joke, though. :)

I don't like `withContext` or `with*`. Aside from seeming too generic (Android has Contexts too, for example), it would look asymmetric when compared to `launch`, unless both functions were renamed, respectively, `runWithContext(...)` and `launchWithContext(...)`.

Then again, both `run` and `launch` are verbs whereas the third in the group is `async` which is an... adjective, I guess? Or if you presume it to be shorthand for something like `doAsynchronously`, you could rename `run` to `sync`, perhaps.

**Comment by LouisCAD** [comment]
@elizarov Wouldn't `runIn(...) { ... }` and `runNonCancellable { ... }` have been better named than `withContext` that by itself doesn't make which type of "Context" we are referring to? (may lead to confusion with Android's Context for example)

**Comment by erik-browne-emc** [comment]
There are still references to run() in ui/coroutines-guide-ui.md

**Comment by elizarov** [comment]
@LouisCAD We've went back and forth though different names and had decide that `withContext` better for consistency with `withTimeout`, even though they are both non verb-based. This naming precedent is set by stdlib function `with(x) { ... }`.

**Comment by mtopolnik** [comment]
As a user of `withContext` in an Android project I can add my experience. In a specific example, I have this line:

```kotlin
val nextFrame = withContext(threadPool) { gifDecoder.nextFrame }
```

(`threadPool` is a global `val` in my project, my own threadpool-context)

The name `withContext` is unevocative. It doesn't convey the magic of what it will do; more importantly, it doesn't signal that it's about coroutines at all. The suggestion `runIn` would solve a lot of issues I have with the current name, even though it may have some other problems.

 As a designer of public API myself I'm kind of sorry to have to bring this up, I share your pain :)
