### ISSUE TITLE
withTimeoutOrNull and channel send/receive

### ISSUE THREAD

**Issue by fvasco** [Kotlin/kotlinx.coroutines#1355]
Our server is affected by sporadic errors, these errors are not well defined and not reproducible.

I wrote a bad test case (#1281) some time ago, sorry, a have to file a new issue.

In our previous experience the major candidate is `withTimeoutOrNull` + `channel.send`, the in that case the coroutine hangs indefinitely.

The prevision version below worked without any issue

```kotlin
val delay = launch { delay(42) }
whileSelect {
    channel.onReceive {
        consume(it) // no suspension
        true
    }
    delay.onJoin { false }
}
```

Yesterday we get a similar issue, the code is:

```kotlin
withTimeoutOrNull(42){
    val value = channel.receive()
    consume(value) // no suspension
}
```

We _suspect_ that a single `value` was extracted but not consumed.

Thoughts?

_Edit: `consume` is not a suspending function_

**Comment by elizarov** [comment]
These particular code path are pretty well covered by functional and stress-tests and I wonder what might have gone wrong. Any chance for a reproducer?

**Comment by fvasco** [comment]
Thank you for response @elizarov,
this is wonderful response.

I tried to reproduce this issue without any success.

In this particular case the `consume` function is `list.add(value)`, I detected in production that one item was lost or was not processed.
Unfortunately there is no log to understand what exactly went wrong.

I will reopen this issue when further updates will be available.

Thank you again.

**Comment by fvasco** [comment]
I answer myself.

> Thoughts?

Bug or not, chunking a channel using `withTimeoutOrNull` is probably a bad style of code: it mixes cancellable and non-cancellable blocks, additionally it works using the non cancellability of non-suspending function as a trick.

Using a selector is the way to go, maybe it is slower and harder to write, moreover it requires to cancel `delay` job manually (#1065), but it works always as expected.

**Comment by elizarov** [comment]
Still it should work and pretty-well covered by tests....
