### ISSUE TITLE
Stacktrace recovery doesn't work with ktor

### ISSUE THREAD

**Issue by opensource21** [Kotlin/kotlinx.coroutines#1358]
Analog to #1328  there is a similar issue with Ktor.

If you clone https://gitlab.com/ppiag/zulipbot, rename application.properties.sample to application.properties and replace `zulip.url=https://####.zulipchat.com` with `zulip.url=https://www.zulipchat.com` and start BotRunner . Unfortunately it's not so easy to provide a simpler example.

Tested with 1.3.0-RC

**Comment by qwwdfsad** [comment]
Could you please elaborate what's the problem?
What is expected and what is an actual behavior?

Your instruction only explains how to start your application, but not the problem

**Comment by opensource21** [comment]
Sorry for the incomplete issue:
If you do the described steps, the program should exit with an exception after a few seconds.
Expected was that I get a stacktrace with `(Coroutine boundary)` 
But I only get the normal stacktrace.
The program must be startet with 
java -Dkotlinx.coroutines.debug -Dkotlinx.coroutines.stacktrace.recovery=true de.ppi.oss.zulipbot.common.BotRunnerKt

**Comment by qwwdfsad** [comment]
Everything works as expected.

>Expected was that I get a stacktrace with (Coroutine boundary)


But an exception (`java.net.MalformedURLException: no protocol: zulip.url=https://www.zulipchat.com/api/v1/messages`) does not cross any coroutine boundary.

It's thrown from within`launch` and is caught in the same coroutine. There is no information that can be further provided.

**Comment by qwwdfsad** [comment]
Though I've spotted a missing line number in one of the frames, filed https://youtrack.jetbrains.com/issue/KT-33185

**Comment by opensource21** [comment]
I guess that in your `application.properties` has the line `zulip.url=zulip.url=https://www.zulipchat.com` instead of `zulip.url=https://www.zulipchat.com`. Then I get the same exception as you described.

With `zulip.url=https://www.zulipchat.com` I get

```
2019-08-07 14:55:31,814 [pool-3-thread-1 @coroutine#2] d.p.o.z.c.BotRunner                 - ERROR: Error running test: Received bad status code: 401 Unauthorized. Expected status code < 300. {"result":"error","msg":"Invalid API key"}
.
de.ppi.oss.kzulip.ktor.BadZulipResponseStatusException: Received bad status code: 401 Unauthorized. Expected status code < 300. {"result":"error","msg":"Invalid API key"}

	at de.ppi.oss.kzulip.ktor.ExpectZulipSuccess$Companion$install$1.invokeSuspend(ExpectZulipSuccess.kt:24) ~[kzulip-0.4.2.jar:?]
	at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:33) [kotlin-stdlib-1.3.41.jar:1.3.41-release-150 (1.3.41)]
	at kotlinx.coroutines.DispatchedTask.run(Dispatched.kt:241) [kotlinx-coroutines-core-1.3.0-RC.jar:?]
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149) [?:1.8.0_152]
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624) [?:1.8.0_152]
	at java.lang.Thread.run(Thread.java:748) [?:1.8.0_152]

```

**Comment by qwwdfsad** [comment]
Thanks for pointing it out, investigating. Looks like an issue on the edge of kotlinx.coroutines and Ktor

**Comment by qwwdfsad** [comment]
`BadZulipResponseStatusException` has two additional fields and is not a  `CopyableThrowable`, so it cannot be recovered anyway (see https://github.com/Kotlin/kotlinx.coroutines/blob/master/docs/debugging.md#stacktrace-recovery-machinery)

I am investigating further whether it works with Ktor machinery

**Comment by qwwdfsad** [comment]
Filed https://github.com/ktorio/ktor/issues/1267 and https://github.com/ktorio/ktor/issues/1268

**Comment by opensource21** [comment]
Thanks for the hint about the exception. I created an [issue](https://gitlab.com/ppiag/kzulip/issues/1) and will try to fix it.
