### ISSUE TITLE
[Flow] combineLatest strange behaviour on Result<T>

### ISSUE THREAD

**Issue by ZeDzislaw** [Kotlin/kotlinx.coroutines#1361]
Hello guys,
I run into a trouble combining two flows where the first was flow of Result<T>.
I wrote some tests to find out what's going on, but I don't get correlation between passing just first flow stream value through combineLatest transformer and wrapping this in downstream as Result.Success of this value (which in fact was also a Result but of Failure).

Here are some test that you can run:

``` @Test
    fun tests() {
        runBlockingTest {
            val error = Exception()
            val result = Result.failure<String>(error)
            val other = "a"
            listOf(result)
                    .map {
                        it
                    }
                    .forEach {
                        val res = result == it
                        println("Is there strange behav on just mapping? : ${!res} / $it")
                    }
            flowOf(result)
                    .map {
                        it
                    }
                    .collect {
                        val res = result == it
                        println("Is there strange behav on flow mapping? : ${!res} / $it")
                    }
            flowOf(result)
                    .combineLatest(
                            flowOf(other)
                    ) { f, _ ->
                        f
                    }.collect {
                        val res = result == it
                        println("Is there strange behav on flow combine latest passing just first value? : ${!res} / $it")
                    }
```
And results are:
`Is there strange behav on just mapping? : false / Failure(java.lang.Exception)`
`Is there strange behav on flow mapping? : false / Failure(java.lang.Exception)`
`Is there strange behav on flow combine latest passing just first value? : true / Success(Failure(java.lang.Exception))`

**Comment by qwwdfsad** [comment]
Thanks for the report!
It is a bug in Kotlin compiler I've filed https://youtrack.jetbrains.com/issue/KT-32821
