### ISSUE TITLE
Can not disable stack trace recovery for a specific exception

### ISSUE THREAD

**Issue by emiksk** [Kotlin/kotlinx.coroutines#1367]
I want to disable stack trace recovery for coroutine when a specific exception is thrown.

In jvm/src/debug.kt, it is written as follows:
https://github.com/Kotlin/kotlinx.coroutines/blob/d293639980d7a6141394dc8174180f221daa4787/kotlinx-coroutines-core/jvm/src/Debug.kt#L22

However, a stack trace is recovered even if the exception is CancellationException.
https://github.com/Kotlin/kotlinx.coroutines/blob/d293639980d7a6141394dc8174180f221daa4787/kotlinx-coroutines-core/jvm/src/internal/StackTraceRecovery.kt#L159-L160

I have questions: 
1. How can I disable stack trace recovery for a specific exception? Should I wait until NonRecoverableThrowable becomes public (as the comment in the link below says) ?https://github.com/Kotlin/kotlinx.coroutines/blob/085a4cb7dec4121f51cda832dbe1e223681d3379/kotlinx-coroutines-core/common/src/internal/StackTraceRecovery.common.kt#L46-L50

2. The comment in the link below says that if the exception is an instance of CancellationException, Stacktrace will not be recovered. Is this comment wrong? 
https://github.com/Kotlin/kotlinx.coroutines/blob/d293639980d7a6141394dc8174180f221daa4787/kotlinx-coroutines-core/jvm/src/Debug.kt#L22

**Comment by qwwdfsad** [comment]
Hi, this part of documentation became slightly obsolete, we've decided to recover `CancellationException` for the sake of better debuggability. 

As a workaround, you can add an additional property to your class to make it unrecoverable (see [debugging.md](https://github.com/Kotlin/kotlinx.coroutines/blob/master/docs/debugging.md#stacktrace-recovery-machinery) p.2).

A proper solution would be indeed making `NonRecoverableThrowable` public.
Before doing so, could you please elaborate why do you have to disable stacktrace recovery for one particular class and what problem are you solving by this?

**Comment by qwwdfsad** [comment]
I've just realized that you can implement `CopyableThrowable.createCopy` in a way to always return `null` if you want to opt-out
