### ISSUE TITLE
Confusing crash log (probably coroutines)

### ISSUE THREAD

**Issue by CoolMind** [Kotlin/kotlinx.coroutines#1370]
I use coroutines in release build. So, after Android minification I get crash logs with weird lines (stack trace is gotten from web analytics).

```
kotlin.KotlinNullPointerException
at com.package.LocationFragment.access$centerLocation()
  access$drawCircle
  access$getErrorMessage
  access$getErrorMessage
  access$getSeekBarPosition
  access$getServices
  access$getServices
  access$setBackgroundTint
  access$setCityId$p
  access$setLatitude$p
  access$setLocationListener$p
  access$setLocationProvider$p
  access$setRadiusChangedJob$p
  access$setSeekBarPositionSet$p
  access$showParametersFragment
  access$showStationsCount
  access$showUserLocation
  addCircle
  getCircleZoomValue
  getCity
  getErrorMessage
  getErrorMessage
  getServices
  isLocationChanged
  onActivityResult
  onCreateView
  onMapReady
  onRequestPermissionsResult
  setBackgroundTint
  setClickListeners
  showParametersFragment
  showStationsCount
  showUserLocation
at com.package.LocationFragment.access$getCityId$p()
  access$hideProgress
  access$moveMapToLocation
  access$selectRadius
  access$setLongitude$p
  access$setRegionId$p
  access$setSeekBarPosition
  access$showErrorDialog
  drawCircle
  getSeekBarPosition
  showErrorDialog
at com.package.LocationFragment$initLocationListener$1.onLocationChanged()
...
at android.location.LocationManager$ListenerTransport._handleMessage(LocationManager.java:371)
at android.location.LocationManager$ListenerTransport.access$000(LocationManager.java:300)
at android.location.LocationManager$ListenerTransport$1.handleMessage(LocationManager.java:316)
at android.os.Handler.dispatchMessage(Handler.java:106)
at android.os.Looper.loop(Looper.java:193)
at android.app.ActivityThread.main(ActivityThread.java:6692)
at java.lang.reflect.Method.invoke(Native Method)
at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:493)
at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:858)
```
Most methods are mine, but there are no line numbers. Even worse, an order of lines is unclear, so I can't understand, what happened and where. I suspect `access$` are called in coroutines and `access$setLongitude$p` is the same as `longitude =`. But I can't understand anything.

For instance, some methods:

    private fun showUserLocation(location: Location) {
        latitude = location.latitude
        longitude = location.longitude
        drawCircle(latitude, longitude)
        view?.let { getServices(it) }

        moveMapToLocation(location.latitude, location.longitude)
    }
    private fun initLocationListener() {
        locationListener = object : LocationListener {
            override fun onLocationChanged(location: Location) {
                Timber.d(
                    "onLocationChanged: latitude = ${location.latitude}, longitude = ${location.longitude}")
                removeLocationUpdates()
                locationListener = null
                showUserLocation(location)
            }
    ...
    }

    private fun getCity(view: View, latitude: Double, longitude: Double) {
        showProgress(view)
        launch(Dispatchers.IO) {
            try {
                val response = interactor.getCity(latitude, longitude)
                if (response.success == ApiConst.RIGHT_SUCCESS_CODE) {
                    regionId = response.city?.region_id
                    cityId = response.city?.id
                    launch(Dispatchers.Main) {
                        if (isAdded) {
                            hideProgress(view)
                            getServices(view, regionId, cityId)
                        }
                    }
                }
            } catch (e: Exception) {
                launch(Dispatchers.Main) {
                    if (isAdded) {
                        showErrorDialog(getString(R.string.connection_timeout))
                        hideProgress(view)
                    }
                }
            }
        }
    }

I suppose I should read the log from top to bottom and find `access$` lines, then try to understand, what method crashed an application. Why so difficult?

**Comment by qwwdfsad** [comment]
I am not sure how exactly it is `kotlinx.coroutines` issue.
Your application crashes with KNPE somewhere in `centerLocation` method.
`access$foo` is a synthetic accessor generated by the compiler to comply with some VM-specific invariant, it just delegates call to `foo`. 

Missing line numbers and order of lines is due to enabled minifier, it is better to ask about it on Android-specific resources

**Comment by CoolMind** [comment]
@qwwdfsad, thanks for the answer, but it is not closed.

    private fun centerLocation() {
        moveMapToLocation(latitude, longitude)
        drawCircle(latitude, longitude)
        if (locationManager?.isProviderEnabled(LocationManager.GPS_PROVIDER) == true ||
            locationManager?.isProviderEnabled(LocationManager.NETWORK_PROVIDER) == true) {
            initLocationListener()
        } else {
            showLocationSettingsDialog()
        }
    }

It can't contain any KNPE.

**Comment by CoolMind** [comment]
I see, this repository has bad support team.

**Comment by CoolMind** [comment]
@qwwdfsad, I added `throw RuntimeException("message")` in one line of code. Then the application crashed, I saw stacktrace. So, the erraneous method was not in the first line of stack! You are wrong. But right, that Proguard mixes lines.
