### ISSUE TITLE
UncaughtExceptionCaptor does not provide a way to assert against and remove an exception from the list

### ISSUE THREAD

**Issue by ZakTaccardi** [Kotlin/kotlinx.coroutines#1378]
I'd like to assert if a specific exception was thrown under a `TestCoroutineScope`. `UncaughtExceptionCaptor` only provides an immutable list of exceptions, so even if I can assert that an expected exception was thrown, the test would still fail when `cleanupTestCoroutines` is called in `@After`

**Comment by elizarov** [comment]
cc @objcode

**Comment by ZakTaccardi** [comment]
> Could you be using an assertFailsWith<Xxxx> { ... } around your code

I tried this, but didn't work.


> are looking for a way to assert that there are certain uncaught exceptions after execution

yep

**Comment by dkhalanskyjb** [comment]
We no longer even provide `UncaughtExceptionCaptor` with 1.6.0-RC. Instead, some exceptions that used to go to the `CoroutineExceptionHandler` will just be propagated structurally and should be handled correspondingly.

If there's still a need to check the uncaught exceptions, one should define their own exception handler, like described here: https://github.com/Kotlin/kotlinx.coroutines/blob/master/kotlinx-coroutines-test/MIGRATION.md#remove-usages-of-testcoroutineexceptionhandler-and-testcoroutinescopeuncaughtexceptions

Given the age of this issue, I'll be closing it, but feel free to reopen it if you have some specific use cases in mind that are not covered well by this.
