### ISSUE TITLE
Provide JUnit Rule that provides a scope that functions like `runBlockingTest`

### ISSUE THREAD

**Issue by ZakTaccardi** [Kotlin/kotlinx.coroutines#1391]
I would like to leverage a separate `@Before setUp()` phase that utilizes a `TestCoroutineScope` that will be used in a `@Test` method - and I would like that the `@Test` block to function similarly to how `runBlockingTest { .. }` works - would this be possible?

An ideal rule would allow the following:

```kotlin
    @get:Rule
    val coroutinesTestRule: CoroutinesTestRule = CoroutinesTestRule()

    private lateinit var test: TestDelegate

    @Before
    fun setup() {
        test = TestDelegate(coroutinesTestRule)
    }

    @Test
    fun `isFeatureEnabled - Disabled`() = runBlocking<Unit> {
        test.givenX()
            .whenY()
            .thenZ()
    }
```

I attempted to implement `CoroutinesTestRule` myself - but it seems a little more involved that simply creating a `TestCoroutineScope` and calling `scope.cleanupTestCoroutines()` at the end.

I had to instead leverage `runBlockingTest { .. }` to get the behavior I wanted, like the special behavior for `delay(..)`

```kotlin
    @get:Rule
    val coroutinesTestRule: CoroutinesTestRule = CoroutinesTestRule()

    private lateinit var test: TestDelegate

    @Before
    fun setup() {
        test = TestDelegate(coroutinesTestRule.testCoroutineScope)
    }

    @Test
    fun `isFeatureEnabled - Disabled`() = runBlockingTest {
        test = TestDelegate(this@runBlockingTest) // would like to avoid having to do this, and be able to do it in a `@Before setUp()` phase

        test.givenX()
            .whenY()
            .thenZ()
    }
```

**Comment by elizarov** [comment]
cc @objcode

**Comment by qwwdfsad** [comment]
Since 1.6.0-RC it should be enough to create `TestScope` manually and invoke `runTest` right on it
