### ISSUE TITLE
Flow from sequence

### ISSUE THREAD

**Issue by halimpuckjava** [Kotlin/kotlinx.coroutines#1399]
hi

add asFlow() extension to sequence

**Comment by fvasco** [comment]
https://kotlin.github.io/kotlinx.coroutines/kotlinx-coroutines-core/kotlinx.coroutines.flow/kotlin.sequences.-sequence/as-flow.html ?

**Comment by halimpuckjava** [comment]
@fvasco thanks maybe i will update kotlin coroutine version

**Comment by halimpuckjava** [comment]
after update my kotlin coroutine to last version i found does no method extension fo List to conert to flow
