### ISSUE TITLE
kotlin.time.Duration overloads for delay in common

### ISSUE THREAD

**Issue by JakeWharton** [Kotlin/kotlinx.coroutines#1402]

**Comment by JakeWharton** [comment]
I would also consider deprecating `delay(long)` with a replacement of `delay(value.milliseconds)`

**Comment by hfhbd** [comment]
Any plans to deprecate `delay(long)` and other `timeMillis: Long` parameters in favor of `Duration` parameter? It is stable since Kotlin 1.6 and coroutines `1.7` allows breaking changes.
Do you accept such PR?

**Comment by qwwdfsad** [comment]
We do not have such plans yet, though it is a good idea not to introduce new API that relies on long millis
