### ISSUE TITLE
JS: TypeError: Cannot read property 'nextTick' of undefined

### ISSUE THREAD

**Issue by webleaf** [Kotlin/kotlinx.coroutines#1404]
```
TypeError: Cannot read property 'nextTick' of undefined
```
I've got this error on `1.3.0+`. All works until `1.2.2`.
I use JS environment different from node.js and browser (mobile js framework NativeScript). There are no `window` and there are no `process`. (seems related with https://github.com/Kotlin/kotlinx.coroutines/pull/1027 https://github.com/Kotlin/kotlinx.coroutines/issues/820)
https://github.com/Kotlin/kotlinx.coroutines/blob/7699a20982c83d652150391b39567de4833d4253/kotlinx-coroutines-core/js/src/JSDispatcher.kt#L81
And seems like in `1.3.0+` `kotlinx-coroutines-core` introduce some changes that rely on the assumption that besides node.js and browser there is no other JS environments.
How can I use coroutines in just general JS environment now?

**Comment by qwwdfsad** [comment]
It looks like on `NativeScript` only `setTimeout` is present as the dispatch mechanism.
Could you please share a reproducing project? I am mostly interested in setuping `NativeScript` for KotlinJS + kotlinx-coroutines

**Comment by webleaf** [comment]
@qwwdfsad reproducing project: [issue1404.zip](https://github.com/Kotlin/kotlinx.coroutines/files/3464205/issue1404.zip)
>It looks like on NativeScript only setTimeout is present as the dispatch mechanism.

Does it means until `1.2.2` it worked for me based on `setTimeout/cleareTimeout`? Because it seemed to worked pretty well, despite the fact that `setTimeout/clearTimeout`  is not js-engine functions, but wrappers of platform specific implementations (Android/iOS) (such platform calls may have micro-delays in `NativeScript`)

**Comment by qwwdfsad** [comment]
>Does it means until 1.2.2 it worked for me based on setTimeout/cleareTimeout

Yes.

>Will this bug be fixed in 1.3.0?

Most likely

Thanks for the sample project, it was really helpful and saved a lot of time!

**Comment by webleaf** [comment]
Thanks a lot for fast reaction (really did not want to get stuck with `1.2.2` and Kotlin `1.3.40`)

Woot! Nifty! Superb! 🚀
