### ISSUE TITLE
Anyway to push exceptions to consume from produce or channel etc?

### ISSUE THREAD

**Issue by XinyueZ** [Kotlin/kotlinx.coroutines#142]
Hi, I've switched from Rx to coroutine in order to simplify an android application, however, the produce or channel has only ```send(some results)``` method which ties only to generic type binding on produce or channel itself.  When the application has exception inside produce, how can we push exception to consume? 

Actually, it would be nice to have the methods like:

```ch.recevieThrowable```
or
```ch.consumeThrowable```
etc... 

I know some ways to do error-handling like [this](http://tinyurl.com/yckotvp2).
Any other ideas?

**Comment by elizarov** [comment]
The exception that is thrown inside of `produce { ... }` builders gets automatically carried over to receiver. If you create your channels manually, then you can `close` the channel with exception. There is the following correspondence between Rx concepts and channels: `onNext(x)` - `send(x)`, `onComplete()` - `close()`, `onError(t)` - `close(t)`.

See more here: https://kotlin.github.io/kotlinx.coroutines/kotlinx-coroutines-core/kotlinx.coroutines.experimental.channels/-send-channel/close.html

**Comment by XinyueZ** [comment]
@elizarov got it, thx
