### ISSUE TITLE
Debounce operator not working as expected ??

### ISSUE THREAD

**Issue by shakil807g** [Kotlin/kotlinx.coroutines#1434]
fun main() = runBlocking<Unit> {
             flow {
             emit(1)
             delay(99)
             emit(2)
             delay(99)
             emit(3)
             delay(1001)
             emit(4)
             delay(1001)
             emit(5)
      }.debounce(1000).collect {
             println(it)   // print  3, 5
     }

Above code print 3, 5
I expected it to print    3, 4, 5

**Comment by shakil807g** [comment]
I found out there was a mistake in flow docs i change it to below and works fine

        fun main() = runBlocking<Unit> {
         flow {
         emit(1)
         delay(99)
         emit(2)
         delay(99)
         emit(3)
         delay(1001)
         emit(4)
         delay(1002)   ------->  increase 1 millisecond
         emit(5)
      }.debounce(1000).collect {
           println(it)   // print  3, 4, 5
     }

**Comment by qwwdfsad** [comment]
Hi, thanks for the report.
The given example exposes the semantics of the method properly but fails in reality due to clock inaccuracy. I will adjust it to work on the default clocks as well
