### ISSUE TITLE
Newly created Jobs considered as cancelled after only 1 occurence of an exception

### ISSUE THREAD

**Issue by libetl** [Kotlin/kotlinx.coroutines#1438]
Hello,

I am trying to build an async flow whose role is to merge identical calls into one (but that is not really related to this bug) https://github.com/libetl/coroutines-pooling-client

I am using an CoroutineScope.async operation where I happen to throw an exception in case of an error received from the user implementation.
https://github.com/libetl/coroutines-pooling-client/blob/master/src/main/kotlin/org/toilelibre/libe/poolingclient/PoolingClientStrategy.kt#L153

The flow starts failing systematically once the first exception bubbled up, making all the coroutine executor threads to vanish.

Once the first ResultFailure is read, the statement
https://github.com/Kotlin/kotlinx.coroutines/blob/master/kotlinx-coroutines-core/common/src/CompletedExceptionally.kt#L12
always decides to use CompletedExceptionally class while I am expecting to have a call to throwOnFailure().

As a result, every subsequent call to the same async operation will call `recoverAndThrow`
https://github.com/Kotlin/kotlinx.coroutines/blob/master/kotlinx-coroutines-core/jvm/src/internal/StackTraceRecovery.kt#L150
and will keep on returning the previously bubbled up exception instead of re-executing the user implementation.

1) Did I make myself clear enough in the above description ?
2) Is it an expected behaviour ?
3) What could have gone wrong ?
4) Thank you for your help

**Comment by zach-klippenstein** [comment]
It would probably be helpful if you could provide a smaller, self-contained example that reproduces your issue - it's not clear from that link what the actual `CoroutineScope` is that is being passed to `Caller`. From your description though, it sounds like the `async` jobs are all getting cancelled - the first thing I'd check is that the job in that scope is a `SupervisorJob`. 

Unrelated to this issue, `callAndGroupBy` can leak subscriptions. If the job is cancelled while receiving from `taskIdSubscriber` on line 130, none of your subscription channels will get closed. If the `select` on line 140 throws (eg job was cancelled or either of the channels failed), `resultSubscription` and `errorSubscription` won't get closed. I would recommend wrapping all that code in `ReceiveChannel.consume`s to automatically close the channels if an exception is thrown.

**Comment by libetl** [comment]
```kotlin
package org.toilelibre.libe.poolingclient

import kotlinx.coroutines.*
import kotlin.coroutines.EmptyCoroutineContext
import kotlin.test.Test

class ThrowingRunnerTest {


    @Test
    fun `throwing in the middle`() {
        var count = 0
        val method: CoroutineScope.() -> Deferred<Int?> = {
            async {
                if (++count == 7) throw UnsupportedOperationException()
                count
            }
        }

        val coroutineScope = CoroutineScope(EmptyCoroutineContext)

        val toRun = (0..1).map {
                coroutineScope.async {
                        repeat(10) {
                            delay(20L)
                            println(method().await())
                        }

                }
        }

        try {
            runBlocking {
                toRun[0].await()
            }
        }catch (e: UnsupportedOperationException) { println("Ignoring failure")}
        println("deliberately incrementing the counter : ${++count}")
        println("and then with counter = $count")
        runBlocking {
            toRun[1].await()
        }

    }
}
```

Is there something I should know about coroutines resume ?

**Comment by libetl** [comment]
cc @zach-klippenstein

**Comment by zach-klippenstein** [comment]
All your async jobs share a common parent job, which lives in `coroutineScope`. The first time any of those jobs fail (you throw an UOE), that exception gets stored in the `Deferred`, but it also gets reported to the parent job, in `coroutineScope`, which cancels that job and stores the failure there as well. This happens The first time `toRun[0]` calls `await()`. The next time you try using that job to launch a new coroutine (i.e. when `toRun[1]` calls `await`), it won't even get started because the parent job is already cancelled, and the resulting `Deferred` will just immediately report the same error.

`async` is weird like that, it reports exceptions both up (to its parent) and down (to the `Deferred`).

In your test, you can fix this by making the parent job a `SupervisorJob`:

```kotlin
val coroutineScope = CoroutineScope(SupervisorJob())
```

`SupervisorJob` ["is similar to a regular Job with the only exception that cancellation is propagated only downwards."](https://kotlinlang.org/docs/reference/coroutines/exception-handling.html#supervision-job)

**Comment by libetl** [comment]
Thanks, that was exactly the piece of advice I needed.
I changed the context to be SupervisorJob and the new jobs remain healthy even after a failure.
