### ISSUE TITLE
Weak ref auf CoroutineContext?

### ISSUE THREAD

**Issue by XinyueZ** [Kotlin/kotlinx.coroutines#144]
Hey, should we use ```WeakReference``` to keep ```CoroutineContext``` gilt before it would be collected by GC? Well in Android we should do it ever when ```Context``` is passed to other, do we do at coroutines cases?

```
class Foo (private val cxt:  CoroutineContext){
  // Do something fool....
}
```

```
launch {
....
 val foo = Foo(coroutineContext)
....
}
```

**Comment by elizarov** [comment]
`CoroutineContext` is very small object that is being referenced as long as coroutine in running. I don't see any benefits in keeping `WeakReference` to it.

**Comment by XinyueZ** [comment]
k k
