### ISSUE TITLE
ListenableFuture future() cancellation

### ISSUE THREAD

**Issue by yorickhenning** [Kotlin/kotlinx.coroutines#1442]
[Issue 1346](https://github.com/Kotlin/kotlinx.coroutines/issues/1346) describes cancellation issues with ListenableFuture.kt.

The PR that should close that issue fixes up `asDeferred()` and `asListenableFuture()`, but _doesn't_ fix `future()`.

`future()` also needs modifying to implement bidirectional cancellation, and some tests validating it.

I'll TAL.

**Comment by elizarov** [comment]
Ping?

**Comment by yorickhenning** [comment]
I haven't had the time to work on this since I filed it. If someone's interested I can hand this off. Is there urgency from anywhere?
