### ISSUE TITLE
SuperVisorJob prevents runBlocking to wait for completion of its children

### ISSUE THREAD

**Issue by kazemihabib** [Kotlin/kotlinx.coroutines#1443]
fun main() = runBlocking<Unit> {
        val supervisor = SupervisorJob()
        launch(supervisor) {
            println("before delay")
            delay(2000L)
            println("After delay")
        }

        println ("After launch")
    }

produce:

    After launch
    before delay

`After delay` not printed.

I couldn't find anything about this behavior of SuperVisorJob in the docs and maybe it's a bug.

**Comment by elizarov** [comment]
This is so by design, because this `SupervisorJob()` that you create is not a child of the parent scope. You can make it a child by creating it with `SupervisorJob(coroutineContext[Job])` or just use `supervisorScope { ... }` scoping function that does that for you.
