### ISSUE TITLE
Should CompletionStage.asDeferred be discouraged?

### ISSUE THREAD

**Issue by glasser** [Kotlin/kotlinx.coroutines#1447]
My understanding based on reading the source is that [`CompletionStage.asDeferred`](https://kotlin.github.io/kotlinx.coroutines/kotlinx-coroutines-jdk8/kotlinx.coroutines.future/java.util.concurrent.-completion-stage/as-deferred.html) from the JDK8 integration creates a new **unscoped** coroutine.  This seems contrary to most of the recent guidance around the importance of scoped concurrency.

Is my interpretation correct? Should the docs for `asDeferred()` warn more strongly against this, and perhaps encourage the use of `async { completionStage.await() }` over `completionStage.asDeferred()`? Maybe even to the level of deprecating it?

The only "advantage" that I can see to using `completionStage.asDeferred()` over `async { completionStage.await() }` is that it can be called without a CoroutineScope, but that's literally the problem with it too.

**Comment by qwwdfsad** [comment]
> ... creates a new unscoped coroutine. This seems contrary to most of the recent guidance around the importance of scoped concurrency.

Yes, when we are talking about the regular coroutines. But here you already have (unstructured) completion stage, so you have to manually manage it. 
Indeed, `async { completionStage.await() }` does not fix the issue, but just masks it. Under the hood, you still have potentially leaking completion stage.

`asDeferred` is mostly designed for the interop with Java, e.g. you have a completion stage from Java and your own API that accepts Deferred and we can't discourage users from that.

Do you have a real-world example of `asDeferred` misuage?

**Comment by glasser** [comment]
Well, CompletableFuture.await() does call cancel() on the CompletableFuture
(if it is in fact a CompletableFuture) on cancellation. Perhaps not every
use of CF properly implements cancellation but if you're lucky enough that
it does, your Java interop does now achieve structured concurrency if you
use async/await but not if you use the seemingly equivalent asDeferred.

**Comment by glasser** [comment]
If I understand properly, with `.asDeferred()`, once you actually `.await()` the Deferred somewhere, things will get hooked up properly so that cancellation of the `.await()`ing coroutine invokes the handler set up by `Job.cancelFutureOnCompletion` to cancel the future, but if the `Deferred` object gets leaked before calling `.await()`, this doesn't happen.  If you make your `Deferred` with `async { f.await() }`, then you don't have that issue.

Basically, my concern is that it looks like `f.asDeferred()` is just syntax sugar for `async { f.await() }` but it isn't (because the latter has an often-implicit CoroutineScope).  My suggestion is to change the docs for `asDeferred()` to something like this (which I'm happy to open a PR for). Note that this is basically the inverse of the advice already given on `CompletionStage.await`.

>>>
Converts this completion stage to an instance of [Deferred].
When this completion stage is an instance of [Future], then it is cancelled when
the resulting deferred is cancelled.

Note that the [Job] of the created [Deferred] is not created as a child of the currently-running [Job], so the [Deferred] and the underlying [Future] are not cancelled when the currently-running [Job] is cancelled. If assuring the cancellation of the given stage is desired, `async { stage.await() }` should be used instead.

**Comment by qwwdfsad** [comment]
> If you make your Deferred with async { f.await() }, then you don't have that issue.

if `async` or its scope is cancelled before `f.await`, Future is leaked as well. 
The same problem from a different perspective.
Moreover, usually, underlying execution is never cancellation-aware, so calling `future.cancel` rarely has any effects, so it does not really matter.

So when you already have a Future, all bets are off. We can't discourage one pattern in favour of another when both of them are flawed by design of the Future itself.

**Comment by glasser** [comment]
While I'm not sure I entirely agree, it sounds like my change to the docs isn't a good idea so I will close this.
