### ISSUE TITLE
Update notification abstraction

### ISSUE THREAD

**Issue by elizarov** [Kotlin/kotlinx.coroutines#145]
A problem: a web app that mages a set of entities (here identified by some string id) and needs to update all the subscribed clients on the update of the corresponding entities in real-time.

`ConflatedBroadcastChannel<Unit>` can be used as "update-notification" abstraction, however it is quite a boilerplate to manage them. An example implementation:

```
// maps entity id to the update signal
val signals = ConcurrentHashMap<String, ConflatedBroadcastChannel<Unit>>()

fun signal(id: String) =
    signals[id]?.offer(Unit) // offer to anyone who's interested

fun track(id: String): ConflatedBroadcastChannel<Unit> =
    signals.computeIfAbsent(id) { ConflatedBroadcastChannel(Unit) }
```

Here, `signal` and `track` do work like an update notification mechanism, given that every consumer is written in the following pattern:

```
track(id).consumeEach { 
    // send a snapshot of an entity from the storage here
}
```

and updates are written like that:

```
// store updated entity here
signal(id)
```

The above code never removes ids that are not interested in from the `signals` map, though. We need some abstraction to encapsulate this kind of update-tracking logic together with ability to keep in memory only ids that some coroutine is interested in.

**Comment by qwwdfsad** [comment]
Superseded by flow abstractions
