### ISSUE TITLE
Android: await frame

### ISSUE THREAD

**Issue by ansman** [Kotlin/kotlinx.coroutines#1474]
It seems like #737 might have regressed, yielding on the immediate main dispatcher while on the main thread is currently a no-op as shown by this example:
```kotlin
        Log.d("Application", "Before")
        GlobalScope.launch(Dispatchers.Main.immediate) {
            Log.d("Application", "Before yield")
            yield()
            Log.d("Application", "After yield")
        }
        Log.d("Application", "After")
```

The example above is placed inside the `Application.onCreate` which is already running on the main thread.

The expected output would be:
```
Before
Before yield
After
After yield
```

But the actual output is:
```
Before
Before yield
After yield
After
```

**Comment by elizarov** [comment]
This is not a regression. It never worked this way after #737. The improvement that we did in #737 was to support yielding into the "unconfined" virtual event loop that is being created for things like `Dispatcher.Unconfined` and for immediate dispatchers when there are multiple "immediately dispatched" events are working. We do not currently support yielding to the "true dispatcher's event loop" from immediate dispatchers. I'll keep your issue open as an enhancement.

Can you, please, go into a little bit more detail of what is your use-cases? Why would you need to be able to use `yield()` like that?

**Comment by elizarov** [comment]
Frankly, I don't think that `yield` is appropriate for your case. Even if we implement it somehow, there will be zero guarantee that "rendering frame is finished". It looks like you you need some Android-specific suspending function `awaitRenderedFrame()` here. If you know how to implement it on android (what exactly are you waiting), then you are welcome to contribute it to the `kotlinx-coroutines-android` module.

**Comment by keyboardr** [comment]
This caught me when updating my `fragment-ktx` dependency. I had previously been doing something like this:

```
lifecycleScope.launch {
  while(conditionNotMet()) {
    yield()
  }
  doTheThingThatRequiresTheCondition()
}
```

`lifecycleScope`'s dispatcher switched from `Main` to `Main.immediate` (generally a good thing), but that meant my while loop caused it to ANR instead of making progress. It took me quite a while to realize that `yield()` wasn't doing what I expected.

**Comment by JakeWharton** [comment]
This change is breaking Retrofit's mitigation against exceptions that are thrown synchronously which relies on `yield()`.

**Comment by elizarov** [comment]
Uh. Oh. We'll see what we can do.

**Comment by ansman** [comment]
> This caught me when updating my `fragment-ktx` dependency. I had previously been doing something like this:
> 
> ```
> lifecycleScope.launch {
>   while(conditionNotMet()) {
>     yield()
>   }
>   doTheThingThatRequiresTheCondition()
> }
> ```
> 
> `lifecycleScope`'s dispatcher switched from `Main` to `Main.immediate` (generally a good thing), but that meant my while loop caused it to ANR instead of making progress. It took me quite a while to realize that `yield()` wasn't doing what I expected.

@keyboardr Be aware that this issue still exists if you yield inside a `whenResumed` block. This will be fixed when https://issuetracker.google.com/issues/168777346 is resolved (hopefully next lifecycle release).
