### ISSUE TITLE
"Inappropriate thread-blocking method call" inspection does not handle flowOn() declaration

### ISSUE THREAD

**Issue by severn-everett** [Kotlin/kotlinx.coroutines#1503]
This is a cross-posting of [KT-33532](https://youtrack.jetbrains.com/issue/KT-33532) - as the issue got no traction there, I figured that maybe it needs to be posted here due to it being related to the Coroutines library:

For the Kotlin Coroutine library, the `Inappropriate thread-blocking method call` code inspection for blocking code in a coroutine can be addressed by placing the blocking code in a `withContext(Dispatchers.IO) {}` call. Per the documentation for the new Flow functionality, switching between contexts is not allowed within a flow code block; instead, the IDE suggests that the context be specified via a `flowOn()` call tacked onto the end of the `flow {}` code block. However, the IDE is still flagging the blocking code as violating the proscribed standard workflow. The code inspector should be updated to reflect that `flowOn()` is used for Kotlin Flow to manage context for blocking code.

Found in: Kotlin 1.3.50, Kotlin-Coroutine 1.3.0

![runSingleCoroutine](https://user-images.githubusercontent.com/12528881/64251768-8be9d400-cf19-11e9-8f69-0d678bb69f17.png)
![runMultiCoroutine](https://user-images.githubusercontent.com/12528881/64251767-8be9d400-cf19-11e9-8363-ea35fcfb1da8.png)
![runFlow](https://user-images.githubusercontent.com/12528881/64251766-8b513d80-cf19-11e9-9b94-129566f00300.png)

**Comment by elizarov** [comment]
Thanks!

**Comment by qwwdfsad** [comment]
Please keep track of this issue under KT-33532, closing this one

**Comment by efemoney** [comment]
Not sure if I should create another issue on KT tracker but another case where IDEA also reports a warning on blocking calls in the scope is with the experimental coroutines api `fun CoroutineDispatcher.invoke` which is `inline` and directly calls `withContext(this@CoroutineDispatcher)` so should be fine.
