### ISSUE TITLE
assertNotNull(deferred) gets "Deferred result is never used" inspection

### ISSUE THREAD

**Issue by glasser** [Kotlin/kotlinx.coroutines#1517]
(Not sure if is supposed to go to some IntelliJ JIRA instead.)

The following code gets a "Deferred result is never used" inspection highlighting `assertNotNull`:

```
package foo

import kotlinx.coroutines.Deferred
import kotlinx.coroutines.GlobalScope
import kotlinx.coroutines.async
import kotlinx.coroutines.runBlocking
import kotlin.test.Test
import kotlin.test.assertEquals
import kotlin.test.assertNotNull

object DeferredTest {
	@Test fun t() = runBlocking {
		val d: Deferred<Int>? = GlobalScope.async { 42 }
		assertNotNull(d)
		assertEquals(42, d.await())
	}
}
```

I'm not sure why — because assertNotNull may throw and leak the Deferred? I'll note that replacing the test body with this roughly equivalent code does not have the inspection:

```
		val d: Deferred<Int>? = GlobalScope.async { 42 }
		assertEquals(42, d!!.await())
```

(In reality the code that returns `Deferred<V>?` is more complex, of course.)

This is IntelliJ 2019.2.1, kotlinx.coroutines 1.3.1, kotlin 1.3.50.

**Comment by elizarov** [comment]
It goes here: https://youtrack.jetbrains.com/issue/KT-33741
