### ISSUE TITLE
Dispatchers.Main vs Dispatchers.Main.immediate

### ISSUE THREAD

**Issue by yamasa** [Kotlin/kotlinx.coroutines#1522]
Recently, the AndroidX lifecycle library switched to using `Dispatchers.Main.immediate` instead of `Dispatchers.Main`.
https://developer.android.com/jetpack/androidx/releases/lifecycle#2.2.0-alpha04

On the other hand, the standard functions such as [MainScope](https://kotlin.github.io/kotlinx.coroutines/kotlinx-coroutines-core/kotlinx.coroutines/-main-scope.html) are still using `Dispatchers.Main` by default.

My question is which one should be used by default.
https://github.com/Kotlin/kotlinx.coroutines/blob/master/ui/coroutines-guide-ui.md#starting-coroutine-in-ui-event-handlers-without-dispatch
Although it is explained a little in the above document, I don't understand the disadvantages of `Dispatchers.Main.immediate` well.

**Comment by qwwdfsad** [comment]
`Dispatchers.Main.immediate` is a performance optimization that may change an order of execution as a result of the optimization. And to understand why it happens (or its implications), one should understand the concept of immediate/undispatched start/event-loops.

>My question is which one should be used by default.
...
>I don't understand the disadvantages of Dispatchers.Main.immediate well.

The main disadvantage is that it has slightly different behaviour. While it is generally safe (and sane), it's still a new concept one should bear in mind and understand. If you are a new user of `kotlinx.coroutines`, it's better to stick with `Dispatchers.Main`. If not and you understand what `immediate` dispatcher does then it's a matter of choice.

**Comment by yamasa** [comment]
> The main disadvantage is that it has slightly different behaviour. While it is generally safe (and sane), it's still a new concept one should bear in mind and understand.

Thanks, I get it.
We will be cautious to use `immediate` in our project.

**Comment by sdzshn3** [comment]
By default viewModelScope uses Dispatchers.Main.immediate

**Comment by jamesonwilliams** [comment]
> And to understand why it happens (or its implications), one should understand the concept of immediate/undispatched start/event-loops.

Well, I'm here for it, @qwwdfsad. Lay it on us. We're ready.
