### ISSUE TITLE
BroadcastChannel's consumeEach is still marked as obsolete…

### ISSUE THREAD

**Issue by LouisCAD** [Kotlin/kotlinx.coroutines#1528]
… and references now closed issue #254
A workaround is to add an `openSubscription()` call before to get a `ReceiveChannel`, which has it as experimental (not obsolete), but it's unclear if this method on `BroadcastChannel` is here to stay or not.

**Comment by qwwdfsad** [comment]
>it's unclear if this method on BroadcastChannel is here to stay or not.

That's why it is still marked as obsolete :)
We are still not sure whether `BroadcastChannel` is a good abstraction at all (because it's not really a channel and it behaves rather like `Flow`) and there is a possibility that it will be deprecated in the favor of potential #1082 solution
