### ISSUE TITLE
Broken generated code on Turkish PC

### ISSUE THREAD

**Issue by fthdgn** [Kotlin/kotlinx.coroutines#1529]
Hi,

We have a problem with applications compiled on Turkish PCs. While the compiled code run it throws the exception below.
`Exception in thread "main" java.lang.NoSuchMethodError: kotlin.coroutines.jvm.internal.Boxing.boxİnt(I)Ljava/lang/Integer;`

"boxİnt" contains "latin capital letter i with dot above" (U+0130).
Java String.toUpperCase() method with Turkish locale returns this char for input "latin small letter i" (U+0069).

Probably at some point compiler generates "boxİnt" string from "int" input and because of the usage of system default, it generates uppercase İ.

You can generate this error by running this project on a Turkish PC.
https://github.com/fthdgn/kotlin-coroutine-turkish-bug

**Comment by fthdgn** [comment]
Related closed issues #852  #817

**Comment by JakeWharton** [comment]
Seems like this should be reported to http://kotl.in/issue as it's a Kotlin compiler issue, not something related to this library.

**Comment by qwwdfsad** [comment]
Thanks for raising the issue.
This is indeed a compiler bug, filed https://youtrack.jetbrains.com/issue/KT-33821

**Comment by elizarov** [comment]
Please, subscribe to the compiler bug. I'm closing an issue here.
