### ISSUE TITLE
about netty actor

### ISSUE THREAD

**Issue by l42111996** [Kotlin/kotlinx.coroutines#155]
i use netty to recieve message and send it to actor'channel  ,if channel is full ,i wish to block netty thread,how to design it? use runBlocking ?

`class ActorThread {

    var actor: ActorJob<IHandler>
    var threadPool: CoroutineDispatcher

    constructor(threadPool: CoroutineDispatcher) {
        this.actor = actor(threadPool,1000){
            for(msg in channel){
                msg.run()
            }
        }
        this.threadPool = threadPool
    }

    fun put(handler:IHandler){
        //TODO 
        runBlocking(threadPool) {
            actor.send(handler)
        }
    }

    fun shutdown(){
        actor.close()
    }

}`

**Comment by elizarov** [comment]
Yes. Just do `runBlocking { actor.send(...) }`. It does exactly what you need -- blocks the thread when suspended.

**Comment by l42111996** [comment]
Is there a higher performance solution?

**Comment by l42111996** [comment]
Is there a higher performance solution?

**Comment by l42111996** [comment]
Is there a higher performance solution?
i use it in a game server, netty for network, one client one actor

**Comment by fvasco** [comment]
I have the same problem, I wrote the following extension (but I don't know the performance gain):

        fun <T> SendChannel<T>.sendBlocking(element: T) {
            // fast path
            if (offer(element))
                return
            // slow path
            runBlocking {
                send(element)
            }
        }

I think that this method should be integrated in the standard library.

**Comment by elizarov** [comment]
This `sendBlocking` is indeed a more efficient way to do that. It makes sense to have it in the standard library.

**Comment by l42111996** [comment]
i need run on my coroutineContext ,i think 

sendBlocking(element: E,context: CoroutineContext = EmptyCoroutineContext)

 is better

**Comment by elizarov** [comment]
What a `coroutineContext` parameter is supposed to do in `sendBlocking`?

**Comment by l42111996** [comment]
sorry ,i hava a wrong test ,EmptyCoroutineContext is enought ,In most cases the queue will not be full，thanks for your kindly reply
