### ISSUE TITLE
TestCoroutineContext is marked as deprecated

### ISSUE THREAD

**Issue by yorickhenning** [Kotlin/kotlinx.coroutines#1550]
[`TestCoroutineContext`](https://kotlin.github.io/kotlinx.coroutines/kotlinx-coroutines-core/kotlinx.coroutines.test/-test-coroutine-context/) is marked deprecated.

 #541 seems to have fixed the issue `TestCoroutineContext` was deprecated over.

Is this class still supported and useful?

**Comment by qwwdfsad** [comment]
#541 introduced `runBlockingTest` & co. instead in a separate `kotlinx-coroutines-test` module and this API will be developed and maintained.

`TestCoroutineContext` is obsolete and will be abandoned completely as soon as we merge #1206

**Comment by yorickhenning** [comment]
OK!

A documentation page on testing with Coroutines would be very helpful. There isn't much agreement on style and tooling.
