### ISSUE TITLE
Terrible performance

### ISSUE THREAD

**Issue by DanialLiu** [Kotlin/kotlinx.coroutines#1551]
I use kotlin 1.3.50 and coroutines 1.3.1 on android
this is my simple code
```
GlobalScope.launch{
            while(true){
                Log.i("tag", "default dispatchers")
                delay(1000)
            }
        }
```
CPU usage:
![kotlin-coroutine](https://user-images.githubusercontent.com/958496/65120665-8e235680-da20-11e9-970d-3284b1faee4e.png)

CPU usage will raise up to 30% every second

If I change delay(1000) to delay(10)
Every DefaultDispatch thread will cost more than 40% each CPU core
As the result of profile tool, most CPU waste in findTask
![kotlin-coroutine-performance](https://user-images.githubusercontent.com/958496/65121175-5bc62900-da21-11e9-8fa6-32f637a3f4a8.png)

Why the performance is so terrible?

**Comment by qwwdfsad** [comment]
It's a known issue #1046 which fix is targeted to 1.3.2.
Closing as duplicate
