### ISSUE TITLE
Have kotlinx-coroutines-guava depend on listenablefuture instead of guava artifact

### ISSUE THREAD

**Issue by dlew** [Kotlin/kotlinx.coroutines#1552]
At the moment, kotlinx-coroutines-guava only adds a coroutine implementation for `ListenableFuture`. However, it depends on the *entire* Guava library (com.google.guava:guava), rather than just the `ListenableFuture` part of it (com.google.guava:listenablefuture).

Would it be acceptable to switch it to depend only on the latter artifact, to avoid pulling in all of Guava for those who don't want to depend on it? (This is primarily an Android concern due to the size of the Guava library.)

**Comment by elizarov** [comment]
Yes. I've checked `com.google.guava:guava` dependencies and it looks like it should work out. PR is welcome.

**Comment by JakeWharton** [comment]
The implementation relies on things like `SettableFuture` which are in Guava proper. Or are you saying Guava should be `implementation` and the listenable future artifact should be `api`?

**Comment by dlew** [comment]
@JakeWharton Ack, you're right; I missed that completely.

Closing! I should've thought this through a bit more.
