### ISSUE TITLE
Integration with jdk7

### ISSUE THREAD

**Issue by dmytrodanylyk** [Kotlin/kotlinx.coroutines#156]
To use coroutines in Java we have following module "Integration with [JDK8 CompletableFuture](https://github.com/Kotlin/kotlinx.coroutines/blob/master/integration/kotlinx-coroutines-jdk8/README.md) (Android API level 24)".

What are our options for Android API level < 24? Are there any plans to _add kotlinx-coroutines-jdk7_ with regular [Future](https://docs.oracle.com/javase/7/docs/api/java/util/concurrent/Future.html)?

**Comment by fvasco** [comment]
Regular `Future` exposes blocking api only, you should look at `Deferred` interface or Guava library.

**Comment by dmytrodanylyk** [comment]
Imagine you are developing library, which expose `Deferred` or suspended functions. Asking Java clients to add `Guava` library is a bit "too much".

**Comment by fvasco** [comment]
I agree,
for this reason many asynchronous libraries implement own futures and Java 8 introduced the `CompletitionStage` interface.

Feel free to choose a better alternative.

**Comment by dmytrodanylyk** [comment]
> many asynchronous libraries implement own futures

If you have some great examples, would appreciate if you can share. 

My idea was to expose `Deferred` and then, client apps could use one of jet brains [integrations](https://github.com/Kotlin/kotlinx.coroutines/tree/master/integration).

**Comment by fvasco** [comment]
> If you have some great examples, would appreciate if you can share.

Netty, Vert.x

> My idea was to expose Deferred and then, client apps could use one of jet brains integrations

Try to write some client code to understand better the final result.
