### ISSUE TITLE
Insufficient Proguard configuration rules

### ISSUE THREAD

**Issue by christofferqa** [Kotlin/kotlinx.coroutines#1564]
If a field is never written, R8 will replace all reads of that field by the default value of the field. Therefore it is important that the Proguard configuration for kotlinx.coroutines correctly specifies which fields are written using reflection.

In https://issuetracker.google.com/issues/141416122, a small project is shared that breaks due to missing Proguard configuration rules in kotlinx.coroutines. I found that adding the following two keep rules to the project solves the issue.
```
-keep,allowobfuscation class kotlinx.coroutines.io.ByteBufferChannel { kotlin.coroutines.Continuation writeOp; }
-keep,allowobfuscation class kotlinx.io.pool.DefaultPool { long top; }
```

I then found that the Proguard configuration rules for kotlinx.coroutines contain the following rule (https://github.com/Kotlin/kotlinx.coroutines/blob/master/kotlinx-coroutines-core/jvm/resources/META-INF/proguard/coroutines.pro#L8):
```
-keepclassmembernames class kotlinx.** {
    volatile <fields>;
}
```

This should be updated to:
```
-keepclassmembers class kotlinx.** {
    volatile <fields>;
}
```

In addition to specifying that the names of these fields cannot be changed, this also specifies that these fields are assigned using reflection (in this case, AtomicReferenceFieldUpdater).

Originally filed at https://issuetracker.google.com/issues/141416122 and https://github.com/ktorio/ktor/issues/1354.

**Comment by cy6erGn0m** [comment]
According to the documentation

>-keepclassmembernames class_specification
    Short for-keepclassmembers,allowshrinkingclass_specification Specifies class members whose names are to be preserved, **if they aren't removed** in the shrinking phase. 

>-keepclassmembers [,modifier,...] class_specification
    Specifies class members to be preserved, if their classes are preserved as well. For example, you may want to keep all serialization fields and methods of classes that implement theSerializable interface.

Not sure we can replace `keepclassmembernames` with `keepclassmembers` because it's not enough to keep field, we need to keep names as well.

**Comment by christofferqa** [comment]
The `keepclassmembers` directive also preserves the name of the field.

**Comment by cy6erGn0m** [comment]
@christofferqa I don't see where it is documented

**Comment by christofferqa** [comment]
According to the documentation, `-keepclassmembernames` is an alias for `-keepclassmembers,allowshrinking`. Thus, the only difference between `-keepclassmembernames` and `-keepclassmembers` is that the latter rule does not allow matched fields to be removed.
