### ISSUE TITLE
Channel.receive with the filter predicate

### ISSUE THREAD

**Issue by khovanskiy** [Kotlin/kotlinx.coroutines#1569]
It will be nice to have the method to receive the first message from a channel, which matched by the given predicate. The other messages should stay in the channel until they received by other predicates.
This method can help to use channels like in message broker applications

**Comment by elizarov** [comment]
Unfortunately, it would be impossible to implement efficiently while also maintaining all the guarantees that channels have (linearizability, etc). Message broker application need to use their own domain-specific data structures.
