### ISSUE TITLE
What does '~is' mean?

### ISSUE THREAD

**Issue by erikhuizinga** [Kotlin/kotlinx.coroutines#1576]
Here

https://github.com/Kotlin/kotlinx.coroutines/blob/a70022d6e7d9aa5d8fe27a2c46e987a2e8b85c21/kotlinx-coroutines-core/common/src/flow/Channels.kt#L74

'~is' is used. Does this mean 'not is' or 'approx. is'/'more or less is'?

Please use natural language in the docs.

**Comment by qwwdfsad** [comment]
This is a mathematic notation for [equivalence](https://en.wikipedia.org/wiki/Equivalence_relation#Notation) . Informally, it's just "roughly it's the same as".

I will rephrase this doc, thanks for pointing it out

**Comment by erikhuizinga** [comment]
Thanks. By the way, '~' also can mean [logical negation](https://en.wikipedia.org/wiki/Negation#Notation) and that's how I interpreted it.
