### ISSUE TITLE
Update CoroutineScope docs to recommend explicit scope

### ISSUE THREAD

**Issue by elizarov** [Kotlin/kotlinx.coroutines#1581]
`CoroutineScope` documentation currently recommends the following code pattern:

```
class MyActivity : AppCompatActivity(), CoroutineScope by MainScope() {
    ...
}
```

It's time to update it to explict scope style, which seems to be winning in its clarity and popularity:

```
class MyActivity : AppCompatActivity() {
    private val scope = MainScope() 
    ...
}
```

**Comment by kpritam** [comment]
As per this guideline, can you please help me with the following example if any changes need to be done?
```
class Script : CoroutineScope {
    private val executor = Executors.newSingleThreadExecutor().asCoroutineDispatcher()
    private val job = Job()

    override val coroutineContext: CoroutineContext get() = job + executor
    
    // ....
}
```

**Comment by qwwdfsad** [comment]
@kpritam 
```
class Script : CoroutineScope {
    private val executor = ... // Separate variable to close it later
    private val scriptScope = CoroutineScope(executor)
}

```

**Comment by kpritam** [comment]
> @kpritam
> 
> ```
> class Script : CoroutineScope {
>     private val executor = ... // Separate variable to close it later
>     private val scriptScope = CoroutineScope(executor)
> }
> ```

Thanks @qwwdfsad , Just to confirm, do you mean like this?
```
class Script {
    private val executor = Executors.newSingleThreadExecutor().asCoroutineDispatcher()
    private val scriptScope = CoroutineScope(executor)
    init {
        scriptScope.launch { delay(1000) }
    }
}
```

**Comment by Wanchan9** [comment]
ทุกอย่างที่เกิดขึ้นจากการกระทำของทั้งหมด ผมยังไม่เข้าภาษาตัวต่อ ที่ผมเรียนได้ก็พวกคุณทั้งหมด ผมขอโอกาศ กับพวกเราทั้งได้ไหมคับหากว่าผมตัดสินใจไปแล้วผิดขอให้ทุกคนยกโทษให้ผมด้วยนะคับ

**Comment by guelo** [comment]
Not sure if this matter for the documentation, but in my team instead of doing something like this 
```kotlin
class Activity {
    private val mainScope = MainScope()
    
    fun destroy() {
        mainScope.cancel()
    }
}
```
we created a class that ties the lifecycles and scope together using a androidx.lifecycle observer.
```kotlin
class MainScope(lifecycleOwner: LifecycleOwner) : CoroutineScope, LifecycleObserver {

    init {
        lifecycleOwner.lifecycle.addObserver(this)
    }

    override val coroutineContext = SupervisorJob() + Dispatchers.Main

    @OnLifecycleEvent(Lifecycle.Event.ON_PAUSE)
    fun destroy() = coroutineContext.cancelChildren()
}
```

Then  don't have to worry about managing the scope cancellation in every activity
```kotlin
class Activity {
    private val mainScope = MainScope(this)
}
```

**Comment by zsmb13** [comment]
@guelo: this is actually provided in a first-party way, it's called `LifecycleScope`, and you can access it on any `LifecycleOwner` (Activity, Fragment, Fragment view owner): https://developer.android.com/topic/libraries/architecture/coroutines#lifecyclescope

**Comment by guelo** [comment]
Well now I feel stupid. I'm not sure how I missed that.
