### ISSUE TITLE
Paradoxically slow performance when launching coroutines in IO dispatcher

### ISSUE THREAD

**Issue by elizarov** [Kotlin/kotlinx.coroutines#1583]
The benchmark was inspired by this code: https://github.com/Heapy/kotlin-benchmarks/commit/6b446867886ec54341a180209840bf39c37e1d14 where it seems that the author got the paradoxial result that coroutines are slower, which I failed to replicated. 

However, when comparing different dispatchers it turns out that `Dispatchers.IO` is much slower at this kind of usage. See the resulting becnhmark code at https://github.com/Kotlin/kotlinx.coroutines/blob/dispathers-benchmark/benchmarks/src/jmh/kotlin/benchmarks/DispatchersContextSwitchBenchmark.kt which produces:

```
Benchmark                                                       Mode  Cnt    Score     Error  Units
DispatchersContextSwitchBenchmark.coroutinesBlockingDispatcher  avgt   10   37.172 ±   0.587  ms/op
DispatchersContextSwitchBenchmark.coroutinesDefaultDispatcher   avgt   10  149.659 ±   7.954  ms/op
DispatchersContextSwitchBenchmark.coroutinesIoDispatcher        avgt   10  522.634 ± 211.396  ms/op
DispatchersContextSwitchBenchmark.threads                       avgt   10  714.920 ±  19.840  ms/op
```

**Comment by qwwdfsad** [comment]
Fixed in 1.3.3
