### ISSUE TITLE
Integration with Scala Future

### ISSUE THREAD

**Issue by elizarov** [Kotlin/kotlinx.coroutines#159]
We would like to have an integration module for Scala `Future` class in a similar vein to Guava `ListenableFuture` integration. It can be made with cut-and-paste of guava integration module based on the contribution guidelines: https://github.com/Kotlin/kotlinx.coroutines/tree/master/integration#contributing

**Comment by DmitriyZaitsev** [comment]
grabbed

**Comment by qwwdfsad** [comment]
Unlikely to fix, unlikely to maintain all the scala versions :)
