### ISSUE TITLE
Wrong thread with `suspend main` (works with `runBlocking`)

### ISSUE THREAD

**Issue by Boza-s6** [Kotlin/kotlinx.coroutines#1591]
Following code has different behavior depending which main function is used:
```
import kotlinx.coroutines.*

fun main() {
    runBlocking {
            someSuspendFunction()
    }
}

//suspend fun main() {
//        someSuspendFunction()
//}

suspend fun someSuspendFunction() {
    printThread("[someSuspendFunction] before")
    val string = withContext(context = Dispatchers.Default) {
        printThread("[someSuspendFunction] In 'withcontext'")
        return@withContext "String"
    }
    printThread("[someSuspendFunction] after: $string")
}


fun printThread(s: String) {
    println(s.padEnd(50) + Thread.currentThread().toString())
}
```

*runBlocking* prints:
```
[someSuspendFunction] before                      Thread[main,5,main]
[someSuspendFunction] In 'withcontext'            Thread[DefaultDispatcher-worker-1,5,main]
[someSuspendFunction] after: String               Thread[main,5,main]
```

*suspend main* prints:
```
[someSuspendFunction] before                      Thread[main,5,main]
[someSuspendFunction] In 'withcontext'            Thread[DefaultDispatcher-worker-2,5,main]
[someSuspendFunction] after: String               Thread[DefaultDispatcher-worker-2,5,main]
```

As you can see thread after `withContext` is **wrong** in case `suspend main` is used.

**Comment by fvasco** [comment]
`suspend fun main` does not define any `Dispatcher`, so when the `Continuation` is resumed then it uses the current thread. There is not thread constraints.

`runBlocking` defines a `Dispatcher` on the main thread, instead.

**Comment by Boza-s6** [comment]
Why is there a difference?

It creates really unexpected behavior. I would *never* expect that thread changes between yield points.

**Comment by fvasco** [comment]
> I would never expect that thread changes between yield points.

You have to change this misconception.

In the [coroutine specification](https://github.com/Kotlin/KEEP/blob/master/proposals/coroutines.md#concurrency-and-threads)
> The running coroutine is always executed in some thread. However, a suspended coroutine does not consume a thread and it is not bound to a thread in any way. The suspending function that resumes this coroutine decides which thread the coroutine is resumed on by invoking Continuation.resumeWith on this thread and coroutine's interceptor can override this decision and dispatch the coroutine's execution onto a different thread.

Take a look to the coroutine guide: https://kotlinlang.org/docs/reference/coroutines/coroutine-context-and-dispatchers.html

**Comment by Boza-s6** [comment]
I thought that without *explicitly* switching threads coroutine stays on one thread. It's a little unfortunate that's not the case imo.

Does that mean that when I bridge some callback based API, I have to use dispatcher from coroutine context to call `resumeWith`?

Pseudo code:
```
suspendCoroutine { cont ->
  api.doSomething { res -> 
     disaptcher.post {cont.resumeWith(res) }
  }
}
```

**Comment by elizarov** [comment]
Thanks @fvasco for answers. I hope it helps.
