### ISSUE TITLE
How to distribute work among limited coroutines in a most efficient way?

### ISSUE THREAD

**Issue by circusmagnus** [Kotlin/kotlinx.coroutines#1594]
What would be a recommended / most efficient way to distribute work among limited pool of worker-coroutines?

1. Have a single "task" distributor Channel and a specified number of coroutines receiving from it.

2. Actor-style, specified number of channels, each with a single coroutine worker behind it. Use select expression to select first available worker for each "task".

3. Yet another way?

**Comment by elizarov** [comment]
The first option (a single channel with several coroutines) aka "worker pool" is the most natural one. See also #172
