### ISSUE TITLE
java.util.Stream.consumeAsFlow() operator

### ISSUE THREAD

**Issue by josephlbarnett** [Kotlin/kotlinx.coroutines#1601]
Given a `java.util.Stream`, it can be converted to a coroutine `Flow` in a way that ensures the stream is closed after the flow is finished (consumed or cancelled) like follows:
```
result.iterator().asFlow().onCompletion { result.close() }
```
or, alternatively:
```
flow {
    result.use {
        for (edge in it) {
            emit(edge)
        }
    }
}
```

Would be slightly more convenient to have a `Stream.consumeAsFlow()` implementation in the coroutines libraries that does so even less verbosely.

**Comment by qwwdfsad** [comment]
It could be nice addition to the jdk8 module.
But we cannot name it `asFlow` for the same reasons we don't have `ReceiveChannel.asFlow` (we have `consumeAsFlow` instead): resulting Flow can be used only once
