### ISSUE TITLE
Android UI delay does not work with Long.MAX_VALUE

### ISSUE THREAD

**Issue by elizarov** [Kotlin/kotlinx.coroutines#161]
Doing `delay(Long.MAX_VALUE)` on Android ends up invoking `Handler.postDelayed` which invokes the following code:

```
    public final boolean sendMessageDelayed(Message msg, long delayMillis) {
        if (delayMillis < 0) delayMillis = 0;
        return sendMessageAtTime(msg, SystemClock.uptimeMillis() + delayMillis);
    }
```

Note, how addition operation here overflows on `Long.MAX_VALUE` delay.

**Comment by JakeWharton** [comment]
Can you file on b.android.com/new? But why would you ever do this?

**Comment by elizarov** [comment]
Filed. I don't know why. It is just an edge case that better be working as expected (it shall effectively wait forever).
