### ISSUE TITLE
android with kotlin corutines , the unit test failure does not show in IDE if CoroutineExceptionHandler is attached

### ISSUE THREAD

**Issue by lannyf77** [Kotlin/kotlinx.coroutines#1612]
Having unit test which tests the data fetch result. But after switch to use coroutines, the unit test failure is not shown as before anymore.

In app's DataRequest.kt which will fetch the data list and post to liveData, it is done inside the coroutine's launch{}:

There is exceptionHandler for the coroutineScope:

    private val coroutineExceptionHandler = CoroutineExceptionHandler { _, exception ->
       
        Log.e(TAG, "!!! exception in coroutineExceptionHandler($exception)")
        exception.printStackTrace()
        ......
    }

And used in the launching the root coroutines job:

    @Throws(Exception::class)
    private fun launchCoroutine(block: suspend CoroutineScope.() -> Unit): Job = serviceScope.launch(context =    coroutineExceptionHandler, block = block)

    
The coroutines job start from calling:

    launchCoroutine {
        doDataFetch()
    }

doDataFetch() will fetch the data and when the data list is ready in the callback it calls the `onDataFetchedReady()` which does the post to the liveData in the `postDataList(list)`

    suspend fun onDataFetchedReady() = withContext(Dispatchers.IO) {
    
        ...
        launch {
            postDataList(list)
        }
    }

And in the unit test its liveData observer will get the liveData update and calling into the test function `verifyExpectedDataSize()` where it may detect failure:

    ListRequesterTest.kt

    @RunWith(AndroidJUnit4::class)
    fun verifyExpectedDataSize(
        originalList: List<Data>,
        resultList: List<Data>
    ): Int {

        ... ...

        assertTrue("the data size is wrong", (dataSize > 0 && resultList.size >= dataSize))

        ... ...
    }
 
In logCat it shows:

        E/DataRequest: !!! exception in coroutineExceptionHandler(java.lang.AssertionError: the data size is wrong)

    	Suppressed: java.lang.AssertionError: the data size is wrong
        at org.junit.Assert.fail(Assert.java:88)
        at org.junit.Assert.assertTrue(Assert.java:41)
        at com.xxx.ListRequesterTest$verifyExpectedDataSize(ListRequesterTest:200)
        at com.xxx.ListRequesterTest$LiveDataObserver.onChanged(ListRequesterTest.kt:64)

        at androidx.lifecycle.LiveData.considerNotify(LiveData.java:113)
        at androidx.lifecycle.LiveData.dispatchingValue(LiveData.java:131)
        at androidx.lifecycle.LiveData.setValue(LiveData.java:289)
        at androidx.lifecycle.MutableLiveData.setValue(MutableLiveData.java:33)
        at androidx.lifecycle.LiveData$1.run(LiveData.java:91)
        at androidx.arch.core.executor.testing.InstantTaskExecutorRule$1.postToMainThread(InstantTaskExecutorRule.java:43)
        at androidx.arch.core.executor.ArchTaskExecutor.postToMainThread(ArchTaskExecutor.java:101)
        at androidx.lifecycle.LiveData.postValue(LiveData.java:273)
        at androidx.lifecycle.MutableLiveData.postValue(MutableLiveData.java:28)

        at com.yyy.DataRequest.postDataList(DataRequest.kt:200)
        at com.yyy.DataRequest.access$postDataList(DataRequest.kt:39)
        at com.yyy.DataRequest$onDataReady$2$invokeSuspend$$inlined$synchronized$lambda$3.invokeSuspend(DataRequest.kt:508)
        at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:33)
        

In the test in IDE it shows the green check and no error with "Tests ran to completion".
But in logCat it shows the test has failed
```Suppressed: java.lang.AssertionError: the data size is wrong```

How to prevent the coroutines exception handler from swallowing the test failure?

**Comment by bohsen** [comment]
@lannyf77 If you rethrow the exception the test should fail I believe.

**Comment by lannyf77** [comment]
@bohsen, this is the workaround we do now
```
class MyTestException : Exception{}
```

in the test wrap the assert into one that throw `MyTestException`

```
fun MyTestAssertTrue (String message, boolean condition) {
    try {
        assertTrue(message, !condition)
    } catch (ex: Throwable) {
        throw(MyTestException(message)
    }
}
```

so the test will be calling `MyTestAssertTrue (message, condition)` instead of  `assertTrue(...)` directly.
and in the `coroutineExceptionHandler` do re-throw if the exception is `MyTestException`

```
val coroutineExceptionHandler = CoroutineExceptionHandler { _, exception ->
    Log.e(TAG, "!!! exception in coroutineExceptionHandler($exception)")
    exception.printStackTrace()
    ......
    if (exception is MyTestException) {
       throw (exception) . //<==== re-throw
    }
}
```
but the test result is
```
Test failed to run to completion. Reason: 'Instrumentation run failed due to 'Process crashed.''. Check device logcat for details
```
not like when it does without registering the `coroutineExceptionHandler` it prints out the call stack at the fail place.

**Comment by elizarov** [comment]
`CoroutineExceptionHandler` is not swallowing an exception, it just lets you handle it. The fact that your test does not crash on exception means that somewhere you are not using structured concurrency properly, e.g. you are launching coroutines without a parent job, thus there is no path to propagate exception to your test code. 

Can you share a code that actually starts a tests? Even better, can you create a small self-contained reproducer code that demonstrates your problem?

**Comment by lannyf77** [comment]
@elizarov the project is huge, I try to simplify here to show the related parts, hope it may show some issue. Thanks for the help!

Having a `DataRequester` which fetches data and post to its liveData.
`DataRequester`. start() will start the data fetching flow and return the livaeData for observing.
When data fetching is complete the `onFetchedDataReady()` is called to do the post to liveData.

and the testing part is just instantiate the `DataRequester` and start to observe the liveData, and test assert when the result comes in.

```

class DataRequester private constructor(
        ...
) : IDataRequester {

    private val serviceJob = Job()
    private val serviceScope = CoroutineScope(Dispatchers.IO + serviceJob)

    private val coroutineExceptionHandler = 
              CoroutineExceptionHandler { _, exception -> exception.printStackTrace()
    }
    @Throws(Exception::class)
    private fun launchCoroutine(block: suspend CoroutineScope.() -> Unit): Job = 
                         serviceScope.launch(context = coroutineExceptionHandler, block = block)

    private val fetchedLiveData = MutableLiveData<List<IData>>()
    ......

    override fun start(): IDataResponse {  //<== start the data fetching flow and 
                         //return the livaeData for observing
        ...
        launchCoroutine {
            doFetchData()
        }
        return FetchLiveData(fetchedLiveData, stateLiveData) //<== return the liveData
    }

    private suspend fun doFetchData() {
        coroutineScope {
            while (isActive && fetchers.size > 0) {
                val fetcher = fetchers.removeAt(0)
                        ...
                launch {
                    fetcher.getData()  //<== all called funstions inside are 
                          //either suspend fun (not  using different coroutine scope), or plain fun
                }
            }
        }
        onFetchedDataReady()  //<== all fetching complete and have 
                              //the theFetchedData then do post to liveData
    }

    private suspend fun onFetchedDataReady() = withContext(Dispatchers.IO) {
        synchronized(_lock) {
            ......
            launch {
                fetchedLiveData.postValue(theFetchedData)
            }
            ......
        }
    }
...
}
interface IDataResponse {
    fun getLiveData(): MutableLiveData<List<IData>>
    fun getStateLiveData(): MutableLiveData<State>
}

class FetchedLiveData(
        private val fetchedLiveData: MutableLiveData<List<IData>>,
        private val stateLiveData: MutableLiveData<State>
) : IDataResponse {
    override fun getLiveData(): MutableLiveData<List<IData>> {
        return fetchedLiveData
    }

    override fun getStateLiveData(): MutableLiveData<State> {
        return stateLiveData
    }
}

```

The test part, it calls DataRequester.start() to get the liveDat, observe it, and in the `liveDataOnChanged` to do the test.

when assert failed the DataRequester's coroutinesExceptionHandler is called and the test shows complete without reporting error.

```
class DataTest {
    ...
    private lateinit var requestor: IDataRequester
    ...

    inner class LiveDataObserver(...) : Observer<List<IData>> {
        override fun onChanged(it: List<IData>?) {
            liveDataOnChanged(it)
        }
    }
    /**
     * data fetcher flow test
     */
    fun startRequestSession(dataFetchers: ArrayList<IDataFetcher>) {

        requestor = DataRequester(......)
        val observableLiveData = requestor.start()

        liveDataObserver = LiveDataObserver()
        observableLiveData.observeForever(iveDataObserver)
                ...
    }

    fun liveDataOnChanged(it: List<IData>?) {  // is is in the DataRequest's fetch - post flow, which are in the corutines context scope

        assertTrue("... posted data size != expected data size, ${it?.size} != $n", it?.size == n)  
        //<== if the assert fail the CoroutineExceptionHandler exceptionhandler 
        //will catch the exception but swallowing it

                ...
    }
```

**Comment by bohsen** [comment]
> when assert failed the DataRequester's coroutinesExceptionHandler is called and the test shows complete without reporting error.

Isn't this due to the fact that you swallow the `AssertionError` and rethrow your `MyTestException` in your `MyTestAssertTrue` function? You haven't posted the test (a self-contained reproducer) so it's difficult to say. Your code is really difficult to reason about IMHO (I understand that this is a big project but still).

You should consider posting this to the kotlin coroutines slack channel to get input from the experts that hang out in there. And maybe try to have this simplified. You will probably get a lot more feedback there.
