### ISSUE TITLE
[FLOW] collect the latest emitted value after some time from the latest emission

### ISSUE THREAD

**Issue by manueldidonna** [Kotlin/kotlinx.coroutines#1613]
I'm not sure how to explain my usecase. I have a textfield that emits on each text change but I need to collect the latest value only when there aren't other emissions for 300ms

```kotlin
flow {
    emit(1) // this won't be collected because 2' is emitted after 40ms '
    delay(40)
    emit(2) // this won't be collected because '3' is emitted after 40ms 
    delay(40)
    emit(3) // this will be collected because it's the latest emitted value
}.specialOperatorWithoutAName(timeInMillis = 300)

// I only want `3` after 380 milliseconds 
```

I hope someone can help me

**Comment by joaotrota** [comment]
Isn't [sample](https://kotlin.github.io/kotlinx.coroutines/kotlinx-coroutines-core/kotlinx.coroutines.flow/sample.html) the operator you're looking for?

**Comment by bnorm** [comment]
Seems more like [debouce](https://kotlin.github.io/kotlinx.coroutines/kotlinx-coroutines-core/kotlinx.coroutines.flow/debounce.html) to me.

**Comment by michgauz** [comment]
In fact, I miss something like a sample but with the last value emitted

**Comment by houssemzaier** [comment]
if you want the latest element sent via flow you can also do thi:
`flow{..}.toList().last()
`

**Comment by amir1376** [comment]
I need the same thing
did you found something useful ?
