### ISSUE TITLE
can i use coroutines in Java

### ISSUE THREAD

**Issue by YYXWJ** [Kotlin/kotlinx.coroutines#1619]
like:
In Java file:
Callable callable = new Callalbe(){
private void run(){
    Thread.sleep(1000)
}
}

In kotlin：
launch{
        callable.run();
}

but it dose not work

**Comment by elizarov** [comment]
What exactly are you trying to achieve?

**Comment by YYXWJ** [comment]
i must be Java in my project ,but i want do long-running operations in kotlin ,but i can not add word ''suspend'' in Java, so coroutines can not have worked nonblocking pending。
my english is not well, If I don't express myself clearly enough，please tell me ，I'll get someone to help me organize the language. thank you

**Comment by YYXWJ** [comment]
for example:
public void readfile(File strFile){
    try{
            InputStream is = new FileInputStream(strFile);
            int iAvail = is.available();
            byte[] bytes = new byte[iAvail];
            is.read(bytes);
            logger.info("文件内容:\n" + new String(bytes));
            is.close();
        }catch(Exception e){
            e.printStackTrace();
        }
}
in kotlin:
launch{
    readfile(file)
}

but this function is not suspend ,

**Comment by fvasco** [comment]
Hi @YYXWJ
use Kotlin's coroutine is really tricky from Java.
Is it possible? Yes, it is.
Is it worth? I really think no.

I suggest you to use Kotlin's coroutine in Kotlin and `CompletableFuture` (or Guava, RxJava) integration in Java. These solutions works well togheter.

**Comment by YYXWJ** [comment]
> Hi @YYXWJ
> use Kotlin's coroutine is really tricky from Java.
> Is it possible? Yes, it is.
> Is it worth? I really think no.
> 
> I suggest you to use Kotlin's coroutine in Kotlin and `CompletableFuture` (or Guava, RxJava) integration in Java. These solutions works well togheter.

but coroutine can reduce thread quantity

**Comment by fvasco** [comment]
> but coroutine can reduce thread quantity

Yes, and no.

All the above technologies helps to reduce thread quantity.
Coroutine is a language feature, and it is not directly related to threads.

You can use coroutine to use asynchronous without write callback (`suspend` keyword does the trick).

Java does not support any kind of `suspend` keyword, so "yes", you can use the Kotlin's coroutine library in Java, and "no", you have to use it without any trick (handling **any** intrinsic by hand).

I suggest you to use an Java-friendly library already covered in the [official module list](https://github.com/Kotlin/kotlinx.coroutines#modules).

**Comment by qwwdfsad** [comment]
Thanks @fvasco  for answering this question
