### ISSUE TITLE
Support for Java 9 Flow API

### ISSUE THREAD

**Issue by fvasco** [Kotlin/kotlinx.coroutines#162]
Rename kotlinx-coroutines-reactive package to Java 9 package.

**Comment by elizarov** [comment]
Why rename? `kotlinx-coroutines-reactive` support Reactive Streams specification interfaces. It does not work with Java 8 `Flow.*` interfaces. We should define a new module for that. The only tricking part is how name it: either `kotlinx-coroutines-jdk9` or `kotlinx-coroutines-flow`.

**Comment by fvasco** [comment]
Hi @elizarov,
I said that badly, I am fully agree with you.

Both names are nice,
I consider a bit better to offer a complete jdk 9 integration as a single dependency, however this goal can be reached by putting `kotlinx-coroutines-flow` as dependency of `kotlinx-coroutines-jdk9`.

**Comment by elizarov** [comment]
What else there is to jdk 9 integration beyond `Flow.*` interfaces?

**Comment by fvasco** [comment]
Nothing,
so I prefer the name `kotlinx-coroutines-jdk9`.

Flow api should not look different from time api.

**Comment by qwwdfsad** [comment]
Fixed in 1.3.5
