### ISSUE TITLE
Couldn't inline method call 'collect' [Android]

### ISSUE THREAD

**Issue by dragneelfps** [Kotlin/kotlinx.coroutines#1637]
Getting the below error when trying to use flow on Android:

```
Caused by: org.jetbrains.kotlin.codegen.CompilationException: Back-end (JVM) Internal error: Couldn't inline method call 'collect' into
public suspend inline fun <T> kotlinx.coroutines.flow.Flow<T>.collect(crossinline action: suspend (T) -> kotlin.Unit, `$completion`: kotlin.coroutines.Continuation<kotlin.Unit>): kotlin.Any? defined in kotlinx.coroutines.flow
```

Using `org.jetbrains.kotlinx:kotlinx-coroutines-android:1.3.2`

**Comment by dragneelfps** [comment]
So it seems that enabling Jetpack Compose caused the error. The project builds after **removing** the following line:
```
buildFeatures {
    compose true
}
````

**Comment by elizarov** [comment]
Yes. Compose is using a experimental compiler version that does not fully support coroutines yet.

**Comment by dragneelfps** [comment]
Thanks for the info. I hope we are able to use compose with coroutines or kapt soon.
