### ISSUE TITLE
GlobalScope.launch中repeat

### ISSUE THREAD

**Issue by GuoXuanPif** [Kotlin/kotlinx.coroutines#1641]
![image](https://user-images.githubusercontent.com/36481960/68016295-3dfe0c00-fccf-11e9-8c60-ec10c1ee5357.png)
为什么我运行出来是
0——999的?
网站运行的又只是0-2

**Comment by GuoXuanPif** [comment]
http://www.kotlincn.net/docs/reference/coroutines/basics.html#%E5%85%A8%E5%B1%80%E5%8D%8F%E7%A8%8B%E5%83%8F%E5%AE%88%E6%8A%A4%E7%BA%BF%E7%A8%8B
这个网站的

**Comment by qwwdfsad** [comment]
Please use English to report issues and ask questions in this repository or refer to local resources similar to Stackoverflow
