### ISSUE TITLE
`delay` leads to crash from worker because of DefaultDelay 

### ISSUE THREAD

**Issue by e5l** [Kotlin/kotlinx.coroutines#1645]
```
Uncaught Kotlin exception: kotlin.native.IncorrectDereferenceException: Trying to access top level value not marked as @ThreadLocal or @SharedImmutable from non-main thread
```

Please consider marking `DefaultDelay` with `@SharedImmutable`
https://github.com/Kotlin/kotlinx.coroutines/blob/a70022d6e7d9aa5d8fe27a2c46e987a2e8b85c21/kotlinx-coroutines-core/native/src/CoroutineContext.kt#L29

**Comment by elizarov** [comment]
This would be fixed as a part of multi-threaded coroutines support.

**Comment by qwwdfsad** [comment]
Fixed in `native-mt` branch
