### ISSUE TITLE
Support of ApacheHttpClient?

### ISSUE THREAD

**Issue by IRus** [Kotlin/kotlinx.coroutines#165]
Is it make sense to add support of ApacheHttpClient's `execute` method(as described [here](https://ruslan.ibragimov.by/2017/06/08/how-to-use-apache-asynchttpclient-with-kotlin-coroutines/)) to integrations?

**Comment by elizarov** [comment]
We are building client http library based on AppacheHttpClient as a part of ktor.io project. See https://github.com/ktorio/ktor/tree/master/ktor-client It is currently work in progress.

**Comment by IRus** [comment]
Okay, so people who like to use coroutines with apache http async client have to use ktor-client.
