### ISSUE TITLE
[Flow] add flatMapFirst (exhaustMap) operator

### ISSUE THREAD

**Issue by hoc081098** [Kotlin/kotlinx.coroutines#1656]
Please add flatMapFirst (exhaustMap) operator for Flow, like this [exhaustMap-rxjs](https://rxjs-dev.firebaseapp.com/api/operators/exhaustMap), flatMapFirst in RxSwift.
![](https://rxjs-dev.firebaseapp.com/assets/images/marble-diagrams/exhaustMap.png)

**Comment by qwwdfsad** [comment]
Could you please elaborate a bit on your particular use-case?
I realize what this operator does, but it is a bit unclear to me what exact domain-specific problem it solves

**Comment by floschu** [comment]
One use-case I could think of would be an interval + a refreshChannel, that get combined into a `Flow` that then maps to a long running suspending task:

``` kotlin
val refreshChannel: BroadCastChannel<Unit>
val intervalFlow: Flow<Unit> // emits every x TimeUnit

flowOf(intervalFlow, refreshChannel.asFlow()).flattenMerge()
    .exhaustMap { anOperationThatTakesSomeTime() }
    .launchIn(someScope)
```
The idea is to not run multiple `anOperationThatTakesSomeTime()` in parallel.

I think however that this could be achieved with the following operators if I am not mistaken:

``` kotlin
flowOf(intervalFlow, refreshChannel.asFlow()).flattenMerge()
    .conflate()
    .map { anOperationThatTakesSomeTime() }
    .launchIn(someScope)
```

**Comment by elizarov** [comment]
@floschu Yes, use can use `conflate().map { ... }` or `mapLatest`:
* `conflate().map { ... }` would wait for a long operation to finish before starting a new one.
* `mapLatest { ... }` would cancen an ongoing operation and restart it.

@hoc081098 Are there any other use-case that are not covered?

**Comment by elizarov** [comment]
Closing for the absence of non-covered use-cases.

**Comment by hoc081098** [comment]
Thanks for the help, I found workaround solution:
```kotlin
@ExperimentalCoroutinesApi
fun <T, R> Flow<T>.flatMapFirst(transform: suspend (value: T) -> Flow<R>): Flow<R> =
    map(transform).flattenFirst()

@ExperimentalCoroutinesApi
fun <T> Flow<Flow<T>>.flattenFirst(): Flow<T> = channelFlow {
  val outerScope = this
  val busy = AtomicBoolean(false)
  collect { inner ->
    if (busy.compareAndSet(false, true)) {
      launch {
        try {
          inner.collect { outerScope.send(it) }
          busy.set(false)
        } catch (e: CancellationException) {
          // cancel outer scope on cancellation exception, too
          outerScope.cancel(e)
        }
      }
    }
  }
}
```

**Comment by fabioCollini** [comment]
> @floschu Yes, use can use `conflate().map { ... }` or `mapLatest`:
> 
> * `conflate().map { ... }` would wait for a long operation to finish before starting a new one.
> * `mapLatest { ... }` would cancel an ongoing operation and restart it.
> 
> @hoc081098 Are there any other use-case that are not covered?

@elizarov I think there is a case that is not covered, something similar to `mapLatest` that ignores new operations instead of canceling the ongoing one. I am not sure if it's possible to achieve it using other operators, however the implementation provided by @hoc081098 in the previous comment works great

**Comment by elizarov** [comment]
> @fabioCollini I think there is a case that is not covered, something similar to `mapLatest` that ignores new operations instead of canceling the ongoing one.

That is what `conflate().map { ... }` combo does.

**Comment by fabioCollini** [comment]
@elizarov I think `conflate` is similar but slightly different. Here's an example:
```kotlin
suspend fun main() {
    val start = System.currentTimeMillis()
    fun log(s: String) = println("[${System.currentTimeMillis() - start}] $s")
    suspend fun longTask(it: Int) = try {
        log("start $it")
        delay(1000)
        log("end $it")
        it
    } catch (e: CancellationException) {
        log("cancelled $it")
        throw e
    }

    flowOf(1, 2, 3, 4, 5)
        .onEach {
            delay(300)
            log("Emitted $it")
        }
        .conflate()
        .onEach { longTask(it) }
        .collect { log("collect $it") }
}
```
This code prints:
```
[387] Emitted 1
[391] start 1
[696] Emitted 2
[999] Emitted 3
[1302] Emitted 4
[1393] end 1
[1393] collect 1
[1393] start 4
[1606] Emitted 5
[2397] end 4
[2397] collect 4
[2397] start 5
[3401] end 5
[3401] collect 5
```

`2`, `3` and `4` are emitted while `1` was running so, thanks to `conflate`, only `4` is executed at the end of `1`. Same for `5` that is emitted while `4` is running and so it's executed at the end.

Instead using the `flatMapFirst` defined in the previous comment:
```kotlin
    flowOf(1, 2, 3, 4, 5)
        .onEach {
            delay(300)
            log("Emitted $it")
        }
        .flatMapFirst {
            flow {
                emit(longTask(it))
            }
        }
        .collect { log("collect $it") }
```
This is the result:
```
[383] Emitted 1
[390] start 1
[690] Emitted 2
[995] Emitted 3
[1297] Emitted 4
[1395] end 1
[1406] collect 1
[1601] Emitted 5
[1603] start 5
[2603] end 5
[2603] collect 5
```
`2`, `3` and `4` are emitted while `1` is running so are just ignored. `5` is emitted after `1` ended so it's executed normally.
