### ISSUE TITLE
Thread use in suspendCoroutine

### ISSUE THREAD

**Issue by xwh3238557** [Kotlin/kotlinx.coroutines#1662]
When i use a thread in suspendCoroutine, like this:
```<kotlin>
GlobalScope.launch(CoroutineExceptionHandler { _, throwable -> 
            println("In")
        }) {
            suspendCoroutine<Int>  { c ->
                c.resume(1)
                thread {
                    c.resume(2) //this line will throw a exception 
                }
            }
        }
```
The exception handler will not work. When the exception throws, it seems like the thread's defaultExceptionHandler do the handle things instead of CoroutineExceptionHandler.

I know it is strange to use Thread in co-routine but suspendCoroutine is usually used in call back style functions Which sometimes wrtie in Third-party libs, we can not re-write. 

So it designed like this? or it is just a bug?

**Comment by elizarov** [comment]
It is so by design. The exception is throws inside `thread { ... }` block and thus handled by the thread's uncaught exception handler.
