### ISSUE TITLE
"Inappropriate thread-blocking method call" does not handle custom dispatcher

### ISSUE THREAD

**Issue by Tolriq** [Kotlin/kotlinx.coroutines#1664]
Crossposting https://youtrack.jetbrains.com/issue/KT-34931 as maybe the check is from coroutines code or the annotation I should use is provided by it.

```
suspend fun apiCall() {
  val result = withContext(ServiceLocator.backgroundDispatcher) { blockingcall }
} 
```

Is there a way to indicate that it's OK to call blocking methods in that specific dispatcher instead of adding tons of @Suppress("BlockingMethodInNonBlockingContext") ?

**Comment by elizarov** [comment]
Please, don't cross-post. The inspection is a part of Kotlin plugin.
