### ISSUE TITLE
Is this act expected or not for [SupervisorJob/CoroutineScope]?

### ISSUE THREAD

**Issue by liyzay** [Kotlin/kotlinx.coroutines#1665]
Here is the code:
```
suspend fun CoroutineScope.withScopeException(){
    return with(this) {
        coroutineException()
    }
}

suspend fun CoroutineScope.coroutineException(){
    println("context:$coroutineContext")
    var delay = 600L
    // launch the first child
    val firstChild = async {
        println("context:$coroutineContext")
        delay(delay)
        if(delay>=500L){
            println("First child is failing")
            throw AssertionError("First child is cancelled")
        }
    }
    // launch the second child
    val secondChild = async {
        println("context:$coroutineContext")
        try {
            println("Second child is running")
            delay(1000L*3)
        } catch (e:Throwable){
            println("Second child catch throwable:${e.message}")
            throw e
        } finally {
            println("Second child is cancelled:${coroutineContext[Job]?.isCancelled}")
        }
    }
    // wait until the first child fails & completes
    try {
        firstChild.await()
    } catch (e: Throwable) {
        println("Catch first throwable:${e.message}")
    }
    try {
        secondChild.await()
    } catch (e: Throwable) {
        println("Catch second throwable:${e.message}")
    }
}

//this will cause App to crash,why?
fun launchScopeException(){
    val scope = CoroutineScope(SupervisorJob()+Dispatchers.Main)
    scope.launch {
        //here is the difference
        withScopeException()
    }
}

//this works normally
fun launchWithScopeException(){
    val scope = CoroutineScope(SupervisorJob()+Dispatchers.Main)
    scope.launch {
        //here is the difference
        scope.withScopeException()
    }
}
```
The SupervisorJob is supposed to keep parent Job not effected by its children,is`t it?

**Comment by liyzay** [comment]
Here is the log for **launchScopeException**:
> 11-20 02:12:22.867 28492-28492/dev.*.extapp I/System.out: context:[StandaloneCoroutine{Active}@1f8f43c8, Main]
11-20 02:12:22.867 28492-28492/dev.*.extapp I/System.out: context:[DeferredCoroutine{Active}@b56fc61, Main]
11-20 02:12:22.867 28492-28492/dev.*.extapp I/System.out: context:[DeferredCoroutine{Active}@28f53386, Main]
11-20 02:12:22.867 28492-28492/dev.*.extapp I/System.out: Second child is running
11-20 02:12:23.467 28492-28492/dev.*.extapp I/System.out: First child is failing
11-20 02:12:23.487 28492-28492/dev.*.extapp I/System.out: Second child catch throwable:Parent job is Cancelling
11-20 02:12:23.487 28492-28492/dev.*.extapp I/System.out: Second child is cancelled:true
11-20 02:12:23.497 28492-28492/dev.*.extapp I/System.out: Catch first throwable:First child is cancelled
11-20 02:12:23.497 28492-28492/dev.*.extapp I/System.out: Catch second throwable:Parent job is Cancelling

Here is the log for **launchWithScopeException**:

> 11-20 02:11:37.557 28492-28492/dev.*.extapp I/System.out: context:[SupervisorJobImpl{Active}@2f510a4f, Main]
11-20 02:11:37.577 28492-28492/dev.*.extapp I/System.out: context:[DeferredCoroutine{Active}@1ebfa5dc, Main]
11-20 02:11:37.577 28492-28492/dev.*.extapp I/System.out: context:[DeferredCoroutine{Active}@204ad6e5, Main]
11-20 02:11:37.577 28492-28492/dev.*.extapp I/System.out: Second child is running
11-20 02:11:38.187 28492-28492/dev.*.extapp I/System.out: First child is failing
11-20 02:11:38.197 28492-28492/dev.*.extapp I/System.out: Catch first throwable:First child is cancelled
11-20 02:11:40.587 28492-28492/dev.*.extapp I/System.out: Second child is cancelled:false

**Comment by qwwdfsad** [comment]
Because an exception is reported to different scopes.

In the first case (`launchScopeException`) exceptions from children (two `async` jobs) are aggregated in the parent (top-level `launch`) that, by default, report it to exception handler (=> crashes your app).

In the second case, children are related to supervisor job and attempt to report their exceptions to it. But (as stated in `SupervisorJob` documentation), children of supervisor should handle their exception by themselves and `async` handler is a no-op (as it's expected that someone else will handle it when calling `await`)

**Comment by liyzay** [comment]
@qwwdfsad thank you very much,I get it now.
