### ISSUE TITLE
Kotlin 1.3.60 support for native part

### ISSUE THREAD

**Issue by IgorKey** [Kotlin/kotlinx.coroutines#1666]
Is there release date for kotlin 1.3.60 supporting? This issue related to K/N ABI compatibility

**Comment by elizarov** [comment]
Yes. Stay tuned. It will be released.

**Comment by soywiz** [comment]
New targets are not published (only the eap version):
* https://jcenter.bintray.com/org/jetbrains/kotlinx/kotlinx-coroutines-core-tvosarm64/
* https://jcenter.bintray.com/org/jetbrains/kotlinx/kotlinx-coroutines-core-watchosarm64/

**Comment by elizarov** [comment]
New targets will come with the new release on `kotlinx.coroutines`.
