### ISSUE TITLE
FlowCollector<T>.withContext() is depreciated with Error level

### ISSUE THREAD

**Issue by Malachiasz** [Kotlin/kotlinx.coroutines#1677]
Kotlin 1.3.2, I try to use withContext inside of flow{}, but it's Depreciated wit level Error. It says to use flowOn instead - an @ExperimentalCoroutinesApi. Go figure. How can you basically remove functionality when you don't have a stable replacement yet?

Migration.kt
`@Deprecated(message = "withContext in flow body is deprecated, use flowOn instead", level = DeprecationLevel.ERROR)
public fun <T, R> FlowCollector<T>.withContext(context: CoroutineContext, block: suspend () -> R): Unit = noImpl()`

**Comment by qwwdfsad** [comment]
>How can you basically remove functionality when you don't have a stable replacement yet?

It is not "removed" functionality. `withContext(anything) { emit(...) }` is not supposed to work and produces runtime exception. This deprecation just escalates this error from runtime to compile time.

This declaration is removed anyway (#1616, the rationale is explained in my comment to KT-34318) in 1.3.3 to enable usages like
```
flow {
    val value = withContext(...) { computeValue() }
    emit(value)
}
```

**Comment by Malachiasz** [comment]
Thank you for answer, but I find this way of handling API users not nice.

You discovered problems with some API. Instead of fixing it without braking API or simply Depreciating given method and solving problem with a new one, you broke the original method `= noImpl()` without providing stable new solution.

**Comment by qwwdfsad** [comment]
The original method is not broken, `withContext` is still here and works properly.
Deprecated `withContext` is an **extension function on FlowCollector**. Thus it is only selected when you are using it from withing `flow {}` block directly.

So even now you can workround it by simply extracting `withContext` into a separate method:
```
fun computeValueWithContext(): T = withContext(...) { computeValue() }

flow {
    val value = computeValueWithContext()
    emit(value)
}
```

**Comment by Malachiasz** [comment]
Except that API from user point of view is the extension function. Good to know, that there are workarounds.
