### ISSUE TITLE
Performance question about actor messages

### ISSUE THREAD

**Issue by psteiger** [Kotlin/kotlinx.coroutines#1681]
Hi

The traditional way of messaging an actor is:

1. sending a `sealed class` as the message,
2. calling a specific method defined inside the actor depending on the `sealed class` message

Is there any performance overhead, or any drawback at all, in sending a lambda function as the message itself of the actor, instead of a `sealed class` message, and then just invoking the lambda in the actor's `for` loop?

**Comment by elizarov** [comment]
It should not be much different, but if really care about performance then I'd suggest to setup a benchmark to measure your specific use-cases.
