### ISSUE TITLE
JDK_16 error

### ISSUE THREAD

**Issue by IgorGanapolsky** [Kotlin/kotlinx.coroutines#1684]
Hello,
I am not able to run any code nor unit tests in this repo.  IntelliJ constantly gives this error:
> Build file '/Users/igorganapolsky/workspace/git/kotiln/kotlinx-coroutines-core/build.gradle' line: 61
Execution failed for task ':kotlinx-coroutines-core:checkJdk16'.
> JDK_16 environment variable is not defined. Can't build against JDK 1.6 runtime and run JDK 1.6 compatibility tests. Please ensure JDK 1.6 is installed and that JDK_16 points to it.

**Comment by qwwdfsad** [comment]
Have you tried to define `JDK_16` environment variable as [documentation suggests](https://github.com/Kotlin/kotlinx.coroutines#building)?

**Comment by IgorGanapolsky** [comment]
Why is JDK_16 required for coroutines?

**Comment by qwwdfsad** [comment]
Because `kotlinx.coroutines` is compatible with Java 6 (Android 14 I suppose) and we ensure that by running tests with JDK 6

**Comment by imanushin** [comment]
@IgorGanapolsky , see also #1589 for coroutines + JDK6.

**Comment by IgorGanapolsky** [comment]
So it sounds like JDK6 requirement will be dropped in the near future :)

**Comment by MilkBiscuit** [comment]
I still can see this issue.

Can not run 'exampleBasic09' until I comment below code in build.gradle


```
        if (!System.env.JDK_16) {
            throw new GradleException("JDK_16 environment variable is not defined. " +
                    "Can't build against JDK 1.6 runtime and run JDK 1.6 compatibility tests. " +
                    "Please ensure JDK 1.6 is installed and that JDK_16 points to it.")
        }
```

I don't understand why you are still keeping this code.

**Comment by elizarov** [comment]
We have to ensure that we don't accidentally build it against a later version of JDK 1.6 and accidentally use classes not present in JDK 1.6. As spelled out in contribution guide, you can simply set `JDK_16` to `JAVA_HOME`.

**Comment by mcpiroman** [comment]
I've heard kotlin 1.5 no longer supports java 1.6 (and 1.7). Should it be dropped here, too?

**Comment by qwwdfsad** [comment]
Than

**Comment by qwwdfsad** [comment]
Thanks, that's worth taking care of to simplify the life of external contributors.
It's a big bigger than just removing it from Gradle, because it requires some changes in our TC infrastructure as well

**Comment by qwwdfsad** [comment]
Fixed in current develop
