### ISSUE TITLE
user coroutines for mingw or macos

### ISSUE THREAD

**Issue by ApplePeels** [Kotlin/kotlinx.coroutines#1687]
is there anyone know how can i user coroutines in mingw or macos?

this is my sample:
```
runBlocking {
        GlobalScope.apply {
            launch(Dispatchers.Default) {
                delay(1000L) // non-blocking delay for 1 second (default time unit is ms)
                println("World!") // print after delay
            }
            println("Hello,")
        }
}
```

and then throw exception:
`kotlin.IllegalStateException: There is no event loop. Use runBlocking { ... } to start one.`

when i replace Dispatchers.Default to Dispatchers.Unconfined then throw
`Uncaught Kotlin exception: kotlin.IllegalStateException: Cannot execute task because event loop was shut down`

anyone else could help me??

kotlin_version=1.3.60
kotlinx_coroutines_version=1.3.2-1.3.60

**Comment by elizarov** [comment]
The code you are trying to run is not currently supported, but will be supported in the future. See #462 for details.
