### ISSUE TITLE
Kotlin: Unresolved reference: runBlockingTest

### ISSUE THREAD

**Issue by PedroD** [Kotlin/kotlinx.coroutines#1688]
I am getting this error in the sample project you can find here:

https://github.com/OpenAPITools/openapi-generator/tree/master/samples/server/petstore/kotlin-springboot-reactive

Here's how it looks when I open it with iJ and try to run it without any modification:

![imagem](https://user-images.githubusercontent.com/3803097/70250076-3f5ea080-1775-11ea-88f1-c461faef2c8c.png)

**Comment by qwwdfsad** [comment]
`runBlockingTest` requires `kotlinx-coroutines-test` dependency

**Comment by PedroD** [comment]
But this is how the example comes, so this is a bug?

**Comment by qwwdfsad** [comment]
`runBlockingTest` was added in 1.2.1, but the project depends on 1.2.0.
Please upgrade the version (it's better to upgrade straight to 1.3.2) in order to fix the problem

**Comment by PedroD** [comment]
Shouldn't this be fixed in a new release?

**Comment by qwwdfsad** [comment]
In a new release of what?

**Comment by AlexSuvorov2k** [comment]
Still error.
Add a testImplementation 'org.jetbrains.kotlinx:kotlinx-coroutines-test:1.7.2' is not helped

**Comment by dkhalanskyjb** [comment]
You should take a look at the more modern `runTest` instead: https://kotlinlang.org/api/kotlinx.coroutines/kotlinx-coroutines-test/kotlinx.coroutines.test/run-test.html
