### ISSUE TITLE
Native build out of date?

### ISSUE THREAD

**Issue by nanodeath** [Kotlin/kotlinx.coroutines#1690]
I'm getting this error when running the compileKotlinLinux task:

```
w: skipping /mnt/Data/.gradle/caches/modules-2/files-2.1/org.jetbrains.kotlinx/kotlinx-coroutines-core-linuxx64/1.3.2/d264b5de14d0b152f9054bd1f1dce719b224de77/kotlinx-coroutines-core.klib. The abi versions don't match. Expected '[17]', found '14'
w: The compiler versions don't match either. Expected '[]', found '1.3.50-release-11850'
e: Could not find "/mnt/Data/.gradle/caches/modules-2/files-2.1/org.jetbrains.kotlinx/kotlinx-coroutines-core-linuxx64/1.3.2/d264b5de14d0b152f9054bd1f1dce719b224de77/kotlinx-coroutines-core.klib" in [/home/.../Projects/json-beam-2, /home/.../.konan/klib, /home/.../.konan/kotlin-native-linux-1.3.61/klib/common, /home/.../.konan/kotlin-native-linux-1.3.61/klib/platform/linux_x64].
```

> 1.3.50

However the version of Kotlin and the Kotlin Multiplatform plugin I'm running is 1.3.61. This is with coroutines 1.3.2.

Do I need to downgrade to 1.3.50?

**Comment by nanodeath** [comment]
Neither downgrading Kotlin nor the coroutines version seems to help. build.gradle looks like this:

```groovy
kotlin {
    // snip
    linuxX64("linux")
    sourceSets {
        commonMain {
            dependencies {
                implementation kotlin('stdlib-common')
                implementation "org.jetbrains.kotlinx:kotlinx-serialization-runtime-common:$serialization_version"
                implementation "org.jetbrains.kotlinx:kotlinx-coroutines-core-common:$coroutines_version"
            }
        }
        commonTest {
            dependencies {
                implementation kotlin('test-common')
                implementation kotlin('test-annotations-common')
            }
        }
        // snip
        linuxMain {
            dependencies {
                implementation "org.jetbrains.kotlinx:kotlinx-serialization-runtime-native:$serialization_version"
                implementation "org.jetbrains.kotlinx:kotlinx-coroutines-core-native:$coroutines_version"
            }
        }
        linuxTest {
        }
    }
}

jvmTest.useJUnitPlatform()
```

**Comment by nanodeath** [comment]
I also sometimes get this error as a bubble:

>There are 2 libraries attached to the project that were compiled with an older Kotlin/Native compiler and can't be read in IDE: "atomicfu.klib" at /mnt/Data/.gradle/caches/modules-2/files-2.1/org.jetbrains.kotlinx/atomicfu-linux64/0.13.0/4922cefb7da8998ddc11535c5c9e038d82de58f1/atomicfu.klib "kotlinx-coroutines-core.klib" at /mnt/Data/.gradle/caches/modules-2/files-2.1/org.jetbrains.kotlinx/kotlinx-coroutines-core-linuxx64/1.3.2/d264b5de14d0b152f9054bd1f1dce719b224de77/kotlinx-coroutines-core.klib  Please edit Gradle buildfile(s) to use Kotlin Gradle plugin version 1.3.61. Then rebuild the project and re-import it in IDE.

**Comment by Tolriq** [comment]
You need to use a temporary coroutine version: ```1.3.2-1.3.60```

**Comment by nanodeath** [comment]
:1st_place_medal: thanks, that did the trick! Didn't help that some of my common tests seem not to ever terminate on the native target, but that's another issue.

To anyone else who comes across this, you'll also need `maven { url "https://kotlin.bintray.com/kotlinx" }` in your `repositories` block because it's not released on MavenCentral.
