### ISSUE TITLE
Dispatchers.IO doesn't clean interruption when reusing a thread

### ISSUE THREAD

**Issue by qwwdfsad** [Kotlin/kotlinx.coroutines#1691]
Originally reported: https://youtrack.jetbrains.com/issue/KT-35283

**Comment by marcbowes** [comment]
According to the issue report this is "already fixed". Could you provide a link to the commit/s that fixed the problem? I'm just curious.

**Comment by qwwdfsad** [comment]
https://github.com/Kotlin/kotlinx.coroutines/pull/1652, https://github.com/Kotlin/kotlinx.coroutines/commit/2fd02cdf8816464df06f80f8df7e006cf3799e39 in particular

**Comment by marcbowes** [comment]
Thanks.
