### ISSUE TITLE
Function returning Deferred with a name that does not end with async

### ISSUE THREAD

**Issue by akingyin1987** [Kotlin/kotlinx.coroutines#1692]
Function returning Deferred with a name that does not end with async

**Comment by elizarov** [comment]
What's the issue?

**Comment by harshmittal29** [comment]
Any update on this warning. I am also getting this 
<img width="481" alt="Screenshot 2021-11-29 at 5 01 59 PM" src="https://user-images.githubusercontent.com/12228878/143838149-aaaaa206-716b-435e-899c-02f170fecf26.png">

**Comment by fvasco** [comment]
What's the issue?

**Comment by forceporquillo** [comment]
> Any update on this warning. I am also getting this <img alt="Screenshot 2021-11-29 at 5 01 59 PM" width="481" src="https://user-images.githubusercontent.com/12228878/143838149-aaaaa206-716b-435e-899c-02f170fecf26.png">

Still facing this issue
