### ISSUE TITLE
Add .asFlow() extensions for ObservableValue to kotlinx-coroutines-javafx library

### ISSUE THREAD

**Issue by qwwdfsad** [Kotlin/kotlinx.coroutines#1695]
>It would be nice if all observable properties could be easily converted to Flow when coding with TornadoFX. This could be added either for `javafx.beans.value.ObservableValue` or (maybe even better) for the entire `javafx.beans.Observable` interface if possible.

Originally reported here: https://youtrack.jetbrains.com/issue/KT-35389

**Comment by LittleLightCz** [comment]
Thank you, I am watching like a hawk :eagle: :relaxed:
