### ISSUE TITLE
spring datajpatest with kotlin coroutine

### ISSUE THREAD

**Issue by itavq** [Kotlin/kotlinx.coroutines#1702]
Hello,

The issue I'm dealing with might be wider then coroutines, but I'd give it a try here:
it seems that spring datajpatest is losing it's repositories state when I'm using coroutines.

Consider that test: 
```
import kotlinx.coroutines.*
import org.junit.jupiter.api.Test
import org.junit.jupiter.api.extension.ExtendWith
import org.springframework.beans.factory.annotation.Autowired
import org.springframework.boot.test.autoconfigure.orm.jpa.DataJpaTest
import org.springframework.data.jpa.repository.JpaRepository
import org.springframework.test.context.ContextConfiguration
import org.springframework.test.context.junit.jupiter.SpringExtension
import javax.persistence.*

@ExtendWith(SpringExtension::class)
@ContextConfiguration(classes = [SpringTestConfig::class])
@DataJpaTest
class BadRepoTest(@Autowired val testedRepository: TestRepository) {
    @Test
    fun testRepo() {

        testedRepository.saveAndFlush(TestEntity())

        println("count at start: ${testedRepository.count()} and $testedRepository")
        runBlocking {
            runCodeAsync().await()
        }
        println("count post async code: ${testedRepository.count()} and $testedRepository")
    }

    fun runCodeAsync(): Deferred<Unit> {
        return GlobalScope.async {
            println("count in async code: ${testedRepository.count()} and $testedRepository")
        }
    }
}

interface TestRepository : JpaRepository<TestEntity, Int>

@Entity
@Table(name = "test")
data class TestEntity(
    @Id @GeneratedValue(strategy = GenerationType.IDENTITY) val id: Int? = null
)
```

which yields the output:

> count at the start: 1 and SimpleJpaRepository@40d04cf8
> count in async code: 0 and SimpleJpaRepository@40d04cf8
> count post async code: 1 and SimpleJpaRepository@40d04cf8
 
In non-test scenario (where repositories are persistent mySql) it's obviously not the case.
Any idea how can I force the implementation to share the same memory repo state?

**Comment by elizarov** [comment]
It looks that this is somehow related to the fact that JPA is using a thread-local cache somewhere. @sdeleuze How do you deal with that in Reactive Spring? Let's discuss what can we do to bring the corresponding thread-locals to coroutine context.

**Comment by sdeleuze** [comment]
Hi, this is not really a use case we support officially, but for JPA on WebFlux we usually invoke `mono.subscribeOn(Schedulers.elastic())`, see related documentation [here](https://projectreactor.io/docs/core/release/api/reactor/core/scheduler/Schedulers.html#elastic--). Not sure if it is different from what Coroutines does here or not.

What we recommend is not to mix Reactive and blocking IO world, and to leverage [R2DBC](https://spring.io/projects/spring-data-r2dbc) and its Coroutines native support instead of JPA.

**Comment by Rfank2021** [comment]
@elizarov I also met the problem, but I think it's a transaction isolation problem. I printed `TransactionSynchronizationManager.isActualTransactionActive()` in main thread and coroutine, it shows main thread is in a transaction(@DataJpaTest will start a transaction) but coroutine not.

**Comment by koenpunt** [comment]
> What we recommend is not to mix Reactive and blocking IO world, and to leverage [R2DBC](https://spring.io/projects/spring-data-r2dbc) and its Coroutines native support instead of JPA.

What about a transition period? I'm working on an application that uses JPA heavily, and now we're migrating to R2DBC, one repo at the time. Is there a way to "safely" call a JPA repo method from a suspend fun? Would `runBlocking` be appropriate for this?
