### ISSUE TITLE
"Inappropriate thread-blocking method call" reported on java.nio.channels

### ISSUE THREAD

**Issue by Mygod** [Kotlin/kotlinx.coroutines#1707]
It seems like now it just reports everything that throws `IOException`. Some false positives that I see:

1. `DatagramChannel.open`;
2. `AbstractSelectableChannel.configureBlocking`;
3. Once `configureBlocking(false)` is called, subsequent calls should not raise blocking warnings, like `DatagramChannel.send`;
4. `DatagramSocket.bind` probably is not blocking?
5. `org.xbill.DNS.Message` constructor;
6. `SocketChannel.open`.

Related code: https://github.com/shadowsocks/shadowsocks-android/blob/63448896f4bf01b40b21439a386b7d68f5fdd3c2/core/src/main/java/com/github/shadowsocks/net/LocalDnsServer.kt

**Comment by glasser** [comment]
It even reports this for `suspend` functions which throw IOException or a subclass! (I commented this on https://youtrack.jetbrains.com/issue/IDEA-209249 )

**Comment by Mygod** [comment]
So it sounds like this is a check that I should disable.

**Comment by qwwdfsad** [comment]
Please keep track of this issue in linked IDEA ticket

**Comment by Mygod** [comment]
The linked IDEA ticket is entirely different from my report though.

**Comment by elizarov** [comment]
You are welcome create a separate IDEA to cover your use-case.
