### ISSUE TITLE
kotlin-gradle-plugin version with build.gradle version

### ISSUE THREAD

**Issue by aitazhixin** [Kotlin/kotlinx.coroutines#1709]
kotlin-gradle-plugin has been updated to 1.3.61, build.gradle:version updated to 3.5.3. But kotlin.stdlib.jdk8:1.3.50 can not be download. kotlin-coroutines-core:1.3.33 can not be found.

**Comment by qwwdfsad** [comment]
`kotlin-coroutines-core:1.3.33` there is no such version, the latest one is `kotlin-coroutines-core:1.3.3`.
Also, it would help if you will provide more details, for example, a reproducing project
