### ISSUE TITLE
Regression: Job.invokeOnCompletion not called on cancellation in 1.3.3

### ISSUE THREAD

**Issue by LouisCAD** [Kotlin/kotlinx.coroutines#1714]
Here's a standalone reproducing snippet that you can try on 1.3.2 and 1.3.3:

```kotlin
import kotlinx.coroutines.*

runBlocking {
    val loginScope = CoroutineScope(Job())
    val firstJob = loginScope.launch {
        println("Start first job")
        delay(1000)
        println("First job done!")
    }
    firstJob.invokeOnCompletion {
        // Bug: Never called on kotlinx.coroutines 1.3.3
        println("Job completed")
    }
    delay(100) // Let job start
    loginScope.cancel(cause = null) // Cancel job early
    println("Cancelled? " + firstJob.isCancelled)
    delay(1000) // Wait for callback?
}
```

**Comment by qwwdfsad** [comment]
Thanks for the self-contained repro! Though on my machine it never reproduces and successfully prints 
```
Start first job
Cancelled? true
Job completed
```
every time. 

Could you please provide a bit more details? E.g. a more concrete setup, whether this is a "pure" main function or something else is being executed in default dispatcher etc.
Does it reproduce after a clean build?

**Comment by LouisCAD** [comment]
I'm seeing it reproduce when run on play.kotl.in, using `suspend fun main() { … }` in place of `runBlocking { … }`. Can you reproduce it now?

**Comment by qwwdfsad** [comment]
Unfortunately, it still doesn't reproduce. And `play.kotl.in` still uses 1.3.2

**Comment by LouisCAD** [comment]
My bad. The last `delay(1000)` actually waits long enough to have the CompletionHandler invoked. 

If you remove it, you'll see it never be called as the program exits, but then, it behaves the same on 1.3.2 and 1.3.3.

Sorry for the false alarm.
