### ISSUE TITLE
Channel typealias 

### ISSUE THREAD

**Issue by avdyushin** [Kotlin/kotlinx.coroutines#1718]
I'd like to have a typealias for channel like this:

```
import kotlinx.coroutines.channels.Channel
typealias MyChannel = Channel<Int>
val channel = MyChannel()
```

But it says: `Expression 'MyChannel' of type 'Channel.Factory' cannot be invoked as a function. The function 'invoke()' is not found`

**Comment by qwwdfsad** [comment]
It is because `Channel<Int>()` is not a constructor call, but a [factory function call](https://kotlin.github.io/kotlinx.coroutines/kotlinx-coroutines-core/kotlinx.coroutines.channels/-channel.html).
You can define your own in the same manner: `fun MyChannel(): MyChannel = Channel<Int>()`

**Comment by avdyushin** [comment]
Ah I see, thanks for details. So here is how to make the same behaviour:

```
import kotlinx.coroutines.channels.Channel
typealias MyChannel = Channel<Int>
@Suppress("FunctionName")
fun MyChannel(capacity: Int = RENDEZVOUS): MyChannel = Channel(capacity)
```
And usage:
```
val b = MyChannel(10)
fun funcA(channel: MyChannel) { }
```
