### ISSUE TITLE
Flow for RSocket

### ISSUE THREAD

**Issue by whyoleg** [Kotlin/kotlinx.coroutines#1721]
Question about best practices for using [rsocket](http://rsocket.io) and flow
Some time ago I've started conversion of rsocket-java to rsocket-kotlin-mpp here [whyoleg/rsocket](https://github.com/whyoleg/rsocket). And from that time, I have an opened question in my mind about the best solution/architecture for one thing.
RSocket is built with Reactive Streams semantics in mind. The question is about [REQUEST_N](http://rsocket.io/docs/Protocol#flow-control).
If to look on my interface of RSocket, specifically on [requestStream](https://github.com/whyoleg/rsocket/blob/multiplatform/core/src/main/kotlin/io/rsocket/RSocket.kt#L52), it has such signature: 
```kotlin
fun requestStream(payload: Payload): Flow<Payload>
```
It's look OK. Then, I need f.e. to buffer by 10, or get results chunked by 10, in current implementation it will send to server/client REQUEST_N payload with value 1 for each new data, we will want to get.
So, if to use `buffer(10)`, on collect of flow it need to send 10 requests with REQUEST_N 1 to buffer data, and then 1 request for each new element
If to use `chunked(10)`, it will send 10 requests on collect, and after 10 elements collected, send once more 10 request, and so on
But, it will be really waste of resources. So, from my side, I think I need some new abstraction over flow, where I will have possibility to handle such cases without overhead.
Flow has very good design, but it's tightly coupled to communication inside one application. In such cases, there is something missing for such things.
And I think, it's not only needed for rsocket, but also for some other protocols or just simple client/server streaming.
With such long prelude: What can flow propose for such situations?
If compare this use-case for flow and f.e. reactor - there is no out of the box solution. Of course I can create my own wrapper over flow to handle it (and I will do it), but may be something like this can be added to library, as Flow is now such cool?

**Comment by elizarov** [comment]
You don't need a new abstraction over flow. There are two perfectly fine solutions:

* Make "request size" over the network a an option property of your network communication channel/engine and pick some reasonable default (larger than 1).  IMO, this is the best thing to do, as these kind of controls (just like TCP buffer size, etc) usually and naturally belong to the network configuration of your code, as should not pollute the rest of your code.

* You can also additionally integrate your networking flow implementation with `buffer(n)` operator on flows to override the default setting on case-by-case basis if needed. Currently, API to do that is not public, but we can expose it somehow if it is really needed.

**Comment by whyoleg** [comment]
Big thx for the answer!
I thought about you first proposal. But I think, that it will be better if such things will work per request. So f.e. we have 2 requests, one for entities, getting which will be very slow or even just not needed (through some external services, ads, recommendations), and second for entities which we get directly from DB and it's ok to request more of them at one time. So in such case, for 1 request, 5-10 buffer/chunk is normal, but for second - 50-100.
So, I will look more inside internal implementations of ChannelFlow-s and other things, and check, if it's possible to use them for such interactions.
