### ISSUE TITLE
Promote suspendAtomicCancellableCoroutineReusable

### ISSUE THREAD

**Issue by cy6erGn0m** [Kotlin/kotlinx.coroutines#1724]
Please promote `suspendAtomicCancellableCoroutineReusable` from module-internal to opt-in annotated internal API so it could be used in tight loops in ktor and I/O related stuff with no error suppressions and no risk of binary incompatibility.

**Comment by qwwdfsad** [comment]
Probably won't do it for a long time. Our investigation with memory leaks has shown that this primitive is a time-bomb.

E.g., the following issues should be addressed:
    * Invoking `cancel()` on a reusable insatnce
    * Handling exceptions thrown from the `block` (hint: mutating`getResult()` is not called)
    * Semantics of `invokeOnCancellation`
