### ISSUE TITLE
Wrong flow behavior - take with toList 

### ISSUE THREAD

**Issue by Nocri** [Kotlin/kotlinx.coroutines#1725]
Issue also posted on SO in case it's connected with LiveData but I guess it's more a Kotlin issue:
https://stackoverflow.com/questions/59408008/kotlin-takeint-tolist-omits-first-element

I have a test LiveData that emits items every 2 seconds. I convert it to flow and call take(3).toList() on it.

```
val list = newLiveData
            .asFlow()
            .onEach {
                println("Item ${it.status}")
            }
           .take(3)
           .toList()

println(list.joinToString {  "${it.status} " })
```

The implementation of that liveData makes it emit LOADING at first, then keep emitting SUCCESS, so I was expecting to see in the list:

`LOADING, SUCCESS, SUCCESS`

But for some reason it returns just

```
Item LOADING
Item SUCCESS
Item SUCCESS
SUCCESS , SUCCESS , SUCCESS 
```

What's weird, it prints correct values in onEach and if I replace "take(3)" with "first()" I do indeed get the correct LOADING status.

**Comment by qwwdfsad** [comment]
What type does `newLiveData` emits?
Are you sure it is not mutable?

You can easily check it e.g. using `.asFlow().map { it.status }.onEach { ... }.take(3).toList()`.
Self-contained reproducer would be helpful as well

**Comment by Nocri** [comment]
Yes, it is mutable and reusable for emissions. 
It's emitting StateData and changing it's state after every emission. 

Here is the sample (sorry, couldn't make it pure Kotlin for some reason, it wouldn't find LiveData in lifecycle package :/ ):
https://github.com/Nocri/LiveData_flow_issue

And I'll send sourcecode below for sake of issue history-making

**Comment by Nocri** [comment]
### StateData

```
class StateData<T> {

    @NonNull
    var status: DataStatus
        private set
    @Nullable
    var data: T?
        private set
    @Nullable
    var error: Throwable?
        private set

    init {
        status = DataStatus.CREATED
        data = null
        error = null
    }

    fun loading(): StateData<T> {
        status = DataStatus.LOADING
        data = null
        error = null
        return this
    }

    fun success(@NonNull data: T): StateData<T> {
        status = DataStatus.SUCCESS
        this.data = data
        error = null
        return this
    }

    fun error(@NonNull error: Throwable?): StateData<T> {
        status = DataStatus.ERROR
        data = null
        this.error = error
        return this
    }

    fun complete(): StateData<T> {
        status = DataStatus.COMPLETE
        return this
    }

    enum class DataStatus {
        CREATED, SUCCESS, ERROR, LOADING, COMPLETE
    }

    override fun toString(): String {
        return status.toString() + super.toString()
    }
}
```

### EmittingLiveData

```
class EmittingLiveData : LiveData<StateData<Int>>() {

    init {
        value = StateData()
    }

    override fun observe(owner: LifecycleOwner, observer: Observer<in StateData<Int>>) {
        startEmitting()
        super.observe(owner, observer)
    }

    override fun observeForever(observer: Observer<in StateData<Int>>) {
        startEmitting()
        super.observeForever(observer)
    }

    private fun startEmitting() {
        GlobalScope.launch(Dispatchers.Unconfined) {
            value = value?.loading()

            async {
                while (this.isActive) {
                    delay(1000)
                    postValue(value?.success(0))    //Might need set value
                }
            }.start()
        }
    }

}
```

### Test

```
class LiveDataFlowTest {

    @get:Rule
    val rule = InstantTaskExecutorRule()

    @Test
    @ExperimentalCoroutinesApi
    fun flowEmissionIsCorrect() = runBlocking {
        val dispatcher = TestCoroutineDispatcher()
        Dispatchers.setMain(dispatcher)

        val list = EmittingLiveData().asFlow().onEach { println(it.status) }.take(3).toList()

        assert(
            list.map { it.status } == listOf(
                StateData.DataStatus.LOADING,
                StateData.DataStatus.SUCCESS,
                StateData.DataStatus.SUCCESS
            )
        )
    }
}
```

**Comment by qwwdfsad** [comment]
>It's emitting StateData and changing it's state after every emission.

Well, that's the problem. In the end, you have a list with 3 elements, that refer to the same object that you are mutating. 
Either you shouldn't store references to such objects at all (=> doing defensive copy, in the same thread) or just emit new values each time
