### ISSUE TITLE
Android: CoroutineExceptionHandlerImpl ClassCastException with R8 1.6.53 and AGP 3.6RC01

### ISSUE THREAD

**Issue by Tolriq** [Kotlin/kotlinx.coroutines#1729]
Since updating Coroutines to 1.3.3 coroutine exception handler crash with a classcast exception and hide the real underlying issues:

```
java.lang.ClassCastException: 
  at k4.a.b0.a (CoroutineExceptionHandlerImpl.kt:1)
  at g4.z.s0.a (ViewGroupUtilsApi14.java:821)
  at k4.a.t0.a (DispatchedTask.kt:3)
  at k4.a.t0.run (DispatchedTask.kt:28)
  at k4.a.v2.c.a (CoroutineScheduler.kt:42)
  at k4.a.v2.a.run (CoroutineScheduler.kt:15)
```

I have sent the mapping and APK to R8 team, but since I've also updated AGP to 3.6 RC1 the rules applied are a little different too as it now properly apply https://github.com/Kotlin/kotlinx.coroutines/blob/master/ui/kotlinx-coroutines-android/resources/META-INF/com.android.tools/r8-from-1.6.0/coroutines.pro and no more https://github.com/Kotlin/kotlinx.coroutines/blob/master/ui/kotlinx-coroutines-android/resources/META-INF/com.android.tools/r8-upto-1.6.0/coroutines.pro

So pinging @wojtek-kalicinski / @qwwdfsad to see if maybe it's a side effect of the missing ```-keep class kotlinx.coroutines.android.AndroidDispatcherFactory {*;}``` ?

Can provide generated bytecode of anything if needed.

(Retrace show that the crash occurs at https://github.com/Kotlin/kotlinx.coroutines/blob/master/kotlinx-coroutines-core/jvm/src/CoroutineExceptionHandlerImpl.kt#L27)

**Comment by qwwdfsad** [comment]
Sorry for coming late to the party, AFAIR this was a bug in R8 that should've been fixed.

Closing as obsolete
