### ISSUE TITLE
Converting android.os.Handler calls to use coroutines

### ISSUE THREAD

**Issue by athuls** [Kotlin/kotlinx.coroutines#1739]
I am new to Kotlin and want to port some existing Android applications (such as video player, navigation app, etc.) to Kotlin and use coroutines for handling their async tasks (e.g. network calls, video rendering, onClick). Is there a systematic way to convert all the async tasks which currently use say, android.os.Handler threads, to use coroutines without breaking functionality/minimal code changes? This is a generic question but any guidance to move forward will be helpful!

**Comment by elizarov** [comment]
You are welcome to study guidelines on Android use with coroutines. I'm not sure there's any generic porting, since it very much depends on the style your application is written with.
