### ISSUE TITLE
IO operation withTimeout

### ISSUE THREAD

**Issue by pauliusrum** [Kotlin/kotlinx.coroutines#1740]
Kotlin: 1.3.61
Coroutines: 1.3.3

A:
```kotlin
    withTimeout(1_000) {
        GlobalScope.async(Dispatchers.IO) {
            Thread.sleep(10_000);
        }.await()
    }
```

B:
```kotlin
    withTimeout(1_000) {
        withContext(Dispatchers.IO) {
            Thread.sleep(10_000);
        }
    }
```

The IDE suggest that I replace A code snippet with B. But if I replace the code as the IDE suggests then timeout only happens after 10 seconds instead of 1 second.

**Comment by xizzhu** [comment]
Cancellation is cooperative:

> if a coroutine is working in a computation and does not check for cancellation, then it cannot be cancelled

`Thread.sleep()` doesn't check cancellation.

More details [here](https://kotlinlang.org/docs/reference/coroutines/cancellation-and-timeouts.html#cancellation-is-cooperative).

**Comment by pauliusrum** [comment]
Yes, but the IDE suggests to replace it with a solution that works differently.

**Comment by qwwdfsad** [comment]
This is a pre-coroutine scope IDE diagnostic, though it is still useful for the newcomers.

When one writes `async {}.await()` it **usually** means that they want to switch the context of the execution, not to launch a background coroutine and await it in a cancellable way. Thus it suggests to replace it with a more corresponding `withContext` call
