### ISSUE TITLE
example-cancel-02.kt: The sample code is incorrect.

### ISSUE THREAD

**Issue by LeoAndo** [Kotlin/kotlinx.coroutines#1741]
@qwwdfsad @elizarov @Inego

The sample code is incorrect.
https://github.com/kotlin/kotlinx.coroutines/blob/master/kotlinx-coroutines-core/jvm/test/guide/example-cancel-02.kt#L11
https://github.com/kotlin/kotlinx.coroutines/blob/master/kotlinx-coroutines-core/jvm/test/guide/example-cancel-02.kt#L17

``` currentTimeMillis() ``` ==> ``` System.currentTimeMillis() ```

### document
https://kotlinlang.org/docs/reference/coroutines/cancellation-and-timeouts.html#cancellation-is-cooperative

**Comment by elizarov** [comment]
In fact, it is correct. We use our own `currentTimeMillis()` on purpose here, so that example can do a double-duty as tests.
