### ISSUE TITLE
How do I use a specific thread as the thread that runs the coroutine?

### ISSUE THREAD

**Issue by Black-tail** [Kotlin/kotlinx.coroutines#1744]
For example, when I use the OpenGL drawing program in an Android project, the drawing thread of the OpenGL is not the Main thread. In this case, Dispatchers.Main is not applicable. How do I launch a coroutine on the OpenGL drawing thread? As far as I know, Dispatchers.unconfig is not applicable to this case either.

**Comment by fvasco** [comment]
You need a proper [CoroutineDispatcher](https://kotlin.github.io/kotlinx.coroutines/kotlinx-coroutines-core/kotlinx.coroutines/-coroutine-dispatcher/index.html).

I don't know if one already exists, but implementing a new one is pretty easy, you should define the [dispatch](https://kotlin.github.io/kotlinx.coroutines/kotlinx-coroutines-core/kotlinx.coroutines/-coroutine-dispatcher/dispatch.html) method only.

**Comment by qwwdfsad** [comment]
Indeed, you just have to define your own `CoroutineDispatcher`.
If you already have a `java.util.concurrent.Executor` for your OpenGL environment, you can convert it to the dispatcher via [asCoroutineDispatcher](https://kotlin.github.io/kotlinx.coroutines/kotlinx-coroutines-core/kotlinx.coroutines/java.util.concurrent.-executor/index.html)

**Comment by feresr** [comment]
I'm also interested in this, can someone point to an example? I'm using GLSufraceView (Android) do I need to build my own OpenGL context with EGL instead?

**Comment by xloger** [comment]
A OpenGL CoroutineDispatcher like this:
```kotlin
class GlCoroutineDispatcher: CoroutineDispatcher() {

    companion object {
        val Instances = GlCoroutineDispatcher()
    }

    private var dispatcher: ((Runnable) -> Unit)? = null

    override fun dispatch(context: CoroutineContext, block: Runnable) {
        val useDispatcher = dispatcher
        if (useDispatcher != null) {
            useDispatcher.invoke(block)
        } else {
            Log.e("GlCoroutineDispatcher", "GlCoroutineDispatcher.dispatcher is null.Maybe you need call `Dispatchers.GL.init(binding.glTextureView)`")
            block.run()
        }
    }

    fun init(glTextureView: GLTextureView) {
        dispatcher = {
            glTextureView.queueEvent(it)
        }
    }

    fun release() {
        dispatcher = null
    }
}

val Dispatchers.GL: GlCoroutineDispatcher
    get() = GlCoroutineDispatcher.Instances
```
Initialize only need to bind the GLTextureView when onCreate：
```kotlin
Dispatchers.GL.init(binding.glTextureView)
```
If you not use GLTextureView，just rewrite dispatcher by  `glThread.queueEvent(r)`.

call like this:
```kotlin
withContext(Dispatchers.GL) {
    GLES20.glClearColor(0f, 0f, 0f, 0f)
    //do something
}
```

**Comment by fvasco** [comment]
@gmazzo `context.isActive` looks harmful to me, it can prevent releases of resources.
`block` should run unconditionally and you use `ensureActive()` in your code.

**Comment by gmazzo** [comment]
> [@gmazzo](https://github.com/gmazzo) `context.isActive` looks harmful to me, it can prevent releases of resources. `block` should run unconditionally and you use `ensureActive()` in your code.

Good catch 💪 , I missed that, thanks! So, now, this is the implementation I'm using:

```kotlin
@ActivityScoped
class GLDispatcher @Inject constructor(
    private val view: GLSurfaceView,
) : CoroutineDispatcher() {

    override fun dispatch(context: CoroutineContext, block: Runnable) = view.queueEvent {
        context.ensureActive()
        block.run()
    }

}
```

**Comment by gmazzo** [comment]
Actually I just read fully the doc of `distch` and
> This method should guarantee that the given block will be eventually invoked, otherwise the system may reach a deadlock state and never leave it. The cancellation mechanism is transparent for CoroutineDispatcher and is managed by block internals.

What I don't get why my code wasn't canceled after the GL thread was destroyed 🤔 . I think I'll keep researching it. Thanks!

I may go back to the original one:
```kotlin
class GLDispatcher @Inject constructor(
    private val view: GLSurfaceView,
) : CoroutineDispatcher() {

    override fun dispatch(context: CoroutineContext, block: Runnable) {
        view.queueEvent(block)
    }

}
```

Or try your previous example.

**Comment by dkhalanskyjb** [comment]
Simply scheduling an event is the way to go. `kotlinx.coroutines` provides the "prompt cancellation guarantee" (please see https://kotlinlang.org/api/kotlinx.coroutines/kotlinx-coroutines-core/kotlinx.coroutines/suspend-cancellable-coroutine.html) to ensure that coroutines resume with a `CancellationException` in cancelled contexts. If the context truly got cancelled and the code is normal `kotlinx.coroutines` usage, then either we have a bug somewhere, or your code contains something like
```kotlin
try {
  delay(100) // or some other suspend operation
} finally {
  // will run even if the context is cancelled
  doSomeOpenGlOperation()
}
```
Finalizers are guaranteed to run (that's by design, as they are involved in resource cleanups).
