### ISSUE TITLE
About '@Volatile ' problem?

### ISSUE THREAD

**Issue by fhlkm** [Kotlin/kotlinx.coroutines#175]
I am run the code of:

https://github.com/Kotlin/kotlinx.coroutines/blob/master/coroutines-guide.md#volatiles-are-of-no-help

However, the result is as follows rather than "Counter=1000000"

Completed 1000000 actions in 36 ms
Counter = 370430

**Comment by mkobit** [comment]
It isn't expected that `Counter=1000000` at the end

> This code works slower, **but we still don't get "Counter = 1000000" at the end,** because volatile variables guarantee linearizable (this is a technical term for "atomic") reads and writes to the corresponding variable, but do not provide atomicity of larger actions (increment in our case).
