### ISSUE TITLE
Cancel the job which suspend in delay can cause it run to next suspend function

### ISSUE THREAD

**Issue by RigarSu** [Kotlin/kotlinx.coroutines#1752]
I have a loop job. Every time I call the resetJob, I cancel the last running Job. It work well in my local environment(No Proguard), But In my release apk, every time I cancel the last job,, the delay will be cancled immediately and the job will continue to run, go to the doSomeRequest(), invokeOnCancellation will be invoke on doSomeRequest(), then job do not continue. I debug my release apk, find continuation.invokeOnCancellation { handler.removeCallbacks(block) } has invoke, but the job still continue run to the second suspend function. Is there anyone encountered this problem. Is it a bug in Proguard, like https://github.com/Kotlin/kotlinx.coroutines/issues/1035
```
fun resetJob() {
    mQueryJob?.cancel()
    mQueryJob = appScope.launch(Fast_UI) {
        delay(30 * 1000)
        //second suspend function
        val result = doSomeRequest()
    }
}
```

**Comment by qwwdfsad** [comment]
Could you please provide a self-contained reproducer that I can run?

**Comment by RigarSu** [comment]
I upgrate the proguard to 6.2.0 and solve this problem.
