### ISSUE TITLE
Flow intermediate operators don't work with method references

### ISSUE THREAD

**Issue by sollecitom** [Kotlin/kotlinx.coroutines#1755]
# Issue
At the moment the intermediate operators that can extend a `Flow`, like `map` as an example, do not accept references to non-suspending methods or to properties.
A function can still be specified as a lambda, so say `flow.map { String.length() }` works, while `flow.map(String::length)` doesn't.

# Possible Solution
We could create additional extension functions accepting `KProperty1` and `KFunction1` and then delegate to the existing one.

## Example

```
fun <T, R> Flow<T>.map(property: KProperty1<T, R>): Flow<R> = map { property.get(it) }
```
for properties and

```
fun <T, R> Flow<T>.map(function: KFunction1<T, R>): Flow<R> = map { function.invoke(it) }
```
for methods.

**Comment by qwwdfsad** [comment]
Unfortunately, this is a not yet addressed  limitation of Kotlin frontend: https://youtrack.jetbrains.com/issue/KT-30536

Introducing an overload as a workaround works, but unfortunately bloats the size of the library, its maintainability and how approachable it is for novices. I will try to push this issue one more time instead
