### ISSUE TITLE
Stateless conflated Broadcast channel

### ISSUE THREAD

**Issue by orwir** [Kotlin/kotlinx.coroutines#1756]
I'm trying to create events handling based on coroutines (`ConflatedBroadcastChannel` specifically) but faced an issue that currently it is not possible to have stateless broadcast channel. Events like button clicks and some notifications relevant only in a small time frame (just when they appeared) and preserving state in the "event bus" leads to unexpected behavior. So question is can we have "stateless flag" in `ConflatedBroadcastChannel` or probably new class to deal with it?

I created small class and it works fine, but might be better to have it natively.

```kotlin
@ExperimentalCoroutinesApi
class StatelessBroadcastChannel<T> constructor(
    private val broadcast: BroadcastChannel<T> = ConflatedBroadcastChannel()
) : BroadcastChannel<T> by broadcast {

    override fun openSubscription(): ReceiveChannel<T> = broadcast
        .openSubscription()
        .apply { poll() }

}
```

**Comment by elizarov** [comment]
Have you tried using `ArrayBroadcastChannel`? It keeps no "state". See https://atoulme.github.io/kotlinx.coroutines/kotlinx-coroutines-core/kotlinx.coroutines.experimental.channels/-array-broadcast-channel/index.html
Use can create it with `BroadcastChannel(capacity)`.

**Comment by orwir** [comment]
Yep, it doesn't preserve a state but it suspends send function while buffer is full. So I get a queue of stale events if my emitter too fast or consumer too slow.

Closest examples to a thing I'm looking for are [PublishProcessor](http://reactivex.io/RxJava/javadoc/io/reactivex/processors/PublishProcessor.html) and [LiveEvent](https://github.com/hadilq/LiveEvent/blob/master/lib/src/main/java/com/hadilq/liveevent/LiveEvent.kt).

**Comment by elizarov** [comment]
@orwir You can get it now with `BroadcastChannel(1).asFlow().conflate()`. 

However, I'm a bit lost in your specific use-case. You originally said that you are looking for a mechanism to handle "events like button clicks and some notifications relevant only in a small time frame" and it looks like `onBackpressureLatest()` (aka `conflate` in Kotlin Flow) is not really appropriate here, since any delay or hiccup in the subscribing code would immediately result in the events being lost. What am I missing here?

**Comment by orwir** [comment]
@elizarov It' seems I just misunderstood how I can work with channels. `BroadcastChannel(1).asFlow().conflate()` is exactly I'm looking for. Thanks for pointing out. You can close the issue.
Seems I need to read once again documentation about channel/flows.
