### ISSUE TITLE
Mocking exception scenarios for suspend function

### ISSUE THREAD

**Issue by nf17** [Kotlin/kotlinx.coroutines#176]
I am writing tests for mocking a exception scenario like this: 
` @Test
    fun getAccountInformation_failure() = runBlocking<Unit>{
        whenever(userManager.getAccountInfo()).thenThrow(Throwable())`

i get back an error 

_org.mockito.exceptions.base.MockitoException: 
Checked exception is invalid for this method!
Invalid: java.lang.Throwable_

i am using the latest mockito version 2.12.

**Comment by elizarov** [comment]
This is a known problem in Mockito that has nothing to do with coroutines. See this issue: https://github.com/mockito/mockito/issues/1166
