### ISSUE TITLE
An explanation of intermediate flow operators does not match the result of sample code

### ISSUE THREAD

**Issue by tatsuyafujisaki** [Kotlin/kotlinx.coroutines#1760]
This issue is about this article:
https://kotlinlang.org/docs/reference/coroutines/flow.html#intermediate-flow-operators

### Issue
Despite  the following explanation,
> It produces the following three lines, **each line appearing after each second**

the following sample code prints three lines at the same time after three seconds.
```kotlin
import kotlinx.coroutines.*
import kotlinx.coroutines.flow.*

          
suspend fun performRequest(request: Int): String {
    delay(1000) // imitate long-running asynchronous work
    return "response $request"
}

fun main() = runBlocking<Unit> {
    (1..3).asFlow() // a flow of requests
        .map { request -> performRequest(request) }
        .collect { response -> println(response) }
}
```

### Result (printed at the same time after three seconds)
```
response 1
response 2
response 3
```

**Comment by qwwdfsad** [comment]
Could you please clarify what version of coroutines and Kotlin are you using?
I've checked your very sample on the latest coroutines and it works as expected

**Comment by Wanchan9** [comment]
123

**Comment by tatsuyafujisaki** [comment]
I am using a runnable Kotlin snippet embedded in the following section, and Kotlin Playground.
https://kotlinlang.org/docs/reference/coroutines/flow.html#intermediate-flow-operators

**Comment by elizarov** [comment]
Kotlin playground waits for results then prints them, so you would not see "printed every second part there". I'll cross-post this problem to Kotlin Playground.

**Comment by tatsuyafujisaki** [comment]
Now I’ve got it. Thank you very much.

**Comment by elizarov** [comment]
Posted to the appropriate tracker now: https://youtrack.jetbrains.com/issue/JS-11816
Thanks for the report. I'm closing the issue here.
