### ISSUE TITLE
callbackFlow and flatMapMerge, how to close channels that are not used anymore ?

### ISSUE THREAD

**Issue by CharlyLafon37** [Kotlin/kotlinx.coroutines#1773]
I have this code inside a class ``ConversationRepository`` that talks to Firebase Database. The Firebase SDK works with callbacks so I figured why not try to wrap them inside a callbackFlow().

The code inside ``ConversationRepository`` looks something like this : 

```kotlin
override fun observeConversationsIds(userId: String): Flow<List<String>> = callbackFlow {
        val path = "products/users/${userId}/conversations"
        val listener = object : ValueEventListener
        {
            override fun onCancelled(error: DatabaseError)
            {
                close(error.toException())
            }

            override fun onDataChange(snapshot: DataSnapshot)
            {
                offer(snapshot.children.mapNotNull { it.key })
            }
        }

        database.getReference(path).addValueEventListener(listener)

        awaitClose {
            Log.d("BLUE", "invoke on close multi")
            database.getReference(path).removeEventListener(listener)
        }
    }

    override fun observeConversation(conversationId: String, currentUserId: String): Flow<Conversation> = callbackFlow {
        val path = "chats/conversations/$conversationId"
        val listener = object : ValueEventListener
        {
            override fun onCancelled(error: DatabaseError)
            {
                close(error.toException())
            }

            override fun onDataChange(snapshot: DataSnapshot)
            {
                snapshot.getValue<ConversationResponse>()?.let { offer(it) }
            }
        }

        database.getReference(path).addValueEventListener(listener)

        awaitClose {
            Log.d("BLUE", "invoke on close single")
            database.getReference(path).removeEventListener(listener)
        }
    }.map { conversationConverter.toConversation(it, conversationId, currentUserId) }
```

And the code in my ``ViewModel`` that uses this Flow looks like this : 
```kotlin
conversationDataSource.observeConversationsIds(currentUserId)
            .onEach { /* Clear the UI conversations list because a change has been detected*/ }
            .flatMapMerge { it.asFlow() } // <-- Flow<List<String>> to Flow<String>
            .flatMapMerge { conversationDataSource.observeConversation(it, currentUserId) }
            .safeCollect { // <--- Extension that fixes issue while https://github.com/Kotlin/kotlinx.coroutines/pull/1730 is not merged and released
                // Put/Update the conversation in the UI conversation list
            }
```

What the code above does is : 
- Observe the list of conversations of a user. The returning list is a List of String that represents each conversation ids.
- At any change in this list, I clear the UI conversations and listen to each one the conversation of the list.
- At any change in each individual Firebase conversations, I update the UI.

But each time ``conversationDataSource.observeConversationsIds(currentUserId)`` emits a new List of conversation ids, I renew the observation of each Conversation since I recall ``conversationDataSource.observeConversation(it, currentUserId)`` on each conversation id.
And I am observing that each time ``conversationDataSource.observeConversationsIds(currentUserId)`` emits, old observations of each conversation id are not closed.

My question is : how do I close the ``Channel``s representing old observations of old conversationIds ? Because a new call to ``flatMapMerge { conversationDataSource.observeConversation(it, currentUserId) }`` will create new ``Channel``s but how do I close the old ones ?

**Comment by elizarov** [comment]
Take a look, please, at `flatMapLatest` which, I think, is supposed to do exactly what you are looking for.
