### ISSUE TITLE
Inconsistent documentation for newSingleThreadContext

### ISSUE THREAD

**Issue by sschilli** [Kotlin/kotlinx.coroutines#1775]
The [Kotlin Native Sharing](https://github.com/Kotlin/kotlinx.coroutines/blob/native-mt/kotlin-native-sharing.md#threads-and-dispatchers) page says the following:

> kotlinx.coroutines provides ability to create single-threaded dispatchers for background work via newSingleThreadContext function that is **available for both Kotlin/JVM and Kotlin/Native**

However, the linked page for [newSingleThreadContext](https://kotlin.github.io/kotlinx.coroutines/kotlinx-coroutines-core/kotlinx.coroutines/new-single-thread-context.html) says this function is available for JVM only:

> Platform and version requirements: JVM

One of these is clearly wrong, and I'm inclined to believe it is the first, since I can't seem to use `newSingleThreadContext` from Kotlin/Native using the latest coroutines version (1.3.3).

**Comment by elizarov** [comment]
The "Kotlin Native Sharing" page and all the related code is not in the master yet. It is a separate work-in-progress branch at this moment.
