### ISSUE TITLE
rxSingle() for coroutines do not return error on exception

### ISSUE THREAD

**Issue by lukjel** [Kotlin/kotlinx.coroutines#1776]
Code example:
```
    override fun handle(input: JsonObject): Single<JsonObject> {
        return kotlinx.coroutines.rx2.rxSingle() {
                apply(input)
        }
    }
```
In case method `apply(input)` throws an exception there is no error for Single.

Kotlin: 1.3.61
Coroutines-Rx2 - 1.3.3
Java OpenJDK 13

I discovered it during migration from Coroutines-RX2 1.1.1
Equivalent code worked properly:
```
    override fun handle(input: JsonObject): Single<JsonObject> {
        return GlobalScope.rxSingle() {
                apply(input)
        }
    }
```

**Comment by lukjel** [comment]
I discovered it during migration from Coroutines-RX2 1.1.1
Equivalent code worked properly:
```
    override fun handle(input: JsonObject): Single<JsonObject> {
        return GlobalScope.rxSingle() {
                apply(input)
        }
    }
```

**Comment by qwwdfsad** [comment]
Could you please show how do you consume the resulting `Single`?
E.g. trivial `rxSingle<Int> { error("error") }.await()` properly propagates the exception

**Comment by lukjel** [comment]
It is a part of our library based on Vertx.io so classes `Handler`, `Message` and `JsonObject` are from Vert.x.
The `handle` function is implemented in Kotlin in class: `BeeverHandler` wich implements `Handler<Message<JsonObject>>`. The object of this class is given to Java object `BeeverVerticle` (exgtends `AbsrtractVerticle` from Vert.x) and is used in method `handle`. 
The most importnat thing: with 1.1.1 it works, with 1.2.0 (and later) not. 

Here is simplified code (I removed not important parts):

```
	@Override
	public void handle(final Message<JsonObject> msg) {
		...
		Single<JsonObject> observable;
		try {
			observable = this.handler.handle(body);
		} catch (Throwable e) {
			observable = Single.error(e);
		}
		observable.subscribe(
			(JsonObject res) -> {
				msg.reply(res);
			},
			err -> {
				handlerLogger.debug("error details: ", err);
				msg.fail(0, err.toString());
			}
		);
	}
```

I've also checked that version 1.2.2 is not working "properly" (where still is `GlobalScope.rxSingle`).

**Comment by lukjel** [comment]
Any ideas?

**Comment by akarnokd** [comment]
This works (Kotlin 1.3.61, Coroutines 1.3.3, Java 8u241 & 13.0.2) so not sure what the problem could be:

```kotlin
fun handle(input: String) : Single<String> {
    return rxSingle {
        "!" + Integer.parseInt(input)
    }
}
```

```java
public class UseSingle {

    public static void main(String[] args) throws Exception {
        SomeRxSingleKt.handle("1")
                .subscribe(System.out::println, Throwable::printStackTrace);

        SomeRxSingleKt.handle("")
                .subscribe(System.out::println, Throwable::printStackTrace);

        Thread.sleep(1000);
    }
}
```

**Comment by qwwdfsad** [comment]
The problem indeed looks like an application-specific.
If you've double-checked and sure that it is a `kotlinx.coroutines` bug or misbehaviour, please attach a self-contained reproduced (the one I could copy-paste/clone from github and run) with a short explanation.
