### ISSUE TITLE
Flow<T>.FlattenMerge has unexpected 'catch()' behavior

### ISSUE THREAD

**Issue by rollie42** [Kotlin/kotlinx.coroutines#1780]
[Playground sample][1]

Given this code, the exception thrown in `getRecords()` is not caught in `testFlattenMerge()` - should it not be catchable though? Also, in `getPeople()`, the exception can be caught which causes `flattenMerge()` to work as expected, but it prints out *"Caught in people"* before any numbers are printed, and not after 64, as I expected. Is this the correct behavior? I can't quite fit my mental model of `flattenMerge()` around this.

    import kotlin.reflect.KProperty
    import kotlin.system.measureTimeMillis
    import kotlinx.coroutines.flow.*
    import kotlinx.coroutines.*
    
    fun getRecords(id: Int) = flow {
        repeat(5) { emit("A record for $id") }
        if (id == 6) throw RuntimeException("Anything but #6!")
        repeat(5) { emit("A record for $id") }
    }
    
    fun getPeople() = flow {
    	repeat(10) { emit(getRecords(it)) }
    	// repeat(10) { emit(getRecords(it).catch{ println("Caught in getPeople()")}) } // This works, but it prints /before/ any cnt lines...?
    }
    
    suspend fun testFlattenMerge() {
        println ("Merge with flattenMerge()")
        var cnt = 0
        val flowOfFlows = getPeople()
        flowOfFlows.catch{ println("Caught before flattenMerge")}
            .flattenMerge()
            .catch{ println("Caught after flattenMerge")}
            .collect {
                println("${cnt++}") // Without catching inside getPeople() this stops at 64
            }
    }
    
    suspend fun testManualMerge() {
        println("Merge manually")
        var cnt = 0    
        repeat(10) {
            getRecords(it).catch{ println("Caught in manual merge") }
            	.collect {
                    println("${cnt++}") // This goes up to 94, as expected
                }
        }
    }
    
    fun main() = runBlocking {
        testFlattenMerge()
        testManualMerge()
    }

  [1]: https://pl.kotl.in/chvzi5JaV

**Comment by qwwdfsad** [comment]
Everything behaves as expected.

>Given this code, the exception thrown in getRecords() is not caught in testFlattenMerge() - should it not be catchable though? 
```
getPeople().catch { println("Caught before flattenMerge") }
    .flattenMerge()
    .catch { println("Caught after flattenMerge") }
```

The first catch has no effect as `getPeople`  never throws an exception -- it just emits cold flows emitted by `getRecord()`.
The second `catch` actually catches the exception from the `getRecord(6)` flow, triggers its body (prints "Caught after flattenMerge") and completes. Doesn't matter whether you have `catch` or no -- any exception will stop the upstream (`Flow<String>` at this moment) similarly to how in a regular code you cannot do the following:
```
try {
    ... code...
} catch (e: Exception) {
    // "please resume 'try' block right after the line that thrown an exception
}
```

And in `testManualMerge` you don't have a single `Flow<String>`, you can 10 independent flows that you collect independently. They are not equivalent in the same manner as the following snippet:
```
val lambdas = List<() -> Unit>(10) { ... }

//  flattenMerge:
try {
    for (lambda in lambdas) lambda()
} catch (e: Throwable) {
   println("Caught after flattenMerge")
}


// Manual merge
repeat(10) {
    try {
        lambdas[it]()
    } catch (e: Throwable) {
       println("Caught in manual merge")
    }
}
```

**Comment by rollie42** [comment]
Ah okay I think I see; a lot of my confusion stemmed from the expectation that `catch()` would enable continued processing.

The only thing I'm a still not sure of then - on the line with the comment (ex: https://pl.kotl.in/MQlUaw--u) it will print "Caught in getPeople()" before any "cnt". If my understanding is correct, `flattenMerge()` will return a flow that, when collected, will collect the result of `getPeople()`. So one coroutine inside `flattenMerge()` will collect from `getRecords(0)`, another from `getRecords(1)` etc (depending on concurrency used in `flattenMerge()`. But it should not collect every record in the result of  `getRecords()` before returning back to the original call site, so while I do expect 'Caught in getPeople()' to be displayed, it should only be displayed after a number of other records have already printed. Maybe not 64 precisely due to concurrency on flattenMerge, but certainly not before any are returned.

So while typing this, I tried specifying concurrency in flattenMerge; from 1-6, the "Caught in getPeople()" is printed after some number of cnt lines. But from 7 or more, it seems consistently printed first. This isn't precisely impossible, since it may be that by chance with various coroutines collecting asynchronously, all choose to collect from the result of getRecords(6), in which case I think the 7th will hit the exception statement, but it seems very unusual. Also, if you do specify something like flattenMerge(7), you would expect changing the throw condition in getRecords from `id == 6` to `id == 4` would cause a different behavior, because the flatten merge was causing collection from the flow generated by getRecords(6) for some reason, but it doesn't change the output.

Not sure if I'm making sense, but...it's a confusing topic ;)

**Comment by qwwdfsad** [comment]
>it will print "Caught in getPeople()" before any "cnt".

It is because `flattenMerge` buffers incoming requests. You can play with `flattenMerge().buffer(1)` to see how it affects the behaviour. 
By using the single-threaded dispatcher (`runBlocking`), the order of the output just leaks internal implementation details: how elements are buffered, how incoming flows are split to multiple coroutines and how they suspend. It is not something worth puzzling about :)
