### ISSUE TITLE
Crash in iOS App Extensions

### ISSUE THREAD

**Issue by Ti-m** [Kotlin/kotlinx.coroutines#1781]
Hey,

I try to use coroutines with kotlin-native on iOS in an NEPacketTunnelProvider
 app extension. https://developer.apple.com/documentation/networkextension/nepackettunnelprovider

In my main app I use coroutines this way without problems:

```
class Test {
    fun doSomething() {
        GlobalScope.launch(MainDispatcher) {
            //do stuff
        }
    }
}

expect val MainDispatcher: CoroutineDispatcher
```

```
actual val MainDispatcher: CoroutineDispatcher = NsQueueDispatcher(dispatch_get_main_queue())
internal class NsQueueDispatcher(
    private val dispatchQueue: dispatch_queue_t
) : CoroutineDispatcher() {
    override fun dispatch(context: CoroutineContext, block: Runnable) {
        dispatch_async(dispatchQueue) {
            block.run()
        }
    }
}
```

But if I run `doSomething()` from the app extension it always crashes.

```
Thread 1 Queue : com.apple.main-thread (serial)
#0	0x00000001fe8170dc in __pthread_kill ()
#1	0x00000001fe890094 in pthread_kill$VARIANT$mp ()
#2	0x00000001fe76fea8 in abort ()
#3	0x0000000100ec6408 in konan::abort() ()
#4	0x0000000100eca66c in TerminateWithUnhandledException ()
#5	0x0000000100eca45c in KonanTerminateHandler() ()
#6	0x00000001fde48838 in std::__terminate(void (*)()) ()
#7	0x00000001fde488c4 in std::terminate() ()
#8	0x00000001fde53d5c in objc_terminate ()
#9	0x00000001fe6b97e8 in _dispatch_client_callout ()
#10	0x00000001fe667008 in _dispatch_main_queue_callback_4CF$VARIANT$mp ()
#11	0x00000001fec0cb20 in __CFRUNLOOP_IS_SERVICING_THE_MAIN_DISPATCH_QUEUE__ ()
#12	0x00000001fec07a58 in __CFRunLoopRun ()
#13	0x00000001fec06fb4 in CFRunLoopRunSpecific ()
#14	0x00000001ff5d595c in -[NSRunLoop(NSRunLoop) runMode:beforeDate:] ()
#15	0x00000001ff610e1c in -[NSRunLoop(NSRunLoop) run] ()
#16	0x00000001fe8d9a44 in _xpc_objc_main ()
#17	0x00000001fe8dc3a4 in xpc_main ()
#18	0x00000001ff612db0 in -[NSXPCListener resume] ()
#19	0x00000002047ce328 in ___lldb_unnamed_symbol369$$PlugInKit ()
#20	0x00000002047ce154 in ___lldb_unnamed_symbol365$$PlugInKit ()
#21	0x00000002047ce6a4 in ___lldb_unnamed_symbol371$$PlugInKit ()
#22	0x00000001ff7e2818 in NSExtensionMain ()
#23	0x00000001fe6ca8e0 in start ()
```

Any ideas what’s the problem here?
Is the function dispatch_get_main_queue() maybe returning something wrong in the context of an app extension?

Versions:
Kotlin 1.3.61
Coroutines 1.3.3

**Comment by Ti-m** [comment]
I created a reproducer. Unfortunately it’s a little hard to set up:
* This only works with a real developer account. You can’t get the entitlement with a personal team.
* This only works on a real device. The Api is not available on simulator
* When the app is started the first time a vpn config is created
* You have to change this line accordingly for this to work: `tunnelProviderProtocol.providerBundleIdentifier = "<your appid of the extension>"`
* It’s easier to see the crash if you attach the debugger: In Xcode: Debug -> Attach to process by PID or Name -> type „vpn“ 
* You can start the extension in the OS settings: Settings -> VPN -> Select Test Profile -> click connect

https://github.com/Ti-m/mpp-example/tree/crash-in-vpn-extension

**Comment by elizarov** [comment]
It looks that you are trying to call `doSomething` from a background thread. Kotlin/Native runtime is not safe to be called to this way. If you initialize your K/N runtime in the main thread, then you should make all the calls to it from the main thread, too. You can use `dispatch_async` in your Swift code for that. 

Does it help?

**Comment by Ti-m** [comment]
Hey,

You are right. If I call my code like this it works:

```
override func startTunnel(options: [String : NSObject]?, completionHandler: @escaping (Error?) -> Void) {
        // Add code here to start the process of connecting the tunnel.
        DispatchQueue.main.async {
              NSLog("vpn-service start")
              let test = Test()
              test.doSomething()//Now this works
              NSLog("vpn-service stop")
        }
}
```

It seems that the default thread of the extension is not the „classical“ main thread.
If I pause it in the debugger its called : „com.apple.NSXPConnection.user.endpoint“ instead of „com.apple.main-thread“

Thank you very much.
