### ISSUE TITLE
Add operator fun <T> ClosedRange<T>.component1|2()

### ISSUE THREAD

**Issue by rollie42** [Kotlin/kotlinx.coroutines#1782]
Closed ranges are always represented as a series pair of values (start, endInclusive). They fit into the model for a data class, but since they are represented by an interface, the same benefit can be obtained with:

```
operator fun <T : Comparable<T> > ClosedRange<T>.component1() = this.start
operator fun <T : Comparable<T> > ClosedRange<T>.component2() = this.endInclusive
```

(Or maybe create an interface type for `Data2` that `ClosedRange` can implement more concisely)

A practical use case for this:

```
fun <T> ClosedRange<T>.byHour() : Sequence<ClosedRange<T>>
        where T : Temporal, T : Comparable<T>  = sequence {
    var t1 = start
    while (t1 < endInclusive) {
        val t2 = (t1 + Duration.ofHour(1)) as T
        yield (t1..t2)
        t1 = t2
    }
}

// ...
val range = rangeStart..rangeEnd
for ((start, end) in range.byHour()) {
    // ...
}
```

**Comment by zach-klippenstein** [comment]
This doesn't have anything to do with coroutines, you probably want to file a kotlin issue instead: http://youtrack.jetbrains.net/issues/KT

**Comment by rollie42** [comment]
Ah fair point - I think I was using this to facilitate something with coroutines, and didn't think much before posting. Will reroute!
