### ISSUE TITLE
Threadlocal context is lost on async

### ISSUE THREAD

**Issue by clintam** [Kotlin/kotlinx.coroutines#1786]
Hi there, we are using thread local context and have observed that the context is lost inside an async block. Interestingly, this only appears to happen when the code inside of `withContext` is a function call (It works as expected when inlining the function)

Reading over #985 I think this is a different issue.

We can reproduce this issue as follows (test fails on master and release 1.3.2)

```
class ThreadContextTest : TestBase() {

    val threadLocal = ThreadLocal<String>()
    val name = "test-name"

    @Test
    fun `async -- extracted body`() = runTest {
        suspend fun body() {
            assertCurrentName()
            async {
                assertCurrentName() // BUG: This fails
            }.await()
        }

        withContext(threadLocal.asContextElement(name)) {
            body()
        }

    }

    @Test
    fun `async -- inline function`() = runBlocking {
        withContext(threadLocal.asContextElement(name)) {
            // This is just inlining the body() above
            assertCurrentName()
            async {
                assertCurrentName()
            }.await()
        }
    }

    private fun assertCurrentName() {
        assertEquals(name, threadLocal.get())
    }
}

```

In the above test, the first case fails, but the second works.

**Comment by qwwdfsad** [comment]
Hi,

This is not a bug, but rather a weird interaction with extensions.
In your `async -- extracted body` example, `async` coroutine is launched on the scope of `runTest` that does not know about your threadlocal. The fix is straightforward -- add  a `CoroutineScope` extension receiver to `body` method

**Comment by clintam** [comment]
Thanks. I confirm this fixes the issue for me, but it does still feel surprising. 

I would have thought the async would "know" about the threadlocal from the context that is present when it runs. But now that I read the doc closely I see

> Coroutine context is inherited from a [CoroutineScope]

and notice that the default value for context is empty
` context: CoroutineContext = EmptyCoroutineContext`

I wonder how things would breakdown if we defaulted the context from `coroutineContext` instead of empty?


A bit more about our use-case: We have APIs that allow us to creating tracing spans with tags like so (simplified):

```
suspend fun <T> runInSpan(spanName: String, body: suspend fun () -> T) : T =  withContext(spanThreadLocal.asCoroutineContext(makeSpan(spanName)) {
body()
}
```

so we have changed this to make the body take the CoroutineContext as a receiver. This does work nicely (but breaks a few usages where the bodies expected a diff receiver).

**Comment by qwwdfsad** [comment]
>I wonder how things would breakdown if we defaulted the context from coroutineContext instead of empty?

It is not really possible because `async` is not a `suspend` function, thus it neither know about the outer context at all, nor have access to it.

Thanks for the use-cases, can confirm you are using it as we've initially designed :)
