### ISSUE TITLE
Duplicate of 'META-INF/kotlinx-coroutines-core.kotlin_module'

### ISSUE THREAD

**Issue by jbruchanov** [Kotlin/kotlinx.coroutines#1797]
In android project depending on ktor & coroutines having
`More than one file was found with OS independent path 'META-INF/kotlinx-coroutines-core.kotlin_module'`

Same files are defined in following deps
```
org.jetbrains.kotlinx:kotlinx-coroutines-core:1.3.3
org.jetbrains.kotlinx:kotlinx-coroutines-core-common:1.3.3
```

`android.packagingOptions` pickFirst/exclude helps as workaround

**Comment by elizarov** [comment]
What AGP version are you using?

**Comment by jbruchanov** [comment]
AGP=3.5.3
kotlin=1.3.61

**Comment by elizarov** [comment]
I cannot reproduce it. How do you add dependency to `kotlinx-coroutines` to your build? Can you share the reproducer build file?

**Comment by jbruchanov** [comment]
quick overview
Project
 - app (depends on android_lib_module1 & android_lib_module2)
 - android_lib_module1 (depends on ktor& droid coroutines)
 - android_lib_module2 (depends on droid coroutines)

both lib_modules released in mavenLocal
app is using them both from mavenLocal

I'll send a repo link later today

**Comment by elizarov** [comment]
I see. That's because of `ktor`, but I don't think it is possible to prevent a dependency to `kotlinx-coroutines-core` from appearing in ktor build, so we need to rename the module name for `kotlinx-coroutines-common`.
