### ISSUE TITLE
Flow onBackpressureDrop analog

### ISSUE THREAD

**Issue by krossovochkin** [Kotlin/kotlinx.coroutines#1807]
In RxJava there are different backpressure strategies among which the most interesting are BUFFER, LATEST and DROP.
In Kotlin Flow there are analogs to BUFFER and LATEST:
- `.buffer()` for BUFFER
- `.conflate()` for LATEST

But there seems no direct way to have DROP.

In RxJava onBackpressureDrop just drops events if consumer is  not ready to consume them.
The difference can be seen in diagrams:
![](https://raw.github.com/wiki/ReactiveX/RxJava/images/rx-operators/bp.obp.latest.png)
![](https://raw.github.com/wiki/ReactiveX/RxJava/images/rx-operators/bp.obp.drop.png)

The use case for DROP strategy is when we're actually not interested in receiving events from the past. 

There is a way to have such functionality:
```
fun <T> Flow<T>.onBackpressureDrop(): Flow<T> {
    return channelFlow { collect { offer(it) } }.buffer(capacity = 0)
}
```
It is based on the fact that `offer` doesn't emit value if consumer is suspended. And we ensure that it will be suspended by using buffer with capacity 0.

I think it would be good to have separate operator for backpressure drop (along with other strategies with `buffer` and `conflate`). 
It might ease migration from RxJava to Kotlin Flow.

**Comment by qwwdfsad** [comment]
It is currently being reviewed in #1798

**Comment by krossovochkin** [comment]
Hi @qwwdfsad 
Thank you, then closing this as duplicate of #1798

**Comment by qwwdfsad** [comment]
Thanks.
By the way, thanks for a detailed write-up and comparison with other operators!
