### ISSUE TITLE
How to ? kotlinx.coroutines on android native. (Godot yield implementation)

### ISSUE THREAD

**Issue by piiertho** [Kotlin/kotlinx.coroutines#1808]
Hi there !

This is more a question than an issue, I don't know if there's a better place to ask.

I am currently working with contributors on adapting Kotlin to godot’s GDNative, using kotlin cinterop: https://github.com/utopia-rise/godot-kotlin.

 In gdscript (godot’s scripting language), there is a `yield` method, which is basically a coroutine. So we implement it for godot-kotlin using kotlin’s couroutines (see [here](https://github.com/utopia-rise/godot-kotlin/tree/master/wrapper/godot-library-extension)).  
We managed to get it working on every platforms, except android, as we cannot find a native implementation for android [here](https://repo1.maven.org/maven2/org/jetbrains/kotlinx/)

What I understand is that on android you have to use a JVM implementation of coroutines, to access `Dispatchers.Main`, according to the [readme](https://github.com/Kotlin/kotlinx.coroutines#android).  
I’d like to know if we understand well the problem, and if you have any workaround to bring `yield` on [godot-kotlin](https://github.com/utopia-rise/godot-kotlin) for android ?

Thank you for your time.

**Comment by elizarov** [comment]
We don't currently ship pre-compiled versions of `kotlinx.coroutines` for AndroidNative targets. See #812 for the relevant issue. 

The main problem is that we lack the infrastructure to test such integration. If you know now to set up the tests for Android/Native toolchain, then you are welcome to contribute. It should start with support for AndoidNative targets in atomicfu project. See https://github.com/Kotlin/kotlinx.atomicfu/issues/122

P.S. I'm closing this issue as a duplicate.
