### ISSUE TITLE
Cancellation of an Actor after deprecation of ActorJob

### ISSUE THREAD

**Issue by bohsen** [Kotlin/kotlinx.coroutines#181]
After updating kotlinx.coroutines to version 0.20 I've found out that actor() now returns a SendChannel instead of an ActorJob as this has been deprecated. 
This means that you no longer have access to the cancel()-method.
With this change how would you do a cancellation? Should you just call close() instead of cancel()?

This is my code:
```kotlin
private val actor = actor<Action>(UI, Channel.CONFLATED) {
        for (action in this) when (action) {
              is someAction ->  doSomething()
        }
    }
    ...
// Should cancel() be replaced with close()?
override fun onCleared() = actor.cancel().unit
```

This is  from an Android project by the way.

**Comment by jcornaz** [comment]
Personnaly, I would simply close the `SendChannel` yes.

If you realy feel the need to immediatly cancel the Job, you can still  [cancel the coroutines via explicit job](https://github.com/Kotlin/kotlinx.coroutines/blob/master/coroutines-guide.md#cancellation-via-explicit-job):

```kotlin
private val actor = Job()

init {
  actor<Action>(UI, Channel.CONFLATED + actor) {
        for (action in this) when (action) {
              is someAction ->  doSomething()
        }
    }
}

...

override fun onCleared() {
   actor.cancel()
}
```

**Comment by bohsen** [comment]
@jcornaz Thank you very much for the quick and excellent answer.
