### ISSUE TITLE
flowOn causes EXC_BAD_ACCESS on iOS

### ISSUE THREAD

**Issue by kar** [Kotlin/kotlinx.coroutines#1810]
When I try to explicitly set the dispatcher for my flow, my app crashes pointing to:

#0	0x0000000102f64f14 in kfun:kotlinx.coroutines.flow.checkFlowContext#internal ()

Works fine on Android, or when I remove the flowOn call from my flow.

Any ideas on how to debug this?

**Comment by elizarov** [comment]
Can you give more details, please. Are you trying to work from multiple-threads? If so, please note that Kotlin/Native runtime is not thread-safe -- you cannot access regular K/N object from multiple threads; they must be froze. Also, you'll need a special version of `kotlinx.coroutines` that makes coroutines themselves shareable. See #462 for details.

**Comment by elizarov** [comment]
See #462, please
