### ISSUE TITLE
How to test kotlin suspend function from spock

### ISSUE THREAD

**Issue by mariusstaicu** [Kotlin/kotlinx.coroutines#1812]
Hi, 

I haven't found a way until now to unit test a suspend function using spock.
If anyone can shed some light on this please do so.
Thanks

**Comment by elizarov** [comment]
You can try calling your suspending function from `runBlocking { ... }` and then testing the result of that.

**Comment by mariusstaicu** [comment]
I cannot use runBlocking from spock, however this is a good idea. I could create a wrapper kotlin function with runBlocking{}. Thanks, I'll try.

**Comment by julianwki** [comment]
You could also mock that Continuation object, which kotlin is compiling into the method call. This code worked for me:

```
def continuation = Mock(Continuation) {
  getContext() >> Mock(CoroutineContext)
}

subjectUnderTest.suspendableMethod(someParameter, continuation)
```

**Comment by madhu-kt** [comment]
It's been a while, but is this still the acceptable way to mock suspend functions using Spock?
@julianwki Your solution works great to some extent, but when using wildcard invocations via `0 * _`, tests fail with this error:

```
Too many invocations for:

0 * _   (1 invocation)

Matching invocations (ordered by last occurrence):

1 * continuation.getContext()   <-- this triggered the error
```
Am I missing something?

Thanks

**Comment by javiersolis1023** [comment]
> You could also mock that Continuation object, which kotlin is compiling into the method call. This code worked for me:
> 
> ```
> // mocked continuation
> def continuation = Mock(Continuation) {
>   getContext() >> Mock(CoroutineContext)
> }
> 
> // method call which should be tested
> subjectUnderTest.suspendableMethod(someParameter, continuation)
> ```

If the method should return a value,  how you obtain the value?

**Comment by ACharchula** [comment]
I'm using `BuildersKt` which lets to run `runBlocking` in Groovy:

`
    <T> T runBlocking(Closure<T> suspendingFunction) {
        return BuildersKt.runBlocking(
            EmptyCoroutineContext.INSTANCE,
            (scope, continuation) -> suspendingFunction(continuation)
        )
    }
`

I based it on solution presented in article: https://kt.academy/article/cc-other-languages `Calling suspending functions from other languages`
