### ISSUE TITLE
ConflatedBroadcastChannel should deliver last value

### ISSUE THREAD

**Issue by pacher** [Kotlin/kotlinx.coroutines#1816]
For `ConflatedChannel` the problem was discussed in #332, addressed in #1235 and fixed by #1239,
but not for `ConflatedBroadcastChannel`

Slightly modified example from #1235:
```kotlin
fun main() = runBlocking {
    val channel = Channel<Int>(capacity = Channel.CONFLATED)
    with(channel) {
        send(1); send(2); send(3); send(4)
        close()
    }
    println(channel.receive())
}
```
Correctly prints `4`, but
```kotlin
fun main() = runBlocking {
    val channel = ConflatedBroadcastChannel<Int>()
    with(channel) {
        send(1); send(2); send(3); send(4)
        close()
    }
    println(channel.openSubscription().receive())
}
```
throws `ClosedReceiveChannelException`

Is it by design?

**Comment by elizarov** [comment]
It is the design now, but we can change it. What is your use-case for `ConflatedBroadcastChannel` where this difference in behavior becomes important?

**Comment by fluidsonic** [comment]
I just ran into the same issue.

I have a `ConflatedBroadcastChannel` for emitting `DownloadStatus` (initial, running[…], completed).

```kotlin
class DownloadCoordinator {
   private val stateChannel = ConflatedBroadcastChannel<DownloadState>(DownloadState.Initial)
   val state = stateChannel.asFlow()
   // etc.
}
```

Emitting looks like this:
- initial
- running (10%)
- …
- running (90%)
- complete
- **close**

Now a consumer that's interested in the latest state of the download simply does this:

```kotlin
downloadCoordinator.state.first()
```

It was totally unexpected to me that `.first()` doesn't work on a `ConflatedBroadcastChannel`-backed `Flow` once it's closed:
```
NoSuchElementException: Expected at least one element
```

Not even `val state = stateChannel.asFlow().conflated()` seems to help 🤔

**Comment by qwwdfsad** [comment]
Thanks for the detailed explanation.
It seems like this particular problem will be resolved with stateful flow

**Comment by elizarov** [comment]
It is being provided by implementation in #1974

**Comment by pacher** [comment]
@elizarov Sorry for late reply in these difficult times
My use case is like in #332, that is why I did not specify it. More specifically second use case in your  [comment](https://github.com/Kotlin/kotlinx.coroutines/issues/332#issuecomment-405903512).
I have a computation producing intermediate results, which I want to expose as `Flow` from API. So I have private `ConflatedBroadcastChannel` and expose it via `channel.asFlow()`.
My original intention was to close channel normally when computation is complete to indicate that the last result is a final result of computation. And close with error if computation fails.
But if the client collects the flow after channel is closed, it gets no results at all.
Currently my solution is to never close channels, which feels wrong. I also had to introduce additional wrapper class with `isFinal` flag, so that I can use `takeUntil { it.isFinal }` operator on the flow before returning it. Btw, currently there is no such operator in the library.

Anyway, my point was that `ConflatedChannel` and `ConflatedBroadcastChannel` should behave similarly. I don't see why the number of clients should change the semantics wrt last value. Deliver last value or not, but shouldn't it be consistent? What is the fundamental difference in semantics between the two which I am missing? I though that it was just overlooked and forgotten, so I opened this issue to remind.

Now, you can close the issue if you will, but in my opinion it is not resolved. Neither `StateFlow` nor `SharedFlow` could be used in case of computation with intermediate values because they are both designed for never-ending streams. They can not be closed and there are no mechanisms for error propagation.

**Comment by elizarov** [comment]
@pacher As discussed in `SharedFlow` design #2034 you can materialize completion. There is no `takeUntil` operator, but there is a `takeWhile` operator, so you can write `takeWhile { !it.isFinal }` on the collector's side of the `SharedFlow`. Moreover, shared flow lets you replay any number of items to the collectors, so you can configure shared flow with `replayCapacity = 2` to get both the final result and the completion status of the computation. Thus, it seems to me that the shared flow design in #2034 fully covers your use-case.

**Comment by pacher** [comment]
> so you can write `takeWhile { !it.isFinal }`

@elizarov No I can't, because then final result will not be included, which is a bummer.
The difference to `takeWhile` is that predicate is checked after emitting the item so that the item which flipped predicate is included as well. [RxJava](http://reactivex.io/RxJava/3.x/javadoc/io/reactivex/rxjava3/core/Flowable.html#takeUntil-io.reactivex.rxjava3.functions.Predicate-) and [Reactor](https://projectreactor.io/docs/core/release/api/reactor/core/publisher/Flux.html#takeUntil-java.util.function.Predicate-) both have `takeWhile`/`takeUntil` combo. Weirdly I did not find it in kotlin collections, I was sure it is there too.

For implementation I copy-pasted `takeWhile` and changed
```kotlin
            if (predicate(value)) emit(value)
            else throw AbortFlowException(this)
```
to
```kotlin
            emit(value)
            if (predicate(value)) throw AbortFlowException(this)
```
But it would be really nice to have it in the library (even simple `takeWhile` uses internal classes which I had to copy as well). Maybe somebody can make a PR, maybe even me.

> As discussed ... shared flow design in #2034 fully covers your use-case

Yes, I got your point in #2034 that materializing is the way to go, which I still think is a workaround (and [not only me](https://github.com/Kotlin/kotlinx.coroutines/issues/2034#issuecomment-630731259)).  I would rather say: "`SharedFlow` could be used in building a solution which covers your use-case".

While we are waiting for proper operators in the library, can you please have a look at this naive implementation of dematerialize?
```kotlin
sealed class Event<T> {
    class Emission<T>(val item: T) : Event<T>()
    class Error(val error: Throwable) : Event<Nothing>()
    object Complete : Event<Nothing>()
}

fun <T> Flow<Event<T>>.dematerialize(): Flow<T> = 
    takeWhile { it !is Complete }
        .map { 
            when(it) {
                is Emission -> it.item
                is Error -> throw it.error
                Complete -> error("Can not happen")
            }
        }
```
Is it usable? Is it idiomatic just to throw from `map`? Will it play nicely with cancelling subscription upstream, cleaning up and whatnot (my source is currently still `ConflatedBroadcastChannel.asFlow()` which uses `openSubscription`)? I guess the answers are `yes`, but I am still too new to coroutines to feel confident
Thanks

**Comment by elizarov** [comment]
> > so you can write `takeWhile { !it.isFinal }`
> No I can't, because then final result will not be included, which is a bummer.

@pacher Good point. Thanks. See #2042 

> While we are waiting for proper operators in the library, can you please have a look at this naive implementation of dematerialize?
> Is it usable? Is it idiomatic just to throw from `map`? Will it play nicely with cancelling subscription upstream, cleaning up and whatnot (my source is currently still `ConflatedBroadcastChannel.asFlow()` which uses `openSubscription`)? I guess the answers are `yes`, but I am still too new to coroutines to feel confident

This implementation looks good to me and it is quite idiomatic. It is similar to what we'll write if we make a decision to include that kind of operator into the library.

**Comment by elizarov** [comment]
We've decided to add `Flow.transformWhile` operator for now to cover the use-case of delivering last value and then completing. See #2065 for details.
