### ISSUE TITLE
Not seeing 1.3.3 on npm

### ISSUE THREAD

**Issue by ScottPierce** [Kotlin/kotlinx.coroutines#1819]
I had to downgrade to 1.3.2, as I'm not seeing 1.3.3 on npm: https://www.npmjs.com/package/kotlinx-coroutines-core

**Comment by qwwdfsad** [comment]
Yep, 1.3.3 wasn't published because of the internal infrastructure problems.
We'll see whether we can publish it now

**Comment by qwwdfsad** [comment]
Fixed by uploading 1.3.4 to the NPM :)
