### ISSUE TITLE
Question regarding new parent parameter in builders

### ISSUE THREAD

**Issue by frnusmartobjects** [Kotlin/kotlinx.coroutines#182]
Hello,

I was reading the tutorial [here](https://github.com/Kotlin/kotlinx.coroutines/blob/master/coroutines-guide.md#parental-responsibilities) which says to use coroutineContext

But in [this](https://github.com/Kotlin/kotlinx.coroutines/blob/master/ui/coroutines-guide-ui.md#lifecycle-and-coroutine-parent-child-hierarchy) tutorial the Job is used for the parenting responsiblities

Main question is: I am not sure which way to use for indicating parenting relationships, which one is correct? Is the new `parent` parameter in the builders is the new correct way of creating children coroutines with an explicit parent?

Side question: Where can I read about there differences between coroutine context (or scope) and `Job`?

Thank you

**Comment by elizarov** [comment]
Both are correct. The more detailed description was moved to this section of the guide:
https://github.com/Kotlin/kotlinx.coroutines/blob/master/coroutines-guide.md#cancellation-via-explicit-job

The documentation for `launch` also explains how `parent` works:
https://kotlin.github.io/kotlinx.coroutines/kotlinx-coroutines-core/kotlinx.coroutines.experimental/launch.html

I've provided further details in this StackOverflow Q&A: https://stackoverflow.com/questions/47689984/what-is-the-difference-between-coroutinecontext-and-job-in-kotlinx-coroutines/47689985

**Comment by frnusmartobjects** [comment]
Thank you very much
