### ISSUE TITLE
runBlocking and coroutineScope in documentation

### ISSUE THREAD

**Issue by BulatMukhutdin** [Kotlin/kotlinx.coroutines#1822]
In [documentation](https://kotlinlang.org/docs/reference/coroutines/basics.html#scope-builder) it is stated that 
```
The main difference between these two is that the runBlocking method blocks the current thread for waiting, while coroutineScope just suspends, releasing the underlying thread for other usages
```
This place needs clarification because both of operators 'blocks': the one that is given in code snippet and the alternative
```
suspend fun foo() = coroutineScope {
    println("Start scope")

    launch {
        println("Start nested launch")
        delay(200L)
        println("Task from nested launch")
    }

    coroutineScope {
        println("Start nested scope which is also would be waited")
        delay(300)
        println("Task from nested scope")

    }

    println("Coroutine scope is over") // This line is not printed until the nested coroutineScope completes
}
```

**Comment by fvasco** [comment]
@BulatMukhutdin 
What is your proposal?

**Comment by BulatMukhutdin** [comment]
For me is seems that they both  are blocking since in both cases ``` println("Coroutine scope is over")``` would be printed only after ```coroutineScope``` fininsh

**Comment by pikzen** [comment]
How is that different from calling any `suspend fun` ? Replacing your nested coroutineScope with a suspend fun would have the exact same behavior. `coroutineScope` doesn't spawn a new coroutine. It takes, the, well, current coroutine scope and does things in it.

runBlocking is for running suspendable functions in a non coroutine context. Say, in your main() function.

**Comment by BulatMukhutdin** [comment]
I am not talking about a purpose of runBlocking.
The main question is: why it is stated that runBlocking blocks thread while coroutineScope only suspends it. From my perspective they both are blocking. 
Could you please provide an example where you call coroutineScope with some delay and it doesn't delay the very next operation after it?

**Comment by fvasco** [comment]
> why it is stated that runBlocking blocks thread while coroutineScope only suspends it. From my perspective they both are blocking.

You should refer to the [official KEEP](https://github.com/Kotlin/KEEP/blob/master/proposals/coroutines.md), "block a coroutine" is a unspecified behaviour and it does not have a defined meaning.

In other words: when a thread blocks it blocks the routine that it has running.
Instead, when a coroutine suspends, the `Dispatcher` runs another coroutine on the same thread; in this case, the coroutine was suspended, but the thread is running another coroutine, it was not blocked.

Regarding the example, the `delay` function is composed by two routines, the first one schedules the second one after a delay, so the "coroutine" (both routines) completes when the second one completes.
During this delay (the suspension) the thread is available (possibly running).
Finally, you should note that the `Dispatcher` can resume the second routine on a different `Thread`.
