### ISSUE TITLE
Queue of tasks without a receiver

### ISSUE THREAD

**Issue by recheej** [Kotlin/kotlinx.coroutines#1835]
As far as I know, there's not a primitive for a queue of tasks. So say you want to run a list of suspending functions without blocking, but each function is run after the previous completes. Something close is ```Channel```, but that requires a receiver on the other end. 

@elizarov thoughts?

**Comment by denkuy** [comment]
What is a queue of tasks? `List<Job>`? Wouldn't that just be a `for` coupled with an `await`?

**Comment by recheej** [comment]
@denkuy @elizarov  basically I'd like a  (simple) way to run an arbitrary number of tasks, but sequentially, FIFO. and then of course await the result. Is there a simple way to do this via a for loop + await? How would you get a reference "previous" jobs?

**Comment by elizarov** [comment]
Assuming that you have `tasks: List<Task>` and a `suspend fun processTask(task: Task)` you can simply write:

```
tasks.forEach { processTask(it) }
```

Does it work for you? If not, can you please elaborate more on the problem you are having and give some code example?
