### ISSUE TITLE
Update version for kotlin up to 1.3.70

### ISSUE THREAD

**Issue by IgorKey** [Kotlin/kotlinx.coroutines#1839]
kotlin 1.3.70 released https://blog.jetbrains.com/kotlin/2020/03/kotlin-1-3-70-released/
Need to update coroutines library up to 1.3.70 and kotlin-native coroutines to aka 1.3.4-mt.

**Comment by elizarov** [comment]
Already fixed in PR #1837, will be released soon, followed by mt version sometime after.
