### ISSUE TITLE
How to do UnitTests for classes based on corroutines?

### ISSUE THREAD

**Issue by XinyueZ** [Kotlin/kotlinx.coroutines#184]
The UnitTests goes forward through, however, the tests should be unsuccessful.

```
    @Test
    fun testSample() {
        runBlocking(testJob) {
            launch(testJob) {
                assertThat(1, `is`(10))
            }.also { it.join() }
        }
    }
```

I know it could handle assertThat in main-thread ,but, I really want to handle assert in routine itself.

**Comment by jcornaz** [comment]
Here is a workaround :

Define an alternative to join, that would throw any exception occurring when executing the job
```kotlin
suspend fun Job.joinAndThrow() {
  join()
  val exception = getCancellationException()
  if (exception is JobCancellationException)
    exception.cause?.let { throw it }
}
```

Then the following test will fail (as expected)
```kotlin
@Test
fun testSample() = runBlocking {
  launch {
    assertThat(1, `is`(10))
  }.joinAndThrow()
}
```

Result :
```
java.lang.AssertionError: 
Expected: is <10>
     but: was <1>
```

But I'm not realy satisfied with this solution, and I would like to know if there is a proper way to propagate exception occuring in job.

**Comment by XinyueZ** [comment]
@jcornaz I think the problem is from ```also```.  The ```also``` provides return 's value to caller of sample2 and the program goes through.  When the ```join``` is being now outside and called directly, there's normal usage and the problem is no more.

```
 @Test
    fun testSample2() {
        runBlocking(job) {
            launch(job) {
                assertThat(1, `is`(10))
            }.also { it.join() }
        }
    }

    @Test
    fun testSample3() {
        runBlocking(job) {
            launch(job) {
                assertThat(1, `is`(10))
            }.join()
        }
    }
```

**Comment by jcornaz** [comment]
@XinyueZ, `also` shouldn't cause any problem. As it is an inline extension function, the code you put in braces will remplace the call of `also` at compile time.

I am realy surprised, if you say that `testSample3` run as expected for you (the test fail).

for me, this doesn't work as expected (the test pass) :
```kotlin
@Test
fun testSample3() {
  runBlocking {
    launch {
      assertThat(1, `is`(10))
    }.join()
  }
}
```

**Comment by XinyueZ** [comment]
@jcornaz But it was really different between with ```also``` and without it.
I ran them just now, the ``testSample3``` works as I want.

**Comment by jcornaz** [comment]
Could you please share the code of the whole test class ?

I am especialy, interested to see what is the `job` instance you give as an argument to `launch`

If `join` would work as we expect, this test should pass (and it doesn't) :
```kotlin
class CustomException : Throwable()

@Test(expected = CustomException::class)
fun testSample4() = runBlocking {
  launch {
    throw CustomException()
  }.join()
}
```

**Comment by XinyueZ** [comment]
@jcornaz 
```

@RunWith(RobolectricTestRunner::class)
class TestSomething {

    val job = Job()
    
    @Test
    fun testSample1() = runBlocking(job) {
        launch(job) {
            assertThat(1, `is`(10))
        }.join()
    }

    @Test
    fun testSample2() {
        runBlocking(job) {
            launch(job) {
                assertThat(1, `is`(10))
            }.also { it.join() }
        }
    }

    @Test
    fun testSample3() {
        runBlocking(job) {
            launch(job) {
                assertThat(1, `is`(10))
            }.join()
        }
    }
}
```

**Comment by jcornaz** [comment]
Your test is biased because you use the same job instance for all of your tests function.

The job will hold the exception instance, and the second test will directly fail at `runBlocking`, because the job state is already "completed with an exception".

To make the tests unbiased init your job like that : 

```kotlin
lateinit var job: Job

@Before
fun setup() {
  job = Job()
}
```

And you will see no diference if you use also or not.

**Comment by XinyueZ** [comment]
I c, it is fixed. Thx guy.

**Comment by jcornaz** [comment]
You're welcome.

Besides, you may be interested to look at this thread #61.

It says, that using `async` instead of `launch`, and `await` instead of `join` would solves the problem :

```kotlin
@Test
fun testSample() {
    runBlocking(testJob) {
        async(testJob) {
            assertThat(1, `is`(10))
        }.await()
    }
}
```
