### ISSUE TITLE
runBlocking does not wait for a coroutine with different CoroutineScope

### ISSUE THREAD

**Issue by vidhithakrar** [Kotlin/kotlinx.coroutines#1849]
I want to write an integration test where I don't want to make the coroutine execution synchronous from the test. The code looks something like below:

    @Test
    fun testDoWork() {
        runBlocking {
            val backgroundWorker = BackgroundWorker()
            backgroundWorker.doWork()
        }
        println("end")
    }

    class BackgroundWorker :
    CoroutineScope by CoroutineScope(Dispatchers.IO) {
    fun doWork() {
        println("starting work")
        this@BackgroundWorker.launch {
            println("staring coroutine")
            delay(100L)
            println("changing context")
            withContext(Dispatchers.Default) {
                println("in a different context")
                delay(50L)
                println("done with different context")
            }
            println("ending coroutine")
        }
    }
}

Output:

starting work
staring coroutine
end

Here runBlocking does not wait for the coroutine to finish. I am not able to understand why is it so. 

If I use the same dispatcher as runBlocking like below then it works as expected:

    runBlocking {
            val backgroundWorker = BackgroundWorker(this.coroutineContext)
            backgroundWorker.doWork()
        }
   
    class BackgroundWorker(private val dispatcher: CoroutineContext) :
    CoroutineScope by CoroutineScope(dispatcher) {
    fun doWork() {
        println("starting work")
        this@BackgroundWorker.launch(Dispatchers.IO) {
            println("staring coroutine")
            delay(100L)
            println("changing context")
            withContext(dispatcher) {
                println("in a different context")
                delay(50L)
                println("done with different context")
            }
            println("ending coroutine")
        }
    }
}

**Comment by fvasco** [comment]
> A parent coroutine always waits for completion of all its children.
https://kotlinlang.org/docs/reference/coroutines/coroutine-context-and-dispatchers.html#parental-responsibilities

In your first example, `BackgroundWorker` isn't a child of `runBlocking`.
In fact you can safety remove the `runBlocking` invocation without changing the sample behaviour.

Instead, in the second example, `this@BackgroundWorker.launch` is a child of `runBlocking`, so it works as you expect. (And you cannot remove `runBlocking` safety)

**Comment by vidhithakrar** [comment]
Sorry, But I am not able understand why do you say that in the first example, `BackgroundWorker` is not the child of `runBlocking`?

In both the examples, the only difference is the dispatcher which is being set in while initialising `BackgroundWorker`. In the first example, it's `Dispatchers.IO` while in the second example it's same as `runBlocking`. But in both the examples, `BackgroundWorker` uses different dispatchers internally.

**Comment by fvasco** [comment]
> BackgroundWorker is not the child of runBlocking?

No, in the first example: `class BackgroundWorker :
CoroutineScope by CoroutineScope(Dispatchers.IO)`, there is no external reference.

> the only difference is the dispatcher which is being set in while initialising BackgroundWorker

In the second example `this@BackgroundWorker.launch` is a child of the `runBlocking` parent scope, in the first example `this@BackgroundWorker.launch` is a child of `CoroutineScope(Dispatchers.IO)`.

**Comment by vidhithakrar** [comment]
Ok, Now I understood what you are saying. 

When we create CorouineScope with `CoroutineScope(Dispatchers.IO)` it creates a new `Job()` which does not have any reference to the parent job, in this case `runBlocking` is a parent Job.

But when we create CoroutineScope with CoroutineContext of `runBlocking` as shown in the second example, it already has a job which is used as a parent job and hence `runBlocking` waits for the child Coroutine to complete.

**Comment by fvasco** [comment]
Yes @vidhithakrar,
you understood.

Structured concurrency uses Job's hierarchy.

I think you can close this issue.

For future generic questions, please consider other [resources](https://kotlinlang.org/community/#kotlin-online-resources), like [Kotlin Forum](https://discuss.kotlinlang.org).
