### ISSUE TITLE
Multiplatform Actors

### ISSUE THREAD

**Issue by penn5** [Kotlin/kotlinx.coroutines#1851]
Currently, actors are only supported on JVM. The lack of multiplatform actors is currently blocking my project, and from the imports of Actors.kt, I would think that there is no JVM-specific code at all in actors. I haven't looked in depth though.

**Comment by qwwdfsad** [comment]
We have a long-term plan to support proper multiplatform actors (#87).
Porting existing code to MPP is a no-go because current actors are way too flawed. And designing new ones is a task that requires a lot of time we don't have (yet).

Closing as duplicate.
