### ISSUE TITLE
channelFlow cannot catch exception from callback

### ISSUE THREAD

**Issue by Nghicv** [Kotlin/kotlinx.coroutines#1853]
I try to get the current location using coroutines. But I cannot catch exceptions if they happened inside a callback 
```
fun requestUpdateLocation(): Flow<LocationResult> = channelFlow {
        // ...
        fusedLocationClient.lastLocation.addOnCompleteListener { locationTask ->
            // throw RuntimeException() // cannot catch
            val location = locationTask.result
                //...
        }
            // ...

        awaitClose {
            ...
        }
    }
        .catch { e -> // cannot catch exception }
        .flowOn(Dispatchers.Main)
```

**Comment by elizarov** [comment]
I'm not sure how your question is related to coroutines. Assume you were not using coroutines. How would catch an exception that was thrown inside `addOnCompleteListener {  .... }` code?

**Comment by Nghicv** [comment]
Maybe it is not related to coroutines. 
I faced this issue when migrating from RxJava to kotlin coroutines. 
Rx version:
```
fun requestUpdateLocation(): Single<LocationResult> = Single.create<LocationResult> { emitter ->
        // ...
        fusedLocationClient.lastLocation.addOnCompleteListener { locationTask ->
            // throw RuntimeException() // cannot catch
            val location = locationTask.result
                //...
        }
            // ...

        awaitClose {
            ...
        }
    }
```
We can catch an exception that was thrown inside addOnCompleteListener { .... } in `onError`. Can we do the same with kotlin coroutines in this case?

**Comment by elizarov** [comment]
Can you provide a self-contained example that shows how you catch this exception using `onError` with Rx, please?

**Comment by Nghicv** [comment]
Exceptions are handled from caller like below:
Rx:
```
requestUpdateLocation()
    .subscribe(
                { result -> handleResult(result) },
                { throwable -> handleError(throwable) } // Exception is catched here
            )
```
Coroutines:
```
requestUpdateLocation()
   .catch { e -> handleError(e) // cannot catch exception }
   .flowOn(Dispatchers.Main)
   .collect { result -> handleResult(result) }
```

**Comment by elizarov** [comment]
@Nghicv I mean example where an exception from inside of `addOnCompleteListener { ... }` gets caught`/.

**Comment by elizarov** [comment]
I'm closing it. Feel free to reopen if you still have a problem here.
