### ISSUE TITLE
Nested runBlocking and init block

### ISSUE THREAD

**Issue by fvasco** [Kotlin/kotlinx.coroutines#1861]
I found a trouble in the follow code:

```kotlin
import kotlinx.coroutines.launch
import kotlinx.coroutines.runBlocking

object A {
    var ok = false

    init {
        println(1)
        runBlocking { }
        println(2)
        ok = true
        println(3)
    }

}

fun main() {
    runBlocking {
        launch { println(A.ok) }
        launch { println(A.ok) }
    }
}
```

I expect:

```
1
2
3
true
true
```

but it is:

```
1
false
2
3
true
```

openjdk version "11.0.6" 2020-01-14
kotlin 1.3.70
coroutine 1.3.4

**Comment by qwwdfsad** [comment]
This is the same problem as described #1697 (see my explanation here)

It is basically a tradeoff between "nested runblocking just hangs the thread and you have a deadlock" and "nested runblocking sometimes confuses people"

Closing as duplicate, let's move our discussion there

**Comment by fvasco** [comment]
Thank you, @qwwdfsad,
are you pointing to

> @fvasco recommendation is correct, closing the issue

Can you check the issue reference, please?

In this case, nested runblocking sometimes confuses object initialization. The object `A` can be used uninitialized, `ok` cannot be false.
