### ISSUE TITLE
Some of ext. functions are implicit

### ISSUE THREAD

**Issue by nil2l** [Kotlin/kotlinx.coroutines#187]
For example `Channel.find()` function won't return `null` if `Channel` is not closed.

The behaviour is implicit. Well, it works good and maybe even expected, but it's very different from `Collection.find()` behaviour. And before use you have to test to make find out exactly. So some remark in documentation would be nice here (or another method name?). 

https://kotlin.github.io/kotlinx.coroutines/kotlinx-coroutines-core/kotlinx.coroutines.experimental.channels/find.html

**Comment by elizarov** [comment]
The general description should be placed into some general documentation about `Channel`. Unlike both `List` and `Sequence` types, `Channel` types represent a *hot* stream of data, like data coming from a network connection. It arrives when it arrive and once it is consumed it is consumed. 

However, adding some short piece of documentation that highlights this makes sense for all operators on channels.

**Comment by qwwdfsad** [comment]
I am closing this as obsolete, we are going to deprecate all such extensions on channels
