### ISSUE TITLE
Is the order of execution between different coroutine threads guaranteed by the order these thread are created through GlobalScope.launch(coroutineContext)?

### ISSUE THREAD

**Issue by sunset2017** [Kotlin/kotlinx.coroutines#1871]
Suppose I have following code to save data to disk asynchronously:

fun saveData(data: Data) {
    GlobalScope.launch(Dispatchers.IO) {
        saveDataOperation(data);
    }
}

This function is called twice by two different thread, is it guaranteed that the execution of saveDataOperation(data) will be determined by the order of this saveData function being called? A different phasing is: is it possible that the data saved in the second call being overridden by the data saved in the first call due to the actual execution order reversed?

**Comment by elizarov** [comment]
No. There is no guarantee on the order of coroutines launched this way. The best way to ensure order is to have a _single_ coroutine doing all the operations in the order you need.
