### ISSUE TITLE
IllegalStateException : Already resumed

### ISSUE THREAD

**Issue by gurveers** [Kotlin/kotlinx.coroutines#1874]
Hi, 

I am observing live data using _observeForever()_ and then removing the observer later.  I handle success and failure scenarios and resume the continuation object accordingly. 

//failure
`
removeObserver(observer)
`
`
if (coroutine.isActive) coroutine.resume(getErrorState())
`
//success
`
removeObserver(observer)
`
`
if (coroutine.isActive) coroutine.resume(data)
`

In most cases it works fine. However, randomly few times I get exception :

Fatal Exception: java.lang.IllegalStateException: Already resumed, but proposed with update android.widget.RemoteViews@ebbd63d
       at kotlinx.coroutines.CancellableContinuationImpl.alreadyResumedError(CancellableContinuationImpl.java:277)
       at kotlinx.coroutines.CancellableContinuationImpl.resumeImpl(CancellableContinuationImpl.java:272)
       at kotlinx.coroutines.CancellableContinuationImpl.resumeWith(CancellableContinuationImpl.java:189)

It seems , the _**isActive**_ check isn't behaving as expected. Please suggest a better check to avoid this crash. 

Cheers !

**Comment by elizarov** [comment]
Can you give a little bit more context on your code, please. Do you have a self-contained reproducer by any chance?

**Comment by gurveers** [comment]
> Can you give a little bit more context on your code, please. Do you have a self-contained reproducer by any chance?

Sorry, didn't understand exactly. I'll try to elaborate. 
I have a runBlocking block, which gets resumed based on LiveData I am observing. This LiveData can return error/success/cachedData. This might be sending multiple data depending on cache data and network availability. In order to prevent "Already Resumed " exception, I added the **isActive** checks. However, it doesn't seem to work always as I am still observing this exception but hard to get into that scenario.

pseudo code as below, 
```
@Synchronized
fun getData(): UserData = runBlocking {
  suspendCancellableCoroutine<UserData> { coroutine ->
                         observer = Observer { response ->
                            
                            response.either({
                              // failure 
                               removeObserver()
                               if ((response as Either.Left).hasCachedData) {
                                    if (coroutine.isActive) coroutine.resume(data)
                                } else {
                                    if (coroutine.isActive) coroutine.resume(getErrorState())
                                }
                            }, { data ->
                                   // success
                                    removeObserver()
                                    if (coroutine.isActive) coroutine.resume(data)
                                }
                            })
                        }
                    }

                    Handler(Looper.getMainLooper()).post {
                        useCase.data.observeForever(observer)
                    }

   }
}

```

**Comment by elizarov** [comment]
If you are observing `LiveData`, then you can use ready-to-use extensions provided by Google to use them with coroutines. No need to write your own. Just write `data.asFlow().first()` if you want to get the first observed value.

**Comment by gurveers** [comment]
I do need the second value as well, as second one might be the updated value from API. The problem seems to be that the check isActive isn't working as expected. Nowhere in my code, have I resumed the continuation without this check, still somehow it throws this exception.

**Comment by elizarov** [comment]
@gurveers Any chance you can provide some kind of self-contained reproducer for this problem?

**Comment by gurveers** [comment]
@elizarov unfortunately I can't do that, even reproducing the crash is a lot of effort.

Hopefully the crash log helps you.


Fatal Exception: java.lang.IllegalStateException: Already resumed, but proposed with update android.widget.RemoteViews@7564348
       at kotlinx.coroutines.CancellableContinuationImpl.alreadyResumedError(CancellableContinuationImpl.java:277)
       at kotlinx.coroutines.CancellableContinuationImpl.resumeImpl(CancellableContinuationImpl.java:272)
       at kotlinx.coroutines.CancellableContinuationImpl.resumeWith(CancellableContinuationImpl.java:189)
       at com.TestClass$_testMethod_$1$invokeSuspend$$inlined$suspendCancellableCoroutine$lambda$3$1$2.invoke(_TestClass.java:507_)
       at androidx.lifecycle.LiveData.considerNotify(LiveData.java:113)
       at androidx.lifecycle.LiveData.dispatchingValue(LiveData.java:131)
       at androidx.lifecycle.LiveData.setValue(LiveData.java:289)
       at androidx.lifecycle.MutableLiveData.setValue(MutableLiveData.java:33)
       at androidx.lifecycle.LiveData$1.run(LiveData.java:91)
       at android.os.Handler.handleCallback(Handler.java:873)
       at android.os.Handler.dispatchMessage(Handler.java:99)
       at android.os.Looper.loop(Looper.java:214)
       at android.app.ActivityThread.main(ActivityThread.java:7073)
       at java.lang.reflect.Method.invoke(Method.java)
       at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:494)
       at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:965)

**Comment by elizarov** [comment]
It just means that you called `resume` on the same continuation twice. It is hard to figure out how this might happen just by a snippet of your code.

**Comment by huan-nguyen** [comment]
@elizarov I'm having a similar issue in my app. My question is why coroutine doesn't resume immediately after `Continuation.resume` gets called? That way we'd never get this sort of exception (calling `resume` on an already resumed `Continuation`. I'm certain there is some reasons behind. Interested to hear your guidance.

**Comment by elizarov** [comment]
Calling `resume`, usually, just schedules coroutine for execution in the corresponding coroutine dispatcher.

**Comment by volo-droid** [comment]
@elizarov Can you please look into this issue again? We have a simpler use-case where the issue is reproduced, hopefully it will be useful for you:

```kotlin

import android.app.Activity
import androidx.fragment.app.Fragment
import androidx.lifecycle.LifecycleOwner
import androidx.lifecycle.lifecycleScope
import com.google.android.play.core.review.ReviewManager
import kotlinx.coroutines.CancellableContinuation
import kotlinx.coroutines.suspendCancellableCoroutine
import javax.inject.Inject
import kotlin.coroutines.resume

/**
 * An interface to display a UI requesting user feedback
 */
interface FeedbackRequestUiPresenter {

    /**
     * Show Feedback Request UI to the user
     *
     * @return feedback option selected by the user
     */
    suspend fun showFeedbackRequest(): UserFeedbackResult
}

/**
 * Class that requests a user feedback using a dialog created by [UserFeedbackDialogBuilder].
 */
class FeedbackRequestDialogPresenter @Inject constructor(
    private val fragment: Fragment,
    private val lifecycleOwner: LifecycleOwner,
    private val reviewManager: ReviewManager
) : FeedbackRequestUiPresenter {

    override suspend fun showFeedbackRequest(): UserFeedbackResult =
        suspendCancellableCoroutine { continuation ->
            lifecycleOwner.lifecycleScope.launchWhenResumed {
                showDialog(continuation)
            }
        }

    private fun showDialog(continuation: CancellableContinuation<UserFeedbackResult>) {
        val activity = fragment.requireActivity()
        UserFeedbackDialogBuilder(activity).apply {

            setOnDismissListener {
                continuation.resume(UserFeedbackResult.DISMISS)
            }

            setOnSubmitReviewClickListener {
                requestRating(activity) {
                    continuation.resume(UserFeedbackResult.LEAVE_REVIEW)
                }
            }

            setOnContactSupportClickListener {
                continuation.resume(UserFeedbackResult.CONTACT_SUPPORT)
            }

            setOnAskLaterClickListener {
                continuation.resume(UserFeedbackResult.ASK_LATER)
            }
        }.show()
    }

    private fun requestRating(activity: Activity, onCompleteBlock: () -> Unit) {
        reviewManager
            .requestReviewFlow()
            .addOnCompleteListener { reviewInfo ->
                if (reviewInfo.isSuccessful) {
                    reviewManager
                        .launchReviewFlow(activity, reviewInfo.result)
                        .addOnCompleteListener { onCompleteBlock() }
                }
            }
    }
}

class UserFeedbackDialogBuilder @JvmOverloads constructor(context: Context, themeResId: Int = 0) :
    MaterialAlertDialogBuilder(context, themeResId) {

    private val binding = FeedbackDialogBinding.inflate(context.inflater)

    init {
        setView(binding.root)
    }

    var onDismissListener: DialogInterface.OnDismissListener? = null
        private set

    override fun setOnDismissListener(
        onDismissListener: DialogInterface.OnDismissListener?
    ): MaterialAlertDialogBuilder {
        this.onDismissListener = onDismissListener
        return super.setOnDismissListener(onDismissListener)
    }

    fun setOnSubmitReviewClickListener(listener: (View) -> Unit) =
        binding.submitReview.setOnClickListener(listener)

    fun setOnContactSupportClickListener(listener: (View) -> Unit) =
        binding.contactSupport.setOnClickListener(listener)

    fun setOnAskLaterClickListener(listener: (View) -> Unit) =
        binding.askLater.setOnClickListener(listener)
}
```

```
Fatal Exception: java.lang.IllegalStateException
Already resumed, but proposed with update CONTACT_SUPPORT

kotlinx.coroutines.CancellableContinuationImpl.alreadyResumedError (CancellableContinuationImpl.kt:335)
kotlinx.coroutines.CancellableContinuationImpl.resumeImpl (CancellableContinuationImpl.kt:330)
kotlinx.coroutines.CancellableContinuationImpl.resumeWith (CancellableContinuationImpl.kt:250)
app.sample.feedback.FeedbackRequestDialogPresenter$showDialog$$inlined$apply$lambda$3.invoke (FeedbackRequestUiPresenter.kt:57)
app.sample.feedback.FeedbackRequestDialogPresenter$showDialog$$inlined$apply$lambda$3.invoke (FeedbackRequestUiPresenter.kt:29)
app.sample.feedback.UserFeedbackDialogBuilder$sam$android_view_View_OnClickListener$0.onClick (Unknown Source:2)
android.view.View.performClick (View.java:7192)
com.google.android.material.button.MaterialButton.performClick (MaterialButton.java:992)
FeedbackRequestUiPresenter
```

**Comment by elizarov** [comment]
It looks like you call `resume` twice on the same continuation.

**Comment by Ornolfr** [comment]
@elizarov Is there any way to resume it safely so that exception is not thrown when the continuation is resumed second time?

**Comment by aruke** [comment]
@elizarov How can we avoid calling resume twice on the same continuation?

**Comment by psteiger** [comment]
@aruke a strategy I used to use was to save the continuation in a nullable var, resuming from the var and immediately setting it to null afterwards. Then, if other callbacks eventually try to resume it again, field will be null.

But honestly, it works but it's flaky design. In my opinion you should only suspend and resume if there's a single callback that is guaranteed to always run and run exactly once. For example, GMS tasks and `addOnCompleteListener`.

**Comment by aruke** [comment]
@psteiger Thanks for the suggestion. I agree that the using nullable `var` strategy is flaky.
I was looking in the source and I found one very helpful method `tryResume` in `SafeContinuation` class, unfortunately, it is internal to the coroutine library.

Here's (bare) minimum reproduction of the error.

```kotlin
import android.os.Bundle
import android.view.View
import android.widget.Toast
import androidx.appcompat.app.AppCompatActivity
import androidx.lifecycle.lifecycleScope
import kotlinx.coroutines.launch
import kotlinx.coroutines.suspendCancellableCoroutine
import kotlin.coroutines.resumeWithException

class MainActivity : AppCompatActivity() {

    interface Callback {

        fun onSuccess(done: Boolean)
        fun onFailure()
    }

    enum class State {
        SUCCESS_DONE,
        SUCCESS_NOT_DONE,
        FAILURE
    }

    override fun onCreate(savedInstanceState: Bundle?) {
        super.onCreate(savedInstanceState)
        setContentView(R.layout.activity_main)
        lifecycleScope.launch {

            val result = try {
                suspendTest()
            } catch (error: Error) {
                error.message
            }
            Toast.makeText(this@MainActivity, result, Toast.LENGTH_SHORT).show()
        }
    }

    private suspend fun suspendTest(): String {
        return suspendCancellableCoroutine { continuation ->
            val callback = object : Callback {

                override fun onSuccess(done: Boolean) {
                    // Checking if continuation isCompleted will prevent the error "Already Resumed"
                    if (continuation.isCompleted) {
                        return
                    }

                    if (done) {
                        continuation.resumeWith(Result.success("Success:Done"))
                    } else {
                        continuation.resumeWith(Result.failure(Error("Success:NotDone")))
                    }
                }

                override fun onFailure() {
                    // Checking if continuation isCompleted will prevent the error "Already Resumed"
                    if (continuation.isCompleted) {
                        return
                    }
                    continuation.resumeWithException(Error("Failure"))
                }
            }

            // Two or more State params will replicate the error message
            emulateCallback(callback, State.SUCCESS_DONE, State.SUCCESS_DONE)
        }
    }

    private fun emulateCallback(callback: Callback, vararg state: State) {
        state.forEach {
            findViewById<View>(android.R.id.content).rootView.postDelayed({
                when (it) {
                    State.SUCCESS_DONE -> callback.onSuccess(true)
                    State.SUCCESS_NOT_DONE -> callback.onSuccess(false)
                    State.FAILURE -> callback.onFailure()
                }
            }, 2000)
        }
    }
```

Sorry, it's Android code, but it can be run in any JVM env with some changes.

What I changed was checking if `continuation` `isCompleted` before calling the `resume*` methods.
Also, the reason for `Already Resumed` is the callback is getting called multiple times (late realization)
The callback in the actual code is from a third-party library, and the getting called multiple times condition was deep-buried. 
This is supposed to solve my problem, but now I am wondering if I can dispose of the cancellable continuation after any of the `resume*`  call without triggering an exception. (My understanding is `continuation.cancel()` will not work for this)

**Comment by chizoba** [comment]
Had similar issue. From what I observed, the callback still has the instance of the continuation even if the suspended coroutine may have completed. Hence, the callback can be triggered again and will lead to `resume` being called more than once. You should probably unregister the callback whenever you call `resume` to prevent a crash.

**Comment by aruke** [comment]
In my case, there is no method provided by the third party library for unregistering the callback, so I think checking if the continuation is completed is the best solution I got so far.

**Comment by migmacdev** [comment]
Here are my 2 cents, I had the same issue when I wrapped an API callback into a **suspendCancellableCoroutine**, the callback inside was receiving calls in different methods, therefore cont.resume was being called twice, what I ended up doing was an extension function to only call resume if the **cont** was active, like:
```kotlin
private fun <T> CancellableContinuation<T>.resumeIfActive(value: T) {
    if(isActive) {
        resume(value)
    }
}
```
for my case, this works since I only care about the first call to cont.resume

**Comment by karan4c6** [comment]
Facing similar issue while using RelatimeFirebase Db, here is my code: 

`
    override suspend fun fetchHomeUi(): Result<HomeUiResponseFirebase, NetworkError> =
        withContext(dispatcher) {

            try {

                when (val result = homeUiCallback(firebaseDatabase.reference)) {
                    FirebaseUiResult.Error -> Result.Failure(NetworkError.UnknownError)
                    is FirebaseUiResult.Success -> {
                     
                        val homeModel = result.snapshot.getValue(HomeUiResponseFirebase::class.java)
                        Log.d(TAG, "homeModel: $homeModel")

                        Result.Success(homeModel)
                    }
                }

            } catch (e: Exception) {
                Log.e(TAG, "fetchHomeUi: ${e.message}")
                Result.Failure(NetworkError.UnknownError)
            }
        }

    private suspend fun homeUiCallback(myRef: DatabaseReference) =
        suspendCoroutine<FirebaseUiResult> { con ->

            myRef.addValueEventListener(object : ValueEventListener {
                override fun onDataChange(snapshot: DataSnapshot) {
                    con.resume(FirebaseUiResult.Success(snapshot))
                }

                override fun onCancelled(error: DatabaseError) {
                    con.resume(FirebaseUiResult.Error)
                }
            })
        }`
                
        The above code gives following error whenever the updates are made to Relatime Db on Firebase.
        
        **Crash log:**

>   java.lang.IllegalStateException: Already resumed
>         at kotlin.coroutines.SafeContinuation.resumeWith(SafeContinuationJvm.kt:44)
>         at com.karansyd4.data.home.data.repository.HomeUiRepositoryImpl$homeUiCallback$2$1.onDataChange(HomeUiRepositoryImpl.kt:68)
>         
        
However am able to prevent crash by using suspendCancellableCoroutine, highlighted the differences below in bold.
```

  **suspendCancellableCoroutine**<FirebaseUiResult> { con ->

            // TODO - how to receive multiple callbacks
            myRef.addValueEventListener(object : ValueEventListener {
                override fun onDataChange(snapshot: DataSnapshot) {
                    **if (con.isActive)** con.resume(FirebaseUiResult.Success(snapshot))
                }

                override fun onCancelled(error: DatabaseError) {
                    **if (con.isActive)** con.resume(FirebaseUiResult.Error)
                }
            })
        }
```
