### ISSUE TITLE
Cancel CoroutineScope children and not the CoroutineScope itself

### ISSUE THREAD

**Issue by kevincianfarini** [Kotlin/kotlinx.coroutines#1878]
Right now I've run into a situation on Android where I need to subscribe and unsubscribe to view events repetitively. I have my view events bound to a Flow, and launch them as follows. 

```kotlin
private fun subscribeToSpinner(spinner: ValidatedSpinnerComponent) {
    spinner.changes.onEach { ... }.launchIn(lifecycleScope)
}
```

When I unsubscribe from these events, I was originally doing `lifecycleScope.cancel`. This was cancelling the whole scope and not just the children, which is to be expected. 

It's not intuitive for me to wrap them all up into a single `coroutineScope { ... }` and cancel that because they happen at different places. 

So, the workaround for this in my codebase is to do the following:

```kotlin
lifecycleScope.coroutineContext[Job]!!.children.forEach { it.cancel() }
```

I was surprised to see there was no out of the box way to do child cancellation, and am wondering if there's a reason for that. If not, I would be willing to make a PR for it. 

I am proposing that we include `CoroutineScope.cancelChildren`.

**Comment by kevincianfarini** [comment]
I also found out that you can do the following:

```kotlin
CoroutineScope.coroutineContext[Job]!!.cancelChildren()
```

That's still not intuitive in my opinion.

**Comment by elizarov** [comment]
So, are you asking for `CoroutineScope.cancelChildren()` extension of you have something else in mind?

**Comment by kevincianfarini** [comment]
`CoroutineScope.cancelChildren` would be good :)

**Comment by elizarov** [comment]
Ah, here's the problem. We use `CoroutineScope` as a receiver in all coroutine builder lambdas, so when you write `coroutineScope { .... }` then inside of the block you get access to all the extension functions on `CoroutineScope`. If we add `cancelChildren()`, then it will be become valid there, too. But, unlike builders like `launch`, it does not look called for nor clear. It looks like `coroutineContext.cancelChildren()`, though longer, but is more explicit.

**Comment by kevincianfarini** [comment]
> But, unlike builders like launch , it does not look called for nor clear.

 I'm not sure I understand that bit. 

However, can't that argument be applied to `cancel` as well? What's stopping the user from doing the following? 

```kotlin
val scope = coroutineScope {
    ...
    cancel()
}
```

**Comment by elizarov** [comment]
In general, we try to limit extensions on `CoroutineScope` to avoid confusion over what's happening. We talked this through when adding `CoroutineScope.cancel()`. The `cancelChildren()`, on the other hand, seem to be quite rarely needed to warrant this kind of scope pollution.

**Comment by kevincianfarini** [comment]
That's fair! Thanks for entertaining the idea.
