### ISSUE TITLE
Coroutines confined to the UI thread – example is missing

### ISSUE THREAD

**Issue by nil2l** [Kotlin/kotlinx.coroutines#188]
This example seems to be empty:
https://github.com/Kotlin/kotlinx.coroutines/tree/master/ui/kotlinx-coroutines-android/example-app

Sample:
```
launch(UI) {
    user = service.getUser().execute()// some sync network request, need non-UI thread
    textView.text = user.name// this need to be called in UI thread
}
```

1. Is it correct usage? Will UI thread be blocked? Or should I use async/await?
1. If not, how does coroutine determine what to run UI thread and what in (which??) non-UI?

**Comment by elizarov** [comment]
This example is a template for the corresponding guide: https://github.com/Kotlin/kotlinx.coroutines/blob/master/ui/coroutines-guide-ui.md
