### ISSUE TITLE
Module kotlinx-coroutines-play-services updated but I actually need to still use the annotations

### ISSUE THREAD

**Issue by gastsail** [Kotlin/kotlinx.coroutines#1893]
I have updated `kotlinx-coroutines-play-services` to the latest release **1.3.5** 

`implementation 'org.jetbrains.kotlinx:kotlinx-coroutines-play-services:1.3.5'`

Now, since 1.3.0 these annotations can be omited from our code

> All Flow API not marked with @FlowPreview or @ExperimentalCoroutinesApi annotations are stable and here to stay.

But for some reason, not having the annotation in my class is still asking me to annotate my method/class with the `@ExperimentalCoroutinesApi` annotation for `callbackFlow`

Since it is now stable, I don't want to use the annotation anymore in my classes, is this a separated module that needs to be updated?

I don't have the core coroutines for kotlin, just the module, as I can see in [Maven](https://mvnrepository.com/artifact/org.jetbrains.kotlinx/kotlinx-coroutines-play-services), the same releases for the core `kotlinx.coroutines `also applies to this module, so I don't know why the annotation is still needed after updating.

**Comment by elizarov** [comment]
`callbackFlow` is still experimental: https://kotlin.github.io/kotlinx.coroutines/kotlinx-coroutines-core/kotlinx.coroutines.flow/callback-flow.html
Does it answer your question?

**Comment by gastsail** [comment]
Thanks !

**Comment by gastsail** [comment]
Thanks !
