### ISSUE TITLE
`MutabilityException` when using mt-native `Flow`

### ISSUE THREAD

**Issue by ScottPierce** [Kotlin/kotlinx.coroutines#1895]
I'm using Kotlin 1.3.71, Gradle 6.2.2, and Coroutines `1.3.5-native-mt`.

I’m encountering a `MutabilityException` when using the `native-mt` version of coroutines with Flow. I’ve been stuck on this all day and it doesn’t make a ton of sense to me. I’ve re-created the issue on a small scale in the form of tests, one with the exception, one without. It’s difficult to tell if I’m being dense, or if there is a bug that I’m hitting.

For some reason the tests never complete when both are in the file. If you comment out `test2`, run `test1`, let it complete, and then check the stdout from the test, you’ll see the error. `test1` has the exception. If you run `test2`, you'll see that it doesn't. `test1` just wraps `test2`'s suspend function, and offers a callback. Also the exception is coming from deeper in the callstack.

Here is a gist with a test that will reproduce:
https://gist.github.com/ScottPierce/0e687021f34d779708d1f32bfc81e8e2

**Comment by elizarov** [comment]
What you are doing in this example in that you are sending a lambda over a channel to another thread:
```
        channel.send { // <---------- send a lambda
            emitAll(it.getData())
        }
```
When you do that, the whole closure of this lambda is captured and frozen. But this closure also contains `FlowCollector` (the object on which you call `emitAll`) which is not shareable object. `FlowCollector` cannot be shared with other threads. You can `emit` to a collector only from the same thread (context) according to "context preservation" rules of the flow. 

You should use `channelFlow { ... }` which gives you a shareable `Channel` that you can use to send data from other threads.

**Comment by ScottPierce** [comment]
But I'm doing a `flowOn(context2)`, which is the same thread the channel is acting on. Since they are on the same thread, I didn't think a freeze would happen. I've observed this non-freezing effect when the same thread is used in other situations.

Also I'm getting two cases:
1. When both tests are active and not commented out - the tests never complete
2. If I comment out `test2` eventually `test1` will complete, but the test is successful. Why is the exception eaten? Why doesn't it crash the test? I observed the same behavior in an iOS App.

**Comment by elizarov** [comment]
All that matters here is that a `channel` that you use is shared between threads (frozen). It is frozen because you freeze your instance of `AsyncExample` that contains a reference to a channel. Thus, everything that is sent over this channel is shared (frozen).

In this particular case, it goes deeper that than. Even if you remove that freeze it still will not work, because the `Job` that collects that data is shared due to a long sharing chain and when you `send` in the context of a shared job it would also freeze the channel. I'm not sure if it is a bug or not.

**Comment by ScottPierce** [comment]
I swapped my code to use `channelFlow` now, but now on `channel.send` and `channel.close` I'm getting warnings that say `Non-applicable call for builder interfaces`. Should I be concerned about that?

```Kotlin
override fun getExperiments(
    appName: String,
    userIdentifier: String,
    experiments: List<Experiment>,
    mode: AbTestMode
): Flow<List<ExperimentGroup>> = channelFlow {
    delegateChannel.send { base ->
        try {
            base.getExperiments(appName, userIdentifier, experiments, mode).collect {
                channel.send(it)
            }
        } catch (e: Exception) {
            channel.close(e)
        }
    }
}
```

**Comment by ivakub** [comment]
@ScottPierce Can you please check this warning with 1.4-M1? We fixed some cases with this warning in this Kotlin version. Anyway, it would be helpful to create an issue [here](http://kotl.in/issue) and attach your project (you can set visibility to `jetbrains-team`) or self-contained code example.

**Comment by ScottPierce** [comment]
Things seem to be working now for me. I've filed https://youtrack.jetbrains.com/issue/KT-37958 because I think the inconsistencies I'm seeing might be bugs. The code example I've provided there is self-contained.

Thanks for your help guys!
