### ISSUE TITLE
Creating callbackFlow / flow as an instance and reusing it in multiple places

### ISSUE THREAD

**Issue by Varsha-29** [Kotlin/kotlinx.coroutines#1897]
Similar to channels and broadcast channels, can flows also be instantiated and reused at multiple places? 

General usage of creating flows is wrapping the logic to emit the data inside flow's body and is returned. 
Snippet : 
```
fun listenToDataChanges() : Flow<T>
{
return flow {
            dataSource.querySomeInfo()?.consumeEach { 
                data->
                if (someCondition) {
                    emit(data)
                }
            }
        }
}
```
Everytime listenToDataChanges() is called, a new flow instance is created and multiple subscriptions would be made. Instead is it possible to create and reuse the instance to avoid multiple subscriptions?

**Comment by elizarov** [comment]
This is planned to be provided via some-kind of `share` operator in the future. Please, follow #1716
