### ISSUE TITLE
Optimize `runBlocking` and `EventLoop` implementations

### ISSUE THREAD

**Issue by elizarov** [Kotlin/kotlinx.coroutines#190]
* `EventLoopBase` implementation class should allocate both `queue` and  `delayed` lazily, moreover, a queue shall not be allocated as long as there is at most one queued task (optimization that is similar to `JobSupport`)
* `DispatchedContinuation` shall extend `QueuedTask`, so that common case of `EventLoop` usage does not involve creation of objects at all.
* Consider providing a reusable version of `EventLoop` implementation, so that performance-sensitive code can create a single instance that is reused for multiple sequential invocations of `runBlocking`.

**Comment by fvasco** [comment]
> multiple sequential invocations of runBlocking

Should be a reusable `EventLoop` saved in a `ThreadLocal` by `runBlocking`?

**Comment by elizarov** [comment]
No. Saving small object `ThreadLocal` is usually counter-production. Access to `ThreadLocal` is typically more expensive than allocation/collection of small objects. TheadLocal pooling is usually beneficial only for very large objects.

**Comment by fvasco** [comment]
The current EventLoop implementation is unusable in the Netty thread pool.
I don't know if it is possible to do it more generic.

**Comment by elizarov** [comment]
Can you clarify, please? Why would you need `EventLoop` implementation in Netty, given that Netty has its own event loop?

**Comment by fvasco** [comment]
Hi @elizarov,
you are right.A sample Netty use case is the #155, more in general a listener in not always invoked in the same thread.
I suspect the current implementation cover a small set of use case.

**Comment by elizarov** [comment]
So why is that unusable with Netty?

**Comment by fvasco** [comment]
Hi @elizarov,
If I have understand good, the current implementation enforce to use always the same thread for the `EventLoop`.
Netty uses a thread pool to invoke channel's listener.

I want to use a Kotlin actor to consume Netty events, so I must use `runBlocking` to send events to actors.
To improve performance I should cache the `EventLoop` and use a single instance to send all Netty events, unfortunately Netty uses a thread pool to invoke the listener but the invocation thread can be different for two event.

Therefore, if I understand good, I cannot cache the `EventLoop` and I must use a plain `sendBlocking` to send each event.

**Comment by tr8dr** [comment]
HI, I came across this posting.  I am also trying to figure out how to send messages to an actor outside of a coroutine.   I am receiving events from non-coroutine code at fairly high frequency and would like to pass these on to an actor.   I am concerned with the cost of doing:
```
runBlocking {
    actor.send (<msg>)
}
```
Is there a better and more performant way to send events from an "external" source?

**Comment by fvasco** [comment]
Take a look to `sendBlocking`

**Comment by qwwdfsad** [comment]
@tr8dr 
You can always start with non-suspending `offer` first and fallback to `runBlocking` + `send` only when offer failed

**Comment by tr8dr** [comment]
@fvaso thanks for the pointer (I had to update my version of the coroutine library to see this function).    @qwwdfsad Interesting, I assume ```offer``` would be better suited for high-frequency events if there is sufficient buffer size than ```sendBlocking```?     Any idea on the performance difference between these two?

**Comment by fvasco** [comment]
@tr8dr 
for your use case you can consider to send large buffer using `sendBlocking` and then flatten the channel

```kotlin
fun <E> ReceiveChannel<Iterable<E>>.flatten(): ReceiveChannel<E> = produce(context = Unconfined, capacity = 0) {
    this@flatten.consumeEach { iterable ->
        iterable.forEach { channel.send(it) }
    }
}
```

**Comment by tr8dr** [comment]
@fvasco that would be prudent if I had a queue of these to send.  Unfortunately handing off events as they come at (unpredictable) arrival times.  Minimizing latency is fairly important.

**Comment by fvasco** [comment]
@tr8dr are right and I agree with you, but I don't know your use case.
If your code is after a batch elaboration then it is easy to send all elements at once (so use the `flatten` operator), otherwise `sendBlocking` is more appropriate.

`offer` is a non-blocking lightweight operator, unfortunately sometimes it fails (except for conflated/unlimited channels), `runBlocking/send` is more reliable.
`sendBlocking` works always without issues.

**Comment by qwwdfsad** [comment]
@tr8dr in general `sendBlocking` and `offer` have the same performance if `send` doesn't suspend (aka there is enough buffer capacity), because internally it has the same (`if (!offer()) { runBlocking {...}}`) check.

For cases when channel capacity is saturated you should measure your performance on your specific workload because numbers out of thin air ("on my artificial benchmark sendBlocking is two times slower") are mostly useless
