### ISSUE TITLE
Cancel child job when parent is cancelled

### ISSUE THREAD

**Issue by TooLazyy** [Kotlin/kotlinx.coroutines#1907]
Hi. I have a question.
Let's say I have 1 flow which is listening for updates from a websocket and pushing changed into a local db. And another one listening for db update.
I would like to combine em in such a way.
```
suspend fun listnerForUpdates(): Flow<> {
    remoteFlow.collect {
        db.save(it)
    }
    db.asFlow() //pseudo
}
```
The problem is: I can make a remote flow running, but `db.asFlow()` never executed coz `remoteFlow` still working. Or I can make the remote and local one running, but when I stop the job started with `launch { listnerForUpdates() }`, the remote on is still working.
Of if I cancel entire scope, it works.
I'm not sure `flatMapMerge` is the rescue.
For sure I can launch two separate flow via `launch {}`, but it smells.
So is there any way to combine flows the way I wish? (maybe creating a new context somehow)?

**Comment by elizarov** [comment]
First of all, the general rule is that you should avoid function that are both `suspend` and return a flow. They are confusing. As to your question, you can try something like this:

```
suspend fun listnerForUpdates(): Flow<T> = channelFlow { // creates a flow-limited scope
    // concurrently lanch a job to save to db
    remoteFlow.onEach { db.save(it) }.launchIn(this)
    // send everything from db into this flow
    db.asFlow().collect { send(it) }
}
```

Currently, `channelFlow` is the only convenient concurrency-equipped primitive that flow provides. You use-case is good one for somewhat a more tailored solution.

**Comment by TooLazyy** [comment]
yeah. ty, it works.
