### ISSUE TITLE
Launching multiple flows when a parent flow emits. 

### ISSUE THREAD

**Issue by rishabh-kohli** [Kotlin/kotlinx.coroutines#1916]
I have this code.
```
var scope: CoroutineScope? = null
parentFlow
		.onEach { parentValue ->
			scope?.cancel() // Cancel flows from last time.
			scope = CoroutineScope(Dispatchers.Default) // Scope for new flows
			(1..3).forEach { subValue -> // Loop for each sub value. Will set a new flow
				getFlowFor(parentValue, subValue)
						.onEach {
							processResult()
						}
						.launchIn(scope!!) // Start in our scope which we can cancel
			}
		}
		.onCompletion { scope?.cancel() } // viewModelScope is getting cancelled
		.launchIn(viewModelScope)
```
Is there any inbuilt function which can achieve this? Without having to declare a new scope?
And if it isn't, should the API contain such a function?

**Comment by elizarov** [comment]
I'm not sure I correctly understand what you are trying to achieve, but you can try `mapLatest` which cancels the previous work on each new emission and use `withContext` scope to have multiple sub-flows launched concurrently: 

```kotlin
parentFlow.mapLatest { parentValue -> 
    withContext(Dispatchers.Default) { // this: CoroutineScope in which we launch sub-flows
        (1..3).forEach { subValue ->
            getFlowFor(parentValue, subValue).onEach { processResult() }.launchIn(this)
        }
    }
}.launchIn(viewModelScope)
```

**Comment by rishabh-kohli** [comment]
That works for my use case.
Cleans up the code some.
But what I was considering was writing a transform function which returns a List of Flows.
Then the entire list can get cancelled with the mapLatest's new emission.

**Comment by elizarov** [comment]
There's the whole family of `xxxLatest` functions in `kotlinx.coroutines` that cancel their previous work on new emissions. The most low-level of them being `collectLatest` and `transformLatest`. Take a look, please.

Do you have any other questions?

**Comment by rishabh-kohli** [comment]
Nope. 
Thank you. :)
