### ISSUE TITLE
broadcastIn() does not emit a value to all consumers

### ISSUE THREAD

**Issue by ReginFell** [Kotlin/kotlinx.coroutines#1917]
I am experiencing very strange behavior when use `broadcastIn()`,
I have the following code 
```kotlin
 val channel = flowOf("Test value").conflate().broadcastIn(GlobalScope)

 launch { channel.consumeEach { println("First consumer") } }
 launch { channel.consumeEach { println("Second consumer") } }
 launch { channel.consumeEach { println("Third consumer") } }
```
I expected that all consumers will receive "Test value", but actual log is 

> First consumer

Adding a small delay after flowOf solves the issue
```kotlin
   val channel = flowOf("Test value").onEach { delay(1L) }.conflate().broadcastIn(GlobalScope)

   launch { channel.consumeEach { println("First consumer") } }
   launch { channel.consumeEach { println("Second consumer") } }
   launch { channel.consumeEach { println("Third consumer") } }
```

> First consumer
> Second consumer
> Third consumer

Do you have any good ideas on how it can be fixed without introducing 1L delay? Thanks

**Comment by elizarov** [comment]
The way that `broadcastIn` works is that when the incoming flow is closed, then it stops working, regardless of the `conflate()` operator that is used before it. It is defined for mostly "never-ending" flows. However, the `flowOf(...)` is a flow that emits all listed elements and immediately closes. 

What is you use-case for `broadcastIn`. What were you trying to achieve?

**Comment by ReginFell** [comment]
So, I am trying to achieve `shareIn` from. https://github.com/Kotlin/kotlinx.coroutines/issues/1261

```kotlin
fun observe(userId: UserId?): Flow<UserInfo>{
when(userId) {
null -> flowOf(null)
else -> userInfoRepository.observe(userId)
}
.conflate().broadcastIn(scope).asFlow()
```

And in case if the userId is not null everything works, but if it is null then the value is broadcasted only to one collector.

**Comment by qwwdfsad** [comment]
Obsolete in the favour of `shareIn`
