### ISSUE TITLE
How to detect if a `CoroutineDispatcher` is suspended due to a delay?

### ISSUE THREAD

**Issue by ZakTaccardi** [Kotlin/kotlinx.coroutines#1919]
I want to be able to inform `Espresso` that it should not consider itself idle when there is an active coroutine with a specific name that is suspend due to a `delay(..)`.

```kotlin
idlingDispatchers.reportNotIdleWhileCoroutineIsDelayed(
  CoroutineName("my_coroutine")
)
```

One way to achieve this would be to inject a custom `delay(..)` function, but I would prefer to avoid that to keep production code simple.

The difficulty I'm having is that I want to leverage the default behavior of `DefaultDelay` (which is `internal`) unless I am attempting to monitor a specific `CoroutineName` for idle.

**Comment by elizarov** [comment]
You can inject this behavior in a custom `CoroutineDispatcher` implementation by implementing a `Delay` interface, in which case the `delay(...)` function delegates to it.
