### ISSUE TITLE
Coroutine behaviour inconsistent in Android. UI getting updated from non UI Thread

### ISSUE THREAD

**Issue by MichaelChand** [Kotlin/kotlinx.coroutines#1924]
### Premise:
Create Coroutine in MainActivity.kt with context Dispatchers.IO
Update TextView.
Text View Updates.

Expected Behavior: Must throw exception and do not update Text View because should not update UI from a non UI thread.
Actual result: Updates the UI, no Exception is thrown.
Example:
```
CoroutineScope(Dispatchers.IO).launch {
    tvResult.text = "Some sample text" //This works when it should not
}
```

### Other observations
In activity_main.xml, for the TextView leave "android:layout_height=" as "wrap_content" 
Set  "android:layout_width= to "wrap_content"
In MainActivity.kt inside onCreate method create an onClick Listener and add the above Coroutine Code example:
```
btnSubmit.setOnClickListener {
        CoroutineScope(Dispatchers.IO).launch {
            tvResult.text = "Some sample text"
        }
}
```
In this circumstance Coroutine does not behave as it should when layout_width is "match_parent" but does work correctly if layout_width is "wrap_content"

How to replicate:
Using: Android Studio version 3.6.2. Kotlin 1.3.72. May produce same effect on earlier versions as well.

1. Create new Android Studio project
2. Select Empty Activity.
3. Select Language: Kotlin
4. Select SDK Version. eg API 29:Android 10.0 (Q)
5. Let the build complete.
6. Add TextView to activity_main.xml. Set id to tvResult. Leave default text
7. Set android:layout_width="match_parent"
8. Set android:layout_height="wrap_content"
9. Add Button to activity_main.xml. Set id to btnSubmit. Set text to "Submit"
10. Adjust Constraints so both TextView and Button is visible at run time in emulator/physical device. Layout can be Constraint or Linear

Add Coroutine libraries to dependencies block of build.gradle app file:
implementation 'org.jetbrains.kotlinx:kotlinx-coroutines-android:1.3.5'
implementation 'org.jetbrains.kotlinx:kotlinx-coroutines-core:1.3.5'

In MainActivity.kt

1. Go to the onCreate method
2. Inside the method and after setContentView(...) add the following Coroutine code:

 ```
 btnSubmit.setOnClickListener {
         CoroutineScope(Dispatchers.IO).launch {
             tvResult.text = "Some sample text"
         }
 }
```

3. Add appropriate imports eg import kotlinx.coroutines.* to the file.
2. Run the application in emulator or device.
3. Click Submit button.
4. The TextView tvResult will update with "Some sample text" and no exception will be thrown. This is the bug as it is incorrect behavior because TextView is getting set from a worker thread which should not be permitted.

### Only condition where Coroutine appears to work correctly as it should

1. Under the above conditions (i.e Coroutine inside setOnClickListener) Set android:layout_width="wrap_content"
 NOTE: layout_width is changed from "match_parent" to "wrap_content".
3. Run application in emulator or device.
4. Click Submit.
5. TextView tvResult does not update and an exception is thrown. This is correct behavior.

**Comment by elizarov** [comment]
Thanks for report, but this is not related to coroutines. Android does not consistently check for UI thread so sometimes you get exception on trying to touch UI fron non-UI thread, sometimes you do not. See thing SO question, for example: https://stackoverflow.com/questions/44890807/setting-text-on-textview-from-background-thread-anomaly There are a lot of similar ones.

**Comment by MichaelChand** [comment]
Hi elizarov,
Thank you for providing the link to a similar issue. I have looked through that and others since. While I concede that the title of my report makes the problem seem familiar there is one difference in the two problems. 
The problem the link you provided and others I have searched talk about the issue that happens sometimes. Each one working as they should once a delay is injected through suspending the thread for some time, usually 1000 mS.

However if you follow the steps i have provided, the problem occurs every single time without a miss. Therefore this isn't a "sometimes get exception, sometimes you dont" situation. This is a situation where you ever get an exception even if you suspend the worker thread for 1000 mS and even 5000 mS. 

As a result of updating UI from a worker thread every time without fail opens this up for introduction of bugs in published applications. That would be unsatisfactory behavior from this system.

**Comment by elizarov** [comment]
It is still not related to the coroutines. `setText` on Android simply does not perform a consistent check for UI thread. You can print the currently running thread to confirm, that, indeed, the code works from the background thread. Sorry, but there's nothing we can fix in `kotlinx.coroutines` to fix this specific Android feature.
