### ISSUE TITLE
kotlinx-coroutines transitive deps are bringing in 1.3.70 stdlib unless manual exceptions written

### ISSUE THREAD

**Issue by jnorthrup** [Kotlin/kotlinx.coroutines#1925]
I am assuming this is not intended but intellij shows how 1.3.70 artifacts are brought in as deps of at a minimum maven projects.   the workaround is of course to make maven exclusions.

I am working on 1.4-M1 and I am hoping for parity in coroutines libs soon!

![image](https://user-images.githubusercontent.com/73514/79729460-b4440880-8319-11ea-8aff-1e02006bea22.png)

**Comment by elizarov** [comment]
Please, use version `1.3.5-1.4-M1`.

**Comment by jnorthrup** [comment]
Could not find artifact org.jetbrains.kotlinx:kotlinx-coroutines-core:pom:1.3.5-1.4-M1 in bintray.kotlin.eap (https://dl.bintray.com/kotlin/kotlin-eap)
