### ISSUE TITLE
Catched Exception in Flow cancels processing of following elements

### ISSUE THREAD

**Issue by spyro2000** [Kotlin/kotlinx.coroutines#1928]
Hi there,

I am playing around with Kotlin Flow to prepare some basic training material. I created a simple example to make some tests regarding exception handling inside of Kotlin Flows: 

```kotlin
@OptIn(ExperimentalCoroutinesApi::class)
suspend fun main() = coroutineScope {
    val myDuckFlow = duckFlow()
    myDuckFlow
            .onEach {
                println("Checking age")
                if (it.age < 18) throw IllegalArgumentException("Sorry ${it.name}! Adults only!")
            }
            .map {
                println("Adding family name")
                it.copy(name = it.name + " Duck")
            }
            .catch { println("Error: ${it.message}") }
            .collect {
                println("Collect")
                println(it)
            }
    println("Done!")
}

fun duckFlow(): Flow<Duck> = flow {
    println("Emitting Donald")
    emit(Duck("Donald", 35))
    
    println("Emitting Huey")
    emit(Duck("Huey", 7))

    // following code is never executed
    println("Emitting Daisy")
    emit(Duck("Daisy", 32))
}

data class Duck(val name: String, val age: Int)
````
Output:

````
Emitting Donald
Checking age
Adding family name
Collect
Duck(name=Donald Duck, age=35)
Emitting Huey
Checking age
Error: Sorry Huey! Adults only!
Done!
````

As you can see, the processing just stops after the first (catched!) exception which cancels the whole operation! Poor Daisy is not emitted/processed at all. I was under the impression, that `.catch()` should prevent this, allowing to catch individual errors and continuing with the other elements?

Is this intended behavior or could this be some kind of bug? (If not how to do this right way)?

Thank you.

**Comment by elizarov** [comment]
Yes. This is the intended behavior. The upstream flow in your example _has completed with exception_. The `catch` operator allows to handle this exception, but the upstream is already complete. The only thing you can do is to _restart_ it using `retry` operator, but you cannot make it "continue".

**Comment by spyro2000** [comment]
Thanks for your answer. But I just don't get it. I'm giving up on that. It's just too confusing for me. :(

Just don't get why the catch() isn't preventing this exception from bubbling up and killing the whole Flow instead. Isn't that the acual purpose of a catch and has been for many years now?

**Comment by spyro2000** [comment]
Ok, thanks for your answer. But what's the (correct) way then to catch exception thrown when processing individual elements then (given that _catch_ doesn't prevent the whole flow to break)...? That's a little bit - confusing :(

**Comment by dave08** [comment]
I had the same surprise, but in the end, I used a sealed class with a Failure data class containing the exception instead of throwing (or just try/catch it and return that Failure class if you absolutely need the exception), and checkk out Roman's recent article on Medium about using exceptions in Kotlin....

**Comment by spyro2000** [comment]
Hi @dave08,

it seems not possible to _really_ catch any exception than with a `.filter( try-catch)` construct here. So I really don't get the whole point about avoiding them in the first place.

**Comment by dave08** [comment]
@spyro2000 An exception in a flow is really a case that is more of a fatal, non-recoverable type. `catch` basically gives the opportunity to send extra emission/s on such a type of failure... You need to try/catch where the exception is actually thrown for a non-fatal exception, and replace it with some kind of emission that reports such a failure. See this article for more: https://medium.com/@elizarov/kotlin-and-exceptions-8062f589d07 .

**Comment by dave08** [comment]
Also, in Rx all the onError operators actually seem to react the same way except for `onExceptionResumeNext`, I wonder if it might be nice to have some kind of parameter to `catch` that would actually do that?

**Comment by spyro2000** [comment]
Sorry, I still don't see why an "catched" exception thrown when processing a single element should break the whole flow... So yes, something like catchAndContinue() would be great.

**Comment by MrPaperMoon** [comment]
Why is closed? 
It's not possible to set SuperviserJob or setup flow to behavior to don't cancel themself after exception. All u got it's: get cover every coroutine by try/catch and handle before and some possible way handle it?
It's be nice, to make something like supervisorScope method, but not like: shouldThrow { true }

**Comment by spyro2000** [comment]
Hi MrPaperMoon,

the only think, that works for me, is a pattern linke this:

```kotlin
duckFlow()
        .filter { // <--- .filter with try/catch returning false on exception
            try {
                checkAge(it)
                true
            } catch (e: IllegalArgumentException) {
                println("Error: $e.message")
                false
            }
        }
        .map {
            println("Adding family name")
            it.copy(name = it.name + " Duck")
        }
        .catch { println("(Complete) flow cancelled: ${it.message}") }
        .collect {
            println("Collect")
            println(it)
        }
```` 

Output:

````
Emitting Donald
Checking age
Adding family name
Collect
Duck(name=Donald Duck, age=35)
Emitting Huey
Checking age
Sorry Huey! Adults only!
Emitting Daisy
Checking age
Adding family name
Collect
Duck(name=Daisy Duck, age=32)
Done!
````

**Comment by MrPaperMoon** [comment]
@spyro2000 nice, it's possible to use it in my case?:
```
    override suspend fun invoke(input: I): Flow<O> {
        val channelFlow = channelFlow<O> {
            launch {
                val value: O = getFirst()
                send(value)
            }

            launch {
                val value: O = getSecond()
                send(value)
            }

            launch {
                val value: O = getLast()
                send(value)
            }
        }

        return flow {
            val merge: Merge<O>

            channelFlow
                .collect {
                    merge.merge(it)
                    emit(merge)
                }
        }
    }
```
