### ISSUE TITLE
[QUESTION] about kotlinx-io and kotlinx-coroutines-io

### ISSUE THREAD

**Issue by revintec** [Kotlin/kotlinx.coroutines#193]
Hi, I would like to exchange data between JVM and JS, kinda like a binary JSON format
I found kotlinx-io, it supports both JVM and JS, and I also found kotlinx-coroutines-io

I'm confused about the two, so my question is:
1) do kotlinx-coroutines-io have a JS version? I used to find broken links in the kotlinx-coroutines documentation, but it seems that they've been removed in the latest version, are they deprecated?
2) as they are related, which one should I use for the long run, will one be replaced by the other?

**Comment by elizarov** [comment]
Bith `kotlinx-io` and `kotlinx-coroutines-io` are still work in progress. The plan is that the former provide basic cross-platform abstraction for blocking or in-memory input/output, while the former provides coroutine-based asynchronous IO. Both are in a flux and are under active developer, neither is ready for wide use. There is a plan to provide JS version for both of them when they are ready.
