### ISSUE TITLE
CompletableFuture is API level 24 and above, considered including a backport?

### ISSUE THREAD

**Issue by tschellenbach** [Kotlin/kotlinx.coroutines#1930]
This approach looks really nice: https://github.com/Kotlin/kotlinx.coroutines/blob/master/integration/kotlinx-coroutines-jdk8/README.md#example

A backport of completableFuture would make it work for API level 21. Is this on your roadmap?

**Comment by qwwdfsad** [comment]
Could you please elaborate on what do you mean by API level 21 backport?

**Comment by tschellenbach** [comment]
something like this: https://github.com/stefan-zobel/streamsupport/blob/master/src/cfuture/java/java8/util/concurrent/CompletableFuture.java

**Comment by qwwdfsad** [comment]
No, this is not something we are planning or willing to do. Our goal is to provide a clear integration layer with `java.util.concurrent.CompelteableFuture` for users that rely on Java 8 API
