### ISSUE TITLE
Subscribing to multiple flow in one lifecycleScope.launch {} does not work

### ISSUE THREAD

**Issue by zakrodionov** [Kotlin/kotlinx.coroutines#1933]
The subscriber flow test2 does not receive data, but if you transfer it to another ifecycleScope.launch {}, it will work correctly

```
lifecycleScope.launch {
            viewModel.test1
                .collect {
                    Log.d("test_lifecycleScope", it)
                }

            viewModel.test2
                .collect {
                    Log.d("test_lifecycleScope", it)
                    //not emitted
                }
        }
```

version coroutines 1.3.5
version lifecycle 2.3.0-alpha01

**Comment by elizarov** [comment]
It is so by design. I highly recommend reading an official reference to get familiar with the Flow API philosophy: https://kotlinlang.org/docs/reference/coroutines/flow.html There is "launching flows" section there, that covers your needs of having multiple streams concurrently collected.
