### ISSUE TITLE
JS: Use window.setMessage instead of setTimeout for coroutines inside the browser

### ISSUE THREAD

**Issue by elizarov** [Kotlin/kotlinx.coroutines#194]
In the modern browsers `setTimeout` is limited to around 4ms, so coroutines communicating between each and suspending/resuming would have a very slow progress, because coroutine resumptions are currently scheduled using a zero-internal `setTimeout`.

See the following blog post: https://dbaron.org/log/20100309-faster-timeouts

**Comment by bashor** [comment]
@elizarov 
Looks like `Promise.resolve().then(...)` and `MessageChannel` are better solution to fix this.
The related micro-benchmark: https://esbench.com/bench/55d4d44e2efbca1100bf7251

I believe that `Promise.resolve().then(...)` will be faster than `setTimeout` on Node.js too. But `process.nextTick` probably will be the fastest solution on Node.js.
