### ISSUE TITLE
Dispatchers.Main.immediate have different behavior on Android and unit test

### ISSUE THREAD

**Issue by shiehnpin** [Kotlin/kotlinx.coroutines#1948]
Hi, I'm new to coroutine. I run the code on unit testing and android app and got different results.

    class CoroutineTest{
        
        private val mainThreadSurrogate = newSingleThreadContext("UI thread")

        @Before
        fun setUp() {
            Dispatchers.setMain(mainThreadSurrogate)
        }

        @After
        fun tearDown() {
            Dispatchers.resetMain() // reset main dispatcher to the original Main dispatcher
            mainThreadSurrogate.close()
        }

        @Test
        fun test()  = runBlocking<Unit>{
            launch(Dispatchers.Main) {
                launch (Dispatchers.Main.immediate) {
                    println("1")
                }
                println("2")
                launch (Dispatchers.Main) {
                    println("4")
                }
                println("3")
            }
        }
    }

On Android I got 1 ->2->3->4, however, the result on unit testing is 2->3->1->4. It seems `immediate` is not working properly. Is this normal behavior? Or I misunderstand some concepts?

**Comment by elizarov** [comment]
The `immediate` dispatcher's behavior is specific to real UI dispatchers (like Android) and is not currently implemented by the `newSingleThreadContext` dispatcher. I'll leave it open as feature request.

**Comment by qwwdfsad** [comment]
Closing as "won't fix": the demand on this feature is quite low and doesn't outweigh cons of implementing `Dispatchers.Main`-specific API in the general-purpose dispatchers for the sake of `setMain`
