### ISSUE TITLE
In android,the art runtime Underlying implementation is thread,what is different between use coroutines and thread?

### ISSUE THREAD

**Issue by ljzyljc** [Kotlin/kotlinx.coroutines#1949]
In android,the art runtime Underlying implementation is thread,what is different between use coroutines and thread?
If i create a coroutines in main-thread，the art runtime final create a java-thread? 
If i create five coroutines in a java-thread(named "moon")，the art runtime final create a executor and run five task(runnable)? and the art runtime now hava a executor, a java-thread(named "moon")，a main-thread?
Is it right? and if is not right , what will happened?

**Comment by elizarov** [comment]
There's are lots of materials on the web about the coroutine basics. You can start with the official general guide on coroutines here 
https://kotlinlang.org/docs/reference/coroutines/coroutines-guide.html 
or a guide on using Android with coroutines here 
https://developer.android.com/kotlin/coroutines 
If you have any questions the best place to ask them would be https://stackoverflow.com
