### ISSUE TITLE
runBlocking is missing in common module

### ISSUE THREAD

**Issue by JonasFranzDEV** [Kotlin/kotlinx.coroutines#195]
`runBlocking` is not available from common modules.

**Comment by elizarov** [comment]
This is so by design. `runBlocking` cannot be reasonably implemented in JS. The implementation that was ported to JS has too many limitations to be generally useful.

**Comment by JonasFranzDEV** [comment]
How could I test suspend functions in unit tests? Example: https://github.com/JonasFranzDEV/gitea-client/blob/master/common/src/test/kotlin/RepositoriesAPITest.kt
(multiplatform project)

**Comment by dany-kun** [comment]
A simple/naive solution could be `while (!job.isCompleted) {}`

**Comment by elizarov** [comment]
See here for details on async testing in JS: https://youtrack.jetbrains.com/issue/KT-22228
