### ISSUE TITLE
"Already resumed"  error with firestore realtime database

### ISSUE THREAD

**Issue by mataiaslev** [Kotlin/kotlinx.coroutines#196]
Hi!

I am receiving the error **IllegalStateException: Already resumed**

Firestore has the real time way to get data, in which his Listener (addSnapshotListener) will be called more than once. Each change into the database, like delete some item or add one produce a call to this listener. So as in the issue #48 @fvasco says, it's not a "continuation" issue. 

but It's possible works with this type of listeners with coroutines?

**some code for give context:**

Extensión function for await the get:
```kotlin
suspend fun Query.awaitQuery(): QuerySnapshot = suspendCoroutine { continuation ->
    addSnapshotListener { querySnapshot, firebaseFirestoreException ->
        continuation.resume(querySnapshot)
    }
}
```

get:
```kotlin
suspend fun getAllPets(): List<Pet> {
        val docRef = firestore.collection("pets")
        //createdAt >= now - 7dias.
        val snapshot = docRef.whereGreaterThanOrEqualTo("createdAt", petHelper.getLimitDate()).awaitQuery()
        return getPetsFromSnapshot(snapshot)
    }
```

please tell me if more information is needed :)

**Comment by elizarov** [comment]
What are you trying to achieve? It looks that you are just trying to get the current results of your query. In this case you definitely don't need `addSnapshotListener` which is designed to listen to stream of changes in real-time. 

You should you `Query.get` method which returns a `Task`. A `Task` is a type of the future that is used in Firebase API. It has a way to install a call back with `addOnCompleteListener` and so you can integrate with it using `suspendCoroutine`.

**Comment by mataiaslev** [comment]
HI @elizarov thanks for answer :).  i am trying to use the real-time firestore database with coroutines. my question is if it's possible to work with coroutines and real-time. the real-time approach in code looks like with the get(). But if someone insert something in the database, the event will be launched again, and again if happens again.

 is possible works with coroutines for this type of events? if we did it without coroutines, each time that the event happens the success listener updates an observable (in my case live data) and refresh the data into the view. With coroutines, when someone insert something in the database, i get the "already resumed" error for the continuation. and make sense, but it makes me wonder this.

**Comment by fvasco** [comment]
Hi @mataiaslev,
a short answer is "yes" (a definitive answer depends to your use case).

In this example I see an elaboration of a stream of events, so the query should return a `Channel<List<Pet>>` or some other kind of reactive stream.

You can use an `actor` to update the view, then you should redirect query live result to the actor.

Here some actor's code.

    sealed class ViewCommand {
        data class UpdatePetList(val pets: List<Pet>) : ViewCommand()
    }
    
    val viewUpdater = actor<ViewCommand> {
        channel.consumeEach { command ->
            when (command) {
                is ViewCommand.UpdatePetList -> ... // update the view
            }
        }
    }

You can simplify the code sending all events directly to the actor.

**Comment by mataiaslev** [comment]
thanks!! I am going to try.
Give me some time and I am going to came back for tell what happens.

**Comment by mataiaslev** [comment]
I can avoid the error with channels, now my extension function is:

```
suspend fun Query.awaitQuery(): Channel<QuerySnapshot> {
    val channel = Channel<QuerySnapshot>()
    addSnapshotListener { querySnapshot, _ ->
        launch { channel.send(querySnapshot) }
    }
    return channel
}
```

but just works the first time, then the send method do nothing, or at least nothing in this method:

```
suspend fun getAllPets(): List<Pet> {
        val docRef = firestore.collection("pets")
        //createdAt >= now - 7dias.
        val channel = docRef.whereGreaterThanOrEqualTo("createdAt", petHelper.getLimitDate()).awaitQuery()
        return getPetsFromSnapshot(channel.receive())
    }
```
i
so, I thing that like you say @fvasco the solution to my problem is use channels. But  I can't figure out how to get the things working.

**Comment by fvasco** [comment]
Hi @mataiaslev,
Use `send` in a `launch` function means "put in the channel in any order"

    launch { channel.send(querySnapshot) }

It is really better to use a unlimited `Channel` and `sendBlocking` function.

Moreover `channel.receive()` suspend the function until something happen, so your current implementation register a listener, await for the first element and then throw the listening away.

I suggest you -if possible- to send all Firestore's events to an `actor''s channel and manage the updates there.

**Comment by mataiaslev** [comment]
thanks! I will try :) I need to start with the concept of actors haha thanks for your answers!
