### ISSUE TITLE
Latest release version in Maven links to EPA version

### ISSUE THREAD

**Issue by yevhenii8** [Kotlin/kotlinx.coroutines#1960]
There's no difference between these two, both refer to latest EPA version.

```
implementation("org.jetbrains.kotlinx:kotlinx-coroutines-core:latest.integration")
implementation("org.jetbrains.kotlinx:kotlinx-coroutines-jdk8:latest.integration")
```
```
implementation("org.jetbrains.kotlinx:kotlinx-coroutines-core:latest.release")
implementation("org.jetbrains.kotlinx:kotlinx-coroutines-jdk8:latest.release")
```

Expected: I expect to see 1.3.5 version resolved with latest.release and 1.4-M1 version with latest.integration.
Actual: both linked to EPA version, I can't get this dependency without having EPA repository connected.

![image](https://user-images.githubusercontent.com/13679188/80367204-56706d00-8893-11ea-92ec-03a9f3c0bad2.png)

**Comment by elizarov** [comment]
There's nothing we can do affect which version is treated as the "latest one". Please, don't link to the latest version. Always specify the actual version you are using. Would it solve your problem?

**Comment by elizarov** [comment]
It is available in `kotlinx` repository: https://dl.bintray.com/kotlin/kotlinx/
See https://bintray.com/kotlin/kotlinx/kotlinx.coroutines

**Comment by yevhenii8** [comment]
Yes, It would.
But it's a little bit useful to use latest release/snapshot version in test/stage/pet projects. My thought was that release and snapshot/epa usually are split from each other.  Maybe I'm wrong ? And Gradle says:
```
For an external module component, the status is determined from the module descriptor:
For modules in a Maven repository, this value will be "integration" for a SNAPSHOT module, and "release" for all non-SNAPSHOT modules.
```

**Comment by elizarov** [comment]
We have more variation here than binary snapshot/non-snapshot. In particular, the "latest" version you are getting is not snapshot one.

**Comment by yevhenii8** [comment]
Well, okay. Thank you
