### ISSUE TITLE
Using the sample code does not reproduce the problem

### ISSUE THREAD

**Issue by Vixb1122** [Kotlin/kotlinx.coroutines#198]
See: [https://github.com/Kotlin/kotlinx.coroutines/blob/master/coroutines-guide.md#the-problem](url)
> Note: if you have an old system with 2 or fewer CPUs, **then you will consistently see 1000000**, because CommonPool is running in only one thread in this case. _**To reproduce the problem**_ you'll need to make the following change:

```Kotlin
val mtContext = newFixedThreadPoolContext(2, "mtPool") // explicitly define context with two threads
var counter = 0

fun main(args: Array<String>) = runBlocking<Unit> {
    massiveRun(mtContext) { // use it instead of CommonPool in this sample and below 
        counter++
    }
    println("Counter = $counter")
}
```
**I will not consitently see 1000000.**

outputs:
```
Completed 1000000 actions in 25 ms
Counter = 892791
```
```
Completed 1000000 actions in 26 ms
Counter = 862276
```
```
Completed 1000000 actions in 29 ms
Counter = 881049
```

**Comment by elizarov** [comment]
It will be fixed when we implement our own implementation for `DefaultDispatcher` instead of `CommonPool`.
