### ISSUE TITLE
Plain Job doesn't wait for children on join()

### ISSUE THREAD

**Issue by paulblessing** [Kotlin/kotlinx.coroutines#199]
A `Job` that isn't backed by a coroutine doesn't seem to wait for its children to complete when `join()` is called after cancelling. Given the following tests, I would expect them both to pass but only one does.

```kotlin
  private fun runTest(cancelAndJoinBlock: suspend (Job) -> Unit) {
    runBlocking {
      val parentJob = Job()

      val finishedLast = AtomicReference<String>()

      launch(parent = parentJob) {
        // Something "long-running" that doesn't suspend
        Thread.sleep(500)
        finishedLast.set("child")
      }

      // Give the child enough time to have started
      delay(200, TimeUnit.MILLISECONDS)

      cancelAndJoinBlock(parentJob)
      finishedLast.set("join")

      // Give the child enough time to have finished
      delay(1, TimeUnit.SECONDS)

      // The child should have finished before the join on the parent returned
      assertEquals("join", finishedLast.get())
    }
  }

  // This one fails
  @Test fun parentJobWithCancelAndJoin() {
    runTest { parentJob ->
      parentJob.cancel()
      parentJob.join()
    }
  }

  // This one passes
  @Test fun parentJobWithCancelAndJoinChildren() {
    runTest { parentJob ->
      parentJob.cancelChildren()
      parentJob.joinChildren()
    }
  }
```

**Comment by paulblessing** [comment]
Changing `parentJob` to a coroutine-backed `Job` that does nothing but suspend indefinitely (but cancellably) using something like `val parentJob = launch { delay(100, TimeUnit.DAYS) }` seems to be a reasonable workaround. One could also likely write a `suspend fun delayForever()` that never resumes normally, and call that function from within `parentJob`'s `launch`.

**Comment by elizarov** [comment]
The plain `Job()` constructor currently creates a very limited implementation of `Job` that does not have a _cancelling_ state. When you cancel this `Job` it becomes _cancelled_ immediately, thus no way. We can change that to fix your example. I'll see what other effects it will have.

**Comment by paulblessing** [comment]
If it helps, the use-case I had in mind was something along the lines of having a single parent `Job` that would be the parent job for everything running in the background for a signed-in user. Then, when the user chooses to sign out, cancel that parent job and use `join()` to let any in-flight background work clean itself up before fully tearing down the user's context.

Using a `Job` from the `Job()` constructor seemed like a nice way to realize that use-case, but if changing the semantics of `Job()` has other effects, as I mentioned above there are already other seemingly reasonable ways of accomplishing the same result, even without any changes to the coroutines library.

I think the questions become:
- Is the use-case I'm considering even something that makes sense?
- Is this use-case something that the coroutines library needs to / wants to support?
- If it's decided that the coroutines library should support this use-case, does it make sense for `Job()` to have that _cancelling_ behavior, or would a different object/API be warranted?

**Comment by elizarov** [comment]
It does make sense.

**Comment by elizarov** [comment]
After investigation I've found that this is a bug and it will be fixed in the next update. When Job is cancelled it should go into _cancelling_ state while it has children and the `join` should wait until it becomes _cancelled_ (that is, when all its children become cancelled).
