### ISSUE TITLE
Multiplatform kotlinx-coroutines-test

### ISSUE THREAD

**Issue by joffrey-bion** [Kotlin/kotlinx.coroutines#1996]
I'm writing coroutine-based multiplatform libraries, and I would love to use these nice testing tools for common code.

Is there any plan to make this library multiplatform? (even with a subset of the features?)
Is there an existing YouTrack issue for this that I could upvote and follow?

**Comment by joffrey-bion** [comment]
I tried copy-pasting the non-internal part of `kotlinx-coroutines-test` into my common test code.
Apart from a couple JVM-specific annotations, and `printStackTrace()`, it looks like most of it is in fact pure Kotlin code, and I could run it fine in my common tests.

How much work would it represent to publish this lib as multiplatform? (maybe I'm missing something, like a dependency on some other task)

**Comment by altavir** [comment]
It would really help to have it in multiplatform. Mainly for JS.

**Comment by CommanderTvis** [comment]
Same issue.

**Comment by nunocastromartins** [comment]
For anyone finding this issue and wanting a workaround for testing coroutines in common code, here's what I'm using right now (someone posted the JS workaround with promises in the forums somewhere, I'm not the author of that):

```kt
// Common code:
expect fun runBlockingTest(block: suspend () -> Unit)
expect val testCoroutineContext: CoroutineContext

// JVM code:
actual val testCoroutineContext: CoroutineContext =
    Executors.newSingleThreadExecutor().asCoroutineDispatcher()
actual fun runBlockingTest(block: suspend () -> Unit) =
    runBlocking(testCoroutineContext) { block() }

// JS code:
val testScope = MainScope()
actual val testCoroutineContext: CoroutineContext = testScope.coroutineContext
actual fun runBlockingTest(block: suspend () -> Unit): dynamic = testScope.promise { block() }

// Example common test:
@Test
fun testMyCoroutines() = runBlockingTest {
   // ...
}
```

Of course, this doesn't have all the features of `kotlinx-coroutines-test`, but it's working well enough for me.

**Comment by y9san9** [comment]
@nunocastromartins for me your solution leads to 'no test running' error. I've resolved it with something like this:
```kotlin
val testScope = MainScope()
val testCoroutineContext: CoroutineContext = testScope.coroutineContext

fun runTestBlocking(block: suspend () -> Unit) {
    val func = eval("""(promise) => async () => { await promise }""")
    val promise = testScope.promise { block() }
    func(promise)()
}
```

**Comment by TrevorStoneEpic** [comment]
To add on to @nunocastromartins answer, if you want to use the coroutine scope in your runBlockingTest suspend block it can be modified to 

`
expect fun runBlockingTest(block: suspend CoroutineScope.()-> Unit)
expect val testCoroutineContext: CoroutineContext

// JVM code:
actual val testCoroutineContext: CoroutineContext =
    Executors.newSingleThreadExecutor().asCoroutineDispatcher()
actual fun runBlockingTest(block: suspend CoroutineScope.() -> Unit) =
    runBlocking(testCoroutineContext) { this.block() }

// JS code:
val testScope = MainScope()
actual val testCoroutineContext: CoroutineContext = testScope.coroutineContext
actual fun runBlockingTest(block: suspend CoroutineScope.() -> Unit): dynamic = testScope.promise { this.block() }

//iOS code:
actual val testCoroutineContext: CoroutineContext =
    newSingleThreadContext("testRunner")

actual fun runBlockingTest(block: suspend CoroutineScope.() -> Unit) =
    runBlocking(testCoroutineContext) { this.block() }

`

Now you can easily use things like `async{}` or `launch{}` inside of the runBlockingTest code

**Comment by ankushg** [comment]
Burned a day trying to figure out why trying to use `kotlinx-coroutines-test` in my `commonTest` made my whole project fall apart -- didn't realize the artifact is JVM only!

The top-level README indicates that the project supports multiplatform, so it seems like a reasonable assumption that everything supports multiplatform unless marked otherwise

Are there any plans to bring this to the multiplatform world? 

In the meantime, should we update the docs (both the top-level README, and the README inside `kotlinx-coroutines-test`) to reflect that `-test` is JVM-only?

Or further: should we rename the artifact to something like `kotlinx-coroutines-test-jvm`?

**Comment by joffrey-bion** [comment]
@qwwdfsad are there any plans for this in the foreseeable future? I have trouble estimating the amount of work required to make this possible. Do you have any insight about this?

**Comment by dbaroncelli** [comment]
@TrevorStoneEpic
I have a KMM project and, with reference to you snippets:
I have added the "expect" code in **CommonTest**
I have added the JVM "actual" code in **AndroidTest**
I have added the ios "actual" code in **iosTest**

but I when I run my "commonTest" test function, I get the error:
`Exception in thread "Test worker" java.lang.IllegalStateException: Module with the Main dispatcher had failed to initialize. For tests Dispatchers.setMain from kotlinx-coroutines-test module can be used`

Currently these are my dependencies for coroutines:
**commonMain**: implementation("org.jetbrains.kotlinx:kotlinx-coroutines-core:1.4.2-native-mt")
**androidMain**: implementation("org.jetbrains.kotlinx:kotlinx-coroutines-android:1.4.2")

**Comment by ArcticLampyrid** [comment]
@qwwdfsad Any progress here?

**Comment by CommanderTvis** [comment]
I have the very same question

**Comment by JavierSegoviaCordoba** [comment]
I am waiting until the roadmap is updated to ask for this and for the issue with runBlockingTest too

**Comment by dkhalanskyjb** [comment]
Implemented in https://github.com/Kotlin/kotlinx.coroutines/commit/2e25baeb29274853a1926f6bf7c3be761f306d72.

**Comment by ultraon** [comment]
@dkhalanskyjb Could you please help a bit?

I tried using `org.jetbrains.kotlinx:kotlinx-coroutines-test:1.6.0-RC` as a `commonTest` sourceSet dependency for KMM project (Andorid + iOS targets only), and I have the following error:
```
Could not find org.jetbrains.kotlinx:kotlinx-coroutines-test-iosarm64:1.6.0-RC.
Searched in the following locations:
  - https://dl.google.com/dl/android/maven2/org/jetbrains/kotlinx/kotlinx-coroutines-test-iosarm64/1.6.0-RC/kotlinx-coroutines-test-iosarm64-1.6.0-RC.pom
  - https://repo.maven.apache.org/maven2/org/jetbrains/kotlinx/kotlinx-coroutines-test-iosarm64/1.6.0-RC/kotlinx-coroutines-test-iosarm64-1.6.0-RC.pom
Required by:
    project :ads > org.jetbrains.kotlinx:kotlinx-coroutines-test:1.6.0-RC
```

I thought `kotlinx-coroutines-test:1.6.0-RC` should support all native targets, did I miss something?

**Comment by joffrey-bion** [comment]
@ultraon there was an issue with the iOS publication of 1.6.0-RC.

We have to wait for 1.6.0-RC2 or 1.6.0 as far as I know

**Comment by LouisCAD** [comment]
RC2 is actually out.

**Comment by ultraon** [comment]
Due to https://github.com/Kotlin/kotlinx.coroutines/issues/3078 we are waiting for the next version/attempt :-)

**Comment by joffrey-bion** [comment]
> Due to #3078 we are waiting for the next version/attempt :-)

Same here :) `1.6.0-RC` couldn't be used on iOS, now `1.6.0-RC2` breaks all targets for me 😄
