### ISSUE TITLE
ArrayBroadcastChannel not docummented

### ISSUE THREAD

**Issue by altavir** [Kotlin/kotlinx.coroutines#1999]
[Buffered BroadcastChannel factory](https://kotlin.github.io/kotlinx.coroutines/kotlinx-coroutines-core/kotlinx.coroutines.channels/-broadcast-channel.html) references ArrayBroadcastChannel, but the class is internal so the behavior of a BroadcastChannel with buffer is not documented. I suggest removing a reference to the internal class and describe the behavior instead.

**Comment by qwwdfsad** [comment]
Broadcast channels are going to be deprecated, so closing this
