### ISSUE TITLE
IO suspend methods are mixed into FutureController

### ISSUE THREAD

**Issue by ilya-g** [Kotlin/kotlinx.coroutines#2]
Suspension functions for async IO are placed in FutureController due to:
- async IO must somehow interop with async futures.
- lack of extension `suspend` functions
- even if those extensions were possible, these methods are already member-extensions, so they can't be outside of the controller.

I suggest to wrap async IO operations into CompletableFuture's instead and perform `await` on these futures. This would require to write:

```
totalBytesRead += await(input.asyncRead(buf, totalBytesRead))
```

instead of 

```
totalBytesRead += input.aRead(buf, totalBytesRead)
```

but IMO it's much more clear that a suspend point is introduced in the first example.

**Comment by elizarov** [comment]
Not applicable anymore. Async IO can be use in any async coroutine now.
