### ISSUE TITLE
StateFlow does not work properly with static values

### ISSUE THREAD

**Issue by arnis71** [Kotlin/kotlinx.coroutines#2011]
When trying to use StateFlow with enums I found that after the first set values no longer get propagated to the flow and it hangs indefinitely. The same goes for objects.

Example code:
```
enum class Enum {
    V1, V2, V3
}
```
```
val flow = MutableStateFlow<Enum>(null)
coroutineScope {
    launch {
        flow.collect {
            println("collect $it")
        }
    }
    launch {
        (0..100).forEach {
            delay(2000)
            flow.value = StatusWrap(Enum.V1)
        }
    }
}
```

Is this behaviour supposed to be correct for some reason or it is a bug?

**Comment by hoc081098** [comment]
This is behavior of `StateFlow`:
### Strong equality-based conflation:
Values in state flow are conflated using [Any.equals] comparison in a similar way to [distinctUntilChanged] operator. It is used to conflate incoming updates to [value][MutableStateFlow.value] in [MutableStateFlow] and to suppress emission of the values to collectors when new value is equal to the previously emitted one.

**Comment by arnis71** [comment]
But it useful sometimes to set the same data so it would be propagated to observers. Is this the final api or we can expect the support for consequent equal values?

**Comment by elizarov** [comment]
We'll provide a different, more flexible primitive, for those rare cases when you don't want equality-based conflation. Stay tuned.

**Comment by francescogatto** [comment]
Hi! is there a method to do that? thanks!

**Comment by Shabinder** [comment]
@elizarov any update? or can we expect any soon?

**Comment by carterhudson** [comment]
@elizarov Any update on this?

**Comment by elizarov** [comment]
It's there. Checkout ShatedFlow: https://kotlin.github.io/kotlinx.coroutines/kotlinx-coroutines-core/kotlinx.coroutines.flow/-shared-flow/

**Comment by Shabinder** [comment]
> It's there. Checkout ShatedFlow: https://kotlin.github.io/kotlinx.coroutines/kotlinx-coroutines-core/kotlinx.coroutines.flow/-shared-flow/

Yup, using that only.
