### ISSUE TITLE
Implement overloads for standard suspending functions with timeout

### ISSUE THREAD

**Issue by elizarov** [Kotlin/kotlinx.coroutines#202]
This is a performance-related improvement. The goal is to have overloads for TBD standard suspending function with an optional timeout parameter for performance reasons to minimize the number of allocated objects and to ensure that no objects are allocated in fast path when no suspension happens as compared to using a generic `withTimeout(...) { ... }`.

**Comment by qwwdfsad** [comment]
Won't fix unless there is a real-world driven use-case that cannot be achieved otherwise
