### ISSUE TITLE
Suspend coroutine doesn't return while using firestore listener in offline mode

### ISSUE THREAD

**Issue by Varsha-29** [Kotlin/kotlinx.coroutines#2029]
In my app, I would be fetching some data from firestore. When the response to the firestore query is ready, I would return the fetched data to the caller.

I wrapped the firestore call and response in a `suspendCorotuine` 

```
suspend fun fetchDataFromFireStore(): Data? {
        return suspendCoroutine { continuation ->
               FirebaseFirestore.getInstance().document(DATA_PATH).get().addOnCompleteListener { task ->
                    if (task.isSuccessful && task.result != null) {
                        continuation.resume(task.result?.toObject(Data::class.java))
                    } else {
                        continuation.resume(null)
                    }
                }
            }
        }
```

This works well in online mode. Firestore provides offline cache and when I try to execute the same snippet when the internet is turned off, I'm getting the data from firestore inside the listener. But the result is not sent back to the caller  though **continuation.resume()** is invoked. It hangs and the result is never obtained

**Comment by zach-klippenstein** [comment]
Is your job somehow getting cancelled when you enter offline mode?

**Comment by Varsha-29** [comment]
I did not get job cancelled exception. After the suspend method was called, it was running indefinitely

**Comment by elizarov** [comment]
@Varsha-29 Do you have some kind of a self-contained reproducer?

**Comment by Varsha-29** [comment]
Hi @elizarov , could you let me know, what a self-contained reproducer is? I am wrapping the firestore listener within a suspendCoroutine block, in order to continue when the result is obtained asynchronously

**Comment by zach-klippenstein** [comment]
A self-contained reproducer is a small project or code snippet that doesn't depend on any private code that reproduces the issue. It allows the maintainers to run and debug the issue locally.
