### ISSUE TITLE
Compilation errors in macOS using kotlin/native

### ISSUE THREAD

**Issue by yperaltag** [Kotlin/kotlinx.coroutines#2033]
I'm working with some examples in macOS using kotlin/native and I saw the following behavior: 
```
fun main() = runBlocking {
}
```
is giving a linker error with message **Could not find 'main' in '\<root\>' package.**

however the following links fine:
```
fun main() {
    runBlocking {
    }
}
```

**Comment by yperaltag** [comment]
Also I got the error **Unresolved reference: suspendCoroutine** when trying the following:
```
suspend fun myCoroutine() = suspendCoroutine { cont ->
    cont.resume()
}
```
I was just trying to do something nice with this https://github.com/Kotlin/KEEP/blob/master/proposals/coroutines.md#wrapping-callbacks

**Comment by yperaltag** [comment]
Another error: **Type inference failed: Not enough information to infer parameter T in suspend inline fun \<T\> suspendCancellableCoroutine(crossinline block: (CancellableContinuation\<T\>) -> Unit): T**

that error was produced with the following code:
```
suspend fun myCancellableCoroutine() = suspendCancellableCoroutine { cont ->
    cont.resume {
    }
}
```
if I force the value to type **Unit** (_look at the following code_) then another error still pending: **No value passed for parameter 'value'**
```
suspend fun myCancellableCoroutine(): Unit = suspendCancellableCoroutine { cont ->
    cont.resume {
    }
}
```
however the compiler doesn't complain with the following:
```
suspend fun myCancellableCoroutine(): Int = suspendCancellableCoroutine { cont ->
    cont.resume(0) {
    }
}
```

**Comment by qwwdfsad** [comment]
Sorry for such a delay.

The first issue with the main should have been fixed in the latest release and the latter are related to the fact that `kotlin.coroutines.*` package is not imported and that a mandatory parameter `value` hasn't been passed to the `resume` function
