### ISSUE TITLE
Where 1.3.7-1.4-M1 ?

### ISSUE THREAD

**Issue by slavonnet** [Kotlin/kotlinx.coroutines#2048]
Hello

Why not build 1.3.7-1.4-M1?

**Comment by qwwdfsad** [comment]
Hi, mostly because there were no demand for it.
Typically, we release only the current version with EAP compilers and major ones to spend our efforts on something else.

Are you asking out of curiosity or do you have specific concerns?

**Comment by slavonnet** [comment]
I so crazy ) i use Android 4.1 cannry 9 (becouse ver 10 not have kotlin 1.4 plugin + corrutines 1.3.5-M1.4). I also use IR compiller mode + progressive mode. And it is commercial project :)
Have sometime performance issues becouse i use havy api update + room usage and try use last version for use all optimization
