### ISSUE TITLE
coroutines-android:0.20 APK install problem

### ISSUE THREAD

**Issue by SirotovAB** [Kotlin/kotlinx.coroutines#205]
We updated library from 0.19.3 to 0.20.
And now we have APK install problem (Android 5.0 - 5.1)
Installation problem log (Xiaomi Redmi Note 2  Anroid 5.0.2):
```
01-11 08:51:47.339 24754-24764/? A/libc: Fatal signal 11 (SIGSEGV), code 1, fault addr 0x0 in tid 24764 (Compiler driver)
01-11 08:51:47.405 24788-24788/? E/AEE/AED: AM write failure (32 / Broken pipe)
01-11 08:51:47.493 744-2798/? E/SharedPreferencesImpl: Couldn't create directory for SharedPreferences file shared_prefs/log_files.xml
01-11 08:51:47.495 24788-24788/? E/AEE/AED: request.action: 0
01-11 08:51:47.529 278-278/? E/installd: DexInv: —- END '/data/app/com.appdomain.ru-2/base.apk' —- status=0x000b, process failed
```
Problem devices list:
HM Note 2 (hermes) - Xiaomi Redmi Note 2  Anroid 5.0.2
Redmi Note 3 (hennessy)
A5000 (A5000)
One E9PLUS dual sim (htc_a55ml_dtul)
PSP3531DUO (DW53B01G)
Blade V6 (P635A20)
LG K10 (m23g)
ZenPad C 7.0 (Z170MG) (P001)
S1 (S1a40)
LG Prime Plus 4G (mc90ds)
A7000 (A7000-a)
TAB 2 A7-20F (Tab2A7-20F)
TAB 2 A10 (A10-70L)
TAB 2 A10 (A10-70F)
PSP3504DUO (PSP3504DUO)
Power Five (PowerFive)
p70a
mx4
LG Max (v10)
Le X507 (X3_HK)
K50-T5
K3 Note (K50a40)
K3 Note (aio_otfp)
k01q_h

**Comment by elizarov** [comment]
Can you provide more details, please? Can you publish a self-contained reproducer or some additional debug info that would help in pinpointing what is causing the problem?

**Comment by SirotovAB** [comment]
Bug versin:  https://github.com/SirotovAB/CoroutinesBugDemo/commit/a539dbd4eaac46f271e7b3f6a300678715991ae2
Fixed version: https://github.com/SirotovAB/CoroutinesBugDemo/commit/1866c01b6e5ad3c50be8fd62143bf14299eab1e0

**Comment by elizarov** [comment]
I cannot reproduce this problem on emulator with Android Lollipop 5.0 (API 21) and I don't have any of those physical devices. Are there any additional details like verbose logs that would explain why it fails?

**Comment by SirotovAB** [comment]
This problem deos not reproduce on emulator.  
Ver 0.21 has the same problem.
Option minifyEnabled true fix this problem.

**Comment by romansl** [comment]
This line in proguard config returns this bug back:
```
-keep class kotlinx.coroutines.experimental.channels.ChannelsKt$flatMap$1
```

**Comment by romansl** [comment]
This function:
```kotlin
public fun <E, R> ReceiveChannel<E>.flatMap(context: CoroutineContext = Unconfined, transform: suspend (E) -> ReceiveChannel<R>): ReceiveChannel<R> =
        produce(context) {
            consumeEach {
                transform(it).consumeEach {
                    send(it)
                }
            }
        }
```

**Comment by elizarov** [comment]
Thank you very much for this investigation.

**Comment by elizarov** [comment]
I've reposted this as Kotlin JVM BE issue: https://youtrack.jetbrains.com/issue/KT-22278
