### ISSUE TITLE
Couldn't inline method call 'map'

### ISSUE THREAD

**Issue by sschuberth** [Kotlin/kotlinx.coroutines#2056]
Upon the upgrade from 1.3.6 to 1.3.7 we start to [see](https://travis-ci.com/github/oss-review-toolkit/ort/builds/168028964#L974):

```
e: org.jetbrains.kotlin.codegen.CompilationException: Back-end (JVM) Internal error: Couldn't inline method call 'map' into

public final fun invokeSuspend(`$result`: kotlin.Result<kotlin.Any>): kotlin.Any? defined in org.ossreviewtoolkit.analyzer.Analyzer.analyzeInParallel.<anonymous>.<closure-Analyzer$analyzeInParallel$2$1>
```

Any hint how to solve this?

**Comment by elizarov** [comment]
It is a compiler bug. Please, post it together with a link to the code where it shows to http://kotl.in/issue

**Comment by sschuberth** [comment]
Done: https://youtrack.jetbrains.com/issue/KT-39158.

**Comment by elizarov** [comment]
Thanks a lot!
