### ISSUE TITLE
Deprecated feature:  .asListenableFuture()

### ISSUE THREAD

**Issue by Jean-PhilippeDESCAMPS** [Kotlin/kotlinx.coroutines#2059]
Hello,

Im freelancer developer, and I got a mission to update an Android app.
The project was implement experimental coroutines version. I have to update to recent librairies.
 
I can't find a solution to resolved my last error:

`async(UI) {
     refreshAccessToken().get()
     loadAccessToken()
}.asListenableFuture()`

Can somebody have a solution to rebuild the .asListenableFuture() feature ?

**Comment by fvasco** [comment]
Did you seen here https://github.com/Kotlin/kotlinx.coroutines/tree/master/integration/kotlinx-coroutines-guava ?

**Comment by Jean-PhilippeDESCAMPS** [comment]
@fvasco thanks, its compiling now.
