### ISSUE TITLE
Async block in Fragment does not run after Instant Run

### ISSUE THREAD

**Issue by balthild** [Kotlin/kotlinx.coroutines#206]
## Step to reproduce

- Open [this project](https://github.com/balthild/AsyncExample) in Android Studio
- Click "Run App" Button. 
- On the UI there's `"Async message"`. In logcat there're two such messages:
```
01-12 17:21:44.914 17593-17593/com.balthild.asymcexample I/System.out: Some log
01-12 17:21:44.929 17593-17620/com.balthild.asymcexample I/System.out: Async log
```
- Make some changes. For example, replace `"Some log"` with `"Some log 2"` in `MainActivityFragment.kt`.
- Click "Apply Changes" Button (Instant Run). 
- On the UI there's `"Hello World!"`, which is set in `fragment_main.xml`. Only one more message goes in Logcat:
```
01-12 17:21:44.914 17593-17593/com.balthild.asymcexample I/System.out: Some log
01-12 17:21:44.929 17593-17620/com.balthild.asymcexample I/System.out: Async log
01-12 17:21:52.092 17593-17593/com.balthild.asymcexample I/System.out: Some log 2
```

**Comment by elizarov** [comment]
Thank's a lot for the report. I've investigated the problem, minimized it without using `kotlinx.coroutines` library and reported to the the Kotlin issues here https://youtrack.jetbrains.com/issue/KT-22267

However, most likely it is not the problem in the Kotlin compiler, but in the Android toolchain that updates dex file for hot replace, so it might need to be reported to Google at the end.
