### ISSUE TITLE
var and Atomic

### ISSUE THREAD

**Issue by rewlad** [Kotlin/kotlinx.coroutines#2062]
Why is it written ```var counter = AtomicInteger()```?
It seems to be ```val```, because counter itself is not mutated, but the value of atomic does.
And this way we leave someone possibility to do ```counter = ``` in an unsafe way.
And we can not make CI rule to warn of unsafe global mutable state.
On the other hand may be someone (who does not know what is Atomic*) needs to see, that counter has mutable _meaning_.

https://github.com/Kotlin/kotlinx.coroutines/blob/1eeed509abbe8e542124841ce14884202463460b/kotlinx-coroutines-core/jvm/test/guide/example-sync-03.kt#L27

https://kotlinlang.org/docs/reference/coroutines/shared-mutable-state-and-concurrency.html

**Comment by elizarov** [comment]
That's a bug. Thanks for noticing!
