### ISSUE TITLE
On the issue of starting the coroutine。

### ISSUE THREAD

**Issue by z589533** [Kotlin/kotlinx.coroutines#207]
![image](https://user-images.githubusercontent.com/12063612/35035557-b31cebe4-fbac-11e7-8395-abf618313259.png)

commTow=CPU*50
commOne=CPU-1

Whether to construct the number of thread schedulers or specify the maximum number of coroutines

![image](https://user-images.githubusercontent.com/12063612/35035648-0e7abfca-fbad-11e7-919d-dc7960140b58.png)

![image](https://user-images.githubusercontent.com/12063612/35035920-b182da5e-fbad-11e7-9f2c-57443c409013.png)
![image](https://user-images.githubusercontent.com/12063612/35035937-bb0c3c6e-fbad-11e7-806a-6113cc0a3f06.png)
ForkJoinPool.commonPool-worker-3 delay  It can not start，
so In my opinion, it is the number of coroutines constructed

Can I think so?

**Comment by elizarov** [comment]
Can you please clarify what is the problem you are experiencing?

**Comment by z589533** [comment]
ok, my question is whether launch (comm) is the maximum size for a given coroutine

**Comment by elizarov** [comment]
Size of what?

**Comment by z589533** [comment]
coroutine Max Size

**Comment by elizarov** [comment]
What is the "size of a given coroutine"? Coroutines don't have "size", so I'm totally confused what is your question. Can you, please, clarify?

**Comment by z589533** [comment]
![image](https://user-images.githubusercontent.com/12063612/35097808-b12608ee-fc8c-11e7-8ff1-530eb4e970b9.png)
commOne set size 10
commTow default size CPU-1=3
![image](https://user-images.githubusercontent.com/12063612/35097839-df8e347c-fc8c-11e7-872e-f7af014b0a9f.png)
commTow Only 3 coroutines are started
commOne  Only 10 coroutines are started

Whether or not to explain, launch(commTow) is coroutines size

**Comment by elizarov** [comment]
I see from you picture that everything is working as designed. Sorry, but I don't understand your question. What is your concern?

**Comment by z589533** [comment]
My question is whether newFixedThreadPoolContext is the method that determines the maximum number of coroutines

**Comment by elizarov** [comment]
No. `newFixedThreadPoolContext` creates a coroutine dispatcher with a fixed number of _threads_. It can run unlimited number of coroutines. The number of coroutines that you can run is only limited by the amount of memory you have.

**Comment by z589533** [comment]
thank you, I know now
