### ISSUE TITLE
Get name of coroutine executing from within kotlinx.coroutines library

### ISSUE THREAD

**Issue by athuls** [Kotlin/kotlinx.coroutines#2070]
Could you please provide pointers as to how the coroutine name of an executing coroutine is propagated to the kotlinx.coroutines layer, which actually manages and schedules the coroutine to run asynchronously? For more context:
we are building an Android app. Without making any changes to the app itself, we want to instrument kotlinx.coroutines library to determine the beginning and end of each executing coroutine and also get the name of the executing coroutine. We looked at the code in CoroutineScope.launch (in Builders.common.kt file), and tried inspecting the coroutine scope and coroutine context objects. However we didn't have any luck in determining the name of the enclosing coroutine in the application layer, that was executing, from within kotlinx.coroutines library.

**Comment by elizarov** [comment]
By default, coroutines don't have a name unless you add `CoroutineName` context element. However, in debug mode coroutines have automatically generated unique identifier that is available via `CoroutineId` context element.

**Comment by qwwdfsad** [comment]
Also, please note that `CoroutineId` is not publicly available and is reflected only in the whole `coroutineContext` string representation and in the name of the thread that is executing this coroutine
