### ISSUE TITLE
StateFlow: Make conflation optional

### ISSUE THREAD

**Issue by TebbeUbben** [Kotlin/kotlinx.coroutines#2072]
The documentation says that StateFlows are always conflated. "So a slow collector skips fast updates, but always collects the most recently emitted value."
However, this leads to problems if you are not just interested in the current state itself but also in the previous one or if you need run a certain action when it jumps to a very particular state. Conflation is bad in these cases because it might remove some values in between that were actually important to you.

**Comment by ashdavies** [comment]
It would probably be a bit hard (and unnecessary) to make `StateFlow` conflation optional as it appears to be built into its design, however, it sounds like `StateFlow` isn't the right tool of choice for you. If you want to handle backpressure differently, you will probably benefit from using a rendezvous or buffered `Channel`.

```kotlin
private val _rendezvousFlow: Channel<String> = Channel(RENDEZVOUS)
val redezvousFlow: Flow<String> get() = _rendezvousFlow.receiveAsFlow()
```

I'm not 100% on whether to use `get() =` here though.

**Comment by elizarov** [comment]
Please, take a look at the upcoming `SharedFlow` design as presented in #2034. It is more flexible than a `StateFlow` and has configurable conflation policy. Does it help with your use-case?

**Comment by TebbeUbben** [comment]
> Please, take a look at the upcoming `SharedFlow` design as presented in #2034. It is more flexible than a `StateFlow` and has configurable conflation policy. Does it help with your use-case?

Thanks! `SharedFlow` seems to be exactly what I'm looking for.
