### ISSUE TITLE
CompletableJob doesn't finish when complete() is called

### ISSUE THREAD

**Issue by LearnThroughWork** [Kotlin/kotlinx.coroutines#2077]
What's happening: Both runBlocking parent and childJob continue to work.

What I expected: childJob would complete and runBlocking will continue to run.

Question: Am I using the Job api wrong? Could anyone help me reason what is happening?

Code:

class Test {

    fun start() = runBlocking {
        val childJob = Job()
        launch(childJob) {
            while (true) {
                println("Child working ")
                delay(1000L)
            }
        }

        childJob.complete() // returns true

        while(true) {
            println("Parent working")
            delay(1000L)
        }
    }

    companion object {
        @JvmStatic
        fun main(args: Array<String>) {
            Test().start()
        }
    }
}

**Comment by elizarov** [comment]
But what are you trying to achieve with this code? What do you want/expect to happen?

**Comment by elizarov** [comment]
You are _completing_ the _parent_ job of the coroutine you are launching, but the coroutine itself `launch(childJob) { ... }` continues to run. If you want to _stop_ the launched coroutine, you shall _cancel_ it or its parent job.

**Comment by LearnThroughWork** [comment]
> But what are you trying to achieve with this code? What do you want to happen?

I understand now. The `childJob` actually becomes the parent of `launch(childJob) {}` coroutine.

What I wanted is to _complete_ a launched coroutine instead of _cancelling_ it. The _Job_ returned by `launch { }` doesn't have a way to _complete_ it.


fun start() = runBlocking {
    
    val child = launch {
        while (true) {
            println("Child working ")
            delay(1000L)
        }
    }

    child.complete() // Wanted to complete it manually instead of using child.cancel()

    while(true) {
        println("Parent working")
        delay(1000L)
    }
}

**Comment by elizarov** [comment]
Your coroutine is running an infinite `while (true) { ... }` loop. It cannot complete normally. It can only be canceled. If you want it to complete, then it should not have an infinite loop. For example, you can write something like `while (!childJob.isComplete) { ... }` and then when you call `childJob.complete()` the next iteration of the `while` loop will complete, completing the coroutine. Does it help?

**Comment by LearnThroughWork** [comment]
Yes this looks is what I wanted. Thanks
