### ISSUE TITLE
Usually, `await` throws a wrong exception for representing a failure of a `Deferred` (e.g., of an `async` coroutine)

### ISSUE THREAD

**Issue by taras-i-fedyk** [Kotlin/kotlinx.coroutines#2086]
**The current behavior:** `await`ing the result of a `Deferred` (e.g., of an `async` coroutine) throws the original exception in the current coroutine when the current coroutine is failing / has failed or is being cancelled / has been cancelled as a result of the `Deferred`’s failure (e.g., of the `async` coroutine's failure) .

**The proposed behavior:** `await` throws a `CancellationException` in such a case instead.

**Here are the reasons why the proposed behavior would be much more appropriate:**

- the proposed behavior would conform to the paradigm in accordance with which a suspending function throws a `CancellationException` when the current coroutine is failing / has failed or is being cancelled / has been cancelled. 

- the proposed behavior would be consistent with how `Job.join` and `ReceiveChannel.receive` work. 

- the proposed behavior would not create the illusion that you can catch the exception generated by a failed `Deferred` (e.g., by a failed `async` coroutine) for the sake of preventing its parent coroutine from failing automatically. 

    Because if you're told that `await` can throw only a `CancellationException` under the given circumstances, you understand that once some exception has been thrown, Structured Concurrency has been already applied and you can’t undo it. Thus you know beforehand that the effect of catching an exception is limited, and such a limited effect doesn't contradict common sense.

**Comment by elizarov** [comment]
The ship has sailed with respect to how `.await()` works and it works this way by design, to ensure that computation can be transparently moved to another coroutine while perfectly preserving its resulting value and resulting exceptions, e.g.

```
val d = scope.async { doSomething() }
d.await()
```

Should behave identically to:

```
doSomething()
```

**Comment by taras-i-fedyk** [comment]
@elizarov 

**When the parent scope is failable,** the two pieces of code you gave as an example cannot be identical in principle, because the first piece of code is subject to the automatic application of Structured Concurrency which makes a difference. Consequently, those pieces of code are not identical even now, with the current behavior of `await`, which was designed specifically for ensuring the identity in question. If so, there was no point in designing the behavior of `await` in such a way. Especially taking into account the fact that it led to the significant drawbacks pointed out in my initial post in which I described why the proposed behavior would be much more appropriate.

**And when the parent scope is not failable,** those pieces of code are identical indeed. But my complaints regarding the current behavior of `await` are in no way related to such cases. (As I mentioned in my initial post, my complaints are related solely to the cases when the current coroutine is failing / has failed or is being cancelled / has been cancelled as a result of the Deferred’s failure.)
