### ISSUE TITLE
Request `awaitSingleOrNull` for reactive

### ISSUE THREAD

**Issue by JasonMing** [Kotlin/kotlinx.coroutines#2088]
kotlin-coroutines  `awaitSingle()` can assert the Flux contains one and only one element and returning first element.
But seems there is no operators can assert the Flux contains **_zero or one element_**, i.e., `awaitSingleOrNull()`.

**Comment by elizarov** [comment]
Also related to #2079

**Comment by dkhalanskyjb** [comment]
Hi @JasonMing! In fact, a method with that same name has been present for a while as an extension on arbitrary `Publisher`, but we decided to deprecate that method, as it has a confusing name: "xOrY" in Kotlin typically means that if the operation finishes with an error, then "Y" will be returned instead, but for `awaitSingleOrNull`, this would require that `null` is returned in cases of both zero elements and *more than one element*, which can be surprising.

Maybe this method could be added with another name, like `awaitAtMostOne`, but we would like first to know the use cases for this methods. Could you please share yours?

**Comment by JasonMing** [comment]
Hi @dkhalanskyjb! This issue seems has been obsoleted after kotlinx.coroutines 1.4.0 released at 27 Oct 2020.
If only focus on this issue, the reason I'd like to request `awaitSingleOrNull()` feature is, awaiting on a `Mono` which I don't care about its value but only status, `single` may provide better readability and semantic than `first`.
This await operation is common in bridging reactive api in coroutine context.

**Comment by dkhalanskyjb** [comment]
This issue being obsoleted will become obsoleted after kotlinx.coroutines 1.5.0, as we plan to remove `awaitSingleOrNull` :) https://github.com/Kotlin/kotlinx.coroutines/pull/2628
That said, your use case should not be affected, as `awaitSingleOrNull` on `Mono` will still be present. So, this issue can be closed then?

**Comment by JasonMing** [comment]
ok👌
