### ISSUE TITLE
UnitSerializer naming inconsistency

### ISSUE THREAD

**Issue by PaulWoitaschek** [Kotlin/kotlinx.coroutines#2094]
Currently it's:
```kotlin
Int.serializer()
Boolean.serializer()
..
UnitSerializer()
```
For consistency it would be great if you deprecated `UnitSerializer()` and follow the same schema and provide a `Unit.serializer()` replacement.

**Comment by qwwdfsad** [comment]
Seems to be the wrong repository :) 
Moved to https://github.com/Kotlin/kotlinx.serialization/issues/867
