### ISSUE TITLE
Exception transparency violation in Flows

### ISSUE THREAD

**Issue by peterLaurence** [Kotlin/kotlinx.coroutines#2095]
Hi,

I tried to violate exception transparency in Flows, just to check. Using coroutines `1.3.7` and Kotlin `1.3.72`, this simple Flow won't compile:

```kotlin
val upstream: Flow<Int> = flowOf(1, 2, 3).map {
    try {
        it
    } catch (e: Throwable) {
        0
    }
}
```

It produces in the console: 
```
e: org.jetbrains.kotlin.codegen.CompilationException: Back-end (JVM) Internal error: Couldn't transform method node:
```

This naïve implementation catches all downstream exception and tries to emit a value if a throwable is caught. If we collect this flow, should we expect to get an `IllegalStateException`? Like, for example:

```kotlin
val violatesTransparency: Flow<Int> = flow {
    for (i in 1..3) {
        try {
            emit(i)
        } catch (e: Throwable) {
            emit(-1)
        }
    }
}

fun main() = runBlocking {
    try {
        violatesTransparency.collect { value ->
            check(value <= 2) { "Collected $value" }
        }
    } catch (e: Throwable) {
        println("Caught $e")
    }
}
```
We get:
```
Caught java.lang.IllegalStateException: Flow exception transparency is violated:
    Previous 'emit' call has thrown exception java.lang.IllegalStateException: Collected 3, but then emission attempt of value '-1' has been detected.
    Emissions from 'catch' blocks are prohibited in order to avoid unspecified behaviour, 'Flow.catch' operator can be used instead.
    For a more detailed explanation, please refer to Flow documentation.
```

**Comment by qwwdfsad** [comment]
Hi,
Back-end error is a bug in the compiler, it shouldn't normally happen. I've filed https://youtrack.jetbrains.com/issue/KT-39690, please keep track there and thanks for the reproducer!

>f we collect this flow, should we expect to get an IllegalStateException?

Yes, please read the exception message carefully:
>**Previous 'emit' call has thrown exception** java.lang.IllegalStateException: Collected 3
>but then emission attempt of value '-1' has been detected.  **Emissions from 'catch' blocks are prohibited** in order to avoid unspecified behaviour, 'Flow.catch' operator can be used instead.

This exception prevents exactly what you are doing -- attempts to emit an element from `catch` block. You can use `flow.catch` operator instead.

In order to understand why it is prohibited to emit from `catch` block, consider the following scenario:

```
val flow = flow {
    try { emit(1); emit(2) }
    catch (e: Exception) { emit(2) }
}

flow.collect {
    if (it == 2) throw CancellationException("Collected had enough data")
    else println(it)
}
```

It would be really unexpected if this code printed `1, 3`

**Comment by peterLaurence** [comment]
@qwwdfsad I'm aware of the `catch` operator - I just wanted to make sure of the expected result when this issue will be resolved on the compiler side.
It's clear for me, thanks!
