### ISSUE TITLE
`.scan` first element is emitted before `.onStart`

### ISSUE THREAD

**Issue by peterfigure** [Kotlin/kotlinx.coroutines#2099]
```
        flowOf(2, 3, 4)
            .onStart {
                emit(0)
            }
            .scan(1, { acc, t -> t})
            .collect { println(it) }
```

will result in 

```
1
0
2
3
4
```

It caught me by surprise, if this is expected (or non-deterministic) I would suggest making this very clear in `scan`'s documentation?

**Comment by fvasco** [comment]
You should consider that in the code `flow.scan(1, { acc, t -> t})`, the first item emitted is `1`.
In you case flow is `0, 2, 3, 4`
