### ISSUE TITLE
kotlinx-coroutines-test. withContext {...} in liveData {...} doesn't switch back to the previous context after its finish

### ISSUE THREAD

**Issue by a-kari** [Kotlin/kotlinx.coroutines#2102]
Hello! I'm writing an integration test for my Android app. And I've faced an issue with `liveData {...}` coroutine builder: when I call `withContext {...}` function inside of it, it switches to a given context (e.g. `Dispatchers.IO`), but does not switch back after return (to `Dispatchers.Main.immediate`).

The test looks like:

**WordFragmentIntegrationTest:**

```kotlin
@RunWith(RobolectricTestRunner::class)
@Config(application = TestAppWithDaggerComponent::class)
class WordFragmentIntegrationTest {

    @get:Rule
    val coroutinesRule = CoroutinesRule()

    private val mockWebServer = MockWebServer()

    @After
    fun teardown() {
        mockWebServer.shutdown()
    }

    @Test
    fun `should fetch a word from api and populate the view`() = runBlockingTest {
        // Mock api response, it works fine.
        val response = MockResponse().setResponseCode(HttpURLConnection.HTTP_OK)
                                     .setBody(SAMPLE_API_WORD_JSON)
                                     .setBodyDelay(0, TimeUnit.MILLISECONDS)
        mockWebServer.enqueue(response)
        mockWebServer.start(8080)

        // Launch a Fragment under test. It triggers an api call.
        val fragmentScenario = launchFragmentInContainer<WordFragment>()

        // Wait for the Fragment to do its work.
        fragmentScenario.onFragment { fragmentUnderTest ->
            runBlocking {
                while (fragmentUnderTest.isLoading) { yield() }
                
                // Do some assertions...
            }
        }
    }
}
```

**CoroutinesRule:**

```kotlin
class CoroutinesRule : ExternalResource() {

    override fun before() {
        Dispatchers.setMain(TestCoroutineDispatcher())
    }

    override fun after() {
        Dispatchers.resetMain()
    }
}
```

---

And a piece of code, which causes test failure.

**WordViewModel:**

```kotlin
val wordLiveData = liveData {
    printCurrentThread("Emitting the first value")
    emit(UIState.ShowLoading)

    val value = withContext(Dispatchers.IO) {
        printCurrentThread("Fetching a value")
        loadWordUseCase(wordId)
    }

    printCurrentThread("Emitting the second value")
    emit(value)
}

private fun printCurrentThread(message: String) {
    val threadInfo = "Thread: ${Thread.currentThread().id}. UI thread: ${Looper.getMainLooper().thread.id}"
    println("$message. $threadInfo")
}
```

It works fine in production environment:

```bash
Emitting the first value. Thread: 1. UI thread: 1  # First emitting is on the UI thread.
Fetching a value. Thread: 365. UI thread: 1        # Fetching is on some IO thread.
Emitting the second value. Thread: 1. UI thread: 1 # Switched back to the UI thread.
```

But in the test environment (where `Dispatchers.Main` is replaced) `withContext {...}` does not switch back to `liveData {...}`'s `Dispatchers.Main.immediate`, and it causes `CoroutineLiveData` crash, because its `emit()` should be called from the UI thread.

```bash
Emitting the first value. Thread: 11. UI thread: 11  # Emitted on the UI thread.
Fetching a value. Thread: 19. UI thread: 11          # Switched to IO thread.
Emitting the second value. Thread: 19. UI thread: 11 # Didn't switch back, which caused:

Exception in thread "DefaultDispatcher-worker-1 @coroutine#2"
 java.lang.IllegalStateException: Cannot invoke setValue on a background thread
	at androidx.lifecycle.LiveData.assertMainThread(LiveData.java:462)
	at androidx.lifecycle.LiveData.setValue(LiveData.java:304)
...
```

---

Is it a bug or am I doing something wrong? E.g. maybe I have a wrong `CoroutinesRule`?

**Comment by elizarov** [comment]
It looks like some problem in `TestCoroutineDispatcher` (cc @qwwdfsad ) that sometimes seems to behave like an unconfined dispatcher. I struggle to reproduce your specific setup, though.

**Comment by a-kari** [comment]
My setup is in [this branch](https://github.com/a-kari/dictionary/tree/integration-tests).

Files to check:

* [`build.gradle` of the module under test](https://github.com/a-kari/dictionary/blob/integration-tests/feature_word/build.gradle)
* [Versions of used libraries](https://github.com/a-kari/dictionary/blob/integration-tests/scripts/dependencies_versions.gradle)
* [`WordViewModel`](https://github.com/a-kari/dictionary/blob/integration-tests/feature_word/src/main/java/jp/neechan/akari/dictionary/feature_word/presentation/WordViewModel.kt) - a class where the error occurs
* [`WordFragmentIntegrationTest`](https://github.com/a-kari/dictionary/blob/integration-tests/feature_word/src/test/java/jp/neechan/akari/dictionary/feature_word/presentation/WordFragmentIntegrationTest.kt)
* [`CoroutinesRule`](https://github.com/a-kari/dictionary/blob/integration-tests/test_utils/src/main/java/jp/neechan/akari/dictionary/test_utils/junit/CoroutinesRule.kt)

**Comment by aconda-mercari** [comment]
Is there an update to this?
