### ISSUE TITLE
Allow any suspending function to be a clause in the select expression

### ISSUE THREAD

**Issue by 1zaman** [Kotlin/kotlinx.coroutines#2106]
Currently, the `select` expression requires it's clauses to implement one of the `SelectClause*` interfaces, and provide an implementation of it's `registerSelectClause*` method to coordinate with the `SelectInstance` to deliver the result. This makes it hard to use `select` with any clause that's not already provided by the library.

Why not allow any suspending function to be used directly as a clause? The `select` implementation could then manage it directly, by invoking it with a `Continuation` which would cancel the other clauses when it's resumed (preferably even from it's interceptor). For those special clauses that need to coordinate and rendezvous with `select`, such as `Channel` transfers and `Mutex` locking, we could use a special subclass of `Continuation` that provides the methods needed for that.

The builder DLS could be something like this:
```kotlin
select<Unit> {
    on { someSuspendFunction() } perform { process(it) }
    on { otherSuspendFunction() } perform { process(it) }
}
```

**Comment by elizarov** [comment]
Unfortunately, this is impossible to implement in practice. Moreover, the protocol between a data-structure and a `select { ... }` expression itself is very complex, so we don't open it to 3rd-party implementation. We support only classes inside `kotlinx.coroutines` as participants in `select` protocol.

**Comment by 1zaman** [comment]
The approach I described seems to be relatively simple to implement (invoke all the suspending clauses, wait for one to be completed, then cancel all the others), and should be fine for the vast majority of user implementations.

Where more complex behaviour is required, it seems to me that it would also not be that hard to refactor the existing implementations to work with this approach, by simply having the `Continuation` provide a reference to the `SelectInstance`, and then interacting with it exactly as already being done in the `registerSelectClause*` method implementation. This `Continuation` subclass can be `internal` in the library, allowing only the library implementations to interact directly with the `SelectInstance`, while user implementations would not have to do anything special.

If you like, I can work on creating a minimal pull request demonstrating how I think this can be achieved, when I get some time.

**Comment by elizarov** [comment]
That's no what `select` expression is designed to do. It is designed to atomically perform one of the operations and make sure that the others are not executed. It is not the same as running them concurrently and cancelling the slow ones. The latter is usually called `race { ... }` of something like that. If you have use-cases for it, then you can file a separate issue describing your use-cases.
