### ISSUE TITLE
Flow not emitting after a transaction that deletes then inserts room entity

### ISSUE THREAD

**Issue by giancarlogatti** [Kotlin/kotlinx.coroutines#2108]
I did try to create a minimal repro of the issue I'm experiencing, but that one actually worked properly, but it was much more pared down compared to what is in my app. Essentially I know the object is actually updating as I have used a debugger and it does delete then insert, but flow is never triggered. Also tried just using @Update but that did not work as well. I hope I can link my project here....if it's ran it will be on the exact screen where I am experiencing the issue. 

The insertion and deletion of my particular room entity works but the update does not. Actually it has but only maybe 1 in 20 times on average. This is the exact branch of the project that can be cloned to see the issue:

https://github.com/giancarlogatti/Notify

The particular screen that is having an issue is the fragment known as CreateEditAlarmFragment - which is in presentation->ui->alarm->create. 

To recreate the issue I am having in testing...please:

1. Create a new time by clicking the time button.
2. Click on the created time and change the time. 

You'll see it doesn't change but it should change if new flow was collected. Thanks, tell me anything else you need.

**Comment by elizarov** [comment]
Are you sure this problem is related to `kotlinx.coroutines` and not some problem in Room or in your code?
