### ISSUE TITLE
Detach from 'suspendCancellableCoroutine' block after cancellation

### ISSUE THREAD

**Issue by 1zaman** [Kotlin/kotlinx.coroutines#2114]
`suspendCancellableCoroutine { cont -> }` creates a `CancellableContinuation` wrapper around the original `Continuation`, which handles cancellation by immediately resuming the wrapped `Continuation` with the cancellation exception, and discarding any subsequent resumes from the executing block.

This results in an easy to use method for converting futures and other callback-based APIs to suspending functions, while not having to worry about handling and propagating cancellation. Some futures do not even support cancellation, and this makes it simple to add cancellation on top of them.

After the cancellation has been handled by the `CancellableContinuation`, the executing block is effectively orphaned, and the coroutine resumes without waiting for it. However, the block still retains a reference to the continuation, and thus to the whole coroutine call stack (including the enclosing classes of all the suspending methods in the call stack). It may take some time for the upstream future to handle the cancellation (or it may not support cancellation at all), and in the meanwhile it would prevent the coroutine from being garbage collected, even though it’s no longer part of the coroutine.

This can be fixed by having the `CancellableContinuationImpl` wrapper clear the reference to it’s inner `Continuation` after resuming it, which will leave the executing block with no reference to the coroutine, and allow the coroutine to be garbage collected without having to wait on the block to complete. Due to the way it’s implemented though (extending `DispatchedTask`, and. the `dispatch()` method being implemented externally), it will require some refactoring to achieve this, so I didn't attempt it myself

**Comment by elizarov** [comment]
Thanks for a detailed writeup, but it is not a compelling reason to undertake such a refactoring. Reasoning about code that uses mutable references (vars) becomes harder, complicating the maintenance of this code. The benefit in this particular case is minimal and quite hypothetical at this point. A more serious reason, inspired by the real code that can be encountered in the wild, is needed to undertake it.
