### ISSUE TITLE
sending or offering inside block of code on another thread kotlin/native

### ISSUE THREAD

**Issue by Elkhoudiry** [Kotlin/kotlinx.coroutines#2115]
is there a way to call `flow.collect { .. }` from a background worker and call `offer/send` from another thread (probably main thread).

i've this listener that always gives real time result when the data changes, but it does it on the main thread, how to offer that to my collecter that i created on a background thread, i'm always having this exception, and what does it mean exactly.
`Uncaught Kotlin exception: kotlin.native.concurrent.FreezingException: freezing of $flowTest$lambda-6$lambda-5$FUNCTION_REFERENCE$0@1fd6428 has failed, first blocker is BlockingCoroutine{Active}@af5408`

my code:
```
runOnBackground{
    val myFlow = createFlow()
    myFlow.collect { .. }
}
```

```
createFlow() = channelFlow <snapshot> {
    // real time data change listener
    val listener = firestore.snapshotListener{ snapshot, error -> 
        // this block of code is on main thread
        offer(snapshot) // exception here
    }
}
```

i know multithreading isn't supported in kotlin/native, i'm just checking if there is a work around or not right now

**Comment by elizarov** [comment]
Multithreading in Kotlin/Native is supported in a separate `native-mt` branch. See #462 for details and updates.
