### ISSUE TITLE
`withTimeout` hangs on objects with exception-throwing `equals`

### ISSUE THREAD

**Issue by elizarov** [Kotlin/kotlinx.coroutines#212]
Run this code: 

```
import kotlinx.coroutines.experimental.*

class FooBar {
    override fun equals(obj: Any?): Boolean = TODO()
}

fun main(args: Array<String>) = runBlocking<Unit> {
    withTimeout(100L) {
        FooBar()
    }
}
```

It should return normally (returning an instance of `FooBar` from inside of `withTimeout` block), but it hangs. 

This problem was originally reported here: https://youtrack.jetbrains.com/issue/KT-21629

**Comment by konrad-kaminski** [comment]
Fixed in #215. Object equality instead of reference equality was used when comparing with `COROUTINE_SUSPENDED`.
