### ISSUE TITLE
NoSuchMethodError

### ISSUE THREAD

**Issue by gleno** [Kotlin/kotlinx.coroutines#2126]
Slightly convoluted, but this minimally reproduces the bug in coroutines 1.3.7:

```kotlin
import kotlinx.coroutines.*

class A {
    init {
        GlobalScope.launch {
            suspend fun test(a: Boolean = false) = 0
            test()
        }
    }
}

fun main() {
    runBlocking {
        launch {
            A()
            delay(100)
        }
    }
}
```

This throws a `NoSuchMethodError`. Seems to be caused by suspend and the optional parameter on the function declared inside the coroutine in `A`. 

Kotlin 1.3.72, Java 1.8, Desktop and Android are affected. Maybe this is a compiler issue?

**Comment by qwwdfsad** [comment]
Thanks for the watered-down reproducer!
Unfortunately, this is a known compiler bug https://youtrack.jetbrains.com/issue/KT-27449. Please keep track of and vote for it there.

Known workarounds are extracting this function from suspend lambda or not using default parameters in such functions

**Comment by gleno** [comment]
@qwwdfsad Great! I googled a bit, but nothing came up. It's not a big issue to work around, once you do know it's an issue. :)
