### ISSUE TITLE
crash : Dispatchers.Main is missing

### ISSUE THREAD

**Issue by fndwn** [Kotlin/kotlinx.coroutines#2133]
I create a new android studio project and use coroutines 1.3.7.
The simple app crashed when launching activity.
~~~gradle
implementation 'org.jetbrains.kotlinx:kotlinx-coroutines-core:1.3.7'
~~~

~~~kotlin
override fun onCreate(savedInstanceState: Bundle?) {
        super.onCreate(savedInstanceState)
        setContentView(R.layout.activity_main)
        // crash!!
        GlobalScope.launch(Dispatchers.Main) {}
}
~~~

**Comment by SeekDaSky** [comment]
Looks like you are missing the [`kotlinx-coroutines-android`](https://github.com/Kotlin/kotlinx.coroutines/tree/master/ui/kotlinx-coroutines-android) dependency
