### ISSUE TITLE
kotlinx-coroutines-core-common:1.3.7-1.4-M3 seems missing on kotlinx

### ISSUE THREAD

**Issue by jayv** [Kotlin/kotlinx.coroutines#2136]
`kotlinx-coroutines-core-common:1.3.7-1.4-M3` is missing on kotlinx repo (latest: `1.3.5-1.4-M1`)

We're trying to switch to kotlin `1.4-M3` in a multiplatform project and have switched to `1.3.7-1.4-M3` for core (jdk) and js, are we supposed to mix it with common `1.3.5-1.4-M1` (for the time being) or is there a new approach to setting up the dependencies for `common` in a multiplatform project?

**Comment by jayv** [comment]
I suppose this may be a result what's described here: 
https://blog.jetbrains.com/kotlin/2020/06/kotlin-1-4-m2-released/#hierarchical-project-structure

Do I understand correctly that there is no longer a need for a `*-common` dependency in a multiplatform project for  `commonMain`?

**Comment by qwwdfsad** [comment]
Indeed, you are right, now it's enough to depend on `kotlinx-coroutines-core` right in the common source-set
