### ISSUE TITLE
StateFlow - Custom equality predicate

### ISSUE THREAD

**Issue by timusus** [Kotlin/kotlinx.coroutines#2140]
I have a `StateFlow` that holds the latest list of songs from a database. The idea is that any downstream collector that is interested in songs can query this `StateFlow` rather than triggering a requery of the database.

```
    private val songsRelay: Flow<List<Song>> by lazy {
        MutableStateFlow<List<Song>?>(null)
            .apply {
                CoroutineScope(Dispatchers.IO)
                    .launch {
                        songDataDao.getAll().flowOn(Dispatchers.IO)
                            .collect { songs -> value = songs }
                    }
            }
            .filterNotNull()
            .flowOn(Dispatchers.IO)
    }
```

Due to `StateFlow`s built in `Any.equals()` based conflation, the value is only updated/emitted if the underlying songs aren't equal.

This doesn't work well for me, as song equality is based on a song 'ID' - but I'd like the StateFlow to update when other properties of the song (such as the `playCount` or `playbackPosition`) are changed. I could change the equality contract of song, but this adversely affects other areas of code which rely on two songs being considered equal based on their ID.

Ideally, I'd like to be able to pass my own predicate to StateFlow - similar to `distinctBy()` for a regular flow.

Thanks for your consideration!

**Comment by elizarov** [comment]
That use-case is covered by the design of the upcoming `SharedFlow`. It does not have built-in equality and can be combined with an arbitrary `distinctBy` operator. See #2034 for details.
