### ISSUE TITLE
deferred.await() with try-catch inside a launch{} is cancelling all coroutines in a scope when exception occur.

### ISSUE THREAD

**Issue by premkumarroyal** [Kotlin/kotlinx.coroutines#2147]
Hi,
I am launching multiple coroutines using async, directly in scope, and calling .await() in another coroutine with launch builder. 

All async are in scope level so calling await will throw an exception, so I wrapped deferred.await() with try-catch and expected that it should not cancel all other coroutines that are running. 

But all coroutines are canceled. Please find the code.

```kotlin
private fun multipleCoroutinesAtScopeLevel() {

    val scope = CoroutineScope(CoroutineName("ParentJob"))

    val firstDef = scope.async(CoroutineName("firstDef")) {
      delay(2000)
      throw IllegalAccessException();
      return@async "First"
    }
    val secondDef = scope.async(CoroutineName("secondDef")) {
      delay(4000)
      return@async "Second"
    }
    val thirdDeff = scope.async(CoroutineName("thirdDeff")) {
      delay(3000)
      return@async "third"
    }

    val helperJob = scope.launch(CoroutineName("HelperJob")) {
      try {
        firstDef.await()
      } catch (e: Exception) {
        Log.e(TAG, "Exception at $firstDef")
      }

      secondDef.await()
      thirdDeff.await()
    }
  }
```
Output:
"secondDef#2":DeferredCoroutine{Cancelled}@9a4604f
"thirdDeff#3":DeferredCoroutine{Cancelled}@c6f43dc
Exception at "firstDef#1":DeferredCoroutine{Cancelling}@a351ce5
"HelperJob#4":StandaloneCoroutine{Cancelled}@58943ba

**If this is as expected, may I know a little more about it?**

**Comment by dalvin** [comment]
I tried wrapping this in `runBlocking` and `runBlockingTest`

`runBlockingTest` is working fine and providing secondDeff and thirdDeff values successfully.

Should there be a difference in structured concurrency behavior between `runBlocking` and `runBlockingTest`?

**Comment by elizarov** [comment]
This is so by design. Please, consult a section of the guide on the structured concurrency: https://kotlinlang.org/docs/reference/coroutines/composing-suspending-functions.html#structured-concurrency-with-async
Does it help?

**Comment by premkumarroyal** [comment]
Thanks @elizarov 

Understand. I think it would be better if we have detailed docs on async behavior in a nested coroutine. It took quite some time to me understand after trying out some samples and reading some blogs.
