### ISSUE TITLE
Unexpected exception cause when there was no one

### ISSUE THREAD

**Issue by evgenyvaganov** [Kotlin/kotlinx.coroutines#2153]
After refactoring of our code to coroutines we noticed weird behavior, with the function withTimeout, when exception cause is set to a different instance of itself. Reproducible by the following code: 
```
@Test
fun testUseTimeoutWeirdBehavior() = runBlocking<Unit> {
    try {
        throw IllegalStateException("Bad state")
    } catch (exp: Exception) {
        assertNull(exp.cause)
    }

    try {
        withTimeout<Unit>(Duration.ofMillis(200)) {
            throw IllegalStateException("Bad state")
        }
    } catch (exp: Exception) {
        assertNull(exp.cause)
    }
}
```

We workaround-ed it by some ugly code:
```
suspend fun <T> useTimeout(duration: Duration, block: suspend CoroutineScope.() -> T): T {
    try {
        return withTimeout(duration, block)
    } catch (e: Exception) {
        val cause = e.cause
        if(cause != null && e.javaClass == cause.javaClass) {
            throw cause
        }
        throw e
    }
}
```
which doesn't look right.

**Comment by qwwdfsad** [comment]
This is not a bug, but a feature named [stacktrace recovery](https://github.com/Kotlin/kotlinx.coroutines/blob/master/docs/debugging.md#stacktrace-recovery). It is enabled by default in unit tests (detected by `-ea` flag) to simplify debugging.
To see what it is doing you can try to call `exp.printStackTrace()` and see what it prints.

I encourage you to read a linked paragraph, but TL;DR such `cause` copying recovers missing asynchronous coroutine frames by the cost of exception copying and additional causes.

If this is undesirable behaviour, you can disable it with a system property `kotlinx.coroutines.stacktrace.recovery` set to `false`.

**Comment by evgenyvaganov** [comment]
Oh, my bad. Thank you for the clarification. You are right, the cause, even it is the same exception and message, has different more elaborative stack trace. 
It just confused me a bit when our tests started failing due to the presence of the cause. Maybe it is worth considering to wrap that inner exception into your own to avoid similar confusions in the future.
