### ISSUE TITLE
Support for Mingw86

### ISSUE THREAD

**Issue by danielgruber** [Kotlin/kotlinx.coroutines#2157]
We're trying to build a 32 bit version for our Kotlin Native Project and would love to support 32 bit. Is this possible right now?

**Comment by qwwdfsad** [comment]
Unfortunately, it is not really possible.
We neither have bare metal to actually _test_ mingw binaries, nor enough time to take care of this issue

**Comment by JohnLCaron** [comment]
I see that kotlinx-coroutines-core has a mingwx64 target but not a mingwx86. Is there something about mingwx86 that makes it harder than mingwx64?

**Comment by qwwdfsad** [comment]
[mingwX86 is deprecated](https://kotlinlang.org/docs/native-target-support.html#deprecated-targets) thus we are not adding support for that target
