### ISSUE TITLE
StateFlow unreferenced compileKotlinIos - error multiplatform

### ISSUE THREAD

**Issue by cbgm** [Kotlin/kotlinx.coroutines#2163]
Hi,
I'm using StateFlow / MutableStateFlow in shared code which works fine with Android. But when the pod for iOS is about to be installed there is an unreferenced error (StateFlow / MutableStateFlow is only used inside the shared). Might there be an issue with configuration or is it a problem with multiplatform? Because of this [link](https://github.com/Kotlin/kotlinx.coroutines/issues/2120) I assume the compilation should be possible

**Comment by qwwdfsad** [comment]
Could you please ensure that you have `common` dependency to `kotlinx-coroutine-core?`
Similarly to how it is explained [here](https://github.com/Kotlin/kotlinx.coroutines#multiplatform)

**Comment by cbgm** [comment]
Thx for your response. After updating the libs everything was working fine. The issue can be closed
