### ISSUE TITLE
Unresolved reference: test

### ISSUE THREAD

**Issue by sureshmaidaragi1919** [Kotlin/kotlinx.coroutines#2167]
When I try to run below methods it always shows.

`Unresolved reference: test
`

As I know this is about **Kotlin Collections** issue , didn't find GitHub link to raise **Kotlin collection** issue, So ended up raising in coroutines 

**Ref link :**
https://kotlinlang.org/api/latest/jvm/stdlib/kotlin.sequences/filter.html

**Here is the screen shot**
<img width="414" alt="Screenshot at Jul 27 14-51-53" src="https://user-images.githubusercontent.com/28126457/88526460-93c2d300-d019-11ea-83f6-caf09e8136a8.png">

**Comment by JakeWharton** [comment]
You can file a bug about the samples in the standard library at http://kotl.in/issue. This repository is not the appropriate place.

**Comment by sureshmaidaragi1919** [comment]
ho okay Jake, posted  https://youtrack.jetbrains.com/issue/KT-40747
Thanks for sharing me standard library link
