### ISSUE TITLE
Modify StateFlow operators to return StateFlow instead of Flow

### ISSUE THREAD

**Issue by Volt316** [Kotlin/kotlinx.coroutines#2169]
I'm running into a minor annoyance when trying to combine StateFlows because all of the operators for StateFlow return Flow. This is solved at the moment by casting all of my operations back to StateFlow but it would be nice if I didn't have to do a cast every time.

    val test1 = MutableStateFlow(1)
    val test2 = MutableStateFlow(2)
    val test3: StateFlow<Int> = test1.map { it * 2 } as StateFlow<Int>
    val test4: StateFlow<Int> = test1.combine(test2) { first, second -> first + second } as StateFlow<Int>

**Comment by fvasco** [comment]
Duplicate #2008 #2081

**Comment by Volt316** [comment]
Oh sorry, I didn't see anything on this topic. Thanks for linking the other posts.
