### ISSUE TITLE
Flow.catch() doesn't actually catch exceptions

### ISSUE THREAD

**Issue by AbdoNasr3** [Kotlin/kotlinx.coroutines#2174]
When I work with flows I'm relying heavily on `catch()` operator to catch upstream exceptions happen, So I can throw exception wherever I want and at the same time ensure that exceptions don't get propagated to the next layer of my architecture.    
But I get shocked today when I tried to run one of my project tests, see code snippet: 
```
    @Test
    fun failedToGetId_ReturnEmpty() = mainCoroutineRule.runBlockingTest {
        // GIVEN invalid pubId
        val mockedPubRepo = mock<PublisherRepository> { on(it.getPublisherId(testPubInfo)).doReturn(null) }
        val period = ZonedDateTime.ofInstant(Instant.now(), ZoneId.systemDefault()).minusDays(7).toEpochSecond()
        val mockedArticlesRepo = mock<ArticlesRepository> { on(it.getPubArticlesSince(TestData.publisher1.id, period)).doReturn(TestData.uiArticles) }

        pubArticlesSince = PublishedArticlesSince(mockedPubRepo, mockedArticlesRepo)

        // When trying to get Articles of this publisher
        val returnArticles = mutableListOf<UiArticle>()
        pubArticlesSince(Pair(testPubInfo, Since.LAST_7_DAYS)).toCollection(returnArticles)

        // Assert the list is empty since there's exception happened
        assertThat(returnArticles).isEmpty()
    }
```
As you can see list expected to be empty when things go wrong But instead the test fails throwing `NullPointerExcption()`
How is This happens Since I catch all exceptions like this:

```
 `suspend operator fun invoke(parameters: P): Flow<R> { 
        execute(parameters)
        .catch { e -> Timber.e("Exception happened while executing, cause: ${e.message}"); emitAll(emptyFlow()) } 
}`
```
However, when I tried to wrap `execute(parameters)` in traditional imperative `try {} catch {}` block,  the test passes and everything works fine, So how this happens? I hope this will be fixed soon Since I love declarative `catch()` operator But for now I still need to use `try{} catch {}` until this issue be fixed.

**One Final Note**: I also tried `onCompletion()` operator but nothing changed

**Comment by qwwdfsad** [comment]
Could you please provide a self-contained reproducer that I can copy-paste and run? Project to checkout is fine too.

It probably has something to do with improper mocks setup or tricky bug in `catch` operator, but it's hard to tell without actual reproducer (or even stacktrace)

**Comment by AbdoNasr3** [comment]
Thanks for your response! I don’t think it is something related to improper mocks since i have mocks like that for other flow code tests. But after a few days of opening this issue i’ve taken a deep look again into the code that generated this issue and i found that this is something happened under the hood in my code before evaluating the intended result to `Flow` so i think it might the reason why `catch()` failed to catch such exception

**Comment by qwwdfsad** [comment]
`catch` should not fail tho. Is there any chance you will be able to find a reproducer for this problem?

**Comment by AbdoNasr3** [comment]
Here's a fake implementation of my code that produces the same issue: 
```
fun main() {
    generateExceptionRandomly()
        .catch { e -> println("Exception happened, cause: ${e.message}") }
}

fun generateExceptionRandomly(): Flow<String> {
    val randomNum = if (Random.nextInt(2) == 1) 4 else throw NullPointerException()
    return listOf("someIds", "some_id", "some_another_id").asFlow()
}
```

**Comment by qwwdfsad** [comment]
Well, it's definitely not Flow.catch` issue.

Your code is a rough equivalent of the following:
```
val flow: Flow<Int>
if (Random.nextBoolean()) {
    flow = flowOf(1, 2, 3)
} else {
    throw NullPointerException()
}

flow.catch { e -> ...}.collect()
```

`catch` is not supposed to catch exceptions from all the code, but **only** from within a flow.
