### ISSUE TITLE
An uncatched exception from Java produces no backtrace

### ISSUE THREAD

**Issue by Pansebert** [Kotlin/kotlinx.coroutines#2179]
When I add following Code to my Android App:
`GlobalScope.launch {
    val file = java.io.File("foo")
}`
The unhandled Exception causes the App to exit but without any backtrace at all. 
While Something like 
`GlobalScope.launch {
    throw Exception("foo") 
}`
works fine.
First I thought this is an issue of the Android Debugging Bridge but they said that I was wrong (https://issuetracker.google.com/issues/162446113). Am I at the correct place here? :)

**Comment by qwwdfsad** [comment]
Please use slack or stackoverflow for broad questions non-related to coroutines in details.

In your particular example `val file = java.io.File("foo")` produces no backtrace because it doesn't throw an exception
