### ISSUE TITLE
Creation of a library implementor's guide

### ISSUE THREAD

**Issue by dave08** [Kotlin/kotlinx.coroutines#218]
A few people have asked how and what the best practice is to turn callbacks into usable w/ coroutines. 

I think it's ambiguous to have this in KEEP which is usually spec docs for planning features and explaining internals, not end user documentation, which gives the feeling that `suspendCoroutine` and th like are low level api not to be used.

In reality, it seems that this IS the best way to turn callbacks into `suspend fun`, also an explanation of the different ways of doing it like the option of making it cancellable would be great.

This and other points might warrent a library implementor's guide, that would turn this into 'official' and also outline other good practices along the way. 

In Rx, there are extensive libraries out there for a wide variety of needs, with official guidlines in coroutines, it might make it easier for implementors to want to 'jump into the boat', its could be much easier than in Rx...

**Comment by elizarov** [comment]
Good point. I'm planning to writing something along those lines with a tentative title of "Coroutine Integration Guide". The idea is that it is going to explain how to integrate coroutines with 3rd party libraries of various kinds (talk though all sorts of callbacks).

**Comment by qwwdfsad** [comment]
It seems like coroutines are quite popular and all the guidances are pretty well-covered by the community and Android materials :)
