### ISSUE TITLE
Ambiguous method error when using RxConvert from Java

### ISSUE THREAD

**Issue by DartJulia** [Kotlin/kotlinx.coroutines#2182]
While using the extension functions from [RxConvert](https://github.com/Kotlin/kotlinx.coroutines/blob/master/reactive/kotlinx-coroutines-rx2/src/RxConvert.kt) to convert `Flow` to `Observable` or `Flowable` in Java, we fail to build from an ambiguous method error.
`asFlowable()` and `asObservable()` both have a `JVMName` of `from`. The following test case in Java is a way to reproduce this issue:

```java

public class FlowToRxJavaTest {
    @Test
    void observableFromFlowTest() {
        Flow<String> flow = stringFlow();
        Observable<String> observable = RxConvertKt.from(flow);
    }
    @Test
    void flowableFromFlowTest() {
        Flow<String> flow = stringFlow();
        Flowable<String> flowable = RxConvertKt.from(flow);
    }
}
```
A simple fix could be removing the `JVMName` entirely. Another option is changing the `JVMName` to be more specific to the function, but an appropriate name doesn't come to mind.

After a solution is decided I would be more than happy to create a PR for a fix.

**Comment by qwwdfsad** [comment]
>A simple fix could be removing the JVMName entirely. Another option is changing the JVMName to be more specific to the function, but an appropriate name doesn't come to mind.

Unfortunately, it's not that simple, because it will break every binary client that already compiled against older version of `kotlinx.coroutines`. It requires proper migration path with `HIDDEN` API and, ideally, a way to prevent this in the future.
