### ISSUE TITLE
Job Cancellation Exception

### ISSUE THREAD

**Issue by abhinavtestbook** [Kotlin/kotlinx.coroutines#2184]
Getting - Failure(kotlinx.coroutines.JobCancellationException: Job was cancelled; job=SupervisorJobImpl{Cancelled}@511b48c)

while using viewModelScope.launch { } , viewModel is being initialised in onViewCreated of fragment. 
<img width="684" alt="Screenshot 2020-08-06 at 8 22 29 PM" src="https://user-images.githubusercontent.com/68221307/89546884-b1b2e380-d822-11ea-8083-06130fc85756.png">

**Comment by qwwdfsad** [comment]
Please elaborate on what exactly is wrong, why do you expect results to differ from what you have and how to reproduce this behaviour

**Comment by abhinavtestbook** [comment]
Expecting the function in try to be executed but job is getting cancelled before going in to try block. 
<img width="759" alt="Screenshot 2020-08-06 at 8 33 43 PM" src="https://user-images.githubusercontent.com/68221307/89548121-423df380-d824-11ea-9102-794701881a6a.png">

**Comment by LobnaMazhar** [comment]
Have you solved this issue?? @abhinavtestbook

**Comment by abhinavtestbook** [comment]
Not yet.

**Comment by qwwdfsad** [comment]
Unfortunately, I am not able to help here without a detailed explanation.
I would suggest asking in `#coroutines` Kotlin slack channel for a more interactive discussion
