### ISSUE TITLE
BlockHound detects `kotlinx.coroutines.reactive.ReactiveFlowKt#<clinit>` during `Mono.awaitFirst()`

### ISSUE THREAD

**Issue by okue** [Kotlin/kotlinx.coroutines#2190]
I'm using BlockHound integration defined in `kotlinx-coroutines-debug` with reactor.

### Problem

When the code `Mono#awaitFirst()` is executed, BlockHound detected blocking call here:
https://github.com/Kotlin/kotlinx.coroutines/blob/1.3.8/reactive/kotlinx-coroutines-reactive/src/ReactiveFlow.kt#L145

This detection occurs only once or twice after starting my application.
After [`contextInjector`][1] variable is initialized, this detection is not warned any more.

Every time we start the application, BlockHound detects and outputs warning messages, which sounds a little noisy.

versions:
- Kotlin: 1.3.72
- kotlinx.coroutines: 1.3.8
- BlockHound: 1.0.4

### Workaround

We can suppress this blocking call.

```kotlin
BlockHound.builder()
    .with(CoroutinesBlockHoundIntegration())
    .allowBlockingCallsInside(
        "kotlinx.coroutines.reactive.ReactiveFlowKt", "<clinit>"
    )
```

### Question

Does BlockHound integration of `kotlinx-coroutines-debug` have a plan to suppress this kind of warning?

[1]: https://github.com/Kotlin/kotlinx.coroutines/blob/1.3.8/reactive/kotlinx-coroutines-reactive/src/ReactiveFlow.kt#L144

**Comment by qwwdfsad** [comment]
Thanks for the report! Suppressing is probably the best option here

**Comment by okue** [comment]
Thanks!

**Comment by okue** [comment]
https://github.com/Kotlin/kotlinx.coroutines/pull/2331 resolves this issue.
Thanks @dkhalanskyjb.
