### ISSUE TITLE
CoroutinesTimeout replacement for JUnit 5

### ISSUE THREAD

**Issue by asarkar** [Kotlin/kotlinx.coroutines#2197]
https://github.com/asarkar/coroutines-test

**Comment by dkhalanskyjb** [comment]
Thank you, this is a nice idea! There is now a PR for this, #2402.

**Comment by asarkar** [comment]
The idea wasn’t to lift my code and make a PR, but to use it as is instead.

**Comment by dkhalanskyjb** [comment]
The proposed implementation was written independently from yours and is different in some significant ways.

**Comment by qwwdfsad** [comment]
Fixed in 1.5.0
