### ISSUE TITLE
Unexpected uncompleted Job on tests with Channel's

### ISSUE THREAD

**Issue by 4face-studi0** [Kotlin/kotlinx.coroutines#2202]
## Scenario
I'm tryin' to test a ViewModel that suggest a Collection of Movies to the User, one by one.
* it has an Use Case that fetches a list of N movies
* it launches a coroutine on I/O Dispatcher where:
  * it takes 5 random movies from that list and send to a channel with a buffer of 5
    * if channel is full just wait ( `send` )
    * if operation fails, wait 500ms and try again
  * when all the 5 movies are buffered, iterate again the same process, while the scope is active
* `next()` function launches a coroutine on I/O Dispatcher that pulls ( `receive` ) a movies from the buffer and set to result
* a slot has been freed from buffer, which is ready to receive another Movie

## Expected behavior
After injecting the scope from `runBlockingTest`, injecting all the dispatches as `TestCoroutineDispatcher` and closing the `buffer` channel at the end of my assertions, the test to compete without unfinished jobs.

## Current behavior
The test fails in an unexpected way, in order for it complete correctly I have to
* In test:
  * Create an additional scope `TestCoroutineScope` to inject in the ViewModel
  * Close the buffer
  * Call `cleanupTestCoroutines` on the additional scope
* In my VM
  * Send to channel on another dispatcher ( TestCoroutineDispatcher )
  * But collect on the same dispatcher of the test ( `launch { }` )

Any other combination would make it fails
Funny thing is that while I was writing a minimal example for reproduce it, I found out that it pass with a similar setup, but ONLY if:
* I run everything on same dispatcher as the test
* I do NOT use an additional scope

( _Examples and link to project at the bottom_ )

## Environment
**OS** MacOs Big Sur beta
**IDE** IntelliJ Ultimate 2020.2
**Kotlin MP** 1.4.0
**Coroutines** 1.3.9
**Test Coroutines** 1.3.8
**JDK** 14
**Test environment** JUnit 4

## Example two - most similar to real case scenario
[Link to this example](https://github.com/4face-studi0/CineScout/blob/1906f4c1fd2e6ee606902f1a6a53954e565c958e/client/src/jvmTest/kotlin/testingChannels/two.kt)
[Link to my real test](https://github.com/4face-studi0/CineScout/blob/1906f4c1fd2e6ee606902f1a6a53954e565c958e/client/src/jvmTest/kotlin/client/viewModel/GetSuggestedMovieViewModelTest.kt)
[Link to my real ViewModel](https://github.com/4face-studi0/CineScout/blob/1906f4c1fd2e6ee606902f1a6a53954e565c958e/client/src/commonMain/kotlin/client/viewModel/GetSuggestedMovieViewModel.kt)
```kotlin
import client.DispatchersProvider
import client.TestDispatchersProvider
import client.ViewStateFlow
import client.viewModel.CineViewModel
import domain.Test.Movie.Inception
import domain.Test.Movie.TheBookOfEli
import entities.movies.Movie
import kotlinx.coroutines.CoroutineScope
import kotlinx.coroutines.cancel
import kotlinx.coroutines.channels.Channel
import kotlinx.coroutines.delay
import kotlinx.coroutines.flow.collect
import kotlinx.coroutines.flow.take
import kotlinx.coroutines.isActive
import kotlinx.coroutines.launch
import kotlinx.coroutines.test.TestCoroutineScope
import kotlinx.coroutines.test.runBlockingTest
import kotlin.random.Random
import kotlin.test.Test

class ExampleTwo {

    private class SUT(
        override val scope: CoroutineScope
    ): CineViewModel, DispatchersProvider by TestDispatchersProvider() {
        private val getSuggestedMovies = { listOf(Inception, TheBookOfEli) }

        val result = ViewStateFlow<Movie>()

        private val buffer = Channel<Movie>(5)

        init {
            next()

            scope.launch(Io) {
                while(isActive) {
                    try {
                        // Take 5 random from suggestions
                        val suggestions = getSuggestedMovies()
                            .shuffled(Random)
                            .take(5)

                        // Send to buffer if not full, otherwise wait
                        for (suggestion in suggestions)
                            buffer.send(suggestion)

                    } catch (t: Throwable) {
                        result.error = t
                        delay(500)
                    }
                }
            }
        }

        fun next() {
            scope.launch {
                result.data = buffer.receive()
            }
        }

        override fun closeChannels() {
            buffer.cancel()
        }
    }

    // * * * TESTS * * *

    @Test // Fail
    fun `one`() = runBlockingTest {
        val sut = SUT(this)

        sut.result.take(3).collect {
            println(it)
            sut.next()
        }

        cleanupTestCoroutines()
    }

    @Test // Fail
    fun `two`() = runBlockingTest {
        val sut = SUT(this)

        sut.result.take(3).collect {
            println(it)
            sut.next()
        }

        sut.closeChannels()
        cleanupTestCoroutines()
    }

    @Test // Success
    fun `three`() = runBlockingTest {
        val scope = TestCoroutineScope()
        val sut = SUT(scope)

        sut.result.take(3).collect {
            println(it)
            sut.next()
        }

        sut.closeChannels()
        scope.cleanupTestCoroutines()
    }

    @Test // Fail
    fun `four`() = runBlockingTest {
        val scope = TestCoroutineScope()
        val sut = SUT(scope)

        sut.result.take(3).collect {
            println(it)
            sut.next()
        }

        scope.cancel()
    }
}
```

## Example one - tryin to reproduce
[Link to file](https://github.com/4face-studi0/CineScout/blob/1906f4c1fd2e6ee606902f1a6a53954e565c958e/client/src/jvmTest/kotlin/testingChannels/one.kt)
```kotlin
import kotlinx.coroutines.CoroutineScope
import kotlinx.coroutines.cancel
import kotlinx.coroutines.channels.Channel
import kotlinx.coroutines.delay
import kotlinx.coroutines.flow.MutableStateFlow
import kotlinx.coroutines.flow.collect
import kotlinx.coroutines.flow.take
import kotlinx.coroutines.isActive
import kotlinx.coroutines.launch
import kotlinx.coroutines.test.TestCoroutineScope
import kotlinx.coroutines.test.runBlockingTest
import kotlin.test.Test

class ExampleOne {

    private class SUT(private val scope: CoroutineScope) {
        val result = MutableStateFlow(0)
        val buffer = Channel<Int>(5)

        init {
            next()

            scope.launch() {
                var i = 0
                while(isActive) {
                    try {
                        buffer.send(i++)
                    } catch (t: Throwable) {
                        break
                    }
                    delay(10)
                }
            }
        }

        fun next() {
            scope.launch {
                runCatching {
                    result.value = buffer.receive()
                }
            }
        }
    }

    // * * * TESTS * * *

    @Test // Fail
    fun `one`() = runBlockingTest {
        val sut = SUT(this)

        sut.result.take(3).collect {
            println(it)
            sut.next()
        }

        cleanupTestCoroutines()
    }

    @Test // Success
    fun `two`() = runBlockingTest {
        val sut = SUT(this)

        sut.result.take(3).collect {
            println(it)
            sut.next()
        }

        sut.buffer.close()
        cleanupTestCoroutines()
    }

    @Test // Fail
    fun `three`() = runBlockingTest {
        val scope = TestCoroutineScope()
        val sut = SUT(scope)

        sut.result.take(3).collect {
            println(it)
            sut.next()
        }

        sut.buffer.close()
        scope.cleanupTestCoroutines()
    }

    @Test // Fail
    fun `four`() = runBlockingTest {
        val scope = TestCoroutineScope()
        val sut = SUT(scope)

        sut.result.take(3).collect {
            println(it)
            sut.next()
        }

        scope.cancel()
    }
}
```

**Comment by dkhalanskyjb** [comment]
We reworked the whole test module in https://github.com/Kotlin/kotlinx.coroutines/commit/2e25baeb29274853a1926f6bf7c3be761f306d72, so this whole class of errors should vanish.

That said, the issue here is that you call `cleanupTestCoroutines`. You shouldn't: when inside `runBlockingTest` (which is now renamed to just `runTest`), it will clean up the coroutines on its own. Test №3 passes, because the newly-created test coroutine scope is not actually used at all! So, it can be rewritten to simply
```kotlin
    @Test // Success
    fun `three`() = runBlockingTest {
        val sut = SUT(scope)

        sut.result.take(3).collect {
            println(it)
            sut.next()
        }

        sut.closeChannels()
    }
```
This is just as correct.

Also, with the new version of the test module, `cleanupTestCoroutines` should never be called at all.
