### ISSUE TITLE
kotlinx-coroutines-core-native:1.3.9 not found for Kotlin Multiplatform

### ISSUE THREAD

**Issue by xiaobailong24** [Kotlin/kotlinx.coroutines#2206]
[https://github.com/Kotlin/kotlinx.coroutines#native](Native) see:
> Kotlin/Native version of kotlinx.coroutines is published as kotlinx-coroutines-core-native (follow the link to get the dependency declaration snippet).

But [kotlinx-coroutines-core-native](https://search.maven.org/artifact/org.jetbrains.kotlinx/kotlinx-coroutines-core-native/1.3.9/jar) is INVALID.

And [jfrog](https://repo.jfrog.org/artifactory/libs-release-bintray/org/jetbrains/kotlinx/kotlinx-coroutines-core-native/) has no version:1.3.9

**Comment by qwwdfsad** [comment]
Correct, this is stale documentation. Please use artifact `kotlinx-coroutines-core` directly

**Comment by xiaobailong24** [comment]
> Correct, this is stale documentation. Please use artifact `kotlinx-coroutines-core` directly

@qwwdfsad Thanks for your reply. 
And,  does `androidMain` sourceSet for Multiplatform project still use `kotlinx-coroutines-android`?

```
kotlin {
    jvm("android")
    ios()

    sourceSets {
        val commonMain by sourceSets.getting {
            dependencies {
                api("org.jetbrains.kotlinx:kotlinx-coroutines-core:1.3.9")
            }
        }

        val iosMain by sourceSets.getting {
            dependencies {
                  // Not use
//                implementation("org.jetbrains.kotlinx:kotlinx-coroutines-core-native:$kotlinx_coroutines_version")
            }
        }
        val androidMain by sourceSets.getting {
            dependencies {
                // Still use
                implementation("org.jetbrains.kotlinx:kotlinx-coroutines-android:1.3.9")
            }
        }
    }
}
```

**Comment by qwwdfsad** [comment]
Yes, `kotlinx-coroutines-android` is a separate not multiplatform-specific artifact with Android-related API

**Comment by xiaobailong24** [comment]
> Yes, `kotlinx-coroutines-android` is a separate not multiplatform-specific artifact with Android-related API

Got. Thanks.
