### ISSUE TITLE
How to use LiveData + Coroutine?

### ISSUE THREAD

**Issue by XinyueZ** [Kotlin/kotlinx.coroutines#221]
I write some UnitTests and used LiveData in some cases, however, I got the following exception if I use UI or Job() even CommonPool.

```android.arch.core.executor.DefaultTaskExecutor.isMainThread```.

It looks like that the LiveData needs Main-Thread(or maybe ui-thread), but how can I give a correct one? 

thx

**Comment by elizarov** [comment]
You should add `kotlinx-coroutines-android` module to your dependencies and launch your coroutines in Android UI thread using `launch(UI) { ... }`.

**Comment by k-kagurazaka** [comment]
@XinyueZ 
In addition, you should use [InstantTaskExecutorRule](https://developer.android.com/reference/android/arch/core/executor/testing/InstantTaskExecutorRule.html) if you want to do in unit test instead of instrumentation test because the main looper is not mocked in unit test.
