### ISSUE TITLE
java.lang.ClassNotFoundException: kotlin.coroutines.Continuation

### ISSUE THREAD

**Issue by idoflax** [Kotlin/kotlinx.coroutines#2212]
```
Exception in thread "main" java.lang.NoClassDefFoundError: kotlin/coroutines/Continuation
        at java.lang.Class.getDeclaredMethods0(Native Method)
        at java.lang.Class.privateGetDeclaredMethods(Class.java:2701)
        at java.lang.Class.privateGetMethodRecursive(Class.java:3048)
        at java.lang.Class.getMethod0(Class.java:3018)
        at java.lang.Class.getMethod(Class.java:1784)
        at sun.launcher.LauncherHelper.validateMainClass(LauncherHelper.java:544)
        at sun.launcher.LauncherHelper.checkAndLoadMain(LauncherHelper.java:526)
Caused by: java.lang.ClassNotFoundException: kotlin.coroutines.Continuation
        at java.net.URLClassLoader.findClass(URLClassLoader.java:382)
        at java.lang.ClassLoader.loadClass(ClassLoader.java:418)
        at sun.misc.Launcher$AppClassLoader.loadClass(Launcher.java:355)
        at java.lang.ClassLoader.loadClass(ClassLoader.java:351)
        ... 7 more
```
I'm getting the error while executing a jar built by gradle, not when running the program in IntelliJ. I'm not using spring or any framework.
It seems that the Continuation interface appears twice, once in kotlin-stdlib
![Screenshot 2020-08-24 at 13 03 54](https://user-images.githubusercontent.com/10278950/91038245-c1943b00-e60a-11ea-97d9-ee07fad9853d.png)

and once in kotlin-stdlib-common
![Screenshot 2020-08-24 at 13 04 23](https://user-images.githubusercontent.com/10278950/91038282-cbb63980-e60a-11ea-9e63-81207ed65f5f.png)

both of which come from the same dependency
![Screenshot 2020-08-24 at 13 06 54](https://user-images.githubusercontent.com/10278950/91038304-d40e7480-e60a-11ea-8b9a-1bb78f26fa60.png)

Gradle:
```
plugins {
    id 'java'
    id 'org.jetbrains.kotlin.jvm' version '1.3.72'
}

group 'com.something'
version '1.0-SNAPSHOT'

repositories {
    mavenCentral()
}

ext {
    ktorVersion = '1.3.1'
}

dependencies {
    implementation group: 'org.jetbrains.kotlin', name: 'kotlin-stdlib-jdk8'
    implementation group: "io.ktor", name: "ktor-client-apache", version: "${ktorVersion}"
    implementation group: "io.ktor", name: "ktor-client-jackson", version: "${ktorVersion}"
    implementation group: "io.ktor", name: "ktor-client-auth-jvm", version: "${ktorVersion}"
    implementation group: 'com.fasterxml.jackson.module', name: 'jackson-module-kotlin'
    implementation group: 'io.github.microutils', name: 'kotlin-logging', version: '1.8.3'

    testImplementation group: 'org.junit.jupiter', name: 'junit-jupiter-api', version: '5.7.0-M1'
    testImplementation group: 'org.jetbrains.kotlin', name: 'kotlin-test-junit5', version: '1.3.72'
    testImplementation group: 'io.mockk', name: 'mockk', version: '1.10.0'
    testImplementation group: 'org.assertj', name: 'assertj-core', version: '3.16.1'
    testImplementation group: 'com.github.tomakehurst', name: 'wiremock', version: '2.26.0'

}

compileKotlin {
    kotlinOptions.jvmTarget = "1.8"
}
compileTestKotlin {
    kotlinOptions.jvmTarget = "1.8"
}

jar {
    manifest {
        attributes 'Main-Class':'com.something.normailzer.Normalizer'
    }

    from { configurations.compile.collect { it.isDirectory() ? it : zipTree(it) } }
}
```

**Comment by idoflax** [comment]
Update: Changing
`implementation group: 'org.jetbrains.kotlin', name: 'kotlin-stdlib-jdk8'`
to
`compile group: 'org.jetbrains.kotlin', name: 'kotlin-stdlib-jdk8'`

Fixes it, but it's a mystery to me why

**Comment by LouisCAD** [comment]
Then changing it to `api` (which is not deprecated) would also fix the issue, but I agree that it's strange.

That said, it's likely not an issue in kotlinx.coroutines but in Kotlin, which has an issue tracker: kotl.in/issue, or Gradle, or both.

Does the issue reproduce with Kotlin 1.4 and kotlinx.coroutines 1.3.9?

**Comment by idoflax** [comment]
@LouisCAD I actually tried api already and strangely it also doesn't work
I agree it's not an issue with coroutines but rather with how the stdlib is set up

**Comment by LouisCAD** [comment]
What about Kotlin 1.4?

**Comment by romrell4** [comment]
I'm getting this same issue, but using maven.

Kotlin 1.4
kotlinx-coroutines-core 1.3.9

`java.lang.NoClassDefFoundError: Could not initialize class kotlinx.coroutines.BlockingEventLoop`

Any ideas?

**Comment by tallnato** [comment]
I had the same problem after upgrading to Kotlin 1.4.0, then removed the dependency ```implementation "org.jetbrains.kotlin:kotlin-stdlib:$kotlinVersion"```(since it is not needed now) and upgraded mockk version, and it started working 🤔

**Comment by qwwdfsad** [comment]
Does problem still persists with Kotlin 1.4?

**Comment by frynet** [comment]
it works: (pay attention to jar task)
	
	plugins {
		application
		kotlin("jvm") version "1.6.10"
	}

	group = "org.example"
	version = "1.0-SNAPSHOT"

	application {
		mainClass.set("org.example.MainKt")
	}

	repositories {
		mavenCentral()
	}

	dependencies {
		implementation("io.ktor:ktor-client-core-jvm:1.6.7")
		implementation("io.ktor:ktor-client-cio-jvm:1.6.7")
	}

	tasks {
		jar {
		    manifest {
		        attributes["Main-Class"] = application.mainClass
		    }

		    duplicatesStrategy = DuplicatesStrategy.EXCLUDE

		    configurations.compileClasspath.get().forEach {
		        from(if (it.isDirectory) it else zipTree(it))
		    }
		}

		compileKotlin {
		    kotlinOptions.freeCompilerArgs += "-opt-in=kotlin.ExperimentalStdlibApi"
		    kotlinOptions.jvmTarget = JavaVersion.VERSION_1_8.toString()
		}
	}

**Comment by LouisCAD** [comment]
@frynet Wrong issue?

**Comment by frynet** [comment]
> @frynet Wrong issue?

yeah, I had the same problem with "kotlin/coroutines/Continuation" when tried to run 'gradle assemble' task
