### ISSUE TITLE
[Feature Request] Java synchronize()-like synchornization

### ISSUE THREAD

**Issue by tom5079** [Kotlin/kotlinx.coroutines#2220]
AFAIK, `Mutex` is the best way to work with when it comes to synchornization.  
But it is quite inconvenient to keep track of all the `Mutex` instances.  
it would be nice if we had some automatic `Mutex`-keeping mechanism.

Here's an untested sample implementation
```kotlin
private val mutextMapMutex: Mutex()
private val mutexMap = mutableMapOf<Int, Mutex>()

suspend fun <T> synchronized(obj: kotlin.Any, action: () -> T): T {
    val hash = obj.hashCode()
    
    return coroutineScope {
        val mutex = mutextMapMutex.withLock {
            mutexMap[hash] ?: Mutex().also { mutexMap[hash] = it }
        }
        
        mutex.withLock(action = action)
    }
}
```

which will make a code like this run on a `CoroutineScope`
```kotlin
synchronized(this) {
    ... Do something
}
```

**Comment by elizarov** [comment]
Can you, please, explain a bit more on why would you actually need this kind of a feature? What kind of code do you write where this need comes up?

**Comment by tom5079** [comment]
Currently, java `synchronized` is [broken in coroutines](https://blog.danlew.net/2020/01/28/coroutines-and-java-synchronization-dont-mix/), so I thought it would be convineint to have `synchronized` method that uses Mutex in order to make it work in coroutines.

**Comment by itsandreramon** [comment]
You could actually rely on first party support for this using actors in coroutines and mutate your data safely using CSP.

**Comment by fvasco** [comment]
Hi, @tom5079,
I addressed this issue here https://github.com/Kotlin/kotlinx.coroutines/issues/1382#issuecomment-532262334
That solution allow to use the same mutex for multiple resource without further modification, moreover it forces to use the mutex.

**Comment by tom5079** [comment]
I thought there might be several other solutions though.
They are good an all, but what's wrong with the idea of having working `synchronized` in coroutines?

**Comment by elizarov** [comment]
@tom5079 
> I thought there might be several other solutions though.
> They are good an all, but what's wrong with the idea of having working `synchronized` in coroutines?

It's not the question of right or wrong. It's the question of why. Why would you need it? What kind of code do you write that needs it? What's your use-case for this feature?

**Comment by tom5079** [comment]
Because it's a part of the [Java language specification](https://docs.oracle.com/javase/specs/jls/se8/html/jls-14.html#jls-14.19), it should be work as intended.

According to the specification,
> `While the executing thread owns the lock, no other thread may acquire the lock.`

by specification, [this](https://blog.danlew.net/2020/01/28/coroutines-and-java-synchronization-dont-mix/) should not happen.

Maybe I think I chose the wrong name for the issue, I'm considering it as a bug, not an additional feature to add.

**Comment by tom5079** [comment]
Oh, that example might be running on the same thread. It's not a bug then. Thanks!
