### ISSUE TITLE
Stop requiring JDK 6 to run tests

### ISSUE THREAD

**Issue by LouisCAD** [Kotlin/kotlinx.coroutines#2224]
Hello, I'm working on #2213 and I get this on a machine that runs macOS Catalina (10.15.6), where it's not possible to install JDK 6 as far as I know:

```
> Task :kotlinx-coroutines-core:cleanJvmTest UP-TO-DATE
> Task :kotlinx-coroutines-core:checkJdk16 FAILED
FAILURE: Build failed with an exception.
* Where:
Build file '/Users/louiscad/Documents/GitHub/LouisCAD/kotlinx.coroutines/kotlinx-coroutines-core/build.gradle' line: 81
* What went wrong:
Execution failed for task ':kotlinx-coroutines-core:checkJdk16'.
> JDK_16 environment variable is not defined. Can't build against JDK 1.6 runtime and run JDK 1.6 compatibility tests. Please ensure JDK 1.6 is installed and that JDK_16 points to it.
```

Can you please drop this requirement? I think JDK 7 can do. Even better would be to have instructions depending on our OS in the error message to get setup without having to search on Google and focus back on whatever we were doing.

**Comment by elizarov** [comment]
We don't require it anymore. Contribution docs were updated to more explicitly state it.

**Comment by LouisCAD** [comment]
Yep, I noticed, thank you for your action!
