### ISSUE TITLE
[Feature request] Add takeUntil operator

### ISSUE THREAD

**Issue by LouisCAD** [Kotlin/kotlinx.coroutines#2227]
`takeUntil { … }` would be almost the same as `takeWhile { … }`, but once the predicate evaluates to `true`, the last value (where the predicate evaluated to `true`) still passes through, and the upstream flow is then immediately cancelled.

**Comment by pacher** [comment]
Already implemented and released here #2065

**Comment by LouisCAD** [comment]
Thanks for pointing that, it's written very clearly why there's no such named operator. In the meantime I had found `transforWhile`, and it's not so bad. I think I'll use a semicolon to cut down 3 lines of code.
