### ISSUE TITLE
Common `Cancelable` interface?

### ISSUE THREAD

**Issue by ScottPierce** [Kotlin/kotlinx.coroutines#223]
I think it would be an improvement to align `Job`, `Deferred`, and `Channel` under a common `Cancelable` interface. It doesn't have to be named that, but I think it should be similar to the RxJava [Disposable](https://github.com/ReactiveX/RxJava/blob/2.x/src/main/java/io/reactivex/disposables/Disposable.java) interface, perhaps having the equivalent of 2 methods, `cancel`, and `isCancelled`. Perhaps it would be appropriate to break out the `isActive`, and `isCompleted` into their own interfaces as well?

Having a utility class that would be the equivalent of the [CompositeDisposable](https://github.com/ReactiveX/RxJava/blob/2.x/src/main/java/io/reactivex/disposables/CompositeDisposable.java) would be convenient as well.

I don't have a problem submitting a PR myself, I thought it appropriate to discuss this first though.

**Comment by JakeWharton** [comment]
What's the use of a composite container when you can provide a parent reference to create an aggregate? Or, put another way, what does it provide that creating a `Job` as a parent doesn't?

**Comment by ScottPierce** [comment]
Hmmm, do you mean like this:

```Kotlin
val job = Job()

launch(parent = job) {
  // ...
}

launch(parent = job) {
  // ...
}

job.cancel()
```

I hadn't considered that. It even has the `cancelChildren` method which is more or less equivalent to `CompositeDisposable#clear`. You are right. `CompositeDisposable` is unnecessary.

**Comment by ScottPierce** [comment]
That complicates this a little then. While unifying `Channel`, `Deferred`,  and `Job` under a common interface would still be useful in it's own right, I can't think of a way that it would be aware of children, and thus I'm not sure it could have methods like `cancelChildren` associated with it.

The goal I had in my mind would have been to use this common interface in a similar manner to how I've used `Disposable` previously, which is unifying all scoped items that need to be torn down behind it, and then adding them all to `CompositeDisposable`, and then calling `clear` on them in my lifecycled Android screens.

That's starting to feel like maybe that specific use-case would be best solved by a third party library that standardizes a cancel / dispose behavior, and then is integrated with this coroutine library. Thoughts?

**Comment by elizarov** [comment]
`Job` is coroutine's unifying cancellable entity. It is both cancellable and an aggregate, which is very convenient given coroutines' light-weight and ability to decompose a big job into smaller children jobs at any time. Btw, `Job` was initially named `Lifecycle` in a prototype implementation, but then renamed to a `Job`.

**Comment by ScottPierce** [comment]
`Channel` doesn't currently have any way to tie into Job, does it?

**Comment by elizarov** [comment]
Bare channel does not. There are `produce` and `actor` builders that tie the channel to the job. However, the  resulting "channel's job" is not currently exposed via public api.

**Comment by qwwdfsad** [comment]
Currently, `CoroutineScope` provides a mechanism for abstracting any computation/scope (whether it is an actor, job or a future), the new interface may add even more confusion, so I'd rather not to introduce it.
