### ISSUE TITLE
FATAL EXCEPTION: ForkJoinPool.commonPool-worker-3

### ISSUE THREAD

**Issue by Proxcentaur** [Kotlin/kotlinx.coroutines#2235]
I'm a beginner in Kotlin, when I was trying to use coroutines suddenly this error happended:
FATAL EXCEPTION: ForkJoinPool.commonPool-worker-3
java.util.ConcurrentModificationException

any suggestion?

**Comment by fvasco** [comment]
![Bug report](http://3.bp.blogspot.com/-i4P-QfIoUSE/T0dx50bJ53I/AAAAAAAAAcw/DzgWNO_KgBY/s1600/117+art+of+bug+reporting.png)
