### ISSUE TITLE
add `all` function

### ISSUE THREAD

**Issue by helmbold** [Kotlin/kotlinx.coroutines#2238]
To make Kotlin Flow more suitable for a wide range of tasks, I suggest to add an [`all` function like in Reactor](https://projectreactor.io/docs/core/release/api/reactor/core/publisher/Flux.html#all-java.util.function.Predicate-).

## Description

Emit a single boolean true if all values of this sequence match the Predicate.

## Signature

```kotlin
fun <T> Flow<T>.all(predicate(T) -> Boolean): Flow<Boolean>
```

**Comment by elizarov** [comment]
Can you, please, provide an example of how you're going to use it in some real code? Why would you need it for a flow?
