### ISSUE TITLE
add `buffer(duration)` function

### ISSUE THREAD

**Issue by helmbold** [Kotlin/kotlinx.coroutines#2240]
To make Kotlin Flow more suitable for a wide range of tasks, I suggest to add an [`buffer(Duration)` function like in Reactor](https://projectreactor.io/docs/core/release/api/reactor/core/publisher/Flux.html#buffer-java.time.Duration-).

## Description

Collect incoming values into multiple List buffers that will be emitted by the returned Flow every `bufferingTimespan`.

## Signature

```kotlin
fun <T> Flux<T>.buffer(bufferingTimespan: Duration): Flow<List<T>>
```

Consider to also implement:

```java
Flux<List<T>> buffer(Duration bufferingTimespan, Duration openBufferEvery)
```

**Comment by elizarov** [comment]
It looks like a duplicate of #1302. Please, take a look.

**Comment by helmbold** [comment]
@elizarov Yes, it is a duplicate.
