### ISSUE TITLE
CoroutineScope.ensureActive() documentation

### ISSUE THREAD

**Issue by tanmatra** [Kotlin/kotlinx.coroutines#2241]
The docs state what it "Throws IllegalStateException if the context does not have a job in it"
https://github.com/Kotlin/kotlinx.coroutines/blob/master/kotlinx-coroutines-core/common/src/CoroutineScope.kt#L229
But it delegates to CoroutineContext.ensureActive(), for which "This function does not do anything if there is no Job in the context"
https://github.com/Kotlin/kotlinx.coroutines/blob/master/kotlinx-coroutines-core/common/src/Job.kt#L593

**Comment by elizarov** [comment]
Good catch. Thanks
