### ISSUE TITLE
Flow.sample() - incorrect documentation example or bug

### ISSUE THREAD

**Issue by drinkthestars** [Kotlin/kotlinx.coroutines#2243]
The example provided in the docs for `Flow.sample(...)` does not seem to behave as the documentation states:

``` Kotin
    flow {
        repeat(10) {
            emit(it)
            delay(50)
        }
    }
    .sample(100)
    .collect { print("$it ")}
```

According to documentation, expected output: `1 3 5 7 9`
Actual output : `2 4 6 8` (sometimes even `2 4 6 8 9`)

However, `debounce`'s example works as documented when tested side-by-side here: https://pl.kotl.in/NS_M7Sx01

This could even be a bug with the playground, but it's weird that `debounce` works as expected in the same environment 🤔

**Comment by elizarov** [comment]
Thanks a lot! Timings here are indeed a bit unrealistic, so it only works under virtual time, not in reality. Will fix.

**Comment by drinkthestars** [comment]
Got it. Yes, definitely noticed that unit tests would pass, but behaves differently otherwise. Thanks @elizarov!
