### ISSUE TITLE
native-mt: InvalidMutabilityException when trying to read object

### ISSUE THREAD

**Issue by felipef0x** [Kotlin/kotlinx.coroutines#2248]
When trying to read a frozen object, the InvalidMutabilityException is thrown.
I'm using coroutines `1.3.9-native-mt`.

commonMain:
```kotlin
expect class PlatformImpl() : Platform {

    override val platformStr: String

}

abstract class Platform {

    abstract val platformStr: String

    init {
        CoroutineScope(Dispatchers.Default).launch {
            while (true) {
                println("platformStr: $platformStr")
                delay(1000)
            }
        }
    }

}
```

iosMain:
```kotlin
actual class PlatformImpl actual constructor() : Platform() {

    actual override val platformStr: String = UIDevice.currentDevice.run { "$systemName $systemVersion" }

}
```

Result:
```
Uncaught Kotlin exception: kotlin.native.concurrent.InvalidMutabilityException: mutation attempt of frozen kmm.app.shared.PlatformImpl@1b1d708
```
\
The result is the same if we change the line:
```kotlin
println("platformStr: $platformStr")
```
to
```kotlin
println("this: ${this@Platform}")
```
\
If we move the whole `init` code from `commonMain/Platform` to `iosMain/PlatformImpl`, the app runs perfectly and no exception is thrown.
\
\
I'm sharing the project, as it may be useful:
https://github.com/felipef0x/kmm-app

**Comment by felipef0x** [comment]
This is what's happening:

1. `Platform.init` is called (`PlatformImpl.platformStr` is not initialized yet)
2. `CoroutineScope.launch@Platform.init` is called and makes `PlatformImpl` frozen
3. `PlatformImpl.init` is called
4. `PlatformImpl.platformStr` tries to get initialized, but its parent is already frozen

Regarding the language model, in case an object is referenced in a CoroutineScope in its own initialization, would there be any issue if this behavior changes and make it freeze only after it gets initialized?

If so, this is what would happen:

1. `Platform.init` is called (`PlatformImpl.platformStr` is not initialized yet)
2. `CoroutineScope.launch@Platform.init` is called and `PlatformImpl` is flagged to get frozen after init
3. `PlatformImpl.init` is called
4. `PlatformImpl.platformStr` get initialized
5. `PlatformImpl` is frozen

**Comment by elizarov** [comment]
It has to be frozen as soon as the coroutine is launched. The general advice is to avoid launching coroutines in background threads from `init { ... }` blocks. Extract it into a separate `start()` function or something. This also a good rule to follow in general also prevents some tricky concurrency bugs on JVM.

**Comment by felipef0x** [comment]
Ok I see, I'll change my approach.
Thank you.
