### ISSUE TITLE
cancel() is not resolved in Flow Android

### ISSUE THREAD

**Issue by NurseyitTursunkulov** [Kotlin/kotlinx.coroutines#2249]
I am using Kotlin version 1.3.6 in android. I want to cancel flow at specific moment. From docs I found this solution 👍 
https://kotlinlang.org/docs/reference/coroutines/flow.html#flow-completion , there is a method: cancel(). But it is not resolved, how to fix it?

**Comment by elizarov** [comment]
You need to press Alt+ENTER in IDEA to import it. Also, each code example has a link to the full code with all the required imports. You can copy them from there. Does it help?

**Comment by NurseyitTursunkulov** [comment]
No It does not, Alt+ENTER offers only RxJava methods. If I use this code in Kotlin Playground it works, but not in Android. May be I need to install something ?

**Comment by elizarov** [comment]
Which specific example are you trying to do? Do have `kotlinx.coroutines` dependency added to your project? Which version?

**Comment by NurseyitTursunkulov** [comment]
I am making a TimeCounter :


```
var shouldTimerStop = false
fun startCountingTimer(leftSeconds: Int): Flow<Int> {
    shouldTimerStop = false
    return flow {
        for (i in leftSeconds downTo 0) {
            if (shouldTimerStop)
                return@flow
            delay(1000)
            emit(i)
        }
    }
}

fun stopCountingTimer() {
    shouldStop = true
}
```

Currently the solution is return from the flow under specific condition, but I think there is better way to do it.

implementation "org.jetbrains.kotlinx:kotlinx-coroutines-core:1.3.6"
    implementation "org.jetbrains.kotlinx:kotlinx-coroutines-android:1.3.6"
implementation "org.jetbrains.kotlin:kotlin-stdlib-jdk7:1.3.60"

**Comment by elizarov** [comment]
What's your problem with this code? What is not resolved here?

**Comment by NurseyitTursunkulov** [comment]
I can not use cancel()  function here:

```
var shouldTimerStop = false
fun startCountingTimer(leftSeconds: Int): Flow<Int> {
    shouldTimerStop = false
    return flow {
        for (i in leftSeconds downTo 0) {
             **cancel()**
            if (shouldTimerStop)
                return@flow
            delay(1000)
            emit(i)
        }
    }
}

fun stopCountingTimer() {
    shouldStop = true
}
```
also : 

```
    startCountingTimer(10).**cancellable()**.collect {
        if (it == 3) cancel()
        
    }
```

cancelable() is not resolved

**Comment by elizarov** [comment]
Yes, because `flow { ... }` does not provide `this: CoroutineScope` context unlike `runBlocking { ... }` and other builder. You can use `currentCoroutineContext().cancel()`. Does it help?

**Comment by NurseyitTursunkulov** [comment]
yes it helped with cancel(), but how to be with cancellable()?
```
 startCountingTimer(10).**cancellable()**.collect {
        if (it == 3) cancel()
        
    }

```

**Comment by elizarov** [comment]
Please, update your project to the most recent version 1.3.9

**Comment by NurseyitTursunkulov** [comment]
thank you very much!!!! may Allah guide you.
