### ISSUE TITLE
Missing class: java.lang.instrument.ClassFileTransformer

### ISSUE THREAD

**Issue by Anigif** [Kotlin/kotlinx.coroutines#2266]
When building our Android app in release mode with gradle (and thereby also R8), the task `minifyReleaseWithR8` gives the following warning: `Missing class: java.lang.instrument.ClassFileTransformer`

Removing the following line from the dependency list the warning dissapers, so I assume it's related to that module: `implementation "org.jetbrains.kotlinx:kotlinx-coroutines-android:1.3.9"`

Here's stats I hope help identifying the issue:
- targetSdkVersion: 30
- minSdkVersion: 23
- com.android.tools.build:gradle: 4.0.1
- Kotlin version: 1.4.10

I'm not sure if this is related to #2046 since the same class is mentioned. That issue is however for ProGuard and mentions other issues too.

**Comment by qwwdfsad** [comment]
We'll add a rule to ignore this problem in 1.4 release
