### ISSUE TITLE
Unable to remove DebugMetadata annotation with ProGuard

### ISSUE THREAD

**Issue by kober32** [Kotlin/kotlinx.coroutines#2267]
I have an app that is being obfuscated and shrunk by R8 (not a fullMode). Even after that the `kotlin.coroutines.jvm.internal.DebugMetadata` class is kept (obfuscated) above every class that is using coroutines.

As I went through the documentation and other issues, I found zero references about how to get rid of this annotation that (as names suggest) shouldn't be there on a release build.

The code after  the R8:

```java
    @nb1(c = "my.path.to.package.ActivationManager$removeActivationRemotely$2", f = "ActivationManager.kt", l = {286, 290}, m = "invokeSuspend")
    static final class g extends sb1 implements qc1<h0, ya1<? super d91>, Object> {
        private h0 j;
        Object k;
        Object l;
        Object m;
...
```

Is there a way how to get rid of it other than just getting rid of the coroutines altogether?

**Comment by elizarov** [comment]
It looks like an R8 problem. I'd suggest to report it to the R8 team.

**Comment by Thomas-Vos** [comment]
I have the following in my R8 rules that removes the annotation for me:
```
# Ensure the DebugMetadata annotation is not included in the APK.
-checkdiscard @interface kotlin.coroutines.jvm.internal.DebugMetadata
-assumenosideeffects public class kotlin.coroutines.jvm.internal.BaseContinuationImpl {
  private kotlin.coroutines.jvm.internal.DebugMetadata getDebugMetadataAnnotation() return null;
  public java.lang.StackTraceElement getStackTraceElement() return null;
  public java.lang.String[] getSpilledVariableFieldMapping() return null;
}
```
There is some more information in the following issue: https://issuetracker.google.com/issues/155947700

**Comment by qwwdfsad** [comment]
Please follow the linked issue on Google tracker, this is indeed an R8 problem

**Comment by vvb2060** [comment]
Should these rules be added to coroutines.pro?
https://github.com/Kotlin/kotlinx.coroutines/blob/11daf8253689606080940a5d09c82d77154f54bb/ui/kotlinx-coroutines-android/resources/META-INF/com.android.tools/r8-from-1.6.0/coroutines.pro#L17-L22
