### ISSUE TITLE
IO Dispatcher creates more than 64 threads

### ISSUE THREAD

**Issue by unnamedw** [Kotlin/kotlinx.coroutines#2272]
Annotation describes IO Dispatcher like this,

_It defaults to the limit of 64 threads or the number of cores (whichever is larger)._

As I understood, Maximum number of threads that can be created by Dispatchers.IO is up to 64 because I use only 6core and 12 threads CPU, but my result is a little bit tricky.

This is my code.

```
repeat(500) {
    CoroutineScope(Dispatchers.IO).launch {
        println(Thread.currentThread().name)
    }
}
```
and this is the result.

```
...

DefaultDispatcher-worker-18
DefaultDispatcher-worker-46
DefaultDispatcher-worker-17
DefaultDispatcher-worker-47
DefaultDispatcher-worker-69
DefaultDispatcher-worker-64
DefaultDispatcher-worker-66
DefaultDispatcher-worker-67
DefaultDispatcher-worker-68
DefaultDispatcher-worker-41

...
```
Why is threadpool count bigger than 64? 
Does that mean actual threads was created more than 64?

**Comment by qwwdfsad** [comment]
Thanks for pointing it out, I'll rephrase the doc a bit.

`Dispatchers.IO` shares underlying threadpool with `Dispatchers.Default`, so the number of simultaneous threads is 64 + #CORES_SIZE. In your particular example, underlying threadpool starts compensating all 64 IO threads with a few threads for potential tasks in `Dispatchers.Default`
