### ISSUE TITLE
DebugProbesKt.bin gets shipped in release apk

### ISSUE THREAD

**Issue by G00fY2** [Kotlin/kotlinx.coroutines#2274]
Not a big deal, but I am wondering if the Android build process should really add this to every release APK (gets placed into the root folder).

Tested with Android Studio 4.0.1 and 4.2.0 Canary 12 using the latest Kotlin and Coroutines Android plugins/libraries.

As a workaorund it should be safe to use 
```
packagingOptions {
  exclude 'DebugProbesKt.bin'
}
```
for release builds, right?

**Comment by elizarov** [comment]
Yes. It is safe to exclude. I wonder if we can also add the corresponding exclusion options directly to the library. Is it even possible?

**Comment by qwwdfsad** [comment]
Fixed by providing how-to documentation in 1.4.0

**Comment by G00fY2** [comment]
For everyone reading this, [this ](https://github.com/Kotlin/kotlinx.coroutines/commit/b82439e6b570249cfbd25622dc06cb0ec156c006#diff-b335630551682c19a781afebcf4d07bf978fb1f8ac04c6bf87428ed5106870f5)was added to the README.

**Comment by bubenheimer** [comment]
@qwwdfsad Can you clarify the how-to instructions, please? They are hard to actually understand and follow. They say "no loss of functionality", but it would appear that I will lose some mystery debug capabilities. The instructions appear to remove these capabilities from both release and debug builds, and not being a Gradle wiz, like most devs, I'm not sure how to limit this to only release builds. My guess, after some meddling, would be to put it in `android { buildTypes { release`, but I can't say whether that actually does the right thing.

Or maybe the Gradle snippet is usable exactly as written and meant in a "just trust us" sense? Does "DebugProbesKt.bin" get introduced only in release build dependencies? "Just trust us" is generally unwise for a dev. Please add additional explanation.

**Comment by qwwdfsad** [comment]
>but it would appear that I will lose some mystery debug capabilities.

Could you please elaborate on what exact part of debug functionality disappears when you are applying `packagingOptions
`? The instruction tells nothing about debugging capabilities of `kotlinx.coroutines` and explains that "a resource file that is not required for the coroutines to operate
normally and is only used by the debugger" (meaning IDEA debugger, not an application-level capabilities)

**Comment by bubenheimer** [comment]
The instructions given in the README say that the resource file is used by the debugger, suggesting that when I remove the resource file, the debugger will lose some functionality, which would be undesirable when debugging a debug build. I don't know what debug functionality is lost. Or is `DebugProbesKt.bin` just needed for some standalone debugger like jdb, and if I debug in IDEA or Android Studio, then I would not need the resource file?

Applying the lines from the instructions appears to remove this debugging functionality from both debug builds and release builds. Debug and release builds generally use the same Gradle build script. The instructions need to specify how to remove debugging functionality from release builds only, without also removing them from debug builds. Debug builds are specifically intended for debugging. One would want maximum debugging capabilities in this case and not lose any.

An Android Gradle Plugin expert at your organization may be able to solve this problem. @G00fY2 may know the answer, too.

**Comment by qwwdfsad** [comment]
`DebugProbesKt.bin` is needed to enable the builtin support for [coroutines debugger](https://www.jetbrains.com/help/idea/debug-kotlin-coroutines.html) in IDEA. This functionality does not work with Android debugging at all, so no debugging capabilities are lost.

**Comment by bubenheimer** [comment]
Great to know, thank you! Please add that to the README instructions to clarify why the file is safe to remove from all APKs. Developers generally need to know why something is the correct thing to do, not just be told to do something and take your word for it.
