### ISSUE TITLE
How to tell kotlin coroutine not call Thread.defaultUncaughtExceptionHandler

### ISSUE THREAD

**Issue by vipcxj** [Kotlin/kotlinx.coroutines#2275]
In my Thread.defaultUncaughtExceptionHandler, If it meet a unrecognized exception, it will kill the app. Because Thread.defaultUncaughtExceptionHandler is a last resort, I think it is reasonable. But it seems that kotlin coroutine will call defaultUncaughtExceptionHandler even if I catch the exception. Then my app always crash.
for example:
```kotlin
    suspend fun _switchBase(baseInfo: DomainInfo): Throwable? {
        return withContext(Dispatchers.IO) {
            try {
                ApiSource.instance.switchDomain(SwitchDomainParams(baseInfo.path!!)) // this is a suspend method from retrofit2. and it will throw the exception.
                domainPath = baseInfo.path!!
                domainId = baseInfo.id!!
                domainType = baseInfo.type!!
                domainName = baseInfo.name!!
                domainNumber = baseInfo.number!!
                return@withContext null
            } catch (t: Throwable) {
                return@withContext t // catched successful here. but the app will crash because defaultUncaughtExceptionHandler is invoked too.
            }
        }
    }

    suspend fun switchBase(baseInfo: DomainInfo) {
        _switchBase(baseInfo)?.also {
            throw it
        }
    }

    // we call this.
    suspend fun switchBase(): Boolean {
        if (isDomained()) {
            return try {
                switchBase(DomainInfo(domainId, domainType, domainNumber, domainName, domainPath))
                true
            } catch (t: Throwable) {
                false
            }
        }
        return false
    }
```

**Comment by elizarov** [comment]
Do you have a self-contained reproducer code/project that I could run to see the problem?

**Comment by vipcxj** [comment]
> Do you have a self-contained reproducer code/project that I could run to see the problem?

[The repo](https://github.com/vipcxj/kotlin-coroutine-cases)

**Comment by elizarov** [comment]
Thanks! I don't see how this is related to coroutines in any way, though. In your test, if I remove `suspend` modifier from `ApiService.testBaiDu()` function and remove the whole `runBlocking { ... }` from the test code and simply call `ApiSource.instance.testBaiDu()` without any use of coroutines I still get the same exception in the `UncaughtExceptionHandler`. 
It simply seems to be a feature (or a bug) of Retrofit that is not related to coroutines in any way.

**Comment by vipcxj** [comment]
> Thanks! I don't see how this is related to coroutines in any way, though. In your test, if I remove `suspend` modifier from `ApiService.testBaiDu()` function and remove the whole `runBlocking { ... }` from the test code and simply call `ApiSource.instance.testBaiDu()` without any use of coroutines I still get the same exception in the `UncaughtExceptionHandler`.
> It simply seems to be a feature (or a bug) of Retrofit that is not related to coroutines in any way.

After  I remove suspend modifier from ApiService.testBaiDu() function and remove the whole runBlocking { ... }, The console print
```
The exception should be catched here.
java.lang.IllegalArgumentException: Service methods cannot return void.
    for method ApiService.testBaiDu
	at retrofit2.Utils.methodError(Utils.java:54)
	at retrofit2.Utils.methodError(Utils.java:43)
	at retrofit2.ServiceMethod.parseAnnotations(ServiceMethod.java:36)
	at retrofit2.Retrofit.loadServiceMethod(Retrofit.java:202)
	at retrofit2.Retrofit$1.invoke(Retrofit.java:160)
	at com.sun.proxy.$Proxy0.testBaiDu(Unknown Source)
	at com.example.kotlin.retrofit2.TestKt.main(Test.kt:12)
	at com.example.kotlin.retrofit2.TestKt.main(Test.kt)

Process finished with exit code 0

```
UncaughtExceptionHandler is not called. The exception is catched.

**Comment by elizarov** [comment]
I also see "It should not be happened!!!" printed in this example. You can also declare `fun testBaiDu(): Call<Void>` and then do `ApiSource.instance.testBaiDu().execute()`. You'll also see "It should not be happened!!!".

**Comment by vipcxj** [comment]
> I also see "It should not be happened!!!" printed in this example. You can also declare `fun testBaiDu(): Call<Void>` and then do `ApiSource.instance.testBaiDu().execute()`. You'll also see "It should not be happened!!!".

No，still print and only print “The exception should be catched here.”

**Comment by vipcxj** [comment]
@elizarov any news? Since the exception is caught first by the kotlin coroutine, it should not be handled again by the default exception handler.

**Comment by elizarov** [comment]
I don't see exception being caught in coroutines. I see that exception happens in an internal Retrofit thread and gets reported to the uncaugth exception handle. There is nothing the code in `kotlinx.coroutines` can do about it.

**Comment by vipcxj** [comment]
> I don't see exception being caught in coroutines. I see that exception happens in an internal Retrofit thread and gets reported to the uncaugth exception handler. There is nothing the code in `kotlinx.coroutines` can do about it.

In my test case, the console show "The exception should be catched here." and "It should not be happened!!!". So the exception is catched by both uncaugth exception handler and coroutines. I think it should be only catched by one of them.
