### ISSUE TITLE
Coroutines basics Docs

### ISSUE THREAD

**Issue by codejunk1e** [Kotlin/kotlinx.coroutines#2279]
While reading the coroutines basics docs https://kotlinlang.org/docs/reference/coroutines/basics.html 

I noticed that a reference link to [" CoroutineScope"](https://kotlin.github.io/kotlinx.coroutines/kotlinx-coroutines-core/kotlinx.coroutines/-coroutine-scope/) interface leads to the ["coroutineScope"]( https://kotlin.github.io/kotlinx.coroutines/kotlinx-coroutines-core/kotlinx.coroutines/coroutine-scope.html) function.  

On the docs it reads like this, "Essentially, coroutines are light-weight threads. They are launched with launch coroutine builder in a context of some CoroutineScope." but the link on the "CoroutineScope" here leads to the [coroutineScope function](https://kotlin.github.io/kotlinx.coroutines/kotlinx-coroutines-core/kotlinx.coroutines/coroutine-scope.html), rather than ["CoroutineScope" interface](https://kotlin.github.io/kotlinx.coroutines/kotlinx-coroutines-core/kotlinx.coroutines/-coroutine-scope/) . 

Personally, I feel referencing the interface should be the right thing but I could be wrong.

**Comment by elizarov** [comment]
Thanks for the report! It is a bug in the kotlinlang.org website infrastructure. I've reported it here: https://youtrack.jetbrains.com/issue/KTL-166

**Comment by elizarov** [comment]
Turn out it is actually a problem here, fixing.
