### ISSUE TITLE
Lazy initialization of the parent job

### ISSUE THREAD

**Issue by elizarov** [Kotlin/kotlinx.coroutines#228]
Here is the use-case from Ktor http client. When request is created it creates `CompletableDeferred` for its result, but it does not yet has any context. Later on when request is executed it has to be attached to the context and the job of the context has to become its parent in the sense of parent-child relation between coroutines. So, there is a need for a public API to create parent-child relations between jobs after their creation.

We shall also consider having multiple parents via this kind of API, however use-cases for multiple parents are not apparent at this moment.

**Comment by qwwdfsad** [comment]
Won't fix
