### ISSUE TITLE
JS: Upload kotlinx-coroutines-core-js library to npm

### ISSUE THREAD

**Issue by elizarov** [Kotlin/kotlinx.coroutines#229]

**Comment by cah-andrewfitzgerald** [comment]
This has come up on slack on more than one occasion, and potentially makes coroutines much more difficult to make use of from javascript

**Comment by deviant-studio** [comment]
any news on this? i've just realized i stuck with my little react project :)

**Comment by elizarov** [comment]
`npm install kotlinx-coroutines-core`
