### ISSUE TITLE
Guidance on testing coroutines in commonTest or jsTest?

### ISSUE THREAD

**Issue by mikeholler** [Kotlin/kotlinx.coroutines#2290]
I'm trying to learn kotlin mulitplatform. I know I can use `kotlinx-coroutines-test` to test coroutines on the JVM, but unfortunately it does not appear to support the JavaScript runtime.

I've spend the last couple of hours looking all over the internet for best practices for testing coroutines in JS or multiplatform situations, but I can't find any good guidance. My questions are:

1. Can someone point me to either a code snippet or documentation for testing coroutines in Kotlin JS or mulitplatform?
2. Can we put that somewhere prominent for beginners to multiplatform like myself can easily find testing guidance?

**Comment by elizarov** [comment]
This issue has some working receipes. https://youtrack.jetbrains.com/issue/KT-19813
