### ISSUE TITLE
Crash using kotlinx-coroutines-core-js with React-Native

### ISSUE THREAD

**Issue by ScottPierce** [Kotlin/kotlinx.coroutines#230]
I'm getting the following crash when loading the `kotlinx-coroutines-core-js` library with React-Native:

```undefined is not a function (evaluating 'this.window_0.addEventListener('message',WindowDispatcher_init$lambda(this),true)```

This appears to be on line 1593 of the generated js file:
```
  function WindowDispatcher(window_0) {
    CoroutineDispatcher.call(this);
    this.window_0 = window_0;
    this.messageName_0 = 'dispatchCoroutine';
    this.queue_0 = new WindowDispatcher$queue$ObjectLiteral(this);
    this.window_0.addEventListener('message', WindowDispatcher_init$lambda(this), true);
  }
```

My guess is that this is happening because React-Native runs in an environment without a `window` object.

**Comment by elizarov** [comment]
It is was running without `window` there would have been no problem. It looks like it has a `window`, but it does not have `addEventListener` on its window. It is easy to fix (by checking for `addEventListener` function on the window in addition to the `window` itself).
