### ISSUE TITLE
Using BlockHound fails with exception in UncaughtExceptionHandler

### ISSUE THREAD

**Issue by fluidsonic** [Kotlin/kotlinx.coroutines#2301]
I don't get very far when trying to use BlockHound.
I think it's because printing exceptions to standard error in the default UncaughtExceptionHandler is considered IO and thus triggers BlockHound to throw an exception there.

```kotlin
BlockHound.builder()
	.with(CoroutinesBlockHoundIntegration())
	.install()
```
Soon after:
```
Exception: reactor.blockhound.BlockingOperationError thrown from the UncaughtExceptionHandler in thread "DefaultDispatcher-worker-9"
```

1.4.0-M1

**Comment by dkhalanskyjb** [comment]
What is the version of BlockHound that you're using? Deciding that writing to stderr is okay is a bit out of our scope, but BlockHound whitelisted the standard streams in `1.0.4-RELEASE`: https://github.com/reactor/BlockHound/releases/tag/1.0.4.RELEASE

**Comment by fluidsonic** [comment]
I was using 1.0.4.RELEASE

**Comment by dkhalanskyjb** [comment]
I see. You used the form
```kotlin
BlockHound.builder().install()
```
When invoked in such a way, BlockHound will not look for integrations on its own: https://github.com/reactor/BlockHound/blob/master/docs/customization.md, and whitelisting of the standard streams is provided as another integration. Could you try installing BlockHound like in the following snippet or without using a builder altogether?
```kotlin
// import reactor.blockhound.integration.StandardOutputIntegration

BlockHound.builder()
	.with(CoroutinesBlockHoundIntegration())
	.with(StandardOutputIntegration())
	.install()
```
