### ISSUE TITLE
Example code in languange guide may contain deprecated methods but never pointed out

### ISSUE THREAD

**Issue by michaelfyc** [Kotlin/kotlinx.coroutines#2305]
My Kotlin-coroutines-core version is 1.3.8. When I tried to run the example code at https://kotlinlang.org/docs/reference/coroutines/select-expression.html#selecting-on-close on my local environment, the IDE pointed out that method `onReceiveOrNull` has been deprecated. But it was never mentioned even on detailed [documentation page](https://kotlin.github.io/kotlinx.coroutines/kotlinx-coroutines-core/kotlinx.coroutines.channels/on-receive-or-null.html). Issue #1676 mentioned this a year ago, but it seems there is no better workaround even till now... 
I'm glad to see that Kotlin 1.4.0. is working on the exclusion of the deprecated experimental coroutines. Looking forward to the new documentation that highlights differences between versions.

**Comment by qwwdfsad** [comment]
Fixed in docs
