### ISSUE TITLE
Can not catch some Throwable in coroutine

### ISSUE THREAD

**Issue by Shinglem** [Kotlin/kotlinx.coroutines#2310]
This code would not work :
```
       try {
            suspendCancellableCoroutine<String> { cont: CancellableContinuation<String> ->
                cont.resumeWithException(Throwable("" , null))
            }

        } catch (e: Exception) {
            println("catched")
            e.printStackTrace()
        }

        println("pass")
```

The `catch` block an `println("pass")` are unreachable . 

All Throwable with the field `cause` is null have the same problem.

### version
kotlin 1.4.10
kotlinx-coroutines-jdk8 1.3.9

**Comment by fvasco** [comment]
Hi, @Shinglem,
can you explain the issue better?

The code never catches a `Throwable`.

This is a simpler reproducer:

    try {
        throw Throwable("", null)
    } catch (e: Exception) {
        println("catched")
        e.printStackTrace()
    }

    println("pass")

**Comment by qwwdfsad** [comment]
Indeed, it's enough to replace `catch (e: Exception)` with `catch (e: Throwable)`
