### ISSUE TITLE
Wrong parsing of return statement.

### ISSUE THREAD

**Issue by mr5z** [Kotlin/kotlinx.coroutines#2313]
Sorry if this is the wrong place to report this but I can't really find the correct site.
Here goes the issue anyway:

```Kotlin
    private fun test() : Boolean {
        return
            false
    }
```

This is not compiling in Android Studio with Kotlin v1.4.0-rc.

**Comment by fvasco** [comment]
> I can't really find the correct site

Take a look here https://kotlinlang.org/community/

Anyway, you wrote:

    private fun test() : Boolean {
        return // you cannot return Unit here, in Java this statement is "return;"
            false
    }

**Comment by mr5z** [comment]
@fvasco thanks! That's fair, but a bit of disappointed when I want to format my code with that style.
