### ISSUE TITLE
Coroutine -> Rx extensions don't `test()` properly

### ISSUE THREAD

**Issue by nukeforum** [Kotlin/kotlinx.coroutines#2317]
I'm trying to convert a rather large project to coroutines in a piecemeal fashion. In order to not break the existing API, I'm leaning on the Rx extensions to convert back to Rx just under the outer edge of the API. Unfortunately, this has broken all my tests. It seems like the underlying `Job` doesn't properly `yield()` and await the return of the subscription.

This fails:
```kotlin
class ExampleUnitTest {
    @ExperimentalCoroutinesApi
    val dispatcher = TestCoroutineDispatcher()

    @ExperimentalCoroutinesApi
    @Test
    fun testTest(): Unit = dispatcher.runBlockingTest {
        val testObserver = rxSingle(dispatcher) {
            stopper()
        }.test()

        yield()

        testObserver.apply {
            assertComplete()
            assertValue(4)
        }
    }

    private suspend fun stopper(): Int {
        delay(1000)
        return 4
    }
}
```

And this succeeds:
```kotlin
class ExampleUnitTest {
    @ExperimentalCoroutinesApi
    val dispatcher = TestCoroutineDispatcher()

    @ExperimentalCoroutinesApi
    @Test
    fun testTest(): Unit = dispatcher.runBlockingTest {
        val testObserver = rxSingle(dispatcher) {
            stopper()
        }.test()

        testObserver.awaitTerminalEvent()

        testObserver.apply {
            assertComplete()
            assertValue(4)
        }
    }

    private suspend fun stopper(): Int {
        delay(1000)
        return 4
    }
}
```

In any case, I would have expected that `test()` would be terminal and blocking in `runBlockingTest`.

Is there something I'm missing in order to utilize the coroutine locks correctly?

**Comment by elizarov** [comment]
Neither test works for me. However, if I replace `yield()` with `advanceTimeBy(1000)` in the first one then it passes as expected.

**Comment by nukeforum** [comment]
I wouldn't have expected to have to `advanceTimeBy(1000)`, but I guess that explicitly awaiting is the only way to achieve what I'm looking for. Thanks for looking into this @elizarov!
