### ISSUE TITLE
Room integration

### ISSUE THREAD

**Issue by elizarov** [Kotlin/kotlinx.coroutines#232]
See #231. We should provide an out-of-the box integration with Room either via an integration module (if that is possible in Room at all) or via a PR to the Room library.

**Comment by dmytrodanylyk** [comment]
Also, I would love to have extension functions for android `LiveData` to work with channels, not with `Observable`.

See [LiveData](https://developer.android.com/reference/android/arch/lifecycle/LiveData.html), [Observer](https://developer.android.com/reference/android/arch/lifecycle/Observer.html)

**Comment by Kernald** [comment]
There's work in progress (and a first stage released as of Room 2.1.0-alpha03) tracked here: https://issuetracker.google.com/issues/69474692

**Comment by elizarov** [comment]
I'm closing this issue as this integration work is being up on Google side.
