### ISSUE TITLE
Exception in actor not handled by CoroutineExceptionHandler

### ISSUE THREAD

**Issue by dkrivoruchko** [Kotlin/kotlinx.coroutines#233]
Please help to figure out what I'm going wrong?

        val handler = CoroutineExceptionHandler { _, ex ->
            Log.e("Handler", ex.toString())
        }

        launch(CommonPool + handler) {
            throw Exception("Exception in launch, handled by CoroutineExceptionHandler")
        }

        actor<Unit>(CommonPool + handler) {
            throw Exception("Exception in actor, NOT handled by CoroutineExceptionHandler")
        }

Exception in actor does not handled by CoroutineExceptionHandler.
Android
kotlin version = '1.2.21'
coroutine version = '0.22.2'

**Comment by elizarov** [comment]
Because `CoroutineExceptionHandler` any handles uncaught exception in `launch`. An `actor` does not have uncaught exception. An exception in actor is propagated to the actor's channel and the next attempt to send to the failed actor will fail.
