### ISSUE TITLE
[native-mt] runBlocking in Unit test with 1.3.9-native-mt or 1.3.9-native-mt-2 never exits

### ISSUE THREAD

**Issue by werner77** [Kotlin/kotlinx.coroutines#2335]
Consider the very simple unit test:

```
@Test
    fun coroutines() {
        runBlocking {
            withContext(Dispatchers.Main) {
                println("1")
                withContext(Dispatchers.Main) {
                    println("2")
                }
                println("3")
            }
            println("4")
        }
        println("5")
    }
```

This test runs and finishes fine on JVM or native with the main (non-mt) version, but with the mt version it hangs indefinitely.

**Comment by ntherning** [comment]
I have seen this deadlock too on iOS. I believe the problem with `runBlocking()` is that it is blocking the main thread without letting iOS process any blocks (coroutines) enqueued on the [native GDC main queue](https://developer.apple.com/documentation/dispatch/dispatchqueue/1781006-main). On iOS `Dispatchers.Main` uses this queue to asynchronously run coroutines.

I have experimented with making my own version of `runBlocking()` for my tests which uses `NSRunLoop.mainRunLoop.runUntilDate(...)` to give GDC a chance to process the queued blocks. It works, coroutines are run, but my understanding of coroutine internals is not deep enough to make it reliable (e.g. waiting for all descendant jobs to complete).

I see that there's a concept of an `EventLoop` in the coroutines internals which I don't fully understand. Perhaps a custom `EventLoop` impl for the iOS main thread could make `runBlocking()` pump the main thread run loop as needed and prevent the deadlocking?

**Comment by qwwdfsad** [comment]
`native-mt` is no longer supported and it is recommended to use regular releases of coroutines along with new memory model
