### ISSUE TITLE
Flow.collect doesn't receive any values

### ISSUE THREAD

**Issue by yandroidUA** [Kotlin/kotlinx.coroutines#2345]
I'm using `1.4.0` version of coroutines in android app.

Code where I'm invoke function that return `Flow` and `collect` values from that `Flow`:
```
    fun <T> signIn(
        context: Context,
        loginData: T,
        authenticationMethod: AuthenticationMethod<T, *>,
    ) = viewModelScope.launch(Dispatchers.Default) {
        this@SignInViewModel.authenticationMethod = authenticationMethod
        authenticationMethod.signInEmitting(context, loginData)
            .collect { status -> _loginStatusLiveData.postValue(Event(status)) }

        this@SignInViewModel.authenticationMethod = null
    }
```

Code for emitting values:

```
    fun signInEmitting(context: Context, signInData: T): Flow<AuthenticationStatus> = flow {
        emit(AuthenticationStatus.Loading)

        val validationResult = onSingInValidate(signInData)
        if (!validationResult.isOk) {
            // something happened
            emit(AuthenticationStatus.AuthenticationError(validationResult.errors))
            return@flow
        }

        val status = onSignIn(signInData)
        if (status is AuthenticationStatus.AuthenticationSuccess) {
            status.accountInfo?.let {
                FileUtils.writeFile(context, ACCOUNT_FILE, Json.encodeToString(AccountInfo.serializer(), status.accountInfo))
            }
        }
        emit(status)
    }

```

I'm sure that all emit functions is called (I saw this in debugger mode), and `signIn` (where I'm collecting items) is waiting for last item to be emitted and only than continue working, so it suspends, but I doesn't receive any value in `collect` 
function.
Please checkout this video, maybe it will be useful:

![Flow_problem](https://user-images.githubusercontent.com/46822605/97485057-47fa2f80-1962-11eb-9e2a-ad73871623cd.gif)

**Comment by yandroidUA** [comment]
Fixed after `Invalidate cache and restart` in Android Studio, but it's very strange behaviour. Something with library version and gradle cache or It's just random mistake?

**Comment by TheHemantKaushik** [comment]
I am also getting the same issue. It is only visible when I run my application on API 22 emulator and working fine on API 30 emulator. I have tried:
1. Invalidate cache and restart
2. Upgrade/downgrade Kotlin version

**Comment by dpreussler** [comment]
I have the same issue with API23 its working but not with 30
invalidate cached didnt seem to help

**Comment by elizarov** [comment]
Is there any chance to reproduce with some self-contained code?
