### ISSUE TITLE
Warning when collecting a flow to a MutableSharedFlow

### ISSUE THREAD

**Issue by ansman** [Kotlin/kotlinx.coroutines#2347]
Since `MutableSharedFlow` is a `FlowCollector` I thought it be nice if this was possible:
```kotlin
someFlow.collect(sharedFlow)
```
which it technically is but since the `collect` method of `Flow` is annotated with `@InternalCoroutinesApi` a warning is produced. I feel as if this should be allowed.

**Comment by elizarov** [comment]
Good point. Internal `collect` is a temporary technicality that we might be able to remove in the future. For now, you can use `sharedFlow.emitAll(someFlow)` to get the same effect without any warning. See here for more details: https://kotlin.github.io/kotlinx.coroutines/kotlinx-coroutines-core/kotlinx.coroutines.flow/emit-all.html

**Comment by ansman** [comment]
Ah, good point. Perhaps the warning can point you towards that method.

**Comment by ansman** [comment]
Closing this as `Flow.collect` is no longer labeled as internal.
