### ISSUE TITLE
Probably-leaking memory around coroutines debug instrumenter

### ISSUE THREAD

**Issue by mglukhikh** [Kotlin/kotlinx.coroutines#2348]
Reproduction: in Kotlin project, run `FirDiagnosticsSpecTestGenerated` using Gradle from IDEA interface (not from command line). After ~40% tests passed, you will first see slowdown and then tests begin to fail with "GC overhead limit exceeded". NB: when run from command line, tests are completed without problems. NB2: tests can be run one-by-one also without problems.

In memory snapshot I see that a lot of `FirCompisiteSymbolProvider`s are hold by `statics or constant pool of kotlinx.coroutines.debug.internal.DebugProbesImpl`. Looks like it points to some coroutine debug instrumenter problem.

**Comment by mglukhikh** [comment]
Looks like duplicate for https://github.com/Kotlin/kotlinx.coroutines/issues/2117

**Comment by elizarov** [comment]
It is fixed in `kotlinx.coroutines` version `1.3.8`. Which version you observe this problem on?

**Comment by mglukhikh** [comment]
1.3.7.

**Comment by qwwdfsad** [comment]
Investigated with Mikhail, Kotlin project used 1.3.7
