### ISSUE TITLE
When you merge two callbackFlows, call first, only one invokeOnClose is called

### ISSUE THREAD

**Issue by nachtien** [Kotlin/kotlinx.coroutines#2349]
Per this [slack discussion](https://kotlinlang.slack.com/archives/C1CFAFJSK/p1603910136235100), we wanted to take the first emitted response, then cancel any other outstanding requests.  Tested against 1.4.0, with the following code:

``` kotlin
merge(
    callbackFlow {
        delay(600)
        offer("Request 1 completed")
        awaitClose {
            println("Request 1 is now closed")
        }
    },
    callbackFlow {
        delay(500)
        offer("Request 2 completed")
        awaitClose {
            println("Request 2 is now closed")
        }
    }
)
    .first().also {
        println(it)
    }
```

Expected:
``` text
Request 2 is now closed
Request 1 is now closed
Request 2 completed
```

Actual:
``` text
Request 2 is now closed
Request 2 completed
```

**Comment by qwwdfsad** [comment]
It behaves as expected.
Your second callback flow emits the value `Request 2 is now closed`, it is passed to the downstream `first` operator and `first` operator immediately cancels the upstream as soon as the first element arrives.
Thus, the first callback flow (which sleeps in the `delay`) function is immediately cancelled and `delay` function throws `CancellationException`. The `awaitClose` function is not even reached in your code
