### ISSUE TITLE
viewmodelscope.launch shows partial code coverage in sonarqube

### ISSUE THREAD

**Issue by yuvaraj119** [Kotlin/kotlinx.coroutines#2351]
At the function getDetails(str) viewModelScope.launch it shows partially covered in sonarqube. 
Not able to figure out how to cover.

It shows 1 of 3, so there are 3 cases that have to be covered in JUnit.

Assumption:
1 case - it can be the success of the launch - do(green)
2 case - it can be a failure - how to make viewModelScope.launch fail in JUnit?
3 case -?

function getDetails(string)=viewModelScope.launch {
//some code
}

Code in images links:- 
https://i.stack.imgur.com/X43OU.png
https://i.stack.imgur.com/QSmdy.png

StackOverflow link - https://stackoverflow.com/questions/64594799/viewmodelscope-launch-shows-partial-code-coverage-in-sonarqube

kotlinVersion = '1.4.10'
coroutinesVersion = '1.3.0'
Jacoco - 0.8.6 
sonarqube - 7.8

**Comment by qwwdfsad** [comment]
Sorry, we are not familiar with sonarqube. It's better to ask on sonarqube mailing-list/stackoverflow as it seems to be a coverage-specific issue, not `kotlinx.coroutines`-related one

**Comment by albka1986** [comment]
@yuvaraj119 
Have you found an answer? Your StackOverflow page doesn't exist anymore

**Comment by yuvaraj119** [comment]
> @yuvaraj119 
> Have you found any answer? Your StackOverflow page doesn't exist anymore

Yes by updating jacoco to latest version
