### ISSUE TITLE
Different behavior of offer() and tryEmit() without buffer (Channel and SharedFlow)

### ISSUE THREAD

**Issue by j2esu** [Kotlin/kotlinx.coroutines#2352]
Consider we have:
```
fun testFlow() = runBlocking {
    val numbers = MutableSharedFlow<Int>()
    numbers.onEach(::println).launchIn(GlobalScope)
    delay(500)
    numbers.tryEmit(0)
    delay(500)
}
```
This code prints nothing, so SharedFlow ignores tryEmit if it has no buffer. It will work with extraBufferCapacity >= 1 (or replay).
But if we do the same with Channel without buffer, the value will be printed:
```
fun testChannel() = runBlocking {
    val numbers = Channel<Int>()
    GlobalScope.launch { for (n in numbers) println(n) }
    delay(500)
    numbers.offer(0)
    delay(500)
}
```
This prints 0 as expected.

I think it's a little misleading and also breaking change when migrating from event channels to shared flows. Is this an intended behavior, or a bug? (kotlinx-coroutines-android:1.4.0)

**Comment by elizarov** [comment]
It is intended to be this way. Shared Flows are not Channels and are not intended to replace them. They are intended to replace BroadcastChannels which do behave in the same way &mdash; in the absence of subscription, all sent/emitted values are immediately dropped.

Does it help?

**Comment by j2esu** [comment]
Thanks for answer, but the code above is not an example of "absence of subscription" situation. SharedFlow in the first example has one subscriber (via launchIn(...)), but tryEmit() doesn't send items if no buffer specified.

**Comment by j2esu** [comment]
Intended behavior.  Docs [updated](https://github.com/Kotlin/kotlinx.coroutines/compare/1.4.1...master#diff-81e5d97455f3d34b04ad9bb54a5a079dc9f9841434fce5092d1b553aa504578e) in release [1.4.1](https://github.com/Kotlin/kotlinx.coroutines/releases/tag/1.4.1)
