### ISSUE TITLE
React-Native: `The provided value cannot be converted to a sequence.`

### ISSUE THREAD

**Issue by ScottPierce** [Kotlin/kotlinx.coroutines#236]
I'm seeing an error when running a react-native in the chrome browser. When react-native is running normally, it will use the `NodeDispatcher` and run the js on the device. When react-native is being debugged, it runs inside of Chrome, thus using the `WindowDispatcher`. I'm seeing an error when running the react-native javascript inside of a browser, that I don't see when running on the device.

Any thoughts? If you can point me in the right direction, I can submit another PR.

<img width="644" alt="screen shot 2018-02-10 at 2 30 49 pm" src="https://user-images.githubusercontent.com/871169/36066068-a1b62942-0e71-11e8-8685-203783d1e17a.png">

**Comment by elizarov** [comment]
Can you somehow set it up to use source maps to decode JS line offsets to the actual line number in the Kotlin source? That would greatly aid in figuring out what's going on there.
