### ISSUE TITLE
MutableStateFlow/StateFlow testing

### ISSUE THREAD

**Issue by NoNews** [Kotlin/kotlinx.coroutines#2373]
Hey, is there a way to test `MutableStateFlow` and `StateFlow` properly, without changing dependencies? (like replacement  to other implementation with  `flowOf` in test which is completes)

Example:

```
    @Test
    fun testStateFlow() = runBlockingTest {
        val flow = MutableStateFlow("")
        flow.collect {
            Assert.assertEquals("", it)
        }
    }
```

This part of code will have a result like `java.lang.IllegalStateException: This job has not completed yet`, as `StateFlow` and `MutableStateFlow` can't be completed. (It's clear)

Thanks!

**Comment by slavonnet** [comment]
I think you get infuinity collect for flow. Try getFist or take(1)

**Comment by denis-bezrukov** [comment]
You can take a look at https://github.com/cashapp/turbine 

then you can write
```
flow.test {
    Assert.assertEquals("", expectItem())
    cancelAndIgnoreRemainingEvents()
}
```

**Comment by qwwdfsad** [comment]
The final recommendation is to indeed using turbine library
