### ISSUE TITLE
mutex.withLock does not reliably release lock on cancellation.

### ISSUE THREAD

**Issue by Tilps** [Kotlin/kotlinx.coroutines#2380]
Playground here with close to minimal test case code.
https://pl.kotl.in/AGAyMv-l5

Running with Kotlin 1.4.10 it will output something like:
37,31,6
java.lang.IllegalStateException: Already locked by java.lang.Object@7c23b6a

With 1.3.72 it outputs:
26,26,0
java.lang.Exception

So it appears to be a regression.

The use of owner is not required, it just allows for the throwing of exception and counting failure frequency rather than hanging the entire test.

**Comment by Tilps** [comment]
As a note 
        mutex.withLock {
          	job.cancel()
        }
        job.join()
can be replaced with:
        mutex.withLock {
        }
        job.cancelAndJoin()
and it'll still fail, the failure frequency is a bit lower though.

**Comment by Tilps** [comment]
I've debugged this and found a solution, I think... Will prepare PR.

**Comment by Tilps** [comment]
I'll note this here, just a sight read of semaphore makes me suspect it has a similar problem.  But I've not created a test case, so I won't create a separate issue for that yet.

**Comment by qwwdfsad** [comment]
Fixed in 1.4.2, thanks!
