### ISSUE TITLE
"withContext" and "prompt cancellation guarantee"

### ISSUE THREAD

**Issue by yvolk** [Kotlin/kotlinx.coroutines#2383]
KDoc for the _withContext_ function ( https://github.com/Kotlin/kotlinx.coroutines/blob/865c229de80fd748e2c983d1f887b99c6e66ce64/kotlinx-coroutines-core/common/src/Builders.common.kt#L131 ) says:

> Note that the result of `withContext` invocation is dispatched into the original context in a cancellable way with a **prompt cancellation guarantee**,  
which means that if the original [coroutineContext], in which `withContext` was invoked, 
is cancelled by the time its dispatcher starts to execute the code,
it discards the result of `withContext` and throws [CancellationException].

But this example https://github.com/Kotlin/kotlinx.coroutines/blob/master/kotlinx-coroutines-core/jvm/test/guide/example-cancel-05.kt
 shows that even if the job is cancelled, "withContext" (in the finally block) starts normally.

I even checked this adding two lines inside finally block:

    ...
        } finally {
            println("Context in finally:  coroutineContext isActive:${coroutineContext.isActive}")
            println("Context in finally:  job isCancelled:${coroutineContext[Job]?.isCancelled}")
            withContext(NonCancellable) {
                println("job: I'm running finally")
    ...

and get this:

    Context in finally:  coroutineContext isActive:false
    Context in finally:  job isCancelled:true
    job: I'm running finally

As I understand, either documentation or behavior should be changed.

**Comment by yvolk** [comment]
Looks like copy-paste bug?!

**Comment by elizarov** [comment]
That's a subtle effect of a combination of `withContext` and `NonCancellable` and it works so by design. I'll see how it could be properly documented.
