### ISSUE TITLE
java.lang.ClassCastException: to `CoroutineStackFrame` at kotlinx.coroutines.internal.ScopeCoroutine.getCallerFrame(Scopes.kt:19)

### ISSUE THREAD

**Issue by willbuck** [Kotlin/kotlinx.coroutines#2386]
For library authors wishing to implement a custom `kotlin.coroutines.Continuation` class, casting to an internal class like `CoroutineStackFrame` is problematic. 

See, for example, this issue filed against micronaut:

https://github.com/micronaut-projects/micronaut-core/issues/4438

The error comes on this line, where micronaut has implemented `Continuation` with the `CompletableFutureContinuation` class

https://github.com/micronaut-projects/micronaut-core/blob/0afdef29d0a6b38b55dc39e3ef2a72bea85be45f/aop/src/main/java/io/micronaut/aop/internal/intercepted/KotlinInterceptedMethod.java#L123

I think the solve is to have `ScopeCoroutine` optionally cast `uCont` to `CoroutineStackFrame`, as `callerFrame` is nullable anyway (and it also seems like what other implementations of `CoroutineStackFrame`, like `SelectBuilderImpl` and `StackFrameContinuation` are doing).

I can work on adding a test to reproduce this issue and create a PR since I'm already in the weeds on it, will update once I do!

**Comment by qwwdfsad** [comment]
Thanks for the report! Filed https://youtrack.jetbrains.com/issue/KT-43395

This is indeed bug on our side worth fixing, but while we are here, I would strongly suggest implementing `CoroutineStackFrame` in `CompletableFutureContinuation` in the following way:

```
class CompletableFutureContinuation(private val continuation: Continuation<Any>) : Continuation<Any>, CoroutineStackFrame {

    override val callerFrame: CoroutineStackFrame?
            get() = continuation as? CoroutineStackFrame

    override fun getStackTraceElement(): StackTraceElement? = null
}
```

**Comment by willbuck** [comment]
@qwwdfsad thanks for the feedback! As far as we could tell, `CoroutineStackFrame` is an internal class, and thus would not be accessible outside of the `kotlinx.coroutines` module for Micronaut to extend it. Is that mistaken?-

**Comment by qwwdfsad** [comment]
`CoroutineStackFrame` is actually a public interface from kotlin stdlib, in the package `kotlin.coroutines.jvm.internal`.

While it may seem dangerous to implement it because it is internal, we are not going to change it because a lot of binary code already depend on it. The worst thing we can do is "deprecate it" with a replacement to the same very interface but in another package

**Comment by willbuck** [comment]
@qwwdfsad alright then, sounds like something to PR against micronaut :) thanks for the clarification!
