### ISSUE TITLE
Using lifecycleScope.launch** throw kotlinx.coroutines.JobCancellationException on fragment pop

### ISSUE THREAD

**Issue by alexanderhudym** [Kotlin/kotlinx.coroutines#2406]
Hello!!

I have a ViewModel

```kotlin
class MyViewModel: ViewModel() {
   private val itemsState = MutableStateFlow(listOf())
   private val  sharedItems = itemsState.shareIn(viewModelScope, SharingStarted.WhileSubscribed(), 1)
   val items: Flow<List<Item> = sharedItems
}
```

I want put items to adapter in fragment

When i use viewLifecycleOwner.lifecycleScope.launchWhenStarted or lifecycleScope.launchWhenStarted as recommended here https://developer.android.com/kotlin/flow/stateflow-and-sharedflow. It throws kotlinx.coroutines.JobCancellationException: Job was cancelled; job=SupervisorJobImpl{Cancelling}@9405731 when i want to pop fragment

When i use lifecycleScope.launch - the same result

But when i use launchIn(viewLifecycleOwner.lifecycleScope), as not recommended by android, no one error has occurred.

How can i fix this exception?

Thanks in advance!

**Comment by alexanderhudym** [comment]
up

**Comment by qwwdfsad** [comment]
This question doesn't seem to be about `kotlinx.coroutines` behaviour, but rather about coroutine usage in Android with lifecycle scopes (that are managed by the Android library).

I'd suggest you asking question in Slack or StackOverflow instead
