### ISSUE TITLE
Dispatcher.IO looks like better option for default dispatcher

### ISSUE THREAD

**Issue by SuperCatDev** [Kotlin/kotlinx.coroutines#2410]
After reading some RxJava articles i mentioned that all authors recommend use Schedule.computation only for hard CPU jobs, while Scheduler.IO looks as better option for everything else (IO operations itself, callbacks execution, data mutation etc) because execution doesn't stop if all continuation threads are busy. 

So my question is, why in coroutines default dispatcher is Dispatcher.Default? As I understand it has the same behavior as Scheduler.computation and it means same problems. Maybe I'm missing something. Can you explain please?

**Comment by fvasco** [comment]
`Dispatcher.Default` should be used for _reasonable_ short tasks, so an available `Thread` should be available in a _short_.

So, if all `Dispatcher.Default` are busy, this means that all CPU are busy, so there is no room to execute a new coroutine.
If you start another `Thread` for a CPU task, this new one have to compete for a CPU, it is not possible to execute two `Thread` on the same CPU simultaneously.

To run two `Thread`s on the same CPU, the scheduler have to run Thread1 for a short period of time, perform a context switch, run Thread2, context switch, Thread1, and so on...
Unfortunately the context switch costs, more Threads require more context switch, so lesser CPU time to perform computation.

So it is cheaper to run short CPU tasks in same `Default` dispatcher, to use `IO` for blocking tasks and to create custom dispatchers for long CPU tasks.

However this doesn't look as a library issue, so please prefer a proper channel for further question ;)

https://kotlinlang.org/community/#kotlin-online-resources

**Comment by SuperCatDev** [comment]
Thank you for rapid answer. But I still have some questions, so I've created new topic: https://discuss.kotlinlang.org/t/dispatcher-io-looks-like-better-option-for-default-dispatcher/20044
