### ISSUE TITLE
4-parameter version of `combine` does not use `combineUnsafe` 

### ISSUE THREAD

**Issue by alexvanyo** [Kotlin/kotlinx.coroutines#2419]
This is a strange discrepancy I noticed in [`Zip.kt`](https://github.com/Kotlin/kotlinx.coroutines/blob/0e67d0a89bc006305e71dbc905cc0a6c4cf562b6/kotlinx-coroutines-core/common/src/flow/operators/Zip.kt#L156), after the performance improvements of #2308. It looks like the 4 parameter version of `combine` wasn't updated to use `combineUnsafe`, unlike the 3 parameter and 5 parameter versions.

**Comment by qwwdfsad** [comment]
Good catch!

**Comment by alexvanyo** [comment]
I opened #2420 to fix this, ready to review at your convenience!

**Comment by alexvanyo** [comment]
Fixed via #2420
