### ISSUE TITLE
Upgrade to reactor 3.4.0

### ISSUE THREAD

**Issue by piyushmor** [Kotlin/kotlinx.coroutines#2432]
Spring Boot 2.4.0 uses project reactor version 3.4.0. We need to upgrade `kotlinx-coroutines-reactor` to use 3.4.0 version of project reactor for it to work with the new version of Spring Boot.

**Comment by qwwdfsad** [comment]
Unfortunately, we cannot do it right now because we are targeting Java 6, while Reactor `3.4.1` targets Java 8.
So we would like to postpone this update until we completely migrate to Java 8.

@sdeleuze do you have any objections against coroutines staying on `3.2.5.RELEASE`?

**Comment by piyushmor** [comment]
hope the cost is worth it, we will not be able to support Spring Boot 2 then. Especially because there are a lot of breaking changes in reactor 3.4.0

**Comment by sdeleuze** [comment]
I don't think we have changed the Java requirements, as far as I remember Reactor is Java 8+ from the beginning so IMO it should be possible to do the upgrade on `kotlinx-coroutines-reactor` unless I missed something.

**Comment by qwwdfsad** [comment]
Aha, thanks! It seems like we were compiling this module against Java 6 and reactor didn't have the corresponding Gradle metadata prior to 3.4.1. We'll update it in the next release

**Comment by piyushmor** [comment]
I am not sure if this does not warrant an early release

**Comment by qwwdfsad** [comment]
Fixed with https://github.com/Kotlin/kotlinx.coroutines/pull/2458
