### ISSUE TITLE
[QUESTION] `launch(Unconfined){...}` inconsistent behavior when used inside `runBlocking(Unconfined){...}`

### ISSUE THREAD

**Issue by revintec** [Kotlin/kotlinx.coroutines#2433]
```kotlin
fun main(){
    fun block(){
        GlobalScope.launch(Unconfined){print("1")}
        print("2")
    }

    block() // 12
    println()

    runBlocking{block()} // 12
    println()

    runBlocking(Unconfined){block()} // 21
    println()
}
```
the third example should output `12` instead it produces `21`
the `block(...)` function, using `Unconfined` dispatcher, should behave the same disregarding where it is called

using kotlin version 1.4.0, kotlinx-coroutines-core:1.4.2, both are the latest versions as of writing

**Comment by qwwdfsad** [comment]
Hi, this is not a bug, but a documented implementation detail.
Please take a look at the `Dispatchers.Unconfined` documentation, specifically at "Event Loop" part: https://kotlin.github.io/kotlinx.coroutines/kotlinx-coroutines-core/kotlinx.coroutines/-dispatchers/-unconfined.html
