### ISSUE TITLE
[Concurrency] withLock extension method raise sometimes java.lang.IllegalStateException Mutex is not locked 

### ISSUE THREAD

**Issue by Fgabz** [Kotlin/kotlinx.coroutines#2434]
Hello everyone, 

I'm currently having issue with the some concurrency code. I'm having a shared state in my app that can be accessed by multiple coroutine. The shared state is handled at the same time by Mutex method and actor, let me know if I should not doing this. 

Some example code

```
class StateRepository(private state stateStore: StateStore,
                                       private val service: Service,
                                       private stateReducer: StateReducer)  {

    private val mutex = Mutex()

    override suspend fun getCurrentState() =
        stateStore.getCurrentState()

    override suspend fun updateStateA(newState: State) {
          mutex.withLock {
              service.update(getCurrentState(), newState)
         }
     }

    override suspend fun updateStateB(newState: State) {
        mutex.withLock {
            service.update(getCurrentState(), newState)
        }
    }

    override suspend fun updateStateC(newState: State) {
        mutex.withLock {
            service.update(getCurrentState(), newState)
        }
    }

}
```

```
open class CoroutineScopeProvider {
    open val IOdefaultScope: CoroutineScope by lazy { CoroutineScope(Dispatchers.IO + SupervisorJob()) }
}

class StateStore @Inject constructor(
    private val scope: CoroutineScopeProvider
) : IStateStore, CoroutineScope by scope.IOdefaultScope {

    private var state: State? = null

    private var storeActor: SendChannel<StoreAction> = storeActor()

    override suspend fun updateCurrentState(state: State?): State? {
        storeActor().send(UpdateStore(state))

        controller.onStateUpdated(state)

        return state
    }

    override suspend fun getCurrentState(): State? {
        val response = CompletableDeferred<State?>()
        storeActor.send(GetCurrentState(response))

        return response.await()
    }

    private fun storeActor() = actor<StoreAction> {
        for (msg in channel) { // iterate over incoming messages
            when (msg) {
                is UpdateStore -> state = msg.state
                is GetCurrentState-> msg.response.complete(state)
            }
        }
    }
}

```

From what I see in my logs, the finally block in the MutexImpl is called to unlock whereas the mutex wasn't lock. I can' really understand what's happening.

Thanks in advance!

**Comment by qwwdfsad** [comment]
Your usages of the Mutex seems okay to me, both the general idea of protecting the state and the attached code.

But the provided information is not enough to locate the bug, whether it is in `kotlinx.coroutines` or in your code.
In general, our Mutex is really well-tested (both with stress tests and model checking), so it's likely that you have a `mutex.unlock` somewhere that does not have preceding `mutex.lock`

**Comment by Animeshz** [comment]
If you suspend the execution in non-single-threaded context, chances are the coroutine resumes in different thread than the one you expect it to. Hence if it doesn't holds the lock, you may run into concurrency problems.

Try to create sort of thread isolation or something if you want to suspend in such conditions.
