### ISSUE TITLE
Add Channel to common library

### ISSUE THREAD

**Issue by ScottPierce** [Kotlin/kotlinx.coroutines#244]
I noticed that channel isn't a part of the common library. I'm developing with the common coroutines library, and was wondering if there was a reason `Channel` is not a part of the common library?

If there is no reason, I'd be happy to contribute by submitting a PR to add it over.

**Comment by pull-vert** [comment]
Hi Scott, I think this is a duplicate of #201 :)

**Comment by ScottPierce** [comment]
Ah, thanks. Closing since this is a duplicate of #201.
