### ISSUE TITLE
Where can I get native 1.4.2 from?

### ISSUE THREAD

**Issue by andrasferenczi** [Kotlin/kotlinx.coroutines#2447]
I've followed the [link](https://search.maven.org/artifact/org.jetbrains.kotlinx/kotlinx-coroutines-core-native/1.4.2/jar) in the documentation, but it seems that neither `org.jetbrains.kotlinx:kotlinx-coroutines-core-native:1.4.2` nor `org.jetbrains.kotlinx:kotlinx-coroutines-core-native:1.4.2-native-mt` exists. the latest version I could find was `1.3.8` [here](https://dl.bintray.com/kotlin/kotlinx/org/jetbrains/kotlinx/kotlinx-coroutines-core-native/).

I am getting the following error when building in `gradle`:

```
     Searched in the following locations:
       - https://repo.maven.apache.org/maven2/org/jetbrains/kotlinx/kotlinx-coroutines-core-native/1.4.2/kotlinx-coroutines-core-native-1.4.2.pom
       - https://jcenter.bintray.com/org/jetbrains/kotlinx/kotlinx-coroutines-core-native/1.4.2/kotlinx-coroutines-core-native-1.4.2.pom
       - https://dl.bintray.com/kotlin/kotlinx/org/jetbrains/kotlinx/kotlinx-coroutines-core-native/1.4.2/kotlinx-coroutines-core-native-1.4.2.pom
```
Because I have all these repositories added to the `build.gradle.kts`:

```
repositories {
    mavenCentral()
    jcenter()
    maven(url = "https://dl.bintray.com/kotlin/kotlinx/")
}
```

So where can I find `1.4.2`, just as the `readme` says?

**Comment by andersio** [comment]
There is only one publication since 1.4.0. You only need to declare `kotlinx-coroutines-core` as a dependency in commonMain, and the platform artifacts would be automatically pulled in.
