### ISSUE TITLE
ConflatedBroadcastChannel as ReadWriteProperty

### ISSUE THREAD

**Issue by jcornaz** [Kotlin/kotlinx.coroutines#245]
Hello, 

In our code base, we found useful to define the folowing extension functions:
```kotlin
operator fun <T> ConflatedBroadcastChannel<T>.getValue(thisRef: Any, property: KProperty<*>): T = value

operator fun <T> ConflatedBroadcastChannel<T>.setValue(thisRef: Any, property: KProperty<*>, value: T) {
  offer(value)
}
```

They allow us to use the following pattern: 
```kotlin
class MyClass {
  private val _value = ConflatedBroadcastChannel(0)
  var value by _value 

  fun openValueSubscription() = _value.openSubscription()
}
```

May I ask what do you think about this ?
Do you think it is an anti-pattern ?
* If yes, why? And how would you achieve better generic observer pattern with coroutines?
* If no, what would you think about making `ConflatedBroadcastChannel` implement `ReadWriteProperty`?

**Comment by elizarov** [comment]
It is interesting. Can you share your project (or maybe some smaller playground project if cannot) via github to see it in a larger context?

**Comment by fvasco** [comment]
I have a similar issue, also.
I need to receive the `value`'s update starting by the current one.
Ie: the state of the `light` depends by the state of the `switch`.
In the `light` constructor i load the `switch` value, I set up its state and then I subscribe the channel.

```
class Light(switch : Switch) {
 init {
  val state = switch.value
  setup(value)
  launch {
   switch.channel.consumeEach { setup(it) }
  }
 }
}
```

This code is weak, I can lost an update during the first `setup` invocation.

**Comment by jcornaz** [comment]
Sorry, but I cannot share the project. Anyway it is not used a lot (yet) as we are really not sure if it is good design or not.

The idea is to achieve generic observer pattern. It is inspired of what we can do with JavaFx and [tornadofx](https://github.com/edvin/tornadofx/wiki/Properties):
```kotlin
class MyClass {
  val valueProperty = SimpleIntegerProperty(0)
  var value by valueProperty 
}

fun usage(obj: MyClass) {
  
  // get current (latest) value
  val currentValue = obj.value
  
  // subscribe
  obj.valueProperty.addListener { _, _, newValue -> println("new value: $newValue") }
}
```

And with a coroutines version I proposed in my first post, one could do:
```kotlin
fun usage(obj: MyClass) {
  
  // get current (latest) value
  val currentValue = obj.value
  
  // subscribe
  launch {
    obj.openValueSubscription().consumeEach { newValue -> println("new value: $newValue") }
  }
}
```

Actually I'm more asking:
1. "What do you think about this designs in a software using coroutines?"
2. "How do you achieve generic observer pattern with coroutines?"

**Comment by fvasco** [comment]
Regarding `setValue` you should consider the closed channel case.

Having something like the reactive `BehaviorSubject` fix your issue?

`ConflatedBroadcastChannel` should have the function:

    fun openSubscription(includeValue: Boolean = false): SubscriptionReceiveChannel

**Comment by jcornaz** [comment]
> Regarding setValue you should consider the closed channel case.

Yes, but there is not a lot to do. I don't see how I can do more than throwing an exception. To achieve it one would simply implement `setValue` with `sendBlocking(value)` instead of `offer(value)`.

But anyway, for this usage the broadcast wouldn't normally be closed, unless we knows that `setValue` will never be called again.

We indeed used `BehaviorSubject` with Rx to achieve it so far. Our goal is to replace usages `BehaviorSubject` by `ConflatedBroadacastChannel` and usages of `PublishSubject` by `BroadacastChannel`.

But there are no technical problem. From a technical point of view it does work as expected, and we don't have any issue. I'm really asking what you think about this design. And, if it appears it is a good design propose to implements `getValue` and `setValue` directly in `kotlinx.coroutines`.

**Comment by fvasco** [comment]
`getValue` and `setValue` are error prone in concurrent programming.

Your `usage` function have the same bug of my `Light` example (as said above, the issue is caused by load the current value outside the subscription).

**Comment by jcornaz** [comment]
> getValue and setValue are error prone in concurrent programming.

I agree. That's why an `openValueSubcription()` is provided. Or would you have a better alternative to propose?

> Your usage function have the same bug of my Light example (as said above, the issue is caused by load the current value outside the subscription).

No, because if one use `openValueSubscription` it will always start by the current value (as it is backed by a `ConflatedBroadcastChannel`). So one would use `getValue()` only if he want the current value and doesn't care if it may be outdated later. And one would use `openValueSubscription()` if he wants to subscribe to all values (including the current).

Note, that if the value changes many times quickly the listener may not receive all changes values but only the latest value. This is usually not a problem, as (in most cases) we only care about the most recent value.

**Comment by fvasco** [comment]
> That's why an openValueSubcription() is provided.

Sorry, I missed it.
I remain skeptical about using a `ConflatedBroadcastChannel` as a variable, this hides too much (purely personal opinion).

**Comment by fvasco** [comment]
Hi @jcornaz,
I took some time to think about this issue, unfortunately I didn't solve it, so I decided to share my opinion with you to understand better this problem.
I dump you some code with ugly names with the only purpose to be clear.

My use case requires an interface like this
```kotlin
interface ObservableVariable<T> {
    var value: T
    fun openValueSubscription(): SubscriptionReceiveChannel<T>
}
```
in such case delegate a variable to the `ObservableVariable` is a reasonable choice.
The `ObservableVariable` is like a regular variable and you can observe it, you cannot `close` or something similar.
Personally for my use case I use the `ObservableVariable` (mutable) and `ObservableValue` (read-only), so it is explicit the emitter and the receivers.

We can choose to implement `ObservableVariable` using `ConflatedBroadcastChannel` (my current implementation) or `ConflatedBroadcastChannel : ObservableVariable`.

First choice is pretty simple and safe.
Second choice is almost ready, `ConflatedBroadcastChannel.value` is a `val` but the change is pretty trivial.

What are the downside of the second choice.
`ConflatedBroadcastChannel` is a complex class, this is a personal opinion so I consider it a bad motivation against it.
`ConflatedBroadcastChannel` can be closed, this is not a great feature. Can I invalidate all variable references? (with great power comes great responsibility)
`ConflatedBroadcastChannel` is a read-write channel, damn! We have `SendChannel` and `ReadChannel` but both `BroadcastChannel` and `ConflatedBroadcastChannel` are read-write, is this a desing flaws?

Finally we should choose a good practice for a common case:

```kotlin
class MyClass(observableVariable: ObservableValue<Int>) {
    var double: Int

    init {
        double = observableVariable.value * 2
        launch {
            observableVariable.openValueSubscription().consumeEach {
                double = it * 2
            }
        }
    }
}
```

a simple solution should be:

```kotlin
class MyClass(observableVariable: ObservableValue<Int>) {
    var double: Int by observableVariable.mapValue { it * 2 }
}

```

Can you compare my considerations with you experience, please?
Thank you.

**Comment by jcornaz** [comment]
I have to say we came up with an interface like the one you proposed too. 

Our version of the `ObservableVariable` interface is just a bit more complex as it allows to subscribe to invalidation events too. (This is inspired from the [ObservableValue](https://docs.oracle.com/javase/8/javafx/api/javafx/beans/value/ObservableValue.html) interface of JavaFx). Being able to open invalidation subscription make possible to have lazy calculations. Nevermind, it doesn't change the design choice you propose.

Then I'd like to say, I really like the naming you used (`ObservableVariable` and `ObservableValue`). Though, I would rename them to `SubscribableVariable` and `SubscribableValue` to avoid confusion with JavaFx `ObservableValue`.

I personaly like the option of making `ConflatedBroadcastChannel` implement `ObservableVariable`. Even if I agree with your considerations (already complex, possibility to be closed), I think it is semantically what `ConflatedBroadcastChannel` already is. It does already provide a `value` read property and an `openSubscription()` which start by the current value. So making it implement this interface would only enforce this semantic and make it more clear. But it wouldn't change its implementation.

About the possibility to be closed, I would say like you "with great power comes great responsibility". I think it  fine to say that's the responsibility to the client code to have a correct usage of it. If one close a property and then try to update it, it should throw an exception. I totally agree with your point. But what else can we do?

>ConflatedBroadcastChannel is a read-write channel, damn! We have SendChannel and ReadChannel but both BroadcastChannel and ConflatedBroadcastChannel are read-write, is this a desing flaws?

Either I don't understand your point, or it is incorrect. `ConflatedBroadcastChannel` and `BroadcastChannel` are `SendChannel` only. They allow to open new `ReadChannel` via  `openSubscription()`, but they are not `ReadChannel`. Or am I missing something ?

Finally, I would use it like this: 
```kotlin
class MyClass(observableVariable: ObservableValue<Int>) {
    var double: Int

    init {
        launch {
	    // ConflatedBroadcastChannel.openValueSubscription() always start by the current value
            observableVariable.openValueSubscription().consumeEach {
                double = it * 2
            }
        }
    }
}
```

And I would rename `mapValue` by `map`.

But globally I'd say your proposition is going in a good direction (in my opinion). We already have something similar implemented in our code base (with two operators `map` and `combine`). So far, it works fine, and I am now aware of a better design.

**Comment by fvasco** [comment]
Well, really nice.

> Either I don't understand your point, or it is incorrect. ConflatedBroadcastChannel and BroadcastChannel are SendChannel only. They allow to open new ReadChannel via openSubscription(), but they are not ReadChannel. Or am I missing something ?

You are right, I try to explain it better adding `SubscribableChannel` and `ConflatedBroadcastChannel`.

```kotlin
interface SubscribableChannel<E> { // like ReceiveBroadcastChannel
    fun openSubscription(): SubscriptionReceiveChannel<E>
}

interface BroadcastChannel<E> : SendChannel<E>, SubscribableChannel<E> {
}

interface ConflatedSubscribableChannel<E> : SubscribableChannel<E> {
    val value: E
}

interface ConflatedBroadcastChannel<E> : BroadcastChannel<E>, ConflatedSubscribableChannel<E> {
    override var value: E
}
```

> It does already provide a value read property and an openSubscription() which start by the current value

Yes, whould be nice to preserve both behaviors.

**Comment by jcornaz** [comment]
Thanks @fvasco, I like the interfaces you propose.

I would only propose these changes:
* Rename `SubscribableChannel` by `Subscribable` and `ConflatedSubscribableChannel` by `ConflatedSubscribable` because they are not necessarily `Channel`. They only provide a way to open new channels.
* Add `out` variance for `SubscribableChannel` and `ConflatedSubscribableChannel`

And I would either:

Make `ConflatedSubscribable` implement `ReadOnlyPropery` and `ConflatedBroadcastChannel` implement `ReadWriteProperty`

 Or provide:
```kotlin
operator fun <T> ConflatedSubscribable<T>.getValue(thisRef: Any, property: KProperty<*>): T = value
operator fun <T> ConflatedBroadcastChannel<T>.setValue(thisRef: Any, property: KProperty<*>, value: T) { this.value = value }
```

**Comment by fvasco** [comment]
> Make ConflatedSubscribable implement ReadOnlyPropery and ConflatedBroadcastChannel implement ReadWriteProperty

I consider better extending the interface (your alternative).

**Comment by fvasco** [comment]
I notify this post regarding the "replay channel" (https://discuss.kotlinlang.org/t/replay-channel/6933): the `ObservableVariable` is, de facto, a similar to a regular `ConflatedBroadcastChannel` with `replay=1`.

**Comment by elizarov** [comment]
So far I like what I see here. You are welcome to send pull request with those interfaces. 

I also see that abstraction for cold streams (see #254) could implement the same interfaces and it should provide a lighter-weight implementation of those interfaces than `ConflatedBroadcastChannel`. This would allow for a lazier and lighter-weight implementation of combinators like `map` and `filter` in the future.

**Comment by jcornaz** [comment]
Hi @fvasco 
Yes, I've drafted a PR yesterday and I'd like to submit it tonight.

Just one think, may I suggest to use this naming scheme: `Subscribable`, `SubscribableValue` and `SubscribableVariable`?

I prefer this naming scheme for two reasons: First, `ConflatedBroadcastChannel` already exist and is a class, not an interface. Second, I think it is not very clear that `ConflatedBroadcastChannel` is the mutable version of `ConflatedSubscribable`.

**Comment by fvasco** [comment]
Hi @jcornaz,
can you write a draft to understand better your proposed changes?

Otherwise open a draft pull request to pin up some comments.

**Comment by jcornaz** [comment]
@fvasco Yes, I've open a draft PR. let's move this discussion there.
