### ISSUE TITLE
Coroutines: binary incompatibility between 1.3.9 and 1.4.2 on stable Flowable.asFlow api

### ISSUE THREAD

**Issue by danielesegato** [Kotlin/kotlinx.coroutines#2450]
What steps will reproduce the issue?

1. build a library using `Flowable.asFlow()` using dependency `org.jetbrains.kotlinx:kotlinx-coroutines-core:1.3.9` and compiling against kotlin 1.3.9
2. use the library from an app compiled against kotlin 1.4.2 (not sure if needed but, declare as dependency  `org.jetbrains.kotlinx:kotlinx-coroutines-core:1.4.2`)
3. compile and run the app ---> crash

I compiled the library with Kotlin, `kotlinx-corotuines-core`, and `kotlinx-coroutines-reactive` at version 1.3.9 and used it in a project that had all at 1.4.2 (Kotlin 1.4.21)

What is the expected result?
the library should work since the API was marked stable and binary compatibility between minors shouldn't break.

What happens instead?

```
    java.lang.NoSuchMethodError: No direct method <init>(Lkotlin/coroutines/CoroutineContext;I)V in class Lkotlinx/coroutines/flow/internal/ChannelFlow; or its super classes (declaration of 'kotlinx.coroutines.flow.internal.ChannelFlow' appears in /data/app/~~ccBt4dlqHFv3AkedliSnSw==/redacted.package.name.debug-QqdNYvkOKVfFKcKUHZwhVg==/base.apk!classes18.dex)
        at kotlinx.coroutines.reactive.PublisherAsFlow.<init>(ReactiveFlow.kt:51)
        at kotlinx.coroutines.reactive.PublisherAsFlow.<init>(ReactiveFlow.kt:50)
        at kotlinx.coroutines.reactive.ReactiveFlowKt.asFlow(ReactiveFlow.kt:30)
```

This is troubling to me, if Kotlin can't be trusted to maintain backward compatibility between 2 minor releases on stable API.

Related discussion on Slack: https://kotlinlang.slack.com/archives/C0922A726/p1607706898472000

I also reported this here but have been told this is a better place: https://youtrack.jetbrains.com/issue/KT-43903

**Comment by qwwdfsad** [comment]
Thanks!

Duplicating my YT answer here for a reference:

>I've been trying to reproduce your issue, but with no success.
It seems like you have a transitive dependency on an older version, but it's hard to say without a proper reproducer, could you please provide one?

**Comment by danielesegato** [comment]
@qwwdfsad I'll try to prepare a small project to reproduce as soon as I can (hope next week)

**Comment by danielesegato** [comment]
[coroutines-bug-2450.tar.gz](https://github.com/Kotlin/kotlinx.coroutines/files/5807587/coroutines-bug-2450.tar.gz)

Sorry for the huge delay @qwwdfsad attached you find a small project.

actually contains 2 android projects, a lib project and an app project.

you need to compile (`./gradlew assemble`) the lib project before running the app project the app project.

there's a direct reference from the app to the path of the aar assembled by the lib.

I could have probably put all together in a single project with library but I didn't tried.

**Comment by qwwdfsad** [comment]
Thanks for the reproducer!

It's actually not an incompatibility: the library compiled with coroutines 1.3.9 will be working with coroutines 1.4.2 without any problems. It's an [inconsistency](https://scans.gradle.com/s/ewqiixe4vd6hg/dependencies?toggled=W1swXSxbMCwzXSxbMCwxXV0) between versions: you depend on `core` module of version `1.4.2`, but `reactive` module version 1.3.9.

These two versions should be consistent. Also, filed #2494

**Comment by danielesegato** [comment]
> Thanks for the reproducer!

no problem! sorry it was with so much delay
 
> It's actually not an incompatibility: the library compiled with coroutines 1.3.9 will be working with coroutines 1.4.2 without any problems. It's an [inconsistency](https://scans.gradle.com/s/ewqiixe4vd6hg/dependencies?toggled=W1swXSxbMCwzXSxbMCwxXV0) between versions: you depend on `core` module of version `1.4.2`, but `reactive` module version 1.3.9.
> 
> These two versions should be consistent.

yeah my main concern with that is that the library using a wrapper for RxJava is an implementation details and an app using it end up with a cryptic runtime error message. The solution is to import a later library of the reactive module but you aren't supposed to need that, it's kind of a workaround.

> Also, filed #2494

completely agree with this one :)

**Comment by qwwdfsad** [comment]
>The solution is to import a later library of the reactive module but you aren't supposed to need that, it's kind of a workaround.

Agree, but alas, current libraries and build systems are really complex beasts :) 
Here is the pointer of how to fix version consistently: https://github.com/Kotlin/kotlinx.coroutines/issues/2307#issuecomment-766915345

I'll close this one and will try to mitigate this issue in via #2494, let's keep track of the progress there
