### ISSUE TITLE
`withTimeout()` fails to cancel its block in presence of a large number of coroutines

### ISSUE THREAD

**Issue by oakkitten** [Kotlin/kotlinx.coroutines#2469]
The following piece of code runs as expected and produces no output as all coroutines get cancelled:

```kotlin
import kotlinx.coroutines.*

fun main() = runBlocking {
    repeat(100) {
        launch { 
            withTimeout(50) {
                delay(1000)
                println("1000 < 50?!")
            }
        }
    }
}
```

But if you change `repeat(100)` to `repeat(10000)`, it prints hundreds of `1000 < 50?!`. ([Kotlin Playground](https://pl.kotl.in/J28vXJEwg))

I think it is reasonable to expect that if the delay is bigger than the timeout, it is always cancelled. In this example, `withTimeout` fails to cancel a delay that is whopping 20 times, or almost by a second, bigger than timeout. At the very least, this behavior should be documented.

(It seems that `withTimeout()` launches another task to cancel its block. Why not make the deadline a property of the scope instead?)

**Comment by qwwdfsad** [comment]
Thanks for the report. It seems like a hard-to-reproduce bug, I'm investigating

**Comment by oakkitten** [comment]
the code at the kotlin playground that i linked reproduces the issue 100% of the time on my machine. i think this is dependent on the speed of the scheduler so you can try increasing the number of coroutines or a slower machine in order to reproduce

**Comment by qwwdfsad** [comment]
Good to know! Still trying to reproduce it on my machine locally in order to properly debug it.
Could you please share the spec of your CPU where you are able to reproduce the problem?

**Comment by oakkitten** [comment]
it's thinkpad x220 with a i5-2520M cpu, win10/wsl

my snippet is using kotlin 1.4.10/jvm, which i guess was the latest at the time. if i choose 1.4.20, the issue cannot be reproduced. i went and tried reproducing the issue locally in kotlin/native and jvm, with no sucess; i tried `kotlin("multiplatform") version "1.4.10"` and `kotlin("jvm") version "1.4.10"` along with `implementation("org.jetbrains.kotlinx:kotlinx-coroutines-core:1.4.2")` but neither had the problem.

so the issue might've been fixed in 1.4.20? although it's a tad sus that i couldn't reproduce it locally

**Comment by qwwdfsad** [comment]
Hi, we've reworked coroutines cancellation here and there and touched the area related to timeouts as well.

I no longer can reproduce the issue, neither on my machines nor on playground. Could you please verify that for coroutines 1.5.1 the problem is gone?

**Comment by oakkitten** [comment]
i can't reproduce the issue in any way now, but then i could only reproduce it in the playground and with the 1.4.10/jvm option which is gone by now. i guess we can all pretend that it was a glitch in the matrix that is unlikely to manifest itself ever again :p

**Comment by qwwdfsad** [comment]
![whoa-deja-vu-matrix-glitch](https://user-images.githubusercontent.com/2780116/129807501-33c18a66-460f-443b-b321-d0f76310de97.gif)
