### ISSUE TITLE
Using the  coroutines on MacOS

### ISSUE THREAD

**Issue by mohnazemi** [Kotlin/kotlinx.coroutines#2475]
Hi guys,

I am new to Kotlin. I am using IntelliJ and tried to add the coroutines MacOS dependency in the Gradle file in my `build.Gradle.kts` file using the following line but I am not sure if I am doing the right thing:

    dependencies {
        implementation("org.jetbrains.kotlinx", "kotlinx-coroutines-core-macosx64",  "1.4.2")
    }

I can add the following line instead but then the coroutines features like `runBlocking` are not available when I want to import and use them. 

    implementation("org.jetbrains.kotlinx", "kotlinx-coroutines-core",  "1.4.2")

I am not sure what is the correct approach to get this working on the MacOS. Can someone please explain what is the correct approach?
Thanks

**Comment by elizarov** [comment]
If you are using Kotlin/JVM then you just depend on `kotlinx-corotines-core` regardless of which OS (macOS, Windows, Linux) you are working from. If you are using Kotlin/Native, then you should depend on ` kotlinx-coroutines-core-native`.

**Comment by mohnazemi** [comment]
Thanks a lot for your help, Roman. I managed to build my code
