### ISSUE TITLE
Missing package kotlinx.coroutines.experimental.android

### ISSUE THREAD

**Issue by shinayser** [Kotlin/kotlinx.coroutines#248]
I just create a new project and added this to the gradle file:

`compile org.jetbrains.kotlinx:kotlinx-coroutines-core:0.22.2`

The "launch" methods is working fine but I cannot do:

```
launch(UI) {    }
```
(it cannot find the "UI" val)

This was working on another project until I tried to remove this compile from my gradle and added it back. After that Android Studio is not able to find the "kotlinx.coroutines.experimental.android" package (specificaly the "android" part). Am I missing something?

**Comment by JakeWharton** [comment]
Yes, `kotlinx-coroutines-android`.

https://github.com/Kotlin/kotlinx.coroutines/blob/master/ui/kotlinx-coroutines-android/README.md

**Comment by shinayser** [comment]
This was removed from the core import? I have to add it manually?

**Comment by JakeWharton** [comment]
It was never in core as it's platform-specific.

**Comment by shinayser** [comment]
Weird, I am looking to my other project's code and its not added on the gradle file, only the core one. o.O
But anyways, I have added this to my gradle file:

`compile "org.jetbrains.kotlinx:kotlinx-coroutines-android:0.22.2"`

Now it is working. Thank you @JakeWharton.

**Comment by JakeWharton** [comment]
Are you using Anko? It might be pulled in transitively.

**Comment by elizarov** [comment]
Glad to see this resolved.

**Comment by HemendraGangwar** [comment]
I am facing this issue from a week, Can you please let me know why i am unable to find class Deferred,

**Comment by HemendraGangwar** [comment]
I am facing this issue from a week, can you please let me know why i am getting Failed resolution of: Lkotlinx/coroutines/experimental/Deferred;
