### ISSUE TITLE
test suspendable function in javascript with kotlin 1.4 with promise

### ISSUE THREAD

**Issue by henry1986** [Kotlin/kotlinx.coroutines#2481]
I'm trying to test a suspendable function in kotlin javascript, but the test stops before the suspendable function is actually executed. 

```kotlin
suspend fun toTest() = println("hello from test")

class TestJS{
    @Test
    fun test(){
        GlobalScope.promise { toTest() }
    }
}
```

I use promise, because I found some examples for older kotlin versions as

```kotlin
actual fun runTest(block: suspend () -> Unit): dynamic = promise { block() }
```

but the function "promise" seems not to exists for kotlin 1.4, or do I miss something?

**Comment by elizarov** [comment]
You need to write `fun test() = runTest { ... }` (mind the `=` sign) and your `runTest` function should use `GlobalScope.promise()`. Please, also follow and vote for the relevant YT issue: https://youtrack.jetbrains.com/issue/KT-22228

Does it help?

**Comment by henry1986** [comment]
I've upvoted the issue you posted.

With the `=` it works now. I've implemented:

```
actual fun runTest(block: suspend () -> Unit): dynamic = GlobalScope.promise { block() }

suspend fun toTest() {
    println("hello from test")
}
```
I did not expect, that this makes a difference: 
1. 
```
class TestJS{
    @Test
    fun test() {
        runTest {
            toTest()
        }
    }
}
```
2.
```
class TestJS {
    @Test
    fun test() = runTest {
        toTest()
    }
}
```

First example works, second doesn't. I assume my understandig of javascript is too small to be really able to comprehend this. But if I'm not misstaken, the "dynamic" keyword as return value of runTest is the reason, why 1 and 2 delivers different behaviour.
