### ISSUE TITLE
Should Job have a failed state?

### ISSUE THREAD

**Issue by Starcarr** [Kotlin/kotlinx.coroutines#249]
Currently, `Job` has this [states](https://kotlin.github.io/kotlinx.coroutines/kotlinx-coroutines-core/kotlinx.coroutines.experimental/-job/index.html):

- Created
- Active
- Completing
- Cancelling
- Cancelled
- Completed

While `Job`'s usage is common for background tasks that don't return anything, it is important to allow external observers of that `Job` to easily know the state in which it currently is. Currently there are three properties that will help with this.

```
job.isCancelled
job.isActive
job.isCompleted
```
This three properties will help the external observer to determine the current state from the initial list (minus _Completing_ which is an internal state whose signature is similar to that of _Active_).

But there's a state whose representation cannot be *easily* determined from the outside: An **exceptional completion**. Consider the following code:

```
fun main(args: Array<String>) = runBlocking {
    val job = launch {
        throw RuntimeException("Not ready!")
    }

    // wait for it to crash
    delay(200)
}
```
After the `delay` the status of  `job` is, as expected, _Completed_. This can be confirmed by looking at the previously mentioned properties:
```
println("cancelled [${job.isCancelled}]")   // -> false
println("active [${job.isActive}]")         // -> false
println("completed [${job.isCompleted}]")   // -> true
```
With the current implementation, then, someone wanting to know if the completion was exceptional or not will have to be forced to do one of this:

- change their code so that it uses `Deferred<Unit>`, thus gaining `isCompletedExceptionally`
- get the cancellation exception and validate that its message is different than "Job has completed normally"

The suggestion to improve this is:

- Have a `isCompletedExceptionally` property like `Deferred` does

**Comment by elizarov** [comment]
That is a tough design question. Your arguments are indeed compelling. However, please consider a solution that is outlined in #220. Would it ultimately reach the same goals for you use-cases?

**Comment by Starcarr** [comment]
I didn't see #220 before. I will close this and we can continue the conversation there. I think one single thread will help to clarify the goal for both sides –the internal implementation and what an external observer expects.
