### ISSUE TITLE
Dispatcher.IO coroutine in Docker container

### ISSUE THREAD

**Issue by nehalshah50** [Kotlin/kotlinx.coroutines#2490]
I have a gRPC service running in the docker container in the cloud. For every incoming gRPC streaming request, I launch a new coroutine under Dispatcher.IO scope as each request needs to make API call. When code runs in Mac or in Docker container on Mac all works fine and generates maximum available threads(default is 64 ---  DefaultDispatcher-worker-1 ... DefaultDispatcher-worker-64) but when the same docker container runs in the cloud it only works off of "DefaultDispatcher-worker-1" thread. 

Docker container/pods in the cloud gets 7milli cpu

**Comment by elizarov** [comment]
What kind of a library do you use to make an API call? Is it a blocking library or an asynchronous library? Why do use `Dispatchers.IO` for your use-case? Is there any change to reproduce this problem with some small self-contained code?
