### ISSUE TITLE
DefaultDispatcher needs public shutdown API for native-mt

### ISSUE THREAD

**Issue by projedi** [Kotlin/kotlinx.coroutines#2491]
[`DefaultDispatcher` global object](https://github.com/Kotlin/kotlinx.coroutines/blob/native-mt/kotlinx-coroutines-core/native/src/Dispatchers.native.kt#L12) creates [a `Worker`](https://github.com/Kotlin/kotlinx.coroutines/blob/native-mt/kotlinx-coroutines-core/native/src/Workers.kt#L40) in its `SingleThreadDispatcher` delegate and never shuts it down. This means that there's an active `Worker` left at the program shutdown, which is catched by Kotlin/Native memory leak checker.

To make memory leak checker do its job, `DefaultDispatcher` would need some public API to shut itself down, which can then be called in user code before program (or test) termination.

**Comment by qwwdfsad** [comment]
Closing as won't fix
