### ISSUE TITLE
QUESTION Combine multiple flows

### ISSUE THREAD

**Issue by P1NG2WIN** [Kotlin/kotlinx.coroutines#2499]
How can i do smth like this

    private val profileIntentFlow = MutableStateFlow(ProfileIntent())

    override fun getProfileIntent(): StateFlow<ProfileIntent> {
        userIntent(), interactionIntent(), skillsModel() - StateFlow

        return profileIntentFlow
            .combine(userRepo.userIntent(), interactionRepo.interactionIntent(), skillsRepo.skillsModel()) {
                user, interaction, skills ->

                ProfileIntent(
                    user,
                    interaction,
                    skills,
                )
            }

    }

**Comment by LouisCAD** [comment]
Use `stateIn` on the resulting flow returned by `combine`.

**Comment by P1NG2WIN** [comment]
> Use `stateIn` on the resulting flow returned by `combine`.
Dont understand how it can help me

**Comment by P1NG2WIN** [comment]
Done by this solution. Maybe it can be done better? 


    init {
        GlobalScope.launch {
            userRepo.userIntentFlow()
                .collect {
                    val profileIntent = profileIntentFlow.value

                    if (profileIntent.userIntent != it)
                        reduceProfileIntent { copy(userIntent = it) }
                }
        }

        GlobalScope.launch {
            interactionRepo.interactionIntentFlow()
                .collect {
                    val profileIntent = profileIntentFlow.value

                    if (profileIntent.interactionIntent != it)
                        reduceProfileIntent { copy(interactionIntent = it) }
                }
        }

        GlobalScope.launch {
            skillsRepo.skillsModelFlow()
                .collect {
                    val profileIntent = profileIntentFlow.value

                    if (profileIntent.skillsModel != it)
                        reduceProfileIntent { copy(skillsModel = it) }
                }
        }
    }

    private fun reduceProfileIntent(code: ProfileIntent.() -> ProfileIntent) {
        val newValue = code.invoke(profileIntentFlow.value)

        if (profileIntentFlow.value != newValue)
            profileIntentFlow.value = newValue
    }

**Comment by LouisCAD** [comment]
Your intial snippet was good, you just needed to call `stateIn` to convert the `Flow` into a `StateFlow`.

**Comment by P1NG2WIN** [comment]
> Your intial snippet was good, you just needed to call `stateIn` to convert the `Flow` into a `StateFlow`.

Does it really matter? Function return type is StateFlow. Anyway, combine function accept only two flows, not three

**Comment by LouisCAD** [comment]
The top level `combine` function accepts any number of flows you need.

Here's a great read for you:
https://kotlin.github.io/kotlinx.coroutines/kotlinx-coroutines-core/kotlinx.coroutines.flow/-flow/

**Comment by P1NG2WIN** [comment]
> The top level `combine` function accepts any number of flows you need.

Yes, i had a problem because i used Flow.combine extension insead of simple combine(flows...)
