### ISSUE TITLE
Add configurable buffer into Flow.produceIn()

### ISSUE THREAD

**Issue by neworld** [Kotlin/kotlinx.coroutines#2503]
Lets consider this code (using `1.4.2` version):
```kotlin
    @Test
    fun produceIn() = runBlockingTest {
        val channel = flow {
            repeat(500) {
                delay(100) // heavy load
                println("Emit $it")
                emit(it)
            }
        }.produceIn(this)

        println("receive from channel: " + channel.receive())
    }
```

The last lines it prints is:
```
...
Emit 63
Emit 64
Emit 65
```

It shows buffer is 64. I found buffer settings are defined in `ChannelFlowOperatorImpl` and there is no way to change them. Even `produceImpl` just uses settings from `ChannelFlowOperatorImpl`.

Actually, I expect `produceIn` do not use any buffer, and if I am needed one I could always: `flow.buffer(64).produceIn()`. But having a configurable buffer is also a good solution: `flow.produceIn(scope, buffer = 0)`.

### Use case

I am using `ReceiveChannel` to merge into the proper position of another flow:
```kotlin
launch {
  val channelB = flowB.produceIn(this)
  flowA.withIndex().transform { item -> 
    emit(item)
    if (item.index > 0 && item.index % 2 == 1)
      emit(flowB.receive())
  }.collect { /* something useful */ }
}
```

But I suppose configurable `produceIn` could help for more cases that involve expensive flow production. 

### Alternative

```
    fun <T> Flow<T>.produceInWithoutBuffer(coroutineScope: CoroutineScope): ReceiveChannel<T> {
        return coroutineScope.produce {
            val job = launch {
                collect { channel.send(it) }
                channel.close()
            }
            invokeOnClose { job.cancel() }
        }
    }
```

**Comment by qwwdfsad** [comment]
Please take a look at the documentation of `produceIn`: https://kotlin.github.io/kotlinx.coroutines/kotlinx-coroutines-core/kotlinx.coroutines.flow/produce-in.html:
```
A channel with default buffer size is created. Use buffer operator on the flow before calling produceIn to specify a value other than default and to control what happens when data is produced faster than it is consumed, that is to control backpressure behavior.
```

So what you want is to do the following:
```
@Test
fun produceIn() = runBlockingTest {
    val channel = flow {
        repeat(500) {
            delay(100) // heavy load
            println("Emit $it")
            emit(it)
        }
    }.buffer(42).produceIn(this)

    println("receive from channel: " + channel.receive())
}
```

The idea of the flow's buffering is that it's completely orthogonal, similarly to execution context: you don't have to specify context/buffer size in each operator that may leverage it, but instead just rely on `buffer` and our internal machinery will optimize and fuse everything for you

**Comment by neworld** [comment]
Seems, my experience with RxJava does not make any good here. `buffer(0)` works well and I like it. Thanks for the explanation!
