### ISSUE TITLE
Request: Map MutableStateFlow to StateFlow

### ISSUE THREAD

**Issue by andreimesina** [Kotlin/kotlinx.coroutines#2514]
Hi, I am trying to convert the generic type of a `MutableStateFlow` and expose it as a `StateFlow` using the `map` operator.

Unfortunately, `map` can only return a `Flow<R>`:

![image](https://user-images.githubusercontent.com/13933526/106535494-03e96e80-64ff-11eb-991c-1468499a8924.png)

I also imagine that adding `as StateFlow<Group` after the `map` isn't really a good idea. 
So, is there any solution for this case right now, or can we have a `map` that returns `StateFlow`?

**Comment by psteiger** [comment]
This has been discussed in #2008. Looks like the current way to deal with this is by using `stateIn` after `map`.

**Comment by andreimesina** [comment]
What if for instance we need to expose the `StateFlow` from a `Repository` pattern component and consume it upper in the hierarchy, in a `ViewModel`? 

We can't hold a `CoroutineScope` in the `Repository` to pass it to the `stateIn` operator, as the scope belongs to the `ViewModel` instead... is my point of view wrong?

**Comment by psteiger** [comment]
@andreimesina you can use a scope that matches the lifecycle of your repositories. In my case, the repositories are singletons, scoped to the whole application, and thus I use `ProcessLifecycleOwner.get().lifecycleScope` as the `CoroutineScope` for `shareIn` and `stateIn`.

Alternatively you can just construct your own `CoroutineScope` objects and use them. However, you might miss Lifecycle callbacks in your Repositories, either for canceling the scope, such as you would in `onDestroy` or `onCleared`, or even pausing/resuming the coroutines when your app is in background/foreground, such as `onStart` and `onStop`. Using scopes from Lifecycles (`LifecycleCoroutineScope`) handle that automatically.

My personal suggestion would be to build your architecture around the scopes automatically provided by `LifecycleOwner` components as it makes managing scopes easier.

**Comment by psteiger** [comment]
@andreimesina by the way, why not just using `asStateFlow()`?

**Comment by andreimesina** [comment]
@psteiger `asStateFlow()` is an extension on `MutableStateFlow`, whereas `map` and other operators return a `Flow`.

So we cannot do

```
val mutableStateFlow = ...

val stateFlow = mutableStateFlow.map {
    ...
}.asStateFlow()
```

Because there is no `asStateFlow()` for a simple `Flow`.

**Comment by qwwdfsad** [comment]
It is indeed not there because it has a lot of open design questions.
E.g. who should invoke the `map` operator, each collector or the upstream?

**Comment by qwwdfsad** [comment]
It is indeed not there because it has a lot of open design questions.

E.g. who should invoke the `map` operator, each collector or the upstream? Should it depend on whether the upstream state flow is a standalone object (just created via `StateFlow(...)` and emitted via `flow.value = 42`) or shared via `stateIn`?
What if mapping lambda suspends in the middle, how should the system behave? 
All these questions have controversial answers that conflict with each other.

As the potential solution, I'd recommend either using `stateIn` operator or basic delegation mechanism:
```
class MappedStateFlow<T, R>(private val source: StateFlow<T>, private val mapper: (T) -> R) : StateFlow<R> {

    override val value: R
        get() = mapper(source.value)

    override val replayCache: List<R>
        get() = source.replayCache.map(mapper)

    override suspend fun collect(collector: FlowCollector<R>) {
        source.collect(object : FlowCollector<T> {
            override suspend fun emit(value: T) {
                collector.emit(mapper(value))
            }
        })
    }
}
```

**Comment by pacher** [comment]
@qwwdfsad Basic delegation is not very good solution since `StateFlow` is not stable for inheritance.

**Comment by ansman** [comment]
Please note that although @qwwdfsad's mapped flow appears to work fine, it has a critical flaw that makes it behave differently than a real state flow, namely that only distinct items are emitted. So for example, if you have an upstream that emits a number and a downstream that emits if it's even or not, changing the upstream from `1` to `3` would emit `false` twice in a row. This might not matter for most people but might cause subtle issues.

An improved version might be:
```kotlin
private class MappedStateFlow<T, R>(
    private val upstream: StateFlow<T>,
    private val mapper: (T) -> R,
) : StateFlow<R> {
    override val replayCache: List<R>
        get() = listOf(value)

    override val value: R
        get() = mapper(upstream.value)

    override suspend fun collect(collector: FlowCollector<R>): Nothing {
        var previous: Any? = Unset
        upstream.collect {
            val value = mapper(it)
            if (value != previous) {
                previous = value
                collector.emit(value)
            }
        }
    }

    private object Unset
}
```

**Comment by silverhammermba** [comment]
@ansman I really like that solution. I recommend pairing it with a public extension function so it can be used everywhere without knowing about the wrapper class

```kotlin
fun <T, R> StateFlow<T>.stateMap(transform: (T) -> R): StateFlow<R> {
    return MappedStateFlow(this, transform)
}
```
