### ISSUE TITLE
Add support for watchosX64

### ISSUE THREAD

**Issue by fluidsonic** [Kotlin/kotlinx.coroutines#2524]
Kotlin 1.4.30 with the new `watchosX64` target has been released.
Coroutines should support it. 1.4.2 doesn't.

**Comment by RdeWilde** [comment]
For reference: https://github.com/Kotlin/kotlinx.coroutines/pull/2679

**Comment by fluidsonic** [comment]
Fixed with [1.5.0 release](https://github.com/Kotlin/kotlinx.coroutines/releases/tag/1.5.0)
