### ISSUE TITLE
volley function wrapped with suspendCoroutine never finishes

### ISSUE THREAD

**Issue by ArdentZeal** [Kotlin/kotlinx.coroutines#253]
Hello, 

I wrote following (test) function to talk to the google maps api via volley and with coroutines. Sadly it never finishes when calling it with the suspendCoroutine. If I use the same function, drop the coroutine stuff and implement a "normal" callback, everything works fine. I am kind of at a loss whats the problem here. Is anybody able to help?

Code executes until  Log.d(LOGTAG, "AFTERAFTER"), but never reaches Log.d("findNaturalLocations", "Response: " + response)

```kotlin
suspend fun testNaturalLocations(tag: Tag, lastKnownUserLocation: Location): ArrayList<CLDistanceRequest> = suspendCoroutine { continuation ->

        Log.d("findNaturalLocations", "getDistanceAndTimeBetweenLocations")

        var distanceRequests = ArrayList<CLDistanceRequest>()

        val mapsBaseUrl = "https://maps.googleapis.com/maps/api/place/nearbysearch/"
        val mapsOutputFormat = "json"

        val location = "location=" + lastKnownUserLocation.latitude.toString() + "," + lastKnownUserLocation.longitude.toString()
        val radius = "radius=5000"
        val keyword = "keyword=Supermarket"
        val name = "name=Supermarket"
        val sensor = "sensor=true"
        val apiKey = "key=API_KEY"

        val finishedUrl = mapsBaseUrl + mapsOutputFormat + "?" + location + "&" + radius + "&" + keyword + "&" + name + "&" + sensor + "&" + apiKey

        Log.d(LOGTAG, finishedUrl)

        val jsObjectRequest = JsonObjectRequest(Request.Method.GET, finishedUrl, null,
                Response.Listener<JSONObject> { response ->
                    Log.d("findNaturalLocations", "Response: " + response)

                    var results = response.getJSONArray("results")

                    // parse distanceRequests, ommitted for brevity

                    continuation.resume(distanceRequests)
                },
                Response.ErrorListener { error ->
                    Log.e("Error", error.localizedMessage, error)

                    continuation.resumeWithException(error)
                }
        )

        Log.d(LOGTAG, "AFTER");

        jsObjectRequest.setShouldCache(false)
        CLGlobal.getRequestQueue().add(jsObjectRequest)

        Log.d(LOGTAG, "AFTERAFTER");
    }
```

**Comment by elizarov** [comment]
Can you share some self-contained example/project that shows this problem?

**Comment by ArdentZeal** [comment]
Hello I made a minimal working example. The project was too big to attach as file, so you can find it here.
[https://github.com/ArdentZeal/coroutinetest](https://github.com/ArdentZeal/coroutinetest)

Problem seems to be related to the runBlocking {} part as it finishes without problems when just ommiting that.

I also opened a stackoverflow with some comments, maybe sth can be found there too. [https://stackoverflow.com/questions/48916892/suspending-a-kotlin-coroutine-does-not-work-with-volley?noredirect=1#comment84910591_48916892](https://stackoverflow.com/questions/48916892/suspending-a-kotlin-coroutine-does-not-work-with-volley?noredirect=1#comment84910591_48916892)

Kind Regards,
Matthias

**Comment by ArdentZeal** [comment]
After getting some help on Stackoverflow, I think I was just using it wrong by calling it with runBlocking {}
