### ISSUE TITLE
Merge flow in runtime?

### ISSUE THREAD

**Issue by stevepham** [Kotlin/kotlinx.coroutines#2548]
I have one case and don't know if flow supports this or how to solve it. Please everyone help me. My issue explains below:

I have a view and its render state from flowA. At one state of flowA, another flowB comes and I want also to collect flowB to render the state of the view. But seem flowA value lost. 

```
btnTest.setOnClickListener {
  lifecycleScope.launch {
    flowA().collect { num ->
      tvStatus.text = "$num" 
      if (num == 10) { // match condition to trigger flow B
        flowB().collect { // As I want here flowA will merge with flowB and emit value correctly but only flowB collected
      }
   }
}
```

**Comment by pacher** [comment]
`collect` is suspending function which suspend until the flow (flowB) is completed.

Off the top of my head you need something along the lines of:
```kotlin
flowA().flatMapMerge { num -> if (num == 10) flowB() else flowOf(num) }
```
but there might be a better way

**Comment by stevepham** [comment]
hi @pacher, both your solutions work well with my expectation. You save me a lot. Many thanks.
