### ISSUE TITLE
Clean up Android APIs for Java consumers.

### ISSUE THREAD

**Issue by JakeWharton** [Kotlin/kotlinx.coroutines#255]
I have to setup a class in Java which requires a coroutine context and it's a bit awkward having `HandlerContextKt.getUI()` instead of `HandlerContext.UI`. This is, of course, a binary-incompatible change so I'm mostly just proposing it for the eventual, non-experimental version of these libraries.

While a lot of coroutines can't be seen or used by Java, I don't think it's unreasonable to think that _some_ references will be present in mixed codebases. It's not too much effort to ensure that there's a decent experience when this happens. It certainly applies to more than just the Android parts.

Here's an example for `HandlerContext`: https://github.com/Kotlin/kotlinx.coroutines/compare/develop...JakeWharton:jakew/jvm-names/2018-02-21

**Comment by elizarov** [comment]
Thanks for adding this issue here. I have a note on my internal todo list for 1.0 release of the library "Review all top-level file names". However, I did, indeed, forgot about the need to think about appropriate @JvmStatic annotations to make it nicer for Java users where appropriate.
