### ISSUE TITLE
Misleading docs on `MutableStateFlow.emit` and `MutableStateFlow.tryEmit` methods

### ISSUE THREAD

**Issue by rmiller-glreaitylabs** [Kotlin/kotlinx.coroutines#2561]
## The Problem
The documentation for the `MutableStateFlow.emit` and `MutableStateFlow.tryEmit` functions are misleading. For example, the docs for `MutableStateFlow.tryEmit` appear as 
https://github.com/Kotlin/kotlinx.coroutines/blob/dda99e21f45f65eb540ccf4d5e82faf7559bc9e5/kotlinx-coroutines-core/common/src/flow/SharedFlow.kt#L161-L172
but in fact that method never blocks and always returns true, regardless of the `BufferOverflow` setting. 

## Why Does the Problem Exist?
In the source code for the actual definition of `MutableStateFlow`
https://github.com/Kotlin/kotlinx.coroutines/blob/dda99e21f45f65eb540ccf4d5e82faf7559bc9e5/kotlinx-coroutines-core/common/src/flow/StateFlow.kt#L319-L326
the `tryEmit` and `emit` methods are overridden so that (as far as I can tell) they never suspend. 

However, when the `MutableStateFlow` interface is defined, it inherits from the `StateFlow` and `MutableSharedFlow` interfaces:  
https://github.com/Kotlin/kotlinx.coroutines/blob/dda99e21f45f65eb540ccf4d5e82faf7559bc9e5/kotlinx-coroutines-core/common/src/flow/StateFlow.kt#L158

**The `tryEmit` and `emit` functions inherit the documentation from `MutableSharedFlow` despite having their behavior changed in the actual implementation of `MutableStateFlow`**

## A Possible Solution:

Add the overridden functions to the `MutableSharedState` interface with accurate documentation.

**Comment by qwwdfsad** [comment]
Fixed with #2560

**Comment by trevorhackman** [comment]
This still seems a bit confusing. Does this mean there's no reason to ever use emit with a StateFlow, you can always use tryEmit and get the same functionality with less restrictions?

**Comment by Burtan** [comment]
Is there any reason technical restriction that emit does not suspend until all collectors finished? Always using a SharedFlow when you want this functionality is a little cumbersome.
