### ISSUE TITLE
Error in Kotlin/JS (this.local$this$ChannelFlowTransformLatest.flow_0.collect_42ocv1$ is not a function)

### ISSUE THREAD

**Issue by Shabinder** [Kotlin/kotlinx.coroutines#2569]
![image](https://user-images.githubusercontent.com/44765050/110285169-dc5b5980-8008-11eb-93a5-6c3091da2f8c.png)

Everything works as Expected in JVM Targets like desktop and Android.

**Both Stack Traces Point to this :** 
![image](https://user-images.githubusercontent.com/44765050/110285864-e92c7d00-8009-11eb-84aa-cdd9a2834090.png)

if any other info needed, just ask , will try to help.

**Comment by fvasco** [comment]
Can you provide a simple reproducer?

**Comment by Shabinder** [comment]
there is no such small simple project right now, However this error occurs, after I execute following:
```

GlobalScope.launch(Dispatchers.Default){
  //Some Internet Requests etc
} 
```

**Comment by qwwdfsad** [comment]
Thanks! Closing this as it's not directly related to `kotlinx.coroutines` but rather a compiler bug
