### ISSUE TITLE
Free-form transform operation on ReceiveChannel

### ISSUE THREAD

**Issue by elizarov** [Kotlin/kotlinx.coroutines#257]
This idea is inspired by this question: https://discuss.kotlinlang.org/t/syntax-for-fluent-co-routines/6623

The proposal is to have a `transform` operator on `ReceiveChannel` that is basically a pipelineable version of `produce`, so that one can write:

```
channel.transform {
    // here is the code that is invoked once at the beginning
   for (x in inChannel) { // here we can iterate on the incomming channel
       // do something, filter, etc
      outChannel.send(...) // and send to the outgoing channel
   }
} // the result is the outChannel (ReceiveChannel) 
```

The design challenge here is naming `inChannel`/`outChannel`. Shall we just combine them both into a `channel` maybe? 

The related question/proposal is to have the same operation on a `Sequence` in a kotlin stdlib (a pipelineable version of `buildSequence`).

**Comment by fvasco** [comment]
> Shall we just combine them both into a channel maybe?

Please no.

_Transform this into that._

```kotlin
fun <I, O> ReceiveChannel<I>.transform(block: suspend ReceiveChannel<I>.(SendChannel<O>) -> Unit): ReceiveChannel<O>

fun main(args: Array<String>) = runBlocking<Unit> {
    val input: ReceiveChannel<String> = TODO()
    input.transform<String, Int> { output ->
        // here is the code that is invoked once at the beginning
        output.send(0)
        consumeEach { string ->
            output.send(string.length)
        }
        // here is the code that is invoked once at the end
        output.send(-1)
    }
}
```

**Comment by SolomonSun2010** [comment]
# KT-24223 Feature request: add the pipelines operators in Kotlin
https://youtrack.jetbrains.com/issue/KT-24223

**Comment by SolomonSun2010** [comment]
referenced:  KT-24223 Feature request: add the pipelines operators in Kotlin
https://youtrack.jetbrains.com/issue/KT-24223

**Comment by qwwdfsad** [comment]
I am closing this one.
We are not going to extend operators-like API for channels and for cold streams we have `transform` for exactly this purpose
