### ISSUE TITLE
extraBufferCapacity in SharedFlow does not work if there's no collector

### ISSUE THREAD

**Issue by diousk** [Kotlin/kotlinx.coroutines#2576]
I'm try to understand the behavior of SharedFlow, when I used `tryEmit` to emit value to a sharedFlow with **extraBufferCapacity** set to 1, the value can not be buffered.

the code snippet
```
fun main(args: Array<String>) = runBlocking<Unit> {
    var counter = 0
    val testFlow = MutableSharedFlow<Int>(extraBufferCapacity = 1)
	val job = launch (Dispatchers.Default) {
        delay(250)
        testFlow.collect {
        	println("time ${System.currentTimeMillis()} receive $it")
        }
    }
    repeat(3) {
        delay(100)
        val result = testFlow.tryEmit(counter++)
        println("time ${System.currentTimeMillis()} emit result $result")
    }
    
    delay(200)
    job.cancel()
    println("Done!")
}
```
and the result logs
```
time 1615343760971 emit result true
time 1615343761072 emit result true
time 1615343761172 emit result true
time 1615343761174 receive 2
Done!
```
I was expecting the fist value sent to the sharedFlow would be buffered and the subsequent tryEmit would return false 
and the collector will receive the first buffered value.

I also tried to use `emit` and the result is the same (the collector only receive the value sent after starting collect)

Is that an expected behavior?

**Comment by elizarov** [comment]
Yes. Buffering is designed to handle slow subscribers and only applies when there are any subscribers. We're going to clarify docs in #2560.
