### ISSUE TITLE
SharedFlow and flatMapLatest to work well with together in Kotlin/Native

### ISSUE THREAD

**Issue by seyedjafariy** [Kotlin/kotlinx.coroutines#2593]
We have a multiplatform project for Android and IOS. 
Most of our code is in a common module and our architecture is based on `Flow`.
[Reyan](https://github.com/islamversity/Reyan)

We came across this weird bug that blocks our `Flow`s from emitting every time we use `flatMapLatest` on our `SharedFlow`s.
This bug only happens in IOS, and it's not reproducible in Jvm or Android.

In short, all we need is a `SharedFlow` and a `flatMapLatest` operator on the chain to break the chain. none of the operators before or after the `flatMapLatest` will work and basically, the SharedFlow will stop emitting.

Here is a sample code in the main application:
[from](https://github.com/islamversity/Reyan/blob/b6f9b98bdc5396ffa339e5638464be1ffceb7d6a/core/src/commonMain/kotlin/com/islamversity/core/mvi/MviPresenter.kt#L46) - [to](https://github.com/islamversity/Reyan/blob/b6f9b98bdc5396ffa339e5638464be1ffceb7d6a/core/src/commonMain/kotlin/com/islamversity/core/mvi/MviPresenter.kt#L67)

[Emitting in Swift](https://github.com/islamversity/Reyan/blob/b6f9b98bdc5396ffa339e5638464be1ffceb7d6a/reyanIOS/reyan/Surah/SurahView.swift#L35)
[Collecting in Swift](https://github.com/islamversity/Reyan/blob/b6f9b98bdc5396ffa339e5638464be1ffceb7d6a/reyanIOS/reyan/QuranHome/SurahStateCollector.swift#L20)

I also managed to reproduce it in this Demo project which I guess makes the issue more visible and easier to understand.
[SharedFlowFlatMapLatest](https://github.com/worldsnas/SharedFlowFlatMapLatest)

[Common Module Flow Factory](https://github.com/worldsnas/SharedFlowFlatMapLatest/blob/9059b04a19f947e74c17a8c26b5fc4327e76c6fc/app/src/commonMain/kotlin/com/worldsnas/sharedflow/FlowFactory.kt#L5)
[Collecting and Emitting in swift](https://github.com/worldsnas/SharedFlowFlatMapLatest/blob/9059b04a19f947e74c17a8c26b5fc4327e76c6fc/FlowSample/FlowSample/ContentView.swift#L14)

here is the IOS console log output:

```
ContentView init
recieved from normal flow: 1
recieved from normal flow: 2
recieved from state flow: 2
```

**Comment by qwwdfsad** [comment]
Fixed with new memory model
