### ISSUE TITLE
Publisher.asFlow() wraps exception into another instance of same exception

### ISSUE THREAD

**Issue by klamborowski** [Kotlin/kotlinx.coroutines#2594]
While testing part of my code i found a bug in asFlow() for rxjava3. Exception thrown while collecting flow is another instance of it exception with original exception as cause.

build.gradle:
```
implementation 'org.jetbrains.kotlinx:kotlinx-coroutines-rx3:1.4.3'
testImplementation 'junit:junit:4.13.1
testImplementation "org.jetbrains.kotlinx:kotlinx-coroutines-test:1.4.1"
```

Test code:
```
import io.reactivex.rxjava3.core.Flowable
import kotlinx.coroutines.flow.collect
import kotlinx.coroutines.launch
import kotlinx.coroutines.reactive.asFlow
import kotlinx.coroutines.test.runBlockingTest
import org.junit.Assert.assertEquals
import org.junit.Test

class ExampleUnitTest {

    @Test
    fun test1() = runBlockingTest {
        val exception = RuntimeException(Throwable())

        val collectedItems = mutableListOf<Int>()
        val job = launch {
            try {
                Flowable.error<Int>(exception).asFlow().collect { collectedItems.add(it) }
            } catch (e: Exception) {
                assertEquals(exception, e)
            }
        }
        job.cancel()
    }
}
```

With breakpoint on `assertEquals` we can see issue - exception wrapped in new instance of this exception:
![obraz](https://user-images.githubusercontent.com/4972310/111810222-0e589f80-88d6-11eb-86d5-e7cde4a2ba10.png)

BUT!
If we change exception to our custom exception:
```
    class CustomException(cause: Throwable) : Exception(cause)

    @Test
    fun test1() = runBlockingTest {
        val exception = CustomException(Throwable())

        val collectedItems = mutableListOf<Int>()
        val job = launch {
            try {
                Flowable.error<Int>(exception).asFlow().collect { collectedItems.add(it) }
            } catch (e: Exception) {
                assertEquals(exception, e)
            }
        }
        job.cancel()
    }
```
    
After another breakpoint stop on assertEquals we can see the difference. It's working fine now and catched exception is same instance as original exception.

![obraz](https://user-images.githubusercontent.com/4972310/111810476-55469500-88d6-11eb-952c-938fef3c50dd.png)

Why is this happens? Why I've got so different result using almost the same code?

**Comment by elizarov** [comment]
This is "stacktrace recovery", which is a part of coroutines debugging. You can learn details here: https://github.com/Kotlin/kotlinx.coroutines/blob/master/docs/topics/debugging.md

Does it help?

**Comment by klamborowski** [comment]
@elizarov helps a lot, thanks :relieved: It was such a nondeterministic behaviour and seemed like a bug, but it works as it should. 😅
