### ISSUE TITLE
Sliceable dispatchers: Provide alternative to newSingle/FixedThreadPoolContext via a shared pool of threads 

### ISSUE THREAD

**Issue by elizarov** [Kotlin/kotlinx.coroutines#261]
### Background

`newFixedThreadPoolContext` is actively used in coroutines code as a concurrency-limiting mechanism.  For example, to limit a number of concurrent request to the database to 10 one typically defines:

```
val DB = newFixedThreadPoolContext(10, "DB")
```

and then wraps all DB invocation into `withContext(DB) { ... }` blocks.

This approach have the following problems:

* This `withContext(DB)` invocation performs an actual switch to a different thread which is extremely expensive.
* The result of `newFixedThreadPoolContext` references the underlying threads and must be explicitly closed when no longer used. This is quite error-prone as programmers may use `newFixedThreadPoolContext` in their code without realizing this fact, thus leaking threads.

### Solution

The plan is to reimplement `newFixedThreadPoolContext` from scratch so that it does not create any threads. Instead, there will be one shared pool of threads that creates new thread strictly when they are needed. Thus, `newFixedThreadPoolContext` does not create its own threads, but acts only as a semaphore that limits the number of concurrent operations running in this context. 

Moreover, `DefaultContext`, which is currently equal to `CommonPool` (backed by `ForkJointPool.commonPool`), is going to be redefined in this way:

```
val DefaultContext = newFixedThreadPoolContext(defaultParallelism, "DefaultContext")
```

> The current plan is to set `defaultParallelism` to `nCPUs + 1` as a compromise value that ensures utilization of the underlying hardware even if one coroutine accidentally blocks and helps us avoid issue #198 

Now, with this redefinition of `DefaultContext` the code that is used to define its own `DB` context continues to work as before (limiting the number of concurrent DB operations). However, both issues identified above are solved:

* This `withContext(DB)` invocation does not actually perform thread context switch anymore. It only switches coroutine context and separately keeps track of and limits the number of concurrently running coroutines in `DB` context.
* There is not need to close `newFixedThreadPoolContext` anymore, as it is not backed by any physical threads, no risk of leaking threads.

This change also affects `newSingleThreadContext` as its implementation is:

```
fun newSingleThreadContext(name: String) = newFixedThreadPoolContext(1, name)
```

> This _might_ break some code (feedback is welcome!) as there could have been some code in the wild that assumed that everything working in `newSingleThreadContext` was indeed happening in the single instance of `Thread` and used `ThreadLocal` for to store something, for example. The workaround for this code is to use `Executors.newSingleThreadExecutor().toCoroutineDispatcher()`.

This issue is related to the discussion on `IO` dispatcher in #79. It is inefficient to use `Executors.newCachedThreadPool().toCoroutineContext()` due to the thread context switches. The plan, as a part of this issue, is to define the following constant:

```
val IO: CoroutineContext = ...
```

> The name is to be discussed in #79 

Coroutines working in this context share the same thread pool as `DefaultContext`, so there is no cost of thread switch when doing `withContext(IO) { ... }`, but there is no inherent limit on the number of such concurrently executed operations.

> Note, that we also avoid issue #216 with this rewrite.

### Open questions

* Shall we rename `newFixedThreadPoolContext` and `newSingleThreadContext` after this rewrite or leave their names as is? Can we name it better? 

* Should we leave `newSingleThreadContext` defined as before (with all the context switch cost) to avoid potentially breaking existing code? This would work especially well if `newFixedThreadPoolContext` is somehow renamed (old is deprecated), but `newSingleThreadContext` retains the old name.

**UPDATE**: Due to backward-compatibility requirements the actual design will likely be different. Stay tuned.

**Comment by elizarov** [comment]
Unfortunately, the `Mutex` interface (with suspending `lock`) is not an appropriate abstraction to efficiently implement a coroutine dispatcher on top of it. The "semaphore" has to be an internal data structure tightly couple with the implementation of the corresponding dispatcher.

The appropriate value of  `defaultParallelism` is questionable, but I personally like `nCPUs+1` more than `max(nCPUs, 2)`, because the former is more regular, too.

The questions of a flexible thread-pool and blocking IO are indeed different, but it looks that they can be solved with a single implementation effort. We'll definitely start implementation with benchmarks and experiment with different strategies.

The idea is that similarly to FJP, this implementation is going to be "sticky" and will only move coroutines to another thread if absolutely necessarily. With respect to blocking operations it means that we'll give some time for a blocking operations to complete before moving all other coroutines to another thread. It seems to be the most efficient strategy based on our study of other languages and libraries, but we'll see how it actually works out in practice.

**Comment by fvasco** [comment]
Hi @elizarov,
thank you for quick response, I will stay tuned for updates.

Regarding Semaphore like a dispatcher I suspected your consideration too late, sorry for this miss.

However I consider a valid option to use a `Mutex` to limit the concurrent access to a resource, more appropriate than using a custom `CoroutineDispatcher`.

**Comment by fvasco** [comment]
> Should we leave newSingleThreadContext defined as before (with all the context switch cost) to avoid potentially breaking existing code?

I say yes, may be something like:

```kotlin
fun newDedicatedThreadDispatcher(
        threadPoolSize: Int = 1,
        threadFactory: ThreadFactory? = Executors.defaultThreadFactory()
): CoroutineDispatcher
```

**Comment by matejdro** [comment]
> newFixedThreadPoolContext is actively used in coroutines code as a concurrency-limiting mechanism.

> and then wraps all DB invocation into withContext(DB) { ... } blocks.

I'm a bit confused about this. Why is this approach better than defining `DB : Mutex`  object and wrapping all DB invocations into `DB.withLock { ... }` blocks?

**Comment by fvasco** [comment]
Regarding [my consideration above](https://github.com/Kotlin/kotlinx.coroutines/issues/261#issuecomment-368875602), now is available the issue #1088.

**Comment by justjake** [comment]
Hi, I saw the deprecation notice of https://kotlin.github.io/kotlinx.coroutines/kotlinx-coroutines-core/kotlinx.coroutines/new-single-thread-context.html

Is there a recommended, current way to execute coroutines with FIFO semantics? Specifically I need to sequence access of SQLite database to occur from a single thread.

**Comment by fvasco** [comment]
@justjake 

> Is there a recommended, current way to execute coroutines with FIFO semantics?

https://kotlin.github.io/kotlinx.coroutines/kotlinx-coroutines-core/kotlinx.coroutines.sync/-mutex/index.html

> Specifically I need to sequence access of SQLite database to occur from a single thread.

You should not use the coroutine.

**Comment by justjake** [comment]
@fvasco thank you for your reply. However I am now more confused: why is coroutines not the right tool here? My thought was that callers that require SQLite could await sub-operations dispatched to the SQLite dispatcher that uses only a single thread. Currently in my application this uses a concrete `SQLiteJob` with callbacks pushed into a queue, a Java ThreadPool, etc, which is cumbersome and already needs a `suspend` / `resume` to be used from coroutines.

**Comment by fvasco** [comment]
> why is coroutines not the right tool here?

It is possible to run multiple coroutine _concurrently_ on a single thread, but you want to "sequence access of SQLite database to occur from a single thread".

> which is cumbersome and already needs a suspend / resume to be used from coroutines

Put the logic in a function, example:

```
suspend fun <T> sqlContext(block: (Sqlite) -> T) : T =
  executor.submit{ block(sqlite) }.await()
```

**Comment by matejdro** [comment]
Any reason why would this executor be better than mutex?

**Comment by elizarov** [comment]
The reason is that it does a different thing than mutex:
* With mutex (or semaphore) you can limit _concurrency_. That is, you can limit how many _concurrent_ operations of a certain type your code is doing.
* With this limited dispatcher you can limit _parallelism_. That is, you can limit how many things your code does in parallel. This is all about CPU-resource allocation. You can limit how many CPU cores/threads this or that kind of code could consume or block.

**Comment by sschuberth** [comment]
>     * There is not need to close `newFixedThreadPoolContext` anymore, as it is not backed by any physical threads, no risk of leaking threads.

I'm really looking forward to this @elizarov. Is there any ETA / milestone for that feature?

**Comment by elizarov** [comment]
Sorry, I cannot give any specific ETA at the moment.

**Comment by alamothe** [comment]
Related: https://discuss.kotlinlang.org/t/coroutine-dispatcher-confined-to-a-single-thread/17978

I would need `newSingleThreadContext` implemented exactly in this way, to pick a thread from the default thread pool. 

Is there anything I could use in the meantime?

**Comment by elizarov** [comment]
@alamothe In the forum thread you ask:

> Is there such thing as a dispatcher which “picks one worker thread from a default pool and does not jump between threads”?

This is not what this proposal is supposed to do. In this proposal even with a limit of 1 thread it will still jump between threads, but it will ensure that at most 1 thread is used at any time.

**Comment by alamothe** [comment]
> but it will ensure that at most 1 thread is used at any time.

This is actually what I need. The requirement is to prevent unintentional multi-threading (because our code is not thread-safe). My original post didn't state this in the best possible way, but later I arrived at this conclusion.

Thanks for checking!

**Comment by Rosomack** [comment]
Is there any plan to support this for Kotlin/Native?

**Comment by elizarov** [comment]
**UPDATE**: Due to backward-compatibility requirements the actual design will likely be different. Stay tuned.

**Comment by AnonymousGeekDev** [comment]
Hello. Please, are there any updates on the design?

**Comment by qwwdfsad** [comment]
Closing this in the favour of https://github.com/Kotlin/kotlinx.coroutines/issues/2919

Let's continue our discussion there
