### ISSUE TITLE
MutableStateFlow value gives error "Val cannot be reassigned" on 1.4.3

### ISSUE THREAD

**Issue by jonolds** [Kotlin/kotlinx.coroutines#2610]
Android studio shows an error when you try to reassign value of a MutableStateFlow.  It highlights it in red but still allows it to compile.  You can reproduce it with the Advanced Coroutines Codelab at https://github.com/googlecodelabs/kotlin-coroutines/tree/master/advanced-coroutines-codelab 
by changing the coroutines version to 1.4.3.

![image](https://user-images.githubusercontent.com/30565402/112581865-9225f680-8dc4-11eb-94e4-7c18f37eb520.png)

**Comment by qwwdfsad** [comment]
If it compiles, but Android Studio reports an error, I'd suggest reporting it to AS bug tracker directly, it seems to be AS bug.
But it also worth re-importing the project and clearing the build cache first, to see if the problem is gone
