### ISSUE TITLE
Premain-Class missing in 1.4.3 causing debug failures in IntelliJ

### ISSUE THREAD

**Issue by deweyx** [Kotlin/kotlinx.coroutines#2619]
Related to [KTIJ-5659](https://youtrack.jetbrains.com/issue/KTIJ-5659), the 1.4.3 build of `kotlinx-coroutines-core` does not include `Premain-Class` in the `MANIFEST.MF`, nor the `AgentPremain.class` file. Those do exist in `kotlinx-coroutines-core-jvm-1.4.3.jar`.

This is causing failures when debugging unit tests in IntelliJ, which attempts to reference `-javaagent:.../kotlinx-coroutines-core-1.4.3.jar` if you don't include a dependency on `kotlinx-coroutines-core-jvm-1.4.3.jar` (or if `kotlinx-coroutines-core-1.4.3.jar` is before `kotlinx-coroutines-core-jvm` in your effective `pom.xml` for a maven project).

**Comment by qwwdfsad** [comment]
Thanks for the report and investigation in the ticket!

While we are deciding, where exactly this bug belongs, I'll try to workaround it on coroutines side
