### ISSUE TITLE
How should Java provide us with a `Deferred<T>`

### ISSUE THREAD

**Issue by ZakTaccardi** [Kotlin/kotlinx.coroutines#262]
I'm building an SDK in Kotlin, where I want the client to pass in a feature throttle. I'd like this to be a non-blocking future, like `Deffered<T>` or if it were Rx, a `Single<T>`.

```
MySdk.Builder()
  .setFeatureFlag(deferred) // where `deferred` is a `Deferred<Boolean>`
  .build()
```

Internally in the SDK, I wait to asynchronously check if the flag is `true` or `false`

```
launch {
  if(deferred.await()){
    // enable feature
  } else {
    //disable feature
  }
}
```

If the client app, which is injecting an instance of a `Deferred<T>` into the `MySdk.Builder.setFeatureFlag(deferred)` method, is written in Java, how can they best provide an instance of `Deferred<T>`?

If the client app was written in Kotlin, I believe an implementation of `CompletableFuture` would be appropriate (not sure on this).

If this were Rx, I'd expect the client app to inject a `Single.fromCallable { .. }`.

I think it's important for Java consumers to easily construct an instance of `Deferred<T>` (if this is not already possible)

**Comment by jcornaz** [comment]
It is possible to call `async` from java with `DefferedKt.async()`, but this is cumbersome, because the caller would have to give all arguments that are usually optionnal (coroutine context, parent job and start mode)

But it is possible to add create a small and simple helper for that:
```kotlin
// Helper for java written in Kotlin
object DeferredHelper {

  @JvmStatic
  fun <T> create(future: CompletableFuture<T>): Deferred<T> = async { future.get() }

  @JvmStatic
  fun <T> create(supplier: Supplier<T>): Deferred<T> = async { supplier.get() }
}
```

Then one can create a deferred with `DeferredHelper.create(() -> 42)` from Java

**Comment by elizarov** [comment]
In Java you should be able to convert `CompletableFuture` (Java's approach to async) into `Deferred` with something like `FutureKt.asDeferred(future)`, but we don't currently have this in a ready-to-use method.

We need to add extension `fun <T> CompletionStage<T>.asDeferred(): Deferred<T>` into `kotlinx-coroutines-jdk8` module.

**Comment by ZakTaccardi** [comment]
That doesn't work for Android unfortunately, which is stuck on Java 7

**Comment by elizarov** [comment]
Then you can go with `fun <T> create(supplier: Supplier<T>): Deferred<T> = async { supplier.get() }` as suggested above. To incorporate it directly into `kotlinx-coroutines-core` we'll need to figure out an appropriate name for it.

**Comment by JakeWharton** [comment]
It isn't, and hasn't been for years now.

**Comment by ZakTaccardi** [comment]
It looks like Java users could do the following:

```
CompletableDeferred<Boolean> deferred = CompletableDefferedKt.CompletableDeffered<Boolean>(null)

// and when the value is ready, call
deferred.complete(value)
```

Only issue is that it's a bit of an unidiomatic API for Java, but it should do the trick
