### ISSUE TITLE
can we use runblocking  with coroutine for room queries in production?

### ISSUE THREAD

**Issue by bakhtiyar94** [Kotlin/kotlinx.coroutines#2621]
In our product we are using MVP pattern and in Room examples and after long searching I am getting all example with MVVM but now I found this way to run my Room queries using runblocking everything working smoothly I want to know that is this good way to use coroutines, I have heard that runblocking is not recommended for production

```
@Query("""SELECT V.* FROM VISITS AS V LEFT JOIN ORDERS AS O ON O.visitId = V.visitId 
        WHERE V.visitComplete = 1 AND V.visitId = :visitId AND (V.shopClosed = 1 OR O.orderTotal > 0)""")
suspend fun getCompletedVisitByVisitId(visitId: Int): Visits
```

And in my table Helper I am getting result like this

fun getCompletedVisitByVisitId(visitId: Int): Visits? = runBlocking {

  ```
  var data: Visits? = null
    try {
        data = async {
            visitsDao.getCompletedVisitByVisitId(visitId)
        }.await()
    } catch (e: SQLException) {
        CustomMethods.errorLog(e, "getCompletedVisitByVisitId", ErrorLog.TYPE_ERROR, ErrorLog.APPLICATION_ERROR, context)
        e.printStackTrace()
    }
    data
}
```

**Comment by qwwdfsad** [comment]
In your particular example, you are actually trying to block and retrieve the data synchronously, defeating the purpose of coroutines and suspendable Room. It works, but it's easier to do a blocking call in that case.

For further help I'd suggest you asking your question on StackOverflow or in Android-specific communities
