### ISSUE TITLE
Kotlin: No value passed for parameter 'onCancellation'

### ISSUE THREAD

**Issue by Guolianxing** [Kotlin/kotlinx.coroutines#2625]
I tyried to use aio with coroutine like this code [https://github.com/Kotlin/kotlinx.coroutines/blob/87eaba8a287285d4c47f84c91df7671fcb58271f/integration/kotlinx-coroutines-nio/src/Nio.kt](https://github.com/Kotlin/kotlinx.coroutines/blob/87eaba8a287285d4c47f84c91df7671fcb58271f/integration/kotlinx-coroutines-nio/src/Nio.kt)
But the compiler reported an error `Kotlin: No value passed for parameter 'onCancellation'` .
![image](https://user-images.githubusercontent.com/30403429/113538850-de680680-960e-11eb-8a18-7b79ad93d4a2.png)

The version of compiler is `kotlinc-jvm 1.4.32`.
It seems that the compiler can't find the extension function `resume` in `Continuation.kt`, the parent interface of `CancellableContinuation`.
But it works in `kotlinc-jvm 1.3.61`.
Is it a bug of the new version compiler?

**Comment by qwwdfsad** [comment]
It is expected behaviour. The compiler tries to resolve  experimental `resume(value: T, onCancellation: ((cause: Throwable) -> Unit)?)` function and is looking for second parameter.

Otherwise, either `resume` extension function from `kotlin.coroutines` package should be imported or `resumeWith` should be used instead

**Comment by fvasco** [comment]
@Guolianxing,
I made a tiny tool for NIO integration, you can take a look here: https://gitlab.com/asynk/nio

**Comment by Guolianxing** [comment]
> It is expected behaviour. The compiler tries to resolve experimental `resume(value: T, onCancellation: ((cause: Throwable) -> Unit)?)` function and is looking for second parameter.
> 
> Otherwise, either `resume` extension function from `kotlin.coroutines` package should be imported or `resumeWith` should be used instead

Thanks, I confused kotlin with kotlinx. And the code hints can import the package in lower version of idea, but in higher version, it only suggests you create the extension function:  [https://youtrack.jetbrains.com/issue/KT-39990](https://youtrack.jetbrains.com/issue/KT-39990).

This issue can be closed.

**Comment by Guolianxing** [comment]
> @Guolianxing,
> I made a tiny tool for NIO integration, you can take a look here: https://gitlab.com/asynk/nio

Thanks.
