### ISSUE TITLE
FlatMapMerge not cancels on top level collect

### ISSUE THREAD

**Issue by rcaceiro** [Kotlin/kotlinx.coroutines#2639]
Hello, everyone

I have a doubt / question about cancelation on `Flow<T> .flatMapMerge`, the following code shows that I depend on the top level flow to build the new1SecFlow and every time that new1SecFlow is called it creates a new flow but the previous is never cancelled.

I don't know if I am doing wrong but the new1SecFlow can be a call to a Room database or a network call or a external lib and I cannot do implementation trickery to cancel the flow created by new1SecFlow.

```
class MainActivity : AppCompatActivity() {

    override fun onCreate(savedInstanceState: Bundle?) {
        super.onCreate(savedInstanceState)

        flow {
            var i = 0
            while (true) {
                i++
                this.emit(i)
                delay(30000)
            }
        }
            .flatMapMerge { this.new1SecFlow(it) }
            .onEach { Log.d("OnTRACK", it) }
            .flowOn(Dispatchers.Default)
            .launchIn(this.lifecycleScope)
    }

    private fun new1SecFlow(i: Int) = flow {
        var double = i
        while (true) {
            double *= 2
            this.emit("input=$i double = $double")
            delay(1000)
        }
    }
}
```

**Comment by qwwdfsad** [comment]
Yeah, this is the desired behaviour, the `flatMapMerge` is supposed to merge all the produced flows into one.

But it seems like what you are looking for is `flatMapLatest` that cancels the produced flow as soon as the new element arrives

**Comment by rcaceiro** [comment]
@qwwdfsad yes!
thank you so much for the help!
