### ISSUE TITLE
Flow collection isn't triggered when one of the conditional branches contains an empty flow / throws 

### ISSUE THREAD

**Issue by Thomas-Boutin** [Kotlin/kotlinx.coroutines#2651]
# (BugReport)

Hi, during my devs, I've discovered an unexpected behavior : 
A conditional if / else branching followed by a flow collection like so works perfectly : 

```kotlin
val number = 1

if (number == 1) {
    flowOf(1)
} else {
    flowOf(2)
}.collect {
    println(it)
}
```

However, if one of the branches throws an exception like so : 

```kotlin
val number = 1

if (number == 1) {
    flowOf(1)
} else if (number > 1) {
    flowOf(2)
} else {
   throw IllegalArgumentException()
}.collect {
    println(it)
}
```

or returns an empty flow :  

```kotlin
val number = 1

if (number == 1) {
    flowOf(1)
} else if (number > 1) {
    flowOf(2)
} else {
   emptyFlow()
}.collect {
    println(it)
}
```

Then the collection is never triggered. 
The expected behavior would require a collection in every case.
I've created a [playground](https://play.kotlinlang.org/#eyJ2ZXJzaW9uIjoiMS40LjMwIiwicGxhdGZvcm0iOiJqYXZhIiwiYXJncyI6IiIsImpzQ29kZSI6IiIsIm5vbmVNYXJrZXJzIjp0cnVlLCJ0aGVtZSI6ImlkZWEiLCJjb2RlIjoiaW1wb3J0IGtvdGxpbnguY29yb3V0aW5lcy4qXG5pbXBvcnQga290bGlueC5jb3JvdXRpbmVzLmZsb3cuKlxuXG5mdW4gbWFpbigpID0gcnVuQmxvY2tpbmcge1xuICAgbG9hZERhdGEoKVxuICAgbG9hZERhdGFCdWcoKVxufVxuXG5zdXNwZW5kIGZ1biBsb2FkRGF0YSgpIHtcbiAgICB2YWwgbnVtYmVyID0gMlxuICAgIFxuICAgIGlmIChudW1iZXIgPT0gMSkge1xuICAgICAgICBmbG93T2YoMSlcbiAgICB9IGVsc2Uge1xuICAgICAgICBmbG93T2YoMilcbiAgICB9LmNvbGxlY3Qge1xuICAgICAgICBwcmludGxuKGl0KVxuICAgIH1cbn1cblxuc3VzcGVuZCBmdW4gbG9hZERhdGFCdWcoKSB7XG4gICAgdmFsIG51bWJlciA9IDFcbiAgICBcbiAgICBpZiAobnVtYmVyID09IDEpIHtcbiAgICAgICAgZmxvd09mKDEpXG4gICAgfSBlbHNlIGlmIChudW1iZXIgPiAxKSB7XG4gICAgICAgIGZsb3dPZigyKVxuICAgIH0gZWxzZSB7XG4gICAgICAgdGhyb3cgSWxsZWdhbEFyZ3VtZW50RXhjZXB0aW9uKClcbiAgICB9LmNvbGxlY3Qge1xuICAgICAgICBwcmludGxuKGl0KVxuICAgIH1cbn1cblxuc3VzcGVuZCBmdW4gbG9hZERhdGFCdWcyKCkge1xuICAgIHZhbCBudW1iZXIgPSAxXG4gICAgXG4gICAgaWYgKG51bWJlciA9PSAxKSB7XG4gICAgICAgIGZsb3dPZigxKVxuICAgIH0gZWxzZSBpZiAobnVtYmVyID4gMSkge1xuICAgICAgICBmbG93T2YoMilcbiAgICB9IGVsc2Uge1xuICAgICAgIGVtcHR5RmxvdygpXG4gICAgfS5jb2xsZWN0IHtcbiAgICAgICAgcHJpbnRsbihpdClcbiAgICB9XG59In0=) for this issue.

Have a good day :-)

**Comment by fvasco** [comment]
Same for lists, it isn't related to `Flow`.
It looks as a compiler bug, it affects 1.5.0-RC, also.

https://pl.kotl.in/4mo-DMvX1

**Comment by elizarov** [comment]
It's not a bug. It how the precedence of operators works in Kotlin. In Kotlin `if` is an expression itself, essentially having the lowest precedence, and when you write `if (number == 1) {   ... }  else SOMETHING_ELSE`, then the whole `SOMETHING_ELSE` gets parsed together as another expression. In your case the whole `if ... .collect()` is a part of an `else` for the first `if`. 

Does it help?

**Comment by Thomas-Boutin** [comment]
Yes, this helps a lot! 
I thought this syntax could help factorize code but it seems instead to be more error-prone than a higher-order function.
Thanks for your time and explanation, I'm closing the issue :-)

**Comment by qwwdfsad** [comment]
https://youtrack.jetbrains.com/issue/KT-16275 also here is the umbrella issue

**Comment by elizarov** [comment]
@Thomas-Boutin 

> Yes, this helps a lot!
> I thought this syntax could help factorize code but it seems instead to be more error-prone than a function.
> Thanks for your time and explanation, I'm closing the issue :-)
 
 The general advice here is to avoid `if else if else` chains and use `when` instead. It does not have those error-proneness problems and works in a straightforward way.

**Comment by Thomas-Boutin** [comment]
Thanks to both of you!
