### ISSUE TITLE
How to download jar file and run code demo in Command line? 

### ISSUE THREAD

**Issue by qixuxiang** [Kotlin/kotlinx.coroutines#266]
Thanks for your awesome code share.I want to add jar files and run the demo code in Command line, because i have no GUI in my work PC.here is my code:

```
//demo.kt
import kotlinx.coroutines.experimental.*

fun main(args: Array<String>) {
    launch { // launch new coroutine in background and continue
        delay(1000L) // non-blocking delay for 1 second (default time unit is ms)
        println("World!") // print after delay
    }
    println("Hello,") // main thread continues while coroutine is delayed
    Thread.sleep(2000L) // block main thread for 2 seconds to keep JVM alive
}
```

i compile it by ```kotlinc -Xcoroutines=enable demo.kt -include-runtime -d demo.jar```

here is error:

![tim 20180303094425](https://user-images.githubusercontent.com/16591716/36929103-86cf125e-1ec7-11e8-8f5e-9229a97260f7.png)

how to solve this problem, looking forward to your reply!

**Comment by marekdef** [comment]
launch and delay are from kotlinx-coroutines-core-0.22 library.
You need to add them to the classpath when compiling 
kotlinc -classpath kotlinx-coroutines-core-0.22.jar
