### ISSUE TITLE
Please add aReadline fucntion

### ISSUE THREAD

**Issue by Sherlock-Holo** [Kotlin/kotlinx.coroutines#267]
When I write http service, I need to use `aRead` and a `byteBuffer` which use `limit` to ensure just read 1 byte so that  I can confirm the byte is `\r`, `\n` or other.

If I have `aReadline`, I can write http service quickly.

I hope you can add this function, please

**Comment by elizarov** [comment]
`kotlinx-coroutines-nio` module provides a set of wrapper functions for _existing_ methods in NIO channels. Since there is not `readLine`, there is no `aReadLine`.

**Comment by elizarov** [comment]
I would not recommend using `AsynchronousSocketChannel` for your own needs. It provides neither convenience of API, nor performance. That is one of the reasons we are not planning to add any feature to `kotlinx-coroutines-nio`. We are working on a better API for async IO (you can take a look at `kotlinx-coroutines-io` and `ktor-http-cio`), but it is still quite experimental work-in-progress.

**Comment by Sherlock-Holo** [comment]
well I will go to see it, thanks

Roman Elizarov <notifications@github.com> 于 2018年3月4日周日 00:07写道：

**Comment by Sherlock-Holo** [comment]
Are there any examples about  `kotlinx-coroutines-io` ? I want to read to learn how to use `kotlinx-coroutines-io`
