### ISSUE TITLE
Flow flatMap* and emptyFlow()

### ISSUE THREAD

**Issue by Zeliret** [Kotlin/kotlinx.coroutines#2685]
Hi, 

Thank you for your library and efforts!

I have a question. With RxJava I could switch some hot observable source to an empty observable. As a result I could get a switchIfEmpty or onComplete callback invocation. 

If I do it like this:
```kotlin
val hotFlowFromRoom: Flow<List<Item>> = db.someQuery()
val newFlow = hotFlowFromRoom.flatMapLatest{ list ->
  list.firstOrNull()?.let{ flowOf(it) ) ?: emptyFlow()
}
// ... 
// And somewhere else
newFlow.onEmpty { /* not called in case of emptyFlow() */ }
newFlow.onCompletion { /* not called in case of emptyFlow() */ }
```

So how can I complete a hot flow or switch it to some cold flow (empty flow, for example)?

**Comment by consp1racy** [comment]
Hi, could you post equivalent code in RxJava?

**Comment by Zeliret** [comment]
Well, I just tried to create a piece of code with RxJava and failed. Maybe I remember it wrong. 
Is there some way to achieve my goal? 

I have a hot flow from Android Room and Room does not complete it if there is no elements. What I need is to complete the flow if no element found (for example if Room returns empty list), and do not complete if element is found and can be changed in any minute later. 
I was able to emulate it like this: 
```kotlin
            .map { list ->
                list.firstOrNull() ?: throw NoSuchElementException()
            }
// later on
                .catch {
                    if (it is NoSuchElementException) {
                        // Some action here
                    } else {
                        throw it
                    }
                }
```
But I dont feel that it is a right way to do it. ;(

**Comment by consp1racy** [comment]
Did you mean something like this?

```kt
val hotFlowFromRoom: Flow<List<Item>> = TODO()
val newFlow = hotFlowFromRoom
    .takeWhile { it.isNotEmpty() }
    .map { it.first() }
```

Assuming the query returns a list of 0 or 1 items by ID,
* if the item is not in DB, the flow terminates immediately,
* if the item is in DB, you get a flow of the item as it changes,
* if the item is removed from DB, the flow terminates.

**Comment by Zeliret** [comment]
@consp1racy That is exactly what I needed. Thank you! I haven't looked at that method at all, omg.

**Comment by dkhalanskyjb** [comment]
Thanks, @consp1racy! @Zeliret, it looks like your issue was resolved, so I'm closing this, but feel free to reopen it if you have some follow-ups.
