### ISSUE TITLE
Version 1.5-RC01: Job not cancelled when parent Scope is cancelled (if TestCoroutineDispatcher previously paused).

### ISSUE THREAD

**Issue by steve-the-edwards** [Kotlin/kotlinx.coroutines#2698]
Tests to reproduce [EDITED after @Oliver02 pointed out below that the original repro had mistakes]:

```
  @Test
  fun `test cancel scope cancels job deferred`() {
    val testDispatcher = TestCoroutineDispatcher()
    testDispatcher.pauseDispatcher()
    val coroutineScope = CoroutineScope(testDispatcher)
    val deferredJob = coroutineScope.async {
      delay(500)
      42
    }
    testDispatcher.resumeDispatcher()

    coroutineScope.cancel("Oh noes!")

    testDispatcher.advanceUntilIdle()

    assertTrue(deferredJob.isCancelled) // Value is false.
  }

  @Test
  fun `test cancel scope cancels job`() {
    val testDispatcher = TestCoroutineDispatcher()
    testDispatcher.pauseDispatcher()
    val coroutineScope = CoroutineScope(testDispatcher)
    val myJob = coroutineScope.launch {
      delay(500)
    }
    testDispatcher.resumeDispatcher()

    coroutineScope.cancel("Oh noes!")

    testDispatcher.advanceUntilIdle()

    assertTrue(myJob.isCancelled) // Value is false.
  }
```

This was working with version 1.4.2 but is failing in version 1.5-rc01.

In debugging through the `coroutineScope` has two children the ProducerCoroutine and the DeferredCoroutine. After cancelling the producer, the state of the DeferredJob is null - so `.isActive` correctly returns false but `.isCancelled` does not as state is null in `JobSupport`.

This *does* work without pausing before the launch and resuming after. Is that expected behaviour?

**Comment by OliverO2** [comment]
How did you make that compile? `scope` is undefined. If I rename `coroutineScope` to `scope` and wrap it all into a test class, the tests succeed with `kotlinx-coroutines` version `1.5.0-RC`.

**Comment by steve-the-edwards** [comment]
> How did you make that compile? `scope` is undefined. If I rename `coroutineScope` to `scope` and wrap it all into a test class, the tests succeed with `kotlinx-coroutines` version `1.5.0-RC`.

Thanks @OliverO2 this was my mistake when I tried to setup the smaller reproducible code within another test file that already had a `scope` property! You are right, that works correctly so I had to do a bit more digging to see why our case wasn't working correctly.  It is slightly modified to the following:

```
@Test
  fun `test cancel scope cancels job deferred`() {
    val testDispatcher = TestCoroutineDispatcher()
    testDispatcher.pauseDispatcher()
    val coroutineScope = CoroutineScope(testDispatcher)
    val deferredJob = coroutineScope.async {
      delay(500)
      42
    }
    testDispatcher.resumeDispatcher()

    coroutineScope.cancel("Oh noes!")

    testDispatcher.advanceUntilIdle()

    assertTrue(deferredJob.isCancelled) // Value is false.
  }

  @Test
  fun `test cancel scope cancels job`() {
    val testDispatcher = TestCoroutineDispatcher()
    testDispatcher.pauseDispatcher()
    val coroutineScope = CoroutineScope(testDispatcher)
    val myJob = coroutineScope.launch {
      delay(500)
    }
    testDispatcher.resumeDispatcher()

    coroutineScope.cancel("Oh noes!")

    testDispatcher.advanceUntilIdle()

    assertTrue(myJob.isCancelled) // Value is false.
  }
```

**Comment by OliverO2** [comment]
@steve-the-edwards Way better! :smiley: Reproduces here now, too.

The cause seems to be the behavoir of `testDispatcher.resumeDispatcher()`. When setting the property `dispatchImmediately`, this is what happens:

https://github.com/Kotlin/kotlinx.coroutines/blob/0fcd1d8b2c683b9851650f89ab22cc5552579ae0/kotlinx-coroutines-test/src/TestCoroutineDispatcher.kt#L29-L36

So resuming your dispatcher advances time, making your coroutines complete before `cancel` has a chance. Afterwards, `testDispatcher.advanceUntilIdle()` has no effect and an `assertTrue(myJob.isCompleted)` would be appropriate.

**Comment by steve-the-edwards** [comment]
Thanks @OliverO2 yup that explanation makes sense. Also re-tested this small case on 1.4.2 and it works the same. The plot thickens! Will close this issue as
