### ISSUE TITLE
SharingStarted as <no name provided> in Kotlin Flow docs

### ISSUE THREAD

**Issue by jeziellago** [Kotlin/kotlinx.coroutines#2714]
# Description
In [Kotlin Flow Docs](https://kotlin.github.io/kotlinx.coroutines/kotlinx-coroutines-core/kotlinx.coroutines.flow/index.html), the section `Functions` has the fun interface `SharingStarted` showed as [`<no name provided>`](https://kotlin.github.io/kotlinx.coroutines/kotlinx-coroutines-core/kotlinx.coroutines.flow/-no%20name%20provided-.html).

![Screen Shot 2021-05-17 at 12 09 02](https://user-images.githubusercontent.com/8452419/118511844-ad4c1d00-b708-11eb-80b2-ee50af4dbc12.png)

This is a dokka bug opened in https://github.com/Kotlin/dokka/issues/971, and fixed in [Dokka 0.11](https://github.com/Kotlin/dokka/pull/981)

**Comment by qwwdfsad** [comment]
Fixed by updating to new Dokka
