### ISSUE TITLE
Lost connection to device.(Error while loading PDF) Flutter

### ISSUE THREAD

**Issue by aresrana** [Kotlin/kotlinx.coroutines#2735]
E/AndroidRuntime(10232): FATAL EXCEPTION: main
E/AndroidRuntime(10232): Process: com.jiwdopani.jiwdopani, PID: 10232
E/AndroidRuntime(10232): java.lang.NoSuchMethodError: No virtual method nightMode(Z)Lc/c/a/a/e$b; in class Lc/c/a/a/e$b; or its super classes (declaration of 'c.c.a.a.e$b' appears in /data/app/~~NnCdcMIP9p7iXgq1sysAzA==/com.jiwdopani.jiwdopani-TroItXSG_nY2pgCq0oXzQQ==/base.apk)
E/AndroidRuntime(10232): 	at e.a.a.a.a.<init>(:56)
E/AndroidRuntime(10232): 	at e.a.a.a.c.create(:22)
E/AndroidRuntime(10232): 	at io.flutter.plugin.platform.SingleViewPresentation.onCreate(:186)
E/AndroidRuntime(10232): 	at android.app.Dialog.dispatchOnCreate(Dialog.java:419)
E/AndroidRuntime(10232): 	at android.app.Dialog.show(Dialog.java:313)
E/AndroidRuntime(10232): 	at android.app.Presentation.show(Presentation.java:257)
E/AndroidRuntime(10232): 	at io.flutter.plugin.platform.VirtualDisplayController.<init>(:95)
E/AndroidRuntime(10232): 	at io.flutter.plugin.platform.VirtualDisplayController.create(:48)
E/AndroidRuntime(10232): 	at io.flutter.plugin.platform.PlatformViewsController$1.createVirtualDisplayForPlatformView(:207)
E/AndroidRuntime(10232): 	at io.flutter.embedding.engine.systemchannels.PlatformViewsChannel$1.create(:104)
E/AndroidRuntime(10232): 	at io.flutter.embedding.engine.systemchannels.PlatformViewsChannel$1.onMethodCall(:59)
E/AndroidRuntime(10232): 	at io.flutter.plugin.common.MethodChannel$IncomingMethodCallHandler.onMessage(:233)
E/AndroidRuntime(10232): 	at io.flutter.embedding.engine.dart.DartMessenger.handleMessageFromDart(:85)
E/AndroidRuntime(10232): 	at io.flutter.embedding.engine.FlutterJNI.handlePlatformMessage(:819)
E/AndroidRuntime(10232): 	at android.os.MessageQueue.nativePollOnce(Native Method)
E/AndroidRuntime(10232): 	at android.os.MessageQueue.next(MessageQueue.java:335)
E/AndroidRuntime(10232): 	at android.os.Looper.loop(Looper.java:183)
E/AndroidRuntime(10232): 	at android.app.ActivityThread.main(ActivityThread.java:7656)
E/AndroidRuntime(10232): 	at java.lang.reflect.Method.invoke(Native Method)
E/AndroidRuntime(10232): 	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:592)
E/AndroidRuntime(10232): 	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:947)
I/Process (10232): Sending signal. PID: 10232 SIG: 9
Lost connection to device.

**Comment by dkhalanskyjb** [comment]
Please clarify why you think that this failure is related to kotlinx.coroutines.
