### ISSUE TITLE
Old reactive-streams version in kotlinx-coroutines-reactive

### ISSUE THREAD

**Issue by varche** [Kotlin/kotlinx.coroutines#2740]
I am not able to use Publisher.asFlow() in my project because I have 1.0.3 version while kotlinx-coroutines-reactive has 1.0.2

**Comment by qwwdfsad** [comment]
This is expected, but not yet enforced (#2494) behaviour. 
Please ensure that all the supplementary modules have the same version as `kotlinx-coroutines-core`, meanwhile we'll try to provide a better documentation regarding this behaviour

**Comment by varche** [comment]
Looks like I don't have problem with modules versions, my issue is that kotlinx-coroutines-reactive uses reactive_streams_version=1.0.2 (see https://github.com/Kotlin/kotlinx.coroutines/blob/master/gradle.properties) but I use newer version (1.0.3)
