### ISSUE TITLE
why not Concurrent

### ISSUE THREAD

**Issue by yiyinying** [Kotlin/kotlinx.coroutines#275]
fun main(args: Array<String>) = runBlocking {
    val client = OkHttpClient()

    val time = measureTimeMillis {
        val list = List(30) {
            async(CommonPool) {
                print(client.fetch("http://www.hao123.com"))
            }
        }

        list.forEach { it.await() }
    }

    print(time)

}

fun OkHttpClient.fetch(url: String): String? {
    return newCall(Request.Builder()
            .url(url)
            .get()
            .build())
            .execute()
            .body()
            ?.string()
}

**Comment by fvasco** [comment]
CommonPool is very limited, do not block the thread and use an async version.

https://github.com/Kotlin/kotlin-coroutines/blob/master/kotlin-coroutines-informal.md#wrapping-callbacks
