### ISSUE TITLE
`TestCoroutineDispatcher`'s threading policy is undocumented behavior

### ISSUE THREAD

**Issue by kevincianfarini** [Kotlin/kotlinx.coroutines#2756]
Recently I was bitten by the threading policy of `TestCoroutineDispatcher`. In our work application, we were testing that a certain action always gets invoked on the main thread. When testing this using `TestCoroutineDispatcher`, we were getting failing tests. Omitting `TestCoroutineDispatcher` in favor of regular `runBlocking` fixed the tests. 

We ventured to figure out why and ultimately isolated a test case that fails. 

```kotlin
@Test fun isolate() = runBlocking(TestCoroutineDispatcher()) {
  val job = launch {
    val inner = withContext(newSingleThreadContext("test")) {
      Thread.currentThread()
    }
    val outer = Thread.currentThread()
    assertThat(outer).isNotEqualTo(inner)
  }
  job.join()
}
```
When running this test, we received the following error. 

```
expected not to be: Thread[test @coroutine#2,5,main]
```

After several hours of debugging and reading through documentation, it was brought to our attention that it's possible `TestCoroutineDispatcher`'s threading policy might be similar to `Dispatchers.Unconfined`. If this is true, it is undocumented behavior. 

If the team would like, I can update the documentation to reflect this functionality.

**Comment by dkhalanskyjb** [comment]
Hi! We thoroughly reworked the test module in https://github.com/Kotlin/kotlinx.coroutines/commit/2e25baeb29274853a1926f6bf7c3be761f306d72. Now, we provide a dispatcher called `StandardTestDispatcher`, whose threading policy is fairly obvious, as well as a dispatcher called `UnconfinedTestDispatcher`, which is documented.
