### ISSUE TITLE
Bridge method for non-existent "invokeSuspend$accept" is generated

### ISSUE THREAD

**Issue by svasilinets** [Kotlin/kotlinx.coroutines#2769]
Steps to reproduce:

1. Create Foo.kt (add imports)
```kotlin 
package test
class Foo() {
    fun bar() {
        val flow: Flow<String> = flowOf()
        val consumer = Consumer<String> {  }
        runBlocking { flow.collect(consumer::accept) }
    }
}
```
2. `kotlinc -cp  kotlinx-coroutines-core-jvm-1.5.0.jar Foo.kt`
3.  `javap -c 'test/Foo$bar$1.class'`

Last generated method there is: 
```
public static final java.lang.Object access$invokeSuspend$accept(java.util.function.Consumer, java.lang.String, kotlin.coroutines.Continuation);
    Code:
       0: aload_0
       1: aload_1
       2: aload_2
       3: invokestatic  #116                // Method invokeSuspend$accept:(Ljava/util/function/Consumer;Ljava/lang/String;Lkotlin/coroutines/Continuation;)Ljava/lang/Object;
       6: areturn
```       
But `invokeSuspend$accept` method doesn't exist. This bridge isn't called in runtime, so it doesn't result in crash. However, tools that verify bytecode consistency fail on this bytecode. 

version used:
```
> kotlinc -version
info: kotlinc-jvm 1.5.0 (JRE 11.0.10+0-b96-7281165)
```

**Comment by qwwdfsad** [comment]
Thanks for the report! 
This is a compiler bug that will be fixed in the upcoming Kotlin 1.5.30 release.
