### ISSUE TITLE
MutableStateFlow fails to emit on quick emit

### ISSUE THREAD

**Issue by ouattararomuald** [Kotlin/kotlinx.coroutines#2787]
I'm trying to collect events from `flow`.

**ViewModel**
```kotlin
val events = MutableStateFlow<HomeEvent>(HomeEvent.Empty)
val uiEvents: StateFlow<HomeEvent> = events

private suspend fun emitEvent(homeEvent: HomeEvent) {
    events.emit(homeEvent)
}

private fun downloadHomeData() {
    viewModelScope.launch(dispatchers.io + exceptionHandler) {
      longRunningTaskSync()
      emitEvent(HomeEvent.DisplayHomeAnimation())

      longRunningTaskSync2()
      emitEvent(HomeEvent.DisplayProgressiveLoadingImages())

      longRunningTaskSync3()
      emitEvent(HomeEvent.DisplayTitles())

      emitEvent(HomeEvent.DisplayProgressiveLoadingPosts())
      emitEvent(HomeEvent.DisplayProgressiveLoadingComments())
      emitEvent(HomeEvent.DisplayKpi())
    }
  }
```

**HomeFragment**
```kotlin
override fun onCreate(savedInstanceState: Bundle?) {
    super.onCreate(savedInstanceState)
    lifecycleScope.launch {
      repeatOnLifecycle(Lifecycle.State.STARTED) {
        try {
          viewModel.uiEvents.collect { event ->
            when (event) {
              is HomeEvent.DisplayHomeAnimation -> { }
              is HomeEvent.DisplayProgressiveLoadingImages -> { }
              is HomeEvent.DisplayKpi -> { }
              is HomeEvent.DisplayTitles -> { }
              is HomeEvent.DisplayProgressiveLoadingPosts -> { }
              is HomeEvent.DisplayProgressiveLoadingComments -> { }
              is HomeEvent.Empty -> { }
            }
          }
        } catch (t: Throwable) {
        }
      }
    }
}
```

In the example above `MutableStateFlow` fails to emit some events.
But every time I put a `delay(200)` between successive emissions everything works correctly. 

Unless I'm wrong I thing it should emit all events in the order of emission. Is that the expected behavior ? Did I miss something in the documentation ? or I'm doing something wrong ?

**Comment by dkhalanskyjb** [comment]
Hi! This behavior is expected and documented. From https://kotlin.github.io/kotlinx.coroutines/kotlinx-coroutines-core/kotlinx.coroutines.flow/-state-flow/index.html:
> Updates to the value are always conflated. So a slow collector skips fast updates, but always collects the most recently emitted value.

This means that `StateFlow` will not wait for `collect` and may drop values. This is due to the fact that `StateFlow` is supposed to be used when the latest *state* is what matters, not the sequence of events.

You can easily fix your program by replacing the `StateFlow` with a `SharedFlow`.

**Comment by ouattararomuald** [comment]
Hi @dkhalanskyjb thanks a lot for your response. I missed that. I'll try with `SharedFlow`.
