### ISSUE TITLE
'org.jetbrains.kotlinx:kotlinx-coroutines-core:1.5.20-native-mt' can not be upgrade 

### ISSUE THREAD

**Issue by YugeCse** [Kotlin/kotlinx.coroutines#2798]
Hi, friends! I Got a problem. 
There is a alert that is "let the library kotlinx.coroutines upgrade to 1.5.20-native-mt", but after I execute the upgrade process. Many minutes later, none is completed.
"org.jetbrains.kotlinx:kotlinx-coroutines-core:1.5.20-native-mt" is be released ? !

**Comment by qwwdfsad** [comment]
Hi, please stick with `1.5.0-native-mt`.
The current Kotlin version (1.5.20) has nothing to do with `native-mt` version and `1.5.0-native-mt` can be safely used with Kotlin `1.5.20`
