### ISSUE TITLE
java.lang.NoClassDefFoundError: Failed resolution of: Lkotlinx/coroutines/Dispatchers;

### ISSUE THREAD

**Issue by ChawLoo** [Kotlin/kotlinx.coroutines#2800]
引入了1.5.0版本的
    api("org.jetbrains.kotlinx:kotlinx-coroutines-core:1.5.0")
    api("org.jetbrains.kotlinx:kotlinx-coroutines-android:1.5.0")
报错：
java.lang.NoClassDefFoundError: Failed resolution of: Lkotlinx/coroutines/Dispatchers;

**Comment by dkhalanskyjb** [comment]
Which version of the Kotlin compiler do you use?

**Comment by AlanChienYL** [comment]
@ChawLoo Have you use `aspectj` in your project?

**Comment by ChawLoo** [comment]
> @ChawLoo Have you use `aspectj` in your project?

yeah

**Comment by AlanChienYL** [comment]
then you can exclude the coroutine package. everything will work as well

**Comment by ChawLoo** [comment]
> then you can exclude the coroutine package. everything will work as well

Yes, I did that too, it has been resolved, thanks
