### ISSUE TITLE
ReceiveChannel.receiveCatching in common-code has inconsistent behaviour on different platforms

### ISSUE THREAD

**Issue by FelixEngl** [Kotlin/kotlinx.coroutines#2802]
Hello everyone,

I found a bug of `ReceiveChannel.receiveCatching` in version 1.5.0 of `kotlinx.coroutines`.
Basically using `ReceiveChannel.receiveCatching` in a MPP results in inconsistent behaviour of the code when compiled to different platforms. I created a minimal example (link below text), it shows what happens when the common code is compiled to JS and JVM.       
With JS the code behaves like expected, but when I compile the same code to a JVM-target, the function returns a 
 `ChannelResult<ChannelResult<T>>` not a `ChannelResult<T>`. Which contradicts the return type of the function `ReceiveChannel.receiveCatching`.

Here is a minimum example for that behaviour:
https://github.com/FelixEngl/ReceiveChannelStangeBehaviourME/tree/main

**Comment by qwwdfsad** [comment]
Thanks for the reproducer!

This is a new compiler bug, so it can be fixed only around Kotlin 1.6.0.
While I still bisecting it, as a workaround it is possible to remove `inline` modifier from `consumeReceiveCatching`

**Comment by qwwdfsad** [comment]
Thanks, filed https://youtrack.jetbrains.com/issue/KT-47571

Please keep track of the issue there
