### ISSUE TITLE
ambiguous "-mt"  

### ISSUE THREAD

**Issue by jnorthrup** [Kotlin/kotlinx.coroutines#2813]
what is version 1.5.0-mt  ?

the parallelization features of the different dispatchers, launch{}, flows  and the recent eyeball performance measurement seems to imply kotlin-coroutines multicore execution is a wee bit more deliberate, less default, and relatively undefined and in flux right now compared to say the java streams equivalents.  i recently tried to track down parallel map-reduce strategy  in another issue and in relative terms the github status was a museum peice.

for jvm backend code does 1.5.0-mt change any defaults or configured parameters?  it seems to compile the same

**Comment by hfhbd** [comment]
See the pinned issue https://github.com/Kotlin/kotlinx.coroutines/issues/462
The `mt` version affects Kotlin/Native only.
