### ISSUE TITLE
Channels need ability to specify "disposing" policy for their elements

### ISSUE THREAD

**Issue by elizarov** [Kotlin/kotlinx.coroutines#282]
Consider a case where you use a `Channel` to send some resources that need to be disposed (consumed/closed) after use. For example, you are sending network connections, open files, other channels, handles to native memory, etc. See `ReceiveChannel.flatMap`, for example, that specifically works on channel of channels. It all works fine as long as the consumer receives and process all the sent elements. However, if the consumer is cancelled, then it typically cancels the channel it is receiving from and this leaves us in a state where channel's buffer can have some items that were not received yet. Currently all those items are simply dropped. This affects even `RendezvousChannel` as the producer might have already invoked `send(element)` and when consumer cancels the channel this `element` is just dropped. 

Currently now there is no way to specify how those dropped items shall be be closed/disposed.

**Comment by qwwdfsad** [comment]
Implementation note: it can piggyback on #341 storage

**Comment by qwwdfsad** [comment]
Fixed with `onUndeliveredElement` since 1.5.0
