### ISSUE TITLE
Flow not received when flow on IO dispatcher and R8 is enabled in Android

### ISSUE THREAD

**Issue by OHoussein** [Kotlin/kotlinx.coroutines#2835]
Flow is never received when I added flow on IO dispatcher and `minifyEnabled true`, for example, I added the following simple flow and it never received (without any error)
```
flowOf("Hey")
    .flowOn(Dispatchers.IO)
    .collect {
         println("Collect is called $it")
    }
```

But When I disable the `minifyEnabled`, It works perfectly

coroutine version: 1.5.1
Android gradle plugin: 7.1.0-alpha03
Kotlin version: 1.5.10

**Comment by qwwdfsad** [comment]
I cannot reproduce this issue, so it may be related to your setup.

If you're still encountering it, please consider reporting it to google issue tracker as it cleary is related to Android toolchain
