### ISSUE TITLE
class kotlin.Unit cannot be cast to class CustomObject

### ISSUE THREAD

**Issue by KostyaLyapochkin** [Kotlin/kotlinx.coroutines#2838]
Hi. I have found out an interesting compilation bug when I am using Kotlin coroutines without explicit indication returned type. For instance, I have this snippet of code:

```
suspend fun executeSomething(): CustomObject? {
    val s: String? = ""
    val o: Object? = null

    val deferred = GlobalScope.async(Dispatchers.IO) {
        if (s == null) return@async null

        o?.let {
            return@async CustomObject()
        }
    }

    return deferred.await()
}
```

If I don't return a value from async the function will try to return Kotlin.Unit, so I catch java.lang.ClassCastException (class kotlin.Unit cannot be cast to class CustomObject). In another case, if I use the same approach without coroutines like:

```
fun executeSomething(): CustomObject? {
    val s: String? = ""
    val o: Object? = null

    val callback: () -> CustomObject? = callback@ {
        if (s == null) return@callback null

        o?.let {
            return@callback CustomObject()
        }
    }

    return callback.invoke()
}
```

Kotlin compiler understands that It should input automatically null value and it works properly. Please, take a look.

**Comment by pyos** [comment]
Looks like https://youtrack.jetbrains.com/issue/KT-47527

**Comment by qwwdfsad** [comment]
Right, this is the compiler bug, please keep track of it there
