### ISSUE TITLE
Default JS Dispatcher for React Native is wrong

### ISSUE THREAD

**Issue by Legion2** [Kotlin/kotlinx.coroutines#2843]
As part of ecc68f13141d1353aa2bb1d027a077e0fd7be4fb the Default dispatcher for React Native was set to `NodeDispatcher`. However, there is no `process.nextTick` in React Native environments. There is only a fake `process.env` object but nothing else. As a result the Default dispatcher does not work in React Native.

So I tested the other dispatchers. In React Native environments the `SetTimeoutDispatcher` works well. If React Native is executed with a Debugger (Chrome) the JS code is executed in a Chrome worker. In this mode `SetTimeoutDispatcher` and `window.asCoroutineDispatcher()` can be used as dispatchers, `NodeDispatcher` does not work.

To resolve this issue, `createDefaultDispatcher` must be adapted, so it properly detects the fake `process` object without the `nextTick` function.

If needed I can provide a PR and test changes.

**Comment by qwwdfsad** [comment]
Thanks for the detailed explanation! The PR is very welcome
