### ISSUE TITLE
Kotlin/Native Multiplatform library usage from C++

### ISSUE THREAD

**Issue by paumove** [Kotlin/kotlinx.coroutines#2844]
I have a Kotlin Multiplatform project that uses the coroutine library. One of the goals is to compile a shared library for linux and windows. This library (.so / .dll) will be used from other languages such as C, C++, Go, etc.

Currently, I am testing on Windows and C++. When my library reaches a point where it makes use of the `launch {}` function then I get an error `kotlin.IllegalStateException: There is no event loop. Use runBlocking { ... } to start one.`

How can I make use of the coroutine library from languages other than Kotlin?

For example, if I want to make this call:
```
#include <native_api.h>
int main()
{
    native_ExportedSymbols* lib = native_symbols();
    native_kref_test_Companion instance = lib->kotlin.root.test.Companion._instance();
    lib->kotlin.root.test.Companion.foo(instance);
}
```

This code would work correctly:
```
fun foo() {
    runBlocking {
        launch {
            println("Hello world")
        }
    }
}
```

But this code would cause the exception described:
```
fun foo() {
    GlobalScope.launch {
        println("Hello world")                
    }
}
```

I would like to make the call to "foo" asynchronous, the result is obtained through callbacks.

The library will be used by third parties.

Thanks a lot

**Comment by qwwdfsad** [comment]
You probably need to use `1.5.1-native-mt` version. Please see https://github.com/Kotlin/kotlinx.coroutines/issues/462
