### ISSUE TITLE
Rewrite channel operators on top of abstraction of cold streams

### ISSUE THREAD

**Issue by elizarov** [Kotlin/kotlinx.coroutines#285]
This issue is depended on and describes the next steps after introduction of cold streams abstraction as discussed in #254.

## Background

Channel operators were implemented in PR #88. They allow to write code like this:

```
val src = produce { ... } // a ReceiveChannel
val dst = src.filter { ... } // <-- intermediate
val list = src.toList() // <-- terminal
```

Here the operators like `filter` mimic operators that are available for `Sequence` type in Kotlin stdlib. There are _intermediate_ operators (like `filter`) and _terminal_ operators like _toList_.

All the intermediate operators start a new coroutine and consume the source channel (see also #279), they are not suspending functions by themselves, so execution immediately continues to the next step, where you can define the next operator. All the terminal operators also consume the source channel, but they suspend invoker until their job is done.

Typically, operators are used in a sequence starting from source, following through a chain of transformations, and then culminating in a terminal operation, like this:

```
src.map { ... }.filter { ... }.... .consumeEach { ... }
```

Here `consumeEach` is also a terminal operator that is used to perform some custom logic on each element.

**This is highly inefficient**. Every intermediate operation creates a _concurrent_ channel between coroutines, which is quite slow due to the support for concurrency. However, in the typical pipeline like shown above there is no need for concurrency between intermediate steps. 

## Proposed solution

The solution is to redefine all intermediate operators on `ReceiveChannel` so that instead of a `ReceiveChannel` they return a cold stream. 

**This is a breaking change**, however the chains of operators like this:

```
src.map { ... }.filter { ... }.... .consumeEach { ... }
```

will continue to work as before, because the same intermediate and terminal operators will be available on the resulting cold streams. The overall performance of this code will be vastly better (orders of magnitude faster), because there will be much less concurrency and communication. The will only one coroutine that invokes the final _terminal_ operation (in this example `consumeEach`) and the whole pipeline is going to be executed in the context of this terminal coroutine. 

There will be no need (and no support for!) specifying the context in each intermediate operation like `filter` and `map`. So the question is what happens to the code that needs for intermediate steps to happen in the specific context, like this:

```
src.map(UI) { /* must execute in UI */ }.toList()
```

This code will continue to be supported for a while although `map(UI) { ... }` will be deprecated and the proposed replacement is going to be through `produce { ... }` operator that will be defined on cold streams. This operator starts a coroutine to turn a cold stream into a hot one (into a channel) and it also accepts an optional context, so the above code would be rewritten to:

```
src.map { /* must execute in UI */ }.produce(UI).toList()
```

> Open issue: we can continue to support `map(UI) { ...}` as a shortcut for `map { ... }.produce(UI)` instead of deprecating it.

> Open issue: we can also support switching the context and staying with cold streams with another operator tailored to this purpose in a similar way as to how `observeOn`/`subscribeOn` work in Rx.

This `produce` would also allow to recover the old behavior where it is needed. Consider the following (legacy) code: 

```
fun ReceiveChannel<Int>.filterEven(): ReceiveChannel<Int> = 
    filter { it % 2 == 0 }
```

Unfortunately, it would stop to compile after this change (as the resulting type if `filter` is going to be different), but will keep _binary compatibility_ (so compiled code will continue to work). In order to fix this code, but retain the old signature for `filterEven` one would have to write:

```
fun ReceiveChannel<Int>.filterEven(): ReceiveChannel<Int> = 
    filter { it % 2 == 0 }
    .produce()
```

## Other related issues

#280 -- `broadcast` extension will need to be defined on cold streams, too, moreover all operators shall work on the resulting broadcast streams in the same way and produce cold streams that open the actual subscription when the cold stream is materialized.

#257 -- `transform` operation should return cold stream in the same way.

#180 -- new kind of `flatMap` operators will need to defined with cold streams, too.

#167 -- the solution to "fail-fast" when then same stream is consumed multiple times will have to be designed with the cold streams in mind. Hot stream should be considered "consumed" as soon as any operation is invoked on it, even though the result is still cold (not active until consumed). Trying to consume the cold stream that was created on top of a cold stream should result in an error, unless the stream was explicitly broadcasted with `broadcast` operator. 
 
#113 - the need for SPSC channel abstraction is superseded by this issue.

**Comment by dave08** [comment]
Would it be possible to keep `produce` and the planned `broadcast` as hot, and use `Subscribable` as cold, have a `subscribeOn` equivalent during the chaining and then at the end of the chain, call `produce(UI)` or `broadcast(UI)` to decide the type. Then have the terminator to actually start the coroutine?

**Comment by elizarov** [comment]
There are conceptual differences between cold rx-like subscribable streams and hot channels.

* Hot channel is like a TCP/IP networks connection. There are bytes arriving regardless of what you do or don't do and usually there is zero reason to subscribe more than once. You can broadcast a hot channel (called "share" in Rx) with a caveat that late subscribers will necessarily loose some events. Incorrect use of "get & subscribe" pattern is a typical source of bugs in all kinds of such applications. It only works reliable with something like `ConflatedBroadcastChannel` where every subscriber is guaranteed to get the most recent state of the object it subscribes for.

* Cold channel is just a functional indirection. Think about it as a reference to a function that knows how to generate data. You can invoke it more than once with each, each one getting new stream of values. 

How to represent this distinction in our interface and make sure that we don't make it all super-confusing is an open question. 

So far, the plan outlined in this issue uses cold channel as a performance optimization. We keep cold reference to the sequence of transformations, so that we can efficiently materialize it when the terminal operation is invoked.

**Comment by elizarov** [comment]
The ultimate decision is that most of the operators on channels are deprecated, instead, and will be removed in the future. So we will not support:

```
src.map { ... }.filter { ... }.... .consumeEach { ... }
```

But instead, the replacement is:

```
src.consumeAsFlow().map { ... }.filter { ... }.... collect { ... }
```

Note, that conversion from the hot channel to the cold stream is explicit.
