### ISSUE TITLE
some questions about CompletableFuture

### ISSUE THREAD

**Issue by ywf4026** [Kotlin/kotlinx.coroutines#2852]
Hi, when using kotilinx-coroutines-jdk8, I have some questions about CompletableFuture. 
1. Why is it necessary to transform CompletableFuture into a coroutine? Has the number of threads been reduced after using coroutine? 
2.  if I specify the thread pool 'executor' for CompletableFuture, 

```
val future = CompletableFuture.supplyAsync ({
                1
            }, executor)
```

can the coroutine run on these thread pools 'executor'? My purpose is to improve the utilization of the thread pool 'executor'. 
If it is feasible, how to write this code?

Thanks

**Comment by qwwdfsad** [comment]
Hi, your question is too general and I suggest asking it in our slack channel (#coroutines) or on stackoverflow
