### ISSUE TITLE
Is it okay to use higher version coroutine with lower version Kotlin?

### ISSUE THREAD

**Issue by RoadtoS7** [Kotlin/kotlinx.coroutines#2862]
I'm currently using Kotlin 1.4.32.
I want to use CallbackFlow which got stable in Coroutine 1.5.0.
Is it okay to use 1.5.0 Coroutine with Kotlin 1.4.32 release?

**Comment by qwwdfsad** [comment]
It is _probably_ possible, but not recommended in general.

`kotlinx.coroutines` are _forward-compatible_ with Kotlin, e.g. it's possible to use coroutines `1.3.0` with Kotlin `1.3.x`, `1.4.x`, `1.5.x` and so on. But the opposite is not the true -- e.g. the newer version of coroutines might be using the API only present in Kotlin 1.5.0 and above. 

So you can try it with a thoughtful testing of your app scenarios, but it's much better to update Kotlin version instead
