### ISSUE TITLE
Binary incompatibitlity between different kotlinx-coroutines modules

### ISSUE THREAD

**Issue by frost13it** [Kotlin/kotlinx.coroutines#2865]
Given a following set of dependencies:
```
dependencies {
    implementation "org.jetbrains.kotlinx:kotlinx-coroutines-core:1.5.1"
    implementation "org.jetbrains.kotlinx:kotlinx-coroutines-jdk8:1.4.3"
}
```

This simple function fails with `java.lang.NoSuchMethodError: 'void kotlinx.coroutines.AbstractCoroutine.<init>(kotlin.coroutines.CoroutineContext, boolean, int, kotlin.jvm.internal.DefaultConstructorMarker)'`:
````
suspend fun main(): Unit = coroutineScope {
    future {  }
}
````

It is caused by binary incompatibitlity of `AbstractCoroutine` from `kotlinx-coroutines-core` module. Despite it is an "internal" API, it is used in another module, whose version might not be the same.

Dependency graph:
<pre>
runtimeClasspath - Runtime classpath of compilation 'main' (target  (jvm)).
+--- org.jetbrains.kotlin:kotlin-stdlib-jdk8:1.5.20
|    +--- org.jetbrains.kotlin:kotlin-stdlib:1.5.20
|    |    +--- org.jetbrains:annotations:13.0
|    |    \--- org.jetbrains.kotlin:kotlin-stdlib-common:1.5.20
|    \--- org.jetbrains.kotlin:kotlin-stdlib-jdk7:1.5.20
|         \--- org.jetbrains.kotlin:kotlin-stdlib:1.5.20 (*)
+--- org.jetbrains.kotlinx:kotlinx-coroutines-core:1.5.1
|    \--- org.jetbrains.kotlinx:kotlinx-coroutines-core-jvm:1.5.1
|         +--- org.jetbrains.kotlin:kotlin-stdlib-jdk8:1.5.20 (*)
|         \--- org.jetbrains.kotlin:kotlin-stdlib-common:1.5.20
\--- <b>org.jetbrains.kotlinx:kotlinx-coroutines-jdk8:1.4.3</b>
     +--- <b>org.jetbrains.kotlinx:kotlinx-coroutines-core:1.4.3 -> 1.5.1</b> (*)
     \--- org.jetbrains.kotlin:kotlin-stdlib:1.4.30 -> 1.5.20 (*)
</pre>

To prevent such situation, both modules should depend on `kotlinx-coroutines-bom` of the corresponding version, as described in [Gradle documentation](https://docs.gradle.org/current/userguide/dependency_version_alignment.html#aligning_versions_natively_with_gradle).
This way, `kotlinx-coroutines-core:1.5.1` would upgrade `kotlinx-corotuines-jdk8:1.4.3` to the same version, resolving the issue.

**Comment by qwwdfsad** [comment]
Thanks for the suggestion!
