### ISSUE TITLE
Dispatchers.Main.immediate with join deadlocking inside runBlocking

### ISSUE THREAD

**Issue by kbabcockuf** [Kotlin/kotlinx.coroutines#2868]
Breaking down a simple case on Android to do concurrent processing with coroutines, the following code only prints `Launched` and `runBlocking` never completes:

```
    runBlocking {
          val ioJob = launch(Dispatchers.IO) {
            delay(1000)
          }
          val mainJob = launch(Dispatchers.Main.immediate) {
            Log.d("Routine", "Launched")
            ioJob.join()
            Log.d("Routine", "Joined")
          }
    
          listOf(mainJob, ioJob).joinAll()
        }
```

Of course, if we replace `Dispatchers.Main.immediate` with `Dispatchers.IO` everything works great, but we need to run some of the concurrent processing on the main thread.  Imagine a set of processing that occasionally needs to update the UI or otherwise perform something that requires main thread.

Using `Dispatchers.Main` doesn't log anything, as expected.  It appears that once a `join` is performed within the root of `runBlocking` it paralyzes anything suspended that was dispatched to main.

Worth noting, an approach predicated on `CountDownLatch` and threads works great:

```
    val latchMain = CountDownLatch(1)
    val primaryLatch = CountDownLatch(2)

    val ioExecutor = Executors.newCachedThreadPool(Executors.defaultThreadFactory())

    log("Execute IO")
    ioExecutor.execute(
        Runnable {
          log("Delay IO")
          Thread.sleep(1000)
          log("Countdown Main")
          latchMain.countDown()
          Thread.sleep(3000)
          primaryLatch.countDown()
        })

    log("Execute Main")
    Runnable {
      log("Await Main")
      latchMain.await()
      log("Countdown Primary")
      primaryLatch.countDown()
    }.run()

    log("Await Primary")
    primaryLatch.await()
    log("Continue")

    stepTracker.endTracking()
    return stepTracker.stepGraphTrace
  }

  private fun log(msg: String) = Log.i("Routine", "[${Thread.currentThread().name}] $msg")
```

With ouput:

```
2021-08-11 11:04:06.508 23828-23828/com.ubercab.presidio.exo I/Routine: [main] Execute IO
2021-08-11 11:04:06.509 23828-23828/com.ubercab.presidio.exo I/Routine: [main] Execute Main
2021-08-11 11:04:06.510 23828-23828/com.ubercab.presidio.exo I/Routine: [main] Await Main
2021-08-11 11:04:06.510 23828-23888/com.ubercab.presidio.exo I/Routine: [pool-25-thread-1] Delay IO
2021-08-11 11:04:07.512 23828-23888/com.ubercab.presidio.exo I/Routine: [pool-25-thread-1] Countdown Main
2021-08-11 11:04:07.513 23828-23828/com.ubercab.presidio.exo I/Routine: [main] Countdown Primary
2021-08-11 11:04:07.513 23828-23828/com.ubercab.presidio.exo I/Routine: [main] Await Primary
2021-08-11 11:04:10.514 23828-23828/com.ubercab.presidio.exo I/Routine: [main] Continue
```

Any ideas?

**Comment by kbabcockuf** [comment]
Per a wonderful [stackoverflow](https://stackoverflow.com/a/68736878/345606) response, we can accomplish this by inheriting the context of `runBlocking` rather than explicitly specifying `Dispatchers.Main`. 

```
runBlocking {
    log("runBlocking: start")

    val ioJob = launch(Dispatchers.IO) {
        log("ioJob: About to delay")
        delay(1000)
        log("ioJob: Delay done")
    }

    val mainJob = launch {
        log("mainJob: About to join ioJob")
        ioJob.join()
        log("mainJob: ioJob successfully joined")
    }


    // yield() if you want to start executing mainJob before the rest of the runBlocking code

    log("runBlocking: about to join jobs")
    listOf(ioJob, mainJob).joinAll()
    log("runBlocking: jobs joined, exiting")
}

private fun log(msg: String) = Log.i("MainActivity", "[${Thread.currentThread().name}] $msg")
```

Despite the workaround, I'd argue this is not expected logic.  It shouldn't matter if I inherit `runBlocking` weird one-of-a-kind context or not for running other logic on main inside `runBlocking`.

**Comment by qwwdfsad** [comment]
> It shouldn't matter if I inherit runBlocking weird one-of-a-kind context or not for running other logic on main inside runBlocking.

But it should. 

Your example basically has two moving parts:

* `runBlocking`. This is pretty dangerous primitive in the UI development because, as its documentation states, **it blocks the current thread until its completion**. Meaning that no other work can be done in the current thread besides `runBlocking` body.

* `launch(Dispatchers.Main.immediate)` (or `launch(Dispatchers.Main)`, doesn't really matter as the code will deadlock anyway). It tries to schedule the coroutine to the Main thread, but it is already blocked by `runBlocking`.

`runBlocking` has no access to the thread or context it executes on, so it cannot potentially know that there are some tasks _for the thread_ (not for the `runBlocking` itself) that has to be executed in order to progress. It is just a bridge that connects suspending and blocking worlds and waits until the suspending one completes.
