### ISSUE TITLE
Clarify Flow flatMap..., transform... operators strange behaviour. flatMapLatest does not receive a value from upstream and continues downstream forever

### ISSUE THREAD

**Issue by zetokz** [Kotlin/kotlinx.coroutines#2911]
I am facing an issue in my code when being subscribed for MutableStateFlow.flatMapLatest operator doesn't receive any new value.

Unfortunately, the behavior is bizarre for me, and I can't reproduce it without the exact code I use.

But in general, it looks next (simplified version):

```kotlin
class Main {
    interface Api {
        fun doJob() // that is just an external library function I don't have control over and everything I know that it calls C++ lock under the hood
    }
    class Changes
    class Entity

    val externalApi: Api

    val shouldProduce = MutableStateFlow<Boolean>(false)
    val foreverProducer = MutableStateFlow<Entity?>(null)

    init {
        GlobalScope.launch {
            repeat(Int.MAX_VALUE) {
                delay(100)
                foreverProducer.value = Entity()
            }
        }
        GlobalScope.launch {
            repeat(Int.MAX_VALUE) {
                delay(1000)
                shouldProduce.value = !shouldProduce.value
                println("shouldProduce.value == ${shouldProduce.value}")
            }
        }
    }

    fun trackProducedEntities(): Flow<Entity> {
        return foreverProducer.filterNotNull()
    }

    fun trackChanges(): Flow<Changes> {
        return shouldProduce.flatMapLatest {
            println("shouldProduce: flatMapLatest.value = $it") // called only once an never again!!!
            if (it) trackProducedEntities().map { externalApi.doJob() }.map { Changes() } else emptyFlow()
        }
    }

    suspend fun main() {
        trackChanges().collect {
            println("trackChanges.collect: value = $it") // tracking changes forever
        }
    }
}
```

Expected behavior from the above code is: 
I receive Changes class instance each 100 millis until `shouldProduce` flow receives value `false` and for the next second we don't receive anything, and it happens in a loop for each 1 second time window.

But what I have in actual behavior:
Once `shouldProduce` receives `true`, I start receiving changes, and even I see that `false` value is sent every second to `shouldProduce` flow, the `flatMapLatest` doesn't receive it, and it could be easily seen because my `shouldProduce: flatMapLatest.value` log is never called again.

It would be very easy if it weren't so complicated. If I remove `foreverProducer.filterNotNull()`, the issue won't be reproducing anymore, or if I remove `externalApi.doJob()`, the issue will not be reproducing too. (what happens inside externalApi.doJob() I can't say as it is external lib I do not have any source code the only I can say at the final point it calls JNI interface)

So, having all the above, my question to `flow` experts, should it ever be possible that `flatMapLatest` operator in `flow` doesn't receive an upstream value? And if yes, what is the scenario for this? 
I am really confused about this bug in my code...

Thanks in advance for any assistance.

**Comment by zetokz** [comment]
Update:
When I try to debug what happens everything is working fine :(

**Comment by qwwdfsad** [comment]
Hi, unfortunately, it's hard to tell what exactly is wrong without the actual reproducer or additional details.

If removing some of the operators prevents the issue from reproducing, I would say that this is a timing issue (-> data-race) in your code. If `flatMapLatest` does not receive any values, it may be the case that the dispatcher that it is using (the one where you call `collect`) is always occupied by some other jobs.

To help you with debugging, you can try using our[ debugging agent](https://github.com/Kotlin/kotlinx.coroutines/blob/master/kotlinx-coroutines-debug/README.md) that is also available in [IDEA](https://kotlinlang.org/docs/debug-coroutines-with-idea.html#debug-coroutines)
