### ISSUE TITLE
failing test? CompletableFuture.cancel

### ISSUE THREAD

**Issue by venkatperi** [Kotlin/kotlinx.coroutines#292]
File: `kotlinx.coroutines/integration/kotlinx-coroutines-jdk8/src/test/kotlin/kotlinx/coroutines/experimental/future/FutureTest.kt` 
Test: `testCancellableAwaitFuture`
Error: `java.lang.IllegalStateException: Expecting action index 6 but it is only 5`

Or is just failing for me?

I'm not surprised since CompletableFuture.cancel() doesn't behave like other Futures. The future doesn't call downstream handlers nor does it cancel threads; presumably by design ([link](http://www.nurkiewicz.com/2015/03/completablefuture-cant-be-interrupted.html)).

Here's a [test](https://github.com/venkatperi/kotlin-promise/blob/master/src/test/java/com/vperi/promise/Misc.Test.kt) for CompletableFuture.cancel (vs. SettableFuture.cancel):

**Comment by jcornaz** [comment]
All test pass for me at the current states of [develop](https://github.com/Kotlin/kotlinx.coroutines/tree/d7d9e2fabf61b768c8bbc6fd875a9060a261b86f) and and of [master](https://github.com/Kotlin/kotlinx.coroutines/tree/fcdce10143103fb5418e6247abfd44fd8ff941ef)

(including `FutureTest.testCancellableAwaitFuture()` of course)

My JDK: 1.8.0_131

`CompletableFuture.cancel()` is not called in the test you mentioned. `testCancellableAwaitFuture` only ensure, that `await` is a cancellable suspending function. For that it cancel the `Job`, and verify that `await` throw a `CancellationException`. This doesn't test the cancellation of the future itself. The future, actually complete, but this is not tested.

**Comment by elizarov** [comment]
@venkatperi What is the configuration of you system (OS, CPU) and what JDK version you are using?

**Comment by venkatperi** [comment]
```
Darwin Venkats-MacBook-Pro.local 17.0.0 Darwin Kernel Version 17.0.0: Thu Aug 24 21:48:19 PDT 2017; root:xnu-4570.1.46~2/RELEASE_X86_64 x86_64
```

```
java version "1.8.0_144"
Java(TM) SE Runtime Environment (build 1.8.0_144-b01)
Java HotSpot(TM) 64-Bit Server VM (build 25.144-b01, mixed mode)
```
