### ISSUE TITLE
Copyright didn't get updated after 2019.

### ISSUE THREAD

**Issue by Pradumnasaraf** [Kotlin/kotlinx.coroutines#2934]
**Problem**
Copyright didn't get updated after 2019.

Should I update this to 2021?

![Screenshot 2021-09-14 193843](https://user-images.githubusercontent.com/51878265/133273182-6ebc4632-dd8b-4e4d-9528-01f90f75f096.png)

**Comment by qwwdfsad** [comment]
Fixed in develop, thanks!
