### ISSUE TITLE
SharedFlow and StateFlow operators

### ISSUE THREAD

**Issue by P1NG2WIN** [Kotlin/kotlinx.coroutines#2938]
What happens to `SharedFlow`/`StateFlow `after using on them operators returning flow? They turn into regular cold flows and I need to re-do `stateIn`/`shareIn` or the operators just changed the type, but the behavior remains the same and is it enough to cast `as SharedFlow`?

**Comment by qwwdfsad** [comment]
Yes, the instance to which the operator is applied is cold, the original source remains hot.

Please use slack channel or stackoverflow for general questions
