### ISSUE TITLE
pauseDispatcher not working

### ISSUE THREAD

**Issue by jaozinfs** [Kotlin/kotlinx.coroutines#2947]
I'm trying to run some late tests where I need to test different scenarios of a use case.
I'm injecting my test dispatcher so that I can control the routine's currentTime.
I'm getting ahead in time, but I can't stop dispatchImmediately:
`
internal class CheckoutCardUseCase(
    ....
    private val defaultDispatcher: CoroutineDispatcher = Dispatchers.Default
) {
    private val checkoutAttemptDelay = 3_000L
    private val expectedTime = 18_000L

    suspend operator fun invoke(): Result<...> =
        withContext(defaultDispatcher) {
            tryToResult {
                val response = withTimeoutOrNull(expectedTime) {
                    var response: ...? = null
                    do {
                        if (coroutineContext[Job]?.isActive == true) {
                            response =
                                repository.data

                            if (response.inAnalysis())
                                delay(checkoutAttemptDelay)
                        }
                    } while (response.inAnalysis())

                    ...
                } ?: throw TimeoutException("Time out on polling checkout")
                ....
            }
        }
`
My test:

@Test
fun test() = testCoroutineDispatcher.runBlockingTest {
            val mockBaseOpResponse = mockk()
            val expectedException = TimeoutException("Time out on polling checkout")
            val mockClientDetails = mockk()
            coEvery { userRepository.initApplication(any()) } returns mockBaseOpResponse
            coEvery { getClientDetailsUseCase.invoke() } returns mockClientDetails
            pauseDispatcher {
               val result = checkoutCardUseCase.invoke()
                assertThat<Result.Error<CheckNextTaskUseCase.NextStep>>(result) {
                    assertTrue(error is TimeoutException)
                    assertEquals(expectedException.message, error?.message)
                }
                verify(exactly = 0) { checkNextTaskUseCase.checkNextTask(any()) }
            }
}

**Comment by dkhalanskyjb** [comment]
Could you please clarify what behavior you expect and what behavior you get instead? Without knowing what, for example, `response.inAnalysis()` or `checkNextTask` do, for example, it's difficult to make sense of this.

In any case, know that `pauseDispatcher` does *not* prevent code from executing altogether: it only prevents the code from executing *immediately*. If you run `advanceTimeBy`, for example, then the code that is scheduled to run will run, regardless of whether the dispatcher is paused. Yeah, this is confusing.

**Comment by jaozinfs** [comment]
`val response = withTimeoutOrNull(expectedTime) {
                var response: ...? = null
                do {
                    if (coroutineContext[Job]?.isActive == true) {
                        response =
                            repository.data

                        if (response.inAnalysis()) // check if response stay on analysis, if yes, the code call a delay
                            delay(checkoutAttemptDelay)
                    }
                } while (response.inAnalysis()) // check if response stay on analysis, if not, continue with code withTimeOutOrNull
                cardRepository.checkout().data // return another call response
          }
          checkNextTaskUseCase.checkNextTask(response.routeTask) // finally, the next task will be checked with the call response        `

**Comment by jaozinfs** [comment]
> Você poderia esclarecer qual comportamento você espera e qual comportamento você obtém em vez disso? Sem saber o que, por exemplo, `response.inAnalysis()`ou `checkNextTask`fazer, por exemplo, é difícil entender isso.
> 
> Em qualquer caso, saiba que `pauseDispatcher`isso _não_ impede que o código seja executado completamente: apenas impede que o código seja executado _imediatamente_ . Se você executar `advanceTimeBy`, por exemplo, o código programado para execução será executado, independentemente de o distribuidor estar em pausa. Sim, isso é confuso.

As far as I understand, pauseDispatchers blocks delays from being skipped, isn't that right?

**Comment by dkhalanskyjb** [comment]
Not really; it only affects things like `launch` and `async`. Regardless of whether the dispatcher is paused, the code after, say, `delay(1000)` will not run until the virtual time advances to the point after the delay, so if you call `advanceTimeBy`, the delay will be skipped.

**Comment by jaozinfs** [comment]
runBlockingTest automatically calls advanceUntilIdle(), that advances the current time.

` /**
     * Immediately execute all pending tasks and advance the virtual clock-time to the last delay.
     *
     * If new tasks are scheduled due to advancing virtual time, they will be executed before `advanceUntilIdle`
     * returns.
     *
     * @return the amount of delay-time that this Dispatcher's clock has been forwarded in milliseconds.
     */
    @ExperimentalCoroutinesApi // Since 1.2.1, tentatively till 1.3.0
    public fun advanceUntilIdle(): Long`

**Comment by dkhalanskyjb** [comment]
Sure. This still doesn't explain what behavior you find surprising.

**Comment by dkhalanskyjb** [comment]
There is no `pauseDispatcher` anymore, so this is obsolete.
