### ISSUE TITLE
operator `or` for `Flow`

### ISSUE THREAD

**Issue by YuryMikhailuts** [Kotlin/kotlinx.coroutines#2951]
Good afternoon. It is possible that I am now reinventing the wheel, but I could not solve my problem otherwise. I needed an operator that would combine two `Flow` into one, but not in the same way as `zip` or `combine`, but simply adding the values from both flows into one as they come. Thus, if one of the flows is suspended, the second one continues to output results in the output flow.

```kotlin
@OptIn(InternalCoroutinesApi::class)
infix fun <R, U : R, V : R> Flow<U>.or(right: Flow<V>) = object : Flow<R> {
    override suspend fun collect(collector: FlowCollector<R>): Unit = coroutineScope {
        listOf(
            launch {
                this@or.collect {
                    collector.emit(it)
                }
            }, launch {
                right.collect {
                    collector.emit(it)
                }
            }
        ).joinAll()
    }
}
```

Thank you in advance for the answer and I'm sorry if I have written something stupid.

**Comment by fvasco** [comment]
```koltin
suspend fun <T> merge(vararg flows: Flow<T>): Flow<T> = channelFlow {
    for (flow in flows) launch { flow.collect(::send) }
}
```

**Comment by YuryMikhailuts** [comment]
> ```
> suspend fun <T> merge(vararg flows: Flow<T>): Flow<T> = channelFlow {
>     for (flow in flows) launch { flow.collect(::send) }
> }
> ```

Thanks. Your method is simpler.

**Comment by qwwdfsad** [comment]
Such operator already exists: [`merge`](https://kotlin.github.io/kotlinx.coroutines/kotlinx-coroutines-core/kotlinx.coroutines.flow/merge.html).

Naming its counterpart and naming it `or` will confuse people, as it may be interpreted as boolean-like operator or as exclusive or (e.g. `if first is empty, collect second`)

**Comment by YuryMikhailuts** [comment]
> Such operator already exists: [`merge`](https://kotlin.github.io/kotlinx.coroutines/kotlinx-coroutines-core/kotlinx.coroutines.flow/merge.html).
> 
> Naming its counterpart and naming it `or` will confuse people, as it may be interpreted as boolean-like operator or as exclusive or (e.g. "if first is empty, collect second")

Thank you for your answer. I didn't know it was called `merge`. I apologize for misleading you.
