### ISSUE TITLE
how do we plan to keep the reactor module updated based on the updates to reactor-core?

### ISSUE THREAD

**Issue by piyushmor** [Kotlin/kotlinx.coroutines#2960]
currently `kotlinx-coroutines-reactor` module version `1.5.2` uses the `reactor-core` version of `3.4.1`. How do we plan on keep these in sync in the long run? do we need to create a new issue every time when reactor needs to be upgraded? or should this have a separate release cycle based on each reactor and coroutine release?

**Comment by qwwdfsad** [comment]
We do not plan to keep it in sync on a regular basis. Reactor is expected to be fully backwards compatible (at least when no internal API is involved), so we don't have to keep it in sync: end users can just depend on the latest version of Reactor and enjoy both coroutines and latest Reactor features.

Could you please elaborate on why you do think this is a serious concern?

**Comment by piyushmor** [comment]
> We do not plan to keep it in sync on a regular basis. Reactor is expected to be fully backwards compatible (at least when no internal API is involved), so we don't have to keep it in sync: end users can just depend on the latest version of Reactor and enjoy both coroutines and latest Reactor features.
> 
> Could you please elaborate on why you do think this is a serious concern?

Maybe it is and maybe it is not, I cannot comment on that. But in the past I had raised a similar issue: https://github.com/Kotlin/kotlinx.coroutines/issues/2432

**Comment by dkhalanskyjb** [comment]
(Offtop) I'd say that a better pun is the opposite, that is, that we intend to update the dependencies reactively, as opposed to proactively.

**Comment by fvasco** [comment]
Appeal to novelty is a common fallacy, we should consider that a newer version may contain a bug without a known workaround, updating a dependency *just to stay tuned* does not improve the integration.
This module is an adapter, so I can expect that the end-user already declares a direct dependency from Reactor, they is free to choose the reactor version and upgrade/downgrade as preferred.

**Comment by piyushmor** [comment]
ok makes sense
