### ISSUE TITLE
non-intuitive behavioral difference between first() and single()

### ISSUE THREAD

**Issue by LifeIsStrange** [Kotlin/kotlinx.coroutines#2962]
I have an example where we have a flux of events, we apply a filter that reduce the flux to only one specific event.
The prints in the second onEach() prove that there is only one resulting even after the filtering.
when I terminate the final flow with the terminal operator first(), the flow terminate and everything is fine.
But when I use the terminal operator single() instead, the second onEach clearly only print one event but for an unknown reason, single() dot NOT terminate/cancel the flow (the original flow "projectEventStream" is a never ending flow otherwise), and yet do not throw any Exception.

``` Kotlin
launch {
            brainflowObserver.projectEventStream.onEach { System.err.println("1: ${it.eventType}") }
                .filter { (it.payload.payloadType == ProjectPayloadType.BRAINFLOW) && (it.eventType == EventType.DELETE) }
                .onEach { System.err.println("2: ${it.eventType}") }
                .single()
        }
```

``` Kotlin
launch {
            brainflowObserver.projectEventStream.onEach { System.err.println("1: ${it.eventType}") }
                .filter { (it.payload.payloadType == ProjectPayloadType.BRAINFLOW) && (it.eventType == EventType.DELETE) }
                .onEach { System.err.println("2: ${it.eventType}") }
                .single()
        }
```

**Comment by dkhalanskyjb** [comment]
`single` shouldn't cancel the flow; instead, it should throw an exception if more than one emission happens. Could you please provide a complete reproducer of where it isn't the case?

**Comment by LifeIsStrange** [comment]
update: I now understand that only some terminal operators do cancel the upstream flow, and that single contrary to first has no way of knowing when to cancel so it doesn't.
