### ISSUE TITLE
[Play Services Integration] Add support for CancellableTask's progress listener.

### ISSUE THREAD

**Issue by psteiger** [Kotlin/kotlinx.coroutines#2970]
Hi,

It is relatively common to have use cases of long running tasks that report back the task progress to a callback installed through `CancellableTask<T>.addOnProgressListener()`. One such example is Firebase's `StorageTask` for uploading files.

It seems simple enough to support such use cases in the coroutine world by providing a variant of the current `Task<T>.await()` that extends `CancellableTask` instead of `Task`, takes a callback for progress reporting, and returns the Task result (T).

 I have a draft code for it and can submit a PR if welcome:

```kotlin
suspend fun <ProgressT : Any, T : ProgressT> CancellableTask<T>.await(
    coroutineContext: CoroutineContext = EmptyCoroutineContext, // CoroutineContext for the suspending callback
    cancellationTokenSource: CancellationTokenSource?,
    onProgress: suspend (ProgressT) -> Unit
): : T = coroutineScope { // parallel decomposition of the progress reporting coroutine and calling coroutine.
    // have the progress callback send to a conflated channel
    val progressChannel = Channel<ProgressT>(capacity = Channel.CONFLATED)
    // consume the progress channel in a separate coroutine
    launch(coroutineContext) {
        for (progress in progressChannel) onProgress(progress)
    }
    // if passed coroutineContext parameter has a CoroutineDispatcher, we can (should, must?) use it
    // as the executor for addOnProgressListener().
    val dispatcher = coroutineContext[ContinuationInterceptor] as? CoroutineDispatcher
        ?: currentCoroutineContext()[ContinuationInterceptor] as? CoroutineDispatcher
    val executor = dispatcher?.asExecutor()
    val listener = OnProgressListener<ProgressT> { progressChannel.trySend(it) }
    val task = executor?.let {
        addOnProgressListener(executor, listener)
    } ?: addOnProgressListener(listener)
    try {
        cancellationTokenSource?.let {
            task.await(cancellationTokenSource)
        } ?: task.await()
    } finally {
        // task has ended: close the progress channel
        progressChannel.close()
    }
}
```

**Comment by qwwdfsad** [comment]
Hi, 

The overall code looks okay, though it's a bit too domain-specific to be a general-purpose primitive: it (maybe unexpectedly) launches a coroutine, it uses a specific to a concrete use-case primitive in order to keep track of progress (e.g. others may want non-conflated channel or hot flow), it doesn't (though it may be desired) cancel the task if progress listener has crashed and so on.

I would suggest having a project-specific extension in your project's codebase, especially when it doesn't require to use any private/internal coroutines API

**Comment by psteiger** [comment]
Hi, thanks for your response!

> The overall code looks okay, though it's a bit too domain-specific to be a general-purpose primitive: 

I'm not sure I agree that, conceptually, it's too domain-specific. It's a coroutine integration for a listener on a task progress. Usually, but not necessarily limited to, file transferring.

However, I realize now that it is an extension on `CancellableTask`, which is a `com.google.firebase.storage` class and not a core GMS Tasks class. That alone might make it a no-go for kotlinx-coroutines integrations lib. Firebase extensions probably would better be provided by some "firebase-ktx" lib, or project-local extensions as you suggested.

> it (maybe unexpectedly) launches a coroutine, it uses a specific to a concrete use-case primitive in order to keep track of progress (e.g. others may want non-conflated channel or hot flow), it doesn't (though it may be desired) cancel the task if progress listener has crashed and so on.

I completely agree that the drafted implementation is too much opinionated and too little configurable. It has sane choices to me (so far) but of course mileage may vary.

> I would suggest having a project-specific extension in your project's codebase, especially when it doesn't require to use any private/internal coroutines API

That's perfectly fine for my needs, of course.

Thanks!

I'm closing this issue.
