### ISSUE TITLE
Job prints error to stderr while Deferred does not

### ISSUE THREAD

**Issue by mjburghoffer** [Kotlin/kotlinx.coroutines#298]
`Job` causes a stacktrace of the exception via the thread's `uncaughtExceptionHandler`.   `Deferred` does not.  It seems as though these both should behave the same in this circumstance, without needing to do a workaround with `ServiceLoader`,  `context`, or `Thread.setDefaultUncaughtExceptionHandler()`.  I'd rather not have exceptions in jobs be printed unless my logging framework does so, and also it would be preferable to do so where the exception is thrown, not later on via a static handler function (not very DI-friendly).  Here is the following code being executed from the java stdlib:

```java
    // public class java.lang.ThreadGroup.java

    public void uncaughtException(Thread t, Throwable e) {
        if (parent != null) {
            parent.uncaughtException(t, e);
        } else {
            Thread.UncaughtExceptionHandler ueh =
                Thread.getDefaultUncaughtExceptionHandler();
            if (ueh != null) {
                ueh.uncaughtException(t, e);
            } else if (!(e instanceof ThreadDeath)) {
                System.err.print("Exception in thread \""
                                 + t.getName() + "\" ");
                e.printStackTrace(System.err);
            }
        }
    }
```

This is invoked from `Job` (but not `Deferred`) because `StandardCoroutine` overrides the following:

```kotlin
private open class StandaloneCoroutine(
    private val parentContext: CoroutineContext,
    active: Boolean
) : AbstractCoroutine<Unit>(parentContext, active) {
    override fun hasOnFinishingHandler(update: Any?) = update is CompletedExceptionally
    override fun onFinishingInternal(update: Any?) {
        // note the use of the parent's job context below!
        if (update is CompletedExceptionally) handleCoroutineException(parentContext, update.exception) // <-- this is the cause.
    }
}
```

This is very easy to reproduce with the following:

```kotlin
runBlocking {
  launch { throw Exception("job") }.join()  // does print
  async { throw Exception("deferred") }.join()  // no print
}
```

What are the thoughts around this?

**Comment by fvasco** [comment]
You should not ignore the result of `async` computation, somewhere you should invoke `async { }.await()`.

Differently you cannot manage externally the result of `launch`.

**Comment by jcornaz** [comment]
This is by design. If you choose to use `async` over `launch`, it means you care about the result and plan to use `await` and manage any exception at that time (it would be thrown by `await`).

If you choose to use `launch` over  `async`, it means you don't care about the result and let the exception handler manage the exceptions.

As @fvasco said:
> You should not ignore the result of async computation, somewhere you should invoke async { }.await().

That's because if you ignore the result, it means you don't want an `async`, but a `launch`.
