### ISSUE TITLE
Execution of async code in a new thread

### ISSUE THREAD

**Issue by dzharkov** [Kotlin/kotlinx.coroutines#3]
In current implementation execution of coroutine code starts in the same thread and continues until first execution point.
Probably it's worth to run it on a thread-pool (it could be another parameter with some sensible default value, e.g. `ForkJoinPool.commonPool()`)

**Comment by ilya-g** [comment]
It should be noted that in .NET `async` has similar behavior — it runs synchronously until the first `await` is encountered. It even can continue to execute synchronously in case if the awaitable being awaited is already completed. It all helps to minimize unnecessary thread switches.

In case if one needs to postpone the execution, it can be done with [`Task.Yield`](https://msdn.microsoft.com/en-us/library/system.threading.tasks.task.yield(v=vs.110).aspx) awaitable:
```
await Task.Yield()
```

**Comment by elizarov** [comment]
The decision was to always require an explicit specification of execution policy for most coroutine builder. So `launch(Here) { ... }` would execute like in .NET (until first suspend), while `launch (CommonPool) { ... }` would immediate schedule into a background thread. Other execution policies can be defined by user.   The only exception is a `future { }` which goes to `CommonPool` by default.
