### ISSUE TITLE
How to convert a callback to a Deferred on JDK6

### ISSUE THREAD

**Issue by ljani** [Kotlin/kotlinx.coroutines#30]
I'm still a little new to Kotlin and especially its coroutines, so pardon me if I'm asking stupid questions.

Could you provide an example how to interface a third-party library utilizing callbacks with `kotlinx-coroutines-core` with JDK6?

If it's currently not possible, could the required functionality be considered to be added?

`kotlinx-coroutines-jdk8` has `CompletableFuture`, but I'm not able to use JDK8. Another way would be to utilize something like [streamsupport's](https://sourceforge.net/projects/streamsupport/) `streamsupport-cfuture`, but I'd prefer not to add it as a dependency if possible.

Also, I could use channels, but if `Deferred` is the recommended way to transfer a single value between coroutines, I'd like to use that.

Love the work you are doing!

**Comment by elizarov** [comment]
Kotlin coroutines is not a replacement for 3rd party libraries. Kotlin coroutines, together with supporting functions from `kotlinx.coroutines` enables you to _use_ your asynchronous libraries in a natural style, without succumbing to callback hell.

If your 3rd party library uses callbacks, then you should be able to _wrap_ those callback-style functions into _suspending_ functions and use them from your coroutines, as explained in the corresponding section of the design document: 
https://github.com/Kotlin/kotlin-coroutines/blob/master/kotlin-coroutines-informal.md#wrapping-callbacks

**Comment by ljani** [comment]
Thanks for the answer, the second paragraph is exactly what I was after. TBH, I had viewed that document before, but as a beginner it was a little too heavy reading, so I missed that part.

So, if anyone ends up here via eg. Google, [the answer](https://github.com/Kotlin/kotlin-coroutines/blob/dcd9d1246cc76b178ec9a5a706377b7aca345d32/kotlin-coroutines-informal.md#wrapping-callbacks) is:
```kotlin
suspend fun someLongComputation(params: Params): Result = suspendCoroutine { c ->
    someLongComputation(params) { c.resume(it) }
}
```

**Comment by vitalybe** [comment]
To expand a bit, here is how you're actually using `someLongComputation`:

`val result = async(CommonPool) { someLongComputation(params) }.await()`
