### ISSUE TITLE
Usages of the coroutineContext in the docs instead of currentCoroutineContext()

### ISSUE THREAD

**Issue by andrew-k-21-12** [Kotlin/kotlinx.coroutines#3008]
In some of code snippets there are calls to the `CoroutineScope`'s `coroutineContext` - for example in the [Pipelines](https://kotlinlang.org/docs/channels.html#pipelines) section for channels:
```kotlin
// ...
coroutineContext.cancelChildren() // cancel children coroutines
```

At the same time the doc for `coroutineContext` says: 
> Accessing this property in general code is not recommended for any purposes except accessing the [Job] instance for advanced usages.

Also, the doc for `currentCoroutineContext()` says:
> Returns the current [CoroutineContext] retrieved by using [kotlin.coroutines.coroutineContext].
> This function is an alias to avoid name clash with [CoroutineScope.coroutineContext] in a receiver position:
>
> ```
> launch { // this: CoroutineScope
>     val flow = flow<Unit> {
>         coroutineContext // Resolves into the context of outer launch, which is incorrect, see KT-38033
>         currentCoroutineContext() // Retrieves actual context where the flow is collected
>     }
> }
> ```

In the particular examples in the docs usages of the `coroutineContext` instead of `currentCoroutineContext()` don't lead to bad consequences, but It seems like learners can develop a bad habit of such usages. Maybe it's reasonable to be replaced with `currentCoroutineContext()` where possible? Am I wrong?

**Comment by andrew-k-21-12** [comment]
Thank you for the explanations. 

I think the question is whether nesting of coroutine scopes (for example in the way as shown [here](https://youtrack.jetbrains.com/issue/KTIJ-16542)) is good or not. If it's a kind of anti-pattern by itself (and my position is that it should be avoided), then obviously there is no reason in the `coroutineContext` -> `currentCoroutineContext()` replacement. 

Otherwise it's difficult to agree that the such replacement will have no reason because it can prevent from accidental feet shooting.

Of course it's up to you to decide, have nothing left to describe my opinion 🙂

**Comment by dkhalanskyjb** [comment]
The issue you link is not about nesting scopes (which works fine), it's about the `flow` (or suspending lambdas in general) defining no scope, so `coroutineContext`, which would typically return the current coroutine's context, *but* because there's a `coroutineScope` wrapping it, the scope is queried for its context instead.

The flow issue also doesn't seem bad, as, like we're discussing, there aren't many reasons usually to access the `coroutineContext`, doubly so inside `flow`. So, this feels like an issue that could only surface in fairly advanced code.

**Comment by andrew-k-21-12** [comment]
Thank you for the clarification, I think it's clear to me. 

IMO that this case (with contexts ambiguity) is not about only fairly advanced code. Maybe this is some kind of anti-pattern, but what if we want to react on the cancellation inside of a flow as fast as possible? Of course it will happen during the next `emit(...)` call, but if we need it earlier, we can check `isActive` of the current context. And here some possibility to shoot feet appears with `coroutineContext` instead of `currentCoroutineContext()`:

```kotlin
flow<...> {
        for (i in 1..10) {
            // Some heavy processing.
            // coroutineContext is going to point to a wrong context in the check below.
            if (!currentCoroutineContext().isActive) return@flow
            // Some other part of heavy processing.
            emit(...)
        }
    }
        .flowOn(...)
        .collect()
```

Anyway, it was just a suggestion in the original message of the issue, so it's up to you to decide. I think I can close it.
