### ISSUE TITLE
Convert a flow to a mutable flow?

### ISSUE THREAD

**Issue by premnirmal** [Kotlin/kotlinx.coroutines#3014]
I am trying to keep a mutable shared flow in my class, but when I apply any methods to it, it will be converted to an immutable `Flow<T>`:

``` kotlin
class MyClass : Listener<String> {

       private val source = Source()

       val flow: Flow<String>
          get() = _flow

       // region listener
        override fun onUpdate(value: String?) {
            if (value!= null) {
                // emit object changes to the flow
               // not possible, because the builder operators on the flow below convert it to a `Flow` and it doesn't stay as a `MutableSharedFlow` :(
                _flow.tryEmit(value) 
            }
        }
        // end-region

        @OptIn(ExperimentalCoroutinesApi::class)
        private val _flow by lazy {
            MutableSharedFlow<List<RichContentThumbnail>>().onStart {
                emitAll(
                    flow<List<RichContentThumbnail>> {
                        val initialValue = source.getInitialValue()
                        emit(initialValue)
                    }.flowOn(MyDispatchers.background)
                )
            }.onCompletion { error ->
                // when the flow is cancelled, stop listening to changes
                if (error is CancellationException) {
                    // is was cancelled
                    source.removeListener(this@MyClass)
                }
            }.apply {
                // listen to changes and send them to the flow
                source.addListener(this@MyClass)
            }
        }
```

Is there a way to keep the flow as a `MutableSharedFlow` even after I apply the `onCompletion/onStart` methods to it?

**Comment by dkhalanskyjb** [comment]
Hi! Please use the public Slack or StackOverflow for general questions.

> Is there a way to keep the flow as a MutableSharedFlow even after I apply the `onCompletion`/`onStart` methods to it?

There isn't. `onStart` and `onCompletion` only affect a single subscriber and can't be applied to the `MutableStateFlow` as a whole. Also, it probably doesn't have the behavior that you want.
* The `onStart` callback will be called not once `MutableStateFlow` starts to emit things, but, instead, for each new subscriber.
* Likewise, the `onCompletion` callback would also be called for each subscriber separately. It isn't clear even what it would mean to cancel a `MutableStateFlow`: there is no such operation, and it can't even be completed; it's only possible to cancel a specific subscription.

For your use case, I would suggest the following:
* Don't perform `onCompletion`. Instead, specify a `cancel` operation on `MyClass` and invoke it when you need to. I'm not sure when would the right time for that be—when at least one subscriber cancels? when all subscribers cancel?—it depends on the required logic.
* Don't perform `onStart`. Instead, just `emit` the initial value to it when you create it. Or maybe `MutableStateFlow` would suit your use case better, given that you have the initial value?

**Comment by premnirmal** [comment]
> Don't perform onStart. Instead, just emit the initial value to it when you create it. Or maybe MutableStateFlow would suit your use case better, given that you have the initial value?

But I want to create the initial value on a bg thread, is that possible with a `MutableSharedFlow` without having to invoke the constructor on a bg thread?

**Comment by dkhalanskyjb** [comment]
Do you mean `MutableStateFlow`? `MutableStateFlow` can't be created until the initial value is known, so you'll have to acquire the value beforehand somehow. `MutableSharedFlow` can be created without an initial value, you'll just have to emit one to it later.

**Comment by psteiger** [comment]
> But I want to create the initial value on a bg thread, is that possible with a `MutableSharedFlow` without having to invoke the constructor on a bg thread?

I use State and Shared flows extensively on my personal projects. The common dialect to me seems to be converting all your sources (e.g. Source()) to flows, applying any number of operations you want, and finally using `stateIn/shareIn` for sharing the result. That way you keep all of it declarative-style (cold) until the terminal operator. There's no way to compute the initial value outside the hosting thread of the val though. Think about it: StateFlow requires an initial value at the moment of instantiation. How can one delay the computation of this value if at the mean time one can call `yourFlow.value`? A common pattern when you don't have an initial value at the moment is to use `SharedFlow` (no initial value), or use null or a special "token" object (e.g. `Resource.loading()`) as the initial value.
