### ISSUE TITLE
Usage Question - how to call suspend function from a doOnNext or subscribe handler

### ISSUE THREAD

**Issue by yschimke** [Kotlin/kotlinx.coroutines#302]
Is there a good sample of this?  Basically if I need to call suspend functions in a subscribe block or generally a doOnNext, I'd obviously like to avoid calling runBlocking.

```
flux
      .subscribe({ p ->
        runBlocking {
          outputHandler.showOutput(p.dataUtf8)
        }
      }, { e ->
        runBlocking {
          outputHandler.showError("channel error", e)
        }
      })
```

**Comment by fvasco** [comment]
Can you convert the reactive stream to a Kotlin Channel?

(many helper functions are already present)

**Comment by yschimke** [comment]
My problem here is kind of the reverse.  I have mostly reactive streams code, and I want to call suspend functions easily.

I think I'll make syntactic sugar for

```
Flux.just(1, 2, 3) 
    .flatMap( i -> mono { /* sideEffectHere */ }).then(Mono.just(i)))

```

**Comment by fvasco** [comment]
In my demo I defined something similar

https://github.com/fvasco/reactive-spring/blob/574026fd0a9edb451152601eab8141c8eb7a416a/src/main/kotlin/ReactorUtil.kt#L22

This should avoid some `runBlocking` issues

**Comment by yschimke** [comment]
Yep. Thanks, that is pretty close to what I’d need. Given the breadth of the project reactor API it will be pointless to add helpers for all forms. But I wonder if there is a form that makes it as trivial as possible to write these completely inline. 

Also what is the cost of each new continuation context. Is this or can this be shared within an entire chain of the subscription e.g. through the reactor context?

**Comment by yschimke** [comment]
```
fun <T> Flux<T>.onNext(block: suspend (T) -> Unit): Flux<T> {
  return this.flatMap {
    mono {
      block.invoke(it)
    }.thenMany(Flux.just(it))
  }
}

fun <T> Mono<T>.onNext(block: suspend (T) -> Unit): Mono<T> {
  return this.flatMap {
    mono {
      block.invoke(it)
    }.then(Mono.just(it))
  }
}

fun <T> Flux<T>.onError(block: suspend (Throwable) -> Unit): Flux<T> {
  return this.onErrorResume {
    mono {
      block.invoke(it)
    }.thenMany(Flux.error(it))
  }
}

fun <T> Mono<T>.onError(block: suspend (Throwable) -> Unit): Mono<T> {
  return this.onErrorResume {
    mono {
      block.invoke(it)
    }.then(Mono.error(it))
  }
}
```

**Comment by elizarov** [comment]
@yschimke @fvasco You can contribute those extensions to `kotlinx.coroutines`, so that we have in the next version. PR will be welcome.

**Comment by fvasco** [comment]
Thanks for proposal @elizarov,
I have some concerns about extending the `Flux` class, flux is designed for regular non-suspending code, so having `map` and `suspend mapNotNull` may be confusing.
Switching from `Flux` to a suspending interface -instead- should reduce the cognitive load.

@yschimke, what do you think about it?

**Comment by yschimke** [comment]
That makes sense if you want to build a full suspend aware version of Flux and Mono.  Seems like a maintenance burden.  But would be nice for users, and maybe just a thin wrapper.  

Maybe given how easy kotlin DSLs are and including optional named parameters etc, with a few key methods the API could be quite slim?

Feel free to take the code as public domain if at all useful.  I can't contribute without a lot of legal paperwork first.

**Comment by fvasco** [comment]
> with a few key methods the API could be quite slim?

Any choice in such direction risk to be personal and opinable.

I wrote a simple extension for a demo purpose, however keep it in a public library can lead to many issue like: "please, add Xxx to library, too".
Obviously this can be a way, however I prefer to expose some lightweight converter `flux.toReceiveChannel()`, `channel.toFlux()`, `mono.toDeferred()` and `Deferred.toMono()`.

**Comment by yschimke** [comment]
I guess the issue here is the 

`flatMap(mono { // suspend aware code  })`

form works well, and has both back pressure and doesn't need to block the thread.  But 

`doOnNext(x)`

The most predictable forms x will either be runBlocking (ties up a thread), or async (no back pressure and error handling).  I think we need something to make this simpler otherwise the common pattern will be wrong.
