### ISSUE TITLE
Hello, the kotlin plugin has been updated to version 1.5.31, can the version of the coroutine be synchronized?

### ISSUE THREAD

**Issue by SaltedFish-Extreme** [Kotlin/kotlinx.coroutines#3021]

**Comment by qwwdfsad** [comment]
Hi, `kotlinx.coroutines` version has nothing to do with Kotlin version, it's just a coincidence they both are `1.5.x`

**Comment by SaltedFish-Extreme** [comment]
> Hi, `kotlinx.coroutines` version has nothing to do with Kotlin version, it's just a coincidence they both are `1.5.x`

Ah, but when I import the coroutine dependencies, there are always warnings of inconsistent versions of Kotlin
![image](https://user-images.githubusercontent.com/54784104/141482055-57cf0cbf-7492-4b43-a172-c5e16685e4a4.png)

**Comment by SaltedFish-Extreme** [comment]
> 您好，`kotlinx.coroutines`版本与 Kotlin 版本无关，只是巧合`1.5.x`

Ah, I just removed the coroutine dependency and resynchronized gradle. It seems that kotlin-stdlib comes with the latest version of the coroutine package, so there is no need to import dependencies repeatedly.
