### ISSUE TITLE
1.6.0-RC Changelog: FlowCollector is not fun interface

### ISSUE THREAD

**Issue by hfhbd** [Kotlin/kotlinx.coroutines#3037]
From changelog: 
https://github.com/Kotlin/kotlinx.coroutines/blob/3574c2feca23c3e8a1ad00b5bf92e2bf04d95060/CHANGES.md?plain=1#L37

Linked PR does not affect `FlowCollector`: #2790

**Comment by qwwdfsad** [comment]
Thanks! It seems like an automation issue, I'm looking into it, the PR didn't make it for some reason

**Comment by hfhbd** [comment]
Fixed in 1.6.0-RC3
