### ISSUE TITLE
Dispatchers.IO coroutine is blocked by load on Main

### ISSUE THREAD

**Issue by permiakovsa** [Kotlin/kotlinx.coroutines#3038]
Hello, I'm trying to solve the incident. Some coroutine in IO dispatcher reads data from device, but if main thread got a lot of work to redraw - the IO coroutine will be blocked for the delay. on JVM 11
The device-reading coroutine works in DefaultDispatcher-worker-*

**Comment by dkhalanskyjb** [comment]
See the workaround here: https://github.com/Kotlin/kotlinx.coroutines/issues/2972#issuecomment-971631746

**Comment by permiakovsa** [comment]
also it's for JavaFX coroutines

**Comment by dkhalanskyjb** [comment]
Doesn't matter. The issue and the workaround are the same for any `Dispatchers.Main` implementation.

**Comment by permiakovsa** [comment]
So i need to set the flag "kotlinx.coroutines.main.delay" - where I can set it?

**Comment by dkhalanskyjb** [comment]
It is a system property: https://docs.gradle.org/current/userguide/build_environment.html#sec:gradle_system_properties

Even though the workaround should fix this for you, could you please answer some questions to help us design the library?
* What are you doing in `Dispatchers.IO` while the application is busy with drawing?
* What was the debugging process by which you reached the conclusion that "many redraws → the delay hangs"?

Context: in the latest release candidate, we've made it so `Dispatchers.Main` is used to execute `delay`, if possible, so we're interested in which problems this may cause, and how difficult it is to find the root of these problems.

**Comment by permiakovsa** [comment]
No the woraround doesn't work for me. even using 1.6.0-RC lib version
I have a JavaFx application, which reads data from device (early with a java thread executor, now with CorotineScope(Dispatchers.IO). I'm logging the reading interval (in my case 10 ms), and I discover a huge lag (100-200 ms) caused by JavaFx Thread Load

**Comment by dkhalanskyjb** [comment]
> No the workaround doesn't work for me

What exactly are you doing?
`System.setProperty("kotlinx.coroutines.main.delay", "false")` at the start of the application should work.

> reads data from device

I see, thanks! What is the purpose of the `delay` there?

**Comment by permiakovsa** [comment]
```
object Main {
    @JvmStatic
    fun main(args: Array<String>) {
        System.setProperty("kotlinx.coroutines.main.delay", "false")
        FeatureProcedureView.main(args)
    }
}
```
I start JavaFX app this way, also add setProperty to the di objects. Anyway I got the same behavior.

I don't use `delay`, the delay comes from blocking method of device reading library, that uses JNI methods

**Comment by dkhalanskyjb** [comment]
Oh. In this case, maybe this issue is actually unrelated to https://github.com/Kotlin/kotlinx.coroutines/issues/2972.

A question I probably should've asked first: did the issue start happening after updating `1.6.0-RC` or did it happen before as well?

**Comment by permiakovsa** [comment]
yes, first I discovered it using  'kotlinx-coroutines-javafx', version: '1.5.2'

**Comment by dkhalanskyjb** [comment]
Ok, then the workaround I suggested definitely won't work.

Did you ever see the good behavior in this case, or was the issue always present?
Also, it may be difficult to diagnose without a reproducing project—could you provide the source code of a project where this happens?

**Comment by permiakovsa** [comment]
My project is NDA, but  I will prepare a project that will reproduce this behavior, but it requires custom HID device, not keyboard or mouse. Need some time to make a proper mock

**Comment by qwwdfsad** [comment]
Closing as obsolete
