### ISSUE TITLE
Where is library build for target mingw_x86 for 1.6.0-RC?

### ISSUE THREAD

**Issue by caffeine-mgn** [Kotlin/kotlinx.coroutines#3052]
build for target `linux_arm64` missing to

**Comment by qwwdfsad** [comment]
We do not [yet] publish artifacts for these targets

**Comment by Prototik** [comment]
@qwwdfsad also please note the missing darwin variants of `kotlinx-coroutines-test` library in `1.6.0-RC`.

**Comment by Reedyuk** [comment]
Im getting the same for:
```
Could not find org.jetbrains.kotlinx:kotlinx-coroutines-test-iossimulatorarm64:1.6.0-RC
```

**Comment by qwwdfsad** [comment]
All these targets have been supported since 1.6.0:
