### ISSUE TITLE
kotlinx-coroutines-debug depends on android-gradle-aspectj but android-gradle-aspectj is abandoned

### ISSUE THREAD

**Issue by jmarks213** [Kotlin/kotlinx.coroutines#3060]
I went to reach for kotlinx-coroutines-debug to work through an issue I am having but it throws the below error as noted in the readme.  The solution per the readme is to add the android-gradle-aspectj plugin to the project.  When you attempt to add android-gradle-aspectj it fails to resolve as the project did not migrate away from jcenter.

Is anyone able to host the android-gradle-aspectj plugin somewhere?

> Debug agent and Android
> 
> Unfortunately, Android runtime does not support Instrument API necessary for kotlinx-coroutines-debug to function, triggering java.lang.NoClassDefFoundError: Failed resolution of: Ljava/lang/management/ManagementFactory;.
> 
> Nevertheless, it will be possible to support debug agent on Android as soon as GradleAspectJ-Android will support android-gradle 3.3

**Comment by qwwdfsad** [comment]
Hi,

>The solution per the readme is to add the android-gradle-aspectj plugin to the project

This is not what the documentation says. It says 

>Nevertheless, **it will be possible to support debug agent** on Android as soon as [GradleAspectJ-Android](https://github.com/Archinamon/android-gradle-aspectj)  will support android-gradle 3.3 

Yet it is not supported and we gave up on this plan. Thanks for pointing it out, I will adjust the doc accordingly.
We are not going to support coroutine debugger on Android, it will be a built-in tool of Android Studio itself in one of the upcoming versions of AS.

**Comment by jonavos** [comment]
> It will be a built-in tool of Android Studio itself in one of the upcoming versions of AS.

Did this ever happen?

I'm currently running AS 2024.2.2 for instance and I don't believe I can debug coroutines.
