### ISSUE TITLE
Gradle Down

### ISSUE THREAD

**Issue by michaelfretz** [Kotlin/kotlinx.coroutines#307]
I added the library to gradle as described but it seems to be down.

It links to:
https://dl.google.com/dl/android/maven2/org/jetbrains/kotlinx/kotlinx-coroutines-core/0.22.5/kotlinx-coroutines-core-0.22.5.pom

But there I got first a 502 and then a 404

Edit: can be fixed when getting it from maven

**Comment by elizarov** [comment]
You seem to be trying to download it from Google's repository and it is not there. You should add `jcenter()` or `mavenCentral()` repo:

```
repositories {
    jcenter()
}
```

**Comment by elizarov** [comment]
It might have been caused by the downtime of JCenter.
