### ISSUE TITLE
BackendException in 1.6.0-RC2

### ISSUE THREAD

**Issue by MinnDevelopment** [Kotlin/kotlinx.coroutines#3080]
When trying to compile this code I get a backend exception (gist below):

```kt
import dev.minn.jda.ktx.onCommand
import net.dv8tion.jda.api.JDA

fun foo(jda: JDA) {
    jda.onCommand("test") {

    }
}
```

Where `onCommand` is given by:

`JDA#onCommand`: https://github.com/MinnDevelopment/jda-ktx/blob/64e84291b94630585f5d379d02d39fe7558a2a00/src/main/kotlin/dev/minn/jda/ktx/events.kt#L107-L110

`JDA#listener`: https://github.com/MinnDevelopment/jda-ktx/blob/64e84291b94630585f5d379d02d39fe7558a2a00/src/main/kotlin/dev/minn/jda/ktx/events.kt#L50-L52

`CoroutineEventManager#listener`: https://github.com/MinnDevelopment/jda-ktx/blob/64e84291b94630585f5d379d02d39fe7558a2a00/src/main/kotlin/dev/minn/jda/ktx/CoroutineEventManager.kt#L104-L118

Full error:

https://gist.github.com/MinnDevelopment/53f277a612a745b05000993c3640653d

When I call `jda.listener` or `(jda.eventManager as CoroutineEventManager).listener` directly, it doesn't crash. This seems to be caused by the 3 nested inlines.

These are my compiler settings in gradle:

```kt
plugins {
    idea
    application
    kotlin("jvm") version "1.6.0"
}

...

configure<JavaPluginExtension> {
    sourceCompatibility = JavaVersion.VERSION_1_8
    targetCompatibility = JavaVersion.VERSION_1_8
}

tasks {
    withType<KotlinCompile> {
        kotlinOptions.jvmTarget = "1.8"
        kotlinOptions.freeCompilerArgs = listOf(
            "-Xjvm-default=all",
            "-Xlambdas=indy"
        )
    }
}
```

**Comment by qwwdfsad** [comment]
This is a compiler issue, reported it here: https://youtrack.jetbrains.com/issue/KT-50213

Thanks for the detailed explanation!
