### ISSUE TITLE
Cannot access class 'kotlinx.coroutines.CoroutineScope'. 

### ISSUE THREAD

**Issue by Oliver-Zimmerman** [Kotlin/kotlinx.coroutines#3083]
`val composableScope = rememberCoroutineScope()`

The import is included properly but I am still getting the following error:
Cannot access class 'kotlinx.coroutines.CoroutineScope'. Check your module classpath for missing or conflicting dependencies.

Compose version: 1.0.5
KotlinCompilerVersion: 1.5.31
Android Studio Version: 
Android Studio Arctic Fox | 2020.3.1 Patch 3
Build #AI-203.7717.56.2031.7784292, built on October 1, 2021

Seems to be similar as described here:
https://stackoverflow.com/questions/70328832/cannot-access-remembercoroutinescope-with-jetpack-compose

**Comment by qwwdfsad** [comment]
It doesn't seem to have anything with the coroutines library itself, and unfortunately, we cannot help you with the lack of reproducer or analysis presented.

I would suggest using SO or slack channel for such general questions
