### ISSUE TITLE
How to catch this exception?

### ISSUE THREAD

**Issue by venkatperi** [Kotlin/kotlinx.coroutines#309]
I can't figure out how to catch the exception resulting from `completeExceptionally(...)` no matter where I place the `try/catch`. The following code throws in spite of the try/catch:

```
try {
        val job = CompletableDeferred<Int>().apply {
          completeExceptionally(Error("test"))
        }
        runBlocking {
          job.await()
        }
      } catch (e: Exception) {
        println(e)  //never gets here
      }
```

**Comment by qwwdfsad** [comment]
It's because you're throwing `Error`, but trying to catch `Exception`. `Error` is not the subclass of `Exception`, but its supertype.
Try to either catch `Error` (or `Throwable`) or complete job with subclass of `Exception`.

**Comment by venkatperi** [comment]
Well, that was dumb. Thanks. Closing.
