### ISSUE TITLE
Methods with timeout should not crash on negative time

### ISSUE THREAD

**Issue by elizarov** [Kotlin/kotlinx.coroutines#310]
Methods like `delay`, `withTimeout`, `onTimeout` all `require(time >= 0)`. This leads to error-prone time-based code. See gist for #306 for example: https://gist.github.com/elizarov/34150213209158d0dce0db62d9c0a20f 

This code in this gist happens to work if this line is removed, but it would still wrong without this this line (it will subtly main sometimes):

```
if (remainingNanos <= 0) break // this window is over
```

We should remove `require(time >= 0)` from all time-based methods. They should assume that they should not delay (or assume imediate timeout) when negative time is passed.

**Comment by qwwdfsad** [comment]
`CompletableFuture` immediately throws `TimeoutException` if time is not positive.
Rx, Rx2, and Reactor throw TimeoutException if the timeout is not positive, though timeout task is properly scheduled. Negative delay treated as no delay everywhere, but with `Delay` task scheduling
