### ISSUE TITLE
Problem with delay with kotlinx-coroutines-javafx 

### ISSUE THREAD

**Issue by NkD** [Kotlin/kotlinx.coroutines#3106]
**versions**:
- java - 17.0.1
- javafx - 17.0.1
- kotlin-stdlib-jdk8 - 1.6.10
- kotlinx-coroutines-core - 1.6.0
- kotlinx-coroutines-javafx - 1.6.0

**smallest example of bug**
```kotlin
import kotlinx.coroutines.CoroutineScope
import kotlinx.coroutines.Dispatchers
import kotlinx.coroutines.delay
import kotlinx.coroutines.launch
import kotlinx.coroutines.withContext

fun main() {
    val jobCoroutineScope = CoroutineScope(Dispatchers.IO)
    println("started")
    for (job in 1..3) {
        jobCoroutineScope.launch {
            println("job[$job] started")
            for (step in 1..10) {
                  delay(100)
            }
            println("job[$job] ended")
        }
    }
    Thread.sleep(2000)
    println("ended")
}
```
**BUG:** Some jobs stay blocked forever in `delay` function. 

I've been trying to figure out what the problem is. And it is because the delay is redirected to `kotlinx.coroutines.javafx.JavaFxDispatcher#schedule`, where the delay is implemented as a `TimeLine` for JavaFx. However, this Timeline is started outside of the `JavaFX Thread` and this will lead to unexpected results.

**Workarounds:**
- wrap delay as `withContext(Dispatchers.Main) { delay(100) }` - Dispatchers.Main is JavaFx thread in this case.
- add SysProp `kotlinx.coroutines.main.delay=false` - switch off redirecting to JavaFxDispatcher (Dispatchers.Main)
- remove `kotlinx-coroutines-javafx` dependency (not possible for me)

**Comment by miikeat** [comment]
This bug caused our tests to get stuck only on Jenkins!
Thanks for the Workarounds.

We just needed to add this line to our ```build.gradle.kts``` to get them working again:
```
tasks {
  test {
    systemProperty("kotlinx.coroutines.main.delay", "false")
  }
}
```
