### ISSUE TITLE
Source-incompatibility during #3047: "Make FlowCollector fun interface, remove redundant extensions"

### ISSUE THREAD

**Issue by qwwdfsad** [Kotlin/kotlinx.coroutines#3107]
In #3047, the `Flow.collect(action)` extension was removed in the favour of the freshly-added SAM conversion.

The extension was `inline`, so the change is binary compatible and previously compiled clients continue working without any issues, but such change breaks a pattern with using functional type as a non-inline argument.

The following code no longer compiles:
```
val action: suspend (value: Int) -> Unit = { println(it) }
flowOf(1, 2, 3).collect(action)
```

with the following workaround:

```
flowOf(1, 2, 3).collect { action(it) }
```

This incompatibility was discovered after the stable release 1.6.0. Our integration and user-project testing along with RC releases haven't revealed the issue, so the scope of the impact stays unclear.

We're aiming to fix it in the following patch release, feel free to comment on the issue if the impact prevents you from upgrading in order for us to be aware of the urgency of the fix

**Comment by elizarov** [comment]
https://youtrack.jetbrains.com/issue/KT-50477

**Comment by gmk57** [comment]
This change broke our small helper function for Android:
```
fun <T> StateFlow<T>.observe(lifecycleOwner: LifecycleOwner, action: suspend (T) -> Unit) =
    lifecycleOwner.lifecycleScope.launchWhenStarted { collect(action) }
```
After changing `action` type to `FlowCollector<T>` everything seems to work again.

**Comment by mhernand40** [comment]
FWIW, doesn't this also break the following:
```Kotlin
flow
    .onEach { … }
    .collect()
```
