### ISSUE TITLE
asStateFlow vs simple type cast documentation

### ISSUE THREAD

**Issue by ggajews** [Kotlin/kotlinx.coroutines#3114]
Hi guys.
Kotlin [guide](https://kotlin.github.io/kotlinx.coroutines/kotlinx-coroutines-core/kotlinx.coroutines.flow/-state-flow/) recommends using `asStateFlow` to return read only StateFlow
```
private val _counter = MutableStateFlow(0) // private mutable state flow
val counter = _counter.asStateFlow() // publicly exposed as read-only state flow
```
Android [guide](https://developer.android.com/kotlin/flow/stateflow-and-sharedflow) is using simple type cast though:
```
// Backing property to avoid state updates from other classes
private val _uiState = MutableStateFlow(LatestNewsUiState.Success(emptyList()))
// The UI collects from this StateFlow to get its state updates
val uiState: StateFlow<LatestNewsUiState> = _uiState
```

I cannot find a good answer in the documentation what are the differences between these two approaches? What is added value for using the `asStateFlow()` ?

**Comment by fvasco** [comment]
In your example `uiState is MutableStateFlow`, instead a `counter !is MutableStateFlow`
See also #1973

**Comment by ggajews** [comment]
ok so it's "safer" to use `asStateFlow()`, I'll create an issue in Android repo to align the sample
