### ISSUE TITLE
[QUESTION] parallel processing like LMAX disruptor

### ISSUE THREAD

**Issue by revintec** [Kotlin/kotlinx.coroutines#3115]
imagine that we have a data processing pipeline, consists of 3 steps
```kotlin
val finalValue=fn3(fn2(fn1(originalValue)))
```
however `fn2` is cpu intensive, thus we want to parallelize it
```
                    /-> fn2(on thread1) --\
fn1(originalValue) -+-> fn2(on thread2) --+-> fn3(...) -->
                    \-> fn2(on thread3) --/
```
which is the best approach?

I can think of two approaches:
use two channels to fan-out and fan-in, but this doesn't preserve the source data(`originalValue`) order, so we have to buffer, reorder, potentially block to provide back pressure... too complex

another approach is to use LMAX disruptor, a famous java library: https://lmax-exchange.github.io/disruptor/
but this adds another dependency and not kotlin friendly(similarly we can use java `stream`, we also have to consider how to integrate into `stream`'s rather complex internal apis).
most importantly, disruptor excels in low latency high throughput, it adds code/config complexity for this, but not all project need them all. I'm not concerned too much about latency, as I may later refactor the code to distribute `fn2` not only on cpu cores(threads) but also on clusters(different machines). custom data processing pipeline with different performance targets, may not be suitable on spark/flink

**Comment by fvasco** [comment]
Please consider to send your question on a proper channel, see https://kotlinlang.org/community/

**Comment by revintec** [comment]
sorry about that, moved to here https://discuss.kotlinlang.org/t/question-parallel-processing-like-lmax-disruptor/23820
