### ISSUE TITLE
Switching to Blocked DIspatcher Results in Infinite Loop 

### ISSUE THREAD

**Issue by NWuensche** [Kotlin/kotlinx.coroutines#3119]
See the following code

```kotlin
fun main() {
    val t = ForkJoinPool(1).asCoroutineDispatcher()
    runBlocking(t) { //switches to t
        runBlocking { //blocks t
            withContext(Dispatchers.Default) {
                withContext(t) { //Cannot use t, thus infinite loop
                    println("I am here")
                }
            }
        }
    }
}
```

As `t` only contains one Thread, the innermost `withContext` cannot switch to `t`, as this thread is blocked by the second `runBlocking`. Hence, the code runs forever and never prints "I am here" nor exits. Analogously, this happens on Android when replacing `t` with `Dispatcher,Main`. I assume that this always happens when all `x` Threads of a Dispatcher are blocked by `x` `runBlocking`-statements which are interlaced 

Note that adding a second thread to `t` leads to printing "I am here" and exiting the program afterwards.

I would assume that it would be better to throw an exception in the case that all threads of a Dispatcher are blocked, saying that `withContext` cannot switch to a Dispatcher with only blocked threads.

**Comment by fvasco** [comment]
`runBlocking` function should not be used from a coroutine, it has been [already documented](https://kotlin.github.io/kotlinx.coroutines/kotlinx-coroutines-core/kotlinx.coroutines/run-blocking.html?query=expect%20fun%20%3CT%3E%20runBlocking(context:%20CoroutineContext%20=%20EmptyCoroutineContext,%20block:%20suspend%20CoroutineScope.()%20-%3E%20T):%20T).

**Comment by NWuensche** [comment]
I only used the outer `runBlocking` + `ForkJoinPool` to make this code framework-independent.  However, on Android, one can get the same result with only one runBlocking, as the Main-Dispatcher consists only of one Thread:

```kotlin
runBlocking { //blocks MainDispatcher
  withContext(Dispatchers.Default) {
    withContext(Dispatchers.Main) { //Cannot use Main-Dispatcher, thus infinite loop
      println("I am here")
    }
  }
}
```

**Comment by qwwdfsad** [comment]
This is expected behaviour -- `runBlocking`, as the documentation and the name suggest, **blocks** the current thread until it completes. If you dispatch anything to this thread (whether using regular Java API or the corresponding dispatcher), it has to wait until `runBlocking` completes. 
If `runBlocking` completion awaits for such dispatched task -- it's a classic deadlock

**Comment by funyin** [comment]
Somehow I did this in a test and now when I try to debug my actual code I get the test data within the loop.
Even after restarting my laptop. Any suggesting on how to kill this guy?
