### ISSUE TITLE
Android example app need to be split into template and result

### ISSUE THREAD

**Issue by Dmitry-Borodin** [Kotlin/kotlinx.coroutines#314]
What was expected to show there?

**Comment by elizarov** [comment]
It is not supposed to show anything by itself. It is a template for [UI guide](https://github.com/Kotlin/kotlinx.coroutines/blob/master/ui/coroutines-guide-ui.md). It looks that we shall have a copy of example app for all the steps in the guide. Maybe put it into the separate repo.
