### ISSUE TITLE
Parallel actors with partition

### ISSUE THREAD

**Issue by j-min5u** [Kotlin/kotlinx.coroutines#3145]
Hi I'm using kotlin on server-side and actors seem useful for race-conditions but, because it consumes and processes its mailbox sequentially, I'm worried of possible bottleneck (esp. when db or external connections are performed)
my suggestion is to implement concurrent actors managed by a common channel with partitions by adding a partitionedActor fun to the actor api with an additional partitions parameter and a key type parameter
ex)
```kotlin
sealed class Command()
fun CoroutineScope.createActor = partitionedActor<Command, String>(partitions = 3) {
    for(cmd in channel) {
        // do something..

    }
}
```
along with a PartitionedSendChannel<in E, K> interface (for the send fun with the partition key)
```kotlin
public suspend fun send(element: E, key: K?)
```
under the hood, a  partitionedActor with n partitions could be n+1 actors with one routing actor and n actors that process each partition
partition assignment could be done via key?.hashCode % n ?: ( random || load balanced if possible )
I am open to creating a PR if this suggestion is considered.

**Comment by qwwdfsad** [comment]
Hi, we currently have neither resources nor the goal to develop actors in their current state.

They may be reworked in the future (#87), but for now actors are marked as `@ObsoleteCoroutinesApi` and maintained on a best-effort basis
