### ISSUE TITLE
Allow early returns in `Flow.collect`

### ISSUE THREAD

**Issue by Paradyx** [Kotlin/kotlinx.coroutines#3152]
I feel like there should be a way of early returning from a `Flow.collect` without using exceptions or side-effects. This would be exceptionally useful for `Flow<Result<T, E>>.collect()` or `Flow<Either<L, R>>.collect()`. 

Side-note: Unfortunately the native Kotlin [Results](https://kotlinlang.org/api/latest/jvm/stdlib/kotlin/-result/) only allow `Throwable`, which makes it hard to argue in favour of this feature. 

Let me give you an example: 

```kotlin
val data: Flow<Result<T, E>> = fetchAllTheData()
val result: Result<Unit, E> = data.collectWhileSuccessful { d : Result<T, E> ->
    d.andThen { sendAway(data) }
}
```
I got a couple of workarounds to work, which all feel very hacky to me. I'm getting all of this wrong and there is an idiomatic way of returning early from a `collect`.

Please let me know if you have any questions. At least I hope we can have a little discussion about this and people with similar problems can find an idiomatic solution here. 

### Solution with Throwable
The unchecked cast feels pretty unnecessary and the limitations to `Throwable`s feels rather arbitrary.
 
```kotlin
suspend inline fun <T, E> Flow<Result<T, E>>.collectWhileSuccessful(crossinline collector: (Result<T, E>) -> Result<Unit, E>): Result<Unit, E> {
    try {
        this.collect {
            collector(it).onFailure { error -> throw ErrorInFlowException(error) }
        }
        return Ok(Unit)
    } catch (e: ErrorInFlowException) {
        @Suppress("UNCHECKED_CAST")
        return Err(e.error as E)
    }
}
```

### Solution with takeWhile and side-effects
```kotlin
suspend fun <T, E> Flow<Result<T, E>>.collectWhileSuccessful(collector: (Result<T, E>) -> Result<Unit, E>): Result<Unit, E> {
    var finalResult: Result<Unit, E> = Ok(Unit)
    this.map(collector)
        .takeWhile { result ->
            result.fold(
                success = { true },
                failure = {
                    finalResult = Err(it)
                    false
                }
            )
        }.collect()
    return finalResult
}
```

**Comment by qwwdfsad** [comment]
Could you please elaborate on what exactly do you consider a side-effect? A cancelled source flow?

Even taking aside language limitations, the current behaviour is intentional -- it's impossible to "just" return from the flow collection. `Flow` is not a `List` that can be abandoned at any moment. It is an asynchronous stream of data that may or may not be backed by a computation, a coroutine, or an infinite computation.

All aborting operators (`takeWhile`, `take`, `first`, etc.) explicitly cancel the original flow to prevent outgoing computation (potentially stateful and costly!) to be left uncancelled.

**Comment by Paradyx** [comment]
I understand the limitation of propagating the cancellation upstream. However, the given utility functions (`takeWhile`, etc) don't allow to propagate the reason for the abort downstream except through exceptions and side-effects. 

What do I mean with side-effects? A variable outside of the `takeWhile` body is changed and in complex projects it is hard to check weather the reason for the abort is handled correctly. 
```kotlin
val naturalNumbers: Flow<Int> = foo()
var reason: String? = null
naturalNumbers.takeWhile {
    if (it > 500) {
        reason = "limit exceeded"
        false
    } else true
}.collect{}
```

With exceptions there are the same problems. Future me might forget to catch the exception correctly and 
```kotlin
val naturalNumbers: Flow<Int> = foo()
naturalNumbers.collect{
    if (it > 500) throw Exception("limit exceeded") else {}
}
```

**Comment by elizarov** [comment]
Feel free to vote for [KT-33851](https://youtrack.jetbrains.com/issue/KT-33851) iterator-less for-statement operator convention for push-based data streams. If it gets adopted in Kotlin, you'll be able to use a regular `for` loop to collect a flow. That'll give you all your usual means to break from the loop in any way you'd like to. Even an early return will become possible: 

```
// returns some result
suspend fun takeNumbers(naturalNumbers: Flow<Int>): String {
    // collect a flow with a for loop
    for (it in naturalNumbers) {
        if (it > 500) {
            return "limit exceeded" // early return from a loop
        }
     }
     return "OK"
}
```
