### ISSUE TITLE
is `kotlin-tooling-metadata.json` needed by release APK?

### ISSUE THREAD

**Issue by iamriajul** [Kotlin/kotlinx.coroutines#3158]
I've noticed that the `kotlin-tooling-metadata.json` file is being shipped in release APK.

Is this okay? or should I exclude it from PackagingOptions?

Thanks.

**Comment by dsavvinov** [comment]
Hello!
`kotlin-tooling-metadata.json` contains short summary of utility information about the project (no user-strings, only stuff like Kotlin version), which might be used in future to help various tools around Kotlin, should the project be publicly published. 

If it gets into your way, feel free to exclude it now -- nothing should break.
