### ISSUE TITLE
shared flow collectLatest not working as expected

### ISSUE THREAD

**Issue by Manideepkota0708** [Kotlin/kotlinx.coroutines#3162]
sample 1: 
```
fun main() = runBlocking<Unit> {
    val mutableSharedFlow = MutableSharedFlow<String>()
    val sharedFlow: SharedFlow<String> = mutableSharedFlow

    launch {
        sharedFlow.collect {
            println("launch1: $it")
        }
    }

    launch {
        mutableSharedFlow.emit("ONE")
        mutableSharedFlow.emit("TWO")
    }

    launch {
        sharedFlow.collectLatest {
            println("launch2: $it")
        }
    }
}
```
output : 
launch1: ONE
launch1: TWO
launch2: TWO

--------------------------------------------------------------
sample 2: 
```
fun main() = runBlocking<Unit> {
    val mutableSharedFlow = MutableSharedFlow<String>()
    val sharedFlow: SharedFlow<String> = mutableSharedFlow

    launch {
        sharedFlow.collectLatest {
            println("launch1: $it")
        }
    }

    launch {
        mutableSharedFlow.emit("ONE")
        mutableSharedFlow.emit("TWO")
    }

    launch {
        sharedFlow.collect {
            println("launch2: $it")
        }
    }

}
```
output:(nothing)

-------------------------------------------------------------------------------
sample 3:

```
fun main() = runBlocking<Unit> {
    val mutableSharedFlow = MutableSharedFlow<String>()
    val sharedFlow: SharedFlow<String> = mutableSharedFlow

    launch {
        sharedFlow.collect {
            println("launch1: $it")
        }
    }

    launch {
        mutableSharedFlow.emit("ONE")
        mutableSharedFlow.emit("TWO")
    }

    launch {
        sharedFlow.collect {
            println("launch2: $it")
        }
    }

}
```

output: (i didn't  understand why this is the order )
launch2: ONE
launch1: ONE
launch1: TWO
launch2: TWO

**Comment by LouisCAD** [comment]
Aren't the 3 "samples" all the same? 🤔

**Comment by Manideepkota0708** [comment]
> Aren't the 3 "samples" all the same? 🤔

output is different, I have printed output either.

**Comment by LouisCAD** [comment]
But why copy exactly the same code 3 times? This is just adding noise, and decreases the likelihood that people will try to understand the issue you have.

This, plus referencing this issue in other unrelated issues is not the best way to attract the attention you're looking for.

For this issue, I suggest that you make a new one that clearly shows the expected output and the actual output, without duplicating code unnecessarily, and maybe by being thorough about this, you'll find out, before hitting the submit button, whether it's an actual issue in kotlinx.coroutines, or if your understanding was incomplete and improved in the process.

Personally speaking, it happened to me a few times that I was writing an issue, and in the process, realized my mistake or how I was having incorrect expectations.

**Comment by Manideepkota0708** [comment]
each sample is different, 

- sample1: launch1 contains **collect**, launch2 contains **collect latest**
- sample2: launch1 contains **collectLatest**, launch2 contains **collect**
- sample3: launch1 and launch2 contains **collect**

for both sample1 and sample2, I expected the same output which didn't happen.
with little effort, I was able to understand sample 1 and sample 3

can you explain why it doesn't print anything in sample2? @LouisCAD

**Comment by Manideepkota0708** [comment]
created a new one https://github.com/Kotlin/kotlinx.coroutines/issues/3188 @LouisCAD

**Comment by BarryFruitman** [comment]
@Manideepkota0708 It sucks when someone doesn't read your question and railroads your thread. 😢

**Comment by Manideepkota0708** [comment]
I even created a new one #3188, he has given an explanation but didn't get it what he was saying. Just left it @BarryFruitman
