### ISSUE TITLE
Out of memory in test with an active ticker channel

### ISSUE THREAD

**Issue by lukasz-kalnik-gcx** [Kotlin/kotlinx.coroutines#3166]
I have a presenter with injected dispatcher, which performs a task periodically based on a `ticker` Channel:

```
import kotlinx.coroutines.channels.ticker

class Presenter(
    // other dependencies...
    coroutineContext: CoroutineContext = Dispatchers.Default
) {

    val scope = CoroutineScope(coroutineContext)
    
    init {
        scope.launch {
            val tickerChannel = ticker(delayMillis = 30_000L, initialDelayMillis = 0L, coroutineContext)
            for (ticker in tickerChannel) { requestState() }
        }
    }
}
```

In the test I inject an `UnconfinedTestDispatcher` and use `runTest` but the test doesn't fail with unfinished coroutines. It shows a `java.lang.OutOfMemoryError: Java heap space` after some time:

```
class PresenterTest {

    val testScope = TestScope(UnconfinedTestDispatcher())

    @Test
    fun `test requesting state`() = testScope.runTest {
        val presenter = Presenter(
            // other mocked dependencies...
            testScope.coroutineContext
        )
        
        // verify some behavior of the mocked dependencies 
    }
}
```

JUnit Jupiter 5.7.2
Coroutines 1.6.0
Kotlin 1.6.10

**Comment by qwwdfsad** [comment]
Could you please post self-contained `Presenter` source? Consuming from a channel is prohibited in non-suspending contexts, and `Presenter` init block is non-suspending context

**Comment by qwwdfsad** [comment]
From what I can say now -- `tickerChannel` never completes, so if your `requestState` creates memory pressure, then it eventually will lead to OOM

**Comment by lukasz-kalnik-gcx** [comment]
> Could you please post a self-contained `Presenter` source? Consuming from a channel is prohibited in non-suspending contexts, and `Presenter` init block is non-suspending context

Sorry, I forgot to wrap consuming from the ticker channel in `CoroutineScope.launch`. I fixed it now in my example.

**Comment by lukasz-kalnik-gcx** [comment]
> From what I can say now -- `tickerChannel` never completes, so if your `requestState` creates memory pressure, then it eventually will lead to OOM

Shouldn't `runTest` detect though that there is a non-canceled coroutine at the end of the test and just fail the test?

**Comment by lukasz-kalnik-gcx** [comment]
More background: the example is obviously simplified. In the real presenter we use a custom `CoroutineScope` attached to presenter lifecycle callbacks. It holds a `Job` reference and cancels the `Job` when presenter is destroyed.

What I did wrong in my test is I forgot to call `presenter.onDestroy()` at the end of the test. With this the `ticker` coroutine gets canceled.
I was wondering though if `runTest` shouldn't detect the "hanging" coroutine at the end of the test. Or do I understand it wrong?

**Comment by lukasz-kalnik-gcx** [comment]
Yes, I tried `ticker(context = scope.coroutineContext)` but it still didn't get canceled.
Thank you for your fast and helpful responses, I appreciate them very much!

**Comment by lukasz-kalnik-gcx** [comment]
BTW is there an alternative to `ticker()` if they are obsolete?
