### ISSUE TITLE
Proposal: introduce EndlessFlow and endlessFlow

### ISSUE THREAD

**Issue by LouisCAD** [Kotlin/kotlinx.coroutines#3169]
Hello,

After writing `awaitCancellation()` many times to return `Nothing` while collecting an infinite `Flow` that only cancellation can stop, I've been thinking that it'd be nice to have an `EndlessFlow` type that `StateFlow` and `SharedFlow` would implement.

`EndlessFlow` could also be returned by an `endlessFlow { … }` builder, whose lambda would have to return `Nothing`, ensuring the `Flow` never completes.

That would allow us to communicate whether a `Flow` is infinite or not through the API.

It could work in tandem with some operator overloads, where `transform` and `transformLatest` would return `EndlessFlow` when their lambda evaluate to `Nothing` for example.

Do you think it could be considered? Maybe there are other plans to tackle this lack of type explictness through changes in Kotlin itself?

**Comment by dkhalanskyjb** [comment]
> That would allow us to communicate whether a `Flow` is infinite or not through the API.

This encompasses two guarantees:
* "I guarantee that this Flow is finite". This is a guarantee that can't possibly be encoded, ever, and it feels like the more useful of the two.
* "I guarantee that this (Endless)Flow is infinite". We can do that, but is it actually useful?

**Comment by elizarov** [comment]
That's really hard to thread through our existing Kotlin type system. There are two solutions, both bad. Either there is an explosion of overloads (all `filter`, `map`, etc) or there are additional type parameters to all of those functions designed to track this aspect of the flow. Contracts might provide a clearer solution. I've recorder this contracts-related use-cases here https://youtrack.jetbrains.com/issue/KT-51071

**Comment by qwwdfsad** [comment]
That basically sums that up: we do not have an option to provide such flows in a way that is both sound (e.g. ensures that flow is actually infinite) and useful (the information about its infiniteness is not lost after the very first operator applied)

**Comment by LouisCAD** [comment]
@dkhalanskyjb The use case is having all the relevant `Flow` operators return `Nothing` in the right conditions, which can then allow two things:

The first thing is getting static analysis about unreachable code.

The second is implementing functions of type `Nothing` without having to recourse to `awaitCancellation()`, which also prevents you from knowing that the given `Flow` went from infinite to finite or unknown because of other code changes.
The use case for suspending functions that return `Nothing` is communicating at the function signature level that it is designed to run until it gets cancelled, for example, displaying some piece of information in a user interface, until some state changes.
