### ISSUE TITLE
runTest with custom CoroutineExceptionHandler still throws an exception

### ISSUE THREAD

**Issue by lukasz-kalnik-gcx** [Kotlin/kotlinx.coroutines#3171]
I have a suspending function which should throw an exception under certain conditions.

```
class UseCase(val bleState: Any?) {
    
    suspend fun execute() {
        if (bleState == null) throw IllegalStateException()
    }
}
```

The test with the old coroutines test API looked like this:

```
@Test
fun `when no gateway from scanning present then throw`() {
    val useCase = UseCase(null)

    assertThatIllegalStateException().isThrownBy { 
        runBlocking { 
            useCase.execute() 
        } 
    }
}
```

According to the [migration guide](https://github.com/Kotlin/kotlinx.coroutines/blob/master/kotlinx-coroutines-test/MIGRATION.md#remove-usages-of-testcoroutineexceptionhandler-and-testcoroutinescopeuncaughtexceptions), for coroutines-test 1.6.0 it should be changed to something like this:

```
    @BeforeTest
    fun setUp() {
        Dispatchers.setMain(StandardTestDispatcher())
    }

    val exceptions = mutableListOf<Throwable>()
    val customCaptor = CoroutineExceptionHandler { _, throwable ->
        exceptions.add(throwable)
    }

    @Test
    fun `when no gateway from scanning present then throw`() = runTest {
        val useCase = UseCase(null)

        launch(customCaptor) {
            useCase.execute()
        }
        advanceUntilIdle()

        assertThat(exceptions).hasSize(1)
            .first().isInstanceOf(IllegalStateException::class.java)
    }
```

However this test throws the very exception which is supposed to be caught by `customCaptor` and fails.

**Comment by lukasz-kalnik-gcx** [comment]
After reading the [documentation](https://kotlinlang.org/docs/exception-handling.html#coroutineexceptionhandler) on CoroutineExceptionHandler, it looks like the handler can only change the default behavior of printing the exception, but cannot recover from it.

So it looks like the [example](https://github.com/Kotlin/kotlinx.coroutines/blob/master/kotlinx-coroutines-test/MIGRATION.md#remove-usages-of-testcoroutineexceptionhandler-and-testcoroutinescopeuncaughtexceptions) in the migration guide has no chance to work.
The exception will anyway be thrown and will fail the test.

**Comment by lukasz-kalnik-gcx** [comment]
Just wrapping the `runTest` block in a `try ... catch` block works, but it seems weird:

```
    @Test
    fun `when no gateway from scanning present then throw`() {
        try {
            runTest {
                useCase = UseCase(null)

                useCase.execute(Params())
                advanceUntilIdle()
            }
        } catch (exception: IllegalStateException) {
            assertThat(exception).hasMessage("My exception custom message")
        }
    }
```

The test passes however.

**Comment by dkhalanskyjb** [comment]
> The test with the old coroutines test API looked like this

Nope, this doesn't use the old test API at all.

> So it looks like the [example](https://github.com/Kotlin/kotlinx.coroutines/blob/master/kotlinx-coroutines-test/MIGRATION.md#remove-usages-of-testcoroutineexceptionhandler-and-testcoroutinescopeuncaughtexceptions) in the migration guide has no chance to work.

The documentation is correct: it describes how to remove uses of `TestCoroutineExceptionHandler`, which only concerns uncaught exceptions. Here, you launch a coroutine, which catches the exceptions and propagates them upwards. If you did have *uncaught* exceptions, the handler would work.

> Just wrapping the runTest block in a try ... catch works, but it seems weird:

This is unsupported usage and won't work on the JS: we require that `runTest` is the last thing to happen in a test.

Pleas try this:

```
@Test
fun `when no gateway from scanning present then throw`() {
    val useCase = UseCase(null)
    assertFailsWith<IllegalStateException> { 
        useCase.execute()
    }
}
```

**Comment by lukasz-kalnik-gcx** [comment]
> > The test with the old coroutines test API looked like this
> 
> Nope, this doesn't use the old test API at all.
> 

You are right. But I meant that the migration guide also requires to migrate away from the uses of `runBlocking` (which indeed is not a part of the old test API).

> > So it looks like the [example](https://github.com/Kotlin/kotlinx.coroutines/blob/master/kotlinx-coroutines-test/MIGRATION.md#remove-usages-of-testcoroutineexceptionhandler-and-testcoroutinescopeuncaughtexceptions) in the migration guide has no chance to work.
> 
> The documentation is correct: it describes how to remove uses of `TestCoroutineExceptionHandler`, which only concerns uncaught exceptions. Here, you launch a coroutine, which catches the exceptions and propagates them upwards. If you did have _uncaught_ exceptions, the handler would work.
> 

Yes, I guess I misunderstood an "uncaught exception" as "any exception that crashes the test". But indeed an exception inside the coroutine is **caught** by the coroutine and then rethrown up the structured concurrency. The migration guide was not very clear for me here.

> > Just wrapping the runTest block in a try ... catch works, but it seems weird:
> 
> This is unsupported usage and won't work on the JS: we require that `runTest` is the last thing to happen in a test.
> 
> Please try this:
> 
> ```
> @Test
> fun `when no gateway from scanning present then throw`() = runTest {
>     val useCase = UseCase(null)
>     assertFailsWith<IllegalStateException> { 
>         useCase.execute()
>     }
> }
> ```

Thank you, that works and is obviously the correct solution.
