### ISSUE TITLE
Tests with `coroutineScope` + `launch` in 1.6.10 might never finish

### ISSUE THREAD

**Issue by sergeys-opera** [Kotlin/kotlinx.coroutines#3172]
Consider a simple class `IntsObserver` which we want to unit test:
```kotlin
import kotlinx.coroutines.coroutineScope
import kotlinx.coroutines.flow.Flow
import kotlinx.coroutines.flow.launchIn
import kotlinx.coroutines.flow.onEach

class IntsObserver(private val intFlow: Flow<Int>) {
    private val _evenInts = mutableListOf<Int>()
    val evenInts : List<Int> = _evenInts

    suspend fun observe() = coroutineScope {
        intFlow.onEach {
            if (it % 2 == 0) _evenInts.add(it)
        }.launchIn(this)
    }
}
```
This class filters a list of even integers produced by the the passed `intFlow`. An interesting detail about this class is that it creates a new scope from the parent scope by calling `coroutineScope`.

Here's a unit test which verifies that the filtered integers are indeed even:
```kotlin
import kotlinx.coroutines.Dispatchers
import kotlinx.coroutines.ExperimentalCoroutinesApi
import kotlinx.coroutines.flow.MutableStateFlow
import kotlinx.coroutines.launch
import kotlinx.coroutines.test.*
import org.junit.After
import org.junit.Assert
import org.junit.Before
import org.junit.Test

@OptIn(ExperimentalCoroutinesApi::class)
class IntsObserverTest {
    private lateinit var testCoroutineDispatcher: TestDispatcher
    private lateinit var testScope: TestScope
    private lateinit var intFlow: MutableStateFlow<Int>
    private lateinit var observer: IntsObserver

    @Before
    fun setUp() {
        testCoroutineDispatcher = StandardTestDispatcher()
        testScope = TestScope(testCoroutineDispatcher)
        Dispatchers.setMain(testCoroutineDispatcher)

        intFlow = MutableStateFlow(0)
        observer = IntsObserver(intFlow)
    }

    @After
    fun tearDown() {
        Dispatchers.resetMain()
    }

    @Test
    fun `filters even numbers`() {
        testScope.launch {
            observer.observe()
        }
        testScope.advanceUntilIdle()
        intFlow.value = 1
        testScope.advanceUntilIdle()
        intFlow.value = 2
        testScope.advanceUntilIdle()
        Assert.assertEquals(listOf(0, 2), observer.evenInts)
    }

    @Test
    fun `filters even numbers with runTest`() = runTest {
        testScope.launch {
            observer.observe()
        }
        advanceUntilIdle()
        intFlow.value = 1
        advanceUntilIdle()
        intFlow.value = 2
        advanceUntilIdle()
        Assert.assertEquals(listOf(0, 2), observer.evenInts)
    }

    @Test
    fun `filters even numbers but never finishes`() = runTest {
        observer.observe()
        advanceUntilIdle()
        intFlow.value = 1
        advanceUntilIdle()
        intFlow.value = 2
        advanceUntilIdle()
        Assert.assertEquals(listOf(0, 2), observer.evenInts)
    }
}
```

Note that the last test doesn't launch a new job when calling `observer.observe()`. However the job is launched in the observer itself via a `coroutineScope` and `launchIn` method calls. The last test never finishes - the first `advanceUntilIdle` call never returns. Replacing `advanceUntilIdle` with `advanceTimeBy(1)` doesn't help.

**Why does the last test freeze?**

I suspect that the last test case is the most straightforward way of testing the class above (`runTest`+ `advanceUntilIdle`) and I would expect it to be working. I found it weird that I had to wrap one `launch` (inside `IntsObserver`) with another (in the test case itself, `testScope.launch`) to make the test work. Am I doing something wrong?

**Comment by dkhalanskyjb** [comment]
Consider this code:
```kotlin
        runBlocking {
            val flow = MutableStateFlow(0)
            coroutineScope {
                flow.launchIn(this)
            }
        }
```
It will also hang.

This is due to a basic property of `coroutineScope`: `coroutineScope` will only exit once all of its child coroutines are completed: https://kotlin.github.io/kotlinx.coroutines/kotlinx-coroutines-core/kotlinx.coroutines/coroutine-scope.html

So, the tests only show you what actually happens: `coroutineScope { ... }` will only exit once the work in it is done. `launch`-ing some code means that it will execute concurrently, so the rest of the code doesn't have to wait for the `coroutineScope` to finish.
