### ISSUE TITLE
Can kotlin native now support `stack coroutine` like `go language`?

### ISSUE THREAD

**Issue by dragon-zhang** [Kotlin/kotlinx.coroutines#3176]
Can kotlin native now support `stack coroutine` like `go language`?

**Comment by elizarov** [comment]
Even though this is not related to `kotlinx.coroutines` project, I'm still curious what you are trying to accomplish? You can have a `stack` in Kotlin coroutines (see basic example where you have a stack of calls: https://kotlinlang.org/docs/coroutines-basics.html#extract-function-refactoring). What feature are you missing?

**Comment by dragon-zhang** [comment]
The main thread executes IO tasks through the `kotlinx.coroutines`. After the `coroutine` is scheduled to the a thread of the IO thread pool, the a thread will not be blocked.

For example, the size of thread pool `T` is 1, and it takes `1s` for tasks to be executed at a time. Let `1000` coroutines execute tasks and schedule them to a `single thread` of `T`. `kotlin JVM` takes `1000s`, while `goroutine` takes only about `1.1s`.

**Comment by elizarov** [comment]
Yes. You can use non-blocking IO with Kotlin coroutines just like in the Go language for the same effect. The only difference is that non-blocking IO is a part of Go standard library and is implemented in a non-blocking way by default, while IO in Kotlin is located in separate libraries and you have a choice of blocking or non-blocking IO depending on your needs and performance requirements (scale vs throughput). What kind of app you are planning to write?

**Comment by dragon-zhang** [comment]
Oh, I want to build a MQ middleware, like RocketMQ、kafka、pulsar.




------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "Kotlin/kotlinx.coroutines"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2022年2月9日(星期三) 下午3:22
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [Kotlin/kotlinx.coroutines] Can kotlin native now support `stack coroutine` like `go language`? (Issue #3176)





 
Yes. You can use non-blocking IO with Kotlin coroutines just like in the Go language for the same effect. The only difference is that non-blocking IO is a part of Go standard library and is implemented in a non-blocking way by default, while IO in Kotlin is located in separate libraries and you have a choice of blocking or non-blocking IO depending on your needs and performance requirements (scale vs throughput). What kind of app you are planning to write?
 
—
Reply to this email directly, view it on GitHub, or unsubscribe.
Triage notifications on the go with GitHub Mobile for iOS or Android.

**Comment by dragon-zhang** [comment]
Thanks a lot, it will be great helpful.





------------------ Original ------------------
From: Roman Elizarov ***@***.***&gt;
Date: Wed,Feb 9,2022 4:19 PM
To: Kotlin/kotlinx.coroutines ***@***.***&gt;
Cc: dragon-zhang ***@***.***&gt;, Author ***@***.***&gt;
Subject: Re: [Kotlin/kotlinx.coroutines] Can kotlin native now support `stack coroutine` like `go language`? (Issue #3176)





 
Your choice of the IO library depends on how "low level" your code needs to be:
  
You can choose a high-level framework, like Spring Boot, that has a lot of things built-in, like a great non-blocking and scalable IO implementation (Spring WebFlux) that integrates nicely with Kotlin coroutines. 

You can choose a slightly lower-level framework, like Ktor, that also provides a non-blocking IO stack and is implemented with Kotlin coroutines from the group-up. 

You can go even lower level working directly with non-blocking IO libraries like Netty or Java NIO (but then you'll have to write your own adapters to the Kotlin coroutines). 

You can go to "the metal" and code directly against non-blocking POSIX APIs of the operating system, but then it is even more integration code you'll have to write yourself. 
 
I hope it helps.
 
—
Reply to this email directly, view it on GitHub, or unsubscribe.
Triage notifications on the go with GitHub Mobile for iOS or Android.
