### ISSUE TITLE
[Test - coroutine 1.6.0] delay() - runTest with UnconfinedTestDispatcher will throw JobCancellationException

### ISSUE THREAD

**Issue by jun-wu-tw** [Kotlin/kotlinx.coroutines#3181]
Hey, I am gonna upgrading Coroutine 1.6.0 from 1.5.0.

I'd like to use `runTest` with `UnconfinedTestDispatcher` to replace `runBlockingTest` by the guide of Migration.md.

When I used `runTest` with `UnconfinedTestDispatcher`, it will throw JobCancellationException, then it won't continue execute follow codes. So I can't get the correct result. What could I do for this case? 

```
// Test.kt
fun test() = runTest(UnconfinedTestDispatcher()) {
   // mockk Something
   ViewModel().invoke()
   // verify Something
}

// ViewModel.kt
fun invoke() {
viewModelScope.launch {
      // doSomething
      delay(3_000)
      // doSomething - but it won't be executed !!!
}
}
```

Do you have any suggestions? 🙏

**Comment by jun-wu-tw** [comment]
It works in following way. But I don't know why. 🤔 

```
// Test.kt
fun test() = runTest {
   // mockk Something
  withiContext(StandardTestDispatcher(testScheduler)) {
   ViewModel().invoke()
  }
   // verify Something
}
```

**Comment by dkhalanskyjb** [comment]
If it throws a `JobCancellationException`, it means that something is cancelling the `viewModelScope` before `delay` has a chance to run. If you want the `delay` to complete before the cancellation, try this:
```kotlin
@BeforeEach
fun initializeMain() {
  Dispatchers.setMain(UnconfinedTestDispatcher())
}

fun test() = runTest {
  ViewModel().invoke()
  delay(3001) // so the code runs in the meantime
  // verify Something
}
```
In the code that's working, I don't think `withContext` is doing anything useful, so it probably can be removed.

Also, it's probably better to use StackOverflow or Slack to ask general questions like this one.

**Comment by jun-wu-tw** [comment]
Thanks for your relying and explanation. It helps me to understand coroutine deeper.
I am sorry for asking question at there. I will notice that next time. 😄 
Appreciate for the explanation again. 👍
