### ISSUE TITLE
Allow nullable types in Publisher.asFlow and Flow.asPublisher

### ISSUE THREAD

**Issue by nakamura-to** [Kotlin/kotlinx.coroutines#3186]
I'd like to know why the nullable types are not allowed in `Publisher.asFlow` and `Flow.asPublisher`.
Here is the proof code:

```kotlin
import kotlinx.coroutines.flow.Flow
import kotlinx.coroutines.reactive.asFlow
import kotlinx.coroutines.reactive.asPublisher
import kotlinx.coroutines.runBlocking
import org.reactivestreams.Publisher

fun main() = runBlocking {
    val p1: Publisher<Int> = TODO()
    val p2: Publisher<Int?> = TODO()
    val f1: Flow<Int> = TODO()
    val f2: Flow<Int?> = TODO()

    p1.asFlow() // compilation success
    p2.asFlow() // compilation error

    f1.asPublisher() // compilation success
    f2.asPublisher() // compilation error
}
```

I am writing code to handle the R2DBC API with kotlinx-coroutines-reactive. Since `Publisher.asFlow` does not allow nullable types, redundant null handling is required as a workaround:

https://github.com/komapper/komapper/blob/c4e935c8096fcd7e72963b80b7d6b9b894e572e4/komapper-r2dbc/src/main/kotlin/org/komapper/r2dbc/R2dbcExecutor.kt#L42-L48

I hope that nullable types will be supported in `Publisher.asFlow` and `Flow.asPublisher`.

**Comment by mhernand40** [comment]
I believe the [Reactive Streams](reactive-streams.org) specification prohibits emitting `null` values. Since the main JVM implementations are in Java, there is no compile time `null` safety but they will result in `NullPointerExceptions` whenever `null` is emitted if I'm not mistaken. This is certainly true for RxJava 2 & 3.

**Comment by dkhalanskyjb** [comment]
Yes, this is correct, the reason is to avoid providing non-compliant implementations.

**Comment by nakamura-to** [comment]
Thank you for your answer.
