### ISSUE TITLE
collectLatest issue. it's working as expected only after a delay statement.

### ISSUE THREAD

**Issue by Manideepkota0708** [Kotlin/kotlinx.coroutines#3188]
```
fun main() = runBlocking<Unit> {
    val mutableSharedFlow = MutableSharedFlow<String>()
    val sharedFlow: SharedFlow<String> = mutableSharedFlow

    launch {
        sharedFlow.collectLatest {
            println("launch1: $it")
        }
    }

    launch {
        mutableSharedFlow.emit("ONE")
        mutableSharedFlow.emit("TWO")
        mutableSharedFlow.emit("THREE")
        mutableSharedFlow.emit("FOUR")
        mutableSharedFlow.emit("FIVE")
        delay(10)
        mutableSharedFlow.emit("SIX")
        mutableSharedFlow.emit("SEVEN")
        mutableSharedFlow.emit("EIGHT")
        mutableSharedFlow.emit("NINE")
        mutableSharedFlow.emit("TEN")
    }
}
```

output: 
launch1: SIX
launch1: SEVEN
launch1: EIGHT
launch1: NINE
launch1: TEN

**Comment by Manideepkota0708** [comment]
why the first five events are skipped?

**Comment by LouisCAD** [comment]
Because that's how `collectLatest` works. It only cares about the latest, and cancels collection of a previous value, if any.

If you don't want this behavior, use `collect`.

**Comment by LouisCAD** [comment]
I think it's already quite clear in the `collectLatest` KDoc, or did something read ambiguous or unclear to you?

**Comment by Manideepkota0708** [comment]
the first five emits are not getting suspended even if there is a `collectLatest` attached to the shared flow.
the other five emits are suspending and resuming.

The example given in [kotlin docs](https://github.com/Kotlin/kotlinx.coroutines/blob/master/kotlinx-coroutines-core/common/src/flow/terminal/Collect.kt#L65-L85) is pretty easy to understand as it has delay method inside the `collectLatest` block, hence it is canceling the existing one and accepting the next one.

but I didn't get why SIX, SEVEN, EIGHT, NINE, TEN events are getting collected missing the first five events.

I understand that using collect I'm able to get without any issues, but I just thought this should also work the same way.

you can close this if it's not an issue @LouisCAD. And thanks for your patience and response (every time you are replying as soon as you see the comment).

**Comment by qwwdfsad** [comment]
Hey, could you please elaborate on the exact problem you are having?

**Comment by Manideepkota0708** [comment]
Hai @qwwdfsad, firstly kotlin is a great language, I use it every day for my android development.
[please refer this issue](https://github.com/Kotlin/kotlinx.coroutines/issues/3162)
Pls do put some time and copy the exact code in intelli-j and see the output, and If possible explain me. 
If it's not at all an issue, just ignore. Thanks for your time @qwwdfsad
