### ISSUE TITLE
[Support] What happened to kotlinx.coroutines.generate?

### ISSUE THREAD

**Issue by smillies** [Kotlin/kotlinx.coroutines#32]
Hello there,

a while back (with 0.2-beta) I wrote some tree-walking code using function `kotlinx.coroutines.generate`. Specifically, the generate-function would create Sequence objects given a coroutine body containing `yield` suspension points.

I cannot find that library function anymore. Indeed, the Maven artifact itself seems to have gone.  Is there a replacement?

**Comment by ilya-g** [comment]
It has been moved to the Kotlin standard library under the name `buildSequence`. 
Thus to use it you don't have to depend on `kotlinx.coroutines`, just import that function from the package `kotlin.coroutines.experimental`

**Comment by smillies** [comment]
Thanks, found it.
