### ISSUE TITLE
Async is not cancelled

### ISSUE THREAD

**Issue by SamKotlinFisher** [Kotlin/kotlinx.coroutines#320]
I have a function which load the image by click on button. If button is clicked twice (second click before async completion) it's needed to cancel old async and start new.
Code example:
```
private var deferred: Deferred<Bitmap>? = null
override fun onCreate(inState: Bundle?) {
        super.onCreate(inState)
        findViewById<View>(R.id.btn_action).setOnClickListener {
            if (deferred != null && deferred?.isActive == true) {
                Log.d("debug", "cancel")
                deferred?.cancel()
            }
            loadImage()
        }
    }

    private fun loadImage() = launch(UI) {
        Log.d("debug", "start")
        deferred = async {
           val conn = URL("http://elitefon.ru/pic/201503/2560x1600/elitefon.ru-38503.jpg").openConnection() as HttpURLConnection
            val bitmap = BitmapFactory.decodeStream(conn.inputStream)
            Log.d("debug", "end of async")
            return@async bitmap
        }
        deferred?.await()
        Log.d("debug", "loaded")
    }
```

In this case log will be something like this:
```
start
cancel
start
end of async
end of async
loaded
```
As we can see, in spite of cancel, "end of async" log is called twice.
Also, try/catch logging shown that CancelationException is throws in the launch(UI) block (not the async block).
Can I make it so that if I cancel async, the exception was thrown in the async block?

**Comment by jcornaz** [comment]
in coroutines cancellation is [cooperative](https://github.com/Kotlin/kotlinx.coroutines/blob/master/coroutines-guide.md#cancellation-is-cooperative). The code in your `async` block is not actually cancellable.

You can make it actually cancellable by using `yield` or checking `isActive`. 

Example:
```kotlin
deferred = async {
	val conn = URL("http://elitefon.ru/pic/201503/2560x1600/elitefon.ru-38503.jpg").openConnection() as HttpURLConnection
	yield() // throw CancellationException if the deferred is cancelled
	val bitmap = BitmapFactory.decodeStream(conn.inputStream)
	yield() // throw CancellationException if the deferred is cancelled
	Log.d("debug", "end of async")
	return@async bitmap
}
```

**Comment by SamKotlinFisher** [comment]
@jcornaz, thanks for your answer, but this solution is not suitable for me. Most of the async time relates with BitmapFactory.decodeStream(conn.inputStream) and stream still read after cancelation. I want to interrupt stream reading after cancelation like cancel(true) of android.osAsyncTask.

**Comment by fvasco** [comment]
Same issue here https://github.com/Kotlin/kotlinx.coroutines/issues/173

Don't execute blocking code on common pool (it is really like the UI dispatcher).

Use a dedicated Executor and cancel (with interruption) the Future when necessary.

**Comment by SamKotlinFisher** [comment]
@fvasco, I add CachedThreadPool as CoroutineDispatcher to async(CachedPool) like this:
```
val CachedPool = Executors.newCachedThreadPool().asCoroutineDispatcher()
async(CachedPool) {...}
```
But cancelation still not working what I expecting.
Сan you write code example?

**Comment by fvasco** [comment]
Hi @SamKotlinFisher 
cancelling coroutine does not interrupt the thread, so if you need to interrupt thread then you must use `Future.cancel(...)` or something similar.

See also: https://discuss.kotlinlang.org/t/calling-blocking-code-in-coroutines/2368/6

**Comment by SamKotlinFisher** [comment]
@fvasco, thanks for your answer. I developed the similar solution:
```
fun <T> async (block: () -> T): Deferred <T?> {
     var thread: Thread? = null
     val deferred = async (CachedPool) {
         thread = Thread.currentThread ()
         return @async block.invoke ()
     }
     deferred.invokeOnCompletion (true, true) {
         if (deferred.isCancelled && thread! = null && thread? .isAlive == true) {
             thread? .interrupt ()
             thread = null
         }
     }
     return deferred
}
```
What do you think about this?

**Comment by SamKotlinFisher** [comment]
@fvasco, thank you so much for your answer. I hope that this functionality will be able in kotlin-coroutine in a future as are described in #57.
