### ISSUE TITLE
Speed up workers

### ISSUE THREAD

**Issue by slavonnet** [Kotlin/kotlinx.coroutines#3208]
Изменения в #3137 можно улучшить так как новый массив всегда больше предыдущего и содержит в себе предыдущий массив плюс обновление. Следовательно Виолейт не нужен, а нужно хранить размер массива и получать/изменять элемент, если индекс в массиве. Если же массив увеличивается ,то значение размера нужно обновлять после изменения переменной.  

Changes in #3137 can be improved as the new array is always larger than the previous one and contains the previous array plus the update. Therefore, Vop;ate is not needed, but you need to store the size of the array and get / change the element if the index is in the array. If the array increases, then the size value must be updated after changing the variable.

**Comment by dkhalanskyjb** [comment]
volatile нужен, чтобы была гарантия, что когда при копировании происходит присваивание `array = newArray`, во всех потоках, которые увидели результат этого присваивания, также был видны последствия `newArray[i] = curArray[i]`. Посмотрите на правила happens-before для Java.

**Comment by slavonnet** [comment]
Я знаю зачем нужен volatile )  но по условия задачи тут оверхед ИМХО. 
- Элементы массива уже Violate
- ссылку на сам массив за границы класса мы не получаем 
- при изменении размера идет логика COW, а ссылки атомарные 
-- размер массива всегда расширяется поэтому даже если другой тред гоняет цикл то при замене источника цикл за границы не выйдет, а данные по индексам будут те же  Ссылка подменяется в атомарно, а переменная с размером массива константа до след увеличения и хорошо хорошо кешируется
- по условиям задачи изменение идут синхронно (можно ттред сейф сделать)

в результате у у нас атомарный Инт который указывает на текущий размер синхронизирован будет в 1 тик, геттер упрощается до  `if (index  in 0 ..  size) null else arra::get` сеттер аналогичен только `if (index > size) expandAndSize();; array::set`. При этом для тред сейф нужна только блокировка при расширении . Так же для обновления я бы для скорости заменил на Секвенцию, далее, фильтровал нулы и не делал бы лишних сетов, ведь каждый элемент Виолейт, только записывал где значение есть. 

И можно уйти в отрицательный индекс сейчас, это не безопасно

ПСС Когда то Вы поймете что на втором местью после NPE идет thread unsade RW и для сахара след уровня надо  в котлин добавить операцию Get+Compare+SetIfChaned типа   `Obj?.varBol := true`` тем самым снизив вымывания кешей, синхронизации,  нотификации, изменений и повторные изменения без изменений при огромных кросс коллах внутри классов. Это базовая функция затухания энтропии получается. Я  даже уже расписывал этот имправ.

ПССС, Поставте на голосование  вопрос про   `?:` , попытайся переубедить всех что без него лучше, а потом когда потерпишь крах или добавь его или не смей говоришь что котлин создается с сообществом.  Толпа привыкла так. Толпа хочет так.  Я легко разнесу в споре любой довод против, а в конце останется только факт  лицемерия и эгоизма .   Любая TrueWay модель выносится FastPath если профит от упрощения  в разы.  :)

**Comment by qwwdfsad** [comment]
Once again: this is a public repository with English being its only official language, any other language for communication is not welcomed here. If you do not feel comfortable discussing the matter in English -- feel free to reach maintainers you know can understand you via slack or email.

The goal here is to be open for other folks to participate, express their opinion on implementation, design or any other question.

**Comment by qwwdfsad** [comment]
@slavonnet  also, this is the second time when you are using familiarity and hostility towards maintainers, not talking about the fact that you have been warned about the language.

This won't be tolerated any more -- the very next violation of any basic communication hygiene will result in your ban

**Comment by slavonnet** [comment]
@qwwdfsad  You need to be offended when they want to offend you. You have confused the "kitchen talk" narrative style. . In my text there was no appeal to a specific someone, but to a third person (opponent). IDDQD activate and "plus throw" is a good thanks for your participation and willingness to help. No matter how free my style is, the body contains only love and care. I am ready to answer and defend for every word and message, but you will not find the time for this. I don't need an apology if you don't understand your fault.

Fact
- Freedom of the bastard is one of the main values
- I did not subscribe to your rules of business correspondence
- Your freedoms are no more important than mine. The truth is in the middle.
- In my world, if you do not want to communicate with a person, you need to tell him about it. He will leave. Threats are the path to the dark side.

Resources, finance, subscriptions to products, donations to the android topic and other support are turned off. No negative. Your request is heard, Attitude is now neutral.

"No to cages and restrictions in minds, thoughts, deeds, and the truth."

Nevertheless, with respect and good wishes.

**Comment by dkhalanskyjb** [comment]
The fault for using Russian is on me, it was I who initially chose to engage using Russian exclusively. I thought it would be the most efficient way to go in this particular instance. Sorry, my bad.
