### ISSUE TITLE
how to create new forkjoinpool context like CommonPool

### ISSUE THREAD

**Issue by Jaware** [Kotlin/kotlinx.coroutines#321]
in our situation,runtime cpu core size is too large because of the docker,so i want to create new forkjoinpool and use it as the coroutine's running context,there is no docs about how to do that,can anyone show me

**Comment by qwwdfsad** [comment]
Currently, there is no such option.
I think we can add configuration via system property for such specific cases

**Comment by fvasco** [comment]
Are you looking for something like

    ForkJoinPool(2).asCoroutineDispatcher()

However the JVM 10 works well in a container.

**Comment by qwwdfsad** [comment]
The downside of this approach is that now you should pass your dispatcher in everywhere.
It may be applicable, but it's not the most convenient option

**Comment by Jaware** [comment]
thanks for your reply,can i use this 'ForkJoinPool(2).asCoroutineDispatcher()' way  in production?

**Comment by Jaware** [comment]
our k8 docker cluster use  cpu sharing mode with mashine @fvasco ,so the 'Runtime.getRuntime().availableProcessors() ' is not my container's cpu count

**Comment by fvasco** [comment]
This was fixed in JVM 10, alternatively you can safety use `asCoroutineDispatcher`

**Comment by Jaware** [comment]
thanks @fvasco
