### ISSUE TITLE
Robolectric tests froze forever after upgrade to 1.6.0, because of `delay` inside Dispatcher.IO

### ISSUE THREAD

**Issue by neworld** [Kotlin/kotlinx.coroutines#3211]
This code works totally fine on vanilla junit tests, or in <1.6.0 versions of coroutines, but it stuck forever in `RobolectricTestRunner` after upgrade to 1.6.0:
```
@Test
fun foo() = runBlocking {
    withContext(Dispatchers.IO) {
        println("before delay")
        delay(1000) // <------ here stuck forever
        println("after delay")
    }
}
```

Test dispatchers also work OK. Is it intended? If not, I can create a full project if it helps you to fix the bug. My case is similar to #1365

**Comment by dkhalanskyjb** [comment]
Could you try setting the `kotlinx.coroutines.main.delay` system property to `false`? This looks like an issue with the same root cause as https://github.com/Kotlin/kotlinx.coroutines/issues/3173.

**Comment by neworld** [comment]
Thanks, @dkhalanskyjb. It works. I am closing this in favor of having one issue: #3173

**Comment by pacher** [comment]
This issue keeps popping up, I counted already five.
@qwwdfsad Maybe you can consider if anyhow possible to make a minor release where the delay change is reverted? 
Last coroutines release was almost three month ago.
