### ISSUE TITLE
uncaughtExceptionPreHandler does not exist

### ISSUE THREAD

**Issue by NWuensche** [Kotlin/kotlinx.coroutines#3215]
I tried to implement a global coroutine exception handler. However, the `uncaughtExceptionPreHandler` from the [wiki](https://github.com/Kotlin/kotlinx.coroutines/blob/master/docs/topics/exception-handling.md) does not exist. I also added the `kotlinx-coroutines-android` lib in version 1.6, but I still don't get this. Is the wiki outdated, as [the readme](https://github.com/Kotlin/kotlinx.coroutines/tree/master/ui/kotlinx-coroutines-android) also does not say anything about `uncaughtExceptionPreHandler` nor `Thread.uncaughtExceptionPreHandler`?

**Comment by dkhalanskyjb** [comment]
The docs should be updated, as the implementation changed since then.

In any case, you shouldn't have to do anything, the docs only describe what our library does on its own. Adding `kotlinx-coroutines-android` as a dependency should be sufficient for uncaught exceptions in coroutines to be propagated to the Android runtime, one way or another.

**Comment by NWuensche** [comment]
Thank you for the reply. However, I would expect that I can somehow install my
own global CoroutineExceptionHandler, where I can say "write to this log" or something like that. 
Something like `RxJavaPlugins.setErrorHandler` in RxJava. Is there no option for that?

**Comment by qwwdfsad** [comment]
We do not have option for that and we do not intend to provide one. Reactive frameworks experience showed us that having a global mutable state for dispatchers, error handlers, various on* hooks and shutdown hook is the very common source of non-deterministic bugs as the behaviour depends only on who is invoked first/last and has its `Rx*Plugins.set*` won.

The suggested solution is to have your own CEH in application-specific top-level scope.

**Comment by NWuensche** [comment]
Thank you. However, maybe you shouldn't write "...it is possible to redefine global exception handler for all coroutines" in the documentation then, but maybe write that this is indeed *not* possible/recomended :) . I would also like it if you could give an example in the documentation on how to define a CEH on top-level scope. I work on Android, and I'm not 100% how to do this considering using the provided `lifecycleScope` and `viewModelScope`. It would be really annoying to add (and maybe forget) a CEH to each scope separately.
