### ISSUE TITLE
Consider providing CoroutineContext.dispatcher extension property

### ISSUE THREAD

**Issue by qwwdfsad** [Kotlin/kotlinx.coroutines#3216]
TBD

**Comment by zuevmaxim** [comment]
Despite being useful in the library itself, the `context[CoroutineDispatcher]` construction is not widely used in the users' code [1](https://grep.app/search?q=%5B%5E%20%5D%5C%5BCoroutineDispatcher%28.key%29%3F%5C%5D&regexp=true), [2](https://grep.app/search?q=%5B%5E%20%5D%5C%5BContinuationInterceptor%5C%5D%20as&regexp=true). Considering this, no public API is required now
