### ISSUE TITLE
JPMS: coroutines-core-jvm uses package name kotlinx.coroutines.test

### ISSUE THREAD

**Issue by hfhbd** [Kotlin/kotlinx.coroutines#3218]
I want to use the new multiplatform test feature from 1.6.0. 
Unfortunately, we use JPMS, which fails with this error message:
```
module io.ktor.io reads package kotlinx.coroutines.test from both kotlinx.coroutines.test.jvm and kotlinx.coroutines.core.jvm
```
Reason: `coroutines-core` uses the same package `kotlinx.coroutines.test`: https://github.com/Kotlin/kotlinx.coroutines/blob/master/kotlinx-coroutines-core/jvm/src/test_/TestCoroutineContext.kt

Maybe related: https://github.com/Kotlin/kotlinx.coroutines/issues/3128

**Comment by qwwdfsad** [comment]
We'll drop kotlinx.coroutines.test in the next major release, it contains pre-1.0.0 obsolete test classes
