### ISSUE TITLE
Consider adding Long overload of sumBy

### ISSUE THREAD

**Issue by venkatperi** [Kotlin/kotlinx.coroutines#322]
Consider adding `Long` overload of [`sumBy`](https://github.com/Kotlin/kotlinx.coroutines/blob/ff2d18977fef840e98c25f2d94b41bfcc244b46d/core/kotlinx-coroutines-core/src/main/kotlin/kotlinx/coroutines/experimental/channels/Channels.kt#L1445):

(Edit: changed name to `sumByLong` per @jcornaz)

```kotlin
public inline suspend fun <E> ReceiveChannel<E>.sumByLong(selector: (E) -> Long): Long {
    var sum = 0L
    consumeEach {
        sum += selector(it)
    }
    return sum
}
```

**Comment by jcornaz** [comment]
The declaration function signature would clash with `ReceiveChannel<E>.sumBy(selector: (E) -> Int): Int` (because of type erasure)

But it could be named `sumByLong`. This naming is consistent with the current existing `sumByDouble`

**Comment by elizarov** [comment]
The design goal is to keep the set of extensions on `ReceiveChannel` to be conceptually the same as available in kotlin standard library for `Sequence` type: https://kotlinlang.org/api/latest/jvm/stdlib/kotlin.sequences/-sequence/index.html#extension-functions

We would add time-based extensions and other extensions that make sense for asynchronous streams of events, but the goal is to refrain from going into Rx world with hundreds of operators you could ever discover. 

So, I'd say no to `sumByLong`. It is easy to define when needed.

**Comment by qwwdfsad** [comment]
We'd like to avoid introducing hundreds of operators on top of channels.
The main idea is to introduce only non-trivial building blocks (e.g. `DelayChannel` and `select`), which can be used to build any Rx-like operator via a single method.
Moreover, it's unclear whether we need such operators on top of channels when cold streams will be implemented.
