### ISSUE TITLE
mutex.withLock is not guaranteeing order in iOS

### ISSUE THREAD

**Issue by colinta** [Kotlin/kotlinx.coroutines#3224]
We recently started launching the iOS version of our app, powered by React Native and Kotlin Multiplatform, and we're seeing an issue that, we think, is caused by `Mutex#withLock`. On Android we do not see this issue, only on iOS... 🤔 

We are creating a global mutex:
```kotlin
import kotlinx.coroutines.sync.Mutex

internal object HardwareMutex : Mutex by Mutex()
```

And using it to ensure hardware events are handled in order. We have many functions that listen for a hardware event, and they all have this shape:
```kotlin
fun subscribe(): ReceiveChannel<HardwareEvent> = hardwareWrapper.subscribe()  // comes from third party hardware library

suspend fun doDeviceThing(block: ()) =  mutex.withLock {
  val expectedEvents = listOf(HardwareEvent.Connected::class,...)

  return with(subscribe()) {
    hardwareWrapper.doDeviceThing()

    //returns:
    it.consumeAsFlow()
      .filter { event ->
        // here we sanity check that 'event' is one of our expected hardware states
        expectedEvents.any { it.isInstance(event) }
      }.first()
  }
}
```

I chatted about this issue with the Kotlin Slack channel and was asked to post it here to be tracked. I hope I included the useful details!

**Comment by qwwdfsad** [comment]
Hi.

What is the question? :) 

Please provide a problem description -- what exactly does not work in an expected way and, if possible, how to reproduce it. Additional details on the surrounding code are welcome as well
