### ISSUE TITLE
Duplicate of 'META-INF/kotlinx_coroutines_core.version' from two libs.

### ISSUE THREAD

**Issue by saurabhkpatel** [Kotlin/kotlinx.coroutines#3233]
I am trying to bump kotlin-coroutines 1.6.0 in the Android project and I see the following error:

```
* What went wrong:
Execution failed for task ':app:mergeDebugJavaResource'.
> A failure occurred while executing com.android.build.gradle.internal.tasks.MergeJavaResWorkAction
   > 2 files found with path 'META-INF/kotlinx_coroutines_core.version' from inputs:
      - ../org.jetbrains.kotlinx/kotlinx-coroutines-core/1.6.0/c0277601cc4f7f24fe200651c5680e2e424a0a85/kotlinx-coroutines-core-1.6.0.jar
      - ../org.jetbrains.kotlinx/kotlinx-coroutines-core-jvm/1.6.0/f3b8fd26c2e76d2f18cbc36aacb6e349fcb9fd5f/kotlinx-coroutines-core-jvm-1.6.0.jar
     Adding a packagingOptions block may help, please refer to
     https://google.github.io/android-gradle-dsl/current/com.android.build.gradle.internal.dsl.PackagingOptions.html
     for more information
```

Trying to add this dependency: `org.jetbrains.kotlinx:kotlinx-coroutines-core:1.6.0`, see the attached screenshot shows the same name for the two different jar files.

I know I can fix it by `exclude` under `packagingOptions` but that's the correct way to fix this ?

![Screen Shot 2022-04-04 at 4 14 11 PM](https://user-images.githubusercontent.com/1188367/161648360-8393a6bc-fa22-49d2-9466-da24a811a8dc.png)

**Comment by qwwdfsad** [comment]
It seems like it is rather a build system question than kotlinx-coroutines one, I suggest looking for help in the corresponding StackOverflow or Slack channels.

In general, exclude should work, but it seems you explicitly have both `common` and `jvm` specific dependencies declared and it might be the problem. Can't say much more without actual reproducer

**Comment by saurabhkpatel** [comment]
I think I know the reason what's going on.  Closing this now.
another lib was pulling the dependency transitivity.
