### ISSUE TITLE
StandardTestDispatcher runs pending tasks immediately (also regardless of delay)

### ISSUE THREAD

**Issue by NinoDLC** [Kotlin/kotlinx.coroutines#3238]
```
@ExperimentalCoroutinesApi
class WtfMigration {

    private val testCoroutineDispatcher: TestDispatcher = StandardTestDispatcher()

    @get:Rule
    val instantTaskExecutorRule = InstantTaskExecutorRule()

    @Before
    fun setUp() {
        Dispatchers.setMain(testCoroutineDispatcher)
    }

    @After
    fun teardown() {
        Dispatchers.resetMain()
    }

    @Test
    fun testDelayRegression() = runTest {
        liveDataToFlow(testCoroutineDispatcher).observeForever {
            println("new value observed : $it")
            assertEquals("foo", it)
        }
    }

    private fun liveDataToFlow(dispatcher: CoroutineDispatcher) = flow {
        delay(300)
        emit("foo")
    }.asLiveData(dispatcher)
}
```

Running this code prints "new value observed : foo" in the console (the assert doesn't fail, which is even more surprising, we jumped 300ms in time magically !). 

It should fail, as the `StandardTestDispatcher` is supposed to not run tasks immediately (even less so 300 ms in the future). 

Kotlin 1.6.20
Kotlinx-coroutines-test 1.6.1

**Comment by dkhalanskyjb** [comment]
Please use the public Kotlin Slack for general questions.

> It should fail, as the StandardTestDispatcher is supposed to not run tasks immediately (even less so 300 ms in the future).

`runTest` always attempts to run all pending work, including that which is delayed, the choice of a dispatcher doesn't matter. `StandardTestDispatcher` differs from `UnconfinedTestDispatcher` in that the latter is *unconfined*. Please see https://kotlinlang.org/docs/coroutine-context-and-dispatchers.html for an explanation of what unconfinedness entails.

**Comment by NinoDLC** [comment]
This is not a question, this is a bug, or an incoherence in the documentation. 

In the migration guide, it is written `[advanceTimeBy(n)] is not deprecated for TestCoroutineScheduler and TestScope, but has a different meaning: it does not run the tasks scheduled at currentTime + n.`. If it doesn't run tasks scheduled at X time, I guess that time is paused at the beginning of the test, otherwise `advanceTimeBy(n)` makes no sense if runTest always attempts to run all pending work...

This new API is just so confusing, nothing makes sense. Sometimes it says nothing runs by default, the other time it says everything runs by default, it even auto advance in time. Sticking to Kotlin 1.5 for now.

**Comment by dkhalanskyjb** [comment]
> it is written [advanceTimeBy(n)]

I don't see a single `advanceTimeBy` here, so this is irrelevant.

**Comment by NinoDLC** [comment]
I have a `delay(300)` in my flow before it emits anything. In 1.5, I would use `advanceTimeBy(300)` for my flow to emit. So this is relevant. I *used* `advanceTimeBy` but now the new API doesn't behave that way and nothing in the migration guide explains that.

**Comment by dkhalanskyjb** [comment]
This is not true, in 1.5 `runBlockingTest` also ran all the pending work.

**Comment by dkhalanskyjb** [comment]
Remove `advanceTimeBy(301)` from the 1.6 example you've shown, and the test also fails, so this doesn't prove anything.

Also, please assume that, if nothing else, we at least know our own APIs.

**Comment by NinoDLC** [comment]
> Remove advanceTimeBy(301) from the 1.6 example you've shown, and the test also fails, so this doesn't prove anything.

It proves that what you said `In 1.5 runBlockingTest also ran all the pending work.` isn't correct. Neither 1.5 nor 1.6 ran all the pending work. I genuinely try to understand the new "rules" of the new testing API but I have an example that show that all work it done instantly (https://github.com/Kotlin/kotlinx.coroutines/issues/3238#issue-1196075040) and another example that show that no work it done instantly (https://github.com/Kotlin/kotlinx.coroutines/issues/3239#issuecomment-1092847194).

Until 1.6, my understanding was no "automatic jump in virtual test time" was possible. The docs (https://github.com/Kotlin/kotlinx.coroutines/tree/master/kotlinx-coroutines-test#overview) says `[runTest] Runs the test code, automatically skipping delays and handling uncaught exceptions.`, but I produced examples that doesn't automatically skip delays. So I'm very confused.

**Comment by dkhalanskyjb** [comment]
> It proves that what you said In 1.5 runBlockingTest also ran all the pending work. isn't correct

It can't prove that, because what I said is correct. I've spent several months working on these APIs, so I'd hope I know what they do.

Here, run this:
```kotlin
@ExperimentalCoroutinesApi
class X {

    @Test
    fun testFoo() = runBlockingTest {
        println(1)
        launch {
            println(2)
            delay(300)
            println(4)
        }
        println(3)
    }
}
```
It prints
```
1
2
3
4
```
