### ISSUE TITLE
Flow<*>.filterIsInstance is missing its Class<R> overload

### ISSUE THREAD

**Issue by dmstocking** [Kotlin/kotlinx.coroutines#3240]
The Kotlin stdlib provides `filterIsInstance` for Array and Iterable with an inline and non inline version (aka with Class<R>). Flow does not include the Class<R> version. This seems inconsistent and that Flow should add a variant that takes the Class<R>. I have encountered this myself and ended up writing my own `filterIsInstance` to do just that.

```
@Suppress("UNCHECKED_CAST")
public fun <R> Flow<*>.filterIsInstance(klass: Class<R>): Flow<R> = filter { klass.isInstance(it) } as Flow<R>
```

**Comment by dmstocking** [comment]
I would like it fixed for both real life use cases and consistency. I mostly implement protocols for communication applications (like XMPP). What ends up happening is that there are a lot of features that only listen to one type of message. So I usually end up writing a helper function to only get the message you want. It also ends up being more type safe, because I specify the inheritance of the generic parameter. If you just use `filterIsInstance`, you don't end up getting any type safety really due to the compiler just walking up the tree until it finds `Any`. Anyway if you just have the inline version, it becomes very hard to make a useful function without also exposing private variables. 

```
    private val messages = MutableSharedFlow<Message>()

// with this new function I can do
    fun <T : Message> messages(clazz: Class<T>): Flow<T> = messages.filterIsInstance(clazz)
    inline fun <reified T : Message> messages(): Flow<T> = messages(T::class.java)

// without I have to expose a function I don't really want
    private fun messagesRaw(): Flow<Message> = messages
    inline fun <reified T : Message> messages(): Flow<T> = messagesRaw().filterIsInstance(clazz)
```

**Comment by IgnatBeresnev** [comment]
Implemented in #3464

**Comment by IgnatBeresnev** [comment]
> a bot closes the issues automatically once the fixes are part of a release

Some sort of wizardry! Sorry :sweat_smile:

**Comment by dmstocking** [comment]
Hurray!
