### ISSUE TITLE
Wrong Kotlin version in main README.md ?

### ISSUE THREAD

**Issue by psteiger** [Kotlin/kotlinx.coroutines#3242]
Hi!

Docs state that `kotlinx-coroutines` 1.6.1 is a companion to Kotlin 1.6.1. This must be a mistake as there's no such Kotlin public release named 1.6.1, as per https://kotlinlang.org/docs/releases.html#release-details

Does it mean 1.6.10? Or 1.6.20?

Thanks.

**Comment by qwwdfsad** [comment]
Good catch, thanks!

**Comment by psteiger** [comment]
@qwwdfsad thanks for your quick response

Text below badge also needs fixing:

> This is a companion version for the Kotlin 1.6.1 release.
