### ISSUE TITLE
Dispatchers.setMain not working for 1.6+ versions

### ISSUE THREAD

**Issue by akolubau** [Kotlin/kotlinx.coroutines#3244]
Currently, using `1.5.2`, everything works fine. 
After library update to `1.6.0` or `1.6.1` version, I'm receiving message `Module with the Main dispatcher had failed to initialize. For tests Dispatchers.setMain from kotlinx-coroutines-test module can be used`. Same message I receive, if I just remove `@BeforeTest fun setup() { Dispatchers.setMain ...` for `1.5.2`. 
Tried to add `MainCoroutineRule` - no use.

What could be a problem?

**Comment by gbusiri** [comment]
same here

**Comment by dkhalanskyjb** [comment]
Hi! This could be caused by a version mismatch, that is, if the `kotlinx-coroutines-core` version was increased, but the `kotlinx-coroutines-test` version wasn't.

If this is not the case, please provide a project where this issue reproduces so I could take a look at it.

**Comment by gbusiri** [comment]
`kotlinx-coroutines-core` and `kotlinx-coroutines-test` using the same versions. Yeah it's different case i think

**Comment by gbusiri** [comment]
trying to add `@RunWith(AndroidJUnit4::class)` to my test class and then solved, may it can help if your problem same with me.

**Comment by qwwdfsad** [comment]
It would be really helpful if someone could add a reproducing project. 

Mismatched versions shouldn't be an issue since #2952, so it's probably something else that we potentially can workaround on our side

**Comment by DroidZed** [comment]
Any new update on the fix ? I have the same issue even if I add `kotlinx-coroutines-android` , `kotlinx-coroutines-core` and `kotlinx-coroutines-test` on the same project while writing and android instrumented test :/

**Comment by qwwdfsad** [comment]
We still need the reproducer in order to fix the issue, or at least to report it to the responsible party.

It works in general setups, but for some Android projects it doesn't, and we need a reproducer to pinpoint the issue

**Comment by akolubau** [comment]
> ```
> val classUnderTest by lazy { MyClass(TestScope()) }
> ```

This works for me. With 
` Dispatchers.setMain(Dispatchers.Unconfined)`

Suggest to close this issue, because for my case issue is not relevant.
