### ISSUE TITLE
Broken link in documentation of Abstract Flow

### ISSUE THREAD

**Issue by Arthur-Milchior** [Kotlin/kotlinx.coroutines#3256]
In https://kotlin.github.io/kotlinx.coroutines/kotlinx-coroutines-core/kotlinx.coroutines.flow/-abstract-flow/index.html the link to CancellableFlow, https://kotlin.github.io/kotlinx.coroutines/kotlinx-coroutines-core/kotlinx.coroutines.flow/-cancellable-flow/index.html , is 404.

I looked at the source code on https://github.com/Kotlin/kotlinx.coroutines/blob/master/kotlinx-coroutines-core/common/src/flow/Flow.kt#L225 but there is no obvious error there, since the link should be automatically generated from inheritance

**Comment by qwwdfsad** [comment]
Will be fixed in Dokka with [#2460](https://github.com/Kotlin/dokka/issues/2460)
