### ISSUE TITLE
pauseDispatcher and resumeDispatcher replacement in kotlin-coroutine 1.6

### ISSUE THREAD

**Issue by gbusiri** [Kotlin/kotlinx.coroutines#3257]
Hello, i want to ask replacement of `pauseDispatcher` and `resumeDispatcher` in coroutines 1.6?

Previously i have code like this:
```
fun methodFunc() {
            isLoading = true
            render() // other logic or ui logic, assume show loading
            launch {
                ... // other logic, assume call some api
                isLoading = false
                render() // this for remove loading
            }
        }
```

and have test like this:
```
@Test
fun testMethodFunc() {
        dispatcher.pauseDispatcher()

        methodFunc() // call method

        AssertTrue(isLoading)

        dispatcher.resumeDispatcher()

        AssertFalse(isLoading)
}
```

It works when using kotlin-coroutine 1.5. Can you give example replacement for 1.6?

Already tried using `StandardTestDispatcher()`, but not works, the test for `AssertTrue(isLoading)` is always failed because code run until the end (state isLoading == false), so how to paused that?

**Comment by dkhalanskyjb** [comment]
Please use StackOverflow or the Kotlin Slack channel for general questions.

Without the complete code, I can't say what goes wrong, but the behavior you're describing shouldn't happen. In any case, try using `StandardTestDispatcher` and this test code:
```kotlin
@Test
fun testMethodFunc() {
        methodFunc() // call method

        AssertTrue(isLoading)

        dispatcher.runCurrent()

        AssertFalse(isLoading)
}
```
