### ISSUE TITLE
Shared mutable state and concurrency﻿ document references obsolete actor

### ISSUE THREAD

**Issue by saied89** [Kotlin/kotlinx.coroutines#3267]
_Shared mutable state and concurrency_ [document](https://kotlinlang.org/docs/shared-mutable-state-and-concurrency.html#actors) references obsolete actor api.

**Comment by qwwdfsad** [comment]
Thanks, we are aware of that. Unfortunately, we are not ready to replace actors just yet, so we are living with that for some time
