### ISSUE TITLE
Kotlin coroutine `.asFlow()` pair with RxJava `.observeOn(AndroidSchedulers.mainThread())` will block app

### ISSUE THREAD

**Issue by fightyz** [Kotlin/kotlinx.coroutines#3271]
This error seems to only appear on my Huawei Honor 10 (COL-AL10 HarmonyOS 2.0.0). The mobile phone(other mobile phones do not) system will stop all the threads of the app after the app has returned to the background for a period of time (more than ten seconds), and when the app returns to the foreground again, the system will continue to run the threads.

case 1: Just use `.asFlow()` in Android without problems:
```kotlin
val observableInterval = Observable.interval(10, TimeUnit.MILLISECONDS)

uiScope.launch {
    observableInterval
        .asFlow()
        .onEach {
            Log.d("jojo", "interval: $it")
        }.launchIn(this)
}
```
![image](https://user-images.githubusercontent.com/1697504/166150039-e5058d03-61bd-4c42-a388-42066a3b4bc7.png)

case 2: But if I use `.observeOn(AndroidSchedulers.mainThread())`, when the app comes back to the foreground, the counter is stopped after emitting a limited number of data, and the whole app is stuck (but no ANR):
```kotlin
val observableInterval = Observable.interval(10, TimeUnit.MILLISECONDS)
		.observeOn(AndroidSchedulers.mainThread())

uiScope.launch {
    observableInterval
        .asFlow()
        .onEach {
            Log.d("jojo", "interval: $it")
        }.launchIn(this)
}
```
![image](https://user-images.githubusercontent.com/1697504/166150226-68a1338c-546d-4b98-a85c-8bb052fcecd5.png)

case 3: If I add `.toFlowable(BackpressureStrategy.LATEST)`, the app behaves like case 1 again:
```kotlin
val observableInterval = Observable.interval(10, TimeUnit.MILLISECONDS)
		.observeOn(AndroidSchedulers.mainThread())

uiScope.launch {
    observableInterval
				.toFlowable(BackpressureStrategy.LATEST)
        .asFlow()
        .onEach {
            Log.d("jojo", "interval: $it")
        }.launchIn(this)
}
```

My dev environment:
System: HarmonyOS 2.0.0
Dependencies:
```groovy
implementation 'androidx.core:core-ktx:1.7.0'
implementation 'androidx.appcompat:appcompat:1.3.0'
implementation 'com.google.android.material:material:1.4.0'
implementation 'androidx.constraintlayout:constraintlayout:2.0.4'
implementation 'org.jetbrains.kotlin:kotlin-stdlib:1.6.21'
implementation 'io.reactivex.rxjava2:rxjava:2.2.21'
implementation 'io.reactivex.rxjava2:rxandroid:2.1.1'
implementation 'org.jetbrains.kotlinx:kotlinx-coroutines-android:1.6.1'
implementation 'org.jetbrains.kotlinx:kotlinx-coroutines-rx2:1.6.1'
```

**Comment by dkhalanskyjb** [comment]
Hi! Sorry, but I don't think there's anything we can do on our side. We don't have special cases for different devices in our code, so it's not us breaking things, and we don't have your device to test any workarounds that we could come up with. The suggested way forward is to go to either the device manufacturer with your question or to Google's Android issue tracker.
