### ISSUE TITLE
[Docs] Suggestion to add Roman's presentation on structured concurrency (Hydra conference) on README

### ISSUE THREAD

**Issue by psteiger** [Kotlin/kotlinx.coroutines#3273]
Hi,

Recently I stumbled upon [this video](https://youtu.be/Mj5P47F6nJg) of Roman Elizarov lecturing on Kotlin coroutines design history up to the introduction to structured concurrency. I found it very educational, and I think this video is much lesser known than the ones currently linked in the README.

Of course there are tons of external resources on Coroutines already, but I believe it would be valuable to include this particular video on the README because 1) it's from Roman, 2) it tells the design history of the library in ways that are probably not available elsewhere in video presentation, and 3) it tells it up to the introduction of structured concurrency, a concept that became central for Kotlin coroutines.

I notice all current videos on README are from KotlinConf, so I'm hoping that the fact that this particular presentation was not in KotlinConf is not an issue.

P.S I'm not affiliated in any way to the conference in question, and  it is not my goal to promote it.

**Comment by qwwdfsad** [comment]
That's a very good suggestion, thank you!

I personally found the lack of historical reasoning very inconvenient, and it's good to have recorded material on this topic, thanks!
