### ISSUE TITLE
Shared flow not collecting

### ISSUE THREAD

**Issue by savatgithub** [Kotlin/kotlinx.coroutines#3276]
In both of the following sample code, the second collect on a shared flow does not start. I'm not sure if I'm missing something or if there is a bug. Please take a look.

Sample # 1
```
runBlocking {
    val scanFlow: Flow<Int> = flow {
        for (i in 1..2) {
            emit(i)
        }
    }.onCompletion {
        emit(3)
    }.shareIn(this, SharingStarted.WhileSubscribed())

    launch {
        println("first scan start")
        scanFlow.takeWhile { it < 3 }.collect { i ->
            println("first scan $i")
            delay(1.seconds)
        }
        println("first scan complete")
    }
    delay(10.milliseconds)
    launch {
        println("second scan start")
        scanFlow.takeWhile { it < 3 }.collect {
            println("second scan $it")
        }
        println("second scan complete")
    }
}
```

Sample # 2
```
runBlocking {
    val scanFlow: Flow<Int> = flow {
        for (i in 1..2) {
            emit(i)
        }
    }.onCompletion {
        emit(3)
    }.shareIn(this, SharingStarted.WhileSubscribed())

    launch {
        println("first scan start")
        scanFlow.takeWhile { it < 3 }.collect { i ->
            println("first scan $i")
            delay(1.seconds)
            println("second scan start")
            scanFlow.takeWhile { it < 3 }.collect {
                println("second scan $it")
            }
            println("second scan complete")
        }
        println("first scan complete")
    }
}
```

**Comment by psteiger** [comment]
If you put some `println` on the `Flow` emissions, you'll see that sometimes, when the second collection starts, the `SharedFlow` already stopped emitting, hence it won't get any emission (as `replay=0`).

The first `collect` will get all emissions because the emissions happen *after* it starts collecting.

```kotlin
val scanFlow: Flow<Int> = flow {
    for (i in 1..2) {
        println("emitting $i")
        emit(i)
    }
}.onCompletion {
    println("onCompletion emitting 3, throwable=$it")
    emit(3)
}.shareIn(this, SharingStarted.WhileSubscribed())
```

```
first scan start                          // first collection starts here, all emissions happen afterwards
emitting 1                                // flow emissions start here
emitting 2
onCompletion emitting 3, throwable=null   // flow emissions end here
first scan 1
second scan start                         // second collection starts here, all emissions already happened
first scan 2
first scan 3
first scan complete
```

**Comment by savatgithub** [comment]
@psteiger - My understanding is that with `SharingStarted.WhileSubscribed`, flow collection should restart. If you remove the delay from first collection then you get the following output.

```
runBlocking {
    val scanFlow: Flow<Int> = flow {
        for (i in 1..2) {
            println("emitting $i")
            emit(i)
        }
    }.onCompletion {
        emit(3)
    }.shareIn(GlobalScope, SharingStarted.WhileSubscribed())

    launch {
        println("first scan start")
        scanFlow.takeWhile { it < 3 }.collect { i ->
            println("first scan $i")
        }
        println("first scan complete")
    }
    delay(100.milliseconds)
    launch {
        println("second scan start")
        scanFlow.takeWhile { it < 3 }.collect {
            println("second scan $it")
        }
        println("second scan complete")
    }
}
```

```
first scan start
emitting 1
emitting 2
first scan 1
first scan 2
first scan complete
second scan start
emitting 1
emitting 2
second scan 1
second scan 2
second scan complete
```

**Comment by savatgithub** [comment]
https://kotlin.github.io/kotlinx.coroutines/kotlinx-coroutines-core/kotlinx.coroutines.flow/share-in.html

> Normal completion of the upstream flow has no effect on subscribers, and the sharing coroutine continues to run. If a strategy like [SharingStarted.WhileSubscribed](https://kotlin.github.io/kotlinx.coroutines/kotlinx-coroutines-core/kotlinx.coroutines.flow/-sharing-started/-companion/-while-subscribed.html) is used, then the upstream can get restarted again.

**Comment by psteiger** [comment]
@savatgithub , `SharingStarted.WhileSubscribed` will make the whole flow restart when there are no collectors collecting anymore. On the first logs I posted, you can see first flow collection *did not* finish when second flow collection started, hence, collection is not restarted.

On your second example, first collection completes *before* second collection starts, so the upstream flow restarts.

```
first scan start                          // first collection starts, all emissions happen afterwards. Sharing is started. # Collectors = 1
emitting 1                                // flow emissions start here
emitting 2
onCompletion emitting 3, throwable=null   // flow emissions end here
first scan 1
second scan start                         // second collection starts, SharedFlow is still sharing and all emissions already happened. Sharing is started. # Collectors = 2
first scan 2
first scan 3
first scan complete                       // first collection ends. Sharing still does not stop because second collection is still waiting for emissions. # Collectors = 1
```

On the above example, even if a third collector appeared after the last line, then flow would not restart, as the second collector started but did not stop.

**Comment by savatgithub** [comment]
@psteiger - Thanks for the clarification. It was not immediately clear from the documentation though, but your clarification makes sense. This appears to be working as designed.

My use case was to create a function that returns a flow. The computation in the function is expensive so I would like to have only one instance of computation active at any time. If computation has ended then it should restart. I think `shareIn` with a non-zero `replay` e.g., `UNLIMITED` should fulfill the use case. Please let me know if you think this may not work.
