### ISSUE TITLE
Add activation/inactivation tracking for broadcast channel

### ISSUE THREAD

**Issue by elizarov** [Kotlin/kotlinx.coroutines#329]
See analysis here: https://github.com/Kotlin/kotlinx.coroutines/issues/258#issuecomment-379522780

TL;DR For various `BroadcastChannel` implementations it is useful to have ability to track `active` (at least one subscriber) and `inactive` (no subscribers) status. We should consider use-cases for it and design a convenient API for them. 

Note, that it does not apply to regular channels which do not have a concept of subscriber. 

This issue is related to #254

**Comment by LouisCAD** [comment]
This would be very useful since it'd allow `LiveData` like channels that could be used in multiplatform projects.

**Comment by elizarov** [comment]
@LouisCAD There is no design yet. You are welcome to suggest your ideas here.

**Comment by SolomonSun2010** [comment]
Can I treat BroadcastChannel  as data-flow variables in Oz-Mozart [https://www.info.ucl.ac.be/~pvr/GeneralOverview.pdf] ?

Data-Driven Concurrency is cool !
see also: 
Building Scalable, Highly Concurrent & Fault Tolerant Systems - Lessons Learned
https://www.slideshare.net/jboner/building-scalable-highly-concurrent-fault-tolerant-systems-lessons-learned?from_action=save

Dataflow Concurrency
• Deterministic
• Declarative
• Data-driven
• Threads are suspended until data is available
• Lazy & On-demand
• No difference between:
• Concurrent code
• Sequential code
• Examples: Akka & GPars

**Comment by qwwdfsad** [comment]
Superseded by the same Flow design problem :)
