### ISSUE TITLE
Testing classes which require a CoroutineDispatcher to be injected via constructor

### ISSUE THREAD

**Issue by okycelt** [Kotlin/kotlinx.coroutines#3295]
According to [Best practices for coroutines in Android](https://developer.android.com/kotlin/coroutines/coroutines-best-practices#test-coroutine-dispatcher), we should inject a `CoroutineDispatcher` via constructor so a `TestDispatcher` can be injected in tests.

Before 1.6.0, we often used to create the tested object in a `@Before` function shared by all tests where we injected a `TestCoroutineDispatcher` from a rule. Does it mean that we shouldn't do that anymore starting 1.6.0 and it's now recommended to create a new `*TestDispatcher` from a `runTest` scope's `testScheduler` in every test? It works but it seems like copy-pasting a lot of code.

This is the sample test from the "best practices" website.
```kotlin
class ArticlesRepositoryTest {

    @Test
    fun testBookmarkArticle() = runTest {
        // Pass the testScheduler provided by runTest's coroutine scope to
        // the test dispatcher
        val testDispatcher = UnconfinedTestDispatcher(testScheduler)

        val articlesDataSource = FakeArticlesDataSource()
        val repository = ArticlesRepository(
            articlesDataSource,
            testDispatcher
        )
        val article = Article()
        repository.bookmarkArticle(article)
        assertThat(articlesDataSource.isBookmarked(article)).isTrue()
    }
}
```

Thanks in advance

**Comment by dkhalanskyjb** [comment]
Please use the public Slack channel for general questions.

In essence, that section refers to injecting a test dispatcher as opposed to not injecting them at all. Using a Rule to inject a test dispatcher is perfectly fine.
