### ISSUE TITLE
target linux / native removes all suspend fun

### ISSUE THREAD

**Issue by julianhille** [Kotlin/kotlinx.coroutines#3296]
Neither shared nor static libs include any functions declared as `suspend fun`.
(the cpp temporary source code neither).
Currently used dispatcher is `Dispatcher.Default` is there something i could do about it or is it just not implemented?

Thanks.

**Comment by qwwdfsad** [comment]
Sorry, it's not clear what exactly you are trying to achieve, could you please elaborate on it with a bit more details or code examples?

**Comment by julianhille** [comment]
Im having a project which uses `suspend fun test ...`. 
These functions are usable on ios and android BUT when compiled to native linuxx64 (shared or static lib) the function `test` is not in the temporary build cpp code and neither does it exist in the compiled static/shared lib.

**Comment by julianhille** [comment]
Some sample code given:

```
internal class Client(
       private val user: User
) {
   
   suspend fun login (username: String, password: String) {
     // do the actual work
   }

   fun logout () {
     // do the actual work
   }
   
} 
```

Sample linking / building:

```
kotlin {
    linuxX64 {
        binaries {
            staticLib(listOf(DEBUG, RELEASE)) {
                // Binary configuration.
                baseName = "libdemo-static"
                linkerOpts("-L/usr/lib/x86_64-linux-gnu/", "-L/usr/local/lib/")
            }
            sharedLib(listOf(DEBUG, RELEASE))  {
                // Binary configuration.
                baseName = "libdemo-sharedLib"
                linkerOpts("-L/usr/lib/x86_64-linux-gnu/", "-L/usr/local/lib/")
            }
        }
    }
}

```

After compiling this into a binary lib on linux it gives me a lib and a header file.


```

deeply nested structs: .... 
struct {
        libdemo_sharedLib_KType* (*_type)(void);
        void (*logout)(libdemo_sharedLib_kref_org_domain_subdomain_Client thiz);
} Client;
```


Please see that the login function is missing.
There are no linker errors, there are no compile errors.
I can use the the lib just fine in another cpp / c project but it just misses crucial functions.

All these functions have in common that they are suspended coroutine functions.

**Comment by qwwdfsad** [comment]
Unfortunately, it is impossible to export `suspend` functions for plain C/C++, only for Objective-C.

**Comment by julianhille** [comment]
So this ever will be implemented that it is using threads a threadpool or something? 
Closing would mean for me that this is intended behaviour am o correctly assuming this?

Are there any other workarounds, besides extending every and all functions/classes and remove the suspending?

**Comment by julianhille** [comment]
Thank you for your explanation. I suggest to add it to the documentation somewhere. Took me some time.tp figure that out.

**Comment by julianhille** [comment]
Thank you for your explanation. I suggest to add it to the documentation somewhere. Took me some time to figure that out.
