### ISSUE TITLE
Can we remove @FlowPreview yet?  

### ISSUE THREAD

**Issue by martymiller** [Kotlin/kotlinx.coroutines#3310]
I've had this annotation in my code for what seems like two years.  How is it not stable yet?

**Comment by hoc081098** [comment]
related to #3097

**Comment by martymiller** [comment]
Just wanted to share that I added this to my app level `build.gradle.kts` (inside of the android { })

```
  tasks.withType<org.jetbrains.kotlin.gradle.tasks.KotlinCompile>().all {
    kotlinOptions.freeCompilerArgs += listOf(
      "-Xopt-in=kotlin.RequiresOptIn",
      "-Xopt-in=kotlin.OptIn",
      "-Xopt-in=kotlinx.coroutines.ExperimentalCoroutinesApi",
      "-Xopt-in=kotlinx.coroutines.ObsoleteCoroutinesApi",
      "-Xopt-in=kotlinx.coroutines.FlowPreview"
    )
  }
```
This allowed me to remove all the annotations in my code without any complaints from the IDE.  When FlowPreview is eventually removed, I can just remove it from here.

**Comment by albertocavalcante** [comment]
Is there any update on this one (or should it be continued on https://github.com/Kotlin/kotlinx.coroutines/issues/3097)? Thanks

**Comment by qwwdfsad** [comment]
The update will arrive around 1.7.0 release

**Comment by albertocavalcante** [comment]
@qwwdfsad Thanks for the quick response!

**Comment by qwwdfsad** [comment]
A very few API are left as `@FlowPreview`, and they are left so intentionally, so closing this one
