### ISSUE TITLE
"delay" not working with kotlin.incremental.js.ir

### ISSUE THREAD

**Issue by robertfmurdock** [Kotlin/kotlinx.coroutines#3319]
Noticed this in a few projects with Kotlin 1.7.0, but this error is produced when using JS IR + incremental:

`ReferenceError: delay is not defined`

Likely more of a bug in the compiler than the project persay, but it does block being able to use coroutines with this feature.

Related to compiling to Javascript with  IR and `kotlin.incremental.js.ir` enabled.

**Comment by AlexK0** [comment]
It is very possible. I would be very grateful if you share a link to the project, where the issue could be reproduced.

**Comment by qwwdfsad** [comment]
https://youtrack.jetbrains.com/issue/KT-53063/KJS-IR-IC-undefined-reference-for-suspend-functions-in-cross-module-references 

It's a compiler bug that also will be fixed in 1.7.20
