### ISSUE TITLE
Memory leak with new memory model and withTimeout

### ISSUE THREAD

**Issue by qwwdfsad** [Kotlin/kotlinx.coroutines#3351]
See https://youtrack.jetbrains.com/issue/KTOR-4298 for details.

The root cause is our dispatcher implementation:

```

override fun invokeOnTimeout(timeMillis: Long, block: Runnable, context: CoroutineContext): DisposableHandle {
    // No API to cancel on timeout
    worker.executeAfter(timeMillis.toMicrosSafe()) { block.run() }
    return NonDisposableHandle
}
```

Yet it can be workarounded by carefully replacing lambda with something holding an atomic reference to a `block` so it can be nulled out

**Comment by alexvas** [comment]
Would you please publish `1.6.4-native-mt` library version to Maven Central then?

**Comment by qwwdfsad** [comment]
The issues and the fix are related to regular versions of coroutine, the fix is not applicable for `-native-mt` versions
