### ISSUE TITLE
CommonPool possibly not scheduling fair in some cases

### ISSUE THREAD

**Issue by matejdro** [Kotlin/kotlinx.coroutines#337]
I have set up this little test case that measures difference between order of `launch` calls and order of actual launched code being executed:

```kotlin
fun main(args: Array<String>) = runBlocking {
    val job = Job()
    val scheduledIndexCounter = AtomicInteger(0)

    repeat(100000) { launchedIndex ->
        launch(CommonPool, parent = job) {
            val scheduledIndex = scheduledIndexCounter.getAndIncrement()

            val diff = scheduledIndex - launchedIndex
            if (abs(diff) > 20) {
                println("Big diff detected: $launchedIndex -> $scheduledIndex ($diff)")
            }
        }
    }

    job.joinChildren()
}
```

Now I understand that strict sequential scheduling is impossible in multithreaded world, that is why I do not print out small differences < 20, However outputs like this are not uncommon:

> Big diff detected: 16775 -> 16815 (40)
> Big diff detected: 17434 -> 17558 (124)
> Big diff detected: 17433 -> 17583 (150)
> Big diff detected: 17432 -> 17622 (190)
> Big diff detected: 17431 -> 17761 (330)
> Big diff detected: 73587 -> 74402 (815)
> Big diff detected: 76000 -> 76025 (25)
> Big diff detected: 78765 -> 78912 (147)
> Big diff detected: 79439 -> 80153 (714)
> Big diff detected: 79191 -> 81236 (2045)
> Big diff detected: 88781 -> 88825 (44)
> Big diff detected: 91218 -> 91251 (33)
> Big diff detected: 95040 -> 95085 (45)
> Big diff detected: 94555 -> 95813 (1258)
> Big diff detected: 77404 -> 99998 (22594)
> Big diff detected: 95695 -> 99999 (4304)
> Big diff detected: 95696 -> 99997 (4301)

Above output means that some tasks got executed several thousand tasks later than they were supposed to. This was ran on i7 2600K CPU with 4 cores / 8 threads.

Is that a bug or actual expected behavior? I would personally think that scheduler is supposed to schedule all tasks approximately in the same order than they were launched.

**Comment by qwwdfsad** [comment]
Yes, this is expected behaviour. By default FJP schedules task in its local queue, so fairness is not guaranteed and tries to steal tasks when its queue is empty.

Moreover, incoming coroutine scheduler will be unfair as well, because coroutines are extremely sensitive to task locality and execution order

**Comment by matejdro** [comment]
Thanks for the answer. Looks like this is done then.
