### ISSUE TITLE
`delay(0.seconds)` does not check for cancellation

### ISSUE THREAD

**Issue by dziemborowicz** [Kotlin/kotlinx.coroutines#3373]
The `delay` function claims to provide a prompt cancellation guarantee, but, if the duration passed to `delay` is `0`, the function simply returns without doing anything and, in particular, without checking for cancellation.

Should this function be updated to check for cancellation even in the case where it does not suspend so that it guarantees that it never returns successfully if the job was cancelled before it was called?

Or, if not, should the documentation [here](https://kotlinlang.org/api/kotlinx.coroutines/kotlinx-coroutines-core/kotlinx.coroutines/delay.html) be updated to note that `delay` does not check for cancellation if the duration is not strictly positive?

**Comment by qwwdfsad** [comment]
`delay` behaves exactly according to its documentation: 

>If the job was cancelled **while this function was suspended**, it will not resume successfully

This is the default behaviour of most of our primitives -- cancellation is "checked" only during actual suspension for the sake of performance.

Could you please elaborate on whether you spotted it accidentally or if there was an actual production-driven use-case for that?
