### ISSUE TITLE
CoroutineExceptionHandler not invoked when used with TestScope

### ISSUE THREAD

**Issue by carterhudson** [Kotlin/kotlinx.coroutines#3374]
I can't get a `CoroutineExceptionHandler` to be invoked in the fashioned outlined [in the migration guide](https://github.com/Kotlin/kotlinx.coroutines/blob/master/kotlinx-coroutines-test/MIGRATION.md#remove-usages-of-testcoroutineexceptionhandler-and-testcoroutinescopeuncaughtexceptions). 

Coroutines version: 1.6.2

Here's a simple example I would expect to work:
```kotlin
@Test
fun `test`() = runTest {
    val capturedExceptions = mutableListOf<Throwable>()

    exceptionHandler = CoroutineExceptionHandler { _, e ->
        capturedExceptions.add(e)
    }

    launch(exceptionHandler) {
        throw Throwable("a")
    }

    advanceUntilIdle()

    assertThat(capturedExceptions).isNotEmpty() // It's empty :(
}
```

**Comment by dkhalanskyjb** [comment]
Please use the Kotlin Slack channel for general questions. `CoroutineExceptionHandler` is only for exceptions that the coroutine machinery can't propagate upwards. Those are fairly rare now. This exception will be propagated to the coroutine behind `TestScope` and fail the test.

**Comment by carterhudson** [comment]
I didn't think it was a general question. It seemed that, according to the migration guide, this should work.

**Comment by dkhalanskyjb** [comment]
The term "uncaught exceptions" is fairly specific in coroutines: https://kotlinlang.org/docs/exception-handling.html#coroutineexceptionhandler

**Comment by TomekJurkowski** [comment]
@carterhudson did you find an explanation, why the CoroutineExceptionHandler is not invoked in the runTest block? I am struggling with the exact same issue and was wondering if you found some solution

**Comment by carterhudson** [comment]
> @carterhudson did you find an explanation, why the CoroutineExceptionHandler is not invoked in the runTest block? I am struggling with the exact same issue and was wondering if you found some solution

For this particular scenario, I had to stop using `runTest` and `TestScope`, and instead do something like:
```kotlin
    @Test
    fun `some_test`() {
        val testDispatcher = StandardTestDispatcher()
        val scope = CoroutineScope(testDispatcher)
        val throwError = suspend { throw Exception() }
        var caught: Throwable? = null
        val handler = CoroutineExceptionHandler { coroutineContext, throwable ->
            caught = throwable
        }
        scope.launch(handler) {
            throwError()
        }
        testDispatcher.runCurrent()
        assertThat(caught).isNotNull()
    }
```

**Comment by TomekJurkowski** [comment]
thank you, appreciate the help !!

**Comment by dkhalanskyjb** [comment]
The proposed approach is very hacky and can break in subtle ways in more complex scenarios, we certainly don't recommend doing this. Instead, if for some reason you don't want the exceptions to be propagated upwards to `runTest`, break the chain of inheritance between coroutines:

```kotlin
    @Test
    fun testNotPropagatingExceptions() = runTest {
        var caught: Throwable? = null
        val throwable = Exception()
        val handler = CoroutineExceptionHandler { _, exception ->
            caught = exception
        }
        launch(NonCancellable + handler) {
            throw throwable
        }
        runCurrent()
        assertEquals(throwable, caught)
    }
```

Using `NonCancellable` is the key here, as it destroys the inheritance relationship.

Also, to reiterate, the Kotlin Slack channel is just the place for this kind of discussion. There are savvy people there who also could recommend a good approach.
