### ISSUE TITLE
Volatile `previousKey` in `Flow<T>.distinct()` operator

### ISSUE THREAD

**Issue by AChep** [Kotlin/kotlinx.coroutines#3377]
Looking at the implementation of the `Flow<T>.distinct()`:

```kotlin
private class DistinctFlowImpl<T>(
    private val upstream: Flow<T>,
    @JvmField val keySelector: (T) -> Any?,
    @JvmField val areEquivalent: (old: Any?, new: Any?) -> Boolean
): Flow<T> {
    override suspend fun collect(collector: FlowCollector<T>) {
        var previousKey: Any? = NULL
        upstream.collect { value ->
            val key = keySelector(value)
            @Suppress("UNCHECKED_CAST")
            if (previousKey === NULL || !areEquivalent(previousKey, key)) {
                previousKey = key
                collector.emit(value)
            }
        }
    }
}
```

where the `previousKey` on JVM is internally wrapped with

```java
    public static final class ObjectRef<T> implements Serializable {
        public T element;

        @Override
        public String toString() {
            return String.valueOf(element);
        }
    }
```

I wonder why the `element` is not declared as `volatile`. If I understood correctly, `collect` block might be called on different threads and therefore the `previousKey` might have a different cached value per thread.

**Comment by dkhalanskyjb** [comment]
Sure, the block may be executed on different threads, but the internal coroutines machinery does the job of `volatile` here: https://stackoverflow.com/questions/58518783/kotlin-coroutines-happens-before-guarantees
