### ISSUE TITLE
Small Dispatchers.Main documentation inaccuracies with the new MM

### ISSUE THREAD

**Issue by BoD** [Kotlin/kotlinx.coroutines#3381]
On the [doc for the Main dispatcher](https://kotlinlang.org/api/kotlinx.coroutines/kotlinx-coroutines-core/kotlinx.coroutines/-dispatchers/-main.html) it says:
- _"On JS and Native it is equivalent to the Default dispatcher."_, which unless I'm mistaken is no longer true with the new MM (at least on Apple I can confirm that Default and Main are not the same)
- _"MainCoroutineDispatcher.immediate is not supported on the Native platform"_ again it looks like it's no longer true with the new MM

Of course I understand that the doc may not want to be too "new MM specific" as it is still experimental. Maybe the differences can be noted explicitly.

**Comment by dkhalanskyjb** [comment]
Good point, we should change the docs, especially given that we're dropping support for the old memory model.
