### ISSUE TITLE
Coroutines "Select expression" docs page is inaccurate

### ISSUE THREAD

**Issue by awoSYS** [Kotlin/kotlinx.coroutines#3385]
Hi! I'm no Kotlin expert, just noticed a confusing detail on the [Select expression](https://kotlinlang.org/docs/select-expression.html#selecting-from-channels) docs page:

There's a runnable example, which, when clicking on the play button, produces output:

```
fizz -> 'Fizz'
buzz -> 'Buzz!'
fizz -> 'Fizz'
fizz -> 'Fizz'
buzz -> 'Buzz!'
fizz -> 'Fizz'
fizz -> 'Fizz'
```

Which looks in line with the contents of the docs page so far. However, the page states:

"The result of this code is:

```
fizz -> 'Fizz'
buzz -> 'Buzz!'
fizz -> 'Fizz'
fizz -> 'Fizz'
buzz -> 'Buzz!'
fizz -> 'Fizz'
buzz -> 'Buzz!'
```
"

Note the last line. 

Looks like a typo to me, since at the 7th execution, `fizz()` should take precedence, right?

**Comment by qwwdfsad** [comment]
Thanks for spotting!
