### ISSUE TITLE
kotlin should be defined as a peer dependency to kotlinx-coroutines-core

### ISSUE THREAD

**Issue by ansman** [Kotlin/kotlinx.coroutines#339]
Currently kotlin is defined as a regular dependency which means that it's not using the same runtime as your app module and things like `instanceof` might not work as expected.

**Comment by LouisCAD** [comment]
Does this issue only strike in KotlinJS?

**Comment by ansman** [comment]
Yes, on Java and Android there is only a single classpath so you cannot have multiple versions of the same library.
