### ISSUE TITLE
Unresolved reference: "launch"

### ISSUE THREAD

**Issue by Skullper** [Kotlin/kotlinx.coroutines#34]
I was using "org.jetbrains.kotlinx:kotlinx-coroutines-core:0.11-rc" and everything was okey just warning that coroutines is experimental.
Now I have updated kotlin plugin to 1.1.0 and change coroutines dependency to "compile 'org.jetbrains.kotlinx:kotlinx-coroutines-core:0.12'" from your README. And now my AndroidStudio cannot see coroutines. I have unresolve reference error.
What I am doing wrong?

**Comment by elizarov** [comment]
Can you, please, give more details on your project details or the error

**Comment by Skullper** [comment]
Sorry for bothering you. It was my studio lag. I did invalidate and restart and issue disappears.
But now I have another issue. I have warning popup after each gradle sync. 
![screenshot from 2017-03-02 08-52-57](https://cloud.githubusercontent.com/assets/3677314/23496257/d22634d4-ff25-11e6-88ec-97c275511572.png)
How can I rid of it?

**Comment by elizarov** [comment]
Can you, please, file a bug about "Configure Kotlin" to http://kotl.in/issue with details on your project setup (what versions of graddle, Android studio and kotlin plugin you are using and how your graddle project is set up).

**Comment by Skullper** [comment]
Done. With images and gradle files there

**Comment by lostpebble** [comment]
I'm having the same problem.

Not using Gradle, just started a basic Kotlin project. Here's a screen showing my setup and the errors:
![coroutines_problem](https://cloud.githubusercontent.com/assets/1508863/23520993/d6064d9a-ff85-11e6-9634-7151b3bd47ea.jpg)

Haven't used co-routines before in Kotlin, but just trying out this first example is giving me trouble. As you can see, I'm using the recently released 1.1.

**Comment by Skullper** [comment]
@lostpebble Have you added a coroutines dependency? I haven't seen any gradle files. Kotlin projects don't need them?(I have used kotlin only for android projects)

**Comment by lostpebble** [comment]
Well, I'm importing the coroutines package from Kotlin at the top there. Thought that stuff would all come standard with the 1.1 release and updating the package. The package itself is there but the `launch` function doesn't seem to be under `kotlin.coroutines.experimental`

**Comment by Skullper** [comment]
Check README: https://github.com/Kotlin/kotlinx.coroutines

**Comment by lostpebble** [comment]
Ahh, okay all working now. Sorry, just came from another site straight to the guide- noticed that `launch` was in the `kotlinx.coroutines.experimental` package, which comes with 1.1 and was wondering why it wasn't resolving.

Perhaps indicate in the guide that the `kotlinx-coroutines-core` module is needed on top of the regular Kotlin coroutines module.

**Comment by elizarov** [comment]
Fixed now. The guide now includes the notice about setup in the beginning: https://github.com/Kotlin/kotlinx.coroutines/blob/master/coroutines-guide.md

**Comment by Skullper** [comment]
Oh! It's really cool
