### ISSUE TITLE
Call suspend function in java not working sometimes.

### ISSUE THREAD

**Issue by NamekMaster** [Kotlin/kotlinx.coroutines#3401]
I'm working on a SDK project for both Java & Kotlin, the API exposed as suspend function. In Java the suspend function become callback way with `Continuation`, so we encapsulate it like that:

```kotlin
abstract class Callback<in T> : kotlin.coroutines.Continuation<T> {
    private val scope = CoroutineScope(SupervisorJob() + Dispatchers.Main.immediate)
    abstract fun onSuccess(value: T)
    abstract fun onFailure(t: Throwable)
    override val context: CoroutineContext
        get() = scope.coroutineContext
    fun cancel() {
        scope.cancel()
    }
    override fun resumeWith(result: Result<T>) = result.fold(this::onSuccess, this::onFailure)
```

The API looks like this:
```kotlin
interface Api {
  suspend fun getFoo(): String
}
```

The caller could leverage the `Callback` to call suspend function in java as shown below:

```java
api.getFoo(new Callback {
  public void onSuccess(T t) {}
  public void onFailue(Throwable t) {}
})
```

In Java it become this:
```java
public Object getFoo(Continuation<String> c)
```

The problem happened when call it in java, if the implementation of `getFoo` is too simple such like return a string, the continuation is not called, it return the result directly as return value.

```kotlin
override suspend fun getFoo(): {
  return "123"
}
```

I known this is weird but for the compatibility purporse, we may add complex logic in the future. so the `suspend` is necessary.

At first we make a workaround by adding `withContext` to ensure the value passed from continuation:

```kotlin
override fun getFoo(): String = withContext(Dispatchers.IO) { "123" }
```

It is working for a long time until we publish the first release version of the SDK, the automation test of QA report that sometime the `Callback` never called both `onSuccess` and `onFaiture`.  They wirte the test code in Java.

I'v made some research but still don't known the reason, and it never faild when we run it on our own computer. What happened under the hood ? Any response is appreciated.

**Comment by fvasco** [comment]
Hi @NamekMaster,
I suppose you are looking for the coroutine specification details, you missed that every `suspend` method return always a value (never `void`), there is the trick.

> When suspending function suspends coroutine, it returns a special marker value of COROUTINE_SUSPENDED (see more in coroutine intrinsics section). When a suspending function does not suspend the current coroutine but continues the coroutine's execution, it returns its result or throws an exception directly.

So you have to add another check, see: https://github.com/Kotlin/KEEP/blob/master/proposals/coroutines.md#implementation-details

My suggestion is to avoid going deep into these implementation details, you can wrap any `suspend fun` to a `CompletableFuture` or a reactive entity (same for `Flow`).

```java
CompletableFuture<String> fooFuture = FutureKt.future(
        GlobalScope.INSTANCE,
        EmptyCoroutineContext.INSTANCE,
        CoroutineStart.DEFAULT,
        (scope, continuation) -> api.getFoo(continuation)
);
```

Here is a simple little Kotlin helper:

```kotlin
fun <T> future(f: suspend () -> T) = GlobalScope.future { f() }
```

so the Java code becomes:

```java
CompletableFuture<String> fooFuture = MySuspendUtil.future((c) -> api.getFoo(c));
```

Or define bridge methods in your Kotlin interfaces:

```kotlin
interface Api {
    suspend fun getFoo(): String
    fun getFooFuture() = GlobalScope.future { getFoo() }
}
```

**Comment by qwwdfsad** [comment]
I second @fvasco suggestion -- for Java consumers it's recommended to expose Java API. Relying on implementation details for Java interop is not the best way due to various potential pitfalls (e.g. fast-path return like in your example, cancellability and so on).
