### ISSUE TITLE
There is no space before word "after" in documetation. 

### ISSUE THREAD

**Issue by brennschlus** [Kotlin/kotlinx.coroutines#3404]
Here is a link to the webpage with punctuation error https://kotlinlang.org/api/kotlinx.coroutines/kotlinx-coroutines-core/kotlinx.coroutines.flow/on-completion.html
https://github.com/Kotlin/kotlinx.coroutines/blob/6cd4ad3c782dce7143b52034b49f1b6900f54d61/kotlinx-coroutines-core/common/src/flow/operators/Emitters.kt#L87
![изображение](https://user-images.githubusercontent.com/41682156/184319069-827e2aaf-2ce2-45f2-83ba-88702ebd6dfc.png)

**Comment by qwwdfsad** [comment]
This is a bug in Dokka that will be fixed someday, see: https://github.com/Kotlin/dokka/issues/2623#issuecomment-1213059862

We'll update our version as soon as it's ready
