### ISSUE TITLE
flatMapLatest doesn't release last emitted item

### ISSUE THREAD

**Issue by ferhatparmak** [Kotlin/kotlinx.coroutines#3422]
When I return an empty flow inside `flatMapLatest`, it still keeps last emitted item from previous flow in memory.

```
   data class Test(val id: Int)
    
    val testFlow = flow {
        emit(Test(1))
        emit(Test(2))
        delay(100000) // keep flow active
    }

    testFlow
        .flatMapLatest {
            if (it.id == 1) {
                flowOf(it)
            } else {
                emptyFlow()
            }
        }
        .collect()
```

After `Test(2)` is emitted and collected, I still see `Test(1)` object in memory when I use the memory profiler on Android Studio. Shouldn't it be garbage collected?

<img width="1002" alt="Screenshot 2022-08-23 at 16 03 08" src="https://user-images.githubusercontent.com/6843349/186178771-a330ae37-a95d-4835-b581-7f8c26137bbe.png">

**Comment by qwwdfsad** [comment]
Thanks! Unfortunately, it is a compiler issue: https://youtrack.jetbrains.com/issue/KT-33986/Null-out-result-field-when-suspending-a-coroutine that eventually be fixed, there is not much we can do on a library side
