### ISSUE TITLE
CommonPool should be configurable to have a minimum number of threads

### ISSUE THREAD

**Issue by svd27** [Kotlin/kotlinx.coroutines#343]
Currently CommonPool sets the number of threads in its pool to 
```max(NumberofCpus - 1,1)```
this leads that on travis a lot of tests are failing for me. it would be nice to have something like a system property: 
```kotlinx.experimental.coroutines.commonpool.minThreads```
which would allow to override that for unit tests

**Comment by fvasco** [comment]
See #261

**Comment by qwwdfsad** [comment]
For tests, it makes sense to provide separate pool and use it, you can see such pattern in our stress tests. `CommonPool` is a singleton, so changing its size via global system variable may be error prone (especially for tests), so I would not recommend that.

Nevertheless, this is a valid issue (e.g. see #321), so we definitely will address it
