### ISSUE TITLE
Async task tagging for Kotlin JS

### ISSUE THREAD

**Issue by CLOVIS-AI** [Kotlin/kotlinx.coroutines#3433]
Chrome is aiming to implement [a `console.createTask()` method](https://developer.chrome.com/en/blog/devtools-modern-web-debugging/#linked-stack-traces) that allows the debugger to link the source of an asynchronous call to its target (e.g. the stacktraces go across asynchronous boundaries).

Coroutine stacktraces is often a pain point, and this sounds similar to the [asynchronous task debugger](https://www.jetbrains.com/help/idea/debug-asynchronous-code.html#39f8c1a7) added in IDEA last year.

Do you think this change is feasible for Kotlin/JS? If so, I believe it could help the debugging experience.

**Comment by qwwdfsad** [comment]
We decided not to spend any significant effort on JS-specific features for coroutines, as demand seem to be quite low.
So any experimental enhancements that can be *potentially* useful in JS-only environments are off the table

**Comment by ScottPierce** [comment]
The Kotlin team doesn't invest in JS because no one uses it. Every time I try to use Kotlin JS, I encounter issues, so I can't use it. JS has to be invested in for people to be able to use it.
