### ISSUE TITLE
CompositeDisposable analog for Job

### ISSUE THREAD

**Issue by Obolrom** [Kotlin/kotlinx.coroutines#3435]
Is there any container class or something like this to store Jobs like CompositeDisposable in RxJava?
It is not a handful to write composite disposable analog for every project. Moreover, it should be thread-safe

**Comment by qwwdfsad** [comment]
There is no need for `CompositeDisposable`, because the parent job (or parent scope) is exactly it.

If it doesn't suit your needs, please elaborate on your particular use-case
