### ISSUE TITLE
Return UnlimitedIoScheduler instance for Dispatchers.IO.limitedParallelism(Int.MAX_VALUE)

### ISSUE THREAD

**Issue by dovchinnikov** [Kotlin/kotlinx.coroutines#3442]
Don't wrap it into `LimitedDispatcher` unnecessarily.

**Comment by qwwdfsad** [comment]
Do we have any evidence that `LimitedDispatcher` overhead is non-eglible or is it rather a "nice to have" enhancement?

**Comment by dovchinnikov** [comment]
I didn't do any measurements, but I'm 100% sure that doing nothing is faster than whatever `LimitedDispatcher` is doing.
