### ISSUE TITLE
Android lint error 1.6.4 - InvalidPackage

### ISSUE THREAD

**Issue by kserno** [Kotlin/kotlinx.coroutines#3444]
I saw the following issues got resolved: #3277 and #2004 got resolved but using coroutines version 1.6.4 still has this bug
```
/Users/filipsollar/.gradle/caches/modules-2/files-2.1/org.jetbrains.kotlinx/kotlinx-coroutines-core-jvm/1.6.4/2c997cd1c0ef33f3e751d3831929aeff1390cb30/kotlinx-coroutines-core-jvm-1.6.4.jar: Error: Invalid package reference in org.jetbrains.kotlinx:kotlinx-coroutines-core-jvm; not included in Android: java.lang.instrument. Referenced from kotlinx.coroutines.debug.AgentPremain. [InvalidPackage]
```

**Comment by qwwdfsad** [comment]
This is not an issue on coroutines side, see https://github.com/Kotlin/kotlinx.coroutines/issues/3277#issuecomment-1166565258

The solution is to ignore this warning or disable this particular check
