### ISSUE TITLE
Module with the Main dispatcher had failed to initialize. For tests Dispatchers.setMain from kotlinx-coroutines-test module can be used

### ISSUE THREAD

**Issue by gbaatsen** [Kotlin/kotlinx.coroutines#3454]
I saw [this issue](https://github.com/Kotlin/kotlinx.coroutines/issues/3244) , but no one was able to provide a good example of the issue. I wanted to provide it, but since the issue is now closed, here's a new one, using coroutines-test:1.6.4.
This the repo: https://github.com/gbaatsen/cortest

I have isolated the issue from our main project that I cannot share for obvious reasons. So this project doesn't really do anything, it is just to reproduce the problem. When you run the ConsentDetailViewModelTest we get the message `Exception in thread "Test worker @coroutine#3" java.lang.IllegalStateException: Module with the Main dispatcher had failed to initialize. For tests Dispatchers.setMain from kotlinx-coroutines-test module can be used
`
What can be the problem here?

**Comment by dkhalanskyjb** [comment]
`org.junit.Rule` is part of JUnit 4, but `Test` etc are from JUnit 5. So, `mainDispatcherRule` does not get used at all.

**Comment by yeeun-yun97** [comment]
Hi there I am facing MainDispatcher Couroutine in unit test Problem now. Is there any solution to avoid this? 

I got solutions from stackoverflow, but Dispatchers.setMain( StandardTestDispatcher()) was not finishing. and Dispatchers.setMain(Dispatchers.Unconfined) throws exception. 

your github link repo is returning 404 now, for reference.

**Comment by 4lfg24** [comment]
I've recreated the issue he is talking about, more or less, here's the repo: [https://github.com/4lfg24/stopwatch-app](https://github.com/4lfg24/stopwatch-app)

**Comment by dkhalanskyjb** [comment]
@4lfg24, the project you linked does not even use the test module.
