### ISSUE TITLE
Coroutines doesn't run two tasks in parallel.

### ISSUE THREAD

**Issue by tianyirenjian** [Kotlin/kotlinx.coroutines#3457]
I tried launch two jobs fetch two url in the same time.

```kotlin
fun main() = runBlocking {
    val totalT = measureTimeMillis {
        val jobs = launch {
            launch {
                val j1T = measureTimeMillis {
                    getWebContent("https://api.kotlinlang.org/abc")
                }
                println("j1T is $j1T")
            }
            launch {
                val j2T = measureTimeMillis {
                    getWebContent("https://www.notexistswebsite.com/")
                }
                println("j2T is $j2T")
            }
        }
        jobs.join()
    }
    println("totalT is $totalT")
}

fun getWebContent(url: String): String? {
    try {
        val conn = URL(url).openConnection() as HttpURLConnection
        return if (conn.responseCode >= 200 && conn.responseCode <= 399) {
                String(conn.inputStream.readBytes(), Charsets.UTF_8)
        } else {
            String(conn.errorStream.readBytes(), Charsets.UTF_8)
        }
    } catch (e: Exception) {
        return e.message
    }
}

```
The result is always job1 take more time than job2, but it alway print "j1T is xxx" first. And totalT is bigger than j1T plus j2T.

like this:

```
j1T is 567
j2T is 315
totalT is 906

or

j1T is 323
j2T is 6
totalT is 371
```

I think , if these two tasks run in parallel, the j2T should print before j1T, and totalT should smaller than j1T plus j2T.

If I replace call getWebContent() function with delay() function, the code runs well.

The runable code is here: [play.kotlinlang.org](https://pl.kotl.in/uh0psAKz-)

**Comment by qwwdfsad** [comment]
Please refer to `runBlocking` documentation:

> The default [CoroutineDispatcher] for this builder is an internal implementation of event loop that processes continuations
 in this blocked thread until the completion of this coroutine.

The behaviour is expected, you can specify `Dispatchers.Default` for your `launch` subroutines to make them run in parallel.
