### ISSUE TITLE
async (CommonPool) do not work with the emulator Android 5, 6

### ISSUE THREAD

**Issue by sergfirago** [Kotlin/kotlinx.coroutines#346]
async (CommonPool) do not work with the emulator Android 5, 6
I tested the following APIs - 16, 21, 22, 23,  27. Emulated performans Multi-Core CPU = 2
```kotlin

class MainActivity : AppCompatActivity() {
    private val version = android.os.Build.VERSION.RELEASE
    private val LOG_TAG = "CoroutineTest"

    override fun onCreate(savedInstanceState: Bundle?) {
        super.onCreate(savedInstanceState)
        setContentView(R.layout.activity_main)

        Log.d(LOG_TAG, "main thread v$version [${Thread.currentThread().name}]")

        test(CommonPool)

        val nThreads = (Runtime.getRuntime().availableProcessors() - 1).coerceAtLeast(1)
        val poolDispatcher = newFixedThreadPoolContext(nThreads, "FixedPool")
        test(poolDispatcher)
    }

    private fun test(dispatcher: CoroutineDispatcher) {

        launch(dispatcher) {
            Log.d(LOG_TAG, "launch test v$version [${Thread.currentThread().name}]")
        }
        async(dispatcher) {
            Log.d(LOG_TAG, "async test v$version [ ${Thread.currentThread().name}]")
        }
    }
}
```
Result
04-24 18:28:49.151 2392-2392/com.firago.serg.myapplicationcoroutine D/CoroutineTest: main thread v4.1.2 [main]
04-24 18:28:49.151 2392-2405/com.firago.serg.myapplicationcoroutine D/CoroutineTest: launch test v4.1.2 [CommonPool-worker-1]
    async test v4.1.2 [ CommonPool-worker-1]
04-24 18:28:49.161 2392-2433/com.firago.serg.myapplicationcoroutine D/CoroutineTest: launch test v4.1.2 [FixedPool]
    async test v4.1.2 [ FixedPool]

04-24 18:30:30.169 5119-5119/com.firago.serg.myapplicationcoroutine D/CoroutineTest: main thread v5.0.2 [main]
04-24 18:30:30.174 5119-5138/com.firago.serg.myapplicationcoroutine D/CoroutineTest: launch test v5.0.2 [FixedPool]
    async test v5.0.2 [ FixedPool]

04-24 18:32:03.973 6949-6949/com.firago.serg.myapplicationcoroutine D/CoroutineTest: main thread v5.1.1 [main]
04-24 18:32:03.986 6949-6976/com.firago.serg.myapplicationcoroutine D/CoroutineTest: launch test v5.1.1 [FixedPool]
    async test v5.1.1 [ FixedPool]

04-23 21:33:45.102 4999-4999/com.firago.serg.myapplicationcoroutine D/CoroutineTest: main thread v6.0 [main]
04-23 21:33:45.135 4999-5041/com.firago.serg.myapplicationcoroutine D/CoroutineTest: launch test v6.0 [FixedPool]
    async test v6.0 [ FixedPool]

04-24 18:36:22.178 5041-5041/com.firago.serg.myapplicationcoroutine D/CoroutineTest: main thread v8.1.0 [main]
04-24 18:36:22.203 5041-5163/com.firago.serg.myapplicationcoroutine D/CoroutineTest: launch test v8.1.0 [FixedPool]
    async test v8.1.0 [ FixedPool]
04-24 18:36:22.206 5041-5162/com.firago.serg.myapplicationcoroutine D/CoroutineTest: launch test v8.1.0 [ForkJoinPool.commonPool-worker-1]
    async test v8.1.0 [ ForkJoinPool.commonPool-worker-1]

**Comment by qwwdfsad** [comment]
I can't reproduce it on my machine (using the latest android studio and 0.22.5 coroutines).
Could you please provide full thread dump and `ForkJoinPool.commonPool().toString()` on devices where tasks are not executed in CommonPool?

**Comment by sergfirago** [comment]
In build.gradle
```
minSdkVersion 15
targetSdkVersion 27
implementation "org.jetbrains.kotlinx:kotlinx-coroutines-android:0.22.5"
```
ext.kotlin_version = '1.2.40'

In my project 

ForkJoinPool.commonPool().toString() return "java.util.concurrent.ForkJoinPool@3328e0bb[Running, parallelism = 0, size = 0, active = 0, running = 0, steals = 0, tasks = 0, submissions = 2]"
But ForkJoinPool().toString() = java.util.concurrent.ForkJoinPool@221fd7b9[Running, parallelism = 1, size = 0, active = 0, running = 0, steals = 0, tasks = 0, submissions = 0]

If I replace ForkJoinPool.commonPool() by ForkJoinPool() in CommonPool. 
```kotlin
object CommonPool ... {
...
   private fun createPool()  = ForkJoinPool() 
...
```
then tasks are executed in CommonPool.
Cause of error in ForkjoinPool.
Thank.
