### ISSUE TITLE
delay(0L) cannot be canceled

### ISSUE THREAD

**Issue by TianJieYouYue** [Kotlin/kotlinx.coroutines#3469]
In Java, Thread.sleep(0) as a safepoint to pause running, kotlinx.coroutines delay(0L) seems not work.
And delay(1L) time too long.

**Comment by qwwdfsad** [comment]
`delay(0L)` is not expected to be used like a safepoint.

If you are willing to check cancellation status and throw an exception, we have a dedicated `ensureActive` for that
