### ISSUE TITLE
Invalid links in the documentation

### ISSUE THREAD

**Issue by NorbertSandor** [Kotlin/kotlinx.coroutines#3484]
404 links:

| Page | Link text | Link target (invalid) |
| --- | --- | --- |
| /CHANGES.md | here | native/README.md |
| /CHANGES.md | Guide to reactive streams with coroutines | reactive/coroutines-guide-reactive.md |
| /CHANGES.md | Guide to reactive streams with coroutines | reactive/coroutines-guide-reactive.md |
| /CHANGES.md | Guide to reactive streams with coroutines | reactive/coroutines-guide-reactive.md |
| /docs/topics/debug-coroutines-with-idea.md | create one | jvm-get-started.md#create-a-project |
| /docs/topics/debug-flow-with-idea.md | create one | jvm-get-started.md#create-a-project |
| /integration/README.md | site/docs/index.md | ../site/docs/index.md |
| /integration/README.md | here | ../knit/README.md#usage |

**Comment by dkhalanskyjb** [comment]
> /docs/topics/debug-coroutines-with-idea.md
> /docs/topics/debug-flow-with-idea.md

The purpose of these links is to integrate with the website, where they work properly: https://kotlinlang.org/docs/debug-coroutines-with-idea.html

> /integration/README.md

Yes, thanks!

> CHANGES.md

The links there are no longer relevant given the current state of the project, and if someone uses those older versions, they can checkout the old contents of the repository.
