### ISSUE TITLE
Confusing / Invalid documentation of default dispatcher used in "launch" api

### ISSUE THREAD

**Issue by sidsharma2002** [Kotlin/kotlinx.coroutines#3490]
Current resources and documentation is inconsistent about on what dispatcher does a simple ```viewModelScope.launch {}``` runs on. 
I can see that the documentation says that the default dispatcher used is Dispatchers.Default 
 
<img width="687" alt="Screenshot 2022-10-19 at 1 33 35 PM" src="https://user-images.githubusercontent.com/53833109/196633007-59df0b78-a930-497a-b16f-2f9a0141c6fd.png">

but this is a code lab that mentions that by default coroutine is launched on Dispatchers.Main

``` Since viewModelScope has a default dispatcher of Dispatchers.Main, this coroutine will be launched in the main thread. We'll see later how to use different threads. ``` taken from https://developer.android.com/codelabs/kotlin-coroutines#4

I also found a stackoverflow which also mentions that default dispatcher used is Dispatchers.Main : 
 https://stackoverflow.com/questions/62166878/why-does-viewmodelscope-launch-run-on-the-main-thread-by-default
 
ps : let me know if I can also look towards contributing about the same to the documentation.

**Comment by dkhalanskyjb** [comment]
The documentation says that `Dispatchers.Default` is used if no other dispatcher is present in the context. `viewModelScope.coroutineContext` contains `Dispatchers.Main.immediate`, so `Dispatchers.Default` is not used in case of `viewModelScope`.
