### ISSUE TITLE
BlockHound false positive in BlockingCoroutine.joinBlocking

### ISSUE THREAD

**Issue by OliverO2** [Kotlin/kotlinx.coroutines#3492]
org.jetbrains.kotlinx:kotlinx-coroutines-core:1.6.4

Relevant stack trace excerpt:

```text
Caused by: reactor.blockhound.BlockingOperationError: Blocking call! jdk.internal.misc.Unsafe#park
	at java.base@11.0.16/jdk.internal.misc.Unsafe.park(Unsafe.java)
	at java.base@11.0.16/java.util.concurrent.locks.LockSupport.parkNanos(LockSupport.java:234)
	at app//kotlinx.coroutines.BlockingCoroutine.joinBlocking(Builders.kt:88)
	at app//kotlinx.coroutines.BuildersKt__BuildersKt.runBlocking(Builders.kt:59)
	at app//kotlinx.coroutines.BuildersKt.runBlocking(Unknown Source)
	at app//kotlinx.coroutines.BuildersKt__BuildersKt.runBlocking$default(Builders.kt:38)
	at app//kotlinx.coroutines.BuildersKt.runBlocking$default(Unknown Source)
```

**Comment by lowasser** [comment]
This looks like a problem with BlockHound, not kotlinx.coroutines, but -- from the stack trace, this certainly reads like a true positive; `runBlocking` is, indeed, a blocking call.

**Comment by OliverO2** [comment]
Is this any different from, say, #2937? Please elaborate.

**Comment by dkhalanskyjb** [comment]
I don't think that's a false positive. For example, code like
```kotlin
runBlocking {
  withContext(Dispatchers.IO) {
    Thread.sleep(1)
  }
}
```
will not trigger BlockHound, so `BlockingCoroutine` in general works as intended. `BlockingCoroutine` will call `joinBlocking` if it has to await child coroutines in other threads, which, I think, should clearly be considered blocking (hence the name run**Blocking**, basically). So, the low-level behavior makes sense.

Could you provide the full code if you think there's a false positive so that we see the high-level picture?

**Comment by OliverO2** [comment]
Of course I agree that any call to `runBlocking` is exactly that: blocking. Actually, I don't have a problem with Blockhound complaining about such calls and masking those individually. I just wonder if that works as intended: We could also adopt a point of view where any call to `runBlocking` would be considered intentional and instruct Blockhound to avoid complaining on those.

Anyway, the above is part of a larger test suite (unpublished code, unfortunately) which ran without Blockhound complaints before. I'll investigate and come up with more details and a small reproducer, if possible.

**Comment by dkhalanskyjb** [comment]
It should certainly be a prohibited for someone's UI thread to execute the following code, despite it being legal to do `Thread.sleep` in `Dispatchers.IO`:
```kotlin
runBlocking {
  launch(Dispatchers.IO) {
    Thread.sleep(1)
  }
}
```

> any call to `runBlocking` would be considered intentional and instruct Blockhound to avoid complaining on those.

The same argument could be made for basically any blocking call, no? "We can consider all file reads intentional" etc. This would kind of defeat the purpose of BlockHound.

> part of a larger test suite (unpublished code, unfortunately) which ran without Blockhound complaints before.

Before what? What changed? The version of BlockHound? The version of coroutines? If it's really a regression, on whose side is the regression?

**Comment by OliverO2** [comment]
No worries. My post above was just an interim response. Just give me some time to investigate.

The actual change in my code base seemed like a no-op, as it did introduce an extra dependency without actually using that dependency: Before, JUnit 5 was used directly, now it is pulled in by the kotest framework (without using the latter). However, there is an extra kotest plugin involved and maybe stuff I had overlooked.

I'll come up with better information as soon as I have it.

**Comment by OliverO2** [comment]
> The same argument could be made for basically any blocking call, no? "We can consider all file reads intentional" etc. This would kind of defeat the purpose of BlockHound.

While I don't have a definitive answer, I was thinking along these lines:
1. There is coroutine-aware code, which includes some blocking calls, mostly as part of the internal coroutine machinery. Such coroutine-aware code knows when to accept blocking and manages to do so only for acceptable time periods. Blockhound should not complain about such use.
2. There is coroutine-unaware code (file reads belong to this category), which may block for extended time periods. Inadvertently using such code should be detected by Blockhound.

So if I explicitly say `runBlocking`, why should Blockhound question that decision? (In my case it was just containing a short test initialization sequence.)

**Comment by dkhalanskyjb** [comment]
The `join` in `runBlocking` fits squarely into `2`. If `runBlocking` actually blocks (it doesn't do that typically!), it means that it's actually waiting for some code to execute, simple as that.

For example,
```kotlin
var x = 0
runBlocking {
  launch {
    x = 1
  }
}
```
does not fail, ever. It shouldn't fail: there's nothing actually blocking here, all code simply executes. `runBlocking` will only block if there's some forked-off code that it's waiting for. Or, in other words, if it blocks for indefinite periods of time.

```kotlin
runBlocking {
  withContext(Dispatchers.IO) {
    3 + 4
  }
}
```
is logically about the same as
```kotlin
        run {
            var result = 0
            val computation = thread {
                result = 3 + 4
            }
            computation.join()
            result
        }
```
Would you argue that BlockHound should also not question your decision to call this `join()`?

**Comment by OliverO2** [comment]
Here is a reproducer: [OliverO2/kotlinx\-coroutines\-3492](https://github.com/OliverO2/kotlinx-coroutines-3492)

The basic code is:

```kotlin
fun test1() = runTest {
    withContext(Dispatchers.Default) {
        runBlocking {
            delay(1000) // <- triggers BlockingOperationError
        }
    }
}
```

And the BlockHound positive occurs only if this dependency is present:

```kotlin
implementation("io.kotest:kotest-runner-junit5:5.5.1")
```

I did not yet figure out why this makes a difference. The test still seems to be run by the JUnit Jupiter engine, not
the Kotest one.

**Comment by OliverO2** [comment]
> runBlocking will only block if there's some forked-off code that it's waiting for.

If that means blocking without triggering BlockHound, I concur. Waiting for jobs in a scope to finish is just normal coroutines behavior. However, I don't see how that could possibly trigger BlockHound.

> Would you argue that BlockHound should also not question your decision to call this join()?

If its is the coroutines `join()`, yes: I have never seen BlockHound complaining on this. `join()` occurs regularly, either explicitly or implicitly by closing a `coroutineScope`.

To summarize, even within a blocking event loop, waiting for coroutines to finish is just the normal mode of operation, even if those coroutines run for extended amounts of time. If I understand it correctly, BlockHound should only complain about a certain set of suspect blocking calls, if such calls appear in a coroutine while it is in a `WorkerState` of `CPU_ACQUIRED`.

**Comment by dkhalanskyjb** [comment]
> If its is the coroutines join()

It's not. I provided the full context in the code snippet. It is a `join()` on a thread.

> waiting for coroutines to finish is just the normal mode of operation

Again, this could be argued about anything. "I want to read a file here, why is BlockHound complaining about me reading a file? Waiting for the file to be read is just the normal mode of operation for file reading!"

> If I understand it correctly, BlockHound should only complain about a certain set of suspect blocking calls

Some examples of typical uses of BlockHound:
* If the UI thread is blocked while some operation is going on, the redraws will not happen, and the user will think that the app hanged. So, the UI thread should not perform operations other than those with predictable performance characteristics.
* `Dispatchers.Default`, for example, only has one thread per a processor: https://docs.oracle.com/javase/7/docs/api/java/lang/Runtime.html#availableProcessors(). If a thread in `Dispatchers.Default` is busy doing literally nothing (in the case you provide, waiting for `delay` to execute), that's one fewer thread to actually perform computations, so the CPU is underutilized.

So, flagging suspect calls is just an instrument, the goal is to avoid parking a thread that would otherwise do something useful. Whitelisting `runBlocking` goes against this goal, as would whitelisting network calls, waiting on an arbitrary lock, waiting for arbitrary forked-off threads to finish, and so on.

**Comment by OliverO2** [comment]
> It's not. I provided the full context in the code snippet. It is a join() on a thread.

OK, that irritated me, as I'm not familiar with BlockHound usage in non-coroutine contexts. The answer if BlockHound should question a thread `join()` is probably, "it depends". I guess that's why there are predicates to mark threads as "not blocking" or "expect blocking".

Otherwise, I am aware about the implications of UI thread blocking, under-utilizing threads, thread pool starvation, and such. I am also aware that flagging suspect calls is just an instrument (as is the exemption of certain threads for BlockHound purposes).

Note that I am not arguing in favor of whitelisting `runBlocking` if that would effectively disable BlockHound. (The typical coroutine startup sequence uses `runBlocking` to transition from a non-coroutine environment.)

I'm just wondering why the park call triggers BlockHound when the Kotest dependency is present while the seemingly identical call without the Kotest dependency does not. To illustrate, I ran this on the debugger with breakpoint logging.

Output **without** the Kotest dependency:
```text
> Task :jvmTest
OpenJDK 64-Bit Server VM warning: Sharing is only supported for boot loader classes because bootstrap classpath has been appended
joinBlocking starting on 'Thread[Test worker,5,main]'
joinBlocking starting on 'Thread[DefaultDispatcher-worker-1,5,main]'
joinBlocking invoking parkNanos("coroutine#1":BlockingCoroutine{Active}@1931d99, 0) on 'Thread[Test worker,5,main]'
joinBlocking invoking parkNanos("coroutine#3":BlockingCoroutine{Active}@44d040bc, 0) on 'Thread[DefaultDispatcher-worker-1,5,main]'
joinBlocking invoking parkNanos("coroutine#1":BlockingCoroutine{Active}@1931d99, 0) on 'Thread[Test worker,5,main]'
joinBlocking invoking parkNanos("coroutine#1":BlockingCoroutine{Active}@1931d99, 0) on 'Thread[Test worker,5,main]'
joinBlocking invoking parkNanos("coroutine#1":BlockingCoroutine{Active}@1931d99, 0) on 'Thread[Test worker,5,main]'
joinBlocking invoking parkNanos("coroutine#3":BlockingCoroutine{Active}@44d040bc, 958211908) on 'Thread[DefaultDispatcher-worker-1,5,main]'
joinBlocking invoking parkNanos("coroutine#1":BlockingCoroutine{Active}@1931d99, 0) on 'Thread[Test worker,5,main]'
[133 repetitions of the previous line]
joinBlocking invoking parkNanos("coroutine#1":BlockingCoroutine{Active}@1931d99, 0) on 'Thread[Test worker,5,main]'
joinBlocking finishing on 'Thread[DefaultDispatcher-worker-1,5,main]'
joinBlocking invoking parkNanos("coroutine#1":BlockingCoroutine{Active}@1931d99, 0) on 'Thread[Test worker,5,main]'
joinBlocking invoking parkNanos("coroutine#1":BlockingCoroutine{Active}@1931d99, 0) on 'Thread[Test worker,5,main]'
joinBlocking invoking parkNanos("coroutine#1":BlockingCoroutine{Active}@1931d99, 0) on 'Thread[Test worker,5,main]'
joinBlocking invoking parkNanos("coroutine#1":BlockingCoroutine{Active}@1931d99, 0) on 'Thread[Test worker,5,main]'
joinBlocking finishing on 'Thread[Test worker,5,main]'
Disconnected from the target VM, address: 'localhost:46361', transport: 'socket'
```

Output **with** the Kotest dependency:
```text
> Task :jvmTest
joinBlocking starting on 'Thread[Test worker,5,main]'
joinBlocking finishing on 'Thread[Test worker,5,main]'
OpenJDK 64-Bit Server VM warning: Sharing is only supported for boot loader classes because bootstrap classpath has been appended
joinBlocking starting on 'Thread[Test worker,5,main]'
joinBlocking starting on 'Thread[DefaultDispatcher-worker-1,5,main]'
joinBlocking invoking parkNanos("coroutine#3":BlockingCoroutine{Active}@4aa68190, 0) on 'Thread[DefaultDispatcher-worker-1,5,main]'
joinBlocking invoking parkNanos("coroutine#2":BlockingCoroutine{Active}@2a869a16, 0) on 'Thread[Test worker,5,main]'
joinBlocking invoking parkNanos("coroutine#3":BlockingCoroutine{Active}@4aa68190, 955296421) on 'Thread[DefaultDispatcher-worker-1,5,main]'
joinBlocking invoking parkNanos("coroutine#2":BlockingCoroutine{Active}@2a869a16, 0) on 'Thread[Test worker,5,main]'
Breakpoint reached at reactor.blockhound.BlockingOperationError.<init>(BlockingOperationError.java:27)
joinBlocking invoking parkNanos("coroutine#2":BlockingCoroutine{Active}@2a869a16, 0) on 'Thread[Test worker,5,main]'
joinBlocking invoking parkNanos("coroutine#2":BlockingCoroutine{Active}@2a869a16, 0) on 'Thread[Test worker,5,main]'
joinBlocking invoking parkNanos("coroutine#2":BlockingCoroutine{Active}@2a869a16, 0) on 'Thread[Test worker,5,main]'
joinBlocking invoking parkNanos("coroutine#2":BlockingCoroutine{Active}@2a869a16, 0) on 'Thread[Test worker,5,main]'
joinBlocking invoking parkNanos("coroutine#2":BlockingCoroutine{Active}@2a869a16, 0) on 'Thread[Test worker,5,main]'
joinBlocking invoking parkNanos("coroutine#2":BlockingCoroutine{Active}@2a869a16, 0) on 'Thread[Test worker,5,main]'
joinBlocking finishing on 'Thread[Test worker,5,main]'
Disconnected from the target VM, address: 'localhost:42799', transport: 'socket'
```

Stack trace:
```text
Blocking call! jdk.internal.misc.Unsafe#park
reactor.blockhound.BlockingOperationError: Blocking call! jdk.internal.misc.Unsafe#park
	at java.base@11.0.16/jdk.internal.misc.Unsafe.park(Unsafe.java)
	at java.base@11.0.16/java.util.concurrent.locks.LockSupport.parkNanos(LockSupport.java:234)
	at app//kotlinx.coroutines.BlockingCoroutine.joinBlocking(Builders.kt:88)
	at app//kotlinx.coroutines.BuildersKt__BuildersKt.runBlocking(Builders.kt:59)
	at app//kotlinx.coroutines.BuildersKt.runBlocking(Unknown Source)
	at app//kotlinx.coroutines.BuildersKt__BuildersKt.runBlocking$default(Builders.kt:38)
	at app//kotlinx.coroutines.BuildersKt.runBlocking$default(Unknown Source)
	at app//Tests$test1$1$1.invokeSuspend(Tests.kt:19)
	at app//kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:33)
	at app//kotlinx.coroutines.DispatchedTask.run(DispatchedTask.kt:106)
	at app//kotlinx.coroutines.scheduling.CoroutineScheduler.runSafely(CoroutineScheduler.kt:570)
	at app//kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.executeTask(CoroutineScheduler.kt:750)
	at app//kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.runWorker(CoroutineScheduler.kt:677)
	at app//kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.run(CoroutineScheduler.kt:664)
```

**Comment by dkhalanskyjb** [comment]
The integration between coroutines and BlockHound is in the `kotlinx-coroutines-debug` module, which your project doesn't depend on. So, effectively, the BlockHound integration is not there. `kotest` probably does introduce it as a transitive dependency, making it work again.

**Comment by OliverO2** [comment]
That was it. Thank you!

For reference: When there is a need to exempt a specific section of blocking code from BlockHound checks, the following function could be used
```kotlin
package com.example

fun <Result> runBlockingUnchecked(block: suspend CoroutineScope.() -> Result): Result {
    contract {
        callsInPlace(block, InvocationKind.EXACTLY_ONCE)
    }
    return runBlocking { block() }
}
```

in conjunction with a `BlockHoundIntegration` like so:
```kotlin
class AdditionalBlockHoundIntegration : BlockHoundIntegration {
    override fun applyTo(builder: BlockHound.Builder): Unit = with(builder) {
        allowBlockingCallsInside("com.example", "runBlockingUnchecked")
    }
}
```
