### ISSUE TITLE
Could not find org.jetbrains.kotlinx:kotlinx-coroutines-core:1.6.4-native-mt

### ISSUE THREAD

**Issue by AlexanderNaumov** [Kotlin/kotlinx.coroutines#3499]
```
Could not determine the dependencies of task ':BlaBlaBla:transformIosTestCInteropDependenciesMetadataForIde'.
> Could not resolve all task dependencies for configuration ':BlaBlaBla:allSourceSetsRuntimeDependenciesMetadata'.
   > Could not find org.jetbrains.kotlinx:kotlinx-coroutines-core:1.6.4-native-mt.
     Required by:
         project :BlaBlaBla
```

When will "kotlinx-coroutines-core:1.6.4-native-mt" be added to the repository?

**Comment by qwwdfsad** [comment]
We deliberately decommission `-native-mt`. 1.6.4 didn't have any `native-mt`-related fixes, so we omitted it and the general recommendation is to switch on regular versions of coroutines

**Comment by adamint** [comment]
@qwwdfsad this guidance needs to be updated throughout kotlin documentation, for instance [here](https://kotlinlang.org/docs/multiplatform-mobile-concurrency-and-coroutines.html#multithreaded-coroutines)

**Comment by dkhalanskyjb** [comment]
Opened an issue for the website, thanks! https://youtrack.jetbrains.com/issue/KT-55498/The-Concurrency-and-coroutines-article-is-severely-outdated If anyone encounters any other mentions of `native-mt`, please say so here, and we'll try to hunt them down.
