### ISSUE TITLE
Add Repo-Info to Tutorial

### ISSUE THREAD

**Issue by s1monw1** [Kotlin/kotlinx.coroutines#35]
Hey Guys,

would make sense to add the repository information to your coroutines tutorial, wouldn't it?
"maven {
        url "http://dl.bintray.com/kotlin/kotlin-eap-1.1"
}" is necessary to find 
"dependencies {
    compile "org.jetbrains.kotlinx:kotlinx-coroutines-core:0.12"
}"

@see http://kotlinlang.org/docs/tutorials/coroutines-basic-jvm.html

Thanks and kind regards,
Simon

**Comment by ilya-g** [comment]
Thanks, we updated the current version of readme with the actual repository information.
