### ISSUE TITLE
Simple Test fails: NoSuchMethodError: No virtual metod 'find' 

### ISSUE THREAD

**Issue by OneFiveFour** [Kotlin/kotlinx.coroutines#3503]
This is a simple Test in an Android project.
The test file is located in the `androidTest` folder, so it runs as an instrumentation test on an Android emulator.

```
import kotlinx.coroutines.test.runTest
import org.junit.Test

class HouseDaoTest {
    @Test
    fun insertAndGetHouseFromDb_success() = runTest {
        assert(1 == 1)
        assert(2 == 2)
    }
}
```

When running this test, I get the following error:

`No virtual method find(Lkotlin/jvm/functions/Function1;)Lkotlinx/coroutines/internal/ThreadSafeHeapNode; in class Lkotlinx/coroutines/internal/ThreadSafeHeap; or its super classes (declaration of 'kotlinx.coroutines.internal.ThreadSafeHeap' appears in /data/app/~~rVhSG062Jzg60YKAgWe6uQ==/my.packagename.test-Up28py4pbfA6CKyThEVObA==/base.apk)`

The mentioned line of code where the `find` method cannot be found is here:

https://github.com/Kotlin/kotlinx.coroutines/blob/81e17dd37003a7105e542eb725f51ee0dc353354/kotlinx-coroutines-test/common/src/TestCoroutineScheduler.kt#L262

Does anyone know if this is a bug or works as expected??

**Comment by dkhalanskyjb** [comment]
Probably the test module has a more recent version than the core module. Please check your Gradle config.

**Comment by OneFiveFour** [comment]
YES! I feel stupid, but that was the case. The tests did not have access to the core module. Thanks a lot!
