### ISSUE TITLE
When calling yield() with Dispatchers.IO new threads are randomly spawned

### ISSUE THREAD

**Issue by logi-nilsson** [Kotlin/kotlinx.coroutines#3526]
The following code will eventually spawn the maximum number of threads for the dispatcher IO.

```kotlin
CoroutineScope(Dispatchers.IO).launch {
    while (currentCoroutineContext().isActive) {
        // Here we can do Channel::tryReceive() or whatever
        yield()
    }
}
```

Kotlin version: **1.7.10**
Coroutines version: **1.6.4**

The following tests highlights the problem. I expect that only two threads are needed since we only have a the single `runBlocking` and single `launch` of coroutines running.

```kotlin
import kotlinx.coroutines.CoroutineScope
import kotlinx.coroutines.Dispatchers
import kotlinx.coroutines.ExperimentalCoroutinesApi
import kotlinx.coroutines.currentCoroutineContext
import kotlinx.coroutines.isActive
import kotlinx.coroutines.launch
import kotlinx.coroutines.runBlocking
import kotlinx.coroutines.yield
import org.junit.Test
import java.time.Duration
import java.time.LocalDateTime

@OptIn(ExperimentalCoroutinesApi::class)
class YieldTest {
    companion object {
        private const val RUNTIME_SEC: Long =  15L
        private const val TIMEOUT_MS: Long = (RUNTIME_SEC + 1) * 1000
    }

    @Test(timeout = TIMEOUT_MS)
    fun `Test yield on IO dispatcher with limitedParallelism`() {
        val threadGroup: ThreadGroup = Thread.currentThread().threadGroup!!
        var previousThreadCount = threadGroup.activeCount()
        println("In the beginning we have $previousThreadCount threads")
        runBlocking {
            val startTime = LocalDateTime.now()
            val endTime = startTime.plusSeconds(RUNTIME_SEC)
            println("Start - $startTime")
            CoroutineScope(Dispatchers.IO.limitedParallelism(1)).launch {
                while (currentCoroutineContext().isActive && endTime.isAfter(LocalDateTime.now())) {
                    val threadCount = threadGroup.activeCount()
                    if (threadCount != previousThreadCount) {
                        previousThreadCount = threadCount
                        val duration = Duration.between(startTime, LocalDateTime.now()).seconds
                        println("After $duration seconds we have $threadCount threads")
                    }
                    yield()
                }
            }.join()
            println("End - $endTime")
        }
    }


    @Test(timeout = TIMEOUT_MS)
    fun `Test yield on IO dispatcher`() {
        val threadGroup: ThreadGroup = Thread.currentThread().threadGroup!!
        var previousThreadCount = threadGroup.activeCount()
        println("In the beginning we have $previousThreadCount threads")
        runBlocking {
            val startTime = LocalDateTime.now()
            val endTime = startTime.plusSeconds(RUNTIME_SEC)
            println("Start - $startTime")
            CoroutineScope(Dispatchers.IO).launch {
                while (currentCoroutineContext().isActive && endTime.isAfter(LocalDateTime.now())) {
                    val threadCount = threadGroup.activeCount()
                    if (threadCount != previousThreadCount) {
                        previousThreadCount = threadCount
                        val duration = Duration.between(startTime, LocalDateTime.now()).seconds
                        println("After $duration seconds we have $threadCount threads")
                    }
                    yield()
                }
            }.join()
            println("End - $endTime")
        }
    }
}
```

**NOTE: We need to run the tests independently to not affect the thread pool between the tests.**

Output from the test `Test yield on IO dispatcher`:
```
In the beginning we have 6 threads
Start - 2022-11-11T11:33:25.695933
After 0 seconds we have 9 threads
After 0 seconds we have 10 threads
After 0 seconds we have 13 threads
After 0 seconds we have 16 threads
After 0 seconds we have 18 threads
After 0 seconds we have 20 threads
After 0 seconds we have 22 threads
After 0 seconds we have 24 threads
After 0 seconds we have 27 threads
After 0 seconds we have 29 threads
After 1 seconds we have 30 threads
After 1 seconds we have 31 threads
After 1 seconds we have 32 threads
After 1 seconds we have 34 threads
After 1 seconds we have 36 threads
After 1 seconds we have 38 threads
After 1 seconds we have 40 threads
After 1 seconds we have 41 threads
After 1 seconds we have 43 threads
After 3 seconds we have 44 threads
After 3 seconds we have 46 threads
After 3 seconds we have 47 threads
After 3 seconds we have 48 threads
After 3 seconds we have 49 threads
After 3 seconds we have 51 threads
After 3 seconds we have 52 threads
After 3 seconds we have 54 threads
End - 2022-11-11T11:33:40.695933
```

Output from the test `Test yield on IO dispatcher with limitedParallelism`:
```
In the beginning we have 6 threads
Start - 2022-11-11T11:35:19.215872
After 0 seconds we have 9 threads
After 0 seconds we have 10 threads
After 0 seconds we have 11 threads
After 0 seconds we have 12 threads
After 0 seconds we have 13 threads
After 0 seconds we have 15 threads
After 0 seconds we have 16 threads
After 0 seconds we have 17 threads
End - 2022-11-11T11:35:34.215872
```

**Comment by logi-nilsson** [comment]
If this is expected behavior I would like to know how to limit the number of threads used when calling `yield()`.

**Comment by dkhalanskyjb** [comment]
By default, the number of threads in `Dispatchers.IO` is limited to 64, but you can control that number with the `kotlinx.coroutines.io.parallelism` system property.

Given that the number of threads has an upper bound, is this still an issue? If so, could you explain why in more detail?

**Comment by logi-nilsson** [comment]
> By default, the number of threads in `Dispatchers.IO` is limited to 64, but you can control that number with the `kotlinx.coroutines.io.parallelism` system property.
> 
> Given that the number of threads has an upper bound, is this still an issue? If so, could you explain why in more detail?

Yes, I am afraid this is an issue. In my use case it starts to consume a lot of CPU time. 

Granted, it is only my assumption that the overhead of each dispatcher in combination with all the context switching being done in between the coroutines finally consumes all available CPU time. If I am correct, I would assume it also becomes a monetary problem in a cloud environment where multiple Java instances run.

I am grateful for the proposal, but I do not think `kotlinx.coroutines.io.parallelism` is a solution to the problem.

**Comment by logi-nilsson** [comment]
We mitigated the CPU consumption by limiting the number of threads by using `Dispatchers.Default` instead of `Dispatchers.IO` and introduce a `delay` after the `yield` to reduce the number of context switches done.

**Comment by dkhalanskyjb** [comment]
> In my use case it starts to consume a lot of CPU time.

`Dispatchers.IO` is for doing I/O work (network calls etc), not for computations. Also, `yield` is fairly rarely needed, and it's especially not needed before a `delay`, because `delay` yields on its own. Using `Dispatchers.Default` may actually be the proper solution: if you don't want to execute many routines in *parallel*, that's exactly what you need. `IO` is a thread pool for threads that will almost always be awaiting some blocking operation.

> all the context switching being done in between the coroutines finally consumes all available CPU time

This has nothing to do with new threads being created: if there's not enough work for all the threads, they will simply lay dormant.

> I do not think `kotlinx.coroutines.io.parallelism` is a solution to the problem.

That's true in your case, but in general, it is a solution to the problem of too many threads being created.

> Maybe it only limits the number of threads used in parallel?

Yes.
