### ISSUE TITLE
Updating stateFlow from multiple threads not working (tried using update{} & mutext)

### ISSUE THREAD

**Issue by UKMIITB** [Kotlin/kotlinx.coroutines#3532]
There is a scenario where from 2 different threads, a stateflow value is updated concurrently.
Is there any way to capture all those values or atleast capture the last value.

Here is the scenario:

```
class MainViewModel : ViewModel() {

    private val _value = MutableStateFlow(-1)
    val value = _value.asStateFlow()

    var count = 0

    fun startUpdate() {
        viewModelScope.launch(Dispatchers.IO) {
            async {
                updateFrom1()
            }
            async {
                updateFrom1000()
            }
        }
    }

    fun updateValue(value: Int) {
        _value.update { value }
    }

    suspend fun updateFrom1() = withContext(Dispatchers.IO) {
        for (i in 1..1000) {
            updateValue(i)
            Log.d("Ujjwal", "UpdateFrom1 :$i")
        }
    }

    suspend fun updateFrom1000() = withContext(Dispatchers.IO) {
        for (i in 1000 downTo 1) {
            updateValue(i)
            Log.d("Ujjwal", "UpdateFrom1000 :$i")
        }
    }
}
```

```
class MainActivity : ComponentActivity() {
    override fun onCreate(savedInstanceState: Bundle?) {
        super.onCreate(savedInstanceState)
        val viewmodel = MainViewModel()
        setContent {
            MyApplicationTheme {
                // A surface container using the 'background' color from the theme
                MyFunction(viewmodel)
            }
        }
    }
}

@Composable
fun MyFunction(viewModel: MainViewModel) {
    val value by viewModel.value.collectAsState()

    when (value) {
        else -> {
            viewModel.count = viewModel.count + 1
            Text(text = "value is ${viewModel.count}")
            Log.d("Ujjwal", "count is : ${viewModel.count}")
        }
    }

    LaunchedEffect(Unit ){
        viewModel.startUpdate()
    }
}
```

My expectation is at the end I want the value of count to be 2000 (That is it should get executed for all the updates of _value)

For the function I have tried the following variant, but none of them have worked

```
fun updateValue(value: Int) {
        _value.update { value }
    }

fun updateValue(value: Int) {
        viewModelScope.launch {
            _value.update { value }
        }
    }
    
fun updateValue(value: Int) {
        viewModelScope.launch(Dispatchers.IO) {
            _value.update { value }
        }
    }

fun updateValue(value: Int) {
        viewModelScope.launch(Dispatchers.IO) {
            _value.value = value
        }
    }

fun updateValue(value: Int) {
        viewModelScope.launch {
            _value.value = value
        }
    }

fun updateValue(value: Int) {
        viewModelScope.launch {
            _value.emit(value)
        }
    }

fun updateValue(value: Int) {
        viewModelScope.launch(Dispatchers.IO) {
            _value.emit(value)
        }
    }

suspend fun updateValue(value: Int) = withContext(Dispatchers.IO) {
        _value.emit(value)
    }

suspend fun updateValue(value: Int) = withContext(Dispatchers.IO) {
        _value.value = value
    }

fun updateValue(value: Int) {
       viewModelScope.launch {
           mutex.withLock {
               _value.value = value
           }
       }
   }
```

Is there anything that I am missing or having some wrong assumption of how stateFlow is supposed to behave ?
For each execution, I get different value of count (usually around 8-14)

Here is the stackoverflow discussion that I posted
https://stackoverflow.com/questions/74493129/updating-stateflow-value-from-multiple-threads

**Comment by dmstocking** [comment]
StateFlows are always conflated.
> Updates to the [value](https://kotlinlang.org/api/kotlinx.coroutines/kotlinx-coroutines-core/kotlinx.coroutines.flow/-state-flow/value.html) are always [conflated](https://kotlinlang.org/api/kotlinx.coroutines/kotlinx-coroutines-core/kotlinx.coroutines.flow/conflate.html)
> - https://kotlinlang.org/api/kotlinx.coroutines/kotlinx-coroutines-core/kotlinx.coroutines.flow/-state-flow/

Which means you are guaranteed to get the most recent value. There is no guarantee to get every value. If you want every value, you would have to use a MutableSharedFlow. MutableSharedFlows are not conflated by default but do not store any state. Without knowing more, it is hard to give more advice.

One thing I can think of is to stop thinking about values changing over time. Think about Kotlin coroutines and flows more like messages. You can manipulate messages, join multiple messages together, break them apart, etc. If you think about changing variables over time, you are going to have a hard time.
