### ISSUE TITLE
Which part is MIT license?

### ISSUE THREAD

**Issue by manji-black** [Kotlin/kotlinx.coroutines#3536]
Dear sir or madam, 

This library has a following license file: 
https://github.com/Kotlin/kotlinx.coroutines/blob/master/license/third_party/minima_LICENSE.txt

It seems that this library contains a third party software whose license is MIT. 
But I can't identify which is the MIT licensed software. 
Could you please let me know?

Best Regards,

**Comment by dkhalanskyjb** [comment]
Thanks! Looks like it's for https://github.com/jekyll/minima, which we no longer use. It seems that we can safely remove the license file now.

**Comment by qwwdfsad** [comment]
Removed this license in `develop` branch
