### ISSUE TITLE
Exceptions eaten after coroutine has been cancelled

### ISSUE THREAD

**Issue by matejdro** [Kotlin/kotlinx.coroutines#354]
```kotlin
val job = launch {
    withContext(NonCancellable) {
        delay(100)
        println("Throwing exception now...")
        throw Exception()
    }
}

job.cancelAndJoin()
```

Above code will not throw any exception (println will be executed, but exception not thrown).

Is that expected behavior? I would imagine exceptions would always have to be thrown, even after corotuine has been cancelled.

**Comment by qwwdfsad** [comment]
Where do you expect it to be thrown?

See the javadoc to `join`: "This invocation **resumes normally** (without exception) when the job is complete **for any reason**". Job is fire and forget, and this is exactly the case.

You have multiple options:
1) Set your own exception handler, which will handle all uncaught exceptions
2) Use `job.getCancellationException()`, then you receive `JobCancellationException` with cause `Exception`
3) Use `async`:
```
val job = async() {...}
job.cancel()
job.await() // <- will throw Exception
```

**Comment by fvasco** [comment]
> I would imagine...

You have to refer to documentation, always.

**Comment by matejdro** [comment]
This is not related to `join()`. If I replace `cancelAndJoin()` in above example with just `join()`, exception is thrown just fine (and program crashes).

**Comment by qwwdfsad** [comment]
If you replace `cancelAndJoin()` with just `join()`, then cancellation cause of your job is not `JobCancellationException` (which is ignored by default exception handler), but raw `Exception`, which is passed to handler.
So if your program crashes it means that default exception handler is crashing program on any uncaught exception (guess: it's Android)

This part of exception handling is clumsy and not well-defined, we're currently thinking how we can improve it (e.g. see #333). In the final design we'd like to pass `Exception` in that case to exception handler

**Comment by matejdro** [comment]
So basically, that means that once job is cancelled (and cancellation cause determined), all exceptions from that job will be eaten (not passed to default exception handler)?
