### ISSUE TITLE
ChannelFlow throws exceptions too early

### ISSUE THREAD

**Issue by Shusek** [Kotlin/kotlinx.coroutines#3543]
I'm not sure if this is a bug but I was surprised that `channelFlow` does not allow emission of objects  that happened before raised exception unlike as flow{} builder. This the intended behavior?

Simplified code:
```
@Test
    fun simpleEmitWithThrow() = runTest {
        val flow = flow {
            emit(Unit)
            throw IllegalStateException()
        }
        assertEquals(Unit, flow.first()) // test passed
    }

    @Test
    fun simpleChannelFlow() = runTest {
        val flow = channelFlow {
            send(Unit)
            throw IllegalStateException()
        }
        assertEquals(Unit, flow.first()) // test failed with IllegalStateException
    }

```

**Comment by qwwdfsad** [comment]
The `channelFlow` operator is buffered and launches a coroutine under the hood. 

In the `flow` example, the downstream receives the first element and immediately cancels/cuts out the upstream, thus not giving and exception a chance to fire. In `channelFlow` example a level of asynchrony is present -- `Unit` is sent to the channel first, then exception is immediately thrown **before** the downstream read from the channel, and everything is cancelled and failed with the said exception

**Comment by Shusek** [comment]
Sounds reasonable,  in my case to get proper order of events i changed from throw exception to close channel with `close(reason)`.
