### ISSUE TITLE
Unsynchronized access to ThreadSafeHeap in K/N

### ISSUE THREAD

**Issue by qwwdfsad** [Kotlin/kotlinx.coroutines#3547]
https://github.com/Kotlin/kotlinx.coroutines/blob/master/kotlinx-coroutines-core/common/src/EventLoop.common.kt#L441

Note that `@Synchronized` has no effect on K/N

**Comment by 05nelsonm** [comment]
I know this was marked as fixed in #3550 , but wouldn't you also need to change anything marked as `@Volatile` to an `AtomicRef`?

https://github.com/Kotlin/kotlinx.coroutines/blob/725c46c66f506b6d5b7419a5362d4814fec2099c/kotlinx-coroutines-core/common/src/EventLoop.common.kt#L418

**Comment by qwwdfsad** [comment]
This is just to suppress a TSAN warning and not actually a race, and it will be fixed automatically with K/N @Volatile that is coming in 1.8.20
