### ISSUE TITLE
How to keep a coroutine waiting?

### ISSUE THREAD

**Issue by sidsharma2002** [Kotlin/kotlinx.coroutines#3555]
Hi I have a doubt regarding some implementation. 
In a suspend function I launch a firestore snapshot listener and want to keep this coroutine waiting until a certain condition is achieved in that snapshot callback. If I use a CountDownLatch won't I block this coroutine rather it should wait in a suspending manner?

```
suspend fun connect() = withContext(Dispatchers.IO) {
    launch {
        snapshot = object : SomeCallback {
          override fun onReceived() {
                if (x == 100) { HERE I WANT TO RELEASE THE WAITING FUNCTION  }
          }
        }
    }

// wait for the condition to be achieved
}
```
Also does using withContext like I did here creates any overhead? If Dispatchers.IO has 64 threads, if i create 3 scopes then I do have 64 * 3 potential threads in threadpool ?

Already thanks to the future responder!

**Comment by fvasco** [comment]
This question doesn't look as a issue on this library.
I suggest you to discuss your question on a proper channel: https://kotlinlang.org/community/

In the meanwhile, you can take a look to the [official documentation](https://github.com/Kotlin/KEEP/blob/master/proposals/coroutines.md#wrapping-callbacks), [callbackFlow](https://kotlinlang.org/api/kotlinx.coroutines/kotlinx-coroutines-core/kotlinx.coroutines.flow/callback-flow.html) and [CompletableDeferred](https://kotlinlang.org/api/kotlinx.coroutines/kotlinx-coroutines-core/kotlinx.coroutines/-completable-deferred/).

**Comment by ifuatgucluer** [comment]
thanks

Siddharth sharma ***@***.***>, 18 Ara 2022 Paz, 09:08
tarihinde şunu yazdı:
