### ISSUE TITLE
Wrong output given in api documentation of runningFold

### ISSUE THREAD

**Issue by kfh** [Kotlin/kotlinx.coroutines#3567]
There is a minor documentation error in the api docs of [runningFold](https://kotlinlang.org/api/kotlinx.coroutines/kotlinx-coroutines-core/kotlinx.coroutines.flow/running-fold.html). The output in the example should be a list of lists:

will produce `[], [1], [1, 2], [1, 2, 3]` --> will produce `[[], [1], [1, 2], [1, 2, 3]]`

**Comment by qwwdfsad** [comment]
An example enumerates all list elements, not the list `toString()` result, but it indeed can be source of confusion
