### ISSUE TITLE
join() after cancel() will sometimes not wait for coroutine to finish executing fully

### ISSUE THREAD

**Issue by matejdro** [Kotlin/kotlinx.coroutines#357]
Execute this test:

```kotlin
repeat(10000) {
    val previousJobFinished = AtomicBoolean(false)

    val jobA = launch {
        try {
            delay(100)
        } finally {
            // Sleep to simulate doing some work in finally block
            Thread.sleep(10)
            previousJobFinished.set(true)
        }
    }

    val jobB = async {
        jobA.cancelAndJoin()
        assertTrue("Join() has finished, but jobA is still executing", previousJobFinished.get())
    }

    jobB.await()
}
```

After several repeats of inner block in above code (sometimes it happens after 10 repeats, sometimes after hundreds), test will fail.

Apparently `join()` method sometimes does not wait for joined coroutine to finish cancelling completely and will resume executing before joined coroutine finishes completely.

I reproduced this on `org.jetbrains.kotlinx:kotlinx-coroutines-core:0.22.5`

**Comment by qwwdfsad** [comment]
This test has non-obvious data race. 
Sometimes `jobA` is not even started before calling `jobA.cancelAndJoin()`, so `cancel` call immediately cancels not yet started job without starting to execute it (thus not executing `finally` block as well)

Extreme example of this race will be `val jobA = launch(start = CoroutineStart.LAZY)`, in that case `finally` block will never be executed.
