### ISSUE TITLE
Replace Dispatchers.IO 

### ISSUE THREAD

**Issue by famik** [Kotlin/kotlinx.coroutines#3579]
Dispatchers.IO is frequently used
I hope app have only one global io thread pool，but OkHttp‘s dispatcher use  ExecutorService

How to replace Dispatchers.IO like RxJavaPlugins.setInitIoSchedulerHandler,
or  implementation CoroutineDispatcher.asExecutorService:

```
OkHttpClient.Builder()
       .dispatcher(Dispatcher(Dispatchers.IO.asExecutorService()))
       .build()
```

**Comment by dkhalanskyjb** [comment]
There's already `CoroutineDispatcher.asExecutor()`. Providing `asExecutorService` is not viable: it is supposed to support `shutdown`, but shutting down `Dispatchers.IO` is a delicate operation that should not be performed lightly. See https://kotlinlang.org/api/kotlinx.coroutines/kotlinx-coroutines-core/kotlinx.coroutines/-dispatchers/shutdown.html.

I don't see okhttp's `HttpClient` meaningfully using the fact that the executor is an executor service. Maybe the following will do just fine?
```kotlin
fun CoroutineDispatcher.asExecutorService(): ExecutorService = object : Executor by asExecutor(), AbstractExecutorService() {
    override fun shutdown() {
        throw UnsupportedOperationException("shutdown is not implemented")
    }

    override fun shutdownNow(): MutableList<java.lang.Runnable> {
        throw UnsupportedOperationException("shutdownNow is not implemented")
    }

    override fun isShutdown(): Boolean = false

    override fun isTerminated(): Boolean = false

    override fun awaitTermination(timeout: Long, unit: TimeUnit): Boolean = false
}
```
