### ISSUE TITLE
API for creating a parent job backed by a  coroutineContext

### ISSUE THREAD

**Issue by ZakTaccardi** [Kotlin/kotlinx.coroutines#358]
I want to create a job parent for cancellation purposes. I want the parent job to run in a specific context. Currently, we have to do it this way:

```
private val jobParent = Job().apply { this + CommonPool }
```

I think passing that information into the constructor would make for a better and more obvious api.

```
private val jobParent = Job(CommonPool)
```

Is something like this possible?

Rest of usage:

```
launch(parentJob) {  ... }
```

```
override fun onCleared() {
        jobParent.cancelChildren()
    }  
}
```

**Comment by jcornaz** [comment]
`Job` hasn't any dispatcher. So it is not possible, and is meaningless to try to create a `Job` with a dispatcher. What you seem to want is to create a context. A context may have many elements, including `Job` and `CoroutineDispatcher`. You can create a context by combining elements with the `+` operator.

doing `apply { this + CommonPool }` has absolutely no effect. `+` will create a new context with the job an the `CommonPool` dispatcher, but as it is not assigned to a variable, it is simply lost, and the coroutine of your example will be launched the same way as if you would have created a job with simply `Job()`.

However, you can create the context you want like this:
```kotlin
val context = Job() + CommonPool
launch(context) { ... }
```

But this is a *context* not a *job*. and it contains (in this case) two elements, a *dispatcher* and a *job*.

Think of the context has a `Map` where keys are element type (`Job`, `CoroutineDisptacher`, `CoroutineName`, `CoroutineExceptionHandler`, etc.) values are instance of the corresponding type.

**Comment by qwwdfsad** [comment]
Why `context + job` is not suitable for you?

Also note, that cancelling job in `onCleared` is enough, job cancellation cancels its children as well

**Comment by qwwdfsad** [comment]
Any updates on this?

**Comment by ZakTaccardi** [comment]
the use case for this is creating a parent job for children to automatically have a dispatcher applied. I was under the impression this could be done, but I don't think it can.

```
val dispatcher = newSingleThreadContext("MyDispatcher")
val job = Job().apply { this + dispatcher }
        
launch(parent = job) {
  log(1)
}
```

I thought the coroutine would be dispatched by the `dispatcher` above, but it's actually the `DefaultDispatcher`.

**Comment by DrewCarlson** [comment]
```
val job = Job().apply { this + dispatcher }
```
The plus operator for `CoroutineContext` returns a new `CombinedContext`, it does not modify the `Job`.


I think this is what you are looking for:
```
val dispatcher = newSingleThreadContext("MyDispatcher")
val context = Job() + dispatcher
        
launch(context) {
  log(1)
}
```

[`Job.kt`](https://github.com/Kotlin/kotlinx.coroutines/blob/07c5ce48c03b417f1808ab04cd29f76235ed4ce7/common/kotlinx-coroutines-core-common/src/Job.kt#L448-L463) contains two extension functions for `CoroutineContext` that allow for cancelling the `Job` in this new context.
