### ISSUE TITLE
CoroutineScope(Job()) is not being cancelled if one of the child jobs fails.

### ISSUE THREAD

**Issue by Toffor** [Kotlin/kotlinx.coroutines#3589]
According to Job documentation, the invocation of [cancel][Job.cancel] with exception (other than [CancellationException]) on this job also cancels parent. Job.cancel function only accepts CancellationException. I am testing this behavior but cancelling a child job is not cancelling the parent job despite I am not using SupervisorJob. So then what is the exact different in between Job and SupervisorJob ? It is easier to understand difference between coroutineScope and supervisorScope.

```kotlin
fun main()  {
    val parentJob = Job()
    val scope = CoroutineScope(parentJob)

    suspend fun printText(text: String) {
        println("Before Delay: $text")
        delay(1000)
        println("After Delay: $text")
    }

    val job1 = scope.launch {
        printText("Job#1")
    }

    job1.invokeOnCompletion {
        println("Job#1 completed. Cause = $it")
    }

    val job2 = scope.launch {
        printText("Job#2")
    }

    job2.invokeOnCompletion {
        println("Job#2 completed. Cause = $it")
    }

    println(parentJob.children.joinToString { it.toString() } )

    job1.cancel(CancellationException())

    Thread.sleep(10000)

}
```

Output:

```text
Before Delay: Job#1
Before Delay: Job#2
StandaloneCoroutine{Active}@462d5aee, StandaloneCoroutine{Active}@69b0fd6f
Job#1 completed. Cause = java.util.concurrent.CancellationException
After Delay: Job#2
Job#2 completed. Cause = null

Process finished with exit code 0
```

**Comment by ifuatgucluer** [comment]
Teşekkürler

19 Oca 2023 Per 12:09 tarihinde Coşkun Yalçınkaya ***@***.***>
şunu yazdı:

**Comment by qwwdfsad** [comment]
>the invocation of [cancel][Job.cancel] with exception (other than [CancellationException]) on this job also cancels parent

This is an oversight, we'll fix the documentation, thanks for spotting

> I am testing this behavior but cancelling a child job is not cancelling the parent job

This is an expected behaviour, correct it would be impossible to cancel the subtree of jobs or job's own children

For general questions, please refer to our coroutines guide, stackoverflow or community slack

**Comment by ifuatgucluer** [comment]
thanks a lot
