### ISSUE TITLE
Incorrect kdoc for TestScope.backgroundScope

### ISSUE THREAD

**Issue by ansman** [Kotlin/kotlinx.coroutines#3604]
**Describe the bug**

In the documentation for `TestScope.backgroundScope` it says that calling `advanceUntilIdle`, `advanceTimeBy` and `runCurrent` will only advance time when there are only background coroutines left running:
> Additionally, while the coroutines in this scope are run as usual when using advanceTimeBy and runCurrent, advanceUntilIdle will stop advancing the virtual time once only the coroutines in this scope are left unprocessed.

This doesn't really seem to be the case though. It is true that `advanceUntilIdle` will not do anything if the only coroutines running are in the background scope but it seems that both `advanceTimeBy` and `runCurrent` both work just fine when the only coroutines left running are in the background scope.

**Provide a Reproducer**
Here is a test case that showcases the issue:
```kotlin
testScope.runTest {
    var didRun = false
    backgroundScope.launch {
        delay(500L)
        didRun = true
    }
    println(didRun) // prints false as expected

    advanceUntilIdle()
    println(didRun) // prints false as expected

    advanceTimeBy(500L)
    println(didRun) // prints false as expected

    runCurrent()
    println(didRun) // prints true which should not happen if the kdoc is to be believed
}
```

**Comment by dkhalanskyjb** [comment]
From the text you've quoted:

> the coroutines in this scope are run as usual when using advanceTimeBy and runCurrent

> advanceUntilIdle will stop advancing the virtual time

Seems okay to me!

**Comment by ansman** [comment]
Oh man, I totally misread that! 🤦

**Comment by ansman** [comment]
Perhaps the comment could be reworded though because both me and several of my colleagues misread it
