### ISSUE TITLE
Why cancellation cause is sent to CoroutineExceptionHandler?

### ISSUE THREAD

**Issue by kptlronyttcna** [Kotlin/kotlinx.coroutines#361]
For example running this test unexpectedly (at least for me) prints a stack trace of `RuntimeException`.

Why was this design decision made? I mean `RuntimeException` is already mentioned in the cause of cancellation. Why is it passed to `CoroutineExceptionHandler` as an independent exception?

```
class Test {
  @Test
  fun test() = runBlocking<Unit> {
    val job = launch {
      try {
        delay(1000)
      } catch (t: CancellationException) {
        // I should be able to handle cancellation cause here without the involvement of CoroutineExceptionHandler
      }
    }
    delay(100)
    job.cancel(RuntimeException("message"))
    job.join()
  }
}
```

**Comment by qwwdfsad** [comment]
It's because exception handler is unreliable.
For example, `delay(1000)` may be already executed, your `job` could have no `catch` block or `job` may be not yet started (and then it won't start on cancellation)
