### ISSUE TITLE
invokeOnCancellation(onCancelling = false) should (probably) inhibit JobCancellationException

### ISSUE THREAD

**Issue by hsyed** [Kotlin/kotlinx.coroutines#364]
Snippet from a Queue reactor for SQS. The `onCancelling=false` isn't being respected and I have to check for `JobCancellationException` during shutdown is this the intended behaviour ? 

```kotlin
    override fun startUp() {
        fun doLaunch(context: CoroutineContext, delay: Int = 0) {
            launchReactor(context, delay)
                .invokeOnCompletion(onCancelling = false) {
                    if (it != null && it !is JobCancellationException) {
                        logger.atSevere()
                            .atMostEvery(5, TimeUnit.SECONDS)
                            .withCause(it)
                            .log("reactor failed, relaunching")
                        doLaunch(context, 5000)
                    }
                }
        }

        reactorJob = launch {
            for (i in 1..reactorCount) {
                doLaunch(coroutineContext + CoroutineName("qreactor-${client.queueName}-$i"))
            }
            logger.atInfo().log("launched %d reactors for queue %s", reactorCount, client.queueName)
        }
    }
```
---

We could do with some patterns for job supervision like Akka.  implementing a parallel queue reactor is quite complex without it.  The above snippet the code is housed in a guava service and the startup method is supposed to start `n` queue workers. So it would be nice to have a guava `Service` / `ServiceManager` for coroutines. Beyond this a a framework defined mechanism to supervise other jobs -- perhaps I am implying an actor framework.

**Comment by qwwdfsad** [comment]
It is intended behaviour.
Doc to `onCancelling` flag states:
 >when `true`, then the [handler] is invoked as soon as this job transitions to _cancelling_ state

`Cancelling` is a transient state which can be observed while job waits for its children to cancel.
So if the job has at least one child and is cancelled, following transitions will happen:
`Active` -> `Cancelling` (here `cancel` is invoked for all children) -> (when all children finished its cancellation) `Cancelled`.

To avoid confusion, we probably can rename this flag to something less ambiguous.


>We could do with some patterns for job supervision like Akka

We're currently working on new actors API, which may be useful for you ([raw prototype](https://github.com/Kotlin/kotlinx.coroutines/blob/3bf226159655d58164493d203875a0909def3a60/core/kotlinx-coroutines-core/src/test/kotlin/kotlinx/coroutines/experimental/actors/CrawlerExample.kt)), though there is no supervision yet.

In general, job supervision may be useful for `kotlinx.coroutines` users, but we have not enough use-cases to prototype it. Feel free to create new github issue with short explanation of the problem and desired API draft, it will help us to see other users demand/feedback on job supervision.
E.g. it's unclear to me whether `Job` supervision is really helpful if we will implement `Actor` supervision

**Comment by hsyed** [comment]
thanks, sorry for the delay. I have been following the new actor api  -- I should be able to make use of it for my queue implementation. 

After iterating on my design I can see that supervision is not necessary for this use case especially after studying the AWS Java SDK.
