### ISSUE TITLE
Build failed when upgrading to Coroutines V.1.7.0-Beta

### ISSUE THREAD

**Issue by eakteam** [Kotlin/kotlinx.coroutines#3668]
```
* What went wrong:
Execution failed for task ':app:mergeDebugJavaResource'.
> A failure occurred while executing com.android.build.gradle.internal.tasks.MergeJavaResWorkAction
   > 2 files found with path 'META-INF/versions/9/previous-compilation-data.bin' from inputs:
      - C:\Users\EAKTEAM\.gradle\caches\transforms-3\033c0d844605f2bba73c4ea615dac57b\transformed\jetified-kotlinx-coroutines-android-1.7.0-Beta.jar
      - C:\Users\EAKTEAM\.gradle\caches\transforms-3\febf3693d39f31c76ff118a3c4525fae\transformed\jetified-kotlinx-coroutines-core-jvm-1.7.0-Beta.jar
     Adding a packagingOptions block may help, please refer to
     https://developer.android.com/reference/tools/gradle-api/8.0/com/android/build/api/dsl/ResourcesPackagingOptions
     for more information

* Try:
> Run with --stacktrace option to get the stack trace.
> Run with --info or --debug option to get more log output.
> Run with --scan to get full insights.

* Get more help at https://help.gradle.org
```

**Comment by eakteam** [comment]
As a temporary workaround i added in the app.build gradle file:

```
resources {
            merges += ['META-INF/versions/9/previous-compilation-data.bin']
        }
```

**Comment by LouisCAD** [comment]
Got the exact same issue. Any clue what might cause this kind of regression?

**Comment by eakteam** [comment]
> Got the exact same issue. Any clue what might cause this kind of regression?

https://github.com/Kotlin/kotlinx.coroutines/issues/3668

**Comment by qwwdfsad** [comment]
>Got the exact same issue. Any clue what might cause this kind of regression?

`previous-compilation-data.bin` is Gradle's internal machinery for the incremental compilation that seemed to be packed into the resulting artifact because we are depending directly on the compilation task's output for JPMS/Multi-Release JAR support.

A similar problem can be found here: https://discuss.gradle.org/t/previous-compilation-data-bin/43385

**Comment by qwwdfsad** [comment]
We'll accumulate more changes (and also will wait for additional feedback) and will release RC or stable

**Comment by jasonctoms** [comment]
> As a temporary workaround i added in the app.build gradle file:
> 
> ```
> resources {
>             excludes += ['META-INF/versions/9/previous-compilation-data.bin']
>         }
> ```

Does anyone know where to put the resources block in a KMM project?

**Comment by eygraber** [comment]
I think bumps like this are one of the main roadblocks to more people testing out beta or RCs. Is there any harm in releasing multiple beta builds that fix issues like these so there's a lower barrier to entry (and also the ability to validate that the issue was actually fixed)?
