### ISSUE TITLE
extensive usages of withContext/Undispatched coroutines causes ThreadLocal maps to grow, which causes application to become unresponsive

### ISSUE THREAD

**Issue by RestfulBlue** [Kotlin/kotlinx.coroutines#3669]
Each undispatched coroutine spawns a separate threadLocal and if there are a lot of undispatched coroutines - threadLocal map on all threads becomes huge and server spend 100% of cpu on traversing threadLocal maps in order to find empty spot, shift entries and so on

Below a attach screenshots of heapdump from production application which have 2gb of heap.
It creates around 2k of UndispatchedCoroutines. In such scenario ThreadLocalMap on each thread is around ~700. ThreadLocalMap is resized when 75% of slots are used, which means there were at least 500 elements used in parallel at some point of time. 
Earlier we had constant incidents when threadLocal map was reaching 1500 elements. At that point all cpu is being spent on threadLocal map updates.

<img width="2191" alt="Screenshot 2023-03-09 at 14 17 03" src="https://user-images.githubusercontent.com/32250229/224107303-2d69d1d1-d856-4d02-a65c-53ef8be2f9e3.png">

<img width="2214" alt="Screenshot 2023-03-09 at 14 28 56" src="https://user-images.githubusercontent.com/32250229/224106135-380954cf-8fb7-4046-9cf5-8707c3b7c1c0.png">
0f.png">

<img width="2197" alt="Screenshot 2023-03-09 at 14 34 08" src="https://user-images.githubusercontent.com/32250229/224106251-4de423bb-48cb-40da-a287-7bc74e5d11e1.png">

<img width="2087" alt="Screenshot 2023-03-09 at 18 11 29" src="https://user-images.githubusercontent.com/32250229/224106705-6a8553c8-205f-4fad-a385-d8143a6ad818.png">

issue seems to be quite critical, as far as i understand any highloaded server which relies on coroutines could become unavailable at any point of time

**Comment by qwwdfsad** [comment]
After #3593 it's not clear whether the evidence for the issue exists, we are waiting for the additional experiments from Space

**Comment by qwwdfsad** [comment]
Closing as "not enough data to claim it's a problem".
Feel free to reopen if the problem reproduces
