### ISSUE TITLE
Dokka ate a space

### ISSUE THREAD

**Issue by dkhalanskyjb** [Kotlin/kotlinx.coroutines#3687]
<https://kotlinlang.org/api/kotlinx.coroutines/kotlinx-coroutines-core/kotlinx.coroutines.flow/-mutable-shared-flow/try-emit.html> here, there's no space before "and," but there is one in the actual code, and according to the Git history, it was always there.

**Comment by qwwdfsad** [comment]
Worth reporting directly to https://github.com/Kotlin/dokka/
