### ISSUE TITLE
Can't compile with 1.7.0-Beta: kotlinx.coroutines.future.future not resolved

### ISSUE THREAD

**Issue by martypitt** [Kotlin/kotlinx.coroutines#3691]
**Describe the bug**

After upgrading to 1.7.0-Beta, I can't seem to resolve the `future` extension function: `import kotlinx.coroutines.future.future`.

Based on advice in the slack channel, I've added a dependency:

```diff
...
<kotlin.coroutines.version>1.7.0-Beta</kotlin.coroutines.version>
...

      <dependency>
         <groupId>org.jetbrains.kotlinx</groupId>
         <artifactId>kotlinx-coroutines-jdk8</artifactId>
         <version>${kotlin.coroutines.version}</version>
      </dependency>
+     <dependency>
+       <groupId>org.jetbrains.kotlinx</groupId>
+         <artifactId>kotlinx-coroutines-core</artifactId>
+        <version>${kotlin.coroutines.version}</version>
+      </dependency>
```

```bash
mvn dependency:tree -Dincludes=org.jetbrains.kotlinx:kotlinx-coroutines-core -Dverbose -Dscope=compile

[INFO] io.vyne:pipeline-jet:jar:0.24.0-SNAPSHOT
[INFO] +- io.vyne:pipeline-jet-api:jar:0.24.0-SNAPSHOT:compile
[INFO] |  \- io.vyne:vyne-core-types:jar:0.24.0-SNAPSHOT:compile
[INFO] |     \- (org.jetbrains.kotlinx:kotlinx-coroutines-core:jar:1.7.0-Beta:compile - version managed from 1.7.0-Beta; omitted for duplicate)
```

I can  see that it [should be visible](https://github.com/Kotlin/kotlinx.coroutines/blob/master/kotlinx-coroutines-core/jdk8/src/future/Future.kt), but it just won't compile.

In the jar on my local repo, there doesn't appear to be any `kotlinx.coroutines.future` package:
![image](https://user-images.githubusercontent.com/348852/227512796-a4316d09-67bb-47f5-8146-11f8bc9e8743.png)

I've tried to rule out local build issues as much as possible.

**Comment by martypitt** [comment]
Ok, I've reproduced the issue, and in doing so now better understand what's happened.

Previously we were compiling with 1.6.4

Looks like under the old version `future` was an extension against `CoroutineContext`.  In `1.7.0-Beta`, it's against `CoroutineScope`.

I'm not sure if we were doing something invalid previously, and the new syntax is more "correct".  However, it took a bit of digging to get this worked out.

Here's a simple example:

```kotlin
import kotlinx.coroutines.CoroutineScope
import kotlinx.coroutines.Dispatchers
import kotlinx.coroutines.future.future
import kotlin.coroutines.CoroutineContext

internal object MyTransformationScope : CoroutineScope {
    override val coroutineContext: CoroutineContext
        get() = Dispatchers.Unconfined
}

fun doWork() {
    // Used to work
    MyTransformationScope.coroutineContext.future {
        TODO()
    }
    // now...
    MyTransformationScope.future { 
        
    }
}
```

```xml
  <properties>
        <maven.compiler.source>17</maven.compiler.source>
        <maven.compiler.target>17</maven.compiler.target>
        <project.build.sourceEncoding>UTF-8</project.build.sourceEncoding>
        <kotlin.version>1.8.10</kotlin.version>
        <!-- Coroutines 1.7.0-Beta is compatible with 1.8.10 as per https://github.com/Kotlin/kotlinx.coroutines -->
        <kotlin.coroutines.version>1.7.0-Beta</kotlin.coroutines.version>
    </properties>


    <dependencies>
        <dependency>
            <groupId>org.jetbrains.kotlinx</groupId>
            <artifactId>kotlinx-coroutines-jdk8</artifactId>
            <version>${kotlin.coroutines.version}</version>
        </dependency>
        <dependency>
            <groupId>org.jetbrains.kotlinx</groupId>
            <artifactId>kotlinx-coroutines-core</artifactId>
            <version>${kotlin.coroutines.version}</version>
        </dependency>

    </dependencies>
```

**Comment by martypitt** [comment]
To futher clarify - it looks like Maven was resolving to the wrong version, despite `dependencies:tree` telling me otherwise.

I've resolved the versioning problem.  The compilation issue was fixed using the above.

I don't believe this is a bug, but some docs around the change of the scope of the extension function could be helpful.

**Comment by dkhalanskyjb** [comment]
I don't think there ever was a `kotlinx.coroutines.future.future` that used a `CoroutineContext` as a receiver, so I have no idea why the code used to work. I guess it's a good thing it no longer does; probably some compiler bug got fixed. If you want to pursue this further, it would be interesting to see what caused this mystical `CoroutineContext.future` to appear, but then again, if there's no issue, then there's no issue.
