### ISSUE TITLE
[Flow]SafeCollector trigger twice after collect

### ISSUE THREAD

**Issue by OumaSyuu** [Kotlin/kotlinx.coroutines#3694]
Hello, I found something wired while using flow. The operator `flow {}` will trigger twice as I first collect. Here`s the log
![企业微信截图_16800553875917](https://user-images.githubusercontent.com/14196120/228408036-4f12f362-d9bd-4e6b-932f-a27752f60503.png)

Code in ` SmsRemoteDataSource ` like(`smsService` is a refrofit service)
```
 class SmsRemoteDataSource(private val smsService: SmsService) {

    fun getSmsVerifyCode(mobile: String): Flow<Unit> {
        Log.d(javaClass.simpleName, "getSmsVerifyCode: ")
        return flow {
            Log.d(javaClass.simpleName, "getSmsVerifyCode: ")
            val resp = smsService.getSmsVerifyCode(SmsService.GetSmsVerifyCodeParams(mobile))
            if (resp.code != 0 || resp.data == null) throw SmsError(Throwable(resp.msg))
            emit(resp.data)
        }
    }
} 
```

And I was collecting data like
```
 lifecycleScope.launchWhenResumed {
            loginViewModel.getSmsVerifyCode(phoneNum).collect {
                //do something
            }
        }
```

I was confused. I only call it once. Is there any sulotions?

**Comment by dkhalanskyjb** [comment]
Probably the whole `launchWhenResumed` block is called more than once. I don't know what it does, but `launchWhenResumed` is deprecated: https://developer.android.com/reference/kotlin/androidx/lifecycle/LifecycleCoroutineScope#launchWhenResumed(kotlin.coroutines.SuspendFunction1) I don't see a way for `Flow` to do something incorrect here.

**Comment by OumaSyuu** [comment]
Emm, but my `loginViewModel` holds the use case. If `launchWhenResumed ` called more than once, My remote data source must be called not just once. But I just found one log of my remote data source.

**Comment by OumaSyuu** [comment]
I had tried to use 'repeatOnLifecycle'. But it did not save my day.

**Comment by dkhalanskyjb** [comment]
Try to add a log between these two lines:
```
 lifecycleScope.launchWhenResumed {
            // <--- Log here
            loginViewModel.getSmsVerifyCode(phoneNum).collect {
```
This way, you can be sure this is called more than once.

**Comment by OumaSyuu** [comment]
I am sure it is called just one time.

![企业微信截图_16800832703760](https://user-images.githubusercontent.com/14196120/228496017-864a784c-b30e-44a0-80ea-7adcd383b6ba.png)

**Comment by hoc081098** [comment]
Because you use `also { it.launchIn(scope) }`. Please remove it
