### ISSUE TITLE
Error parsing triggers: Cannot find module 'atomicfu'

### ISSUE THREAD

**Issue by SUPERCILEX** [Kotlin/kotlinx.coroutines#370]
There doesn't seem to be an `atomicfu` npm library available when using `v0.23.0-dev-1` of the Coroutines JS lib.

**Comment by SUPERCILEX** [comment]
@elizarov This is still an issue in `v0.23.0`. Can't use Coroutines in JS.

**Comment by elizarov** [comment]
Confirm. Will fix in next update.

**Comment by jakub-frajt** [comment]
@elizarov It looks like that ```require``` in ```kotlinx-coroutines-core.js``` has wrong a module name **atomicfu** but this module has a name **kotlinx-atomicfu** in the package.json. Webpack cannot resolve a module name when I run a build. Can you look at this?

**Comment by elizarov** [comment]
I'll follow up in #396
