### ISSUE TITLE
`SharedFlow.toList(mutableList)`: difference behavior between 1.6.4 vs 1.7.0-Beta

### ISSUE THREAD

**Issue by hoc081098** [Kotlin/kotlinx.coroutines#3706]
Sometimes, I use this method to write simple test on SharedFlow.
Version 1.6.4 works well.
Since 1.7.0-Beta, this method is deprecated and the implementation seem be wrong

```kotlin
val acc = MutableList()
val job = scope.launch(start = Undispatched) {
  sharedFlow.toList(acc)
}

// later...

job.cancel()
assertContentEquals(
 expected = ...,
 actual = acc
)
```

IMO, the correct impl. is `SharedFlow.toList(acc) = (this as Flow).toList(acc)`

**Comment by psteiger** [comment]
+1 to this issue and proposed solution. Seems this commit changed the behavior: https://github.com/Kotlin/kotlinx.coroutines/commit/f981a1d00a9d75169321f5ef63fed16622c3e44f
