### ISSUE TITLE
Files with a link to this page in my META-INF! BUG???

### ISSUE THREAD

**Issue by Maxon1653** [Kotlin/kotlinx.coroutines#3707]
![Screenshot_20230410-143107](https://user-images.githubusercontent.com/126844761/230893643-926d9689-7f76-41f7-b9e1-cf6ba8d3598d.jpg)

![Screenshot_20230410-141552](https://user-images.githubusercontent.com/126844761/230893272-13d1815e-199a-47b0-b1b1-1dede180a341.jpg)

![Screenshot_20230410-141608](https://user-images.githubusercontent.com/126844761/230892848-7a777b54-54c2-49b5-9384-c1868516cad9.jpg)

![Screenshot_20230410-141608](https://user-images.githubusercontent.com/126844761/230892474-5c0cc9a2-9e25-440b-830f-28b33d15d55f.jpg)

**Describe the bug**

What happened? What should have happened instead?

**Provide a Reproducer**

* If possible, please provide a small self-contained project (or even just a single file) where the issue reproduces.
* If you can't pinpoint the issue, please provide at least *some* project where this reproduces, for example, your production one. If you are not ready to show the project publicly, we are open to discussing the details privately.
* If you really can't provide any code, please do still open an issue. This may prompt other people to chime in with their reproducers.

**Comment by qwwdfsad** [comment]
Please use slack or stackoverflow for general questions and fill in the required fields in a more detailed manner.

These files are not links, they specify fully-qualified name for service location via `ServiceLoader` -- a standard Java mechanism for dependency control
