### ISSUE TITLE
jdk11 jdeps 

### ISSUE THREAD

**Issue by valenpo** [Kotlin/kotlinx.coroutines#3708]
Migrating to jre11 and run jdeps show use of sun.misc.Signal and sun.misc.SignalHandler should I just ignore it?

`digraph "kotlinx-coroutines-core-jvm-1.6.4.jar" {
   "kotlinx.coroutines.debug.AgentPremain"            -> "sun.misc.Signal (JDK internal API (jdk.unsupported))";
   "kotlinx.coroutines.debug.AgentPremain"            -> "sun.misc.SignalHandler (JDK internal API (jdk.unsupported))";
}
`
thanks

**Comment by dkhalanskyjb** [comment]
Yes.

**Comment by valenpo** [comment]
@dkhalanskyjb thanks!
