### ISSUE TITLE
Add support for Kotlin/Wasm

### ISSUE THREAD

**Issue by soywiz** [Kotlin/kotlinx.coroutines#3713]
Couldn't find an issue about this.

Would be nice to get support for the WASM target so libraries and projects using kotlinx.coroutines can start experimenting with the target.

Related issue: https://github.com/Kotlin/kotlinx-atomicfu/issues/278

**Comment by y9san9** [comment]
Definitely waiting for it!

**Comment by dkhalanskyjb** [comment]
There's the "subscribe" button to the right of this issue, where you can configure notifications for when there are updates. No need to spam "+1," one feature request with the thumbs-up emoji underneath is enough.

**Comment by VladislavSumin** [comment]
For those who want to look at coroutines for wasm right now, you can connect an experimental repository 
```kotlin
        maven("https://maven.pkg.jetbrains.space/kotlin/p/wasm/experimental")
```
see: https://maven.pkg.jetbrains.space/kotlin/p/wasm/experimental/org/jetbrains/kotlinx/kotlinx-coroutines-core-wasm/

**Comment by bashor** [comment]
PR #3849

**Comment by hfhbd** [comment]
If possible, please also add wasmWasi.

**Comment by eygraber** [comment]
Is there any kind of timeline for this? I was waiting for it to get merged, but if it's going to be a while I'm going to isolate coroutines in the project I'm adding wasm support to so it doesn't block me (I'd rather just wait for the PR to get merged though :smile: )

**Comment by tw-atroehrsm** [comment]
+1 waiting for this :)
