### ISSUE TITLE
Retrying of test not fully supported with AndroidComposeTestRule

### ISSUE THREAD

**Issue by dabrosch** [Kotlin/kotlinx.coroutines#3718]
**What do we have now?**

When using a `TestRule` that retries a failed test you cannot use `AndroidComposeTestRule` inside of that `RetryTestRule`, because of [line 226](https://github.com/Kotlin/kotlinx.coroutines/blob/2653cd23991bcac4ed75018c5a3130f71df77cc2/kotlinx-coroutines-test/common/src/TestScope.kt#L226)  preventing a second execution in spite of the [leave() ](https://github.com/Kotlin/kotlinx.coroutines/blob/2653cd23991bcac4ed75018c5a3130f71df77cc2/kotlinx-coroutines-test/common/src/TestScope.kt#L248) function being called.

The `AndroidComposeTestRule` must be outside of the `RetryTestRule` in order to permit the retry of the test.

**What should be instead?**

It makes a lot more sense to allow the `AndroidComposeTestRule` be re-entered if `leave()` was called, so perhaps in the [enter()](https://github.com/Kotlin/kotlinx.coroutines/blob/2653cd23991bcac4ed75018c5a3130f71df77cc2/kotlinx-coroutines-test/common/src/TestScope.kt#L223) function we could instead check of leave() was executed and perform any necessary cleaning of objects from the last run and then permit the test to continue a second time.

**Why?**

Rule ordering would then not be an issue with respect to rules that retry tests.

**Why not?**

It might be more work to clear out the prior test run, or you might consider test-retrying to be an anti-pattern.

**Comment by dkhalanskyjb** [comment]
This library does not have any special code for Compose, and `AndroidComposeTestRule` is not part of this library. So, it would help if we discuss this purely in terms of what the coroutines library does wrong.

**On the JVM**, you can call `runTest` several times in a row, and nothing bad will happen:
```kotlin
fun someTest() {
  runTest {
  }
  runTest { // ok
  }
}
```
This even works if you repeat the test until it succeeds:
```kotlin
fun someTest() {
  while (true) {
    try {
      runTest {
      }
      break
    } catch (e: Exception) {
      println(e)
    }
  }
}
```

The only issue is if you reuse one `TestScope` several times to do that, which is forbidden:
```kotlin
fun someTest() {
  val scope = TestScope()
  scope.runTest {
  }
  scope.runTest { // not allowed
  }
}
```

However, this code is strange. *Why* would you need the `scope` outside of `runTest`? Typically, it would be to be able to launch some coroutines before `runTest` starts, so the more realistic example would look like this:
```kotlin
fun someTest() {
  val scope = TestScope()
  scope.launch {
  }
  scope.runTest {
  }
  scope.runTest { // not allowed
  }
}
```
There's an obvious issue with this: the coroutine launched before the first `runTest` needs to complete one way or another before the first `runTest` finishes, so the second `runTest` will need to work without it.

To fix this, one would have to do something like this:
```kotlin
fun someTest() {
  val scope = TestScope()
  while (true) {
    try {
      scope.launch {
      }
      runTest {
      }
      break
    } catch (e: Exception) {
      println(e)
    }
  }
}
```
However, at this point, why not just recreate the `scope` each time? The following would work perfectly fine:
```kotlin
fun someTest() {
  while (true) {
    try {
      val scope = TestScope()
      scope.launch {
      }
      runTest {
      }
      break
    } catch (e: Exception) {
      println(e)
    }
  }
}
```

Of course, this is a simplified example: typically, `scope` would be a field in the test class and can't be so easily recreated. However, the argument stays the same: if you *don't* do anything with the `TestScope`, then it makes no sense to keep it as a separate field, but if you *do* something with the `TestScope`, then for the test to work properly on subsequent invocations, all the code that uses the `TestScope` before `runTest` has to be rerun anew anyway.

**Comment by dabrosch** [comment]
You are correct. The real failure here is that the `AndroidComposeTestRule` that is not managed by you guys does not support retrying because it will not re-create the test environment. 

For the time being I have created a `RetryableAndroidComposeTestRule` wrapper which creates a new `AndroidComposeTestRule` for a subsequent retry of the test.

For anyone else, you will not be able to use Kotlin delegation to do it, so it is kinda ugly code, but it works.

**Comment by AShunevych** [comment]
Can you explain how exactly your rule should be implemented at practice? For example, in next rule chain :

```
//
val basicRule = createAndroidComposeRule<MyActivity>()  //  basic rule which starts test
val retryRule = RetryableComposeTestRule  { basicRule } // retry rule 
val flakyRule = FlakytestRule().allowFlakyAttemptsByDefault(2) // from Barista lib 

// So we have flaky rule as outerRule and all rules goes around

@get:Rule
val rulechain:RuleChain = run {
 RuleChain.outerRule (flakyRule ).around(basicRule ).around(retryRule) 
}

```
The problem in this case tests will restart, but line 226 with` IllegalStateException("Only a single call to `runTest` can be performed during one test.")` will be thrown

**Comment by dabrosch** [comment]
The ASOP project has finally been updated with a fix for this issue, see: https://android-review.googlesource.com/c/platform/frameworks/support/+/4072862
