### ISSUE TITLE
Add a security policy

### ISSUE THREAD

**Issue by pnacht** [Kotlin/kotlinx.coroutines#3721]
Sorry for not using one of the templates, couldn't find one that made sense for this issue!

A security policy (SECURITY.md) is a simple document that explains how the project wishes to receive and handle responsible disclosure of potential vulnerabilities. [GitHub recommends](https://docs.github.com/en/code-security/getting-started/securing-your-repository#setting-a-security-policy) that projects have one.

The security policy can be found by users who enter the project's "Security" panel. Having a policy file also adds references to it in the "New issue" page.

There are two main ways to receive such disclosures:
- register an email or website available to receive such reports; and/or
- use [GitHub's private vulnerability reporting](https://docs.github.com/en/code-security/security-advisories/repository-security-advisories/configuring-private-vulnerability-reporting-for-a-repository) feature

If you want to use GitHub's reporting system, it must be activated for the repository:
1. Open the repo's settings
2. Click on [Code security & analysis](https://github.com/Kotlin/kotlinx.coroutines/settings/security_analysis)
3. Click "Enable" for "Private vulnerability reporting"

I'll send a PR with a draft policy along with this issue. You could also create a https://github.com/Kotlin/.github repository and add the policy there, in which case the policy will be available in all of the org's projects.

---

**Disclosure:** My name is Pedro and I work with Google and the [Open Source Security Foundation (OpenSSF)](https://www.openssf.org/) to improve the supply-chain security of the open-source ecosystem.

**Comment by dkhalanskyjb** [comment]
Thanks! This is better solved on the organizational level. Here's the corresponding issue: https://youtrack.jetbrains.com/issue/KT-58245/Create-a-https-github.com-Kotlin-.github-repository-and-add-the-policy
