### ISSUE TITLE
A proposal for Await without copy Context.

### ISSUE THREAD

**Issue by koo-taejin** [Kotlin/kotlinx.coroutines#3726]
Hi.

Please, provides a function that does not copy Context when using Await.

First of all, I would like to say thank you for using this so well. :)

Why I suggest this
  1. In my case, there are things I want to call even if there is no ReactorContext, but I use it as it is to use the convenient features of Await.
  2. Copying ReactorContext is to use lots of resource than I thought.

My application uses 10% of cpu and 25% of memory allocation at this point. 
It would be good to refer to the issue below for the reason for such high resource consumption.
(https://github.com/reactor/reactor-core/issues/3446)

It looks not that difficult In my opinion.

By creating an argument called withContext in the Await.awaitOne method
If you make it like below, it seems that it can be implemented easily.

As before, if copy is set as the default value, it seems possible to support it without major issues, so I suggest that support this function please.

If you need the code, I'll change it like I said and give it to you.

If this offer is difficult to accept, I suggest a code change in `kotlinx.coroutines.reactor.ReactorContextInjector` like belows.

```
internal class ReactorContextInjector : ContextInjector {
    /**
     * Injects all values from the [ReactorContext] entry of the given coroutine context
     * into the downstream [Context] of Reactor's [Publisher] instances of [Mono] or [Flux].
     */
    override fun <T> injectCoroutineContext(publisher: Publisher<T>, coroutineContext: CoroutineContext): Publisher<T> {
        val reactorContext = coroutineContext[ReactorContext]?.context ?: return publisher
        return when(publisher) {
            is Mono -> publisher.contextWrite(reactorContext)  // -> contextWrite {c -> reactorContext.putAll(c)}
            is Flux -> publisher.contextWrite(reactorContext)  // -> contextWrite {c -> reactorContext.putAll(c)}
            else -> publisher
        }
    }
}

```

Below is the code comparing the two.
When running with AsyncProfiler individual tests on my MACBook

CPU
     - as-is: 1,483,000
     - to-be: 186,000
Memory Allocation
     - as-is: 28g
     - to-be : 13g

```
class AwaitTest {

    val count = 10000000;

    @org.junit.Test
    fun testMonoAwaitContextPropagation() {
        val mapOf = mapOf(1 to "a", 2 to "b", 3 to "c", 4 to "d", 5 to "e", 6 to "f", 7 to "g")

        runBlocking(Context.of(mapOf).asCoroutineContext()) {
            val createMono = createMono()

            for (i in 1..count) {
                val injectCoroutineContext = injectCoroutineContext(createMono, coroutineContext)
                injectCoroutineContext.subscribe { v ->  }
            }
        }
    }


    @org.junit.Test
    fun testMonoAwaitContextPropagation2() {
        val mapOf = mapOf(1 to "a", 2 to "b", 3 to "c", 4 to "d", 5 to "e", 6 to "f", 7 to "g")

        runBlocking(Context.of(mapOf).asCoroutineContext()) {
            val createMono = createMono()

            for (i in 1..count) {
                val injectCoroutineContext = injectCoroutineContext2(createMono, coroutineContext)
                injectCoroutineContext.subscribe { v ->  }
            }
        }
    }


    private fun createMono(): Mono<String> = mono {
        val ctx = reactorContext()
        ctx.getOrDefault(7, "noValue")
    }

    private suspend fun reactorContext() = coroutineContext[ReactorContext]!!.context

    fun <T> injectCoroutineContext(publisher: Mono<T>, coroutineContext: CoroutineContext): Mono<T> {
        val reactorContext = coroutineContext[ReactorContext]?.context ?: return publisher
        return when (publisher) {
            is Mono -> publisher.contextWrite(reactorContext)
            else -> publisher
        }
    }

    fun <T> injectCoroutineContext2(publisher: Mono<T>, coroutineContext: CoroutineContext): Mono<T> {
        val reactorContext = coroutineContext[ReactorContext]?.context ?: return publisher
        return when (publisher) {
            is Mono -> publisher.contextWrite { c -> reactorContext.putAll(c) }
            else -> publisher
        }
    }
    
}
```

Thanks.

**Comment by koo-taejin** [comment]
@dkhalanskyjb 

Thank you for your comments.
I commented that an option that does not copy context is needed.
In case it is not accepted, it is suggested to change the copy order as the next best way, so you don't have to worry too much about that part.
I respect all of your opinions.

Thank :)

**Comment by dkhalanskyjb** [comment]
If you respect all of my opinions, then at least read them. I've explained why I don't like the idea of changing the copy order.

**Comment by koo-taejin** [comment]
Yes I understand that perfectly. :)

**Comment by dkhalanskyjb** [comment]
As a workaround until the issue is fixed on the Reactor's side, this function may help:
```kotlin
suspend fun <T> withoutReactorContext(block: suspend CoroutineScope.() -> T) =
    withContext(currentCoroutineContext().minusKey(ReactorContext), block)
```
It strips away the reactor context from the coroutine context for the duration of the block execution, so copying does not happen.

Example:
```kotlin
val result = withoutReactorContext {
  mono.awaitSingleOrNull()
}
```

**Comment by koo-taejin** [comment]
I'm not familiar enough with Coroutines and Reactor.
So I thought how to change it so that the Context would not be delivered, but thank you for letting me know a good way.
I am going to use this as a reference.
Thanks :)
