### ISSUE TITLE
Flow.scan can accept a suspending function for providing its initial value

### ISSUE THREAD

**Issue by NinoDLC** [Kotlin/kotlinx.coroutines#3732]
**Use case**

I have a suspending function giving me the initial value that a `scan` function should have. Example: 
```
fun invoke(): Flow<Int> = someFlow.scan(getBar()) {
    // ...
}

suspend fun getBar(): Int // ...
```

Currently, either I have to:
* make the `invoke` function a suspending function, which sounds like a bad idea since it's returning a Flow (because the coroutine context used for retrieving the `getBar` wouldn't be necessarily the coroutine context used for collecting the flow). Example: 
```
suspend fun invoke(): Flow<Int> = someFlow.scan(getBar()) {
    // ...
}

suspend fun getBar(): Int // ...
```
* use a "one shot" flatMapLatest which is a bit confusing (hey Rx, you're back 😄 ?) since Kotlin is very friendly with its operators, allowing the lambda to be suspending. Example: 
```
fun invoke(): Flow<Int> = flow { 
    emit(getBar()) 
}.flatMapLatest { bar ->
    someFlow.scan(bar) {
        // ...
    }
}

suspend fun getBar(): Int // ...
```
* use a "flow in a flow" trick which is error prone (forgetting the collect is very easy and there's no lint for that). Example: 
```
fun invoke(): Flow<Int> = flow {
    val bar = getBar()
    someFlow.scan(bar) {
        // ...
    }.collect {
        emit(it)
    }
}

suspend fun getBar(): Int // ...
```

**The Shape of the API**

Something along: 
```
public fun <T, R> Flow<T>.scan(initial: suspend () -> R, operation: suspend (accumulator: R, value: T) -> R): Flow<R>
```

Usage: 
```
fun invoke(): Flow<Int> = someFlow.scan(
    initial = { getBar() },
) {
    // ...
}

suspend fun getBar(): Int // ...
```

**Comment by dkhalanskyjb** [comment]
Hi!
> Use case

This is not a use case, this is the shape of the code you have now and an explanation of why you want something different. What exactly are you trying to solve with this code? Depending on the answer, it may turn out that, yes, `invoke` should be a `suspend` function, or that you shouldn't use `scan` at all, or something like that. Or it may turn out that you're right, and there *are* some use cases that would be solved by the solution you're proposing. Without use cases, there's no way of knowing.

**Comment by NinoDLC** [comment]
Sorry, english is not my native langage so I might be completely off the roads here. But I guess you want to understand my business logic ? I simplified it a bit to the most basic need I have.

The `someFlow` is an infinite flow (SharedFlow for that matter) representing the different keyboard keys (like "up" or "down") the user can press (on Android). I am `scan`ing this Flow to emit a value that will usually start at 0, and if the user presses "up", it will emit "1", and then if the user presses "down" twice, it will emit "0" and "-1". Etc, you get it. 

I say "usually start" because it is critical to persist the last value emitted and start back to it, would the application (or flow collection) restart. 

So I am using a `.onEach { saveValueToDatabase(it) }` after the `scan` to persist it. 

You guessed it, `getBar()` is `getValueFromDatabase()`. 

I hope I helped you understand my use case.

**Comment by dkhalanskyjb** [comment]
Yes, business logic is what we're interested in.

You're saying that "flow in a flow" is error-prone, but I disagree: if you forget a `collect`, nothing will function, you'll notice that something is wrong, check the code and, well, add the `collect` call. But the solution you're proposing *is* error-prone: in a multi-threaded context, it's easy to accidentally create several flows that do `scan` and try to write conflicting values to the database. Such a bug would be difficult to find and not noticeable at a glance but would sometimes cause the number to be off by something like ±1.

What do you think of this solution instead? (Pseudocode)
```kotlin
val keypressSharedFlow = SharedFlow<KeyPress>()

val valueStateFlow by lazy {
  // `lazy` ensures that the subscription code below is only run when someone requests it.
  // by default, `lazy` ensures that the initialization is only run once. 
  StateFlow<Int>().also { stateFlowToEmitTo ->
    someScope.launch {
      val initialValue = getValueFromDatabase()
      keypressSharedFlow.scan(initialValue) {
        // ...
      }.collect {
        stateFlowToEmitTo.value = it
        saveValueToDatabase(it)
      }
    }
  }
} // the interested parties need to subscribe to this.
```

**Comment by NinoDLC** [comment]
Yes, passing a scope would also solve the issue, but it's kinda like making the `invoke` function suspending, isn't it ? Feels weird to pass a coroutine scope in order to retrieve a Flow.

**Comment by dkhalanskyjb** [comment]
The question is not what feels weird style-wise but what shows your intentions better.

I agree that it probably makes sense for `scan` to accept a `suspend` function for infinite flows where the collection was interrupted and needs to restart. However, in your particular case, I think it makes sense to encode that only one flow can interact with the database, and having a separate (and visible in the debugger) collection coroutine helps with that.

Also, it's likely that you only want to interact with the database from some threads and not others. With the approach of having a dedicated scope, you can ensure that easily: just specify the correct dispatcher for the scope. When just returning the flow, it's not so simple: you either need `withContext(CorrectDispatcher)` around your database access calls, or use `flowOn`, or you have to make sure that the flow you return is only collected in the correct context.

**Comment by dkhalanskyjb** [comment]
`hoc081098/FlowExt` has had this for a while now, and here is a usage: https://github.com/Kotlin-Android-Open-Source/MVI-Coroutines-Flow/blob/54f5ea87b032773fb8cb640e1f24e2e382069942/data/src/main/java/com/hoc/flowmvi/data/UserRepositoryImpl.kt#L83-L97

Simplifying:

```kotlin
private val changesFlow = MutableSharedFlow<Change>(extraBufferCapacity = 64)

private suspend fun getUsersFromRemoteWithRetry(): List<User>

val usersFlow =
    changesFlow
      .scanWith(::getUsersFromRemoteWithRetry) { acc, change ->
        when (change) {
          is Change.Removed -> acc.filter { it.id != change.removed.id }
          is Change.Refreshed -> change.user
          is Change.Added -> acc + change.user
        }
      }
```

Let's look at it closely. This code receives snapshots, and then also receives changes on top of the snapshots.

First, let's assign consecutive numbers to changes: change 1, change 2, change 3, etc.
Now, imagine that at some point we subscribe to `getUsers`. As implemented, `scanWith` (https://github.com/hoc081098/FlowExt/blob/d288e67a72a90b17819cccdd2df744102d1260ae/src/commonMain/kotlin/com/hoc081098/flowext/scanWith.kt) will first query `getUsersFromRemoteWithRetry` and then subscribe to `changesFlow` to get updates.

Imagine we receive a snapshot that records the changes 1-200. If someone else collects `usersFlow` in parallel before we've subscribed, we will lose the new changes. For example, if we subscribe at the moment the second `usersFlow` collection has consumed the change 205, then changes 201-205 will be lost. Setting a `replayBuffer` of a `MutableSharedFlow` to a large value would make this data race more difficult to achieve, but not impossible.

It's necessary to have a second `usersFlow` collection running in parallel for this issue to occur, so the code I'm linking to looks completely fine. That said, it would probably be a mistake for a general-purpose concurrency library to introduce a primitive that inherently has a built-in race condition.

Thanks for the suggestion! This seems error-prone in general, so we won't be adding this, but it was worth considering.
