### ISSUE TITLE
channelFlow cancellation works incorrectly if cancelled through parent

### ISSUE THREAD

**Issue by anton-kapelyushok** [Kotlin/kotlinx.coroutines#3757]
Can be reproduced on:
kotlin("jvm") version "1.7.21"
implementation("org.jetbrains.kotlinx:kotlinx-coroutines-core:1.7.0-RC")

(Also in 1.8.21 playground)

The [following code](https://play.kotlinlang.org/#eyJ2ZXJzaW9uIjoiMS44LjIxIiwicGxhdGZvcm0iOiJqYXZhIiwiYXJncyI6IiIsIm5vbmVNYXJrZXJzIjp0cnVlLCJ0aGVtZSI6ImlkZWEiLCJjb2RlIjoiaW1wb3J0IGtvdGxpbnguY29yb3V0aW5lcy4qXG5pbXBvcnQga290bGlueC5jb3JvdXRpbmVzLmNoYW5uZWxzLkNoYW5uZWxcbmltcG9ydCBrb3RsaW54LmNvcm91dGluZXMuY2hhbm5lbHMuUmVjZWl2ZUNoYW5uZWxcbmltcG9ydCBrb3RsaW54LmNvcm91dGluZXMuY2hhbm5lbHMuU2VuZENoYW5uZWxcbmltcG9ydCBrb3RsaW54LmNvcm91dGluZXMuY2hhbm5lbHMuYXdhaXRDbG9zZVxuaW1wb3J0IGtvdGxpbnguY29yb3V0aW5lcy5mbG93LmJ1ZmZlclxuaW1wb3J0IGtvdGxpbnguY29yb3V0aW5lcy5mbG93LmNoYW5uZWxGbG93XG5pbXBvcnQga290bGlueC5jb3JvdXRpbmVzLmZsb3cudGFrZVxuXG5mdW4gbWFpbigpIHtcbiAgICBydW5CbG9ja2luZyhEaXNwYXRjaGVycy5EZWZhdWx0KSB7XG4gICAgICAgIGRhdGEgY2xhc3MgTXNnKHZhbCBjaDogU2VuZENoYW5uZWw8U3RyaW5nPilcblxuICAgICAgICB2YWwgbXNncyA9IENoYW5uZWw8TXNnPigpXG5cbiAgICAgICAgbGF1bmNoIHtcbiAgICAgICAgICAgIHRyeSB7XG4gICAgICAgICAgICAgICAgdmFsIG0gPSBtc2dzLnJlY2VpdmUoKVxuICAgICAgICAgICAgICAgIG0uY2guc2VuZChcIjFcIilcbiAgICAgICAgICAgICAgICBtLmNoLnNlbmQoXCIyXCIpXG4gICAgICAgICAgICB9IGNhdGNoIChlOiBUaHJvd2FibGUpIHtcbiAgICAgICAgICAgICAgICBwcmludGxuKFwiQ2FuY2VsZWQgd2l0aCAkZVwiKVxuICAgICAgICAgICAgICAgIHRocm93IGVcbiAgICAgICAgICAgIH1cbiAgICAgICAgfVxuXG4gICAgICAgIGxhdW5jaCB7XG4gICAgICAgICAgICB2YWwgZiA9IGNoYW5uZWxGbG93IHtcbiAgICAgICAgICAgICAgICBtc2dzLnNlbmQoTXNnKGNoYW5uZWwpKVxuICAgICAgICAgICAgICAgIGF3YWl0Q2xvc2Uge31cbiAgICAgICAgICAgIH1cblxuICAgICAgICAgICAgZi5idWZmZXIoMClcbiAgICAgICAgICAgICAgICAudGFrZSgxKVxuICAgICAgICAgICAgICAgIC5jb2xsZWN0IHtcbiAgICAgICAgICAgICAgICAgICAgcHJpbnRsbihcIkNvbGxlY3RlZCAkaXRcIilcbi8vICAgICAgICAgICAgICAgICAgICBjb3JvdXRpbmVTY29wZSB7IGNhbmNlbCgpIH1cbi8vICAgICAgICAgICAgICAgICAgICBjYW5jZWwoKVxuICAgICAgICAgICAgICAgIH1cbiAgICAgICAgfVxuICAgIH1cbn0ifQ==) behaves behaves strange:

If `coroutineScope { cancel() }` is uncommented, it produces
```
Collected 1
Canceled with kotlinx.coroutines.JobCancellationException: ScopeCoroutine was cancelled; job=ScopeCoroutine{Cancelled}@779f7413
```
as expected

If `cancel()` is uncommented instead, it produces just
```
Collected 1
```
and the program never terminates

Expected:
Same output as in first example
Program terminates

```
fun main() {
    runBlocking(Dispatchers.Default) {
        data class Msg(val ch: SendChannel<String>)

        val msgs = Channel<Msg>()

        launch {
            try {
                val m = msgs.receive()
                m.ch.send("1")
                m.ch.send("2")
            } catch (e: Throwable) {
                println("Canceled with $e")
                throw e
            }
        }

        launch {
            val f = channelFlow {
                msgs.send(Msg(channel))
                awaitClose {}
            }

            f.buffer(0)
                .take(1)
                .collect {
                    println("Collected $it")
//                    coroutineScope { cancel() }
//                    cancel()
                }
           }
        }
    }
}
```

**Comment by qwwdfsad** [comment]
This is not a bug in coroutines, but rather in our tooling: https://youtrack.jetbrains.com/issue/KTIJ-16542/Ambiguous-coroutineContext-inspection-shall-report-suspending-lambdas-nested-inside-CoroutineScope-block

1) With `coroutineScope { cancel() }`, it throws `CancellationException` immediately, forcing `collect` to rethrow it, which, in fact, immediately cancels the channel (cancelling the channel producer as well)

2) With `cancel` nothing really happens -- the consuming coroutine is cancelled, while the channel is left in the state "waiting for somebody to receive the second element".

If your coroutine is the only channel consumer, you can do the following:
`awaitClose { msgs.cancel(it) }`
