### ISSUE TITLE
Investigate possibility to implement runBlocking on Node.js using async_hooks

### ISSUE THREAD

**Issue by qwwdfsad** [Kotlin/kotlinx.coroutines#376]
[`async_hook`](https://github.com/nodejs/node/blob/master/doc/api/async_hooks.md) API since Node  8 looks like a way to implement `runBlocking`.
We should investigate whether it's fully applicable

**Comment by qwwdfsad** [comment]
Also, we can use a mechanism similar to [zones.js](https://github.com/angular/zone.js/) and patch every asynchronuous entry point (in addition to intercepting our own coroutines) when stepping into `runBlocking`

**Comment by qwwdfsad** [comment]
After investigation, it seems like `runBlocking` can be implemented only on Node.js using `deasync` or via ES6 async/await methods (then `runBlocking` on JS should be `async`)

**Comment by ScottPierce** [comment]
@qwwdfsad Babel has a polyfill for async/await that allows async/await on all versions of JS.
