### ISSUE TITLE
Stack size becomes negative after instruction [406] pop in

### ISSUE THREAD

**Issue by DominykasZaksas** [Kotlin/kotlinx.coroutines#377]
_Stack size becomes negative after instruction [406] pop in [com/myProject/myApp/Networking/NetworkManager$requestAsyncWithRetry$2.doResume(Ljava/lang/Object;Ljava/lang/Throwable;)Ljava/lang/Object;]_

function's signature 
`suspend fun <T> requestAsyncWithRetry(call : Call<T>, callName : String = "Unknown") : ResponseObject<T>`

I am running Android Studio Canary 16 with kotlin 1.2.41 & kotlinx-coroutines-core:0.22.5
I started having this issue and the only work around is to add
 

`   lintOptions {

        checkReleaseBuilds false

         // Or, if you prefer, you can continue to check for errors in release builds,

        // but continue the build even when errors are found:

        abortOnError false

    }
`

and add a flag to pro-guard file
`-dontoptimize`

Any suggestions how to solve this? What can be the cause?

**Comment by elizarov** [comment]
@DominykasZaksas Can you reproduce this problem with some self-contained examples or otherwise share the code that reproduces it?

**Comment by qwwdfsad** [comment]
@DominykasZaksas any update on that?

**Comment by DominykasZaksas** [comment]
the bug remains with 1.2.51. I will give another go at making self-contained example over the weekend. I might also try 1.3

**Comment by DominykasZaksas** [comment]
Please see the linked repo [https://github.com/DominykasZaksas/negativeStack](https://github.com/DominykasZaksas/negativeStack)

Narrowed down the problem to AnkoLogger and its struggles to log on a background thread. Also, proguard file that strips out a log message somehow affects this all too.

I don't actually use anko logger as I didn't figure out how to handle it in debug and release builds (i guess that's part of the problem) but I didn't remove the code either.

Negative stack size occurs when you try to build the app for release. Debug works fine. If you remove proguard options for log messages this will also make the app compile without problems

**Comment by qwwdfsad** [comment]
It appears o be a bug in proguard 4.7.
Please update default Android SDK's proguard to 6.0.1 and check if the problem is still reproducible
