### ISSUE TITLE
Join does not complete on class extending from AbstractCoroutine

### ISSUE THREAD

**Issue by hsyed** [Kotlin/kotlinx.coroutines#378]
This gist of my class is as follows. `join` never completes after a `cancel`.  `cancel` followed by `joinChildren` does complete however -- `isCompleted` returns true when debugging it so I don't understand why the `join` doesn't complete -- it's not clear from the API what I need to do.

```
internal class QueueReactor(
...
   private val dispatcher: CoroutineDispatcher,
...
) : AbstractCoroutine<Unit>(
    newCoroutineContext(dispatcher + CoroutineName("q-${config.queueName}"), null),
    active = false
) {

    override fun onStart() {
        repeat(config.reactorCount) {
            launch(
                coroutineContext + CoroutineName("q-${config.queueName}-$it"),
                parent = this
            ) {
                while (true) {
                    processBatch(coroutineContext).join()
                }
            }
        }
    }
```

testing it with this

```
        processorJob.cancel()
            runBlocking {
                try {
                    withTimeout(5000) {
                        processorJob.joinChildren()
                    }
                } catch(ex: TimeoutCancellationException) {
                    throw RuntimeException("could not shut down reactorJob", ex)
                }
```

**Comment by qwwdfsad** [comment]
Can you please provide self-contained reproducer?

E.g.
```
internal class QueueReactor(dispatcher: CoroutineDispatcher = CommonPool) : AbstractCoroutine<Unit>(
    newCoroutineContext(dispatcher + CoroutineName("q-1"), null),
    active = false
) {

    override fun onStart() {
        repeat(10) {
            launch(
                context + CoroutineName("q-$it"),
                parent = this
            ) {
                while (true) {
                    processBatch(context).join()
                }
            }
        }
    }

    private fun processBatch(coroutineContext: CoroutineContext): Job {
        return launch(coroutineContext) {
            println("Child")
        }
    }
}

fun main(args: Array<String>) = runBlocking<Unit> {
    val processorJob = QueueReactor()
    processorJob.start()
    processorJob.cancel()
    runBlocking {
        try {
            withTimeout(5000) {
                processorJob.joinChildren()
            }
        } catch (ex: TimeoutCancellationException) {
            println("Caught")
            throw RuntimeException("could not shut down reactorJob", ex)
        }
    }
}
```
Works just fine

**Comment by hsyed** [comment]
Hmm my bad, I meant to show a `join` and not a `joinChildren` the latter works fine. 

```
internal class QueueReactor(dispatcher: CoroutineDispatcher = CommonPool) : AbstractCoroutine<Unit>(
    newCoroutineContext(dispatcher + CoroutineName("q-1"), null),
    active = false
) {

    override fun onStart() {
        repeat(10) {
            launch(
                context + CoroutineName("q-$it"),
                parent = this
            ) {
                while (true) {
                    processBatch(context).join()
                }
            }
        }
    }

    private fun processBatch(coroutineContext: CoroutineContext): Job {
        return launch(coroutineContext) {
            println("Child")
        }
    }
}

fun main(args: Array<String>) = runBlocking<Unit> {
    val processorJob = QueueReactor()
    processorJob.start()
    processorJob.cancel()
    runBlocking {
        try {
            withTimeout(5000) {
                processorJob.join()
            }
        } catch (ex: TimeoutCancellationException) {
            println("Caught")
            throw RuntimeException("could not shut down reactorJob", ex)
        }
    }
}
```

**Comment by qwwdfsad** [comment]
Thanks.

The problem is that usage of `AbstractCoroutine` implicitly implies, that it has a body which is actually executed on start, e.g. via `public fun start(start: CoroutineStart, block: suspend () -> T)`.

But even then, it has clumsy and undocumented interference with laziness (`active = false`), so I'd rather not to use `AbstractCoroutine` directly: it's undocumented, written for our own integration purposes and [probably] has bugs in use-cases other than the ones in `kotlinx.coroutines`.

Could you please elaborate, why do you have to use `AbstractCoroutine` directly?
E.g. why not a wrapper/delegate around `launch(start = LAZY)`?

**Comment by hsyed** [comment]
In general I could have created a wrapper base class with a `start` and `stop` that enforces some lifecycle constraints (`startOnce`), I could have even wrapped a base class from  [Guava Service](https://github.com/google/guava/wiki/ServiceExplained) -- we use these a lot in our codebase. With Guava it's possible to come up with fairly robust startup sequences with service interdependencies by injecting (DI) other services and simply using `wait`. Or you can have a  `ServiceManager` manage a list of `Service`s. 

The `DI` element is important above we have a sizeable mono repo with all sorts of frameworks and our modules are either `guice` or `dagger2`.  `dagger2` is used to create isolated subgraphs responsible for a particular task, these generally return a `Service`. 

I asked a bit about Job/Actor supervision in another issue, that is perhaps in scope for this discussion. The queue example above as a component could make use of traditional Actor supervision so I was trying to use a single top level job (AbstractCoroutine) to capture all of the sub jobs it creates.  

You asked in the other thread what Job supervision might mean if we had actor supervision. Managing a list of Jobs as a unit like the`ServiceManager` does with similar observable lifecycle events and semantics might be Job Supervision ?

I think if the actors are "addressable" and superviseable like in akka the list of jobs vs graph of jobs aspect distinction does not matter -- but then we are talking about having to launch something akin to an `ActorSystem` which is a bit heavier then just being able to manage a list of jobs.

**Comment by qwwdfsad** [comment]
>The queue example above as a component could make use of traditional Actor supervision so I was trying to use a single top level job (AbstractCoroutine) to capture all of the sub jobs it creates.

What benefits do you have by implementing it via extending `AbstractCoroutine` in comparison with an outer job created via `launch`? `AbstractCoroutine` is kind of unstable, so I'd like to know whether it's useful and what for.

>Managing a list of Jobs as a unit like theServiceManager does with similar observable lifecycle events and semantics might be Job Supervision ?

`ServiceManagers` looks to me as simple yet useful abstraction for implementing job supervision, though it's (currently) beyond `kotlinx.coroutines`.

>I think if the actors are "addressable" and "superviseable" like in akka the list of jobs vs graph of jobs aspect distinction does not matter

Not sure that actors and fire-and-forget jobs are semantically equialent in terms of supervision, but I'm not ready to make any claims about it now

**Comment by qwwdfsad** [comment]
Hi @hsyed 
Any updates?
