### ISSUE TITLE
Rendered API docs for future package are broken

### ISSUE THREAD

**Issue by abrooksv** [Kotlin/kotlinx.coroutines#3780]
**Describe the bug**
Not sure if this is the best place to report doc issues on the Kotlin website

https://kotlinlang.org/api/kotlinx.coroutines/kotlinx-coroutines-core/kotlinx.coroutines.future/#-2135376658%2FFunctions%2F-1471630244

Docs list the receiver as `<Error class: unknown class>`

**Comment by mjovanc** [comment]
This is feels like an issue with Dokka. We currently use 1.8.10 Beta, by switching to 1.8.20 Beta didn't solve anything when I tried locally. I have reported a bug: https://github.com/Kotlin/dokka/issues/3146

If this gets resolved in an upcoming PR (by them or me), I will try submit PR here to update the version with the fixes.

**Comment by dkhalanskyjb** [comment]
Seems to work fine now.
