### ISSUE TITLE
Extra methods generated in specific case (lambdas not inlined?)

### ISSUE THREAD

**Issue by thevery** [Kotlin/kotlinx.coroutines#380]
Coroutines calls (not library itself) aren't cheap compared to rx java (3 extra methods for `launch` + `withContext` compared to `fromCallable` + `subscribe`), but this issue makes migration even more difficult when you are at the dexcount limit on android.

34214 vs 34216 methods when you move `finalLabelToMark` line into `launch`.

Minimal sample:
```
package com.thevery.sample.dexcount

import android.support.annotation.Keep
import kotlinx.coroutines.experimental.CommonPool
import kotlinx.coroutines.experimental.launch

class DexCountHelper {

    private val labelsToMark = setOf<String>()
    private val originalState = mapOf<String, MarkedState>()

    enum class MarkedState {
        MARKED_ALL, MARKED_SOME, MARKED_NONE
    }

    @Keep
    fun coroutines() {
        val finalLabelToMark = labelsToMark.filter { lid -> originalState[lid] != MarkedState.MARKED_ALL }

        launch(CommonPool) {
            // +2 methods here :(
            // val finalLabelToMark = labelsToMark.filter { lid -> originalState[lid] != MarkedState.MARKED_ALL }
            println("finalLabelToMark = $finalLabelToMark")
        }
    }
}
```

Full android project: https://github.com/thevery/kotlin-coroutines-dexcount (run `./gradlew assembleDebug` for full dexcount and `./gradlew assembleRelease` for proguarded build).

**Comment by qwwdfsad** [comment]
It's not a `kotlinx.coroutines` problem.
`launch` body generates an inner class for lambda (~state machine), `labelsToMark` and `originalState` are private fields of `DexCountHelper` and you use these fields from `launch` body.
According to JLS, an inner class cannot directly access private fields (which are captured by `launch` closure), so compiler (doesn't matter whether it's Java or Kotlin) generates public synthetic accessors for these fields. The more private fields you capture in the lambda, the more synthetic methods will appear, and they cannot be eliminated by dexguard.
If you will replace `launch` with *any* method with non-inline lambda, nothing changes.

You can read more here: https://medium.com/thoughts-overflow/effects-of-javas-synthetic-accessor-methods-in-android-bb67b3bac22e
