### ISSUE TITLE
Update toolchain and compiler to kotlin 1.9

### ISSUE THREAD

**Issue by igoriakovlev** [Kotlin/kotlinx.coroutines#3812]
Please update the Toolchain and Compiler version for Kotlin 1.9.

The kotlin/wasm needs to be latest version of the compiler to add its support to this library. This is why we need to have the latest version of the kotlin gradle plugin and compiler.

**Comment by qwwdfsad** [comment]
Fixed in `develop`, you can use it as the base branch for WASM target

**Comment by dhakehurst** [comment]
when will this be published to maven central ?
