### ISSUE TITLE
Can I put an item at head of Channel?

### ISSUE THREAD

**Issue by kobe2000** [Kotlin/kotlinx.coroutines#383]
Hi
Is there any API like `LinkedBlockingDeque.addFirst` to buffered Channel？
I am implementing a process putting data back to channel again when there is something wrong in worker thread

**Comment by jcornaz** [comment]
No channel are always FIFO.

But why do you need it? the worker might simply remember the element, can't it?

```kotlin
val worker = actor<Element> {
  var element: Element = receive()

  while (isActive) { // execute until the cancellation of the coroutine
    try {
      handle(element)
      element = receive() // this won't be called if `handle` throw an error
    } catch (t: Throwable) {
      println("something went wrong") // consume the exception, eventually log it.
    }
  }
}
```

In this example, we receive the next element, only if the last element has been successfully handled.

**Comment by qwwdfsad** [comment]
You can't. Moreover, `addFirst` cannot be implemented on top of Channel underlying data structure.
