### ISSUE TITLE
consider exposing the Executor from a CoroutineDispatcher.

### ISSUE THREAD

**Issue by hsyed** [Kotlin/kotlinx.coroutines#385]
In various contexts (--e.g., dagger2 producers, various guava async utils) the `Executor` could be the same as the coroutine dispatcher. Could we get access to the executor so that we can use it directly at least on `CommonPool` and user created `ThreadPoolDispatcher`. Having to inject both or provide both is annoying.

**Comment by qwwdfsad** [comment]
Why `executor.asCoroutineDispatcher()` is not applicable for this purpose?

**Comment by qwwdfsad** [comment]
In general, going back is not always possible.
E.g. in `CommonPool` underlying pool will be soon replaced by our own hand-rolled thread pool which may be not an instance of `Executor`.

One of the solutions is to provide access to the underlying executor for executor-based dispatchers (`asCoroutineDispatcher`, `newFixedThreadPoolContext`, `newSingleThreadContext`).
But going from executor to dispatcher will always cost you an allocation if you have only an executor.

**Comment by hsyed** [comment]
@qwwdfsad Yes that is what I was thinking of.
