### ISSUE TITLE
Unresolved reference: btnApply

### ISSUE THREAD

**Issue by Anianonymous** [Kotlin/kotlinx.coroutines#3852]
package com.devani.pekka

import androidx.appcompat.app.AppCompatActivity
import android.os.Bundle
import android.widget.Button

class MainActivity : AppCompatActivity() {
    override fun onCreate(savedInstanceState: Bundle?) {
        super.onCreate(savedInstanceState)
        setContentView(R.layout.activity_main)
        btnApply
    }
}

when I clicked alt+enter on btnApply, it doesn't import kotlinx.android.synthetic.main.activity_main.*

**Comment by qwwdfsad** [comment]
It has nothing to do with kotlinx.coroutines, please refer to Slack or StackOverflow for general questions

**Comment by Anianonymous** [comment]
> It has nothing to do with kotlinx.coroutines, please refer to Slack or StackOverflow for general questions

Ya thank you
