### ISSUE TITLE
Full-text search on API docs page leads to 404

### ISSUE THREAD

**Issue by SebastianAigner** [Kotlin/kotlinx.coroutines#3862]
- Go to https://kotlinlang.org/api/kotlinx.coroutines/kotlinx-coroutines-core/kotlinx.coroutines/ensure-present.html (or any other page)
- Type "delay" into the search field in the top right
- The first search result leads to https://kotlinlang.org/api/kotlinx.coroutines/kotlinx-coroutines-jdk8/kotlinx.coroutines.time/delay.html, which is a 404.

Reproduces with other function names such as `withTimeout` as well.

**Comment by nikpachoo** [comment]
@SebastianAigner, thanks for reporting the issue. The fix has been applied.
