### ISSUE TITLE
Two instances of DebugProbesImpl if IJ plugin has dependency on coroutines

### ISSUE THREAD

**Issue by gorrus** [Kotlin/kotlinx.coroutines#3883]
STR:
take the sample plugin project from: https://youtrack.jetbrains.com/issue/IDEA-322730#focus=Comments-27-8045387.0-0
use 1.15.1-SNAPSHOT ij gradle plugin: https://youtrack.jetbrains.com/issue/IDEA-322730#focus=Comments-27-8065352.0-0

start debug in IDEA,
as a result there will be two loaded instances of DebugProbesImpl, coroutine debugger in IDEA will pick the wrong one and fail to work.
![image](https://github.com/Kotlin/kotlinx.coroutines/assets/10279003/64cdf777-0558-41eb-94d5-c27cab1c5fe0)

**Comment by gorrus** [comment]
it seems that the second DebugProbesImpl instance is loaded from the instrumented code:
![image](https://github.com/Kotlin/kotlinx.coroutines/assets/10279003/921c31be-39a8-44a5-8922-1dd33631c450)

**Comment by qwwdfsad** [comment]
The issue appeared to be on IJ side: it has a non-trivial hierarchy of classloaders (that also differ in debug and prod builds) that sometimes share and sometimes not the loaded identity of `kotlin.coroutines.jvm.internal.DebugProbesKt`;

No issues on kotlinx.coroutins side
