### ISSUE TITLE
No longer able to catch exceptions from other coroutines while within `runTest` after 1.7.0

### ISSUE THREAD

**Issue by lucas-livefront** [Kotlin/kotlinx.coroutines#3889]
**Describe the bug**
Pre-`1.7.0` we were doing the correct thing by using the Thread ’s uncaught exception handler for exceptions thrown in coroutines that are encapsulated in a tested function like so:
```kotlin
// An example function to test
private fun somethingThatBuildsACoroutineScopeAndThrows() {
    CoroutineScope(Dispatchers.Unconfined).launch {
        throw IllegalStateException("Something is happening")
    }
}

// The utility for testing it correctly before 1.7.0.
fun <T : Throwable> assertThrowsInCoroutine(
    expectedThrowable: Class<T>,
    block: () -> Unit,
): T {
    val originalHandler = Thread.getDefaultUncaughtExceptionHandler()
    var throwable: Throwable? = null
    Thread.setDefaultUncaughtExceptionHandler { _, t -> throwable = t }

    try {
        block()
    } catch (t: Throwable) {
        // Manually catch this here just in case the exception is not in a coroutine
        throwable = t
    }

    Thread.setDefaultUncaughtExceptionHandler(originalHandler)

    return assertThrows(expectedThrowable) {
        throwable?.let { throw it }
    }
}

// An example test
@Test
fun `happy test`() = runTest {
   // Do some other suspend function work... thus requiring the `runTest` wrapper.
   
    assertThrowsInCoroutine(IllegalStateException::class.java) {
        somethingThatBuildsACoroutineScopeAndThrows()
    }
}
```

But as of `1.7.0` if we try this, the exception goes uncaught and the test bombs. In [this PR](https://github.com/Kotlin/kotlinx.coroutines/pull/3449) it seems this behavior was explicitly removed so that users who aren't handling failures in other coroutines experience test failure. I would like to know how we can still correctly catch these exceptions.

**Additional Note**
We can work around this work around by just wrapping our test function in `runTest`.  This is not ideal, because as I understand it, we shouldn't nest `runTest`s.
```kotlin
@Test
fun `wrap in runTest for success`() = runTest {
   // Do some other suspend function work... thus requiring the `runTest` wrapper.

    assertThrowsInCoroutine(IllegalStateException::class.java) {
        runTest {
            somethingThatBuildsACoroutineScopeAndThrows()
        }
    }
}
```

**Comment by dkhalanskyjb** [comment]
Could you give an example of a useful test that uses this? Why would one ever want to intentionally throw exceptions in a way that they are passed to the uncaught exception handler?

**Comment by lucas-livefront** [comment]
Our issue is that our `ViewModel`s use the actor pattern. The `ViewModel` builds an actor with `CoroutineScope.actor()` so the actor is initialized from within the coroutine scope. We have scenarios where we expect something to be in the `SavedStateMap` that we pass to our actor. We want to test that if the value isn't there, an exception is thrown.

**Comment by dkhalanskyjb** [comment]
`ViewModel` means that you have an Android codebase, and uncaught exceptions crash the application on Android. Do you actually have tests that check that if a value isn't present, the app has to crash? Or do you handle exceptions some other way in production?

**Comment by lucas-livefront** [comment]
Your inference is correct. The app would also crash in production.

**Comment by dkhalanskyjb** [comment]
So, do I get it right that you want to **ensure** that your app crashes if the conditions are right? That's a very unusual requirement. Typically, people try to avoid writing code that crashes the app and test that it does not crash under any circumstances.

**Comment by brian-livefront** [comment]
@dkhalanskyjb The idea here is to "fail fast" during development so that we catch any cases where required dependencies are missing. We want to test that our "fail fast" logic is working. This is useful for us to both know and test.

**Comment by brian-livefront** [comment]
@dkhalanskyjb If it helps to have a standard reference, [here is an example](https://github.com/android/nowinandroid/blob/main/feature/topic/src/main/kotlin/com/google/samples/apps/nowinandroid/feature/topic/navigation/TopicNavigation.kt#L38) from the Now In Android project : 

```kotlin
internal class TopicArgs(val topicId: String) {
    constructor(savedStateHandle: SavedStateHandle) :
        this(URLDecoder.decode(checkNotNull(savedStateHandle[topicIdArg]), URL_CHARACTER_ENCODING))
}
```
That `checkNotNull` will [crash in ViewModel](https://github.com/android/nowinandroid/blob/main/feature/topic/src/main/kotlin/com/google/samples/apps/nowinandroid/feature/topic/TopicViewModel.kt#L50) if that data is missing:

```kotlin
@HiltViewModel
class TopicViewModel @Inject constructor(
    savedStateHandle: SavedStateHandle,
    private val userDataRepository: UserDataRepository,
    topicsRepository: TopicsRepository,
    userNewsResourceRepository: UserNewsResourceRepository,
) : ViewModel() {

    private val topicArgs: TopicArgs = TopicArgs(savedStateHandle)

    val topicId = topicArgs.topicId
```

That is the same as what's going on in our case (an exception would be thrown if its missing); the only difference here is that they would get the exception when constructing the VM and we will get in inside a coroutine. The use case is not unusual, but now we are looking for guidance on how to test it given these recent changes to `runTest`.

**Comment by dkhalanskyjb** [comment]
I see. Yes, in your case, nesting `runTest` is fine. It only becomes a problem when dealing with multiplatform code, and I see that your problem is Android-specific, where you can't supply additional coroutine context to the `ViewModelScope`.

**Comment by brian-livefront** [comment]
Sounds good, thanks @dkhalanskyjb! We just wanted to make sure those nested `runTest` calls wouldn't cause us any unforeseen issues so it's good to hear that we should be safe. Thanks for taking a look at this!

**Comment by lucas-livefront** [comment]
Actually, @dkhalanskyjb this solution doesn't work as we expected. 🤦 To be clear here I will use slightly different tests to illustrate the issues here. 

### Using `TestScope.runTest`
The first one uses there `TestScope.runTest` in an attempt to catch the uncaught exception.
```kotlin
@Test
fun `non-TestScope runTest test`() {
    val block: TestScope.() -> Unit = {
        runTest { somethingThatBuildsACoroutineScopeAndThrows() }
    }
    runTest {
        val throwable = assertThrows(IllegalStateException::class.java) {
            block()
        }
    }
}
```
This throws an exception that happens to be an `IllegalStateException` which makes the test appear to succeed. However, if we update the test to test the exception's message we will see it fail. This was the flaw we made in the code we claimed to be a workaround in the initial post.
```kotlin
@Test
fun `non-TestScope runTest test`() {
    val block: TestScope.() -> Unit = {
        runTest { somethingThatBuildsACoroutineScopeAndThrows() }
    }
    runTest {
        val throwable = assertThrows(IllegalStateException::class.java) {
            block()
        }
        assertEquals(
            throwable.message, "Something is happening"
        )
    }
}
```
> expected: <Only a single call to `runTest` can be performed during one test.> but was: <Something is happening>
> Expected :Only a single call to `runTest` can be performed during one test.
> Actual       :Something is happening

So this is not an option for catching uncaught exceptions.

### Using the Unscoped `runTest`
If we use a regular `runTest`, the assertions will succeed but the outermost `runTest` will also throw `IllegalStateException("Something is happening")`.
```kotlin
@Test
fun `non-TestScope runTest test`() {
    val block: TestScope.() -> Unit = {
        runTest { somethingThatBuildsACoroutineScopeAndThrows() }
    }
    runTest {
        val throwable = assertThrows(IllegalStateException::class.java) {
            block()
        }
        // Added print statements to prove that assertions are succeeding
        println("Throwable type is correct: ${throwable is IllegalStateException}")
        println("Throwable message is correct: ${throwable.message == "Something is happening"}")
        assertEquals(
            throwable.message, "Something is happening"
        )
    }
}
```
> Throwable type is correct: true
> Throwable message is correct: true
>
> Something is happening
> java.lang.IllegalStateException: Something is happening
>    ...

This, also, is a non-option for catching uncaught exceptions.

### Conclusion
Ultimately, we don't have a solution for handling uncaught exceptions from with a `runTest` invocation. What do you suggest we do from here and is there anything else you might need from me?

**Comment by dkhalanskyjb** [comment]
> `Only a single call to runTest can be performed during one test`

You can work around that with

```kotlin
    runTest {
        TestScope().runTest {
            println("this doesn't fail")
        }
    }
```

**Comment by lucas-livefront** [comment]
@dkhalanskyjb In this case we see the same error as the "unscoped `runTest`" case that I described above.
```kotlin
    @Test
    fun `building new TestScope runTest test`() {
        val block: () -> Unit = {
            TestScope().runTest { somethingThatBuildsACoroutineScopeAndThrows() }
        }
        runTest {
            val throwable = assertThrows(IllegalStateException::class.java) {
                block()
            }
        // Added print statements to prove that assertions are succeeding
        println("Throwable type is correct: ${throwable is IllegalStateException}")
        println("Throwable message is correct: ${throwable.message == "Something is happening"}")
            assertEquals(
                throwable.message, "Something is happening"
            )
        }
    }
```
> Throwable type is correct: true
> Throwable message is correct: true
>
> Something is happening
> java.lang.IllegalStateException: Something is happening
> ...

**Comment by lucas-livefront** [comment]
Ok, so yes this works. However, I do see it as a kludge. I still cannot make a method to catch uncaught exceptions that works whether or not it is called from within `runTest`. Sure, now I know that it is officially recommended that I not use `runTest` to run suspending code whenever I need to also catch uncaught exceptions. But, even if I thoroughly document my new `assertThrowsInCoroutine` method, an unscrupulous developer employing `assertThrowsInCoroutine` within a `runTest` invocation could still waste time attempting to debug unintuitive failures.

**Comment by lucas-livefront** [comment]
@dkhalanskyjb So is it officially recommended that I not use runTest to run suspending code whenever I also need to catch uncaught exceptions? If it is, I can see there being lingering issues here. This seems like something that would easily be done incorrectly and is difficult to debug.
