### ISSUE TITLE
Add "source" button to API docs

### ISSUE THREAD

**Issue by SebastianAigner** [Kotlin/kotlinx.coroutines#3929]
Currently, there is no convenient way to navigate from the API docs to the actual code in the repository.

Compare other libraries, where Dokka links to the actual source / implementation of symbols: https://hoc081098.github.io/FlowExt/docs/0.x/-flow-ext/com.hoc081098.flowext/-delay-strategy/index.html

<img width="710" alt="Screenshot 2023-11-06 at 16 03 05" src="https://github.com/Kotlin/kotlinx.coroutines/assets/2178959/87f82050-a7ab-47c3-8c65-1af510c8e7dd">

This makes it harder for people who might want to contribute documentation improvements, clarifications, and the like. It'd be great if the button could be added!

**Comment by dkhalanskyjb** [comment]
Here's the API reference for this library: https://kotlinlang.org/api/kotlinx.coroutines/

Here's an example of the page from that API reference: https://kotlinlang.org/api/kotlinx.coroutines/kotlinx-coroutines-core/kotlinx.coroutines/async.html

For me, the `(source)` button renders and works appropriately.
