### ISSUE TITLE
Add transformations to BroadcastChannel

### ISSUE THREAD

**Issue by matejdro** [Kotlin/kotlinx.coroutines#394]
It would be useful to have operators at broadcast channel level, like this:

```kotlin
val numberChannel = BroadcastChannel<Int>(Channel.CONFLATED)

val positiveStringChannel = numberChannel.filter { it > 0 }.map { it.toString() }

val consumerA = launch {
    positiveStringChannel.openSubscription().consumeEach {
        println("Consumer B got $it")
    }
}

val consumerB = launch {
    positiveStringChannel.openSubscription().consumeEach {
        println("Consumer B got $it")
    }
}

// Both consumers receive "10"
numberChannel.send(10)
// Both consumers receive nothing
numberChannel.send(-20)
```

Operators would of course be performed before value is broadcasted to everyone, transforming the value only once for all subscribers.

There are many use cases for this, for example receiving raw data from the server and then transforming that data stream into more friendly data class before broadcasting it across the application.

**Comment by elizarov** [comment]
The plan is to provide a consistent set of operators to all kind of channels are a part of #254. It relation to a `BroadcastChannel` it means that they would implement a cold streams interface (let's call it `Source`) which will have all the `filter` and `map` defined, so when you write:

```
val positive = numberChannel.filter { it > 0 }.map { it.toString() }
```

You'll get a variable of type `Source<String>`.

**Comment by matejdro** [comment]
But will that source also be broadcast channel, e.g. are `map` and `filter` only called once, even with multiple subscribers?

**Comment by elizarov** [comment]
This source is going to be cold. It will subscribe to the original broadcast channel and establish `filter { ... }.map { ... }` pipe line for each consumer. If you need the pipeline to be started once you'll be add `.broadcast()` at the end of that expression and get a broadcast channel.
