### ISSUE TITLE
introduce ReceiveBroadcastChannel

### ISSUE THREAD

**Issue by SalomonBrys** [Kotlin/kotlinx.coroutines#398]
In an interface, we can declare something like this:

```kotlin
interface Whatever {
    val input: SendChannel<Input>
    val output: ReceiveChannel<Output>
}
```

Now, I need `output` to be a `BroadcastChannel`.
The problem with the interface `BroadcastChannel` is that it is also a `SendChannel`.
I would like to give the view the possibility to subscribe to the broadcast, but **not** to send to or cancel the channel.

I think an interface like this would be very usefull:

```kotlin
interface ReceiveBroadcastChannel<T> {
    fun openSubscription(): ReceiveChannel<E>
}
```

**Comment by fvasco** [comment]
Are you seen #274?

**Comment by SalomonBrys** [comment]
No, sorry :(
I did make a search before posting this, but on issues and not on PRs.
my bad ;)
