### ISSUE TITLE
SharedFlow: Emission is not collected after configuration change

### ISSUE THREAD

**Issue by ArcherEmiya05** [Kotlin/kotlinx.coroutines#3989]
**Describe the bug**
SharedFlow `emit` or `collect` is not working immediately after configuration change.

What happened? What should have happened instead?
The `collect` with `Lifecycle.State.STARTED` and any call to `emit` inside Fragment's `onCreateView` should work immediately,

Already put this concern in [SO](https://stackoverflow.com/q/77660284/12204620) but it is already been 3 days and still got no clear answer as to why is this happening.

**Comment by qwwdfsad** [comment]
This question is about Android integration (i.e. we do not have control over `Lifecycle.State.START`) and we have neither control over this integration nor deep understanding. 
I'd suggest sticking with SO, Slack or Google bugtracked
