### ISSUE TITLE
There is a problem about kotlinx.coroutines 0.23.1

### ISSUE THREAD

**Issue by zondaOf2012** [Kotlin/kotlinx.coroutines#400]
android studio 3.1.3
kotlin version 1.2.30

When implementation kotlinx.coroutines 0.23.1 in the gradle.

Problems with Project \:
More than one file was found with OS independent path 'META-INF/main.kotlin_module'

**Comment by JakeWharton** [comment]
You should be excluding all `.kotlin_module` files from your APK in the first place.

This will be fixed by updating the library's Kotlin to 1.2.50 and recompiling as it will honor archivesBaseName in common projects.

**Comment by zondaOf2012** [comment]
@JakeWharton Thanks for your answer.

But it didn't solve the problem.

According this [plan](https://stackoverflow.com/questions/50774577/gradle-build-fails-android-meta-inf-kotlinx-coroutines-core-kotlin-module/50775249) and updating the library's Kotlin to 1.2.50，however, another problem appears: Please select android SDK.

I'm already specifies these options：
compileSdkVersion 27
buildToolsVersion '27.0.3'
Android SDK Path 

In the project's "app.iml" file , I found <orderEntry type="jdk" jdkName="Android API 27 Platform" jdkType="Android SDK" /> change to  "<orderEntry type="jdk" jdkName="Kotlin SDK" jdkType="KotlinSDK" />"

**Comment by zondaOf2012** [comment]
In order to use kotlin-coroutines, 0.19.3 version had no choice.

This current plans:
android studio version 3.1.3
[kotlin version](https://kotlinlang.org/docs/reference/using-gradle.html#configuring-dependencies) 1.2.30
**kotlinx-coroutines-core 0.19.3**

**Comment by mrmitew** [comment]
Just add
```
packagingOptions {
        exclude 'META-INF/main.kotlin_module'
    }
```

between `android {}` in your `build.gradle` file and it will compile fine ;)

**Comment by zondaOf2012** [comment]
@mrmitew This can't solve my problems.

According this plan and updating the library's Kotlin to 1.2.50，however, another problem appears: Please select android SDK.

**Comment by zondaOf2012** [comment]
The latest progress of it：
android studio version 3.1.3
kotlin version 1.2.50
kotlinx-coroutines-core **0.23.3** 
The exception is fixed !👏👏👏👏👏

**Comment by zondaOf2012** [comment]
If I 'd start to config with this：
![image](https://user-images.githubusercontent.com/3021796/41587345-9964c25a-73e1-11e8-8822-fae03b82b2cf.png)

This is OK !

But, discover a very **strange problem** 😂：

If I change to config with this: 
![image](https://user-images.githubusercontent.com/3021796/41587951-041ab66c-73e3-11e8-936b-3ea7950eafb2.png)

As mentioned above, problem will reappear. It doesn’t matter if I change back to first picture and clean/rebuild project etc. 

Now，I change to config with this: 
![image](https://user-images.githubusercontent.com/3021796/41588390-325dd2ec-73e4-11e8-92a9-07de5101181d.png)

This is OK !  Now, There is no problem if I change back to first picture.

In a word, I have found the solution, but I did not understand.

**Comment by elizarov** [comment]
Can you, please, try with the latest released version of coroutines: `0.23.3`. Do you have this problem?

**Comment by tmexcept** [comment]
@zondaOf2012 change kotlin_version from '1.2.50' to '1.2.40', it will be ok

**Comment by zondaOf2012** [comment]
@tmexcept Thank you~~
