### ISSUE TITLE
Async propogates his exceptions to the parent without await

### ISSUE THREAD

**Issue by nikialeksey** [Kotlin/kotlinx.coroutines#4012]
In the [`CoroutineExceptionHandler`](https://kotlinlang.org/api/kotlinx.coroutines/kotlinx-coroutines-core/kotlinx.coroutines/-coroutine-exception-handler/) documentation we see:
> A coroutine that was created using [async](https://kotlinlang.org/api/kotlinx.coroutines/kotlinx-coroutines-core/kotlinx.coroutines/async.html) **always catches all its exceptions** and represents them in the resulting [Deferred](https://kotlinlang.org/api/kotlinx.coroutines/kotlinx-coroutines-core/kotlinx.coroutines/-deferred/index.html) object, so it cannot result in uncaught exceptions.

But in reality we see different cases, when async propogates their exceptions to the parent. Just look at this code:

```kotlin
import kotlinx.coroutines.*

fun main() = runBlocking {
    val handler = CoroutineExceptionHandler { _, e ->
        println("Exception from handler: " + e)
    }

    val scope = CoroutineScope(handler)
    val launchJob = scope.launch {
        async {
            println("Long running task...")
            delay(500)
            throw Exception("Oops!")
        }
    }
    launchJob.join()
}
```

In the output we get this:
```
Long running task...
Exception from handler: java.lang.Exception: Oops!
```

So, this is not the behavior we see in the documentation. 

We need to document such unusual behavior for async either fix the behavior and makes it like described in the documentation.

**Comment by nikialeksey** [comment]
@dkhalanskyjb From the doc:

> A coroutine that was created using [async](https://kotlinlang.org/api/kotlinx.coroutines/kotlinx-coroutines-core/kotlinx.coroutines/async.html) always catches all its exceptions and represents them in the resulting [Deferred](https://kotlinlang.org/api/kotlinx.coroutines/kotlinx-coroutines-core/kotlinx.coroutines/-deferred/index.html) object.

From your comment:
> `async`s exceptions are not uncaught, they are reported to the parent coroutine.

I see contradiction here. Because I understand the doc, that exception from my example without await from the description must be swallowed. In this example:

```
    val launchJob = scope.launch {
        async {
            println("Long running task...")
            delay(500)
            throw Exception("Oops!")
        }.await() // <<<---
    }
```

It will be throwed in above case because we use await (like from the doc).

**Comment by dkhalanskyjb** [comment]
`async` reports exceptions to two different places:

* It stores them to later be accessed via `await` (unconditionally);
* If it has a parent, it also notifies the parent with that exception.
  * If it does not have a parent, this would usually (in case of `launch`) be classified as an uncaught exception and reported to `CoroutineExceptionHandler`. Instead, `async` relies on the user calling `await`.

**Comment by nikialeksey** [comment]
@dkhalanskyjb Okay, just feel the difference:

> A coroutine that was created using [async](https://kotlinlang.org/api/kotlinx.coroutines/kotlinx-coroutines-core/kotlinx.coroutines/async.html) always catches all its exceptions and represents them in the resulting [Deferred](https://kotlinlang.org/api/kotlinx.coroutines/kotlinx-coroutines-core/kotlinx.coroutines/-deferred/index.html) object.

VS (my edit):
>A coroutine that was created using [async](https://kotlinlang.org/api/kotlinx.coroutines/kotlinx-coroutines-core/kotlinx.coroutines/async.html) catches all its exceptions and represents them in the resulting [Deferred](https://kotlinlang.org/api/kotlinx.coroutines/kotlinx-coroutines-core/kotlinx.coroutines/-deferred/index.html) object only when async  is root. When async is the child, then it will notify the parent about that exception.

**Comment by dkhalanskyjb** [comment]
Your edit is incorrect. The exception is stored in a `Deferred` *always*.

**Comment by nikialeksey** [comment]
@dkhalanskyjb Okay, lets try this one:

> A coroutine that was created using [async](https://kotlinlang.org/api/kotlinx.coroutines/kotlinx-coroutines-core/kotlinx.coroutines/async.html) always catches all its exceptions and represents them in the resulting [Deferred](https://kotlinlang.org/api/kotlinx.coroutines/kotlinx-coroutines-core/kotlinx.coroutines/-deferred/index.html) object. But notice the important thing about async: async also will notify parent about that exception if async is a child coroutine.

Don't get me wrong, but current documentation about async and exception propogating is not friendly.
