### ISSUE TITLE
No artifacts published for Kotlin/WASM? (also affects kotlinx-serialization)

### ISSUE THREAD

**Issue by RaphaelTarita** [Kotlin/kotlinx.coroutines#4029]
I have tested this for `org.jetbrains.kotlinx:kotlinx-coroutines-core:1.7.3` and `org.jetbrains.kotlinx:kotlinx-serialization-json:1.5.1`, but I suspect it might be the case for all kotlinx libraries

**Describe the bug**

According to [this page](https://kotlinlang.org/docs/wasm-libraries.html) on the official Kotlin website, both kotlinx-coroutines and kotlinx-serialization should be supported for the new WASM target. However, I tried to include these dependencies for a Kotlin/WASM project and I get a build error because gradle cannot resolve them for the WASM target. Studying the list of checked candidates, it seems that all kinds of targets show up (JVM, JS, a bunch of native targets), but the `wasmJs` variant is missing. Other than the aforementioned documentation page, I cannot find any evidence for a published `wasmJs` variant of `kotlinx-coroutines-core`.

**Provide a Reproducer**

To reproduce this, I've set up a new project that has the following gradle buildscript (`build.gradle.kts`):

```kotlin
import org.jetbrains.kotlin.gradle.targets.js.dsl.ExperimentalWasmDsl

plugins {
    kotlin("multiplatform") version "1.9.22"
}

group = "org.example"
version = "1.0-SNAPSHOT"

repositories {
    mavenCentral()
}

kotlin {
    @OptIn(ExperimentalWasmDsl::class)
    wasmJs {
        browser()
        nodejs()
    }

    sourceSets {
        val wasmJsMain by getting {
            dependencies {
                implementation("org.jetbrains.kotlinx:kotlinx-coroutines-core:1.7.3")
            }
        }
    }
}
```
When invoking `./gradlew(.bat) build`, it yields a lengthy error message about how no matching variant of `org.jetbrains.kotlinx:kotlinx-coroutines-core:1.7.3` was found. If I try to pull this dependency for other targets (JVM, JS, Native), it works just fine.

Maybe I'm doing something wrong, although I tried to make this example match the snippet on the aforementioned documentation page as close as possible. Is there a reason why the dependency cannot be resolved? Is this expected behavior?

**Comment by JakeWharton** [comment]
According to the change log, 1.8.0-RC is the first version with WASM (JS) support.

https://github.com/Kotlin/kotlinx.coroutines/blob/master/CHANGES.md#version-180-rc

**Comment by dkhalanskyjb** [comment]
Yep, it's a bug on the website.

**Comment by dkhalanskyjb** [comment]
Sure thing, an official guy filed the issue in the right place: https://youtrack.jetbrains.com/issue/KT-65471/Wrong-library-versions-listed-for-Wasm-preview
