### ISSUE TITLE
Enum deserialization options

### ISSUE THREAD

**Issue by inemtsev** [Kotlin/kotlinx.coroutines#4031]
Hi team,

Sometimes when consuming a backend written in a different tech stack, the Enums are serialized at Integers. Kotlinx currently does not understand this and custom serializer is needed. Sometimes the contract is generated and there are many such enums, this doesn't scale very well. It would be great if there was an option like Json { enumAsInteger = true } that would change this behavior.

Best Regards,
Ilya

**Comment by dkhalanskyjb** [comment]
Hi! You probably wanted https://github.com/Kotlin/kotlinx.serialization/
