### ISSUE TITLE
Change KotlinX Coroutines versioning to be SemVer-compliant

### ISSUE THREAD

**Issue by Laxystem** [Kotlin/kotlinx.coroutines#4037]
Currently, KotlinX Coroutines release release candidates in the form of: `1.8.0-RC2`.

*However*, SemVer 2.0 describes that the first element after the `-` is sorted alphabetically, and numeral elements after it are sorted by the number they represent.

Currently, if KotlinX Coroutines will manage to reach 10 release candidates somehow, a comparing problem will arise:

- `-RC1`
- `-RC10`
- -RC2`
- [...]
- `-RC9`

When it should be:

- `-RC1`
- `-RC2`
- [..]
- `-RC9`
- `-RC10`

This can be easily solved by changing the versioning to `1.8.0-rc.1` or `1.8.0-RC.1`.

My proposal: use `1.X.X-rc.1` for the next RC instead. I know this is a tiny and annoying request (sorry), but it should solve a few headaches if this library is unlucky enough to have 10 release candidates.

**Comment by dkhalanskyjb** [comment]
Noted, thanks!
