### ISSUE TITLE
Debug coroutines in Android

### ISSUE THREAD

**Issue by albo1337** [Kotlin/kotlinx.coroutines#404]
I just oppened a question in StackOverflow -> [Debug Kotlins coroutines in Android](https://stackoverflow.com/questions/50962243/debug-kotlins-coroutines-in-android)
Could you help me please here? I'm really frustrated now and do not understand, why this is not working. What am I doing wrong?

Please help me guys...

Thanks a lot
Albo

**Comment by elizarov** [comment]
It is problem in Kotlin Plugin for IDEA debugger, not a problem in `kotlinx.coroutines` library. It is being worked on. Please, track this issue: https://youtrack.jetbrains.com/issue/KT-22296

**Comment by elizarov** [comment]
This turns out to be a separate bug. Even more minimized case: https://youtrack.jetbrains.com/issue/KT-25076
