### ISSUE TITLE
RC:1.4.3

### ISSUE THREAD

**Issue by ltaoj** [Kotlin/kotlinx.coroutines#4050]
What broke?

I've cloned this repository into my workspace with the goal of building the project, altering some code, and republishing it for my own use. However, I've encountered an error, as follows:

```
Execution failed for task ':buildSrc:generateExternalPluginSpecBuilders'.
> Could not resolve all files for configuration ':buildSrc:compileClasspath'.
   > Could not find org.jetbrains.dokka:dokka-gradle-plugin:0.9.16-rdev-2-mpp-hacks.
     Searched in the following locations:
       - https://plugins.gradle.org/m2/org/jetbrains/dokka/dokka-gradle-plugin/0.9.16-rdev-2-mpp-hacks/dokka-gradle-plugin-0.9.16-rdev-2-mpp-hacks.pom
       - https://dl.bintray.com/kotlin/kotlin-dev/org/jetbrains/dokka/dokka-gradle-plugin/0.9.16-rdev-2-mpp-hacks/dokka-gradle-plugin-0.9.16-rdev-2-mpp-hacks.pom
     Required by:
         project :buildSrc

Possible solution:
 - Declare repository providing the artifact, see the documentation at https://docs.gradle.org/current/userguide/declaring_repositories.html
```

The artifact, org.jetbrains.dokka:dokka-gradle-plugin:0.9.16-rdev-2-mpp-hacks, has been removed from Maven Central. How can I proceed to build version 1.4.3?

**Comment by qwwdfsad** [comment]
I am afraid you cannot, except if you completely disable Dokka from the build process (which is responsible mostly for the documentation).
This version only existed in Bintray that has been sunsetted

**Comment by ltaoj** [comment]
Thanks! That may has a lots of work for disable Dokka from the build process completely. Can you provide me jar file of org.jetbrains.dokka:dokka-gradle-plugin:0.9.16-rdev-2-mpp-hacks?

**Comment by ltaoj** [comment]
> I am afraid you cannot, except if you completely disable Dokka from the build process (which is responsible mostly for the documentation). This version only existed in Bintray that has been sunsetted

Thanks! That may has a lots of work for disable Dokka from the build process completely. Can you provide me jar file of org.jetbrains.dokka:dokka-gradle-plugin:0.9.16-rdev-2-mpp-hacks?

**Comment by qwwdfsad** [comment]
I don't think we have it anywhere in a form I can be sure of.
You might look into MC and other art factories though: https://mvnrepository.com/artifact/org.jetbrains.dokka/dokka-gradle-plugin/0.9.16-rdev-2-mpp-hacks

**Comment by ltaoj** [comment]
> I don't think we have it anywhere in a form I can be sure of. You might look into MC and other art factories though: https://mvnrepository.com/artifact/org.jetbrains.dokka/dokka-gradle-plugin/0.9.16-rdev-2-mpp-hacks

Thanks for your help! I replace the version: https://mvnrepository.com/artifact/org.jetbrains.dokka/dokka-gradle-plugin/0.9.16, and comment this line code, then the project sync success
![image](https://github.com/Kotlin/kotlinx.coroutines/assets/17923045/4f362da0-b2f8-4452-a58c-6927676781bf)
