### ISSUE TITLE
The coroutine states in the debugger are inaccurate when starts are undispatched

### ISSUE THREAD

**Issue by dkhalanskyjb** [Kotlin/kotlinx.coroutines#4058]
Undispatched starts of coroutines (with `CoroutineStart.UNDISPATCHED` <s>or unconfined dispatchers</s> (sorry, I myself got confused)) confuse the debugger.

```kotlin
fun weWantToUseSteppingInThisFunction() {
  println("A")
  delay(100)
  println("B")
}

runBlocking {
  launch(start = CoroutineStart.UNDISPATCHED) {
    weWantToUseSteppingInThisFunction()
  }
  println("C")
}
```

At point `A`, we'll see that the outer coroutine is considered to be running, whereas the inner coroutine is only "created" and doesn't even have a stacktrace associated with it.

This is not that big of an issue when browsing the list of running coroutines: we'll see that someone executes `A`, it's not a big deal that the slightly incorrect coroutine is doing that. When introducing stepping, this becomes a problem: given a breakpoint at `A`, we need a reliable way to say "run to `B` in the same coroutine." When the coroutine machinery thinks that `A` is executed by the outer coroutine, this becomes impossible.

Previous discussion: https://github.com/Kotlin/kotlinx.coroutines/pull/3987#issuecomment-1907882574

**Comment by Ahmed30mara2018** [comment]
> Undispatched starts of coroutines (with `CoroutineStart.UNDISPATCHED` or unconfined dispatchers) confuse the debugger.
> 
> ```kotlin
> fun weWantToUseSteppingInThisFunction() {
>   println("A")
>   delay(100)
>   println("B")
> }
> 
> runBlocking {
>   launch(Dispachers.Unconfined) {
>     weWantToUseSteppingInThisFunction()
>   }
>   println("C")
> }
> ```
> 
> At point `A`, we'll see that the outer coroutine is considered to be running, whereas the inner coroutine is only "created" and doesn't even have a stacktrace associated with it.
> 
> This is not that big of an issue when browsing the list of running coroutines: we'll see that someone executes `A`, it's not a big deal that the slightly incorrect coroutine is doing that. When introducing stepping, this becomes a problem: given a breakpoint at `A`, we need a reliable way to say "run to `B` in the same coroutine." When the coroutine machinery thinks that `A` is executed by the outer coroutine, this becomes impossible.
> 
> Previous discussion: https://github.com/Kotlin/kotlinx.coroutines/pull/3987#issuecomment-1907882574

**Comment by qwwdfsad** [comment]
I still not exactly sure what is the desired behaviour.

First things first, let's figure out "undispatched" coroutines behaviour:
```
launch(start = CoroutineStart.UNDISPATCHED) { // or launch(Dispatchers.Unconfined)
    weWantToUseSteppingInThisFunction()
}
```

Fir
