### ISSUE TITLE
Try-finally and non-local returns - Mutex.withLock

### ISSUE THREAD

**Issue by Laxystem** [Kotlin/kotlinx.coroutines#4066]
[Here](https://github.com/Kotlin/kotlinx.coroutines/blob/60d2fe8471ce4d289d526f04b51389b06b1c064f/kotlinx-coroutines-core/common/src/sync/Mutex.kt#L107C1-L126C2) is the current implementation of KotlinX Coroutines `Mutex.withLock()`:
```kotlin
/**
 * Executes the given [action] under this mutex's lock.
 *
 * @param owner Optional owner token for debugging. When `owner` is specified (non-null value) and this mutex
 *        is already locked with the same token (same identity), this function throws [IllegalStateException].
 *
 * @return the return value of the action.
 */
@OptIn(ExperimentalContracts::class)
public suspend inline fun <T> Mutex.withLock(owner: Any? = null, action: () -> T): T {
    contract {
        callsInPlace(action, InvocationKind.EXACTLY_ONCE)
    }
    lock(owner)
    return try {
        action()
    } finally {
        unlock(owner)
    }
}
```

Notice how `action` is not `crossinline`. This means that:
```kotlin
suspend fun foo() = mutex.withLock() {
    return 42 // bad, mutex doesn't unlock
}
```

*However*, `action` is called inside a `try` block - do `finally`s apply to non-local returns?
If so, maybe there should be something in the language, or at the very least, in the function's documentation that tells me about it?

This is very confusing, and potentially could cause people to switch `return`s with `return@withLock` all over their project, and then realize that the try block automagically applies to non-local-returns. This feels very `goto`-y.

This issue was previously submitted as [KT-66567](https://youtrack.jetbrains.com/issue/KT-66567/Try-finally-and-non-local-returns).

**Comment by Laxystem** [comment]
I'm saying the documentation should be changed, because this can be confusing.

**Comment by dkhalanskyjb** [comment]
This is not a problem with the library: you're not even supposed to read the source code to use it, so "I don't understand why the implementation works properly" is not something we consider a bug. Especially, we are not going to write comments about fundamental language constructs like `try` and `return`. Here's a good explanation of how `finally` works: https://docs.oracle.com/javase/tutorial/essential/exceptions/finally.html and here's an explanation of inline functions: https://kotlinlang.org/docs/inline-functions.html
