### ISSUE TITLE
`Dispatchers.Default` is not installed in coroutine builders when there is no `ContinuationInterceptor` in native

### ISSUE THREAD

**Issue by whyoleg** [Kotlin/kotlinx.coroutines#4074]
**Describe the bug**

When using one of the coroutine builders (like `launch`) if there is no `ContinuationInterceptor`/`CoroutineDispatcher` in `coroutineContext` coroutine should start on `Dispatchers.Default` as specified in documentation of: [Dispatchers.Default](https://github.com/Kotlin/kotlinx.coroutines/blob/60d2fe8471ce4d289d526f04b51389b06b1c064f/kotlinx-coroutines-core/common/src/Dispatchers.common.kt#L10-L12), [CoroutineScope.newCoroutineContext](https://github.com/Kotlin/kotlinx.coroutines/blob/60d2fe8471ce4d289d526f04b51389b06b1c064f/kotlinx-coroutines-core/common/src/CoroutineContext.common.kt#L6-L8) (which is used under the hood of coroutine builders) and in [CoroutineScope.launch](https://github.com/Kotlin/kotlinx.coroutines/blob/60d2fe8471ce4d289d526f04b51389b06b1c064f/kotlinx-coroutines-core/common/src/Builders.common.kt#L22-L23) itself.

This contract is implemented in `actual` implementations of `CoroutineScope.newCoroutineContext` for all platforms ([jvm](https://github.com/Kotlin/kotlinx.coroutines/blob/60d2fe8471ce4d289d526f04b51389b06b1c064f/kotlinx-coroutines-core/jvm/src/CoroutineContext.kt#L18), [js](https://github.com/Kotlin/kotlinx.coroutines/blob/60d2fe8471ce4d289d526f04b51389b06b1c064f/kotlinx-coroutines-core/js/src/CoroutineContext.kt#L39), [wasmJs](https://github.com/Kotlin/kotlinx.coroutines/blob/60d2fe8471ce4d289d526f04b51389b06b1c064f/kotlinx-coroutines-core/wasmJs/src/CoroutineContext.kt#L29)) except [native](https://github.com/Kotlin/kotlinx.coroutines/blob/60d2fe8471ce4d289d526f04b51389b06b1c064f/kotlinx-coroutines-core/native/src/CoroutineContext.kt#L35), where single-threaded [DefaultExecutor](https://github.com/Kotlin/kotlinx.coroutines/blob/60d2fe8471ce4d289d526f04b51389b06b1c064f/kotlinx-coroutines-core/native/src/CoroutineContext.kt#L6) is used instead.

**Provide a Reproducer**

In following example on jvm, js, wasmJs the same dispatcher will be printed (it's name depends on target, but it is Dispatchers.Default`), but on native dispatchers are different:

```kotlin
val job = Job()
val scope = CoroutineScope(job) // no dispatcher provided
scope.launch(Dispatchers.Default) {
    println("default=${coroutineContext[ContinuationInterceptor]}")
}
scope.launch {
    println("empty=${coroutineContext[ContinuationInterceptor]}")
}
job.complete()
job.join()
```
At my side when running test on `macosArm64`:
```
empty=DefaultExecutor@2c70160
default=DarwinGlobalQueueDispatcher@2c30410
```

**Expected behaviour**

`Dispatchers.Default` should be installed on native.
I found this issue during running some tests, after refactoring tests execution time was increased. I had no idea why, but then when I checked dispatcher in some test and found that it's different - just because before it was just `EmptyCoroutineContext` but now it's Dispatchers.Default`.

Note: test execution time become like several times slower when using `Dispatchers.Default` - not sure if it's expected or not...

**Comment by dkhalanskyjb** [comment]
This looks like it's an overlooked artifact of the time the Native implementation was single-threaded.

> Note: test execution time become like several times slower when using `Dispatchers.Default` - not sure if it's expected or not...

On Apple targets, we use our own implementation of scheduling on top of a native thread for `DefaultDelay`, but delegate to Apple's event queue for `Dispatchers.Default`. This could be the reason.

**Comment by dkhalanskyjb** [comment]
Sure, please go ahead.
