### ISSUE TITLE
Kotlin 1.2.51 not available

### ISSUE THREAD

**Issue by SUPERCILEX** [Kotlin/kotlinx.coroutines#411]
When will it be uploaded? Currently, Coroutines 0.23.4 are unusable because of this.

**Comment by tumugin** [comment]
Add `https://dl.bintray.com/kotlin/kotlin-dev/` to your list of repositories.
```gradle
repositories {
    maven{
        url 'https://dl.bintray.com/kotlin/kotlin-dev/'
    }
    jcenter()
}
```
Until Kotlin 1.2.51 is available in maven central you can use this workaround.
https://mvnrepository.com/artifact/org.jetbrains.kotlin/kotlin-stdlib-jdk8

**Comment by SUPERCILEX** [comment]
Woot! v1.2.51 is available on [Bintray](https://bintray.com/bintray/jcenter/org.jetbrains.kotlin%3Akotlin-gradle-plugin/1.2.51) and [NPM](https://www.npmjs.com/package/kotlin/v/1.2.51)!
