### ISSUE TITLE
TestScope swallows an exception thrown from `launch` outside `runTest`

### ISSUE THREAD

**Issue by osipxd** [Kotlin/kotlinx.coroutines#4140]
**Kotlin:** 1.9.24
**Coroutines:** 1.8.1

**Describe the bug**

I have a simple test that is supposed to be red, but it is green for some reason:

```kotlin
@Test
fun falsePositive() {
    val testScope = TestScope(UnconfinedTestDispatcher())
    testScope.launch {
        println("Launched!")
        fail("Use runTest instead") // or error("...")
    }
}
```
```
> Task :testDebugUnitTest
Launched!
Playground > falsePositive() PASSED
```

I expect `UncaughtExceptionsBeforeTest` to be thrown, but it isn't. However, I can see the exception if I add an empty `testScope.runTest { }` call after the `launch` call. Also, if I replace `TestScope` with `CoroutineScope`, I see the exception. 

Is it an expected behaviour?

**Provide a Reproducer**

[Kotlin Playground](https://pl.kotl.in/Y4Uhuy2zw)

**Comment by dkhalanskyjb** [comment]
Yes, the docs of `TestScope` do mention that not running `runTest` is not supported. Otherwise, `TestScope` has no way of knowing when your test ends and where to report the exception.

**Comment by osipxd** [comment]
Thank you! I'm just curious why `UncaughtExceptionsBeforeTest` wasn't thrown [from here](https://github.com/Kotlin/kotlinx.coroutines/blob/master/kotlinx-coroutines-test/common/src/TestScope.kt#L293-L294)? (For some reason I'm not able to get into the exception handler with debugger to check it myself)

**Comment by dkhalanskyjb** [comment]
As to why: because it's not an *uncaught* exception, that is, an exception not propagated through structured concurrency.
As to why you can't debug this: probably IDEA doesn't want you to. See the attached image.
![image](https://github.com/Kotlin/kotlinx.coroutines/assets/52952525/3f3dd47c-78e7-4f54-9e24-edb16341f842)

**Comment by osipxd** [comment]
Oh, I see. Thank you for the explanation!
