### ISSUE TITLE
Inherit from `kotlinx.coroutines` warning even with interface delegation ?

### ISSUE THREAD

**Issue by VincentMasselis** [Kotlin/kotlinx.coroutines#4150]
**What do we have now?**

For this sample class:
```kotlin
class FooClass : StateFlow<Int> { // -> Prints a warning
     // Interface implementations
}
```

When I've updated to the release 1.9.0-RC, I saw this new warning: `Inheriting from this kotlinx.coroutines API is unstable. Either new methods may be added in the future, which would break the inheritance, or correctly inheriting from it requires fulfilling contracts that may change in the future.`. Fundamentally, I agree with this statement, but I think this warning is not necessary when if interface delegation is used.

**What should be instead?**

```kotlin
class FooClass(stateFlow : StateFlow<Int>) : StateFlow<Int> by stateFlow { // -> Don't print a warning
    // No need to implement methods thanks to the interface delegation
}
```

```kotlin
class FooClass(stateFlow : StateFlow<Int>) : StateFlow<Int> by stateFlow { // -> Print a warning
    // A method from the interface is explicitly overridden, in this case, a warning should be printed
    override val value: Int
}
```

**Why?**

Thanks to the interface delegation, `StateFlow<T>` could evolve a lot, the implementing class will not change at all so the warning points to a problem which doesn't exist. In the order hand, if the class implements methods from the interface, I agree with the warning since evolution will impact the code.

**Why not?**

Could slow down the computation of this warning because it require to detect interface delegation and check if methods from the interface are overridden or not.

**Comment by fzhinkin** [comment]
@VincentMasselis 

> Thanks to the interface delegation, `StateFlow<T>` could evolve a lot, the implementing class will not change at all so the warning points to a problem which doesn't exist.

Unfortunately, interface delegation can only help with source compatibility. Changes in the `StateFlow<T>` interface will still be binary incompatible and will break the inheritance, as the warning message suggests.

You can check how `class FooClass(stateFlow : StateFlow<Int>) : StateFlow<Int> by stateFlow ` would look like after compilation by running `javap` on a classfile or dumping the ABI using https://github.com/Kotlin/binary-compatibility-validator:
```
javap FooClass.class  
Compiled from "FooClass.kt"
public final class FooClass implements kotlinx.coroutines.flow.StateFlow<java.lang.Integer> {
  public FooClass(kotlinx.coroutines.flow.StateFlow<java.lang.Integer>);
  public java.util.List<java.lang.Integer> getReplayCache();
  public java.lang.Integer getValue();
  public java.lang.Object collect(kotlinx.coroutines.flow.FlowCollector<? super java.lang.Integer>, kotlin.coroutines.Continuation<?>);
  public java.lang.Object getValue();
}
```

As you can see, there's no magic under the hood and `FooClass` simply implements `StateFlow`. Once `StateFlow` changes, `FooClass` needs recompilation.
