### ISSUE TITLE
Consider stabilizing `CoroutineStart.ATOMIC`

### ISSUE THREAD

**Issue by jacktol** [Kotlin/kotlinx.coroutines#4151]
The `CoroutineStart.ATOMIC` option was marked experimental almost 6 years ago as part of version 0.30.0. Is there a strong reason that the option is still experimental, or could it be considered stable by now?

**Comment by qwwdfsad** [comment]
I think it's time to promote it to delicate: it has its use-cases, but it's easy to misuse, which fits the delicate concept perfectly

**Comment by lukellmann** [comment]
> I think it's time to promote it to delicate: it has its use-cases, but it's easy to misuse, which fits the delicate concept perfectly

The characteristics listed in the KDoc that make `ATOMIC` delicate also apply to `UNDISPATCHED`. Should it also be made delicate?

**Comment by zuevmaxim** [comment]
@lukellmann `UNDISPATCHED` has a wider range of use cases due to the threading guaranties, so it isn't marked as delicate API
