### ISSUE TITLE
1.9.0-RC: `kotlinx-coroutines-core/jvm/src/internal/ProbesSupport.kt` calls ` kotlinx.coroutines.debug.internal.probeCoroutineResumed`

### ISSUE THREAD

**Issue by nreid260** [Kotlin/kotlinx.coroutines#4152]
**Describe the bug**

This seems like an accident. `probeCoroutineCreated` delegates to `kotlin.coroutines.jvm.internal` but `probeCoroutineResumed` delegates to `kotlinx.coroutines.debug.internal`. Should they not point to the same place?

It also creates a weird build dependency. Now "debug" code is a static dependency of "production" code.

**Comment by fzhinkin** [comment]
@nreid260 thanks for reporting! My colleagues will check the issue once they are back from vacation.
