### ISSUE TITLE
StateFlow, different values, compareAndSet return false

### ISSUE THREAD

**Issue by xyz-fly** [Kotlin/kotlinx.coroutines#4178]
When I tried to replace the stateFlow.value method with the stateFlow.compareAndSet(null, status)) method, the first call was successful, but when the second value was passed in, false was returned.

so, I passed different values, why when calling compareAndSet, false is returned

```
        RongCoreClient.addConnectionStatusListener(object : IRongCoreListener.ConnectionStatusListener {
            override fun onChanged(status: IRongCoreListener.ConnectionStatusListener.ConnectionStatus?) {
                println("ConnectionStatus = " + status?.message?.toString())
                println("compareAndSet =" +      connectStateFlow.compareAndSet(null, status))
            }
        })

```

Calling this method StateFlow.value is equivalent to calling this method StateFlow.compareAndSet(null, value)

StateFlowImpl source code: 
```
private class StateFlowImpl<T>(
    initialState: Any // T | NULL
) : AbstractSharedFlow<StateFlowSlot>(), MutableStateFlow<T>, CancellableFlow<T>, FusibleFlow<T> {
    private val _state = atomic(initialState) // T | NULL
    private var sequence = 0 // serializes updates, value update is in process when sequence is odd

    @Suppress("UNCHECKED_CAST")
    public override var value: T
        get() = NULL.unbox(_state.value)
        set(value) { updateState(null, value ?: NULL) }

    override fun compareAndSet(expect: T, update: T): Boolean =
        updateState(expect ?: NULL, update ?: NULL)

    private fun updateState(expectedState: Any?, newState: Any): Boolean {
```

print log:

2024-07-12 19:14:16.325 12845-12845 System.out com.example.dmdemo I ConnectionStatus = Connecting
2024-07-12 19:14:16.326 12845-12845 System.out com.example.dmdemo I compareAndSet =true
2024-07-12 19:14:16.425 12845-12845 System.out com.example.dmdemo I ConnectionStatus = Connect Success.
2024-07-12 19:14:16.425 12845-12845 System.out com.example.dmdemo I compareAndSet =false

**Comment by dkhalanskyjb** [comment]
The second time, the state of the `StateFlow` is no longer `null` (since you've set it to something else already), so `compareAndSet` fails, as the documentation describes: https://kotlinlang.org/api/kotlinx.coroutines/kotlinx-coroutines-core/kotlinx.coroutines.flow/-mutable-state-flow/compare-and-set.html

**Comment by xyz-fly** [comment]
Later, I changed the use stateFlow.value method, but I still couldn't receive the value. I made sure that I called the collect method first, and then called the stateFlow.value method, but it didn't happen every time. Sometimes it worked, sometimes it didn't.  I don’t quite understand the reason.

**Comment by xyz-fly** [comment]
this is my mistake...
