### ISSUE TITLE
Empty whileSelect {  } hangs

### ISSUE THREAD

**Issue by fvasco** [Kotlin/kotlinx.coroutines#420]
An empty `whileSelect {  }` block hangs forever, this can happen if the `on...` conditions are added programmatically.

```kotlin
fun main(args: Array<String>)= runBlocking {
    whileSelect {  }
}
```

**Comment by qwwdfsad** [comment]
"The caller is suspended until one of the clauses is either selected or fails."
If nothing is registered, nothing can be selected and no one will resume `select` caller.
Note that standalone `select` will hang as well.
It's semantically correct and  Go `select` statement behaves the same way.

You can think about `select` as about infinite loop on steroid:
```
select<Int> {
   intChannel.onReceive { it }
}
```

is rough equivalent (a lot of machinery is omitted for example simplicity):

```
while (true) {
  val element = receiveOrNull()
  if (element == null) {
     yield()
  } else {
    return element
  }
}

```

If you have no clauses in select, you have nothing to break this loop

**Comment by fvasco** [comment]
Thank you for response, @qwwdfsad

There is no way to break the loop?
Something like an IllegalStateException("No clause in the select")

**Comment by qwwdfsad** [comment]
We can do it programmatically, but we won't.
It good to have a consistent mental model I described without corner cases
