### ISSUE TITLE
Recursive buildSequence does not compile

### ISSUE THREAD

**Issue by Temp1ar** [Kotlin/kotlinx.coroutines#421]
```kotlin
class Node {
    val children : List<Node> = emptyList()
}

fun Node.subtree() = kotlin.coroutines.experimental.buildSequence {
    val me = this@subtree
    yield(me)
    //me.children.forEach { yieldAll(it.subtree()) }
    for(child in me.children) {
        for (ancestor in child.subtree())
            yield(ancestor)
    }
}
```
The commented code fails to compile with "No resolved code for yieldAll" generator exception
Uncommented code with recursive type dependency error. 
Can i somehow get it working?
#7 issue is probably related.

**Comment by Temp1ar** [comment]
As a workaround i used approach from stackoverflow [using lazyPlus](https://stackoverflow.com/questions/35142548/recursive-definition-of-infinite-sequence-in-kotlin):
```kotlin
fun Node.subtree2(): Sequence<Node> {
    return sequenceOf(this) lazyPlus {
        children.asSequence().flatMap { it.subtree2() }
    }
}
```

**Comment by elizarov** [comment]
Hm... works for me in the laters version of Kotlin. Anyway, if you are running it recursive type problem, should just specify type explicitly. In this case you can either use `buildSequence<Node>` or add type annotation to the function `fun Node.subtree(): Sequence<Node>`
