### ISSUE TITLE
The last elvis operator is not called in a new coroutine with kotlin 2

### ISSUE THREAD

**Issue by tepel** [Kotlin/kotlinx.coroutines#4233]
**Describe the bug**

The last elvis operator is not called in a coroutine with kotlin 2. It works with kotlin 1.9

**Provide a Reproducer**

```

fun fail() {
    
    runBlocking {
        var result: String = "fail"
        val job = this.launch {
            println("Collect a flow and do some processing with the data")
            "test".let {
                    null
                } ?: run { // this is not called if it is the last thing in the block                        
                    result = "success"
                    println("This is not called when using kotlin 2.0.20!")                        
                }                            
        }

        job.join()
        println("Result is $result")
    }
}
```

Kotlin playground example to reproduce: https://pl.kotl.in/EMdcSNPLj

**Comment by dkhalanskyjb** [comment]
Thanks! This is unrelated to coroutines: I managed to reproduce the same bug without using the `kotlinx-coroutines` library. Reported to https://youtrack.jetbrains.com/issue/KT-71751/K2-regression-Skipping-code-in-the-last-statement-of-a-lambda
