### ISSUE TITLE
document typo in CancellableContinuation.kt

### ISSUE THREAD

**Issue by mountainn-dev** [Kotlin/kotlinx.coroutines#4264]
i think there is typo in suspundCancellableCoroutine public fun in CancellableContinuation.kt

the line 253 which is "prompt cancellation guarantees that 'the the' coroutine will not resume its code successfully."

thank you

<img width="958" alt="스크린샷 2024-10-31 오후 9 16 12" src="https://github.com/user-attachments/assets/a0b0534d-3ef5-4fd7-b900-f29143354d84">

**Comment by qwwdfsad** [comment]
Was fixed with 92df6e19a502bc667e2df74a3ae5823d5ed79896
