### ISSUE TITLE
Flow onBackpressureReduce operator?

### ISSUE THREAD

**Issue by shirozatou** [Kotlin/kotlinx.coroutines#4271]
**Use case**

Fast data producer but slow collector, reduce information from each event without drop or suspend.
For example, send update events to channel, receive most recent result at long running task.

```
val f = flow {
    repeat(52) {
        emit(it)
        delay(100)
    }
}
f.onBackpressureReduce(::maxOf).collect {
    println(it)
    delay(1000)
}
// output: 0, 9, 19, 29, 39, 49, 51
```

**The Shape of the API**

```
// sample
fun <T : Any> Flow<T>.onBackpressureReduce(reduce: (T, T) -> T): Flow<T> {
    return channelFlow {
        var job: Job? = null
        var acc: T? = null
        collect { value ->
            job?.apply {
                cancelAndJoin()
                if (!isCancelled) {
                    acc = null
                }
            }
            val v = acc?.let { reduce(it, value) } ?: value
            acc = v
            job = launch {
                send(v)
            }
        }
    }.buffer(capacity = 0)
}
```

![image](https://raw.githubusercontent.com/wiki/ReactiveX/RxJava/images/rx-operators/Flowable.onBackpressureReduce.png)

**Comment by qwwdfsad** [comment]
Hey, could you please share your product-specific use case? E.g. for which kind of events you want to apply this operator and what's the app logic flow that allows it/benefits from it?

This one has quite some parallels with #3884 and it would be interesting to see how it plays out together. Alternatively, it can be a channel `BufferOverflow` strategy

**Comment by shirozatou** [comment]
Hello, I can't share product use case, but this operator seems very common.

Like bus station,
Reduce: passengers at bus station.
Collector: scheduled bus, no waiting.


My use case is about handling duplicated endpoint request, accumulated parameter, one request each turn, but multiple callbacks.


How about this one?
```
    val logger = Channel<String>(0)
    launch {
        repeat(20) {
            logger.send("log-$it")
            delay(100)
        }
        logger.close()
    }
    //......

    logger.receiveAsFlow()
        .map { listOf(it) }
        .onBackpressureReduce { a, b -> a + b }
        .collect {
            // process as fast as possible.
            println("batch upload: $it")
            delay(500)
        }
//  batch upload: [log-0]
//  batch upload: [log-1, log-2, log-3, log-4, log-5]
//  batch upload: [log-6, log-7, log-8, log-9]
//  batch upload: [log-10, log-11, log-12, log-13, log-14]
//  batch upload: [log-15, log-16, log-17, log-18, log-19]
```

**Comment by shirozatou** [comment]
> Alternatively, it can be a channel BufferOverflow strategy

`SUSPEND`: not upstream friendly,
`DROP_*`: data loss,

Operators based on `transformLatest`: not a choice for some uncancellable process.

**Comment by qwwdfsad** [comment]
What I've meanth is some new strategy, not the existing one, sorry for the confusion.
That operator seems to be the backpressure counterpart of natural batching, with batching happening on the side of the upstream.

>but this operator seems very common.

Maybe you can share what you are using (or were using with another frameworks) instead?

**Comment by shirozatou** [comment]
> What I've meanth is some new strategy

Good idea.

> you can share what you are using

[onBackpressureReduce](https://reactivex.io/RxJava/3.x/javadoc/io/reactivex/rxjava3/core/Flowable.html#onBackpressureReduce-io.reactivex.rxjava3.functions.BiFunction-)

`RxJava` is what I am using, I'm ready to migrate to `Flow` which has multiplatform support.
