### ISSUE TITLE
Need Job.restart() Api

### ISSUE THREAD

**Issue by stefanusayudha** [Kotlin/kotlinx.coroutines#4281]
**Use case**
API to restart a job.

Explain what *specifically* you are trying to do and why.
- It has a cancel operation but don't have restart
- To restart a job requires to create a new job as well as reproducing all component , or values, or parameters, or arguments require by the job to work. Those arguments and parameters sometimes hard to reproduce.
- In the other hand the previous job already have all the information to launch a process.
- In case of a job return error due to some issue, we should be able to restart the job to restart the process.
- We are not always able to restart the job automatically because some protocol might be required to restart the process, like user intention for example.
- In case error happen let say due to temporary IO error, it would be nice to simply call job.restart()

**The Shape of the API**
```kotlin
fun Job.restart()
```

**Comment by fvasco** [comment]
> It has a cancel operation but don't have restart

`Thread` neither.

> To restart a job requires to create a new job as well as reproducing all component , or values, or parameters, or arguments require by the job to work. Those arguments and parameters sometimes hard to reproduce.

It doesn't look too hard to me.

```kotlin
val task: CoroutineScope.() -> Unit = { TODO() }
// start task
launch(block = task) .join()
// restart task
launch(block = task) .join()
```

> In the other hand the previous job already have all the information to launch a process.

Yes, but you should review the [Job's state machine](https://kotlinlang.org/api/kotlinx.coroutines/kotlinx-coroutines-core/kotlinx.coroutines/-job/), too.

> In case of a job return error due to some issue, we should be able to restart the job to restart the process.

Deferred is a Job, a Deferred should be completed twice, one with an error, other with a result?

> We are not always able to restart the job automatically because some protocol might be required to restart the process, like user intention for example.

What is the expected behavior?
How launch a restartable job and a non restartable job?
