### ISSUE TITLE
Release Kotlin 2.1-compatible version

### ISSUE THREAD

**Issue by JakeWharton** [Kotlin/kotlinx.coroutines#4292]
Per [KT-72471 (comment)](https://youtrack.jetbrains.com/issue/KT-72471/2.1.0-Beta2-Removal-of-SubclassOptInRequired-results-in-many-warnings-from-coroutines#focus=Comments-27-10975510.0-0), the current release (1.9.0) depends on an old constructor signature of `@SubclassOptInRequired` [which was changed](https://github.com/JetBrains/kotlin/commit/df10e9e71f9c6e50f98c0562a174b0c321075e91) in Kotlin 2.1 as part of stabilization.

Trying to build a JS binary with `-Xpartial-linkage=disable` produces the following error:
```
e: There is still an unbound symbol at the end of IR linkage process:
Unbound public symbol IrConstructorSymbolImpl: kotlin/SubclassOptInRequired.<init>|<init>(kotlin.reflect.KClass<out|kotlin.Annotation>){}[0]
```

I can enable partial linkage for now to work around the problem, but we generally are wary of doing so (especially for JS). Is it possible to get a new release built with Kotlin 2.1 so that the annotation correctly links against the new `vararg`-based signature and we can go back to disabling partial linkage? Thanks!

**Comment by qwwdfsad** [comment]
We'll do this week, depending on how successful we are with #4296

**Comment by JakeWharton** [comment]
1.10.0 is released.

Thanks!
