### ISSUE TITLE
NoClassDefFoundError when calling launch()

### ISSUE THREAD

**Issue by jetpants** [Kotlin/kotlinx.coroutines#430]
I'm trying my first project following the coroutines tutorial here: https://kotlinlang.org/docs/tutorials/coroutines-basic-jvm.html

I've followed the instructions for creating a Gradle project and I'm using the example code.

I saved the code as Launch.kt and I'm attempting to run the compiled program with `kotlin -cp . LaunchKt`

It throws at exception at the line that calls `launch()`:

`Start
Exception in thread "main" java.lang.NoClassDefFoundError: kotlinx/coroutines/experimental/BuildersKt
	at LaunchKt.main(launch.kt:7)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.jetbrains.kotlin.runner.AbstractRunner.run(runners.kt:61)
	at org.jetbrains.kotlin.runner.Main.run(Main.kt:109)
	at org.jetbrains.kotlin.runner.Main.main(Main.kt:119)
Caused by: java.lang.ClassNotFoundException: kotlinx.coroutines.experimental.BuildersKt
	at java.net.URLClassLoader.findClass(URLClassLoader.java:381)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:424)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:357)
	... 8 more`

I'm sure I'm missing something simple, maybe something on the command-line to tell the run-time that it should include the `kotlinx.coroutines.experimental` library. If so, could this be added to the tutorial?

I see there is the -Xcoroutines=enable option suggested [here](https://kotlinlang.org/docs/diagnostics/experimental-coroutines.html) for compiling from the command-line. Is there a similar option needed at run-time?

Here's my build script (nothing special there):

`buildscript {
    ext.kotlin_version = '1.2.51'
}

plugins { id 'org.jetbrains.kotlin.jvm' version '1.2.51' }

apply plugin: 'java'

group 'jetpants'
version '2.0'

sourceCompatibility = 1.8

repositories {
    jcenter()
    mavenCentral()
}

dependencies {
    compile "org.jetbrains.kotlin:kotlin-stdlib-jdk8"
    compile "org.jetbrains.kotlinx:kotlinx-coroutines-core:0.23.4"
    testCompile group: 'junit', name: 'junit', version: '4.12'
}

compileKotlin {
    kotlinOptions.jvmTarget = "1.8"
}
compileTestKotlin {
    kotlinOptions.jvmTarget = "1.8"
}

kotlin {
    experimental {
        coroutines 'enable'
    }
}

compileKotlin {
    kotlinOptions {
        includeRuntime = true
        noStdlib = false
    }
}`

**Comment by elizarov** [comment]
You to to add `kotlin-coroutines-core` library to the class if you are running application using this library from the command line. Alternatively you can use Gradle application plugin to run (it builds the appropriate classpath automatically): https://docs.gradle.org/current/userguide/application_plugin.html or use `shadow` plugin to build an uberjar with your app and all the libraries: https://github.com/johnrengelman/shadow

**Comment by jetpants** [comment]
Thanks, @elizarov , I have been trying those options today, though without luck. I use the `application` gradle plugin, specifying the `Main-Class` in the manifest for an executable jar that contains the coroutines classes.

I've bundled up all dependencies in the jar and I can run it giving `java/kotlin` just the jar file as the argument but I still get the `NoClassDefFoundError`.

I can see the coroutines classes in my jar (though `kotlinx` appears as `kotlin`, differing from the `import` in my code):

`$ jar tf launch.jar | grep coroutines
kotlin/coroutines/
kotlin/coroutines/experimental/
kotlin/coroutines/experimental/AbstractCoroutineContextElement.class
kotlin/coroutines/experimental/CombinedContext$toString$1.class
kotlin/coroutines/experimental/CombinedContext.class
etc...`

The existing library I want to switch from threads to coroutines will have other command-line applications using it (other than mine own), so I'd like to bind the coroutines classes into the jar or be able to document that when using my library something should be added to the java/kotlin command line. Is there a classpath or something I should be adding?

Thanks and apologies for the newbie question!

My jar declaration in my build.gradle:

`jar {
    manifest {
        attributes 'Implementation-Version': project.version,
                'Implementation-Title': project.name,
                'Implementation-Vendor': '(C) 2018 Steve Ball <jetpants@gmail.com>'
        attributes 'Main-Class': 'LaunchKt'
    }

    from { configurations.compile.collect { it.isDirectory() ? it : zipTree(it) } }
}`

**Comment by jetpants** [comment]
Even manually including `kotlin-coroutines-core` in the fat jar doesn't fix it:

`jar {
    from {
        String[] include = [
            "kotlin-runtime-${kotlin_version}.jar",
            "kotlin-stdlib-${kotlin_version}.jar",
            "kotlin-coroutines-core"
        ]

        configurations.compile
                .findAll { include.contains(it.name) }
                .collect { it.isDirectory() ? it : zipTree(it) }
    }
    ...
}
`

**Comment by elizarov** [comment]
Can you share you project on the github? You do not need all this configuration, manifest, etc. 
1. Follow the docs on setting Kotlin gradle app here: https://kotlinlang.org/docs/reference/using-gradle.html
2. Add you `kotlinx-coroutines-core` library dependency per README here: https://github.com/Kotlin/kotlinx.coroutines#gradle
3. The follow the docs for `application` plugin. You just need to specify `mainClassName` and use `gradle run` to start your application. That's it. No need to touch configuration, jars, anything.

**Comment by jetpants** [comment]
Thanks, @elizarov. I have created a minimal GitHub project as you describe [here](https://github.com/jetpants/clcoroutines).

I can run the project using `./gradlew run` and that is fine. My library is a benchmarking and performance library, so this will not work for users if they must run their programs by invoking Gradle.

I want to investigate switching my library from using threads to using coroutines. I am writing a series of articles on [Low-latency optimisation on the JVM](https://www.linkedin.com/pulse/low-latency-optimisation-jvm-steve-ball/). I am the organiser of the Amsterdam-based _Hi-performance Kotlin Users Group_ and I want to present coroutines as a possible strategy for low-latency applications because of their less-costly setup time compared to OS-level threads.

Running it inside of Gradle currently shows that coroutines and threads have similar (costly) setup times and switching to coroutines hasn't given a measurable performance improvement. That seems very strange to me. I was expecting a boost. Current timings are:

- Single threaded (567 µs)

- Multiple threads (2053 µs); less performant—attributable to costly creation of new threads

- Coroutines (2108 µs); same as threads with small overhead of Gradle running maybe.

If I could run my benchmarking harness from the command line I could dig down into why I am not seeing the expected performance gains from coroutines. I will be writing the next article in the series, addressing parallelism, after my investigation, so I want to shine the best possible light on coroutines and the much more elegant (and potentially) less resource-demanding alternative that they offer to threads or callbacks.

As a related issue, I've read the articles are how coroutines are implemented, but I can't see how coroutines cooperatively multitask when the coroutines are compute-bound. Is there someway to yield the processor (something like `sleep(0)`)? Is there some way I can see the size of the pool in the `CommonPool`? For low-latency services it's often possible to tune the algorithm to match the size of the pool. Without knowing the size of the pool, if there are more compute-bound coroutines than threads in the pool, it will degrade to sequential execution. The worst case is that you divide your task into `n` parts, run each part in a coroutine but there are `n-1` threads. What would be ideal would be to be able to create my own `CommonPool` object with exactly the number of threads I need (`n`) and reuse it to allocate my compute coroutines to.

**Comment by elizarov** [comment]
Coroutines are just thread-pools and executors in disguise. They are designed for writing nicer _asynchronous_ code, for the code that waits something most of the time and to make switching between background and UI threads syntactically nicer. They are not supposed to and cannot give any advantage for compute-bound tasks. You can yield with `yield()` but for CPU-bound task you will necessarily get only as much performance as dictated by the number of CPUs and the CPU-consumption of your own code. You can create your own pools of any size you need (see `newFixedThreadPoolContext` and `Executor.asCoroutineDispatcher` extension).
