### ISSUE TITLE
ForkJoinPool's parallelism is 0

### ISSUE THREAD

**Issue by Ccixyj** [Kotlin/kotlinx.coroutines#432]
I use coroutines on an android virtual device with one cpu only ,  but  find common pool not execute code. finally , i find something like this 
![image](https://user-images.githubusercontent.com/6183506/42557953-6c346b62-8522-11e8-9f36-a57524d3af8d.png)

**Comment by elizarov** [comment]
Omg. That's bad. We should figure out how to detect this case and work around it. This might explain #288 too

**Comment by qwwdfsad** [comment]
So it appears that older versions of android SDK have a off-by-one error when runtime has only one core: https://github.com/AndroidSDKSources/android-sdk-sources-for-api-level-21/blob/master/java/util/concurrent/ForkJoinPool.java#L3278

**Comment by Ccixyj** [comment]
the fix works well !
