### ISSUE TITLE
What does it mean coroutine is cancelled when the resulting job is cancelled?

### ISSUE THREAD

**Issue by finchatticus** [Kotlin/kotlinx.coroutines#433]
In documentation for launch wrote: "Launches new coroutine without blocking current thread and returns a reference to the coroutine as a Job. The coroutine is cancelled when the resulting job is cancelled." What does it mean coroutine is cancelled when the resulting job is cancelled? Could you provide example?

**Comment by elizarov** [comment]
See examples in this section of the guide: https://github.com/Kotlin/kotlinx.coroutines/blob/master/coroutines-guide.md#cancellation-and-timeouts
