### ISSUE TITLE
Misleading enum entry name in test source file

### ISSUE THREAD

**Issue by LouisCAD** [Kotlin/kotlinx.coroutines#438]
https://github.com/Kotlin/kotlinx.coroutines/blob/dae510bba39181b93978f7878c033a50dccad62b/common/kotlinx-coroutines-core-common/src/test/kotlin/kotlinx/coroutines/experimental/channels/TestChannelKind.kt#L30-L33

The enum entry is called `ARRAY_10` but the `ArrayChannel` is of size `8`, which is inconsistent with the rest of the enum entries.

**Comment by qwwdfsad** [comment]
I already fixed that in `develop`
