### ISSUE TITLE
peek() on Channel<T> class

### ISSUE THREAD

**Issue by tr8dr** [Kotlin/kotlinx.coroutines#473]
I am using kotlin actors and would like to do something like:

```
for (msg in channel) {
   when (msg) {
       is A -> {
           batch.add (msg)
           batch.addAll (takeAvailableTypeAMessages(channel))
           <do something with batch>
       is B -> {
           ...
       }
}
```
I need to dequeue and batch items of type *A* that are immediately available on the queue and dispatch.   I recognize could use poll() to get pending messages in the channel.  However, if I encounter a type *B*, I do not want to pull that in, rather leave in the channel for the next iteration.

For example if the following is on the channel:
```
A, A, A, B, A, A
```
I want to get the 3 A's and leave B on the channel for the next cycle of processing.   Likewise if the channel is:
```
A, A, A, A
```
I want to get the 4 A's but not block to await more A's or a B.

One way to implement this would be to have a ```peek()``` method on the channel so that I can lookahead before dequeuing.  However have not seen an operation equivalent to this.   takeWhile {} was a possibility, but I think would block in the later example.

Is there a way I could implement this (precluding pre-batching TypeA messages, which is not an option)?   Thanks

**Comment by elizarov** [comment]
Conceptually, there is no way to have `peek` on a channel. Instead, you should create two different channels -- one for `A` items, and another for `B` and the use `select`:

```
select<Unit> {
    chanA.onReceive { a -> .... }
    chanB.onReceive { b -> .... }
}
```
