### ISSUE TITLE
Allow to create view with limited threads count(Experimental dispatcher).

### ISSUE THREAD

**Issue by e5l** [Kotlin/kotlinx.coroutines#475]
Consider the following use case:
```
val client = HttpClient(threads = 2)
val server = HttpServer(threads = 6)

class HttpClient(threads: Int) {
    val dispatcher = DefaultDispatcher.limited(threads)
}
...
```

**Comment by elizarov** [comment]
This is related to #261. We need to provide ability to create thread-limited blocking and non-blocking dispatchers. It does not see that the corresponding function need to be prefixed with `DefaultDispatcher`. Since it is a default, some top-level functions shoud do just fine.

**Comment by qwwdfsad** [comment]
I've introduced a corresponding API for the experimental dispatcher.
Top-level functions (or members of DefaultDispatcher) will be introduced along with #261
