### ISSUE TITLE
Start jobs with different priorities

### ISSUE THREAD

**Issue by SUPERCILEX** [Kotlin/kotlinx.coroutines#476]
Use case: I have a highly parallelized and computationally intensive series of jobs that completely saturate the default `ForkJoinPool` for a few dozen seconds. However, I want to notify the user of current progress via a ticker that uses `delay`. Currently, the ticker gets stuck waiting for all the other jobs to finish before it can proceed because the pool is saturated.

Workaround: create a seperate single thread dispatcher that does its own thing. This isn't a bad solution, but it took me a half-hour to figure out why the default dispatcher wasn't working.

**Comment by fvasco** [comment]
The workaround is not a workaround, it is a *know issue*.
#261 can help your use case.

The workaround is to use `yield` function *sometimes* to resume others coroutines.

See also: https://stackoverflow.com/a/23436125

**Comment by SUPERCILEX** [comment]
Oh I see, #79 should address this use case.

PS: I don't think #261 will affect me because I'm explicitly creating a new thread: `Executors.newFixedThreadPool(1).asCoroutineDispatcher()`.
