### ISSUE TITLE
Coroutine in kotlin 1.3

### ISSUE THREAD

**Issue by mandomi** [Kotlin/kotlinx.coroutines#489]
Recently I have read kotlin blog post about kotlin 1.3-M1, I came across to this sentence: coroutine has graduated. After that I have tried to add this new features to my project, but each time I synced my project's dependencies I got an error message: you should use library that be compatible with kotlin 1.3
After a lot of time I have found that you have written a wrong dependency in your eap13 branch's description.
you have written : compile 'org.jetbrains.kotlinx:kotlinx-coroutines-core:0.24.0'
instead of : compile 'org.jetbrains.kotlinx:kotlinx-coroutines-core:0.24.0-eap13'

**Comment by qwwdfsad** [comment]
Yes, the guide (I assume you are talking about it) is pointing to stable version 0.24.0, while 1.3 is in early access preview (eap) for early adopters.
Mainline will be updated with release of Kotlin 1.3

**Comment by mandomi** [comment]
In the ReadMe file for **eap13 branch**: https://github.com/Kotlin/kotlinx.coroutines/blob/eap13/README.md

you have written change **ext.kotlin_version** to  **'1.3-M1'** but you haven't changed the coroutines dependency to  **compile 'org.jetbrains.kotlinx:kotlinx-coroutines-core:0.24.0-eap13'**

notice : In **eap13 branch**

**Comment by qwwdfsad** [comment]
Thanks, will fix that
