### ISSUE TITLE
Kotlin/Native has problem with names of classes

### ISSUE THREAD

**Issue by MarcinMoskala** [Kotlin/kotlinx.coroutines#496]
Looks like Kotlin/Native has problems with "-" in names: 

<img width="810" alt="zrzut ekranu 2018-08-15 o 11 22 15" src="https://user-images.githubusercontent.com/6850787/44144517-c117737c-a07f-11e8-8cbb-74b1bd619825.png">
<img width="814" alt="zrzut ekranu 2018-08-15 o 11 22 08" src="https://user-images.githubusercontent.com/6850787/44144518-c1378e1e-a07f-11e8-9cb2-d95b906becbf.png">

Steps to reproduce:
Clone https://github.com/MarcinMoskala/KotlinAcademyApp
Checkout to  new_native_plugin branch
Open iOS in xCode
Click Run

**Comment by qwwdfsad** [comment]
Fixed on Kotlin/Native side
