### ISSUE TITLE
assign coroutine to a variable

### ISSUE THREAD

**Issue by KasperJanssens** [Kotlin/kotlinx.coroutines#505]
Hello,

I would like to write a test for a function taking a coroutine as an argument. The only possibility I seem to have to declare a 'test-coroutine' is creating a 'suspend' member function inside the test class. That is slightly annoying when I have multiple tests with different coroutines I want to inject. 

Is it possible to declare a suspendable lambda and assign it to a variable? Currently I have not really found a way to do this but I'm rather new at this.

**Comment by elizarov** [comment]
Yes. It is possible. Just write `val mySuspendLambda: suspend () -> Unit = { ... }`
