### ISSUE TITLE
example-app: com.android.builder.dexing.DexArchiveBuilderException

### ISSUE THREAD

**Issue by tinyvampirepudge** [Kotlin/kotlinx.coroutines#512]
when I run coroutine-android demo, I met this Error on building process.
**kotlinx.coroutines-master/ui/kotlinx-coroutines-android/example-app**

Caused by: com.android.builder.dexing.DexArchiveBuilderException: Failed to process /Users/xxx/.gradle/caches/modules-2/files-2.1/org.jetbrains.kotlinx/kotlinx-coroutines-core/0.25.0/5664ba2d20c6dcc88c912cc9666baa7f03203bcd/kotlinx-coroutines-core-0.25.0.jar

**Comment by elizarov** [comment]
I'm updatedAndroid Gradle Tools version to `3.3.0-alpha04` and Gradle to version `4.9` and it seems that it fixed the problem. Please, check.

**Comment by glush** [comment]
I'd try with last alpha 3.3.0-alpha06, Gradle 4.9. Confirm. Fixed.

**Comment by brettwillis** [comment]
It seems that Gradle 4.9 requires gradle module format version `0.4`, while `kotlinx-coroutines-core-common-0.25.0.module` uses format `0.3`.

    > Could not resolve org.jetbrains.kotlinx:kotlinx-coroutines-core-common:0.25.0.
         > Could not parse module metadata https://jcenter.bintray.com/org/jetbrains/kotlinx/kotlinx-coroutines-core-common/0.25.0/kotlinx-coroutines-core-common-0.25.0.module
            > Unsupported format version '0.3' specified in module metadata. This version of Gradle supports format version 0.4 only.

Is it currently possible to use coroutines `0.25.0` in a multiplatform project?

**Comment by nbransby** [comment]
@brettwillis looks like you can't go higher than gradle 4.7 to use coroutines atm
