### ISSUE TITLE
how many actors

### ISSUE THREAD

**Issue by jagiellonczyk14** [Kotlin/kotlinx.coroutines#519]
Hi I have short practical question, approximately how many actors are too much
To be more precise actors are very handy and I would like to give actor to a lot of objects to organize it neatly; I know that they are lightweight, however they are still keeping corountines in existence  so they need to consume memory and CPU by mere existence;
so in Desktop application what should be resonable self imposed limit something like 100 actors 1000 or if
 10000 would still not be a practical problem in normal situations?
I am obviously aware that there is no 1 answer for all aps ; just wondering about some rule of thumb

**Comment by elizarov** [comment]
A small actor would occupy a few hundred bytes of memory. Now how much is much depends on your app. In backend application millions of actors would be fine (a few hundred megs is not a problem for a big application), but for a UI app that is probably too much.

**Comment by jagiellonczyk14** [comment]
thank You for fast help
