### ISSUE TITLE
Mutex.withoutLock

### ISSUE THREAD

**Issue by clarcharr** [Kotlin/kotlinx.coroutines#527]
I find myself doing this pattern a lot:

```kotlin
mutex.withLock {
    someWork()

    mutex.unlock()
    try {
        someOtherWork(channel.receive())
    } finally {
        mutex.lock()
    }

    someMoreWork()
}
```

In the case of a regular `Lock`, I'd use a condition variable, which will automatically relinquish the lock. Unfortunately, for this case, I can't do that. It'd be nice to have a `mutex.withoutLock { ... }` or equivalent for this case.

**Comment by penn5** [comment]
This would be incredibly useful to me. For example, using recursive functions. IMO this should just be an inline function equating the the code sample in the OP. AFAIK there is no better alternative than Mutex for this use case, unless a reentrant lock is added (which was previously rejected in #1686).
