### ISSUE TITLE
Error parsing triggers: Cannot find module 'kotlinx-atomicfu' with 0.25.3

### ISSUE THREAD

**Issue by SUPERCILEX** [Kotlin/kotlinx.coroutines#529]
@elizarov Could you please add integration tests? It seems like the `atomicfu` stuff keeps breaking every other release.

**Comment by SUPERCILEX** [comment]
These: #396, #370

And the current version broke it again.

**Comment by SUPERCILEX** [comment]
I could give you my [project](https://github.com/SUPERCILEX/Robot-Scouter/tree/61fa08798840bf5849ac88570d68f5b87e462e5b), but you'll have to setup the Firebase CLI.

Run `./gradlew setup && ./gradlew deployServer --only functions:logUserData`

**Comment by elizarov** [comment]
Can you, please, include some relevant pieces of your build log to help me pinpoint the problem? It is really strange, since 0.25.3 coroutines artifacts do not depends on `atomicfu` both for JVM and JS versions. This dependency is now fully erase and is an internal implementation detail only.

**Comment by elizarov** [comment]
I've found where the extra dependency on `atomicfu-common` is leaking (and can fix it), but I cannot reproduce your project on my integration tests -- it seems to be deployed to all the appropriate repos.

**Comment by SUPERCILEX** [comment]
@elizarov Awesome! And don't worry my project specifically, I'd just like to see a general "Does this work at runtime" integration test for JS. My project will compile, but it will only fail when running `firebase deploy` and I'm not sure what magic they do to check that stuff.

**Comment by elizarov** [comment]
I have no idea either, nor I know how to write a test to check. All I can say is that I see all the latest versions of `kotlinx-atomicfu` deployed to NPMJS, but I also see that NPSJS package.json for `kotlinx-coroutines-core` does not declare `kotlinx-atomicfu` as its dependency anymore. You check it here: https://www.npmjs.com/package/kotlinx-coroutines-core

**Comment by SUPERCILEX** [comment]
Yeah, that's exactly the problem: because it isn't declared, the Firebase thing freaks out. As long as you fix the leak, it should work. 🤷‍♂️

**Comment by elizarov** [comment]
Something went wrong with npm upload in this release. Wrong aftefact got uploaded. For JS use 0.25.0 for now, there are no changes. Will fix.

**Comment by SUPERCILEX** [comment]
SGTM 👍

**Comment by LouisCAD** [comment]
The title should specify that it only affects JS.
