### ISSUE TITLE
The name for the main Android dispatcher

### ISSUE THREAD

**Issue by elizarov** [Kotlin/kotlinx.coroutines#533]
We should finalize the name for the main Android dispatcher for 1.0 release of coroutines. The current name is `UI`, but Android documentation names the corresponding concept "the main thread" (see also here https://github.com/Kotlin/kotlinx.coroutines/issues/427#issuecomment-403562661). Arguably, with structured concurrency (see #410) this name would not be used much often, but we still need to make sure it is clearly named.

**Comment by JakeWharton** [comment]
I strongly prefer `MainThread` for a few reasons:
* The main thread is not always the UI thread
* The main thread is still needed in locations like application subtypes, services, brodcast receivers, job scheduler jobs, etc. where there is no UI to speak of.

**Comment by objcode** [comment]
Seconding `Main` which matches existing APIs (https://developer.android.com/reference/android/os/Looper#getMainLooper()) and is more accurate.

**Comment by elizarov** [comment]
While we are at it, lets reopen discussion #41 about structures for all dispatcher name. Now, when we are about to release structured concurrency (#410) you would not have to mention the dispatcher names too often, so it makes sense to group them all.
