### ISSUE TITLE
Provide high-performance and reusable CancellableContinuation implementation

### ISSUE THREAD

**Issue by elizarov** [Kotlin/kotlinx.coroutines#534]
Consider the following code that reads some bytes in a loop:

```
suspend fun foo() {
   while (true) {
       val bytes = readBytes(buf) // suspending
       if (bytes < 0) break
   }
}
```

where `readBytes` is written via `suspendCancellableCoroutine`. The problem is that each `readBytes` invocation allocates a new `CancellableContinuationImpl` object and some auxiliary ones to track parent's cancellation. This is unacceptable for high-performance IO code and a standard solution need to be provided for that. For 1.0 release we are looking for an experimental implementation of such an API that relies on new feature in 1.3 coroutines: `ContinuationInterceptor.releaseInterceptedContinuation`.

**Comment by qwwdfsad** [comment]
Will be fixed in 1.3.3 by #1534
