### ISSUE TITLE
A coroutine builder needed for async results

### ISSUE THREAD

**Issue by DilbagSandhu** [Kotlin/kotlinx.coroutines#536]
my understanding of async() builder is that the code inside the builder must be synchronous. and coroutine finishes as it hits builder's closing bracket.

but what if the result I want to return is asynchronous.
like in android 

```
val location = async {
         LocationServices.getFusedLocationProviderClient(applicationContext).lastLocation
                 .addOnSuccessListener { it ->
                // location returned after 300ms
                  }
}
```

in the above code, there is no way to hold the coroutine until the location is returned. 
one workaround I found is to use CompletableDeferred like

```
val location = async {
                val deferred = CompletableDeferred<Location>()
                LocationServices.getFusedLocationProviderClient(applicationContext).lastLocation
                        .addOnSuccessListener { it ->
                      // location returned after 300ms
                           deferred.complete(it)
                        }
              deferred.await()
 }
```

I have to write the boilerplate everytime i need these type of results. what if we have a coroutine builder for these situations which make it easy to work with asynchronous results. like

```
val location = asyncResult<Location> {
                LocationServices.getFusedLocationProviderClient(applicationContext).lastLocation
                        .addOnSuccessListener { it: location
                      // location returned after 300ms

                           result.success(it) 
                      // result.error for error
                        }
            }
```

above suggested coroutine builder will start a new coroutine and suspends at the closing bracket. when the location returned we can pass the result back somehow( like result.success()) so the coroutine resumes and return the result.

I am a beginner, So I might have wrong understanding of Coroutine world. correct me if the case I am asking is not possible or there is already a solution available.

**Comment by mrmitew** [comment]
@DilbagSandhu , you can already achieve what you want using the `suspendCoroutine` builder. 

Example:
```
suspend fun getLastKnownLocation() =
            suspendCoroutine<Location> { cont ->
                LocationServices.getFusedLocationProviderClient(applicationContext).lastLocation
                        .addOnSuccessListener { location ->
                            cont.resume(location)
                        }
            }
```

In case of an error, you can resume the coroutine with an exception like so: `cont.resumeWithException(..)`

**Comment by elizarov** [comment]
^ This. Thanks.

**Comment by SolomonSun2010** [comment]
> ^ This. Thanks.

Do this call with current continuation ?

**Comment by DilbagSandhu** [comment]
ok, the above solution suspends the coroutine.
As I am assuming all this work happing on background threads. but as the coroutine got suspended where does the onSuccess code will run, on the main thread right!
to handle this we have to add another coroutine inside the onSuccess if we want to do any heavy calculation and then continue.
we also have to define the scope of that coroutine somehow.

the solution doesn't seem to be complete!
