### ISSUE TITLE
Integrate TestCoroutineContext with structured concurrency

### ISSUE THREAD

**Issue by elizarov** [Kotlin/kotlinx.coroutines#541]
`TestCoroutineContext` (#297) should be integrated with structured concurrency (#410), so that all builders can be used inside the test context (custom builder-extension to be deprecated).

**Comment by qwwdfsad** [comment]
The good idea is to extract `TestCoroutineContext` and `TestBase` into a separate module, maybe getting rid of inheritance

**Comment by objcode** [comment]
I'm taking a look at putting together a PR for this.

**Comment by objcode** [comment]
See https://github.com/Kotlin/kotlinx.coroutines/pull/890 for a draft API that would do this integration. I expect it'll go through some changes during review.

Files are still in the same place - it's mostly up for API review right now. After https://github.com/Kotlin/kotlinx.coroutines/pull/749 lands if this API is promising it should migrate to `kotlinx-coroutines-test`.

Thanks,
Sean

**Comment by qwwdfsad** [comment]
Fixed in 1.2.1
