### ISSUE TITLE
Way to use a CoroutineDispatcher as a RxJava Scheduler

### ISSUE THREAD

**Issue by chrisbanes** [Kotlin/kotlinx.coroutines#548]
The rx2 artifact currently provides `Scheduler.asCoroutineDispatcher()` to use a Scheduler as a CoroutineDispatcher, but not the other way around.

Ideally I'd like to move over to the new `IO` and `BackgroundDispatcher`, and then move my Rx observables to use the same threads too.

**Comment by elizarov** [comment]
PR is welcome!

**Comment by chrisbanes** [comment]
I'll PR when I've done my KotlinConf slides (if no-one else grabs it first)

**Comment by elizarov** [comment]
Please do it for all reactive implementations (rx1, rx2, and reactor) if possible, just like `asCoroutineDispatcher` is implemented in all of them.

**Comment by jblejder** [comment]
I made PR #857

**Comment by Zeyad-37** [comment]
Any progress here ?
