### ISSUE TITLE
TickerMode names ambiguous

### ISSUE THREAD

**Issue by dualscyther** [Kotlin/kotlinx.coroutines#550]
The current names are here: https://kotlin.github.io/kotlinx.coroutines/kotlinx-coroutines-core/kotlinx.coroutines.experimental.channels/-ticker-mode/index.html

I've pasted the relevant section here:

- FIXED_PERIOD: Adjust delay to maintain fixed period if consumer cannot keep up or is otherwise slow. This is a default mode.
- FIXED_DELAY: Maintains fixed delay between produced elements if consumer cannot keep up or it otherwise slow.

Is there a rationale behind the two names? It's not immediately clear which one means what, without reading the documentation. In my opinion, they both sound like the description of FIXED_DELAY. A user of the `ticker()` function will be aware of the two modes, they simply need a way to disambiguate the two without needing to constantly refer to the documentation. Perhaps for FIXED_PERIOD we can use:

`TickerMode.ADAPTIVE`

And for FIXED_DELAY we can use:

`TickerMode.CONSTANT`, `TickerMode.FIXED`, `TickerMode.FIXED_PERIOD` or `TickerMode.FIXED_DELAY`. I like CONSTANT or FIXED, I don't think the _PERIOD or _DELAY endings are necessary because given the `TickerMode` receiver, the user already knows that they are selecting some delay/period mode.

**Comment by qwwdfsad** [comment]
>Is there a rationale behind the two names?

Yes, it is following Java convention: `scheduleWithFixedDelay` and `scheduleAtFixedRate`.
We've decided not to introduce a fixed rate though as it is easy to create a memory leak with an unlimited channel. "Period" is not yet used word in this context and was more or less reflecting its contract, so it was chosen.

> A user of the ticker() function will be aware of the two modes

He should not. It has a default argument that follows a principle of least surprise and **if** user need to have a more precise control over timings it can start digging up.

There is a possibility that name will be changed when tickers will be integrated into structured concurrency, though I am not sure that "adaptive" is a self-describing term.
