### ISSUE TITLE
Error handling like RxJava

### ISSUE THREAD

**Issue by takahirom** [Kotlin/kotlinx.coroutines#567]
I wrote it in RxJava as follows.

```kotlin
    api.fetchPersons()
        .subscribeOn(scheduler)
        .subscribe(
            { persons ->
              showPersons(persons)
            },
            { e ->
              showErrorDialog(e)
            })
```

I enclosed with try catch to do the same on kotlin coroutines as follows. 
But in this case CancellationException did not go to parents, so I thought that it would be in an invalid state.
Is it fine just like this?

```kotlin
    launch { 
      try {
        val persons = api.fetchPersons() // suspend function
        showPersons(persons)
      } catch (e: Exception) {
        showErrorDialog(e)
      }
    }
```

**Comment by takahirom** [comment]
I think slack is more appropriate, so I will move.

**Comment by mhernand40** [comment]
I'd be curious to know what became of this discussion. I wound up asking a similar question in the #coroutines Slack Channel.

https://kotlinlang.slack.com/archives/C1CFAFJSK/p1562606190132400

It sounds very much like Kotlin Coroutines require you to be more specific in your `Exception` handling. In the example above, the code would have to be updated like so:
```Kotlin
    launch { 
      try {
        val persons = api.fetchPersons() // suspend function
        showPersons(persons)
      } catch (ce: CancellationException) {
        throw ce
      } catch (e: Exception) {
        showErrorDialog(e)
      }
    }
```
Or you explicitly catch all the different exceptions that `api.fetchPersons()` can throw, e.g., `IOException`, `SocketTimeoutException`, etc.

Rx definitely makes it easier to `try/catch` any `Throwable`, which some may argue is not ideal.
