### ISSUE TITLE
Dispatchers.Main -> Dispatchers.Android ?

### ISSUE THREAD

**Issue by kirill-grouchnikov** [Kotlin/kotlinx.coroutines#575]
[This page](https://github.com/Kotlin/kotlinx.coroutines/blob/master/ui/README.md) highlights the inconsistency in naming toolkit-specific dispatchers. For Swing and JavaFX the naming follows the name of the toolkit. For Android it is named in a much more generic way.

**Comment by JakeWharton** [comment]
This was clarified a bit here: https://github.com/Kotlin/kotlinx.coroutines/issues/41#issuecomment-420192828

Basically, `Main` is only available when authoring for the Android platform whereas `Swing` and `JavaFX` are both available when authoring for desktop JVM>
