### ISSUE TITLE
HandlerDispatcher name

### ISSUE THREAD

**Issue by Uiasdnmb** [Kotlin/kotlinx.coroutines#580]
I've updated to 0.26.0 recently and noticed that `HandlerContext(handler, name)` is deprecated. 

If I understand correctly, it should be replaced with `Handler.asCoroutineDispatcher()`. However this doesn't provide the name argument which I need for debugging, so I'm forced to use "deprecated" constructor.

**Comment by elizarov** [comment]
I see. No it was not intentional. I'll leave it open as a change request.

**Comment by elizarov** [comment]
@Uiasdnmb can you, please, clarify what different HandlerDispatcher implementations you are using in your code? What is your use-case? Shall we just include `Handler.toString` into the string representation of the `CoroutineDispatcher` that is produced by `handler.asCoroutineDispatcher()`?

**Comment by Uiasdnmb** [comment]
From source I see it already does use `Handler.toString` as fallback in case of `name` being `null`. 

But it does impose the need of subclassing the handler with custom `toString` before using `asCoroutineDispatcher`.

I have a "loader" framework based on coroutines that uses `HandlerContext` to return results on UI thread, but each loader has its own `HandlerContext` instance so name is rather handy in printing.
