### ISSUE TITLE
CountDownLatch implementation

### ISSUE THREAD

**Issue by konrad-kaminski** [Kotlin/kotlinx.coroutines#59]
In JDK we have [CountDownLatch](https://docs.oracle.com/javase/8/docs/api/java/util/concurrent/CountDownLatch.html). It'd be useful to have a `CountDownLatch` which is aware of coroutines. It could have the following interface:

```kotlin
interface CountDownLatch {
    fun countDown()
    fun getCount(): Long
    suspend fun await()
    suspend fun await(time: Long, unit: TimeUnit = TimeUnit.MILLISECONDS): Boolean
}
```

I created two different implementations:
* [First](https://gist.github.com/konrad-kaminski/d7808070f4218349674589e1dc97264a) which uses a list of `Continuation`s which are resumed when the counter goes down to 0,
* [Second](https://gist.github.com/konrad-kaminski/74942a238bcac5318c4c1b3a464a4e77) which uses `ConflatedBroadcastChaneel` holding current state of latch. Note that the `countDown` function in this version is suspending.

I'm sure a better(faster!) implementation could be made.

Looking for an opinion on this.

**Comment by elizarov** [comment]
The direct implementation is definitely better. However, I'm not yet convinced that ContDownLatch-like mechanism is really needed. See the other issue for discussion [Go-like WaitGroup to wait multiple coroutines to finish](https://github.com/Kotlin/kotlinx.coroutines/issues/58).

On the other side, something like Phaser might be useful. But I would need to see use-cases first, anyway.

**Comment by konrad-kaminski** [comment]
Thanks for the explanation. Closing the issue as right now now it seems to be of no use.

**Comment by venkatperi** [comment]
Although this is closed, posting a link to an implementation of [CountdownLatch](https://github.com/venkatperi/kotlin-coroutines-lib/blob/master/docs/com.vperi.kotlinx.coroutines.experimental/-co-countdown-latch/index.md)

**Comment by emilmuller** [comment]
A non-blocking CountDownLatch would be very useful to me.
I come from C# where I frequently employ Semaphore/SemaphoreSlims. They are (among other things) quite useful for replacing mutexes.

**Comment by Mahoney** [comment]
I'm curious as to how I should go about implementing `sendMessageAndWaitUntilProcessed` without a CountDownLatch (or equivalent) in this gist: https://gist.github.com/Mahoney/52fa3184f5af6b00a380cb778cc551ca

**Comment by elizarov** [comment]
> I'm curious as to how I should go about implementing `sendMessageAndWaitUntilProcessed` without a CountDownLatch (or equivalent) in this gist: https://gist.github.com/Mahoney/52fa3184f5af6b00a380cb778cc551ca

@Mahoney You can use a locked mutex (that you unlock to signal event), or a semaphore (that you release to signal an event), or a channel (that you offer an event to) for this particular snippet. Any of those primitives would work.
