### ISSUE TITLE
0.26 backward incompatibility

### ISSUE THREAD

**Issue by Pitel** [Kotlin/kotlinx.coroutines#593]
Our Android app has heavy use of coroutines. But after upgrade from 0.25.3 to 0.26.x, the code stopped working.

Sure, I know about new `CoroutineScope` and I'm definitely gonna refactor it to use that (no one wants 100 deprecation warnings, right) later, but I'd like to have it working first.

Our typical coroutine builder look like this: `launch(UI, parent = job)`.

Are there some known incompatibilites? Something particular I should look for? I've already spent couple of hours on it and couldn't find anything.

**Comment by elizarov** [comment]
This particular code pattern `launch(UI, parent = job)` should not be affected by the structured concurrency change, as you specify explicitly both the dispatcher and the parent job. However, simpler invocations might be affected, as their semantics may change if they start capturing parent scope. Otherwise, there were no incompatibilities or known introduced bugs (that were not present in 0.25.3)

**Comment by qwwdfsad** [comment]
So could you please provide an example of code which is *broken* after migration?
`launch(UI, parent = job)` is deprecated, but neither `UI` nor top-level `launch` are removed, only deprecated with suggested replacement `GlobalScope.launch` and `Dispatchers.Main`.

**Comment by Pitel** [comment]
Well, it's pretty complicated, but I'll try...

Our app is based on WebRTC for audio/video/networking and MQTT for signaling.

The WebRTC has some state (connecting, connected, have_local_sdp, have_remote_sdp, need_renegotiation, etc.). It also has listener interface (provided by the library), which provides callback for those state changes and other audio/video/connectivity related stuff. Some of those callbacks are implemented with `launch` inside.

The MQTT is responsible for sending and receiving messages. It's based on another library, so each message (sent or received) is now pretty much handled by it's own coroutine (`launch`).

What is happening is that when something changes in WebRTC (one `launch` here), we send that change via MQTT (another `launch` there) to another device. That device received that message and parses it (another `launch`) and propagate this change to it's WebRTC (another `launch`).

On 0.25, everything worked pretty much the way it shoudl: one message was received, WebRTC was changed, another message received, WebRTC was already in expected state, etc. But since 0.26, we're seeing that when second message is received, WebRTC changes from the first messages are not yet propagated.

Maybe, just maybe, we should use Actors for those MQTT and WebRTC wrapper classes? I should read some more about them.

**Comment by qwwdfsad** [comment]
Sorry, but your description clarifies nothing about how coroutines machinery is used, but rather explains your app architecture.

Let's checklist:
1) Are you using `isActive`? If so, how?
2) Do your classes implement `Job`, `CoroutineScope` or `AbstractCoroutine`?
3) How did you upgrade to a newer coroutines? Updated library version and recompiled everything without other changes in the source code?
4) Did you dissect your application behaviour changes down to coroutines version? Are you sure it's not a bug introduced somewhere around library version update? If yes, downgrading library version resolves the issue?

>Maybe, just maybe, we should use Actors for those MQTT and WebRTC wrapper classes? I should read some more about them.

It's a good idea to read what primitives `kotlinx.coroutines` provide. For a stream of events there is a lot of primitives better than "launch on every event"

**Comment by Pitel** [comment]
1. `isActive` is used in reconnect watchdog. It's a `Job` with infinite `while` loop and 5 seconds delay, and after the delay, we check if the job is still active (otherwise, the infinite `while` loop inside `Job` won't ever break, right?). But I don't think this is the cause of the issue. I's really more about messaging and WebRTC state synchronization.
2. Our Android activities and fragments uses `Job`. `CoroutineScope` is new in 0.26, so we're in process of rewriting it. But even withou it (just changing dependency from 25 to 26), ou app breaks. (That's the original point of this issue.)
3. Yes. Just changing dependency version and recompiling breaks the app.
4. Yes. Our app works with 0.25.3, but does not with anything newer.

**Comment by Pitel** [comment]
Sorry, I can't give you our code, obviously, because of NDA. And I can't create reproducible example, because I don't know what exactly the problem is. And my original question was just if there are any known incompatibilities.

But let's try it one more time...

On 0.25, the high level overview of actions was like this:
1. Message is received
2. Coroutines is launched to process the message
3. Message is processed, WebRTC changes are made, probably causing another coroutines to start
4. WebRTC state is stabilized
5. `GOTO 1`

Note, that there aren't any synchronization mechanisms involved, no lock, just `launch`es and `async`s.

On 0.26, it looks more like this:
1. Message 1 is received
2. Coroutines is launched to process message 1
3. Message 1 is being processed, WebRTC changes are made, probably causing another coroutines to start
4. During the processing, message 2 is received
3. Message 2 is being processed, but it fails, because WebRTC is not yet in stable state.

All this is cause by just changing the dependency version. No changes in our code. Also note, that all coroutines are launched on Android's UI context.

So there is obviously some synchronization issue. And since I found it (and wrote this issue), I keep thinking how to solve it. The thing is, the WebRTC is changing states _on it's own_, on it's own thread, totaly unaware of any coroutines.

**Comment by LouisCAD** [comment]
@Pitel There's only a few options to troubleshoot your issue on the top of my head:
1. Create an open source reproducer project that is as simple as possible
2. Send a snippet that reproduces the issue

**Comment by qwwdfsad** [comment]
> No changes in our code.

That's probably the problem. 
For example, if you had following code:
```
launch {
  launch { // <- is invoked on outer launch scope
    // do something
  }
  // do something else 
}
```
after update it will behave **diffrently**, because launch defines its own scope.
To preserve compatibility, use
```
GlobalScope.launch {
  GlobalScope.launch {
  }
}

```

**Comment by Pitel** [comment]
@qwwdfsad Is this also the case when we explicitely define context for each `launch`?
```kotlin
launch(UI) {
  launch(UI) {
  }
}
```

I'm now also trying to do some tests to verify it. How can I check what the current scope is?

**Comment by elizarov** [comment]
@Pitel If you explicitly do `launch(UI)` the behavior will still be different. It used to be the case that every `launch` was independent unless you explicitly specify that you want a _child_ coroutines via `launch(coroutineContext)`. It is a child _by default_, unless you explicitly ask to make it global via `GlobalScope.launch`.

**Comment by Pitel** [comment]
In our code, we've had `launch(UI, parent = job)` or `async(UI, CoroutineStart.LAZY, job)`. But the `parent` parameter is now gone. The proper refactoring would become `launch(UI + job)` or `async(UI + job, CoroutineStart.LAZY)`, right?

**Comment by Pitel** [comment]
Also, adding `GlobalScope` to each `launch` and `async` makes the app work with Courtines 0.30.

We'll now of course start adding scopes, and see where it breaks.

Thanks for your help!
