### ISSUE TITLE
async / GlobalScope.async are not equivalent inside runBlocking{ }

### ISSUE THREAD

**Issue by AlexDochioiu** [Kotlin/kotlinx.coroutines#606]
Long story short, I have two pieces of code which should be equivalent, yet they are not. Android's Studio "jump to declaration" shows that they both point to the same thing.

The not working piece of code:

```
init {
        runBlocking {
            Mockito.`when`(fakeAuthRepo.getApiToken()).then {
                return@then async { return@async tokenResponse }
            }
        }
    }
```

The working piece of code:

```
init {
        runBlocking {
            Mockito.`when`(fakeAuthRepo.getApiToken()).then {
                return@then GlobalScope.async { return@async tokenResponse }
            }
        }
    }
```

The only difference between the two is that one uses async and the other one uses GlobalScope.async. Considering that this is inside a runBlocking scope, I expect the two to be equivalent (which also seems to be the case when I check the declaration). However, only the second one actually works (the first one throws exception when I call the method I faked).

P.S. async does not give the deprecated warning, or any other warning (as it is inside runBlocking{ } )
P.P.S. Relevant gradle imports:

```
api "org.jetbrains.kotlin:kotlin-stdlib-jdk7:1.2.61"
api 'org.jetbrains.kotlinx:kotlinx-coroutines-android:0.26.0'

testImplementation 'junit:junit:4.12'
testImplementation 'org.mockito:mockito-core:2.13.0'
testImplementation 'com.squareup.okhttp3:mockwebserver:3.9.1'
```

**Comment by elizarov** [comment]
What are you trying to achieve? I cannot decipher your code. It just looks to complicated. What is the signature of `getApiToken` function? Is it a suspending function? If yes, then why it returns a deferred? If no, then why do you use `runBlocking`?
