### ISSUE TITLE
CoroutineScope cancellation requires a Job

### ISSUE THREAD

**Issue by ZakTaccardi** [Kotlin/kotlinx.coroutines#610]
I expected a `CoroutineScope` to be cancellable on it's own. But a `Job` must be specified for a `CoroutineScope` to be cancelled. This seems a bit odd and error-prone.

### Example

The following fails with `IllegalStateException: Scope should no longer be active`:

```
val scope = CoroutineScope(dispatcher)
check(scope.isActive) { "Scope should be active" }

scope.coroutineContext.cancel()

check(!scope.coroutineContext.isActive) { "Dispatcher should no longer be active" }
check(!scope.isActive) { "Scope should no longer be active" } // fails here
```

But if you cancel via a job, no problems:

```
val job = Job()
val scope = CoroutineScope(dispatcher + job)
check(scope.isActive) { "Scope should be active" }

job.cancel()

check(!scope.coroutineContext.isActive) { "Dispatcher should no longer be active" }
check(!scope.isActive) { "Scope should no longer be active" }
```

**Comment by fvasco** [comment]
It seems a bug

> `isActive` is a shortcut for `coroutineContext.isActive`

https://kotlin.github.io/kotlinx.coroutines/kotlinx-coroutines-core/kotlinx.coroutines.experimental/is-active.html

**Comment by elizarov** [comment]
This is not a bug. It is so by design. The cancellation is supported via `Job`.

**Comment by elizarov** [comment]
To help with this function and make it more use-friendly, we'll change it to throw an exception if the context does not contain a `Job`.

**Comment by fvasco** [comment]
Should the documentation fixed?

`isActive` and `coroutineContext.isActive` have different behaviour, despite the documentation.

**Comment by elizarov** [comment]
Nope. That was bad idea. We'll create `Job()` if it is missing.
