### ISSUE TITLE
Add firebase database module

### ISSUE THREAD

**Issue by cypressious** [Kotlin/kotlinx.coroutines#62]
Firebase DB on Android could use some suspend extensions.

**Comment by elizarov** [comment]
I really hope somebody contributes the corresponding integration. See this document on how to contribute: https://github.com/Kotlin/kotlinx.coroutines/blob/master/integration/README.md

**Comment by lucasvalenteds** [comment]
There is an implementation in [this](https://gist.github.com/beyondeye/f69ba427938f79801c291d18131ff1d9) gist made by @beyondeye. Maybe a module can be written with that code.

Renaming some functions and changing their signatures to be extension functions that code would look like this.

```kotlin
@Test
fun `Can write and read from Firebase Database`() = runBlocking {
    val database = FirebaseDatabase.getInstance()
    val messageNode = database.getReference("message")

    messageNode.writeValue("Hello World")  // suspend function

    val message = messageNode.readValue(String::class.java) // suspend function

    assertEquals("Hello World", message)
}
```

There are other methods implemented, but I couldn't write tests for them yet. Also I'm not so familiar with coroutines yet.

**Comment by XinyueZ** [comment]
I think  an upgrade to this topic should be transferred to this now.

https://firebase.google.com/docs/firestore/data-model

**Comment by lucasvalenteds** [comment]
@elizarov I've written suspend functions to `Task` and `DatabaseReference` [here](https://github.com/lucasvalenteds/kotlinx.coroutines/tree/firebase-android/integration/kotlin-coroutines-firebase-android), but I don't know how to integrate the code with the existing Gradle build files of this project. Could you help with that?
