### ISSUE TITLE
Cancelled scopes can be reused

### ISSUE THREAD

**Issue by ZakTaccardi** [Kotlin/kotlinx.coroutines#621]
It's a bit odd that cancelled scopes can be reused.

### Example
```
val scope = CoroutineScope(Dispatchers.Unconfined + Job())

scope.launch { println("hello!") }

scope.coroutineContext[Job]!!.cancel()

// I expect this not to print, because the scope has been cancelled
scope.launch { println("goodbye!") }
```

### Expected

```
hello!
```

### Actual

```
hello!
goodbye!
```

EDIT: It seems the issue is that before launching a coroutine, the launch does not check if the scope has been cancelled or not:

### yield example
```
val scope = CoroutineScope(Dispatchers.Unconfined + Job())

scope.launch { println("hello!") }

scope.coroutineContext[Job]!!.cancel()

scope.launch {
    yield()
    println("goodbye!")
}
```
### result
```
hello!
```

Is this intentional?

**Comment by elizarov** [comment]
This happens because you are using `Dispatchers.Unconfined`. Please, don't use `Dispatchers.Unconfined` it may result is other weird and unexplicable behaviors, beyond the one you had demonstrated.

**Comment by elizarov** [comment]
This is not intentional, though. Just a side-effect. We might be able to fix it.
