### ISSUE TITLE
Add sendAll to produce

### ISSUE THREAD

**Issue by clarcharr** [Kotlin/kotlinx.coroutines#643]
Because `generateSequence` supports `yieldAll`, it would be nice if `produce` supported `sendAll`. This should accept `Iterable`s, `Sequences`, and `ReceiveChannel`s.

**Comment by qwwdfsad** [comment]
`yieldAll` can be optimized for `generateSequence`, while it's not so easy (and rewarding) for arbitrary channel.

Why `for (i in iterable) send(i)` is not applicable for you?
