### ISSUE TITLE
Make Dokka task independent on accessibility of external API

### ISSUE THREAD

**Issue by qwwdfsad** [Kotlin/kotlinx.coroutines#648]
We need to write a small tool(?) that fetches all external `package-list` files for the documentation we link to and store it somewhere so that they are committed to our repo. Dokka configuration, in turn, shall point to those local file, so that build is independent from availability of 3rd party documentation servers.

**Comment by elizarov** [comment]
We still need to write it. Currently, when building documentation with `gradlew dokka` (which is also required for `knit` and for making a release), external dependencies package lists are fetched from internet and when any of those site is not responsive you cannot build docs, thus cannot make release.
