### ISSUE TITLE
Coroutine freeze UI

### ISSUE THREAD

**Issue by halimpuckjava** [Kotlin/kotlinx.coroutines#649]
hi

i have an issue with coroutine and ui context, this my sample code

GlobalScope.launch(Dispatchers.JavaFx) {
            waitDialog.show()
            setupDetailsSubvensionView()

            val flux = async(Dispatchers.IO) {
                createFluxSubvension()
            }

            flux.await().doOnComplete { waitDialog.close(); println("flux complete.") }
                    .subscribe { updateTableUI(it) }
}

so my waitDialog (spinner in waitDialog is block) & updateTableUI(it) still freeze until flux complete 
subscription task 

so whats wrong ?? how to fix that ??

**Comment by jcornaz** [comment]
`subscribe` is blocking here. Not the coroutines.

You probably want to use [kotlinx-coroutines-reactor](https://github.com/Kotlin/kotlinx.coroutines/blob/master/reactive/kotlinx-coroutines-reactor/README.md) and do something like this:
```kotlin
GlobalScope.launch(Dispatchers.JavaFx) {
	waitDialog.show()
	setupDetailsSubvensionView()

	val result = createFluxSubvension()
                                .subscribeOn(Schedulers.elastic())
                                .awaitFirst() // Here awaitFirst will suspend instead of blocking
	
	waitDialog.close()
	println("flux complete.")
	
	updateTableUI(result)
}
```

Also note that the following won't have have the desired effect:

``` 
val flux = async(Dispatchers.IO) {
            createFluxSubvension()
        }
```

This means the "call of `createFluxSubvension`" is done on IO. But `createFluxSubvension` only build a flux stream right? What you care about is the fact that the actual data will be published from IO.

**Comment by halimpuckjava** [comment]
thanks

for now i just want to use it with coroutine-core only, how to organise my code ??

**Comment by jcornaz** [comment]
>does mean : createFluxSubvension() apply in IO context also flux in create in IO context

It only means the call of `createFluxSubvension` will be done on `IO`. But it has no impact on where the *work* will be done. And that's what you care about: the work behind that function.

>  in witch context flux in created

If `subscribeOn` is used, the actual work will be done on scheduler given to it. Otherwise it will be done on the thread calling `subscribe` (which is why it was blocking in your example)

>how to separate flux creation (also apply of createFluxSubvesnion()) from UI context

Using flux you have to use the operators `subscribeOn` and `observeOn`.

That being said, when using ` kotlinx-coroutines-reactor`, you can pass a coroutine context to the publisher when created with [flux](https://kotlin.github.io/kotlinx.coroutines/kotlinx-coroutines-reactor/kotlinx.coroutines.experimental.reactor/kotlinx.coroutines.experimental.-coroutine-scope/flux.html). And the body of `consumeEach` (which is `inline`) execute the lambda in the context of its caller.

**Comment by halimpuckjava** [comment]
thanks

its possible to give a version of code to fix that with coroutine ??

**Comment by jcornaz** [comment]
> its possible to give a version of code to fix that with coroutine ??

I'm not sure to understand. I gave a working solution with coroutine in my first answer:

```kotlin
launch { // no need to give dispatcher nor to use GlobalScope if your view component implements `CoroutineScope`

  waitDialog.show()
  setupDetailsSubvensionView()

  createFluxSubvension()
      .subscribeOn(Schedulers.elastic())
      .consumeEach { updateTableUI(it) }

  waitDialog.close()
  println("flux complete.")
}
```

Or maybe you asked how to write `Flux<T>.consumeEach` ?

```kotiln
fun <T> Flux<T>.openSubscription(): ReceiveChannel<T> =
    GlobalScope.produce {
      val completion = CompletableDeferred<Unit>()

      // subscribe may block or not, depending of the presence of `subscribeOn` in the upstream
      subscribe(
          { sendBlocking(it) }, // consumer
          { completion.cancel(it) }, // on error
          { completion.complete(Unit) } // on complete
      )

      completion.await() // Suspend until completion or error (throw the error in this case, which will go downstream)
    }

suspend inline fun <T> Flux<T>.consumeEach(action: (T) -> Unit) =
    openSubscription().consumeEach(action)
```

Or you were asking for a solution using *only* coroutines and not Flux?

```kotlin
fun openSubvensionSusbcription(): ReceiveChannel<Item> = GlobalScope.produce(Dispatchers.IO) {
  // Here we are on IO. Elements can be sent downstream with `send`
}

fun handleAction() {
  launch {
    waitDialog.show()
    setupDetailsSubvensionView()

    openSubvensionSusbcription()
        .consumeEach { updateTableUI(it) }

    waitDialog.close()
    println("flux complete.")
  }
}
```

**Comment by halimpuckjava** [comment]
thanks
