### ISSUE TITLE
Android app with coroutines 0.30.1-eap13 crashes in runtime

### ISSUE THREAD

**Issue by trashkalmar** [Kotlin/kotlinx.coroutines#657]
```
java.lang.IllegalStateException: Module with Main dispatcher is missing. Add dependency with required Main dispatcher, e.g. 'kotlinx-coroutines-android'
        at kotlinx.coroutines.Dispatchers.getMain(Dispatchers.kt:61)
```
`kotlinx-coroutines-android` is obviously added.
Version 0.30.0-eap13 works fine.

**Comment by qwwdfsad** [comment]
Could you please provide a self-contained example? Or check why `loadMainDispatcher` loads nothing?

**Comment by trashkalmar** [comment]
> Could you please provide a self-contained example?
It is enough to start any coroutine in UI context. For example:
`GlobalScope.launch(Dispatchers.Main) { ... }`

> Or check why `loadMainDispatcher` loads nothing?
`ServiceLoader` is unable to load `MainDispatcherFactory` class.

**Comment by qwwdfsad** [comment]
>It is enough to start any coroutine in UI context.

I did it in sample Android project and it works in both debug and release mode.

>ServiceLoader is unable to load MainDispatcherFactory.

Again, works on my machine.

Please be cooperative. I'm willing to help you, but I can't do anything with reports like "it doesn't work"

**Comment by trashkalmar** [comment]
It was my fault. I've excluded some Kotlin meta files from APK (specifically, Meta-inf/services/**). It was safe for previous coroutines version, but for 0.30.1 it became destructive.
Sorry that wasted your time.

**Comment by trashkalmar** [comment]
If an app is obfustacted with default proguard settings, it crashes in runtime. Here is sample project to reproduce an issue: https://www.dropbox.com/s/eay696h9qmxjl5e/sample.zip?dl=1
Also, I've created PR #662 to fix this problem.

**Comment by kimcy929** [comment]
I had this bug when exported file apk when using proguard with the version 0.30.2.

**Comment by petitJAM** [comment]
Those proguard rules didn't work for me, so I used this:
```
-keepnames class kotlinx.** { *; }
```
Definitely not a great solution since it tell proguard to keep everything, but it works.

**Comment by bernaferrari** [comment]
Same issue here with 0.30.2.

**Comment by jvlad** [comment]
The same issue with `0.30.1` in release build only (i. e. when `minifyEnabled true` is specified)

Android Studio 3.1.2
Build #AI-173.4720617, built on April 14, 2018
JRE: 1.8.0_152-release-1024-b01 x86_64
JVM: OpenJDK 64-Bit Server VM by JetBrains s.r.o
Mac OS X 10.13.4

Didn't work:  
```
-keepnames class kotlinx.coroutines.CoroutineExceptionHandler {}
-keepnames class kotlinx.coroutines.internal.MainDispatcherFactory {}
```

Worked:  
```
`-keepnames class kotlinx.** { *; }`
```

**Comment by qwwdfsad** [comment]
Thank you @trashkalmar for the sample project.
Jettifier seems to have an issue with `ServiceLoader` and name mangling.

I have (ugly as hell) fix which first tries to lookup main dispatcher in service loader and then invokes `Class.forName("...")`. It will be fixed in 1.0.0-RC

**Comment by bernaferrari** [comment]
This happens to me even without jetfier. Just proguard on its enough.

**Comment by AAverin** [comment]
It would be great if kotlinx.coroutines library could include proguard rules as part of distribution

**Comment by AAverin** [comment]
@bernaferrari then they need to be updated to
```
-keepnames class kotlinx.** { *; }
```
for kotlinx-coroutines-android

**Comment by JakeWharton** [comment]
Why?

**Comment by raiytu4** [comment]
I have the same issue with 0.30.2

I also get default rule at 
https://github.com/Kotlin/kotlinx.coroutines/blob/master/core/kotlinx-coroutines-core/resources/META-INF/proguard/coroutines.pro

Got the same message @trashkalmar 

`-keepnames class kotlinx.** { *; }` did work though

**Comment by dtunctuncer** [comment]
I still have error even though I used suggested ProGuard rules

**Comment by endru-kargo** [comment]
In our case, we put `signingConfigs` in the gradle file, then use the `Generate Signed Bundle / APK` to create the bundle. :D
Removing the `signingConfigs` solves the problem.

**Comment by Panajev** [comment]
@djrsousa thanks for spelling out the issue so well. Wished I had seen it before spending extra time researching the issue, but it was a good experience nonetheless.
Your suggestions, or moving to letting your build.gradle specify how to sign the app in debug and release modes, work, but if people still want to follow their current re-signing flow, they could delete only few files in the META-INF folder instead of all the files:
```
zip -d "$apkInputFullPath" META-INF/\*.RSA
zip -d "$apkInputFullPath" META-INF/\*.SF
zip -d "$apkInputFullPath" META-INF/\*.MF
```
Unless I am missing something, this should do the trick and be a very minimal change to the script people might be already running. Those files are the only ones that get added / modified when the signing occurs from what we could see.
