### ISSUE TITLE
Need Instructions For Using Gradle Kotlin Plugin

### ISSUE THREAD

**Issue by russel** [Kotlin/kotlinx.coroutines#673]
The README gives instructions for using Gradle but with the Groovy script,need to add what to do for when using the Gradle Kotlin plugin to write the build script in Kotlin.

**Comment by elizarov** [comment]
Good catch. PRs are welcome.

**Comment by russel** [comment]
My worry is that my hack is not a good bit of Kotlin code for a Gradle script, so I am not sure I have the backing to make a PR, yet. If there was someone from the Gradle Kotlin Plugin group who could advise that would help.
