### ISSUE TITLE
Mutex deadlock

### ISSUE THREAD

**Issue by Khang-NT** [Kotlin/kotlinx.coroutines#676]
```kotlin
    @Test
    fun testMutex() = runBlocking<Unit> {
        withTimeout(5000) {
            method1() // never complete
        }
    }

    private suspend fun method1() {
        mutex.withLock {
            println("Method 1 start")
            method2()
            println("Method 1 end")
        }
    }

    private suspend fun method2() {
        mutex.withLock {
            println("Method 2 body")
        }
    }
```
From beginning, I thought it was working like `synchronized(lock) {}`.

**Comment by fvasco** [comment]
> From beginning, I thought it was working like synchronized(lock) {}.

No, it works as documented:

> Mutex has two states: _locked_ and _unlocked_. It is **non-reentrant**, that is invoking lock even from the same thread/coroutine that currently holds the lock still suspends the invoker.

https://kotlin.github.io/kotlinx.coroutines/kotlinx-coroutines-core/kotlinx.coroutines.experimental.sync/-mutex/index.html

**Comment by qwwdfsad** [comment]
Thanks, @fvasco
