### ISSUE TITLE
Children factories as extensions on CoroutineScope

### ISSUE THREAD

**Issue by qwwdfsad** [Kotlin/kotlinx.coroutines#688]
The current approach to structured concurrency forces to write a lot of boilerplate while building scoped hierarchies such as `val job = Job(corotineContext[Job])`.

We should provide a more friendly way to create nested entities:
```
fun CoroutineScope.childJob(): Job
fun CoroutineScope.childSupervisorJob(): SupervisorJob
fun CoroutineScope.childCompletableJob(): CompletableJob
fun CoroutineScope.childScope(): CoroutineScope
```

Also, we could (should?) assert that scope has a `Job` and maybe provide a way to extract dispatcher from the scope.

**Comment by fvasco** [comment]
I want to propose again a previous consideration about the scope (3 in https://github.com/Kotlin/kotlinx.coroutines/issues/410#issuecomment-400662366)

Is it possible to reconsider `CoroutineScope` in favour to `Job`?
`Job` interface can extend `CoroutineScope`, so `launch`, `produce` and the above functions can become as extension of `Job`, and we do not have to assert nothing about `CoroutineScope`.

Moreover the `GlobalScope` can be easily replaced by a wild `Job` (`Job().launch { ... }`).

Finally `CoroutineScope` does not add more than the core function [coroutineContext](http://kotlinlang.org/api/latest/jvm/stdlib/kotlin.coroutines/coroutine-context.html), probably not so usefull.

**Comment by fvasco** [comment]
@qwwdfsad thank for your patience.

`Job`s and `Dispatcher`s are both really important for this library.
For `Dispatcher` was defined a good default, `Job` gets only a workaroud (https://github.com/Kotlin/kotlinx.coroutines/commit/5c44afb6ae2ab8cfb89174bccac226b1229c4b23).

Some library method requires a `Job` in the context to work property, like `CoroutineContext.cancel()`

In my opinion `CoroutineScope` _should_ own a `Job`, always.
Without a `job` there is no way to `cancel` a `CoroutineScope`.

It is possible to reconsider [coroutineJob](https://github.com/Kotlin/kotlinx.coroutines/issues/671#issuecomment-427829598) property.

**Comment by elizarov** [comment]
@qwwdfsad We should think twice before adding those (take a look and actual use-cases again), because those extensions are dangerous, see:

```
launch {
    childJob() // ops... lost a reference to it...
}
```

Now my parent job never completes and how am I supposed to debug that in the large piece of code?

**Comment by elizarov** [comment]
@fvasco `CoroutineScope` is an interface with an _intention_ that it always has a `Job`, but we have limited capacity to actually _guarantee_ that it had a job when you implement it _yourself_. However, all the `CoroutineScope` implementations that we provide in `kotlinx.coroutines` always have a `Job`.

**Comment by fvasco** [comment]
Nice @elizarov 

>  we have limited capacity to actually guarantee that it had a job when you implement it yourself

There is no rules about it in the official documentation, you should mention this intention.

Moreover it will possible to define:

```kotlin
val CoroutineScope.coroutineJob : Job get() = checkNotNull(coroutineContext[Job]) { "No Job founds in this coroutine scope"}
```

So we can consider to deprecate:

```kotlin
val CoroutineContext.isActive
fun CoroutineContext.cancel*
```

Because it is not possible to assume any `Job` in a `CoroutineContext`, furthermore this functions are already provided by `coroutineJob`.

**Comment by qwwdfsad** [comment]
Decided not to implement as too dangerous and error-prone
