### ISSUE TITLE
Handle exception only once in case of Job in the coroutines hierarchy

### ISSUE THREAD

**Issue by qwwdfsad** [Kotlin/kotlinx.coroutines#689]
Current exception handling mechanism can report the same exception multiple times.

For example, the exception is reported by every child if their parent can't handle it:
```
val job = Job()
launch(job) {
    delay(Long.MAX_VALUE)
}

launch(job) {
    throw IOException()
}
job.join()
```

`IOException` will be reported twice, though only the second coroutine is responsible for it.

Second problem is even less intuitive: when attaching to already failed job, exception *always* will be reported. This is the case from #686.

**Comment by qwwdfsad** [comment]
More examples:
```
 CoroutineScope(Job()).launch {
            val job = Job(coroutineContext[Job])
            launch(job) {
                println("A")
                throw Exception()
            }
        }
```

**Comment by Mygod** [comment]
From my crashlytics, it seems like something like this still happens in 1.3.0-RC...

**Comment by qwwdfsad** [comment]
What exactly? The same exception is handled twice?

**Comment by Mygod** [comment]
Never mind. It seems to be an error on my end.
