### ISSUE TITLE
android: Add interface MainThreadScope that simplifies CoroutineScope implementation

### ISSUE THREAD

**Issue by cypressious** [Kotlin/kotlinx.coroutines#694]
Consider adding an interface

```kotlin
interface MainThreadScope : CoroutineScope {
    val job: Job

    override val coroutineContext: CoroutineContext
        get() = Dispatchers.Main + job
}
```

that simplifies the implementation of `CoroutineScope`.

If this is considered useful, I would be glad to create a PR.

**Comment by fvasco** [comment]
Consider to use an helper class

```kotlin
class CoroutineScopeHelper(dispatcher: CoroutineDispatcher = Dispatchers.Default, job: Job = Job()) : CoroutineScope {
    override val coroutineContext: CoroutineContext = dispatcher + job
}

class MyCode : CoroutineScope by CoroutineScopeHelper(Dispatchers.Main) {

    fun cancel() {
        coroutineContext.cancel()
    }
}

```

**Comment by elizarov** [comment]
You can already simplify its implementation in the following way:

```
class MyClass : CoroutineScope {
    override val coroutineContext: CoroutineContext = Dispatchers.Main + Job()
}
```

Then, whenever you need to cancel a job, just use `coroutineContext.cancel()`. Does it help? Do we need to introduce any extra abstraction to ... ? It is already just one line.

**Comment by qwwdfsad** [comment]
I've ended up with a more elegant proposal, so I am closing this one.
See #829
