### ISSUE TITLE
yieldAll and recursive generators

### ISSUE THREAD

**Issue by ilya-g** [Kotlin/kotlinx.coroutines#7]
Investigate whether it's possible to implement efficient tail-recursive generators with `yieldAll` suspension function and the nested iterators technique, described here: https://www.microsoft.com/en-us/research/wp-content/uploads/2016/02/specsharp-iterators.pdf

```
fun fromTo(from: Int, to: Int) = generate {
    if (from > to) return
    yield(from)
    yieldAll(fromTo(from + 1, to))
}
```

**Comment by h0tk3y** [comment]
I'm currently investigating this. As to the tail-recursive generators, seems like we can only achieve that using `handleResult()`, which requires a coroutine to return the tail sequence:
```
fun fromTo(from: Int, to: Int) = generateWithTail f@{
    if (from > to) return@f emptySequence()
    yield(from)
    return@f fromTo(from + 1, to)
}
```
As far as I understand, there's no other way to learn whether a nested iterator is the last one yielded in the block, is there? Probably we could use some coroutine metadata here, something that will indicate that a continuation is actually a NOP that will immediately finish the coroutine block. Or is there already a way to learn that?

**Comment by elizarov** [comment]
`buildSequence` is not a part of stdlib with both `yield` and `yieldAll` support provided out-of-the-box.

**Comment by ilya-g** [comment]
Note that the mentioned nested iterator optimization is not implemented.

**Comment by elizarov** [comment]
It actually _is_ available with suspending functions in _even nicer way_:

```
suspend tailrec fun SequenceBuilder.fromTo(from: Int, to: Int) {
    if (from > to) return
    yield(from)
    fromTo(from + 1, to)
}

then do `buildSequence { fromTo(1, 1000) }`
