### ISSUE TITLE
Accept `Duration` for delay

### ISSUE THREAD

**Issue by clarcharr** [Kotlin/kotlinx.coroutines#705]
At least on the JVM, it would be nice to be able to pass `java.time.Duration` to this method. To me, `delay(Duration.ofSeconds(2))` is a lot clearer than `delay(2000)`.

**Comment by elizarov** [comment]
Add `kotlinx-coroutines-jdk8` dependency, there is a corresponding function: https://kotlin.github.io/kotlinx.coroutines/kotlinx-coroutines-jdk8/kotlinx.coroutines.experimental.time/delay.html
