### ISSUE TITLE
some problem when i use it

### ISSUE THREAD

**Issue by skyshenfu** [Kotlin/kotlinx.coroutines#71]
I just copy some code to my Idea and my kotlin version is 1.1.2  and kotlinx.coroutines version is 0.16.0  
code is:
fun main(args: Array<String>) = runBlocking<Unit> {
    launch(CommonPool) {
        repeat(1000) { i ->
            println("I'm sleeping $i ...")
            delay(500)
        }
    }
    delay(1300) // just quit after delay
}

---

error is:
Exception in thread "ForkJoinPool.commonPool-worker-1" java.lang.NoSuchMethodError: kotlinx.coroutines.experimental.DelayKt.delay$default(JLjava/util/concurrent/TimeUnit;ILjava/lang/Object;)

**Comment by elizarov** [comment]
How do you configure/build your project? Can you share it?

**Comment by skyshenfu** [comment]
[here is the error project](https://github.com/skyshenfu/erroprroject)

**Comment by elizarov** [comment]
That is what I did.
1. `git clone https://github.com/skyshenfu/erroprroject.git`
2. Launch IDEA, click Open -> natigate to `pom.xml`, open it, select "Open as project"
3. Wait while Maven projects is imported.
4. Navigate to `main.kt`, click on kotlin logo to start `main` function.
It all works for me.
The most likely cause is that you have some project synching your Maven project to IDEA or some firewall blocks download of `kotlinx.coroutines`. You can try `mvn compile` from the command line to check.
