### ISSUE TITLE
currentScope deprecation / UI best practices

### ISSUE THREAD

**Issue by mateherber** [Kotlin/kotlinx.coroutines#710]
The currentScope builder has been deprecated however [UI guide](https://github.com/Kotlin/kotlinx.coroutines/blob/master/ui/coroutines-guide-ui.md) still lists it as a way to propagate Activity's scope to its presenter.

![image](https://user-images.githubusercontent.com/13942888/47012821-83dc4680-d145-11e8-898d-43504b431778.png)

What is the suggested way as of today? Make the presenter implement CoroutineScope in every case or using coroutineScope builder or something else?

**Comment by qwwdfsad** [comment]
I'll update docs.

Suggested solutions are:
1) Implement a `CoroutineScope` 
2) Have a coroutine scope in a parameter/field (e.g. `uiScope`)
3) Use `coroutineScope` builder
