### ISSUE TITLE
Job.cancel() should not return a Boolean, but Unit

### ISSUE THREAD

**Issue by elizarov** [Kotlin/kotlinx.coroutines#713]
Currently, `Job.cancel()` result documentation is inconsistent with the actual return value for `Job()` instances. Moreover, it is unclear how boolean result of `Job.cancel()` could be used, that is, we don't see any compelling use-case on the use of that boolean value that could guide the logic that this boolean value shall have. So, the proposal is change `Job.cancel()` so that it returns `Unit`.

**Comment by Dico200** [comment]
Is this something you might consider to change before 1.0 release?

**Comment by elizarov** [comment]
Likely, yes.
