### ISSUE TITLE
Is there any way to reuse Channel while using ReceiveChannel's extensions?

### ISSUE THREAD

**Issue by jeiea** [Kotlin/kotlinx.coroutines#722]
With the following code,

```
val ss = GlobalScope.produce {
  repeat(100) { i ->
    println(i)
    send(i)
  }
}
println(ss.take(3).toList())
delay(100)
println(ss.take(3).toList())

// results
0
1
2
[0, 1, 2]
3
[]
```

I want to make the second println print [3, 4, 5], but I couldn't find easy way to do it. Should I use `receive()` manually to achieve it?

**Comment by elizarov** [comment]
Yes. You should use `receive` manually. All the combinators defined on `ReceiveChannel` currently _consume_ it fully (cancel the remainder).
