### ISSUE TITLE
Potential issues with CoroutineScope and runBlocking semantics

### ISSUE THREAD

**Issue by Dico200** [Kotlin/kotlinx.coroutines#723]
`runBlocking` is different from other coroutine builders because it is not an extension of `CoroutineScope`.
If there is an outer scope, programmer might mean to carry over elements from its context. It does not do this unless you explicitly pass the context as a parameter.

## Example 1

Here's an example where it leads to confusion:
```kotlin
class App : CoroutineScope {
    override val coroutineContext = Job() + Dispatchers.Main
    fun dispose() = coroutineContext.cancel()
    
    fun specialFunction() {
        runBlocking { 
            launch {
                // programmer intends to wait for this coroutine, which should run on Main thread, to complete.
                // Uses runBlocking instead of suspend function.
                // But launch does not use outer scope, because runBlocking doesn't do so and overrides it with its own.
            }.join()
        }
    }
}
```

`launch` call in `specialFunction` must be replaced with `this@App.launch` to fix the issue.

Idiomatic code would be to use `suspend` function, 
and if that's not permissible, the programmer should probably do this:
```kotlin
fun specialFunction() {
    val job = launch {
        // coroutine runs in main thread as expected
    }

    runBlocking {
        job.join()
    }
}
```

## Example 2
Assume the programmer has a good reason to carry over the outer context into the `runBlocking` call.
For example:

```kotlin
class App : CoroutineScope {
    override val coroutineContext = Job() + newSingleThreadContext("MyMainThread")
    fun dispose() = coroutineContext.cancel()
    
    fun specialFunction() {
        launch { 
            runBlocking(coroutineContext) {
                println("Hello from runBlocking")
            }
        }
    }
}

suspend fun main() {
    with(App()) {
        specialFunction()
        coroutineContext[Job]!!.join()
        dispose()
    }
}
```

Here, the programmer passed outer coroutine context as a parameter.
Now, the `runBlocking` coroutine will be cancelled when parent is cancelled.
However, this code will never return because there is a deadlock.
From the `runBlocking` documentation:
>  * When [CoroutineDispatcher] is explicitly specified in the [context], then the new coroutine runs in the context of
>  * the specified dispatcher while the current thread is blocked.

So what if the current thread is the same as the dispatcher's single thread? You get a deadlock.

I just wanted to share some difficulties I encountered around `runBlocking` and `CoroutineScope`. Sure, there are ways around these issues, but I think it is worth considering small changes to the behaviour of `runBlocking` here.

I think it *might* make sense to have a version of `runBlocking` that is an extension of `CoroutineScope`. That way, cases where there is an outer scope, we can have the logic for carrying over its context implemented inside the `runBlocking` function. The new version will be prioritized by the compiler when there is a `CoroutineScope`, and its context elements are copied as the programmer would expect. I wonder what your thoughts are. I struggle to find great use cases, but I think this edge case is relatively difficult to maneauver as a programmer at the moment.

**Comment by elizarov** [comment]
Can you please clarify what are the actual use-cases for the examples you've given? Why there might be a need to use `runBlocking` in the otherwise non-blocking code in the same class that implements `CoroutineScope`? 

The reason that `runBlocking` is not an extension of `CoroutineScope` is precisely that it is used to bridge the code that does not use coroutines at all with coroutines code.

**Comment by Dico200** [comment]
While a concrete use case is not present, I'm saying with example 1 that it can be difficult to get `runBlocking` usage right in a place where there is an outer `CoroutineScope`, which is then hidden. That can be confusing for programmers that don't know its precise use case and that have never run into the problem.
They might want to join a job they launch synchronously, example 1 shows a straight forward way of doing that with `runBlocking`.

If you think that's a total non-issue, that's okay. I wrote the issue for it to be considered and thought about before the api is final.

**Comment by elizarov** [comment]
I think that it, at least, deserved some kind of an inspection. Maybe we shall warn on any `runBlocking` usage inside classes that implement `CoroutineContext`, but we'll need more use-cases to study what is going on.

**Comment by qwwdfsad** [comment]
As Roman correctly mentioned, `runBlocking` is not an extension on the scope for a reason and it never will be.

`runBlocking` is a very fragile mechanism which is frequently misused. Maybe it is good to have an inspection for `runBlocking` calls  if scope receiver is present. But before doing so we should ensure that it won't produce too much false-positives for people who use it properly (e.g. in Android `onDestroy` methods to join the job)

**Comment by ZakTaccardi** [comment]
@qwwdfsad I would like to know more details on how this can safely be used. My particular use case is that I need a `CoroutineScope[Job]!!.invokeOnCompletion { .. }` to be executed before `onPause(..)` completes.

Is there a way to run a piece of code synchronously once the `CoroutineScope`'s `Job` is cancelled?

**Comment by Dico200** [comment]
@ZakTaccardi 
```
resumedScope?.let { 
    runBlocking {
        it[Job]!!.cancelAndJoin()
    }
}
```

**Comment by Dico200** [comment]
> @ZakTaccardi
> 
> ```
> resumedScope?.let { 
>     runBlocking {
>         it[Job]!!.cancelAndJoin()
>     }
> }
> ```
> EDIT: This may not work since onPause probably gets called on Main thread too. In that case this code will hang and there's no way to do it, unless you can invoke pending tasks from the Android event loop within the runBlocking call.

Actually, you can try this:
```
resumedScope?.let { s -> 
       s[Job]!!.cancel()
       runBlocking {
           withContext(Dispatchers.Main) {
               // This MIGHT not deadlock because the dispatchers use the same thread? 
               while (s.isAlive) {
                   yield() // invoke Android scheduler?
               }
            }
        }
    }
}
```
NO IDEA if this works.

**Comment by elizarov** [comment]
> I would like to know more details on how this can safely be used. My particular use case is that I need a `CoroutineScope[Job]!!.invokeOnCompletion { .. }` to be executed before `onPause(..)` completes.

`cancel` is guaranteed to synchronously execute all `invokeOnCompletion` handlers, so in your code examples there is a guaranteed that it executed before `onPause` returns. These handlers are explicitly designed to be synchronous: 
https://kotlin.github.io/kotlinx.coroutines/kotlinx-coroutines-core/kotlinx.coroutines/-job/invoke-on-completion.html

**Comment by Dico200** [comment]
I realize that I was an idiot. Completion handlers are not dispatched of course.

> Does it help? Can we close this issue?
@elizarov As far as I'm concerned, the thing you replied to is not directly related to the issue. You said you might consider an IDE inspection to check for correct use of `runBlocking`, but it might be complex to filter false positives there. I am happy to close it here, and you can reopen it if you want to pursue that idea. Sorry for leaving it open all this time :)

**Comment by ZakTaccardi** [comment]
@elizarov I think part of the issue I was having was that the job I was registering a `CompletionHandler` for was the child job of a `CoroutineScope`, not the parent scope's job (the one that has `.cancel()` called on it in `onPause()`. Maybe that caused the cancellation to be dispached? I'm not sure how structured concurrency cancellation plays out for child jobs that get cancelled
