### ISSUE TITLE
HandlerContext is deprecated, but ReplaceWith points to HandlerDispatcher private constructor

### ISSUE THREAD

**Issue by LouisCAD** [Kotlin/kotlinx.coroutines#729]
Was it a mistake? I have a use case for it: Android Camera2 API, as I'm working again on https://github.com/Beepiz/CameraCoroutines

Camera2 API requires a `Handler` in multiple areas, and I'd like to reuse the backing `HandlerThread` (Main thread is not suitable because it causes frame drops).

**Comment by elizarov** [comment]
Sorry, that wrong pointer in KDoc. Use `Handler.asCoroutineDispatcher(...)` extension to convert `Handler` to dispatcher. Does it work for you or you need something else?

**Comment by LouisCAD** [comment]
I'd expect no misleading ReplaceWith, but your solution works for me,
thanks!
