### ISSUE TITLE
Introduce API to inject main dispatcher

### ISSUE THREAD

**Issue by qwwdfsad** [Kotlin/kotlinx.coroutines#746]
Otherwise, Android users should **inject** main dispatcher into their classes to use `Unconfined` in tests. This is pretty ugly, especially when `Dispatchers.Main` is already here.

Proposed solution:
Introduce module `kotlinx-coroutines-core-test` which overrides `Main` dispatcher and API to inject any dispatcher as `Main`.

So users can use `launch(Dispatchers.Main)` and in tests all they need is to add a dependency to `kotlinx-coroutines-core-test` and use `MainDispatcherInjector.inject(dispatcher: CoroutineDispatcher)`.

**Comment by pull-vert** [comment]
I think providing a separate module 'kotlinx-coroutines-core-test'' is really important, to provide Coroutines users a dedicated module with some useful testing tools such as TestBase or TestCoroutineContext (this last one provides useful delay testing features, but will need some changes, also it shouldn't be in 'kotlinx-coroutines-core').

**Comment by qwwdfsad** [comment]
Yes, that's the plan. The plan is to provide more testing utilities (sequential execution validation, virtual time, debug capabilities etc.)

**Comment by BoxResin** [comment]
This feature is really needed!
