### ISSUE TITLE
CoroutineScope "context" shadows Android context

### ISSUE THREAD

**Issue by mttmllns** [Kotlin/kotlinx.coroutines#75]
In Android Activities, Fragments, and Views there is a `getContext()` method that is used frequently.  When used with Kotlin the IDE suggests using property access syntax with the synthetic property `context`.  This is shadowed when using an `async` or `launch` coroutine block, though, by the CoroutineContext `context` of CoroutineScope.

We can use `getContext()` instead and it's not the end of the world, but I wanted to file the issue to see if there should instead be an alternate name for the CoroutineContext.  I imagine many people will run into this "issue" whether writing code or reading other's code and getting confused by the two different "contexts".

Cheers.

**Comment by elizarov** [comment]
The tentative plan is to rename it `coroutineContext`. Stay tuned.

**Comment by elizarov** [comment]
Committed rename of `context` to `coroutineContext` into `develop` branch.

**Comment by elizarov** [comment]
Released in version 0.17
