### ISSUE TITLE
JDK8 & Guava future integration modules do not handle child exceptions properly

### ISSUE THREAD

**Issue by elizarov** [Kotlin/kotlinx.coroutines#751]
The following test demonstrates the problem:
```
    @Test
    fun testChildException() {
        val result = GlobalScope.future(Dispatchers.Unconfined) {
            // child crashes
            launch { throw TestException("FAIL") }
            // but only after parent completes successfully
            42
        }
        assertFailsWith<TestException> { result.get() } // Future should contain child exception
    }
```

**Comment by elizarov** [comment]
The code in both `CompletableFutureCoroutine` and `ListenableFutureCoroutine` handles completion too early -- in `resumeWith`. In fact it should handle completion only in `onComplete` and `onCompleteExceptionally`.

**Comment by elizarov** [comment]
We can mention this as know from problem in `1.0.0`.

**Comment by qwwdfsad** [comment]
One more bug: exception can be loss even without parallel decomposition if exception is racing with cancellation
