### ISSUE TITLE
java.lang.ClassNotFoundException: kotlin.coroutines.jvm.internal.CoroutineImpl

### ISSUE THREAD

**Issue by li-xiaojun** [Kotlin/kotlinx.coroutines#766]
my build.gradle:
```
buildscript {
    ext.kotlin_version = '1.3.0-rc-190'
    repositories {
        mavenCentral()
    }
    dependencies {
        classpath "org.jetbrains.kotlin:kotlin-gradle-plugin:$kotlin_version"
    }
}
apply plugin: "kotlin"
group 'com.lxj'
version '1.0-SNAPSHOT'

sourceCompatibility = 1.8

repositories {
    mavenCentral()
}
dependencies {
    implementation "org.jetbrains.kotlin:kotlin-stdlib-jdk8:${kotlin_version}"
    testCompile group: 'junit', name: 'junit', version: '4.12'
    implementation 'org.jetbrains.kotlinx:kotlinx-coroutines-core:1.0.0-RC1'
}
compileKotlin {
    kotlinOptions.jvmTarget = "1.8"
}
compileTestKotlin {
    kotlinOptions.jvmTarget = "1.8"
}
```

my code is:
```kotlin
fun main(args: Array<String>) {

    GlobalScope.launch{
        print("I am from coroutines")
    }
}

```

the console output:
```
Exception in thread "main" java.lang.NoClassDefFoundError: kotlin/coroutines/jvm/internal/CoroutineImpl
	at java.lang.ClassLoader.defineClass1(Native Method)
	at java.lang.ClassLoader.defineClass(ClassLoader.java:763)
	at java.security.SecureClassLoader.defineClass(SecureClassLoader.java:142)
	at java.net.URLClassLoader.defineClass(URLClassLoader.java:467)
	at java.net.URLClassLoader.access$100(URLClassLoader.java:73)
	at java.net.URLClassLoader$1.run(URLClassLoader.java:368)
	at java.net.URLClassLoader$1.run(URLClassLoader.java:362)
	at java.security.AccessController.doPrivileged(Native Method)
	at java.net.URLClassLoader.findClass(URLClassLoader.java:361)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:424)
	at sun.misc.Launcher$AppClassLoader.loadClass(Launcher.java:349)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:357)
	at start.AKt.main(a.kt:13)
Caused by: java.lang.ClassNotFoundException: kotlin.coroutines.jvm.internal.CoroutineImpl
	at java.net.URLClassLoader.findClass(URLClassLoader.java:381)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:424)
	at sun.misc.Launcher$AppClassLoader.loadClass(Launcher.java:349)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:357)
	... 13 more
```

**Comment by qwwdfsad** [comment]
Is it still a problem with corouines 1.0.0 and Kotlin 1.3?

**Comment by EvilBT** [comment]
@qwwdfsad yes.

**Comment by qwwdfsad** [comment]
Could you please provide a sample project which reproduces the problem?

I've created a project with the same `build.gradle` (but with version 1.3 and 1.0.0) and it works properly

**Comment by tustar** [comment]
Same issue
`import kotlinx.coroutines.GlobalScope
import kotlinx.coroutines.launch


fun main(args: Array<String>)  {
    GlobalScope.launch { // launch new coroutine in background and continue
//        delay(1000L) // non-blocking delay for 1 second (default time unit is ms)
        println("World!") // print after delay
    }
    println("Hello,") // main thread continues while coroutine is delayed
    Thread.sleep(2000L) // block main thread for 2 seconds to keep JVM alive
}`

**Comment by li-xiaojun** [comment]
it works after I update IDEA kotlin plugin to 1.3 and restart IDEA，before the plugin version is 1.2.65.

**Comment by tustar** [comment]
@li-xiaojun , It works for me, thanks!

**Comment by Nadim96** [comment]
Updating kotlin to 1.3 and restarting gave me another error (using the quickstart code on https://ktor.io/quickstart/index.html).

adding 

`implementation 'org.jetbrains.kotlinx:kotlinx-coroutines-core:1.0.0-RC1'`
to 
```
dependencies {
}
```
fixed it for me

**Comment by dtschmidt** [comment]
@Nadim96 that fixed it for me as well! I should have thought of that but I'm so glad to have found your comment. Thank you!

**Comment by kid1412621** [comment]
got this error when using spring webflux corouter (added `implementation("org.jetbrains.kotlinx:kotlinx-coroutines-core:1.3.2")`
in gradle)

**Comment by idoflax** [comment]
I'm experiencing the same and it's not being fixed with adding `implementation("org.jetbrains.kotlinx:kotlinx-coroutines-core:1.3.2").` I'm getting the error while executing a jar built by gradle, not when running the program in IntelliJ. I'm not using spring or any framework.
It seems that the Continuation interface appears twice, once in kotlin-stdlib
![Screenshot 2020-08-24 at 13 03 54](https://user-images.githubusercontent.com/10278950/91038245-c1943b00-e60a-11ea-97d9-ee07fad9853d.png)

and once in kotlin-stdlib-common
![Screenshot 2020-08-24 at 13 04 23](https://user-images.githubusercontent.com/10278950/91038282-cbb63980-e60a-11ea-9e63-81207ed65f5f.png)

both of which come from the same dependency
![Screenshot 2020-08-24 at 13 06 54](https://user-images.githubusercontent.com/10278950/91038304-d40e7480-e60a-11ea-8b9a-1bb78f26fa60.png)


Gradle:
```
plugins {
    id 'java'
    id 'org.jetbrains.kotlin.jvm' version '1.3.72'
}

group 'com.something'
version '1.0-SNAPSHOT'

repositories {
    mavenCentral()
}

ext {
    ktorVersion = '1.3.1'
}

dependencies {
    implementation group: 'org.jetbrains.kotlin', name: 'kotlin-stdlib-jdk8'
    implementation group: "io.ktor", name: "ktor-client-apache", version: "${ktorVersion}"
    implementation group: "io.ktor", name: "ktor-client-jackson", version: "${ktorVersion}"
    implementation group: "io.ktor", name: "ktor-client-auth-jvm", version: "${ktorVersion}"
    implementation group: 'com.fasterxml.jackson.module', name: 'jackson-module-kotlin'
    implementation group: 'io.github.microutils', name: 'kotlin-logging', version: '1.8.3'

    testImplementation group: 'org.junit.jupiter', name: 'junit-jupiter-api', version: '5.7.0-M1'
    testImplementation group: 'org.jetbrains.kotlin', name: 'kotlin-test-junit5', version: '1.3.72'
    testImplementation group: 'io.mockk', name: 'mockk', version: '1.10.0'
    testImplementation group: 'org.assertj', name: 'assertj-core', version: '3.16.1'
    testImplementation group: 'com.github.tomakehurst', name: 'wiremock', version: '2.26.0'

}

compileKotlin {
    kotlinOptions.jvmTarget = "1.8"
}
compileTestKotlin {
    kotlinOptions.jvmTarget = "1.8"
}

jar {
    manifest {
        attributes 'Main-Class':'com.something.normailzer.Normalizer'
    }

    from { configurations.compile.collect { it.isDirectory() ? it : zipTree(it) } }
}
```
