### ISSUE TITLE
Build error

### ISSUE THREAD

**Issue by IgorGanapolsky** [Kotlin/kotlinx.coroutines#768]
Hello,
when I try to build this repo in IntelliJ IDEA 2018.3 EAP (Community Edition)
Build #IC-183.3975.18, built on October 24, 2018
JRE: 1.8.0_152-release-1343-b12 x86_64
JVM: OpenJDK 64-Bit Server VM by JetBrains s.r.o
macOS 10.14.1, I get this error:
>Could not resolve all files for configuration ':kotlinx-coroutines-play-services:aar'.
         > Could not find play-services-basement.aar (com.google.android.gms:play-services-basement:15.0.1).
           Searched in the following locations:
               https://jcenter.bintray.com/com/google/android/gms/play-services-basement/15.0.1/play-services-basement-15.0.1.aar

Please advise

**Comment by qwwdfsad** [comment]
Please make sure you are building it with this commit: https://github.com/Kotlin/kotlinx.coroutines/commit/6f01c9344d77b71117b9880d5abbbdaaf5f18bc3

Google removed some of the transitive dependencies from jcenter, so now this workaround is required :(

**Comment by IgorGanapolsky** [comment]
That works, thanks!
