### ISSUE TITLE
Implement runBlocking on top of iOS event queue

### ISSUE THREAD

**Issue by qwwdfsad** [Kotlin/kotlinx.coroutines#770]
We can improve `runBlocking` on iOS by advancing current iOS event loop if our loop is empty.
It will allow using `runBlocking` from within the main thread for long-running tasks such as http requests.

https://github.com/bootstraponline/run_blocking/commit/a7953192c7078ab41dbf382f56bdc4432a46c84b#diff-c1a933ca71f0c706f65401b240f8c806

**Comment by LouisCAD** [comment]
Interesting to know this is possible!
This is getting me wondering if it should still be named `runBlocking` after this though. Or maybe this behavior should be available with a certain extra parameter, or in a method named differently?
