### ISSUE TITLE
ThreadContextElement failure breaks cancellation

### ISSUE THREAD

**Issue by cy6erGn0m** [Kotlin/kotlinx.coroutines#773]
An exception in `updateThreadContext` breaks job cancellation sequence so the following example hangs forever

```kotlin
package org.jetbrains.tests.cy.element.failure

import kotlinx.coroutines.*
import java.lang.IllegalStateException
import kotlin.coroutines.*

class MyElement : ThreadContextElement<Unit> {
    private object Key : CoroutineContext.Key<MyElement>

    override val key: CoroutineContext.Key<*> get() = Key

    override fun restoreThreadContext(context: CoroutineContext, oldState: Unit) {
    }

    override fun updateThreadContext(context: CoroutineContext) {
        throw IllegalStateException("Prevent a coroutine from starting right here for some reason")
    }
}

fun main() {
    runBlocking {
        GlobalScope.launch(MyElement()) {
            println("OK")
        }.join()
    }
}
```

I'd expect it to cancel job and resume `join` (since it is running not under `MyElement` so it is possible to resume it) however it remains `Active`

**Comment by qwwdfsad** [comment]
There is not much we can do.
We can't resume coroutine in a semi-updated context. If we can't resume it (and cancellation implies resume with exception), we can't complete it, so any `join` will hang.

All solutions may lead to unexpected behaviour:
1) Resuming job in a semi-updated context breaks the contract of `ThreadContextElement `
2) Transferring job to the final state breaks atomicity and cancellation contract
3) Catching and reporting exceptions in every context element and then resuming coroutine will effectively disable "restore" and may leave context element in an inconsistent state.
