### ISSUE TITLE
How to extend channel implementations post 0.27.0

### ISSUE THREAD

**Issue by matejdro** [Kotlin/kotlinx.coroutines#774]
So, with stable coroutines, all channel implementations (`LinkedListChannel`, `ConflateChannel` etc.) became internal and so they could break all the time.

What is the alternative if one wants to create implementation that extends one of those channels, but still needs access to an events such as `afterClose`?

Example use case is for RX wrapper and I have noticed that `rx2` integratition still extends `LinkedListChannel` under the hood: https://github.com/Kotlin/kotlinx.coroutines/blob/ea89e60f8287487edfa6fbc5e2d8cb4f963da260/reactive/kotlinx-coroutines-rx2/src/RxChannel.kt#L62

**Comment by qwwdfsad** [comment]
There is no way to extend channel implementation except copy-pasting them to your project.
We have hidden them exactly because we are going to change them in the future in unexpected ways, preserving only public API and its semantics, but not implementation details.

If you want to extend channel for some reason, it is better to elaborate why do you have to do that so we can discuss other solutions or alternatives.

**Comment by matejdro** [comment]
As I have already mentioned, I want to extend channel to receive `afterClose` events on channel, exactly the way `kotlinx-coroutines-rx2` uses them.

**Comment by qwwdfsad** [comment]
>So bundled integration libraries are only ones that can use these channels safely?

Yes, actual channel class is an implementation detail.

>As I have already mentioned, I want to extend channel to receive afterClose events on channel

Why [`invokeOnClose`](https://kotlin.github.io/kotlinx.coroutines/kotlinx-coroutines-core/kotlinx.coroutines.channels/-send-channel/invoke-on-close.html) is not suitable for you?

**Comment by matejdro** [comment]
I feel like an idiot now. I've gone through the API but did not find this method. Case closed, thanks for the help.

**Comment by qwwdfsad** [comment]
@matejdro it is okay, I'm happy to help.
We definitely should work on API discoverability, so if you have some ideas (e.g. spill `SendChannel` and `ReceiveChannel` to different files, update our guide etc.), feel free to discuss them.

**Comment by matejdro** [comment]
After migrating further, `invokeOnClose` seems to be experimental itself though in `1.0.0`. So it does not appear to be complete solution as I hoped it would (I still need to opt in into experimental features which I wanted to avoid).
