### ISSUE TITLE
Help migrating actors to v1.0

### ISSUE THREAD

**Issue by plokko** [Kotlin/kotlinx.coroutines#776]
Hi, i'm migrating coroutines from 0.27 to 1.0 but i'm having problems understanding how to migrate actors (deprecated).

The code i use is like this:
```kotlin

    private val processor: SendChannel<Downloadable> = actor<Downloadable>(capacity = Channel.UNLIMITED) {
        for (download in channel)
        {
         ///....
        }
      }
```

Thanks

**Comment by CodeZilla7** [comment]
You need to use the actor function available via a CoroutineScope

**Comment by plokko** [comment]
> You need to use the actor function available via a CoroutineScope

how? the actor is deprecated, please make an example
https://kotlin.github.io/kotlinx.coroutines/kotlinx-coroutines-core/kotlinx.coroutines.channels/actor.html

**Comment by qwwdfsad** [comment]
It is not deprecated, it is marked as obsolete.

>**corresponding declarations have serious known flaws and they will be redesigned in the future.**

Currently, we have no replacement, but just an intention to indicate that this API is not should not be exposed to your end-users.

Replacement will arrive either in 1.1.0 or 1.2.0

**Comment by plokko** [comment]
> It is not deprecated, it is marked as obsolete.
> 
> > **corresponding declarations have serious known flaws and they will be redesigned in the future.**
> 
> Currently, we have no replacement, but just an intention to indicate that this API is not should not be exposed to your end-users.
> 
> Replacement will arrive either in 1.1.0 or 1.2.0

Someone should do a migration guide to 1.0 by the way:
it's a matter of pre-pending GlobalScope to launch, actor, etc., changing namespace, replacing UI with Dispatchers.Main and other trivial modification but neither the 1.3 auto migration or Android studio autocomplete helps in this matter and i could not find anything online so i was stuck with trial and error.

**Comment by qwwdfsad** [comment]
>Someone should do a migration guide to 1.0 by the way

https://github.com/Kotlin/kotlinx.coroutines/blob/master/COMPATIBILITY.md#migration-to-100-version-with-kotlin-13

All removed API is still here in `0.30.2`, but is deprecated with a proper `ReplaceWith`.
So in order to migrate, one should first update to `0.30.2` or `0.30.2-eap13`, apply all quickfixes and then update to 1.0.0

**Comment by Rody66** [comment]
Still no stable replacement for actors?

**Comment by elizarov** [comment]
Sorry, not yet.

**Comment by Rody66** [comment]
Thank you, we will wait. Perhaps you can suggest us some of existing solution to make a controllable coroutines queue? We need this to consistently send requests to the server.

**Comment by qwwdfsad** [comment]
Unfortunately no, Flow is still the main priority for us.

**Comment by ondreju93** [comment]
> It is not deprecated, it is marked as obsolete.
> 
> > **corresponding declarations have serious known flaws and they will be redesigned in the future.**
> 
> Currently, we have no replacement, but just an intention to indicate that this API is not should not be exposed to your end-users.
> 
> Replacement will arrive either in 1.1.0 or 1.2.0

I would like to use kotlin actors on production.
Is it a bad idea?
What are the known flaws?

**Comment by rabolfazl** [comment]
> > It is not deprecated, it is marked as obsolete.
> > > **corresponding declarations have serious known flaws and they will be redesigned in the future.**
> > 
> > 
> > Currently, we have no replacement, but just an intention to indicate that this API is not should not be exposed to your end-users.
> > Replacement will arrive either in 1.1.0 or 1.2.0
> 
> I would like to use kotlin actors on production.
> Is it a bad idea?
> What are the known flaws?
> It's been more than a year since you guys last wrote there was no actor replacement, has anything changed?

I'm going to do exactly the same thing: using actors in production. Any news? :)
