### ISSUE TITLE
Allow indirect calls to suspendable methods

### ISSUE THREAD

**Issue by ufoscout** [Kotlin/kotlinx.coroutines#78]
The following code throws a compilation error because "suspendFunction()" is called from a non suspend method:
```
    suspend fun suspendFunction() {
        delay(1000)
    }

    fun notSuspendFunction() {
        suspendFunction()
    }

    @Test
    fun indirectSuspendCall() = runBlocking<Unit> {
        notSuspendFunction()
    }
```

However, indirectly, the notSuspendFunction() method is called into a runBlocking block so I would expect it to run without issues at runtime.
While I clearly understand why there is this check at compile time, this forces to transitively modify all the functions of your code to add the "suspend" annotation. In some situations this is not possible.
For example, imagine that suspendFunction() is in a DAO library and "notSuspendFunction()" is in a project that uses it, in this case you could provide a coroutine based alternative implementation for the DAO but it will break all the library consumers.

**Comment by cypressious** [comment]
While this issue probably for Youtrack, I'll answer here:

You can always do `runBlocking<Unit> {}` in your non-`suspend` functions to cross the boundry to the coroutines world.

**Comment by ufoscout** [comment]
@cypressious the workaround you propose is not the same, in fact, if I am not wrong, `runBlocking<Unit> {}` blocks the calling thread.
In addition, it uses a different context than of the one of the caller and it should be used only as top-level coroutine based on the [documentation](https://github.com/Kotlin/kotlinx.coroutines/blob/master/coroutines-guide.md#coroutine-basics):

> `runBlocking { ... }` works as an adaptor that is used here to start the top-level main coroutine. The regular code outside of runBlocking blocks, until the coroutine inside runBlocking is active.

**Comment by cypressious** [comment]
Yes, `runBlocking` blocks, as the name suggests. Alternatively, use `launch` to start a coroutine without waiting for it. In any way, you can't just call `suspend` functions from non-`suspend` functions because they are compiled completely different. That's just how coroutines work.

**Comment by elizarov** [comment]
It is not just the different compilation. Suspending and non-suspending functions are _conceptually_ different. `suspend` function _can_ suspend the execution, while regular functions _cannot_ do it _conceptually_. Think about it as a part of a function's type. For example, if your function is declared to return a `String` it cannot just go ahead and return an integer 32 instead. Similarly, if your function is declared with a guarantee that it never suspends (a regular function), it cannot just decide go ahead and decide suspend. That is so by design.
