### ISSUE TITLE
Documentation improvement about async.await cancelling outer scope

### ISSUE THREAD

**Issue by Tolriq** [Kotlin/kotlinx.coroutines#787]
After a discussion on slack I discovered that fact (async.await cancelling outer scope) and could not find a proper explanation / really visible point in the current documentation.

https://github.com/Kotlin/kotlinx.coroutines/blob/master/docs/exception-handling.md#exception-handling

Explanations are visible in https://github.com/Kotlin/kotlinx.coroutines/issues/763 but I do not think users will take time to read all the issues to find such things.

Since it's a relatively major point as most docs suggest to have a global coroutineContext for the activity or fragment or whatever, not knowing that can generate hard to find issues.

**Comment by rocketraman** [comment]
Related to this is `supervisorScope`... the section about [supervision](https://github.com/Kotlin/kotlinx.coroutines/blob/master/docs/exception-handling.md#supervision) in the docs does not provide any examples of various *recovery* scenarios. For example, if I am doing parallel task decomposition via `async` inside a `supervisorScope`, how do I either let every job complete (via *not* calling `coroutineContext.cancelChildren()` in the catch block, or alternatively cancel all children coroutines of the supervisor (by calling `coroutineContext.cancelChildren()`). Are their other scenarios that should be discussed as well?
