### ISSUE TITLE
"Suspension functions can be called only within coroutine body" errors on non-suspension function

### ISSUE THREAD

**Issue by Xerus2000** [Kotlin/kotlinx.coroutines#788]
![image](https://user-images.githubusercontent.com/13354331/47937271-77474480-dee0-11e8-8d4d-acca97505860.png)
This code puts a function into a lambda that calls no suspension function. Yet, it reports of a function being a suspending function and thus refuses to compile. 
Here's the function:
![image](https://user-images.githubusercontent.com/13354331/47937346-aeb5f100-dee0-11e8-8112-cb9302775af3.png)

**Comment by Bluexin** [comment]
Looks like the sources and binaries don't match. It was changed to `suspend` in latest commit, and I guess snapshots brought it in.

**Comment by Xerus2000** [comment]
Alright, so the bug is actually in idea. It wasn't refreshing the sources even after doing a gradle refresh while using the newer binaries...
