### ISSUE TITLE
Possible legacy example

### ISSUE THREAD

**Issue by LouisCAD** [Kotlin/kotlinx.coroutines#803]
Multiple possible problems in this snippet of the documentation:
https://github.com/Kotlin/kotlinx.coroutines/blob/00d86c5c1ed5ad2c42b61eab4c5d4117d50339fb/common/kotlinx-coroutines-core-common/src/CoroutineScope.kt#L136

1. Uses `UI` instead of `Dispatchers.Main`
2. Unsure if showcasing an example with `async` is the best choice (I may be wrong on this).

**Comment by elizarov** [comment]
@qwwdfsad We need to merge this particular documentation-fixing commit from your postponed branch.
