### ISSUE TITLE
consumer proguard config is not added.

### ISSUE THREAD

**Issue by aegis123** [Kotlin/kotlinx.coroutines#807]
When building an apk with `org.jetbrains.kotlinx:kotlinx-coroutines-android` the [coroutines.pro](https://github.com/Kotlin/kotlinx.coroutines/blob/1.0.0/core/kotlinx-coroutines-core/resources/META-INF/proguard/coroutines.pro) is not added/applied to proguard configuration so it gets removed by progruard.

Is possible to change `org.jetbrains.kotlinx:kotlinx-coroutines-android` to an AAR instead of an JAR, then the consumer file is automatically used.

**Comment by plastiv** [comment]
It is a feature of R8 to fetch rules from .jars. Until you are not using R8 (it could be enabled for agp 3.2.1 and is enabled by default for 3.3.0-beta), copy rules manually to yours project proguard configuration.

**Comment by aegis123** [comment]
or maybe add it to the readme to make it clear that on agp 3.2.1 and lower or when using proguard you manually need to add it.

**Comment by elizarov** [comment]
Anyone with Android experience can help us write the corresponding docs with all the appropriate versions and settings?
