### ISSUE TITLE
No static method boxİnt(I)Ljava/lang/Integer

### ISSUE THREAD

**Issue by kemalatli** [Kotlin/kotlinx.coroutines#817]
I upgraded my project from experimental coroutines to stable 1.0.1 version. I configured my project with Kotlin 1.3 and with related plugins. I have two computers one of which is a Mac and the other one is a Windows machine. Strangely, I have no issues with my Windows machine. But I produce the following exception with my Macbook. I'm not sure if it is a bug.

`FATAL EXCEPTION: DefaultDispatcher-worker-3
    Process: me.app.android.dev, PID: 6612
    java.lang.NoSuchMethodError: No static method boxİnt(I)Ljava/lang/Integer; in class Lkotlin/coroutines/jvm/internal/Boxing; or its super classes (declaration of 'kotlin.coroutines.jvm.internal.Boxing' appears in /data/app/me.app.android.dev-2/base.apk:classes4.dex)
        at me.app.android.persistence.datasource.CategoryDataSource$listenToCategories$1.invokeSuspend(CategoryDataSource.kt:27)
        at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:32)
        at kotlinx.coroutines.DispatchedTask.run(Dispatched.kt:236)
        at kotlinx.coroutines.scheduling.CoroutineScheduler.runSafely(CoroutineScheduler.kt:594)
        at kotlinx.coroutines.scheduling.CoroutineScheduler.access$runSafely(CoroutineScheduler.kt:60)
        at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.run(CoroutineScheduler.kt:742)`

Exception points to below snippet:
```kotlin
launch {
            val categories = db.getReference(DISCOVERY).singleValue(::convertCategory) // <- This is just an ordinary suspending function
            categoryDao.updateCategories(categories)
            for (i in categories.map { it.categoryIndex }) { // <- Exception points this line.
                discoveryDataSource.fetchDiscoveryFor(i)
            }
        }
```

**Comment by qwwdfsad** [comment]
If you updated your project to 1.3 properly, there shouldn't be such error.
Does restarting your IDE and making `clean build` resolves the issue?

**Comment by qwwdfsad** [comment]
I can't reproduce your problem. Could you please create a self-contained project which reproduces the issue?

**Comment by LouisCAD** [comment]
@kemalatli Does this happen with java's `int` or `java.lang.Integer`? Is your project multi-modules? Any other detail?

**Comment by ErelOzcakirlar** [comment]
I think problem is our system language. I have the same problem and both @kemalatli and I are Turkish. And in Turkish language "i" character's uppercase version is "İ", not "I" as it is in English. Expected method name boxInt but it's actual value is boxİnt so it must be a locale problem. I am not facing this issue in my company's computer which English is set as system language.

**Comment by kemalatli** [comment]
@LouisCAD it happens with `java.lang.Integer` and I think @ErelOzcakirlar might have a point regarding system language settings. Still it is not obvious for me how it is related to the issue. I will check and let you know.

**Comment by emrekose26** [comment]
I've encountered this issue as well. As @ErelOzcakirlar mentioned that the problem is our system language, which is Turkish. After I changed system language TR to EN, the issue was solved.

**Comment by mrtcnnccn** [comment]
Why is this issue closed? Apparently there is a problem with Turkish language.

**Comment by elizarov** [comment]
I does not look like the issue in kotlinx.coroutines library. It looks like an issue in some of the toolchains that are used to build the project. Can you provide a small reproducer example that would show this project on Turkish locale?
