### ISSUE TITLE
Throwing exceptions inside coroutines generates warnings on Android 9 devices

### ISSUE THREAD

**Issue by matejdro** [Kotlin/kotlinx.coroutines#822]
Running this code on Android 9 device/emulator:

```
GlobalScope.launch {
    throw IllegalStateException()
}
```

will result in a `Accessing hidden method Ljava/lang/Thread;->getUncaughtExceptionPreHandler()Ljava/lang/Thread$UncaughtExceptionHandler; (light greylist, reflection)` warning printed into Logcat.

Android 9 includes [crackdown on developers using non-public stuff via reflection](https://developer.android.com/about/versions/pie/restrictions-non-sdk-interfaces), and looks like coroutines got caught in this.

**Comment by matejdro** [comment]
To be honest, I have no solution.

I think best bet is to [Create ticket about this on Google's tracker](https://issuetracker.google.com/issues/new?component=328403&template=1027267) and see what they think about it.

**Comment by LouisCAD** [comment]
cc @adamp ☝️

**Comment by adamp** [comment]
The issue tracker link above is the right place to propagate this question for now. In the meantime iirc you should only see the warning once during the reflection lookup, subsequent invocations should be quiet. I can try to take a look in some more detail next week.

**Comment by qwwdfsad** [comment]
Created https://issuetracker.google.com/issues/120953356

**Comment by Ethan1983** [comment]
@qwwdfsad Thanks for the fix. Is this available in a release?
