### ISSUE TITLE
Joining multiple jobs in a context can cause leaked jobs

### ISSUE THREAD

**Issue by emanguy** [Kotlin/kotlinx.coroutines#827]
Take the following code as an example:

``` kotlin
fun main() {
    val job = GlobalScope.launch { coroutineTesting() }

    runBlocking {
        job.join()
        println("Joined")
        delay(1500)
    }
}

suspend fun coroutineTesting() = coroutineScope {
    val job1 = Job()
    val job2 = Job()
    val job1Context = coroutineContext + job1
    val job2Context = coroutineContext + job2
    val doubleJobContext = coroutineContext + job1 + job2

    launch (job1Context) {
        while (true) {
            println("Doing work in job 1 context!")
            delay(200)
        }
    }

    launch (job2Context) {
        while (true) {
            println("Doing work in job 2 context!")
            delay(200)
        }
    }

    launch (doubleJobContext) {
        while (true) {
            println("Doing work in double job context!")
            delay(200)
        }
    }

    delay(500)
    job1.cancelAndJoin()
    println("Joined after cancel")
    delay(500)
    job2.cancelAndJoin()
    println("Second join after cancel")
}
```

Based on the output it appears that the coroutine in the "double job context" will keep running after Job 1 is cancelled. However, if I change the order of cancellation (i.e. cancel job 2 then job 1), then the coroutine in the double job context gets cancelled before Job 1 is complete. It appears as though the last job in a joined context is what new coroutines get assigned to. I had expected that the behavior would be either:

1. If either job is cancelled, coroutines within the double-job context will be cancelled no matter which one is cancelled
2. Both jobs must be cancelled before child coroutines are cancelled

Is this intended behavior or does it require a fix?

**Comment by qwwdfsad** [comment]
>val doubleJobContext = coroutineContext + job1 + job2

`job2` overwrites `job1` in the context, it is stated in the `plus` documentation: "The elements from this context with the same key as in the other one are dropped."

So behavior is intended, but we can improve tooling here, I've added your use-case to https://youtrack.jetbrains.com/issue/KT-28096

**Comment by emanguy** [comment]
Thanks for the quick response! This makes sense.
