### ISSUE TITLE
gradle dependencies fails for kotlinx-coroutines-core-native

### ISSUE THREAD

**Issue by jurmous** [Kotlin/kotlinx.coroutines#831]
The code compiles and runs, but `./gradlew dependencies` fails for the `org.jetbrains.kotlinx:kotlinx-coroutines-core-native:1.0.1` dependency.

Tested with both gradle 4.7 and 4.10.2 with `enableFeaturePreview("GRADLE_METADATA")`

Because the dependencies task fails the gradle panel in the IDE is showing red underlines under the project.

An image showing the issue
![schermafbeelding 2018-11-14 om 09 59 40](https://user-images.githubusercontent.com/6823511/48471394-1bd85900-e7f4-11e8-86c5-16742e37557e.png)

A zipped project with the issue:
[dependenciesTest.zip](https://github.com/Kotlin/kotlinx.coroutines/files/2579903/dependenciesTest.zip)

**Comment by wild-lynx** [comment]
Hi, thank you for the report. Did I get it right that IDE import and resolve works correctly, except the issue with underline at the Dependencies view? 
Please, follow the YT ticket to get the updates on the issue: https://youtrack.jetbrains.com/issue/KT-27500

**Comment by jurmous** [comment]
Yes indeed. The IDE import went right but it seems the underline the dependency. It seems to be related to the failed in `./gradlew dependencies`.

Thanks for the forward to the YT ticket!

**Comment by elizarov** [comment]
I'll close these issue here. Let's follow in YT.
