### ISSUE TITLE
Improve debuggability of repeated resumeWithException invocations

### ISSUE THREAD

**Issue by elizarov** [Kotlin/kotlinx.coroutines#833]
Repeated invocation of `CancellableContinuation.resumeWithException` forwards it to "uncaught exception handler" but there is nothing in stack trace to help figuring the root cause of the problem (second invocation of `resumeWithException`). This shall be fixed by wrapping exception before forwarding it to uncaught exception handler.

**Comment by cbruegg** [comment]
Would this also fix the issue described [here](https://github.com/JakeWharton/retrofit2-kotlin-coroutines-adapter/pull/30) where calling `resumeWithException` with an Exception created on a different thread than on which the suspending call was originally made resumes the coroutine with an Exception not containing the call to the suspending function?

**Comment by elizarov** [comment]
@cbruegg That will be fixed by #792

**Comment by qwwdfsad** [comment]
I am closing this because this issue is no longer valid after #901 and #896
