### ISSUE TITLE
Puzzling hang in runBlocking

### ISSUE THREAD

**Issue by elizarov** [Kotlin/kotlinx.coroutines#835]
From @konrad-kaminski 

This code hangs, but does not hang without `invokeOnCompletion`:

```
fun main() {
    runBlocking {
        val job = GlobalScope.launch {  }
        job.invokeOnCompletion {  }
    }
}
```

Initial investigation shows that it is timing-depended, e.g. adding `println` statements inside `runBlocking` before `}` affects whether it hangs or not, too.

**Comment by Bluexin** [comment]
I was confused with the issue title :p _~~hand~~ -> **hang**_ I guess?

**Comment by qwwdfsad** [comment]
Single-threaded reproducer:
```
runBlocking {
  // See #835
  coroutineContext[Job]!!.invokeOnCompletion {  }
}
```
