### ISSUE TITLE
Coroutines launched in actor are not getting cancelled when we close the actor channel

### ISSUE THREAD

**Issue by DilbagSandhu** [Kotlin/kotlinx.coroutines#836]
as the title says. if I launch a coroutine in actor and when I close the channel of the actor, coroutine not getting cancelled. 
if coroutine inherit the actorscope should not they be cancelled if the channel associated with it, sends the close signal.

**Comment by Bluexin** [comment]
Closing the channel just breaks the `for (msg in channel)` loop.
So if you want to cancel children when channel is closed, do it after that (by cancelling the current actor).

Did you try closing the channel with an exception?

**Comment by DilbagSandhu** [comment]
so there is no direct way to signal the actor to close the channel and cancel all associated coroutines?

**Comment by Bluexin** [comment]
Maybe if you close the channel with an exception, I haven't tried that but it *should* propagate the exception (cancelling children coroutines).

**Comment by elizarov** [comment]
Here is the actual explanation:

Closing the actor's channel (invoking `channel.close`) literally means the following: I'm no longer planning to send any more message to this actor, please complete (normally) what you were doing and terminate. Closing actor's channel is not cancelling. Actor can still have background children jobs that should continue to work until their normal termination. If you need to _cancel_ the actor (force it to abort without finishing processing the messages) you should cancel its scope. For example if you replace `actor.cancel()` with `throw IOException("We had failed -- abort everything")` in my previous example, then actor is cancelled.

**Comment by DilbagSandhu** [comment]
but what if we want to signal actor ("your work no longer needed(not failed) -- abort everything").
even if I send CancellationException with a close method like actor.close(CancellationException()) it reaches there in the next iteration of channel loop. the actor still continues to do work which I no longer needed.

**Comment by qwwdfsad** [comment]
The example of how to do it is written in the KDoc to `actor`:

>If the actor needs to be aborted without processing all the messages that were already sent to it, then it shall be created with a parent job:
```
val job = Job()
val c = actor(context = job) {  ... }
 ...
// abort the actor
job.cancel()
```

But this is a bit verbose and error-prone, in #87 we will address this issue properly
