### ISSUE TITLE
Provide capacity parameter to channel operators

### ISSUE THREAD

**Issue by qwwdfsad** [Kotlin/kotlinx.coroutines#841]
See https://stackoverflow.com/questions/53282761/kotlin-coroutines-how-to-use-array-channel-with-filter-map

While it could be useful in general, this feature should not be implemented before cold streams (#254) for the same reason why these operators are marked as "obsolete"

**Comment by fvasco** [comment]
Providing `filterTo(Channel)`/`mapTo(Channel)` can solve this issue without binding the channel's operator to `Channel` implementation.

**Comment by qwwdfsad** [comment]
Won't be fixed
