### ISSUE TITLE
How to pause a channel from receive or send

### ISSUE THREAD

**Issue by iammini5** [Kotlin/kotlinx.coroutines#843]
I have a user cases just like how LiveData works, I tried to use Channel but failed. Basically I need to be able to pause the channel from being receive for a moment.

val job = launch(start = CoroutineStart.LAZY) {
            channel.consumeEach { }
        }

I tried to cancel the job and then create another job with the same code above want to use the old channel , but i am not able to receive any thing after i use send function to it .

**Comment by Bluexin** [comment]
If it's a rendez-vous channel (0 capacity) it will technically be paused for as long as there is no consumer actually receiving from it. In other cases, it'll be paused whenever it's full.
Would that work for your use case? Not sure I fully understand what you mean/need.

**Comment by jcornaz** [comment]
This is because you use `consumeEach`. It will cancel the channel in case of exception or in case of cancellation of the coroutines.

```kotlin
val job = launch(start = CoroutineStart.LAZY) {
  for (element in channel) { // <-- suspend
     // use the element
  }
}
```

With this code, you may cancel the job, and restart another one later in order to receive the next messages sent through that channel.
