### ISSUE TITLE
List of available builders is missing in the readme

### ISSUE THREAD

**Issue by Dmitry-Borodin** [Kotlin/kotlinx.coroutines#846]
I couldn't find up to date list of coroutine builders what what they are used for anywhere in the docs.

**Comment by elizarov** [comment]
Maybe here: https://kotlin.github.io/kotlinx.coroutines/kotlinx-coroutines-core/

**Comment by Dmitry-Borodin** [comment]
Thanks!
Is that really core (JVM) specific? 
I expected to see it in top level or in common.

**Comment by qwwdfsad** [comment]
Core is not JVM specific.
Either supported platforms are enumerated in builder's KDoc (e.g. [runBlocking](https://kotlin.github.io/kotlinx.coroutines/kotlinx-coroutines-core/kotlinx.coroutines/run-blocking.html)) or completely omitted (=> supported on all platforms)

**Comment by Dmitry-Borodin** [comment]
From the top level readme:
core — Kotlin/JVM implementation of common coroutines with additional features: 
Which is confusing me...

**Comment by qwwdfsad** [comment]
`core` is a JVM-specific module and uses `kotlinx.coroutines` as a root package.
`common` is a common module and uses `kotlinx.coroutines` as a root package as well.

Top level readme is about JVM package, while API reference aggregates all platforms under one project. It is really confusing, we will think of how to improve the situation

**Comment by dkhalanskyjb** [comment]
Now the docs clearly state what is `common`, what is `jvm`, etc.
