### ISSUE TITLE
JCenter repository link messed up

### ISSUE THREAD

**Issue by altavir** [Kotlin/kotlinx.coroutines#85]
The installation recommendation from [here](https://github.com/Kotlin/kotlinx.coroutines) does not work. For some reason bintray artifact is called `benchmarks`: https://bintray.com/kotlin/kotlinx/kotlinx.coroutines

**Comment by elizarov** [comment]
You should following instruction in the text. The JCenter "download" links gives a link to an incorrect artifact for some reason. I'll see what can be done.

**Comment by altavir** [comment]
It was the first thing I tried. And then it showed gradle error. I've cleaned the gradle cache and now it is working fine, so you could probably close the issue.
