### ISSUE TITLE
Ability to get and process current EventLoop

### ISSUE THREAD

**Issue by cy6erGn0m** [Kotlin/kotlinx.coroutines#850]
There are cases when it is important to process events of current even loop based dispatcher (`Unconfined`, `runBlockgin` and so on). 

For example we have two coroutines running on such event-loop based dispatcher and an asyc destination D. The first one produces messages (coroutine P) and the second filters them into the destination (coroutine F). The coroutines are connected by async channels.

`P -> F -> D`

This works well until we need to adopt some blocking API that doesn't support sending to an async `SendChannel` (or similar). So to get it working we can write an adapter (such as [JavaBlockingQueue](https://gist.github.com/cy6erGn0m/8213cf6a213aaa5a6194bc4203738eec)) that simply blocks if a send operation to an async channel suspends and until it completes.

It may work well with regular dispatchers (such as `Dispatchers.IO`) but doesn't work with event-loop based dispatchers. 

Consider the following explanation why it doesn't:
1. Java code in `P` does send to blocking queue (adapter)
2. Blocking queue adapter does send to async channel and fail (not enough buffer capacity)
3. Blocking queue adapter blocks (does thread park)
4. Here it should be coroutine `F` dispatcher however it couldn't since the event loop is blocked 

The obvious solution here is to fix blocking adapter implementation to not park thread but process event loop instead. Also the default `runBlocking` implementation could also have this capability but it's not clear how to achieve it).

So my first idea is:
1. Make `EventLoop` interface public 
2. Make possible to lookup it from a `CoroutineDispatcher` (member function, extension or something like that)

So one who may need to process event loop can simply write wait loop like this

```kotlin
val eventLoop = dispatcher.eventLoop ?: error("...")

while (condition) {
    val time = eventLoop.processNextEvent()
    if (time == 0L) continue
    if (!condition) break
    publishCurrentThread()
    LockSupport.park(time)
}
```

The disadvantage here is that we do park implicitly so it may prevent epoll-based dispatchers in the future to work properly as we will need to do epoll with time instead of park. So we probably need `BlockingEventLoop` with park function. Adding `processNextEventBlocking` function will not help as I would like to check condition after event processing but before parking.

**Comment by elizarov** [comment]
The solution for `runBlocking` and 'UNCONFINED` is going to be implement in #860. For this issue (ability to access the current event in a thread) we're going to start with a prototype experimental API. The goal of this API is to encapsulated part/unpark methods in JVM. The prototype API is to be discussed when some working prototype for #860 is there.
