### ISSUE TITLE
A page on "concurrency idioms" in docs

### ISSUE THREAD

**Issue by elizarov** [Kotlin/kotlinx.coroutines#853]
We should have a page in documentation on "concurrency idioms" that shows the most common patterns of code that people should learn to use with coroutines.

**Comment by IvanMwiruki** [comment]
Has any progress been made on this?

**Comment by qwwdfsad** [comment]
Unfortunately, no progress. We've been focused on the `Flow` release and rewriting documentation as a "side work in spare time between releases" won't give as a result we'd like.
Thanks for the reminder, we will discuss it again internally.
