### ISSUE TITLE
Question: Job Initialization in Android Activity

### ISSUE THREAD

**Issue by jguerinet** [Kotlin/kotlinx.coroutines#854]
In every example I have seen  when it comes to job initialization in an Activity you always find the following: 
```
lateinit var job: Job
override val coroutineContext: CoroutineContext
    get() = Dispatchers.Main + job

override fun onCreate(savedInstanceState: Bundle?) {
    super.onCreate(savedInstanceState)
    job = Job()
}
```
This is taken directly from the [coroutines documentation](https://kotlin.github.io/kotlinx.coroutines/kotlinx-coroutines-core/kotlinx.coroutines/-coroutine-scope/). 

I tend to avoid `lateinit var`s as much as I can because of any number of problems if they are not initialized at the correct time. I am therefore wondering, is this an acceptable alternative?
```
val job: Job by lazy { Job() }
override val coroutineContext: CoroutineContext
    get() = Dispatchers.Main + job

override fun onCreate(savedInstanceState: Bundle?) {
    super.onCreate(savedInstanceState)
    ...
}
```

Pros (for me): 
* Your `Job` is always defined, no possibility of it being null for whatever reason 
* `Job` declaration/initialization is in one location 

Potential Cons: 
* I haven't checked this out, but maybe creating a `Job` is expensive and if you therefore create it only when you need it as opposed to preemptively you're slowing down that piece of code
* If you don't end up using the job, you still create it for no reason when you call `job.cancel()` in `onDestroy()` (although in the official example you are also creating it for no reason in this case, just at a different time). 

Depending on the answer to that first con, the pros outweigh the cons for me in this case, but I feel like I'm missing something. 

Thanks!

**Comment by JakeWharton** [comment]
There's no reason to use `lazy` and there's no reason that I'm aware of to use a computed property.

```kotlin
val job = Job()
override val coroutineContext = Dispatchers.Main + job
```

**Comment by qwwdfsad** [comment]
All three approaches are fine.
As soon as we decide how to name `cancel` extension on the scope, we will provide `MainScope` as well (see #829 and #828):
```
class MyActivity : CoroutineScope by MainScope()

override fun onDestroy() {
   super.onDestroy()
   cancelScope()
}
```

**Comment by jguerinet** [comment]
@JakeWharton Yes indeed, after rereading it I realized that there isn't any benefit in my approach. The original idea was the offload the creation of the `Job` for when you needed it, not unlike the `lateinit` version where the job creation would happen during `onCreate()` and not before. 

@qwwdfsad Great, thanks for the info. I'll close this for now and subscribe to those 2 issues for continued updates. I actually have defined a `MainScope` in my projects as well to keep coroutines usage clear, so moving that into the coroutines library would be a welcome change on my end.

**Comment by PembaTamang** [comment]
I did this and I am getting an error which says: lateinit property job has not been initialized.
What could be happening?

**Comment by jguerinet** [comment]
Check out the [MainScope](https://kotlin.github.io/kotlinx.coroutines/kotlinx-coroutines-core/kotlinx.coroutines/-main-scope.html), which has since been added since this conversation. This should replace any need of a `lateinit` variable. If you can't use `MainScope` for any reason, please see the straightforward implementation in [Jake Wharton's comment](https://github.com/Kotlin/kotlinx.coroutines/issues/854#issuecomment-441417463) above.
