### ISSUE TITLE
DefaultExecutor can never exit on IDLE

### ISSUE THREAD

**Issue by cy6erGn0m** [Kotlin/kotlinx.coroutines#856]
See `DefaultExecutor.run`. According to it's source, if there are no tasks then `processNextEvent()` returns `Long.MAX_VALUE`. Then we check `shutdownNanos` and if not yet initialized then we check it again for the same condition (that is always true) and compute `parkNanos` time. After parking for `KEEP_ALIVE_NANOS` we respin here again but we are falling into the second case where `parkNanos = parkNanos.coerceAtMost(KEEP_ALIVE_NANOS)` is executed and the same after one more respin so we will never exit but spin every second instead.

Also it looks like we need to reset `shutdownNanos` if there was a task scheduled but we don't do it.

**Comment by mirjalal** [comment]
Any fix for this?
