### ISSUE TITLE
Document how to disable warning for `ExperimentalCoroutineApi` and `ObsoleteCoroutineApi`

### ISSUE THREAD

**Issue by jcornaz** [Kotlin/kotlinx.coroutines#859]
Prior Kotlin 1.3 documentation was clear on how to disable warning for experimental usage of coroutines. (for gradle: `kotlin.experimental.coroutines 'enable'`). And it worked well.

But since Kotlin 1.3, I'm not able to find clear and official documentation about how to disable warnings for usages of  `ExperimentalCoroutineApi` and `ObsoleteCoroutineApi`. I managed to find few things but it is never clear, and doesn't work well.

I suggest to document this. Here is few places I'd expect to find that information:
 * https://kotlinlang.org/docs/reference/using-gradle.html
 * https://kotlinlang.org/docs/reference/using-maven.html
 * https://github.com/Kotlin/kotlinx.coroutines/blob/master/COMPATIBILITY.md

**Comment by qwwdfsad** [comment]
Are you using Intellij IDEA? It should provide a clear advice what you can do with a quickfix

**Comment by jcornaz** [comment]
Yes I use IntelliJ IDEA, but it only propose to add the `UseExperimental` annotation or the used annotation to the member. It doesn't help me to understand how to disable warnings in the whole project.

By the I did find what to do. (using `freeCompilerArgs` for gradle, and plugin configuration arguments for maven).

But I think it should be easier and quicker to find that information and it deserve proper documentation.

**Comment by matejdro** [comment]
Yeah, situation is not ideal. Intellij suggests to add `UseExperimental` annotation. But this annotation itself is ALSO experimental. So to use this annotation, I had to add this to the gradle file, which was not documented at all:

```
tasks.withType(org.jetbrains.kotlin.gradle.tasks.KotlinCompile).all {
            kotlinOptions.freeCompilerArgs += ["-Xuse-experimental=kotlin.Experimental"]
        }
```

**Comment by jcornaz** [comment]
@qwwdfsad, any update on this?

**Comment by qwwdfsad** [comment]
@jcornaz we've found a huge documentation backlog in Kotlin triggered by your issue (https://youtrack.jetbrains.com/issue/KT-28589, parent and related), but it won't be fixed soon.
So I will document it in coroutines separately

**Comment by jcornaz** [comment]
Ok, thanks @qwwdfsad.

**Comment by theapache64** [comment]
I use

```groovy
 kotlinOptions {
        // Disabling coroutine's ExperimentalCoroutinesApi warning
        freeCompilerArgs += [
                "-Xuse-experimental=kotlinx.coroutines.ExperimentalCoroutinesApi",
                "-Xuse-experimental=kotlinx.coroutines.TheAnnotationYouWantToDisable"
        ]
    }
```

**Comment by i30mb1** [comment]
I use
```
tasks.withType<KotlinCompile>().configureEach {
    kotlinOptions {
        freeCompilerArgs = freeCompilerArgs + listOf("-Xopt-in=kotlinx.coroutines.ExperimentalCoroutinesApi")
        jvmTarget = "11"
    }
}
```
