### ISSUE TITLE
Errors with JS ServiceWorker due to Window usage

### ISSUE THREAD

**Issue by neVERberleRfellerER** [Kotlin/kotlinx.coroutines#863]
Due to reliance on Window, it's impossible to use kotlinx.coroutines in ServiceWorkers,
Something as simple as
```
fun something() {
    console.log("something")
}
GlobalScope.launch {
    something()
}

```
causes cryptic errors. Everything is made even worse by browsers trashing console output when worker fails - it is absolute hell to find out what is going on.

**Comment by qwwdfsad** [comment]
I've got a potential fix, but I have a hard time to make a consistent Kotlin+Service Worker bundle to test.
Could you please provide a sample project that demonstrates the issue? It would significantly speed up the fix

**Comment by neVERberleRfellerER** [comment]
It took a while to find it but I have the most important part of the code. It does not build for some reason, i'll try to fix that and simplify it to bere minimum.

**Comment by neVERberleRfellerER** [comment]
Unfortunaltely, I can't turn the code into something useful. It's a patch that was supposed to apply to now deleted branch before whole idea to use ServiceWorker was scraped and my attempt to create new sample from scratch was unsuccessful. I'll try again in another week or two.

**Comment by neVERberleRfellerER** [comment]
I've updated original application and everything works properly at least with kotlinx.coroutines 1.3.0-RC2. The only window reference is the one I requested directly. Thank you.
