### ISSUE TITLE
CoroutineScope rethrow previous exception on new launch with same job

### ISSUE THREAD

**Issue by rezastallone** [Kotlin/kotlinx.coroutines#865]
I follow this guide for using coroutine scope in object with lifecycle object , in my case i use coroutine in android service class

[Coroutine in lifecycle object guide](https://kotlinlang.org/docs/reference/coroutines/coroutine-context-and-dispatchers.html#cancellation-via-explicit-job)

so my service looks like this 
`  
  class MessageWorkerService : Service()  {
       
    private var counter = 0 

    private val parentJob = Job()
    private val scope = CoroutineScope(Dispatchers.IO + parentJob)
   
     private fun myFunction(intent: Intent) = {
            val onError = CoroutineExceptionHandler { _, throwable ->
                  throwable.printStackTrace()
            }
            scope.launch(onError){
                   counter++
                    if (counter == 2) {
                        throw Exception("Crash when counter is 2 ")
                    }
            }
     }

    override fun onDestroy() {
        parentJob.cancel()
        super.onDestroy()
    }

}
`
When I call myFunction() on first call it works fine, on the second it throws error as it should, but on the third, fourth and so on call it throw exception thrown in the second call, it doesn't even reach counter++. it just throw error on .launch call

But when I change myFunction to use the new coroutinescope on each call 

`
CoroutineScope(Dispatchers.IO).launch(onError){
           counter++
           if (counter == 2) {
                    throw Exception("Crash when counter is 2 ")
            }
}
`
It works at it should ( exception only happens when counter is 2 )
Is this how the behaviour expected when coroutine scope share same job ? if so then I have a problem now, how do I use coroutinescope in a lifecycle object without running into this issue ?

I am using org.jetbrains.kotlinx:kotlinx-coroutines-core:1.0.1

**Comment by qwwdfsad** [comment]
It is because root `Job` is cancelled after the first failure.
Please replace `private val parentJob = Job()` with `private val parentJob = SupervisorJob()` and everything will work as you expect.

**Comment by rezastallone** [comment]
> It is because root `Job` is cancelled after the first failure in the child.
> Please replace `private val parentJob = Job()` with `private val parentJob = SupervisorJob()` and everything will work as you expect.

I just tried your solution, works like a char ! 
the guide on that site should be updated.
@qwwdfsad thanks fallout guy !
