### ISSUE TITLE
How to transform a blocking function to suspendable function? 

### ISSUE THREAD

**Issue by tinycedar** [Kotlin/kotlinx.coroutines#872]
I know how to transform a async or callback based functions to suspended functions. Now I am wondering whether it's possible to transform a function with blocking I/O code inside to a suspendable function ?

**Comment by elizarov** [comment]
You can use `withContext { ... }`. You can read more in my blog post: https://medium.com/@elizarov/blocking-threads-suspending-coroutines-d33e11bf4761
