### ISSUE TITLE
java.lang.ClassNotFoundException: Didn't find class "kotlinx.coroutines.experimental.Deferred" 

### ISSUE THREAD

**Issue by HemendraGangwar** [Kotlin/kotlinx.coroutines#879]
I am facing this issue from a week, can you please let me know why i am getting

**java.lang.ClassNotFoundException: Didn't find class "kotlinx.coroutines.experimental.Deferred" on path: DexPathList[[zip file "/data/app/com.coroutines.retrofit.kotlin-1/base.apk"],nativeLibraryDirectories=[/vendor/lib64, /system/lib64]]**

**Failed resolution of: Lkotlinx/coroutines/experimental/Deferred;** 

while i am using the below dependencies,

implementation 'com.jakewharton.retrofit:retrofit2-kotlin-coroutines-experimental-adapter:1.0.0'

implementation 'org.jetbrains.kotlinx:kotlinx-coroutines-core:1.0.1'
implementation 'org.jetbrains.kotlinx:kotlinx-coroutines-android:1.0.1'

and the kotlin version is :
ext.kotlin_version = '1.3.10'

**Comment by qwwdfsad** [comment]
You have to use adapter of the version 0.9.2, it is written in the [README](https://github.com/JakeWharton/retrofit2-kotlin-coroutines-adapter/blob/master/README.md):

>If you are using Kotlin 1.3, download the latest JAR or grab via Maven:
>version>0.9.2</version>
>If you are using Kotlin pre-1.3 and experimental coroutines, download its latest JAR or grab via Maven:
><version>1.0.0</version>

You are using Kotlin 1.3.10, so should pick 0.9.2

**Comment by HemendraGangwar** [comment]
@qwwdfsad Thanks you and the issue has been resolved  by removing experimental version of  **kotlin-coroutines-adapter**
