### ISSUE TITLE
Convert existing blocking Java functions to coroutines

### ISSUE THREAD

**Issue by tinycedar** [Kotlin/kotlinx.coroutines#881]
I have 2 existing functions written in Java: 
```Java
public void injectStock(List<SkuDTO> skus) {
    // omitted...blocking I/O here
}

public void injectAttribute(List<SkuDTO> skus) {
    // omitted...blocking I/O here
}
```
And now I want to invoke these 2 function in a **single thread concurrently**, by means of using Kotlin coroutines. 

```Kotlin
fun doInject(service: SkuQueryServiceImpl, skus: List<SkuDTO>) {
    runBlocking {
        var start = System.currentTimeMillis()
        val stock = async { injectStock(service, skus) }
        val attr = async { injectAttr(service, skus) }
        stock.await()
        attr.await()
        var end = System.currentTimeMillis()
        println("total costs ${end - start} ms, [$start -> $end], ${Thread.currentThread().name}")
    }
}

suspend fun injectStock(service: SkuQueryServiceImpl, skus: List<SkuDTO>): List<SkuDTO> =
        withContext(Dispatchers.IO) {
            val start = System.currentTimeMillis()
            try {
                service.injectStock(skus)
            } finally {
                val end = System.currentTimeMillis()
                println("injectStock ===> ${Thread.currentThread().name}, costs ${end - start} ms, [$start -> $end]")
            }
        }

suspend fun injectAttr(service: SkuQueryServiceImpl, skus: List<SkuDTO>): List<SkuDTO> =
        withContext(Dispatchers.IO) {
            val start = System.currentTimeMillis()
            try {
                service.injectAttribute(skus)
            } finally {
                val end = System.currentTimeMillis()
                println("injectAttr ===> ${Thread.currentThread().name}, costs ${end - start} ms, [$start -> $end]")
            }
        }
```

But the output doesn't work because the time intervals fail to overlap. So is it possible to wrap blocking I/O functions as coroutines and ran them concurrently in a single thread ?

```bash
injectStock ===> DefaultDispatcher-worker-1, costs 41 ms, [1543909588487 -> 1543909588528]
injectAttr ===> DefaultDispatcher-worker-1, costs 67 ms, [1543909588528 -> 1543909588595]
total costs 108 ms, [1543909588487 -> 1543909588595], XNIO-3 task-10
```

**Comment by fvasco** [comment]
> So is it possible to wrap blocking I/O functions as coroutines and ran them concurrently in a single thread ?

No, coroutines are syntax sugar.

**Comment by tinycedar** [comment]
> > So is it possible to wrap blocking I/O functions as coroutines and ran them concurrently in a single thread ?
> 
> No, coroutines are syntax sugar.

It's a pity...In Go, we can achieve this by simply using goroutine regardless of underlying operations(whether I/O blocking or not), because all I/O operations just block current goroutines instead of current thread.

**Comment by elizarov** [comment]
@tinycedar In fact, you cannot do this Go. To see that it is true, take any 3rd party C library with native blocking function and invoke it from a goroutine. It will block the corresponding thread. What you _can_ do in Go, is that you can use standard socket APIs from the Go standard library, because they are written in asynchronous (non-blocking way). 

In Kotlin you can use any asynchronous networking library to the same effect. I'll plug Ktor (http://ktor.io) here, but any other asynchronous library in JVM would work just as well.
