### ISSUE TITLE
Update depencies to the latest kotlin version

### ISSUE THREAD

**Issue by ekans** [Kotlin/kotlinx.coroutines#883]
Currently in my gradle projects I can't follow, by default, the kotlin version update because kotlinx.coroutines depends on kotlin 1.3.0.

Gradle resolves the conflicting version by using kotlin version defined by kotlinx.coroutines. So currently my projects use kotlin 1.3.0 instead of 1.3.11.

Why do you not create a new release when a new kotlin version is released ?

**Comment by fvasco** [comment]
Pay attention to your import order, put coroutines after Kotlin's stdlib

**Comment by ekans** [comment]
What do you mean by import order ? Dependencies declaration order in build gradle files ?

**Comment by ekans** [comment]
Ok I understand.

I had a bad import at the beginning of one build gradle file...
Solved. Thanks!
