### ISSUE TITLE
D8 Compile errors with --info enabled in gradle

### ISSUE THREAD

**Issue by diegomontoya** [Kotlin/kotlinx.coroutines#887]
Kotlin 1.3.11
Android Studio 3.3rc2
Kotlinx.coroutines 1.0.1

> D8:Unexpected error while reading kotlinx.coroutines.channels.ChannelsKt__Channels_commonKt$filterNotTo$1's kotlin.Metadata: null
D8: Unexpected error while reading kotlinx.coroutines.channels.ChannelsKt__Channels_commonKt$filterTo$1's kotlin.Metadata: null
D8: Unexpected error while reading kotlinx.coroutines.channels.ChannelsKt__Channels_commonKt$filterNotTo$3's kotlin.Metadata: null
D8: Unexpected error while reading kotlinx.coroutines.channels.ChannelsKt__Channels_commonKt$filterTo$3's kotlin.Metadata: null
D8: Unexpected error while reading kotlinx.coroutines.channels.ChannelsKt__Channels_commonKt$filterIndexedTo$3's kotlin.Metadata: null
D8: Unexpected error while reading kotlinx.coroutines.channels.ChannelsKt__Channels_commonKt$fold$1's kotlin.Metadata: null
D8: Unexpected error while reading kotlinx.coroutines.channels.ChannelsKt__Channels_commonKt$filterIndexedTo$1's kotlin.Metadata: null
D8: Unexpected error while reading kotlinx.coroutines.channels.ChannelsKt__Channels_commonKt$toChannel$1's kotlin.Metadata: null
D8: Unexpected error while reading kotlinx.coroutines.channels.ChannelsKt__Channels_commonKt$associateByTo$3's kotlin.Metadata: null
D8: Unexpected error while reading kotlinx.coroutines.channels.ChannelsKt__Channels_commonKt$indexOf$1's kotlin.Metadata: null
D8: Unexpected error while reading kotlinx.coroutines.channels.ChannelsKt__Channels_commonKt$foldIndexed$1's kotlin.Metadata: null
D8: Unexpected error while reading kotlinx.coroutines.channels.ChannelsKt__Channels_commonKt$associateByTo$1's kotlin.Metadata: null
D8: Unexpected error while reading kotlinx.coroutines.channels.ChannelsKt__Channels_commonKt$toCollection$1's kotlin.Metadata: null
D8: Unexpected error while reading kotlinx.coroutines.channels.ChannelsKt__Channels_commonKt$lastIndexOf$1's kotlin.Metadata: null
D8: Unexpected error while reading kotlinx.coroutines.channels.ChannelsKt__Channels_commonKt$mapIndexedNotNullTo$1's kotlin.Metadata: null
D8: Unexpected error while reading kotlinx.coroutines.channels.ChannelsKt__Channels_commonKt$groupByTo$1's kotlin.Metadata: null
D8: Unexpected error while reading kotlinx.coroutines.channels.ChannelsKt__Channels_commonKt$mapIndexedTo$3's kotlin.Metadata: null
D8: Unexpected error while reading kotlinx.coroutines.channels.ChannelsKt__Channels_commonKt$mapIndexedTo$1's kotlin.Metadata: null
D8: Unexpected error while reading kotlinx.coroutines.channels.ChannelsKt__Channels_commonKt$mapIndexedNotNullTo$3's kotlin.Metadata: null
D8: Unexpected error while reading kotlinx.coroutines.channels.ChannelsKt__Channels_commonKt$associateTo$1's kotlin.Metadata: null
D8: Unexpected error while reading kotlinx.coroutines.channels.ChannelsKt__Channels_commonKt$groupByTo$3's kotlin.Metadata: null
D8: Unexpected error while reading kotlinx.coroutines.channels.ChannelsKt__Channels_commonKt$mapTo$1's kotlin.Metadata: null
D8: Unexpected error while reading kotlinx.coroutines.channels.ChannelsKt__Channels_commonKt$filterNotNullTo$1's kotlin.Metadata: null
D8: Unexpected error while reading kotlinx.coroutines.channels.ChannelsKt__Channels_commonKt$mapNotNullTo$3's kotlin.Metadata: null
D8: Unexpected error while reading kotlinx.coroutines.channels.ChannelsKt__Channels_commonKt$mapTo$3's kotlin.Metadata: null
D8: Unexpected error while reading kotlinx.coroutines.channels.ChannelsKt__Channels_commonKt$filterNotNullTo$3's kotlin.Metadata: null
D8: Unexpected error while reading kotlinx.coroutines.channels.ChannelsKt__Channels_commonKt$toMap$2's kotlin.Metadata: null
D8: Unexpected error while reading kotlinx.coroutines.channels.ChannelsKt__Channels_commonKt$mapNotNullTo$1's kotlin.Metadata: null

**Comment by jsjeon** [comment]
This is https://issuetracker.google.com/issues/119027642, and the fix should be included to AS 3.3 rc3 or final.

**Comment by qwwdfsad** [comment]
Thanks @jsjeon !
