### ISSUE TITLE
Mutex fairness policy

### ISSUE THREAD

**Issue by fvasco** [Kotlin/kotlinx.coroutines#90]
The current `Mutex` implementation is always fair or not?
Documentation should explicit it.

If current implementation isn't fair then is it possible to add an optional parameter to define a fairness policy?

**Comment by elizarov** [comment]
It is fair.

**Comment by elizarov** [comment]
Released in version 0.18

**Comment by TYZRPVX** [comment]
lock & unlock function make use of `LockFreeLinkedListNode` to ensure FIFO order
