### ISSUE TITLE
Android Studio R8 Shrinking

### ISSUE THREAD

**Issue by jrcacd** [Kotlin/kotlinx.coroutines#905]
Android Studio 3.4 Canary 8
Coroutines 1.1.0-alpha

Generate obfuscated bundle.

Results:

15:07:53.393 [INFO] [org.gradle.api.Project] D8: Unexpected error while reading kotlinx.coroutines.channels.ChannelsKt__Channels_commonKt$filterNotTo$1's kotlin.Metadata: null
15:07:53.400 [INFO] [org.gradle.api.Project] D8: Unexpected error while reading kotlinx.coroutines.channels.ChannelsKt__Channels_commonKt$filterTo$1's kotlin.Metadata: null
15:07:53.477 [INFO] [org.gradle.api.Project] D8: Unexpected error while reading kotlinx.coroutines.channels.ChannelsKt__Channels_commonKt$filterNotTo$3's kotlin.Metadata: null
15:07:53.485 [INFO] [org.gradle.api.Project] D8: Unexpected error while reading kotlinx.coroutines.channels.ChannelsKt__Channels_commonKt$filterTo$3's kotlin.Metadata: null
15:07:53.558 [INFO] [org.gradle.api.Project] D8: Unexpected error while reading kotlinx.coroutines.channels.ChannelsKt__Channels_commonKt$filterIndexedTo$3's kotlin.Metadata: null
15:07:53.569 [INFO] [org.gradle.api.Project] D8: Unexpected error while reading kotlinx.coroutines.channels.ChannelsKt__Channels_commonKt$fold$1's kotlin.Metadata: null
15:07:53.637 [INFO] [org.gradle.api.Project] D8: Unexpected error while reading kotlinx.coroutines.channels.ChannelsKt__Channels_commonKt$filterIndexedTo$1's kotlin.Metadata: null
15:07:53.705 [INFO] [org.gradle.api.Project] D8: Unexpected error while reading kotlinx.coroutines.channels.ChannelsKt__Channels_commonKt$toChannel$1's kotlin.Metadata: null
15:07:53.811 [INFO] [org.gradle.api.Project] D8: Unexpected error while reading kotlinx.coroutines.channels.ChannelsKt__Channels_commonKt$associateByTo$3's kotlin.Metadata: null
15:07:53.814 [INFO] [org.gradle.api.Project] D8: Unexpected error while reading kotlinx.coroutines.channels.ChannelsKt__Channels_commonKt$indexOf$1's kotlin.Metadata: null
15:07:53.819 [INFO] [org.gradle.api.Project] D8: Unexpected error while reading kotlinx.coroutines.channels.ChannelsKt__Channels_commonKt$foldIndexed$1's kotlin.Metadata: null
15:07:54.016 [INFO] [org.gradle.api.Project] D8: Unexpected error while reading kotlinx.coroutines.channels.ChannelsKt__Channels_commonKt$associateByTo$1's kotlin.Metadata: null
15:07:54.070 [INFO] [org.gradle.api.Project] D8: Unexpected error while reading kotlinx.coroutines.channels.ChannelsKt__Channels_commonKt$toCollection$1's kotlin.Metadata: null
15:07:54.087 [INFO] [org.gradle.api.Project] D8: Unexpected error while reading kotlinx.coroutines.channels.ChannelsKt__Channels_commonKt$lastIndexOf$1's kotlin.Metadata: null
15:07:54.428 [INFO] [org.gradle.api.Project] D8: Unexpected error while reading kotlinx.coroutines.channels.ChannelsKt__Channels_commonKt$mapIndexedNotNullTo$1's kotlin.Metadata: null
15:07:54.431 [INFO] [org.gradle.api.Project] D8: Unexpected error while reading kotlinx.coroutines.channels.ChannelsKt__Channels_commonKt$groupByTo$1's kotlin.Metadata: null
15:07:54.440 [INFO] [org.gradle.api.Project] D8: Unexpected error while reading kotlinx.coroutines.channels.ChannelsKt__Channels_commonKt$mapIndexedTo$3's kotlin.Metadata: null
15:07:54.461 [INFO] [org.gradle.api.Project] D8: Unexpected error while reading kotlinx.coroutines.channels.ChannelsKt__Channels_commonKt$mapIndexedTo$1's kotlin.Metadata: null
15:07:54.514 [INFO] [org.gradle.api.Project] D8: Unexpected error while reading kotlinx.coroutines.channels.ChannelsKt__Channels_commonKt$mapIndexedNotNullTo$3's kotlin.Metadata: null
15:07:54.699 [INFO] [org.gradle.api.Project] D8: Unexpected error while reading kotlinx.coroutines.channels.ChannelsKt__Channels_commonKt$associateTo$1's kotlin.Metadata: null
15:07:54.702 [INFO] [org.gradle.api.Project] D8: Unexpected error while reading kotlinx.coroutines.channels.ChannelsKt__Channels_commonKt$groupByTo$3's kotlin.Metadata: null
15:07:54.704 [INFO] [org.gradle.api.Project] D8: Unexpected error while reading kotlinx.coroutines.channels.ChannelsKt__Channels_commonKt$mapTo$1's kotlin.Metadata: null
15:07:54.707 [INFO] [org.gradle.api.Project] D8: Unexpected error while reading kotlinx.coroutines.channels.ChannelsKt__Channels_commonKt$filterNotNullTo$1's kotlin.Metadata: null
15:07:54.717 [INFO] [org.gradle.api.Project] D8: Unexpected error while reading kotlinx.coroutines.channels.ChannelsKt__Channels_commonKt$mapNotNullTo$3's kotlin.Metadata: null
15:07:54.718 [INFO] [org.gradle.api.Project] D8: Unexpected error while reading kotlinx.coroutines.channels.ChannelsKt__Channels_commonKt$mapTo$3's kotlin.Metadata: null
15:07:54.724 [INFO] [org.gradle.api.Project] D8: Unexpected error while reading kotlinx.coroutines.channels.ChannelsKt__Channels_commonKt$filterNotNullTo$3's kotlin.Metadata: null
15:07:54.727 [INFO] [org.gradle.api.Project] D8: Unexpected error while reading kotlinx.coroutines.channels.ChannelsKt__Channels_commonKt$toMap$2's kotlin.Metadata: null
15:07:54.727 [INFO] [org.gradle.api.Project] D8: Unexpected error while reading kotlinx.coroutines.channels.ChannelsKt__Channels_commonKt$mapNotNullTo$1's kotlin.Metadata: null
...
15:09:13.994 [ERROR] [org.gradle.internal.buildevents.BuildExceptionReporter] 
15:09:13.995 [ERROR] [org.gradle.internal.buildevents.BuildExceptionReporter] FAILURE: Build failed with an exception.
15:09:13.995 [ERROR] [org.gradle.internal.buildevents.BuildExceptionReporter] 
15:09:13.995 [ERROR] [org.gradle.internal.buildevents.BuildExceptionReporter] * What went wrong:
15:09:13.995 [ERROR] [org.gradle.internal.buildevents.BuildExceptionReporter] Execution failed for task ':app:transformClassesAndResourcesWithR8ForRelease'.
15:09:13.995 [ERROR] [org.gradle.internal.buildevents.BuildExceptionReporter] > java.lang.NullPointerException (no error message)

**Comment by qwwdfsad** [comment]
Please report it to R8 bug tracker
