### ISSUE TITLE
coroutine cooperatif cancelation

### ISSUE THREAD

**Issue by halimpuckjava** [Kotlin/kotlinx.coroutines#907]

**Comment by fvasco** [comment]
> whats wrong in my code ??

it is not formatted

**Comment by halimpuckjava** [comment]
val job = Job()
val scope by lazy { CoroutineScope(job) }
var result by Delegates.notNull<Long>()

suspend fun longCalcul() = (1..9999999999999).sum()

launchBtn.setOnAction {
   scope.launch {
         res = -1
         println("calcul....")
         withContext(Dispatchers.Default) {
                 while (job.isActive) {
                         res = longCalcul()
                }
       }
       println("result: $res")
   }.invokeOnCompletion { runOnCompletion(it) }
}


fun runOnCompletion(exception: Throwable?) {
     when (exception) {
          null -> println("complete with success")
          else -> println("complete with exeception: ${exception.message}")
     }
}


canceBtn.setOnAction {
    job.cancel()
}


so my issue is when in click on 'cancelBtn' noting happen (corutine still execute my long calcul until finish and display exception on teeminate) 

1. whats wrong (coroutine still running after cancelation) ??
2. how to fix taht (cancel coroutine immediatly)

**Comment by fvasco** [comment]
https://github.com/Kotlin/kotlinx.coroutines/blob/master/docs/cancellation-and-timeouts.md

**Comment by qwwdfsad** [comment]
https://github.com/Kotlin/kotlinx.coroutines/blob/master/docs/cancellation-and-timeouts.md#cancellation-is-cooperative here is an explanation why it happens.
