### ISSUE TITLE
[Question] async can or can not be replaced with withContext(Dispatchers.Default) when run from coroutine scope

### ISSUE THREAD

**Issue by filipkowicz** [Kotlin/kotlinx.coroutines#909]
Android Studio (ver 3.2) propose me to replace all `async { ... }.await()` statements with `withContext(Dispatchers.Default){ ... }` .
As far as I understand since call is done within CoroutineScope object, coroutine context should be used in first example what makes this "hint" wrong because with it body of async will be executed on Default Dispatcher instead of one defined in CoroutineContext after change. Am I correct ?
if so who is responsible of providing such hints? where should i file issue?

correct replacement will be `withContext(coroutineContext)` as I understand

**Comment by qwwdfsad** [comment]
From the formal point of view yes, this is not an equivalent replacement.

But in fact, this is a hint that you are doing something wrong.
`async` uses either dispatcher from the current scope context or (if it is not present), default one.

In the first case, usage of the `async` is meaningless: `async { block() }.await()` is more or less the same as `block()`. And thus "proper" replacement with `withContext(coroutineContext)` carries no value as well. And if you need a nested scope, than `coroutineScope` should be used, not a `withContext(coroutineContext)`.

In the second case, the proper replacement is `withContext(Dispatchers.Default)`.
So inspection assumes that the second case is far more frequent than the first one and makes a corresponding replacement.

**Comment by filipkowicz** [comment]
thanks for answer

what would be correct way of handling this case:

```
class X : CoroutineScope {
    override val coroutineContext = CONTEXT_NEEDED_FOR_ALL_ACTIONS_IN_THIS_CLASS

   public suspend fun doSomethingInXScope() : SomeReturnValue{
       // I want to be sure that all code executed here will be done with coroutineContext from X class and I need to wait until its done because function needs to return value
   }
}
```

my current usecase is: Above class will be used to access database which could be accessed only from one thread -> so I'm creating coroutineContext with singleThreadDispatcher and want to execute all code within this scope

**Comment by qwwdfsad** [comment]
In that case it is better not to implement `CoroutineScope`. `CoroutineScope` is mostly about lifecycle, while what you are looking for is changing the context.

I would implement it like this:

```
class X {
   // Don't forget that thread-pool dispatcher should be closed manually
   private val dispatcher = singleThreadDispatcher(...)
   
   public suspend fun fetchSomething(): SomeReturnValue = withContext(dispatcher) {
     
   }
}


```

**Comment by filipkowicz** [comment]
thanks, will go this way.
closing then
