### ISSUE TITLE
invokeSuspend throws NullPointer while minifyEnabled is true

### ISSUE THREAD

**Issue by tRuNKator** [Kotlin/kotlinx.coroutines#910]
Hello, I used version 1.0.1, but found a problem when exceptions were not processed if the coroutine was canceled [(same issue(fixed in new version)).](https://github.com/Kotlin/kotlinx.coroutines/issues/875) Now I have updated the version to 1.1.0-alpha. And again I ran into another problem. Such code:
MainActivity.kt
```
class MainActivity : AppCompatActivity() {
    override fun onCreate(savedInstanceState: Bundle?) {
        super.onCreate(savedInstanceState)
        setContentView(R.layout.activity_main)
        GlobalScope.launch {
            val result = safeApiCall { doDelay() }
            println(result)
        }
    }

    suspend fun doDelay(): Boolean {
        delay(2000)
        return true
    }
}
```

Utils.kt:

```
suspend fun safeApiCall(call: suspend () -> Boolean): Boolean {
    return try {
        call()
    } catch (throwable: Throwable) {
        false
    }
}
```

Generates such code for Utils.kt (see on last line):
```
.method public final invokeSuspend(Ljava/lang/Object;)Ljava/lang/Object;
    .registers 3
    .param p1    # Ljava/lang/Object;
        .annotation build Lorg/jetbrains/annotations/NotNull;
        .end annotation
    .end param
    .annotation build Lorg/jetbrains/annotations/Nullable;
    .end annotation

    iput-object p1, p0, Lcom/example/myapplication/UtilsKt$safeApiCall$1;->result:Ljava/lang/Object;
    iget p1, p0, Lcom/example/myapplication/UtilsKt$safeApiCall$1;->label:I
    const/high16 v0, -0x80000000
    or-int/2addr p1, v0
    iput p1, p0, Lcom/example/myapplication/UtilsKt$safeApiCall$1;->label:I
    const/4 p1, 0x0

    throw p1
.end method
```

Even with this rules:
```
-dontobfuscate
-dontoptimize
-dontnote
-dontobfuscate
-dontoptimize
-dontpreverify
-dontshrink
```

AS 3.4 Canary 9, android gradle plugin ver 3.4.0-alpha09, kotlin version 1.3.11

**Comment by qwwdfsad** [comment]
It is a bug in minifier, we can't fix it from `kotlinx.coroutines`.
Please report it to R8

**Comment by Pulimet** [comment]
https://issuetracker.google.com/issues/121345586

**Comment by tRuNKator** [comment]
> 
> 
> @tRuNKator , R8 team fixed the issue, but how can I use the version with this fix?
> We need to wait for next gradle tools version and it will include R8 version with the fix? Or there is other way to set it manually?
> Thanks.

You can apply new version manually. But I do not know if this fix entered this version.
`
buildscript {
    repositories {
        google()
        jcenter()
        mavenCentral()
        maven { url "http://storage.googleapis.com/r8-releases/raw/" }
    }

    dependencies {
        classpath 'com.android.tools:r8:1.4.25'  // Must be before the Gradle Plugin for Android.
        classpath "com.android.tools.build:gradle:androidGradlePluginVersion"
    }
}
`

**Comment by Cililing** [comment]
Hi, I have the same problem.
But in my case I am not able to use R8 - very old project that is based on experimental plugin (0.11.0), and there is no way that someone will rewrite ours build scripts.

So, no chance to use R8, but in "normal" proguard bug also exists.
Is there any way to fix that? Thanks.

**Comment by elizarov** [comment]
You can work around by turning off minification or tweaking minification settings. I'm not sure there's anything more we can help with.
