### ISSUE TITLE
What does it mean in Actors Section? 

### ISSUE THREAD

**Issue by RayCZ** [Kotlin/kotlinx.coroutines#911]
https://github.com/Kotlin/kotlinx.coroutines/blob/master/docs/shared-mutable-state-and-concurrency.md

In this section :
There is an actor coroutine builder that conveniently combines actor's mailbox channel into its scope to receive messages from and combines the send channel into the resulting job object, so that a single reference to the actor can be carried around as its handle.

I can't read and understand the English grammar. What does it mean? Can you explain it in a simple way?

**Comment by qwwdfsad** [comment]
Please use our slack channel for general questions
