### ISSUE TITLE
Readme or deployment issue, 1.1.0 is not found on mavenCentral

### ISSUE THREAD

**Issue by westonal** [Kotlin/kotlinx.coroutines#913]
Readme reads:

> Make sure that you have either jcenter() or mavenCentral() in the list of repositories:

But if I have just `mavenCentral` I could not resolve the dependency 1.1.0 core.

**Comment by qwwdfsad** [comment]
Sadly, sync to maven central takes a while. Its timings are unpredictable, usually from 30 minutes to 8 hours

**Comment by qwwdfsad** [comment]
https://repo1.maven.org/maven2/org/jetbrains/kotlinx/kotlinx-coroutines-core-common/1.1.0/

It is there, so I am closing this issue
