### ISSUE TITLE
`Delay` function throws TypeCastException.

### ISSUE THREAD

**Issue by horita-yuya** [Kotlin/kotlinx.coroutines#920]
The `delay` suspend function throws TypeCastException when called from Swift.

The Condition.
- preparing CoroutineDispatcher for main queue.
- launch coroutines using the dispatcher.

I prepared self-containing repository here.
https://github.com/horita-yuya/TempKotlinNativeReport
kotlinx.coroutines version: 1.1.0

**Comment by uncledoc** [comment]
The same problem but I think problem is in `GlobalScope`. My steps to reproduce:
**1.** Create multiplatform project for Android and iOS
**2.** Add dependencies `org.jetbrains.kotlinx:kotlinx-coroutines-core-common:1.1.0`, `org.jetbrains.kotlinx:kotlinx-coroutines-android:1.1.0` and `org.jetbrains.kotlinx:kotlinx-coroutines-core-native:1.1.0`
**3.** Write a simple function in common or iOS module with body `GlobalScope.launch {
       // some code or empty
    }`
**4.** Try to call function in swift from iOS app

p.s. macos 10.14.2, xcode 10.1

**Comment by horita-yuya** [comment]
I see. Thank you.

**Comment by ildarsharafutdinov** [comment]
Having that I have an mpp framework which uses coroutines, what is the right way to "start event loop" on iOS?

Is the following ok?

```
// somewhere in framework

fun appMain(mainBlock: () -> Unit) = runBlocking {
    mainBlock()
}
```

```
// main.m

int main(int argc, char * argv[]) {
    [MppKt appMainMainBlock:^MppKotlinUnit * {
    
        @autoreleasepool {
             result = UIApplicationMain(argc, argv, nil, @"MyAppDelegate");
        }
        return NULL;
    }];
}
```

**Comment by pardom** [comment]
>An actual exception should be kotlin.IllegalStateException: There is no event loop. Use runBlocking { ... } to start one. because dispatcher does not implement Delay interface.

Given this restriction, how should I approach using this JVM/Native API while also supporting JS targets? Should I wrap my API with and `expect`/`actual`?

**Comment by pardom** [comment]
Not sure if this is my issue exactly, but I was linked here from https://github.com/JetBrains/kotlin-native/issues/2752 in response to a bug manifested in https://github.com/pardom/oolong/pull/16. The project does not call `delay` as @qwwdfsad mentions above, but it also doesn't call `runBlocking` because I have no need to block and I also want to support all platforms.

**Comment by elizarov** [comment]
@pardom You don't need to block if you are using coroutines on the main (UI) thread in iOS, but you'll need to write the corresponding dispatcher. See here: #470 Does it help?
