### ISSUE TITLE
AbstractContinuation is logging sensitive information

### ISSUE THREAD

**Issue by AllanWang** [Kotlin/kotlinx.coroutines#926]
(Note that this is with 1.0.1; I'm not sure if this has changed or not)

I have an error report that points to AbstractContinuation, with the error: "Already resumed, but proposed with update %s". A quick google search indicates that the code may have moved, but the last commit is referenced [here](https://github.com/Kotlin/kotlinx.coroutines/blob/db5335a8d68e730010bbf0a6678ed63adad45049/common/kotlinx-coroutines-core-common/src/AbstractContinuation.kt#L192).

The generated IllegalStateException seems to be logging an input or output, which is extremely sensitive. I'm using BugSnag, which posts snippets of bug reports into my public github repo. Can we please avoid printing any variable in exceptions implicitly? Perhaps at least switch it to logging only the class name.

If something else is going on, please let me know. The code in question involves me storing a global reference to a continuation and resuming it later. My guess is that it was resumed twice, though I don't know why it isn't marked as completed or cancelled by then.

---

For reference, a unit test that calls `resume` twice produces the following:

```
java.lang.IllegalStateException: Already resumed

	at kotlin.coroutines.SafeContinuation.resumeWith(SafeContinuationJvm.kt:46)
	...
```

With no mention of the propagated value.

The log I face is

```
java.lang.IllegalStateException: Already resumed, but proposed with update [printed data class, which ended up exposing every field]
        at kotlinx.coroutines.AbstractContinuation.initParentJobInternal$kotlinx_coroutines_core(AbstractContinuation.kt:210)
        at kotlinx.coroutines.AbstractContinuation.cancelImpl(AbstractContinuation.kt:210)
        at kotlinx.coroutines.AbstractContinuation.invokeOnCancellation(AbstractContinuation.kt:210)
        at kotlinx.coroutines.AbstractContinuation.resumeImpl(AbstractContinuation.kt:210)
        at kotlinx.coroutines.AbstractContinuation.resumeWith(AbstractContinuation.kt:141)
```

I also realize by now that I should have probably used CompletableDeferred

**Comment by qwwdfsad** [comment]
This behaviour is slightly changed in 1.1.0: this code path is now not invoked on resume + cancel (which is AFAIK 99% of all exception handling in `AbstractContinuation`).
But this behaviour is still preserved if you call `resume` more than once though.

>Can we please avoid printing any variable in exceptions implicitly? 

No. This behaviour is desired and printing proposed and the current state is essential for post-mortems and debugging. Your use-case is pretty rare and we can't afford to make the general user-experience worse. 

You can set up your own `CoroutineExceptionHandler` and exclude all sensitive information from there.
