### ISSUE TITLE
Suggestion: Scoped(multi-scope) Coroutines

### ISSUE THREAD

**Issue by antanas-arvasevicius** [Kotlin/kotlinx.coroutines#927]
Hi, I've read interesting blog post about how monads and its compositions can be expressed with coroutines only - http://blog.paralleluniverse.co/2015/08/07/scoped-continuations/

As I understood post talks about how coroutines can be used to chain/compose monad usages.
One real example would be: database access and async task. Now in ktor if we want to use transactional database queries correctly we need explicitly pass transaction managers to all suspend functions which is created in route action closure. I'm thinking maybe we could set that transaction manager inside coroutineContext`s property and use that transaction manager in all suspend functions implicitly by reading it from coroutineContext. But would be great that type system would support some checking. For example:
```kotlin
    suspend<DbTransaction> fun queryDatabase() = coroutineScope {
        val dbTransaction = coroutineContext[DbTransactionKey]
    }
    suspend<DbTransaction, CurrentUser> fun doPurchase() = coroutineScope {
        val dbTransaction = coroutineContext[DbTransactionKey]
        val currentUser = coroutineContext[CurrentUserKey]
    }

// to create scope with some coroutine builder
   fun withDatabaseTransaction(dbTransaction, block) = async<DbTransaction> {
      coroutineContext[DbTransactionKey] = dbTransaction
      block()
  }
   fun withCurrentUser(currentUser, block) = async<CurrentUser> {
      coroutineContext[CurrentUserKey] = dbTransaction
      block()
  }

// usage:
   fun httpRouteAction(request) {
       withDatabaseTransaction(db) {
             withCurrentUser(request.authUser) {
                  someAsyncFunctionWhichUseesDoPurchaseSomewhereDeep()
             }
       } 
   }
```

As of writing I understand that type system probably couldn't determine if call site is inside both scopes during compilation and maybe this is more of implicitly imported variables not coroutines, but I'm interested of practices and thoughts how to deal with a given situation. Thanks.

**Comment by fvasco** [comment]
> this is more of implicitly imported variables not coroutines

I agree, how do you fix this issue without coroutine but using regular blocking functions?

See here for _implicit_ discussion: https://github.com/Kotlin/KEEP/pull/87

**Comment by antanas-arvasevicius** [comment]
I think type classes is not exactly what I mean, more like Scala implicit, and upcoming in Dotty Implicit Function Types - https://www.scala-lang.org/blog/2016/12/07/implicit-function-types.html

**Comment by antanas-arvasevicius** [comment]
Yeah, I've misunderstood article. After careful reading an article several
times now hopefully understand what is about.

Main point that coroutines can have a scope on which they run (I think in
kotlin would be aka Dispatchers), but what noted in post that suspend fun
declarations should denote what scopes(dispatchers) it is needed to run
correctly. And as understand coroutines suspends only in its scope and
multiple scopes suspends independently. Is these patterns currently
supported in kotlin? And maybe someone find insights from that article,
just want that kotlin coroutines won't be missing something fundamentally
important :)

**Comment by fvasco** [comment]
I suspect that you are confusing `CoroutineScope` and `CoroutineDispatcher`, moreover Kotlin coroutine does not require none of both.

So that

> coroutines suspends only in its scope

coroutine suspend with or without the scope

> multiple scopes suspends independently

scope does not suspend

Please consider to review your knowledge base, take a look to Kotlin language foundamentals, I strongly suggest this document: https://github.com/Kotlin/KEEP/blob/master/proposals/coroutines.md

Regarding the original (pretty unclear) issue, it does not look related to coroutine in any way.

**Comment by antanas-arvasevicius** [comment]
Yes I'm not confident enought to talk about these concepts, and my first
example was wrong (about variables in coroutine context). You need to
follow a blog post.
 I've noticed that it writes about how coroutines can replace all monad
structures and free developers of monad transformers when different monads
needs to be composed that's why I'm created issue to someone advanced in
kotlins coroutine implementation evaluate that.

By reading more now as I understood blog post talks about delimited
continuation vs delimited continuations with multiple (named) prompts

Do kotlin supports multi prompt continuations? If not, are you planning to
support it?

Theory and use about this:
http://ix.cs.uoregon.edu/~ariola/systematic-multiple-control.pdf

**Comment by qwwdfsad** [comment]
> And as understand coroutines suspends only in its scope and
multiple scopes suspends independently. Is these patterns currently
supported in kotlin?

No. They can be **partially** emulated with a receiver and `@RestrictSuspension`, which is enough for most of the cases.  E.g. take a look how `sequence` builder is implemented.

Type system does not support suspension context restriction further than that and there are no plans to do that.

**Comment by elizarov** [comment]
It is a nice article (and the accompanying talk), but I don't see much pragmatic value in the concept of this kind of delimited (and/or scoped) continuations. Regular function parameters and receiver types in Kotlin address the need to represent the context required for the function call in its type quite well. I don't see why would we need yet another mechanism to the same goal. Frankly, I don't see how: 

```
suspend<DbTransaction> fun queryDatabase()
```

is better than (just as one example to write it):

```
suspend fun DbTransaction.queryDatabase()
```

However, if you've got interested in `shift`/`reset`-style delimited continuations, then you are welcome to study and use the implementation from this gist which is completely type-safe and actually represents a variant of scoped continuation implementation (the scope is in the receiver position): https://gist.github.com/elizarov/5bbbe5a3b88985ae577d8ec3706e85ef

**Comment by elizarov** [comment]
My implementation of `shift`/`reset` is  _delimited_ (which implies that it has _multiple-prompts_). The reference to `DelimitedScope` that `reset` provides to the inner block is its _prompt tag_. The  `shift` if invoked on a particular `DelimitedScope` instance and that determines which "slice of execution stack" is captured and suspended at this point.

However, this has little pragmatic use for a language like Kotlin, since any concept that might possible to implement via delimited continuation is otherwise purely functional language is already supported by Kotlin natively, naturally, efficient. There is little need to reimplement them via delimited continuations.
