### ISSUE TITLE
Mutex.withLock uses owner parameter for checks but doesn't state equality contract in docs

### ISSUE THREAD

**Issue by baltiyskiy** [Kotlin/kotlinx.coroutines#940]
`Mutex.withLock()` states that `owner` is an "optional owner token for debugging". However, it really uses it for consistency checks, e.g. `curOwner !== owner` in `lockSuspend`. This means that `owner` must be unique for each invocation of `withLock()`, otherwise one will get a cryptic `IllegalStateException: Already locked by <owner>`. The problem is that this contract isn't stated in the docs. Another problem is that using a debugging token for consistency checks doesn't look like a good idea.

**Comment by elizarov** [comment]
So what change do you propose to make?

**Comment by baltiyskiy** [comment]
Either update the docs to state that `owner` must be unique for each invocation, or don't use it for consistency checks

**Comment by qwwdfsad** [comment]
>This means that owner must be unique for each invocation of withLock()

It does not. It should be unique for overlapping concurrent operations.

>Either update the docs to state that owner must be unique for each concurrent invocation

Actually, `withLock` was the only method where this limitation has not been noticed
