### ISSUE TITLE
Cancel on Job doesn't cancel scope, if Dispatcher context was overwritten

### ISSUE THREAD

**Issue by Coneys** [Kotlin/kotlinx.coroutines#942]
I use coroutines for any asyn action in my applications, but also I wanted to test my classes, so I wrote small abstraction for Dispatchers:
```
object DispatcherProvider {
    var IO: CoroutineContext = Dispatchers.IO
        private set
    var Main: CoroutineContext = Dispatchers.Main
        private set
    var Default: CoroutineContext = Dispatchers.Default
        private set

    fun enableTesting(coroutineScope: CoroutineScope) {

        IO = coroutineScope.coroutineContext
        Main = coroutineScope.coroutineContext
        Default = coroutineScope.coroutineContext
    }

}
```
In tests I just use it like this: 
```
 runBlocking {
                DispatcherProvider.enableTesting(this)
           // code that call classes which are using Coroutines
            }
// all async code will be done here
```
Everything worked well, but recently I had to test class, which implemented CoroutineScope:
```
class SomeClass():CoroutineScope{

    private val scopeJob by lazy { Job() }
    override val coroutineContext: CoroutineContext by lazy { DispatcherProvider.Main + scopeJob }
    
    fun release(){
        scopeJob.cancel()
    }
}
```
In my tests when I called cancel on scopeJob, scope was still active, and none of async call were stopped. I'm not sure if it is a bug, or I just don't understand something, but I hope someone can help me. 
btw. coroutines rocks!

**Comment by qwwdfsad** [comment]
Could you please elaborate what do you mean but "scope is not cancelled"?

Please provide a self-contained snippet and describe what is not working as expected.
Also, I'd recommend using `cancel` on the scope itself since 1.1.0:
```
class SomeClass() : CoroutineScope {
    
    override val coroutineContext: CoroutineContext by lazy { DispatcherProvider.Main + Job() }

    fun release() {
        cancel()
    }
}
```

**Comment by Coneys** [comment]
Thanks for your answer! I was referring to [Chris Banes talk](https://www.youtube.com/watch?v=P7ov_r1JZ1g&t=1130s) about Android Suspenders, where he showed how to use CoroutineScope and he did cancel it with "job.cancel()"

By "scope is not cancelled" I ment, that "isActive" flag is set to true. Whole example (DispatcherProvider is the class from my first comment:

1. SomeClass 
```
class SomeClass() : CoroutineScope {

    var wasCancelled = false
    private val scopeJob by lazy { Job() }
    override val coroutineContext: CoroutineContext by lazy { DispatcherProvider.Main + scopeJob }

    fun runCoroutine() {
        launch(DispatcherProvider.IO) {
            for (i in 0..10) {
                if (!isActive) {
                    println("Coroutine was cancelled")
                    wasCancelled = true
                    break
                }
                println("In for loop $i")
                delay(100)
            }
            println("Finished with $isActive")
        }
    }

    fun release() {
        scopeJob.cancel()
    }
}
```

2.SomeTest
```
class SomeTest {


    @Test
    fun test() {
        val someClass = SomeClass()

        runBlocking {
            DispatcherProvider.enableTesting(this)
            someClass.runCoroutine()
            delay(50)
            println("Calling release")
            someClass.release()
        }
        assert(someClass.wasCancelled)

    }
}
```
Console output after running test:
In for loop 0
Calling release
In for loop 1
In for loop 2
In for loop 3
In for loop 4
In for loop 5
In for loop 6
In for loop 7
In for loop 8
In for loop 9
In for loop 10
Finished with true

java.lang.AssertionError: Assertion failed

As you can see, after calling release my scope still "isActive". Did I understand Chris wrong? Cancelling job doesn't cancel scope? If so, why do we need this job anyway?

**Comment by Coneys** [comment]
I tested it with executing cancel() on scope itself, but outcome is the same

**Comment by qwwdfsad** [comment]
The problem lies in the fact, that you overwrite Job in your scope.

When you call `enableTesting`, you are not only overwriting dispatcher, but you also take a `runBlocking`'s job.


The proper solution is to capture only dispatchers:
```
fun enableTesting(coroutineScope: CoroutineScope) {
  IO = coroutineScope.coroutineContext[ContinuationInterceptor]!!
  Main = coroutineScope.coroutineContext[ContinuationInterceptor]!! 
  Default = coroutineScope.coroutineContext[ContinuationInterceptor]!!
}
```

**Comment by jemshit** [comment]
Hi, i have this observation and i don't understand the behavior. This is `CoroutineScope`:
```
A:CoroutineScope {
    protected lateinit var job: Job
    override val coroutineContext: CoroutineContext
        get() = job + Dispatchers.Main
}
```

Observation 1:
```
launch{
    withContext(Dispatchers.Default){
        // some heavy job
    }
    // While doing some heavy `job.cancel()` is called
    println("$isActive, ${this@A.job.isActive}, ${coroutineContext[Job]?.isActive}")
    // prints true, false, true
}
```

Observation 2:
```
launch{
    withContext(Dispatchers.Default + this@A.job){
        // some heavy job
    }
    // While doing some heavy `job.cancel()` is called
    println("$isActive, ${this@A.job.isActive}, ${coroutineContext[Job]?.isActive}")
    // prints true, true, true
}
```

`CoroutineScope.job` **is not** active after `job.cancel()`, but `CoroutineScope` **is** active. Both `job` and `CoroutineScope` **is** active when `withContext(Dispatchers.Default + job)` is used. Could any one explain this? My aim is to cancel parent job in CoroutineScope and everything inside it (like withContext). But `if(isActive)` does not behave as expected

**Comment by yazansayed** [comment]
I just call `delay(5)` after cancelling, to allow time for cancellation i guess

**Comment by EarthyOrange** [comment]
@jemshit I ran into something similar recently when I tried to do something as follows:
```
val job = CoroutineScope(Dispatcher.IO).launch {
  while (this.isActive) { // this is CoroutineScope
    // Do something...
  }
}
```

Then at a later point do:
```
job.cancel()
```

It cancels the job but it doesn't set the CoroutineScope.isActive to false. So my job still kept doing something. I ended up fixing this by:
 - wrapping job in an object
 - have an isActive flag in this object which is used in the while loop
 - have a cancel method that sets this flag to false and cancels the job

I am sure that there is a better approach. 

But having given it a thought I don't think the CoroutineScope isActive flag should be changed or used here because:
 - There can be several jobs, of the same generation, attached to the scope. Cancelling one job shouldn't effect other jobs in the same generation.
 - If one such job is cancelled (sets isActive to false) and another new job begins (sets isActive to true) before the former has the chance to check the isActive flag then an erroneous situation will be created.

**Comment by dkhalanskyjb** [comment]
@EarthyOrange, I couldn't reproduce the behavior you describe.
```
        val job = CoroutineScope(Dispatchers.IO).launch {
            while (this.isActive) { // this is CoroutineScope
                println("going to sleep...")
                Thread.sleep(100)
            }
        }
        println("Cancelling")
        job.cancel()
        println("Cancelled")
        Thread.sleep(10000)
```
For me, this prints `going to sleep...` only once.
