### ISSUE TITLE
Make debug module Android-compatible

### ISSUE THREAD

**Issue by LouisCAD** [Kotlin/kotlinx.coroutines#948]
~Here's a permalink to the target doc: https://github.com/Kotlin/kotlinx.coroutines/blob/8f1c728bade0416037793900355de31e064a1dae/core/kotlinx-coroutines-debug/README.md~

**UPDATE**: Note that the most recent version of documentation mentions Android incompatibility. See: https://github.com/Kotlin/kotlinx.coroutines/blob/master/kotlinx-coroutines-debug/README.md#debug-agent-and-android

Leaving this issue open as a change request for future support of Android on-device debugging.

**Comment by Mygod** [comment]
So how are we supposed to debug deadlocks on Android?

**Comment by elizarov** [comment]
You can write unit / integration tests and debug your logic with them.

**Comment by Mygod** [comment]
So I need to write (AND keep) two copies of my logic just to debug deadlocks?

**Comment by elizarov** [comment]
We don't have a good answer yet.

**Comment by Mygod** [comment]
Any reasons we need to use `Ljava/lang/management/ManagementFactory`? I don't see android-gradle-aspectj updating any time soon.

**Comment by elizarov** [comment]
On JVM we can inject debugger into running code. This is done via `ManagementFactory`. On Android this is not possible. We need to weave the corresponding debug code into the `kotlin-stdlib.jar` before it gets dexed and put onto device. Weaving itself is quite easy (we just need to replace a few methods), but maintaining the corresponding gradle plugin is not -- we don't have time at the moment. If somebody can contribute Android-compatible gradle plugin that we can use to weave our debugging aspect that would be great.

**Comment by Mygod** [comment]
Can't kotlin-stdlib have hooks or something to make this compatible?

**Comment by elizarov** [comment]
kotlin-stdlib _has_ special debug hook, but they are static -- to use those hook you must rewire a specifically designed class inside kotlin-stdlib. You don't even need AOP framework for that. You can simply replace the corresponding class. On JVM we can do it at run-time. On Android it has to be a part of dexing toolchain.

The trick is that we need to maintain Gradle plugin that does this reliably and is tested and integrated with Android toolchain. And that is quite painful.

**Comment by Mygod** [comment]
What I was thinking is that maybe we can update kotlin-stdlib and relax the restrictions on the debug hook so that we can do this without using `ManagementFactory` nor gradle plugin dexing. I am not sure how exactly things go under the hood but I think this should work.

**Comment by elizarov** [comment]
The is no good make to make it work in a reliable and module way -- we cannot use `ServiceLoader` in `kotlin-stdlib`, we cannot hard-code `kotlinx.coroutines` class names there either, and we cannot make this hook dynamic -- it has to be static for performance reasons.

**Comment by Mygod** [comment]
For performance issues, can we do something like build variants that disables the dynamic hook for release builds?

**Comment by elizarov** [comment]
That is exactly why we need Gradle plugin on Android. We need it to hook a special "debug-enabled" (appropriately patched) version of `kotlin-stdlib` when building a debug version of application.

**Comment by LouisCAD** [comment]
Is this planned anytime soon?
I have a channel closed exception crashing my app that I struggle a lot to debug. This would be very helpful.

**Comment by eric-labelle** [comment]
> **UPDATE**: Note that the most recent version of documentation mentions Android incompatibility. See: https://github.com/Kotlin/kotlinx.coroutines/blob/master/kotlinx-coroutines-debug/README.md#debug-agent-and-android

It is also mentioned that it will be possible when AGP 3.3 will be supported (they actually stated it support up to `Actual version supporting of AGP 3.6.+`
> Nevertheless, it will be possible to support debug agent on Android as soon as GradleAspectJ-Android will support android-gradle 3.3

So what is the current status on this?

**Comment by qwwdfsad** [comment]
We decided not to implement this request ourselves.
Google has work-in-progress and is planning to provide coroutines debugging support in one of the upcoming versions of Android Studio

**Comment by LikeTheSalad** [comment]
Do you guys think that instead of AspectJ you could use Byte Buddy on Android with https://github.com/LikeTheSalad/android-buddy instead?
