### ISSUE TITLE
Drop a deprecated version of ReceiveChannel.cancel

### ISSUE THREAD

**Issue by elizarov** [Kotlin/kotlinx.coroutines#956]
It causes problems with Java reflection (because there is another void version of it) as reported by Rafael Winterhalter in twitter: https://twitter.com/rafaelcodes/status/1089857906126790656

‏

**Comment by oleksiyp** [comment]
Oh, very nice that it was done before 1.0 and can be dropped... I was afraid it will be never fixed. And it is needed for mocking `Channel`

**Comment by erikhuizinga** [comment]
@oleksiyp you referenced some other issues in my original report. Can you reference from there to this issue, as this will probably close them too?

**Comment by qwwdfsad** [comment]
The issue was fixed in 27b8f45803455125cddf99b3f03c0ea37e3c55e8
