### ISSUE TITLE
withTimeout does not work with CoroutineExceptionHandler?

### ISSUE THREAD

**Issue by Mygod** [Kotlin/kotlinx.coroutines#961]
Code to reproduce: (tested on Android)

```
@Test
fun checkThisOut()
    val scope = object : CoroutineScope {
        override val coroutineContext get() = Dispatchers.Default +
            CoroutineExceptionHandler { _, t -> Log.w("BLAH", t) }
    }
    scope.launch {
        withTimeout(1000) { delay(5000) }
    }
    runBlocking { scope.job.join() }
}
```

The coroutine was timed out but no output was found.

**Comment by qwwdfsad** [comment]
Cancellation exceptions are not reported to the exception handler.
Timeout exception is cancellation exception

**Comment by qwwdfsad** [comment]
No, `withTimeout` exception can only be caught with `catch` block, it is not passed to exception handler
