### ISSUE TITLE
Add checkCancelled() extension for Job / CoroutineContext / CoroutineScope

### ISSUE THREAD

**Issue by abusalimov** [Kotlin/kotlinx.coroutines#963]
Something like:
```kt
fun CoroutineContext.checkCancelled() {
    if (this[Job]?.isCancelled == true) throw job.getCancellationException()
}
```

AFAIK, currently the only way to explicitly check coroutine shall still proceed (at the same time throwing a proper CancellationException with a proper stack trace) is to invoke `yield()`, which has a check similar to the suggested one, yet marked `internal`: https://github.com/Kotlin/kotlinx.coroutines/blob/f62acb6835fb5001f9b52602ebf73a60088d1e4c/common/kotlinx-coroutines-core-common/src/Yield.kt#L29-L32
(`Job.isCancelled` is equivalent to `!Job.isActive` when the coroutine checks that itself).

The suggestion is to expose such extension functions for `Job`, `CoroutineContext`, `CoroutineScope` (similarly to `isActive` and `cancel()`).

**Comment by elizarov** [comment]
What use-case do you envision for this function? Can you given an example code that uses this function, please.

**Comment by abusalimov** [comment]
```kt
  private suspend fun <R> doExecuteCommand(command: DebuggerCommand<R>,
                                           canExecuteWhileRunning: Boolean): R {
    val expirationJob =
      if (canExecuteWhileRunning) supervisorJob
      else createSessionSuspendedSupervisorJob()
    expirationJob.checkCancelled()  // don't run if the supervisor has expired already

    return withContext(coroutineDispatcher) {
      expirationJob.cancelJobOnCompletion(coroutineContext[Job]!!)
      checkCancelled()  // check again

      command.call(this.driver)
    }
  }

  companion object {
    @Throws(CancellationException::class)
    internal fun Job.checkCancelled() {
      if (!isActive) {
        @Suppress("EXPERIMENTAL_IS_NOT_ENABLED")
        @UseExperimental(InternalCoroutinesApi::class)  // need to get rid of this
        throw getCancellationException()
      }
    }
  }

```
