### ISSUE TITLE
This declaration is experimental and its usage should be marked with '@kotlin.coroutines.ObsoleteCoroutineApi'

### ISSUE THREAD

**Issue by pauliusrum** [Kotlin/kotlinx.coroutines#976]
Hello,

I have added kotlin experimental features compiler flag to my gradle.build but i still get the warning shown in idea. What i am doing wrong?

```
  compileKotlin {
        kotlinOptions.freeCompilerArgs += ['-Xuse-experimental=kotlinx.coroutines.ObsoleteCoroutinesApi']
    }
```

**Comment by elizarov** [comment]
Did you reimport your Gradle project into IDEA?

**Comment by pauliusrum** [comment]
Yes. This happened after i updated kotlin to `1.3.20` and the  kotlin compiler plugin.

**Comment by pauliusrum** [comment]
We also have a multiplatform project with these settings:
```
all {
            languageSettings {
                useExperimentalAnnotation 'kotlin.contracts.ExperimentalContracts'
                useExperimentalAnnotation 'kotlinx.coroutines.ExperimentalCoroutinesApi'
                useExperimentalAnnotation 'kotlinx.coroutines.ObsoleteCoroutinesApi'
                useExperimentalAnnotation 'kotlinx.serialization.ImplicitReflectionSerializer'
            }
     }
```

In that project the idea will not shown the warnings anymore.

**Comment by elizarov** [comment]
Can you share some more details? I cannot reproduce it with 1.3.20 on the minimal test that I have.

**Comment by pauliusrum** [comment]
gradle.build:
```gradle
plugins {
    id 'java'
    id 'org.jetbrains.kotlin.jvm' version '1.3.21'
}

group 'example'
version '1.0-SNAPSHOT'

sourceCompatibility = 1.8

repositories {
    mavenCentral()
    jcenter()
}

dependencies {
    implementation "org.jetbrains.kotlin:kotlin-stdlib-jdk8"
    implementation "org.jetbrains.kotlinx:kotlinx-serialization-runtime:0.10.0"
    implementation "org.jetbrains.kotlinx:kotlinx-coroutines-core:1.1.1"
}

compileKotlin {
    kotlinOptions.jvmTarget = "1.8"
    kotlinOptions.freeCompilerArgs = ['-Xuse-experimental=kotlinx.serialization.ImplicitReflectionSerializer,kotlinx.coroutines.ObsoleteCoroutinesApi']
}
```
main.kt
```kotlin
import kotlinx.coroutines.channels.Channel
import kotlinx.coroutines.channels.consumeEach
import kotlinx.coroutines.runBlocking

fun main() = runBlocking {
    Channel<Int>().consumeEach {  }
}
```
![image](https://user-images.githubusercontent.com/6652850/52405458-fba6f600-2ad3-11e9-8974-54568a3042d5.png)

**Comment by jcornaz** [comment]
@pauliusrum

Make sure to use `+=` instead of `=` each time you want to define compiler arguments with `freeCompilerArgs`. Otherwise one gradle script might override the compiler arguments set by another script.

**Comment by pauliusrum** [comment]
Removing this line from gradle.properties helped:
`kotlin.parallel.tasks.in.project=true`

**Comment by elizarov** [comment]
I've reported this issue to Kotlin gradle plugin: https://youtrack.jetbrains.com/issue/KT-29928

**Comment by evansgelist** [comment]
for me works like this
```
kotlinOptions {
            jvmTarget = "1.8"
            freeCompilerArgs += [
                    "-Xuse-experimental=kotlinx.coroutines.ExperimentalCoroutinesApi",
                    "-Xuse-experimental=kotlinx.coroutines.ObsoleteCoroutinesApi"]
        }
```

**Comment by farruhha** [comment]
@evansgelist , thanks. Your solution works like a charm.

**Comment by georrge1994** [comment]
> for me works like this
> 
> ```
> kotlinOptions {
>             jvmTarget = "1.8"
>             freeCompilerArgs += [
>                     "-Xuse-experimental=kotlinx.coroutines.ExperimentalCoroutinesApi",
>                     "-Xuse-experimental=kotlinx.coroutines.ObsoleteCoroutinesApi"]
>         }
> ```

It hidden the warnings from building result, but in the project  code warning still is lighting

**Comment by mochadwi** [comment]
`@since 1.3.70` use `-Xopt-in` to replace `-Xuse-experimental`

```
 // Groovy DSL
compileKotlin {
    kotlinOptions {
        jvmTarget = "1.8"
        freeCompilerArgs += [
                "-Xopt-in=kotlin.RequiresOptIn",
                "-Xopt-in=kotlin.OptIn"
        ]
    }
}
```

```
// Kotlin DSL
tasks.withType<KotlinCompile>().all {
    kotlinOptions.freeCompilerArgs += listOf(
                "-Xopt-in=kotlin.RequiresOptIn",
                "-Xopt-in=kotlin.OptIn"
    )
}
```

**Comment by ursusursus** [comment]
when I use what @mochadwi said, I get `> Task :texts:impl:compileDebugKotlin
w: Class kotlin.OptIn is not an opt-in requirement marker`˙. What does it mean? Is OptIn hooked up implicitly?

**Comment by KhaderMurtaja** [comment]
> for me works like this
> 
> ```
> kotlinOptions {
>             jvmTarget = "1.8"
>             freeCompilerArgs += [
>                     "-Xuse-experimental=kotlinx.coroutines.ExperimentalCoroutinesApi",
>                     "-Xuse-experimental=kotlinx.coroutines.ObsoleteCoroutinesApi"]
>         }
> ```

In which file within the FLutter application ??

**Comment by CHANDRAMOHANnegi** [comment]
Change to the distributionUrl in /android/gradle/wrapper/gradle-wrapper.properties fixed the issue for me.

distributionUrl=https://services.gradle.org/distributions/gradle-7.5.1-all.zip
