### ISSUE TITLE
Differentiate between child and parent cancellation

### ISSUE THREAD

**Issue by ansman** [Kotlin/kotlinx.coroutines#977]
Consider this example:
```kotlin
val job = cachedJob ?: GlobalScope.async { doSomething() }.also { cachedJob = it }
return job.await()
```
If someone calls `cachedJob.cancel()` while someone is waiting, `await` will throw a `CancellationException`. Currently there is no clean way to differentiate between this scenario and the scenario that the parent coroutine was cancelled.

One could check if the parent is still active but it would be nice if a different error was thrown when the child coroutine is cancelled vs the parent being cancelled.

**Comment by elizarov** [comment]
What is your actual use-case? Can you please elaborate a bit on what you are trying to achieve.

**Comment by ansman** [comment]
Say you are listening on a shared resource, that might be cancelled. If that happens you want to do some fallback behavior. Currently the only way to handle this is to catch `CancellationException` and check `isActive` which is ok I suppose but it would be nice if a subclass of `CancellationException` was thrown then the job that is being awaited was cancelled.

**Comment by elizarov** [comment]
You can use `Deferred.join()`. It does not rethrow the exception that was the completion reason of the job you are joining to. After that you can use `Deferred.getCompletionExceptionOrNull()` to learn if it had failed and what exception was the reason. See more here: https://kotlin.github.io/kotlinx.coroutines/kotlinx-coroutines-core/kotlinx.coroutines/-deferred/index.html

**Comment by elizarov** [comment]
I hope this helps. Closing this issue.
