### ISSUE TITLE
Re-add the common sources to platform sources jar

### ISSUE THREAD

**Issue by andreisilviudragnea** [Kotlin/kotlinx.coroutines#979]
The commit e1fa197ddef67768c1586328cbdb2e88c89a26f0 changed the directory layout of the project. This change reintroduced the bug in [KT-20971](https://youtrack.jetbrains.com/issue/KT-20971), which was initially fixed in commit 2bc0a1ba13bb2015c013a3429948e73218cce909.

There is a fix for this problem in #978.

**Comment by elizarov** [comment]
It seems to be fixed in the `develop` branch as a side effect of moving to Kotlin multiplatform plugin.
