### ISSUE TITLE
Async/await gets stuck when using context with single worker

### ISSUE THREAD

**Issue by Pitel** [Kotlin/kotlinx.coroutines#981]
I've a class which look like this:

```kotlin
class Foo: CoroutineScope {
  private val job = Job()
  override val coroutineContext = SINGLE + job // SINGLE might be Android's main, or newSingleThreadContext, it fails with both

  // I really tried it with somethiong this simple, and it's happening
  private val testAsync = async(start = CoroutineStart.LAZY) {
    println("XXX") // This never gets printed
    10
  }

  init {
    // stuff
    runBlocking {
      println("AAA") // This gets printed 
      println(testAsync.await()) // This does not, and nothing below this line gets executed
    }
    // more stuff (not happening)
  }
}
```

So there is the bug.

It's somehwere deep in my projects hierarchy, and I couldn't make reproducible jUnit test. Sorry.

Also note, that instead of `SINGLE`, we have this and we use it in whole project:
```kotlin
object CoroutineContextProvider {
	val UI = Dispatchers.Main
	val CPU = Dispatchers.Default
	val IO = Dispatchers.IO
}
```

And when I modify it for debugging purposes (to get rid of concurrency), so that `CPU` and `IO` shares the same `newSingleThreadContext("single")`, it starts happening. It's also happening when using `Main` for everything (Android app's UI get's stuck this way). When I use `newFixedThreadPoolContext(2, "fixed")`, it works normally and async's body gets called.

There is a [trace from Android Studio for download](https://github.com/Kotlin/kotlinx.coroutines/files/2855270/single-await.trace.gz), look at the `single` thread. And here is screenshot. It seems like the thread gets terminated.

![Trace](https://user-images.githubusercontent.com/113248/52628806-afcfc480-2eb8-11e9-8fc2-e020bd93d5a6.png)

Kotlin 1.3.21, Coroutines 1.1.1.

**Comment by Pitel** [comment]
Also note, then when I change `runBlocking` to `runBlocking(coroutineContext)`, not even the _AAA_ gets printed, it gets stuck right at the begining.

**Comment by elizarov** [comment]
I suspect that when you run your code in the single thread for test purposes, you happen to run your `runBlocking { ... }` code in this very thread. So, `runBlocking` calls correctly _blocks_ this sole thread and since this thread is blocked it cannot execute anything else, so it cannot execute your `async { ... }` block. You get a deadlock.

Do is look like your issue?

**Comment by Pitel** [comment]
Yes, you are probably right. I was finally able to write working test:

```kotlin
class SingleTest {
	private companion object {
		private val SINGLE = newFixedThreadPoolContext(1, "fixed") // Chnage to 2 to make it run
	}

	private val testAsync = GlobalScope.async(SINGLE, CoroutineStart.LAZY) { 10 }

	@Test
	fun test() {
		runBlocking(SINGLE) {
			runBlocking {
				testAsync.await()
			}
		}
	}
}
```

And there is probably not much to do to work around this, right?

**Comment by elizarov** [comment]
You can use `Dispatchers.Unconfined` for single-threaded tests. It does integrate with `runBlocking { ... }` to avoid deadlocks in the code like that. Its design is specifically geared towards tests.
