### ISSUE TITLE
Coroutine exception handler

### ISSUE THREAD

**Issue by simonext** [Kotlin/kotlinx.coroutines#986]
Hello ,

I use coroutine with vert.x web. And when i have some exception in my code like NPE, there is not catch by the the failure handler.
So i have create my own exception handler

````
/**
 * This class is use to corountine to handle each exception and manage it vertx fail
 */
class MyHandlerException(val ctx: RoutingContext) : CoroutineExceptionHandler {
    override val key = CoroutineExceptionHandler.Key
    override fun handleException(context: CoroutineContext, exception: Throwable) {
        //When this is an exception not generating by myself
        if (!exception.localizedMessage!!.matches("[0-9]+".toRegex())) {
            logApp(ctx, errorMessages = exception.localizedMessage)
            ctx.response().statusCode = 400
            ctx.fail(Exception("XXXXX"))
        } else {
            //When is own exception
            ctx.fail(exception)
        }
    }
}
````

And i have to launch my coroutine like this.

````
GlobalScope.launch(MyHandlerException(ctx)) {
...
}
````

I do not know if is the best solution.

I use the
````
<kotlin.version>1.3.11</kotlin.version> 
<vertx.version>3.6.2</vertx.version>
````
Thanks

Simon.

**Comment by elizarov** [comment]
Hello Simon. That is the supposed solution. However, I do recommend to use a structured concurrency in your code, don't use a `GlobalScope`, but explicitly define a scope for your coroutines:

```
val scope = CoroutineScope(Job()) + CoroutineExceptionHandler { ... }
```

Then, whenever you launch coroutine in your own scope:

```
scope.launch { ... }
```

Not only your code look shorted, but if you need to cancel your coroutines you can do `scope.cancel()`. You declare this scope as a part of some object with a life-time (like a user-connection), and cancel all of them when this object is destroyed. I assume that in your application this is going to be the same object that holds your `RoutingContext`.

Does it help?
