### ISSUE TITLE
Using `1.x` coroutines alongside `0.30.2` coroutines

### ISSUE THREAD

**Issue by ZakTaccardi** [Kotlin/kotlinx.coroutines#993]
I have a use case that requires me to upgrade my app's code to `1.x` coroutines (stable), while a 3rd party library I'm consuming internally depends on `0.30.2` coroutines. Is this possible to use these two simultaneously?

I'm currently getting the following exception at runtime when the 3rd party library's code is executed.

```kotlin
java.lang.NoClassDefFoundError: Failed resolution of: Lkotlinx/coroutines/experimental/CompletableDeferredKt;

```

After running `./gradlew :app:dependencies`, I see the following.

```
org.jetbrains.kotlinx:kotlinx-coroutines-core:0.30.2 -> 1.1.1
```

Because Gradle doesn't provide the ability to include two artifacts with the same maven coordinates, I think I'm out of luck here. Would it be possible to publish a legacy version of `0.30.2` so I could include it alongside `1.x` code?

**Comment by qwwdfsad** [comment]
>Would it be possible to publish a legacy version of `0.30.2` so I could include it alongside `1.x` code?

It is definitely possible but requires some effort. Before doing so (especially after 4 months since  1.0 release, so "partial migration" ship has sailed) could you please clarify what library are you using? Is it possible to upgrade this library instead if it is migrated to coroutines 1.x?

**Comment by ZakTaccardi** [comment]
The library has already upgraded to stable coroutines, but unfortunately this issue is blocking us from upgrading https://github.com/RedApparat/Fotoapparat/issues/340

We're an SDK, and our main client hasn't upgraded to AndroidX yet (and we don't want to force them to do so)

**Comment by elizarov** [comment]
The easy solution would be to download the old file as a file (.jar) and add it to your gradle problem as local file dependency. You can also hack gradle dependency resolution and performan a substitution of coordinate, but that's quite more involved.

**Comment by ZakTaccardi** [comment]
I haven't tried those solutions (but it seems like they would work). I just decided to upgrade to AndroidX and didn't encounter any issues with it running along the support library running.
