### ISSUE TITLE
typo in error message of fun `Publisher<T>.awaitOne()`

### ISSUE THREAD

**Issue by LiYing2010** [Kotlin/kotlinx.coroutines#995]
Source Code:
https://github.com/Kotlin/kotlinx.coroutines/blob/master/reactive/kotlinx-coroutines-reactive/src/Await.kt#L120

Error Message here is:
```
"More that one onNext value for $mode"
```

Is the word `"that"` a typo? Looks like the correct word is `"than"`

**Comment by qwwdfsad** [comment]
Thanks, fixed in develop
