### ISSUE TITLE
CoroutineExceptionHandler catch duplicated Exception

### ISSUE THREAD

**Issue by codingWz** [Kotlin/kotlinx.coroutines#996]
-Android
-Retrofit + Coroutine
-try to use CoroutineExceptionHandler to catch SockTimeoutException
problem: once SockTimeoutException is caught（server is manually shutdown for test）, every time  access to the network my app will get the same SockTimeoutException（server is restarted）

1. Simple loginActivity
```java
class LoginActivity : AppCompatActivity(), View.OnClickListener {
	private lateinit var mViewModel: LoginViewModel
	override fun onCreate(savedInstanceState: Bundle?) {
		super.onCreate(savedInstanceState)
		setContentView(com.tech.sf.usermodule.R.layout.activity_login)
		mViewModel = ViewModelProviders.of(this).get(LoginViewModel::class.java)
		loginButton.setOnClickListener(this)
	}

	override fun onClick(v: View) {
		when (v.id) {
			R.id.loginButton -> {
				val userName = userNameEdt.text.toString()
				val password = pwdEdt.text.toString()
				mViewModel.login(userName, password).observe(this, Observer { response ->
					if (response != null && response.success) {						
						Toast.makeText(this, response.data, Toast.LENGTH_SHORT).show()
					} else {						
						Toast.makeText(this, response?.errorMsg, Toast.LENGTH_SHORT).show()
					}
				})
			}
		}
	}

}
```
2.  login method in viewmodel
```java
fun login(userName: String, password: String): LiveData<Response<String?>> {
	val liveData = MutableLiveData<Response<String?>>()
	launchSafely(liveData) {
		val result = mLoginRepository.loginAsync(userName, password)
		liveData.postValue(result.await())
	}
	return liveData
}
```
3. extension function using CoroutineExceptionHandler to catch SockTimeoutException
```java
fun <T> CoroutineScope.launchSafely(
		liveData: MutableLiveData<Response<T?>>,
		block: suspend CoroutineScope.() -> Unit
): Job {
	val handler = CoroutineExceptionHandler { _, t ->
		val response: Response<T?> = Response(data = null, errorMsg = t.message!!, success = false)
		liveData.postValue(response)
	}
	return launch(handler, block = block)
}
```
4. loginAsync in repository
```java
private val userService: UserInterface = NetworkManager.retrofit.create(UserInterface::class.java)
fun loginAsync(userName: String, password: String): Deferred<Response<String?>> {
	val req = LoginReq(userName, password)
	return userService.loginAsync(req)
}
```
5. loginAsync method in apiInterface
```java
interface UserInterface {
	@POST("user/login")
        //implementation 'com.jakewharton.retrofit:retrofit2-kotlin-coroutines-adapter:0.9.2' as CallAdapter
	fun loginAsync(@Body loginReq: LoginReq): Deferred<Response<String?>>
}
```
After debug, I found the first time SocketTimeoutException is caught, the network method is invoked. Retry login , SocketTimeoutException is still caught but the network method is not even invoked, Exception is threw after `launch(handler, block = block)`

**Comment by elizarov** [comment]
Can you, please, show how your `ViewModel` class is implemented. I see that your `launchSafely` is defined as an extension on `CoroutineScope`, and so, since you are using it from your `ViewModel`, I assume that your `ViewModel` implements `CoroutineScope`.  But how?

**Comment by codingWz** [comment]
> Can you, please, show how your `ViewModel` class is implemented. I see that your `launchSafely` is defined as an extension on `CoroutineScope`, and so, since you are using it from your `ViewModel`, I assume that your `ViewModel` implements `CoroutineScope`. But how?

```
class UserViewModel: ViewModel, CoroutineScope {
    private val job = Job()
    override val coroutineContext: CoroutineContext
        get() = Dispatchers.Default + job

    override fun onCleared() {
        super.onCleared()
        job .cancel()
    }
}
```

**Comment by elizarov** [comment]
The `Job()` gets cancelled on the first error and further coroutines fail with this error. You can replace `Job()` with `SupervisorJob()` or use the following shortcut via `CoroutineScope` constructor:

```
class UserViewModel: ViewModel, CoroutineScope by CoroutineScope(Dispatchers.Default) {
    override fun onCleared() {
        super.onCleared()
        cancel()
    }
}
```

Does it help?

**Comment by codingWz** [comment]
It works！
Thanks

**Comment by ahulyk** [comment]
@elizarov thank you!
What is the actual difference between `SupervisorJob()` and `CoroutineScope` constructor?

**Comment by gildor** [comment]
I'm a bit confused how https://github.com/Kotlin/kotlinx.coroutines/issues/996#issuecomment-468890079 different from https://github.com/Kotlin/kotlinx.coroutines/issues/996#issuecomment-468873254

As I can see both versions do the same, but Roman's code is just more concise, but still implicitly creates `Job()` under the hood, but as I understand from context `SupervisorJob()` should be used

**Comment by elizarov** [comment]
Oops, indeed. `CoroutineScope by CoroutineScope(Dispatchers.Default)` creates a `Job()`. It should be `CoroutineScope by MainScope() + Dispatchers.Default`. That kind of highlights that we still have some naming issues w.r.t to `Job`/`SupervisorJob`.

**Comment by ahulyk** [comment]
@elizarov Thank you for clarification! 
`CoroutineScope by MainScope()` creates `SupervisorJob` under the hood - so is works good.
Btw, naming convention is not super clear here :( 
Name `MainScope()` fits in context of Android. But does not fit  for general context.

**Comment by gildor** [comment]
@ahulyk `MainScope` fits any context where there is some Main thread, even now it supported by Android, JavaFX and Swing and also supported by JS and Native (but fallback to Default dispatcher there) so it's not something Android specific.
And naming is caused by very particular use case: If you need a scope that uses Main dispatcher by default, most probably you use it in some UI component and in such cases, you most probably need SupervisorJob because you manage errors yourself and do not want close scope in case of error of one of the child coroutines to simplify usage of this common use case MainScope is created
